"use client";

import React, { useState, useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { PageHeader } from '@/components/shared';
import { Atom } from 'lucide-react';

interface CadmiumAlloyRecord {
  id: string;
  batchNo: string;
  city: string;
  manufacturer: string;
  alloyGrade: string;
  application: string;
  cadmiumPercent: number;
  meltingPointC: number;
  investmentCr: number;
  status: string;
  priority: string;
  origin: string;
  destination: string;
  shipDate: string;
  transitDays: number;
  zone: string;
  remarks: string;
}

const cadmiumAlloyRecords: CadmiumAlloyRecord[] = [
  { id: 'CDA-0001', batchNo: 'CDA-B2401', city: 'Mumbai', manufacturer: 'Hindustan Zinc', alloyGrade: 'Cd-Ag 70/30 Brazing', application: 'Aerospace Brazing (HAL)', cadmiumPercent: 70.0, meltingPointC: 335, investmentCr: 480, status: 'Delivered', priority: 'Critical', origin: 'Hindustan Zinc Udaipur (RJ)', destination: 'HAL Bengaluru (KA)', shipDate: '2026-07-15', transitDays: 3, zone: 'West', remarks: 'Cd-Ag 70/30 brazing alloy for HAL Tejas Mk2 fuel system pipe joint &#8594; 70% Cd 30% Ag &#8594; &#8377;480Cr for 0.8 tonnes &#8594; India &#8377;14,400Cr aero Cd &#8594; HAL 123 Tejas &#8594; 335&#176;C &#8594; &#8594; silver &#8594; &#8594; 450&#176;C service &#8594; &#8594; brazing' },
  { id: 'CDA-0002', batchNo: 'CDA-B2402', city: 'Hyderabad', manufacturer: 'DRDO DMRL', alloyGrade: 'Cd-Bi 40/60 Fusible', application: 'Thermal Fuse (BEL)', cadmiumPercent: 40.0, meltingPointC: 95, investmentCr: 320, status: 'Delivered', priority: 'High', origin: 'DRDO DMRL Hyderabad (TG)', destination: 'BEL Ghaziabad (UP)', shipDate: '2026-07-16', transitDays: 2, zone: 'South', remarks: 'Cd-Bi 40/60 fusible alloy for BEL military fire suppressor thermal link fuse &#8594; 40% Cd 60% Bi &#8594; &#8377;320Cr for 0.5 tonnes &#8594; India &#8377;9,600Cr defence Cd &#8594; BEL 50K fuses &#8594; 95&#176;C &#8594; &#8594; Wood metal &#8594; &#8594; 72&#176;C &#8594; &#8594; link' },
  { id: 'CDA-0003', batchNo: 'CDA-B2403', city: 'Bengaluru', manufacturer: 'Tata Advanced Materials', alloyGrade: 'Cd-Cu 95/5 Bearing', application: 'Marine Propeller Bush (GRSE)', cadmiumPercent: 95.0, meltingPointC: 320, investmentCr: 390, status: 'Delivered', priority: 'High', origin: 'Tata Advanced Materials Bengaluru (KA)', destination: 'GRSE Kolkata (WB)', shipDate: '2026-07-17', transitDays: 3, zone: 'South', remarks: 'Cd-Cu 95/5 for GRSE naval frigate propeller shaft bearing bush &#8594; 95% Cd 5% Cu &#8594; &#8377;390Cr for 2 tonnes &#8594; India &#8377;11,700Cr naval Cd &#8594; GRSE 12 warships &#8594; 320&#176;C &#8594; &#8594; anti-seize &#8594; &#8594; salt water &#8594; &#8594; bush' },
  { id: 'CDA-0004', batchNo: 'CDA-B2404', city: 'Pune', manufacturer: 'Bharat Forge', alloyGrade: 'Cd-Ni 85/15 Plating', application: 'Torque Tube (BHEL)', cadmiumPercent: 85.0, meltingPointC: 310, investmentCr: 340, status: 'Delivered', priority: 'High', origin: 'Bharat Forge Pune (MH)', destination: 'BHEL Hyderabad (TG)', shipDate: '2026-07-18', transitDays: 1, zone: 'West', remarks: 'Cd-Ni alloy electroplate for BHEL steam turbine torque tube thread &#8594; 85% Cd 15% Ni &#8594; &#8377;340Cr for 0.3 tonnes &#8594; India &#8377;10,200Cr power Cd &#8594; BHEL 200 turbines &#8594; 310&#176;C &#8594; &#8594; lubricity &#8594; &#8594; 540&#176;C &#8594; &#8594; thread' },
  { id: 'CDA-0005', batchNo: 'CDA-B2405', city: 'Chennai', manufacturer: 'IGCAR', alloyGrade: 'Cd 99.99% Control Rod', application: 'Reactor Rod (NPCIL)', cadmiumPercent: 99.99, meltingPointC: 321, investmentCr: 620, status: 'Delivered', priority: 'Critical', origin: 'IGCAR Kalpakkam (TN)', destination: 'NPCIL Tarapur (MH)', shipDate: '2026-07-19', transitDays: 2, zone: 'South', remarks: 'Pure Cd sheath for NPCIL PHWR control rod neutron absorber &#8594; 99.99% Cd &#8594; &#8377;620Cr for 1 tonne &#8594; India &#8377;18,600Cr nuclear Cd &#8594; NPCIL 22 reactors &#8594; 321&#176;C &#8594; &#8594; B-10 &#8594; &#8594; thermal &#8594; &#8594; Cd-In-Ag &#8594; rod' },
  { id: 'CDA-0006', batchNo: 'CDA-B2406', city: 'Ahmedabad', manufacturer: 'Gujarat Cadmium Tech', alloyGrade: 'Cd-Pb 70/30 Cable', application: 'Overhead Power Cable (Torrent Power)', cadmiumPercent: 70.0, meltingPointC: 250, investmentCr: 270, status: 'Delivered', priority: 'Medium', origin: 'Gujarat Cadmium Tech Ahmedabad (GJ)', destination: 'Torrent Power Ahmedabad (GJ)', shipDate: '2026-07-20', transitDays: 1, zone: 'West', remarks: 'Cd-Pb 70/30 alloy for Torrent Power 33kV overhead transmission cable sheath &#8594; 70% Cd 30% Pb &#8594; &#8377;270Cr for 3 tonnes &#8594; India &#8377;8,100Cr power Cd &#8594; Torrent 5000 km &#8594; 250&#176;C &#8594; &#8594; corrosion &#8594; &#8594; outdoor &#8594; &#8594; sheath' },
  { id: 'CDA-0007', batchNo: 'CDA-B2407', city: 'Jaipur', manufacturer: 'Rajasthan Cadmium Corp', alloyGrade: 'Cd-Sn 80/20 Solder', application: 'Electronics Solder (Dixon)', cadmiumPercent: 80.0, meltingPointC: 230, investmentCr: 350, status: 'Delivered', priority: 'High', origin: 'Rajasthan Cadmium Corp Jaipur (RJ)', destination: 'Dixon Noida (UP)', shipDate: '2026-07-21', transitDays: 2, zone: 'North', remarks: 'Cd-Sn 80/20 solder for Dixon LED TV motherboard high-reliability solder joints &#8594; 80% Cd 20% Sn &#8594; &#8377;350Cr for 0.5 tonnes &#8594; India &#8377;10,500Cr electronics Cd &#8594; Dixon 1M boards &#8594; 230&#176;C &#8594; &#8594; fatigue &#8594; &#8594; &#8594; 50K cycle &#8594; &#8594; joint' },
  { id: 'CDA-0008', batchNo: 'CDA-B2408', city: 'Bhubaneswar', manufacturer: 'NALCO', alloyGrade: 'Cd-Ag 65/35 Contact', application: 'Relay Contact (BHEL)', cadmiumPercent: 65.0, meltingPointC: 340, investmentCr: 310, status: 'Delivered', priority: 'Medium', origin: 'NALCO Bhubaneswar (OD)', destination: 'BHEL Bhopal (MP)', shipDate: '2026-07-22', transitDays: 3, zone: 'East', remarks: 'Cd-Ag 65/35 for BHEL HVDC circuit breaker relay contact &#8594; 65% Cd 35% Ag &#8594; &#8377;310Cr for 0.4 tonnes &#8594; India &#8377;9,300Cr power Cd &#8594; BHEL 150 breakers &#8594; 340&#176;C &#8594; &#8594; low resistance &#8594; &#8594; 800A &#8594; &#8594; contact' },
  { id: 'CDA-0009', batchNo: 'CDA-B2409', city: 'Coimbatore', manufacturer: 'Tamil Nadu Cadmium Corp', alloyGrade: 'Cd 99.95% Evaporation', application: 'Thin Film Coating (Tata Steel)', cadmiumPercent: 99.95, meltingPointC: 321, investmentCr: 430, status: 'Delivered', priority: 'High', origin: 'Tamil Nadu Cadmium Coimbatore (TN)', destination: 'Tata Steel Jamshedpur (JH)', shipDate: '2026-07-23', transitDays: 3, zone: 'South', remarks: 'Cd evaporation pellet for Tata Steel anti-corrosion PVD coating on automotive sheet &#8594; 99.95% Cd &#8594; &#8377;430Cr for 0.2 tonnes &#8594; India &#8377;12,900Cr steel Cd &#8594; Tata 15 MT &#8594; 321&#176;C &#8594; &#8594; thermal &#8594; &#8594; 5um &#8594; &#8594; PVD' },
  { id: 'CDA-0010', batchNo: 'CDA-B2410', city: 'Surat', manufacturer: 'Gujarat Cadmium Products', alloyGrade: 'Cd-Zn 90/10 Anode', application: 'Sacrificial Anode (Reliance)', cadmiumPercent: 90.0, meltingPointC: 300, investmentCr: 260, status: 'Delivered', priority: 'Medium', origin: 'Gujarat Cadmium Products Surat (GJ)', destination: 'Reliance Jamnagar (GJ)', shipDate: '2026-07-24', transitDays: 1, zone: 'West', remarks: 'Cd-Zn 90/10 sacrificial anode for Reliance offshore platform sea water ballast tank &#8594; 90% Cd 10% Zn &#8594; &#8377;260Cr for 2 tonnes &#8594; India &#8377;7,800Cr marine Cd &#8594; Reliance 20 platforms &#8594; 300&#176;C &#8594; &#8594; cathodic &#8594; &#8594; &#8594; &#8594; &#8594; anode' },
  { id: 'CDA-0011', batchNo: 'CDA-B2411', city: 'Guwahati', manufacturer: 'Assam Cadmium Metals', alloyGrade: 'Cd-Bi-Pb 50/30/20 Eutectic', application: 'Fire Sprinkler (Godrej)', cadmiumPercent: 50.0, meltingPointC: 91, investmentCr: 210, status: 'Delivered', priority: 'Medium', origin: 'Assam Cadmium Guwahati (AS)', destination: 'Godrej Mumbai (MH)', shipDate: '2026-07-25', transitDays: 4, zone: 'East', remarks: 'Cd-Bi-Pb eutectic for Godrej fire sprinkler glass bulb fusible element &#8594; 50% Cd 30% Bi 20% Pb &#8594; &#8377;210Cr for 0.3 tonnes &#8594; India &#8377;6,300Cr safety Cd &#8594; Godrej 100K heads &#8594; 91&#176;C &#8594; &#8594; eutectic &#8594; &#8594; 68&#176;C &#8594; &#8594; sprinkler' },
  { id: 'CDA-0012', batchNo: 'CDA-B2412', city: 'Lucknow', manufacturer: 'UP Cadmium Industries', alloyGrade: 'Cd-Sb 95/5 Bearing', application: 'Engine Bearing (Cummins India)', cadmiumPercent: 95.0, meltingPointC: 305, investmentCr: 420, status: 'Delayed', priority: 'High', origin: 'UP Cadmium Industries Lucknow (UP)', destination: 'Cummins Pune (MH)', shipDate: '2026-07-01', transitDays: 27, zone: 'North', remarks: 'Cd-Sb 95/5 alloy for Cummins heavy diesel engine main bearing overlay &#8594; 95% Cd 5% Sb &#8594; &#8377;420Cr for 1.2 tonnes &#8594; monsoon delay &#8594; India &#8377;12,600Cr auto Cd &#8594; Cummins 200K engines &#8594; 305&#176;C &#8594; &#8594; embeddability &#8594; &#8594; 400&#176;C &#8594; &#8594; bearing' },
  { id: 'CDA-0013', batchNo: 'CDA-B2413', city: 'Noida', manufacturer: 'SAIL', alloyGrade: 'Cd-Ag-Cu 75/20/5 Brazing', application: 'Condenser Joint (Thermax)', cadmiumPercent: 75.0, meltingPointC: 345, investmentCr: 330, status: 'Delivered', priority: 'High', origin: 'SAIL Rourkela (OD)', destination: 'Thermax Pune (MH)', shipDate: '2026-07-26', transitDays: 3, zone: 'East', remarks: 'Cd-Ag-Cu ternary for Thermax VRF condenser copper-to-brass brazed joint &#8594; 75% Cd 20% Ag 5% Cu &#8594; &#8377;330Cr for 0.6 tonnes &#8594; India &#8377;9,900Cr HVAC Cd &#8594; Thermax 500 units &#8594; 345&#176;C &#8594; &#8594; ternary &#8594; &#8594; 400&#176;C &#8594; &#8594; joint' },
  { id: 'CDA-0014', batchNo: 'CDA-B2414', city: 'Bhopal', manufacturer: 'BHEL', alloyGrade: 'Cd-In-Ag 80/15/5 Rod', application: 'Nuclear Control Blade (NPCIL)', cadmiumPercent: 80.0, meltingPointC: 295, investmentCr: 560, status: 'Delivered', priority: 'Critical', origin: 'BHEL Bhopal (MP)', destination: 'NPCIL Kakrapar (GJ)', shipDate: '2026-07-27', transitDays: 2, zone: 'North', remarks: 'Cd-In-Ag 80/15/5 absorber rod for NPCIL PHWR secondary shutdown system &#8594; 80% Cd 15% In 5% Ag &#8594; &#8377;560Cr for 1.5 tonnes &#8594; India &#8377;16,800Cr nuclear Cd &#8594; NPCIL 22 reactors &#8594; 295&#176;C &#8594; &#8594; neutron &#8594; &#8594; &#8594; &#8594; shutdown &#8594; blade' }
];

const tabs = ['Dashboard', 'Registry', 'Analytics', 'Insights'] as const;
type Tab = typeof tabs[number];
const priorityColors: Record<string, string> = { Critical: 'bg-red-100 text-red-800', High: 'bg-amber-100 text-amber-800', Medium: 'bg-green-100 text-green-800', Low: 'bg-slate-100 text-slate-600' };
const delayedSet = new Set(cadmiumAlloyRecords.filter(r => r.status === 'Delayed').map(r => r.id));

export default function CadmiumAlloyLogisticsView() {
  const [activeTab, setActiveTab] = useState<Tab>('Dashboard');
  const [search, setSearch] = useState('');
  const [filters, setFilters] = useState<Record<string, string[]>>({});
  const toggleFilter = (k: string, v: string) => { setFilters(p => { const s = { ...p }; const a = s[k] || []; const i = a.indexOf(v); if (i > -1) { a.splice(i, 1); if (!a.length) delete s[k]; } else s[k] = [...a, v]; return s; }); };
  const filtered = useMemo(() => {
    let d = cadmiumAlloyRecords;
    if (search) { const q = search.toLowerCase(); d = d.filter(r => r.id.toLowerCase().includes(q) || r.batchNo.toLowerCase().includes(q) || r.alloyGrade.toLowerCase().includes(q) || r.application.toLowerCase().includes(q) || r.city.toLowerCase().includes(q) || r.manufacturer.toLowerCase().includes(q)); }
    Object.entries(filters).forEach(([k, vs]) => { if (vs.length) d = d.filter(r => { const v = String((r as unknown as Record<string, unknown>)[k] ?? ''); return vs.some(x => v.toLowerCase().includes(x.toLowerCase())); }); });
    return d;
  }, [search, filters]);
  const totalCr = filtered.reduce((s: number, r) => s + r.investmentCr, 0);
  const avgCd = filtered.length ? filtered.reduce((s: number, r) => s + r.cadmiumPercent, 0) / filtered.length : 0;
  const delayedCount = filtered.filter(r => r.status === 'Delayed').length;

  return (
    <div className="space-y-6">
      <PageHeader title="Cadmium Alloy Logistics" description="Indian cadmium alloy supply chain tracking for aerospace brazing, nuclear control rods, marine bearings, electroplating, power cables, electronics solder and thermal fuse sectors" />
      <div className="flex gap-2 border-b">
        {tabs.map(t => (<button key={t} onClick={() => setActiveTab(t)} className={`px-4 py-2 text-sm font-medium ${activeTab === t ? 'border-b-2 border-amber-500 text-amber-700' : 'text-muted-foreground hover:text-foreground'}`}>{t}</button>))}
      </div>
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card><CardContent><div className="text-2xl font-bold text-amber-600">{filtered.length}</div><div className="text-xs text-muted-foreground">Total Shipments</div></CardContent></Card>
        <Card><CardContent><div className="text-2xl font-bold text-amber-600">&#8377;{totalCr.toLocaleString()} Cr</div><div className="text-xs text-muted-foreground">Total Investment</div></CardContent></Card>
        <Card><CardContent><div className="text-2xl font-bold text-amber-600">{avgCd.toFixed(1)}%</div><div className="text-xs text-muted-foreground">Avg Cd Content</div></CardContent></Card>
        <Card><CardContent><div className="text-2xl font-bold text-red-500">{delayedCount}</div><div className="text-xs text-muted-foreground">Delayed Shipments</div></CardContent></Card>
      </div>
      {(activeTab === 'Dashboard' || activeTab === 'Registry') && (
        <div className="space-y-4">
          <div className="flex flex-wrap gap-2">
            <input placeholder="Search ID, grade, application, city..." value={search} onChange={e => setSearch(e.target.value)} className="border rounded-md px-3 py-1.5 text-sm flex-1 min-w-48" />
            {['status', 'priority', 'zone'].map(f => { const opts = [...new Set(cadmiumAlloyRecords.map(r => (r as unknown as Record<string, unknown>)[f] as string))]; return (<div key={f} className="flex flex-wrap gap-1">{opts.map(o => (<Badge key={o} variant={(filters[f] || []).includes(o) ? 'default' : 'outline'} className="cursor-pointer text-xs" onClick={() => toggleFilter(f, o)}>{o}</Badge>))}</div>); })}
          </div>
          <div className="rounded-md border"><div className="max-h-96 overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-background"><tr><th className="p-2 text-left">ID</th><th className="p-2 text-left">Batch</th><th className="p-2 text-left">Grade</th><th className="p-2 text-left">Application</th><th className="p-2 text-right">Cd%</th><th className="p-2 text-right">&#8377;Cr</th><th className="p-2 text-left">Status</th></tr></thead><tbody>{filtered.map(r => (<tr key={r.id} className={`border-t ${delayedSet.has(r.id) ? 'border-l-4 border-l-red-500 bg-red-50/30' : ''}`}><td className="p-2">{r.id}</td><td className="p-2">{r.batchNo}</td><td className="p-2">{r.alloyGrade}</td><td className="p-2">{r.application}</td><td className="p-2 text-right">{r.cadmiumPercent}</td><td className="p-2 text-right">{r.investmentCr}</td><td className="p-2"><Badge variant={r.status === 'Delivered' ? 'default' : 'destructive'}>{r.status}</Badge></td></tr>))}</tbody></table></div></div>
        </div>
      )}
      {(activeTab === 'Dashboard' || activeTab === 'Analytics') && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <Card><CardHeader><CardTitle className="text-sm">Investment by Application</CardTitle></CardHeader><CardContent><div className="space-y-2">{(Object.entries(filtered.reduce((m, r) => { m[r.application] = (m[r.application] || 0) + r.investmentCr; return m }, {} as Record<string, number>)) as [string, number][]).sort((a, b) => b[1] - a[1]).slice(0, 7).map(([a, v]) => (<div key={a} className="flex justify-between text-sm"><span>{a}</span><span className="font-medium">&#8377;{v}Cr</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Shipments by Zone</CardTitle></CardHeader><CardContent><div className="space-y-2">{(Object.entries(filtered.reduce((m, r) => { m[r.zone] = (m[r.zone] || 0) + 1; return m }, {} as Record<string, number>)) as [string, number][]).sort((a, b) => b[1] - a[1]).map(([z, c]) => (<div key={z} className="flex justify-between text-sm"><span>{z}</span><span className="font-medium">{c}</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Top Routes by Value</CardTitle></CardHeader><CardContent><div className="space-y-2">{filtered.sort((a, b) => b.investmentCr - a.investmentCr).slice(0, 7).map(r => (<div key={r.id} className="flex justify-between text-sm"><span>{r.origin.split('(')[0]} &#8594; {r.destination.split('(')[0]}</span><span className="font-medium">&#8377;{r.investmentCr}Cr</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Nuclear and Defence</CardTitle></CardHeader><CardContent><div className="space-y-2">{filtered.filter(r => r.application.toLowerCase().includes('nuclear') || r.application.toLowerCase().includes('npcil') || r.application.toLowerCase().includes('igcar') || r.application.toLowerCase().includes('drdo') || r.application.toLowerCase().includes('defence') || r.application.toLowerCase().includes('hal') || r.application.toLowerCase().includes('bel') || r.application.toLowerCase().includes('naval')).sort((a, b) => b.investmentCr - a.investmentCr).map(r => (<div key={r.id} className="flex justify-between text-sm"><span>{r.alloyGrade}</span><span className="font-medium">&#8377;{r.investmentCr}Cr</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">By Priority</CardTitle></CardHeader><CardContent><div className="space-y-2">{Object.entries(filtered.reduce((m, r) => { m[r.priority] = (m[r.priority] || 0) + 1; return m }, {} as Record<string, number>)).map(([p, c]) => (<div key={p} className="flex justify-between text-sm"><span className={priorityColors[p] || ''}>{p}</span><span className="font-medium">{c}</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Cd Content Distribution</CardTitle></CardHeader><CardContent><div className="space-y-2">{[{ l: 'Ultra-High (90%+)', f: filtered.filter(r => r.cadmiumPercent >= 90).length }, { l: 'High (70-90%)', f: filtered.filter(r => r.cadmiumPercent >= 70 && r.cadmiumPercent < 90).length }, { l: 'Medium (50-70%)', f: filtered.filter(r => r.cadmiumPercent >= 50 && r.cadmiumPercent < 70).length }, { l: 'Low (&lt;50%)', f: filtered.filter(r => r.cadmiumPercent < 50).length }].map(b => (<div key={b.l} className="flex justify-between text-sm"><span>{b.l}</span><span className="font-medium">{b.f}</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Top Manufacturers</CardTitle></CardHeader><CardContent><div className="space-y-2">{(Object.entries(filtered.reduce((m, r) => { m[r.manufacturer] = (m[r.manufacturer] || 0) + r.investmentCr; return m }, {} as Record<string, number>)) as [string, number][]).sort((a, b) => b[1] - a[1]).slice(0, 7).map(([m, v]) => (<div key={m} className="flex justify-between text-sm"><span>{m}</span><span className="font-medium">&#8377;{v}Cr</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Avg Transit Days</CardTitle></CardHeader><CardContent><div className="space-y-2">{filtered.length ? (Object.entries(filtered.reduce((m, r) => { m[r.zone] = (m[r.zone] || [] as number[]).concat(r.transitDays); return m }, {} as Record<string, number[]>)) as [string, number[]][]).map(([z, d]) => (<div key={z} className="flex justify-between text-sm"><span>{z}</span><span className="font-medium">{(d.reduce((s, n) => s + n, 0) / d.length).toFixed(1)}d</span></div>)) : []}</div></CardContent></Card>
        </div>
      )}
      {(activeTab === 'Dashboard' || activeTab === 'Insights') && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Card><CardContent><div className="text-sm font-medium text-amber-600 mb-2">HAL Cd-Ag Brazing Alloy</div><div className="text-xs text-muted-foreground">HAL using Cd-Ag 70/30 for Tejas Mk2 fuel and hydraulic system brazed joints. Cd-Ag flows at 335&#176;C providing 15% lower brazing temperature than Ag-Cu reducing thermal distortion on thin-wall titanium. Hindustan Zinc developing domestic Cd-Ag strip under &#8377;2,200Cr DRDO programme replacing US Handy-Harman import.</div></CardContent></Card>
          <Card><CardContent><div className="text-sm font-medium text-amber-600 mb-2">NPCIL Cd-In-Ag Control Rod</div><div className="text-xs text-muted-foreground">BHEL manufacturing Cd-In-Ag 80/15/5 absorber rod for NPCIL PHWR secondary shutdown system. Cd provides high thermal neutron cross-section (2450 barn), In adds ductility and Ag prevents corrosion. India qualifying all 22 reactor rods under &#8377;4,500Cr nuclear safety upgrade programme.</div></CardContent></Card>
          <Card><CardContent><div className="text-sm font-medium text-amber-600 mb-2">GRSE Cd-Cu Marine Propeller Bearing</div><div className="text-xs text-muted-foreground">GRSE deploying Cd-Cu 95/5 bearing bush for Indian naval frigate propeller shaft operating in salt water at 200 RPM. Cd provides exceptional anti-seize and embedment properties absorbing hard particles. Tata Advanced Materials qualifying Cd-Cu strip rolling under &#8377;1,800Cr Make in India naval programme.</div></CardContent></Card>
          <Card><CardContent><div className="text-sm font-medium text-amber-600 mb-2">BEL Cd-Bi Thermal Fuse</div><div className="text-xs text-muted-foreground">BEL producing Cd-Bi 40/60 Wood metal fusible link for military vehicle and shipboard fire suppression systems. Cd-Bi eutectic at 95&#176;C provides precise thermal activation replacing mechanical springs. DRDO DMRL developing refined Cd-Bi-Pb ternary for wider 72-91&#176;C range.</div></CardContent></Card>
        </div>
      )}
    </div>
  );
}
