"use client";
import { useState } from "react";
import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, Legend } from "recharts";
import { PageHeader } from "@/components/shared/page-header";
import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar";
import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb";

const COLORS = ["#065f46", "#047857", "#059669", "#10b981", "#34d399", "#064e3b", "#022c22", "#6ee7b7"];
const FACILITIES = ["Serum Institute Pune", "Biocon Bengaluru Biologics", "Dr Reddys Hyderabad", "Cipla Mumbai Formulation", "Zydus Ahmedabad API", "Panacea Biotec New Delhi", "Bharat Biotech Hyderabad", "Emcure Pune Vaccines"];
const CATEGORIES = ["Vaccine Vials 2-8C", "Insulin Pen Cold Chain", "Biologic mAb 2-8C", "Blood Plasma Frozen", "API Temperature Ctrl", "Clinical Trial Kit", "Diagnostic Reagent", "Organ Transport"];
const SHIPMENT_STATUSES = ["Cold Room Validated", "Reefer Truck Moving", "Cold Chain Hub Transfer", "Temperature Excursion Alert", "Customs Bio-Security Hold", "Delivered Hospital Pharmacy"];
const ZONES = ["North India Pharma Belt", "West India API Hub", "South India Biologics", "East India Distribution", "Central India Formulation", "Gulf Export Corridor"];
const MODES = ["Reefer Truck -20 to 8C", "Cold Box Passive 72h", "Air Cargo Temp Ctrl",("Reefer Rail Container"), "Ambulance Organ Escort", "Drone Last-Mile 2kg"];
const TABS = ["Dashboard", "Shipment Registry", "Pharma Analytics", "Insights"];

const SC: Record<string, string> = { green: "bg-green-100 text-green-700", amber: "bg-amber-100 text-amber-700", red: "bg-red-100 text-red-700", blue: "bg-blue-100 text-blue-700", slate: "bg-slate-100 text-slate-600", orange: "bg-orange-100 text-orange-700" };
const statusColor: Record<string, string> = { "Cold Room Validated": "green", "Reefer Truck Moving": "blue", "Cold Chain Hub Transfer": "amber", "Temperature Excursion Alert": "red", "Customs Bio-Security Hold": "orange", "Delivered Hospital Pharmacy": "green" };

function ri(min: number, max: number, value: number) { return Math.min(max, Math.max(min, value)); }

const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const monthlyShipments = Array.from({ length: 12 }, (_, i) => ({ m: MO[i], vaccine: ri(15, 40, 26 + Math.sin(i * 0.5) * 8), insulin: ri(8, 20, 14 + Math.cos(i * 0.6) * 3), biologic: ri(5, 15, 9 + Math.sin(i * 0.7) * 3), plasma: ri(2, 8, 5 + Math.cos(i * 0.8) * 2) }));
const categoryDist = [{ n: "Vaccine Vials", v: 32 }, { n: "Insulin Cold Chain", v: 18 }, { n: "Biologic mAb", v: 16 }, { n: "Blood Plasma", v: 12 }, { n: "API Temperature", v: 10 }, { n: "Clinical Trial", v: 6 }, { n: "Diagnostic", v: 4 }, { n: "Organ Transport", v: 2 }];
const complianceRate = Array.from({ length: 12 }, (_, i) => ({ m: MO[i], actual: +(ri(96, 99.5, 98 + Math.sin(i * 0.4) * 0.8)).toFixed(1), target: 99.0 }));
const facilityPerf = FACILITIES.slice(0, 6).map(f => ({ n: f.split(" ").slice(0, 1).join(" "), v: +ri(90, 99.5, 96 + Math.random() * 2).toFixed(0) }));

interface ShipmentRecord { id: string; batchNo: string; facility: string; zone: string; category: string; description: string; weight: number; unit: string; shipper: string; consignee: string; mode: string; origin: string; destination: string; shipDate: string; etaDate: string; transitDays: number; valueLakhs: number; tempRange: string; status: string; remarks: string; }

const records: ShipmentRecord[] = [
  { id: "CCL-0001", batchNo: "BATCH-SII/COV-2025/07-A081", facility: "Serum Institute Pune", zone: "West India API Hub", category: "Vaccine Vials 2-8C", description: "Covid-19 Covishield 50K Doses Batch-A081", weight: 120, unit: "kg", shipper: "Serum Institute of India", consignee: "MOHFW Delhi Distribution", mode: "Reefer Truck -20 to 8C", origin: "SII Pune Cold Storage", destination: "Central Vaccine Store Delhi", shipDate: "2025-07-08", etaDate: "2025-07-09", transitDays: 1, valueLakhs: 75, tempRange: "2-8C", status: "Reefer Truck Moving", remarks: "Covishield 50K doses SII Pune to Delhi CVS reefer truck with GPS temp logger" },
  { id: "CCL-0002", batchNo: "BATCH-BIOCON/ITUX-2025/07-B445", facility: "Biocon Bengaluru Biologics", zone: "South India Biologics", category: "Biologic mAb 2-8C", description: "Adalimumab Biosimilar 2,000 Vials Alzumab", weight: 60, unit: "kg", shipper: "Biocon Biologics", consignee: "Apollo Hospital Chennai", mode: "Cold Box Passive 72h", origin: "Biocon Bio-Manufacturing", destination: "Apollo Chennai Pharmacy", shipDate: "2025-07-10", etaDate: "2025-07-10", transitDays: 0, valueLakhs: 320, tempRange: "2-8C", status: "Cold Room Validated", remarks: "Adalimumab 2K vials cold box passive Bengaluru to Chennai validated 2-8C" },
  { id: "CCL-0003", batchNo: "BATCH-DRREDDY/INS-2025/07-C334", facility: "Dr Reddys Hyderabad", zone: "South India Biologics", category: "Insulin Pen Cold Chain", description: "Insulin Glargine 10,000 Pens Re-Used", weight: 45, unit: "kg", shipper: "Dr Reddys Laboratories", consignee: "Fortis Hospital Mumbai", mode: "Reefer Truck -20 to 8C", origin: "Dr Reddys API Plant", destination: "Fortis Mumbai Central", shipDate: "2025-07-09", etaDate: "2025-07-10", transitDays: 1, valueLakhs: 85, tempRange: "2-8C", status: "Reefer Truck Moving", remarks: "Insulin glargine 10K pens Hyderabad to Mumbai Fortis reefer continuous monitoring" },
  { id: "CCL-0004", batchNo: "BATCH-CIPLA/API-2025/07-D556", facility: "Cipla Mumbai Formulation", zone: "West India API Hub", category: "API Temperature Ctrl", description: "Remdesivir API 200kg Temperature Controlled", weight: 200, unit: "kg", shipper: "Cipla API Division", consignee: "Hetero Drugs Hyderabad", mode: "Reefer Truck -20 to 8C", origin: "Cipla Mumbai API Plant", destination: "Hetero Formulation Hyderabad", shipDate: "2025-07-08", etaDate: "2025-07-09", transitDays: 1, valueLakhs: 180, tempRange: "15-25C", status: "Cold Room Validated", remarks: "Remdesivir API 200kg Mumbai to Hyderabad 15-25C controlled reefer truck" },
  { id: "CCL-0005", batchNo: "BATCH-BHARAT/BBV-2025/07-E778", facility: "Bharat Biotech Hyderabad", zone: "South India Biologics", category: "Vaccine Vials 2-8C", description: "Rotavirus Vaccine 80K Doses Rotavac", weight: 200, unit: "kg", shipper: "Bharat Biotech International", consignee: "UNICEF Supply Division", mode: "Air Cargo Temp Ctrl", origin: "BBI Hyderabad Campus", destination: "UNICEF Copenhagen Warehouse", shipDate: "2025-07-07", etaDate: "2025-07-09", transitDays: 2, valueLakhs: 240, tempRange: "2-8C", status: "Customs Bio-Security Hold", remarks: "Rotavac 80K doses Hyderabad to UNICEF Copenhagen air cargo customs bio-hold" },
  { id: "CCL-0006", batchNo: "BATCH-PANACEA/CTK-2025/07-F223", facility: "Panacea Biotec New Delhi", zone: "North India Pharma Belt", category: "Clinical Trial Kit", description: "Phase-III Trial Kit 500-Patient Malaria", weight: 350, unit: "kg", shipper: "Panacea Biotec", consignee: "ICMR Delhi Trial Site", mode: "Reefer Truck -20 to 8C", origin: "Panacea Biotec Delhi", destination: "ICMR Headquarters New Delhi", shipDate: "2025-07-10", etaDate: "2025-07-10", transitDays: 0, valueLakhs: 45, tempRange: "2-8C", status: "Delivered Hospital Pharmacy", remarks: "Phase-III malaria trial kit 500 patients Panacea to ICMR Delhi delivered" },
  { id: "CCL-0007", batchNo: "BATCH-ZYDUS/API-2025/07-G112", facility: "Zydus Ahmedabad API", zone: "West India API Hub", category: "API Temperature Ctrl", description: "Sorbitol Excipient 500kg Pharma Grade", weight: 500, unit: "kg", shipper: "Zydus Cadila Healthcare", consignee: "Mankind Pharma New Delhi", mode: "Reefer Rail Container", origin: "Zydus API Works Ahmedabad", destination: "Mankind Plant Paonta Sahib", shipDate: "2025-07-09", etaDate: "2025-07-11", transitDays: 2, valueLakhs: 12, tempRange: "15-25C", status: "Reefer Truck Moving", remarks: "Sorbitol 500kg pharma grade Ahmedabad to Paonta Sahib reefer rail container" },
  { id: "CCL-0008", batchNo: "BATCH-SII/FLU-2025/07-H445", facility: "Serum Institute Pune", zone: "West India API Hub", category: "Vaccine Vials 2-8C", description: "Quadrivalent Flu Vaccine 30K Doses", weight: 75, unit: "kg", shipper: "Serum Institute of India", consignee: "Max Hospital Saket Delhi", mode: "Cold Box Passive 72h", origin: "SII Cold Chain Centre", destination: "Max Hospital Saket Pharmacy", shipDate: "2025-07-10", etaDate: "2025-07-11", transitDays: 1, valueLakhs: 90, tempRange: "2-8C", status: "Cold Chain Hub Transfer", remarks: "QIV flu 30K doses Pune to Delhi Max Hospital cold box hub transfer" },
  { id: "CCL-0009", batchNo: "BATCH-BIOCON/BIO-2025/07-I667", facility: "Biocon Bengaluru Biologics", zone: "South India Biologics", category: "Biologic mAb 2-8C", description: "Trastuzumab Biosimilar 1,000 Vials CANMAb", weight: 35, unit: "kg", shipper: "Biocon Biologics", consignee: "Tata Memorial Mumbai", mode: "Air Cargo Temp Ctrl", origin: "Biocon Bio-Manufacturing", destination: "Tata Memorial Hospital Mumbai", shipDate: "2025-07-09", etaDate: "2025-07-09", transitDays: 0, valueLakhs: 450, tempRange: "2-8C", status: "Delivered Hospital Pharmacy", remarks: "Trastuzumab CANMAb 1K vials Bengaluru to Tata Mumbai air cargo delivered" },
  { id: "CCL-0010", batchNo: "BATCH-EMCURE/VAC-2025/07-J890", facility: "Emcure Pune Vaccines", zone: "West India API Hub", category: "Diagnostic Reagent", description: "HIV ELISA Test Kit 50,000 Units", weight: 250, unit: "kg", shipper: "Emcure Pharmaceuticals", consignee: "NACO Regional Depot Bhubaneswar", mode: "Reefer Truck -20 to 8C", origin: "Emcure Diagnostics Pune", destination: "NACO Bhubaneswar Depot", shipDate: "2025-07-08", etaDate: "2025-07-11", transitDays: 3, valueLakhs: 35, tempRange: "2-25C", status: "Temperature Excursion Alert", remarks: "HIV ELISA 50K units Pune to Bhubaneswar temp excursion 9.2C alert triggered" },
  { id: "CCL-0011", batchNo: "BATCH-DRREDDY/PLS-2025/07-K123", facility: "Dr Reddys Hyderabad", zone: "South India Biologics", category: "Blood Plasma Frozen", description: "COVID-19 Convalescent Plasma 50 Units", weight: 25, unit: "kg", shipper: "Dr Reddys Blood Bank", consignee: "AIIMS New Delhi Blood Bank", mode: "Air Cargo Temp Ctrl", origin: "Dr Reddys Hyderabad Blood Bank", destination: "AIIMS New Delhi Transfusion", shipDate: "2025-07-10", etaDate: "2025-07-10", transitDays: 0, valueLakhs: 8, tempRange: "-20C Frozen", status: "Cold Room Validated", remarks: "Convalescent plasma 50 units frozen -20C Hyderabad to AIIMS air cargo validated" },
  { id: "CCL-0012", batchNo: "BATCH-BHARAT/JEV-2025/07-L345", facility: "Bharat Biotech Hyderabad", zone: "South India Biologics", category: "Vaccine Vials 2-8C", description: "Japanese Encephalitis Vaccine 100K Doses", weight: 250, unit: "kg", shipper: "Bharat Biotech International", consignee: "UP State Vaccination Store Lucknow", mode: "Reefer Truck -20 to 8C", origin: "BBI Cold Chain Hub", destination: "UP RKS Store Lucknow", shipDate: "2025-07-07", etaDate: "2025-07-09", transitDays: 2, valueLakhs: 120, tempRange: "2-8C", status: "Delivered Hospital Pharmacy", remarks: "JE vaccine 100K doses Hyderabad to Lucknow RKS delivered state cold chain" },
  { id: "CCL-0013", batchNo: "BATCH-CIPLA/ART-2025/07-M567", facility: "Cipla Mumbai Formulation", zone: "West India API Hub", category: "API Temperature Ctrl", description: "Artemisinin API 100kg Anti-Malarial", weight: 100, unit: "kg", shipper: "Cipla API Division", consignee: "IPCA Laboratories Ratlam", mode: "Reefer Rail Container", origin: "Cipla Kurkumbh API Plant", destination: "IPCA Ratlam Formulation", shipDate: "2025-07-09", etaDate: "2025-07-10", transitDays: 1, valueLakhs: 65, tempRange: "15-25C", status: "Reefer Truck Moving", remarks: "Artemisinin API 100kg anti-malarial Kurkumbh to Ratlam reefer rail" },
  { id: "CCL-0014", batchNo: "BATCH-ZYDUS/BIO-2025/07-N890", facility: "Zydus Ahmedabad API", zone: "West India API Hub", category: "Organ Transport", description: "Donor Kidney with Preservation Solution", weight: 5, unit: "kg", shipper: "Zydus Hospital Ahmedabad", consignee: "Apollo Hospital Chennai Transplant", mode: "Ambulance Organ Escort", origin: "Zydus Hospital OR", destination: "Apollo Chennai Transplant OR", shipDate: "2025-07-10", etaDate: "2025-07-10", transitDays: 0, valueLakhs: 15, tempRange: "2-8C UW Solution", status: "Delivered Hospital Pharmacy", remarks: "Donor kidney Ahmedabad to Chennai ambulance air escort UW solution cold chain" },
];

const transitCount = records.filter(rec => rec.status === "Reefer Truck Moving").length;
const hubCount = records.filter(rec => rec.status === "Cold Chain Hub Transfer" || rec.status === "Temperature Excursion Alert").length;
const deliveredCount = records.filter(rec => rec.status === "Delivered Hospital Pharmacy" || rec.status === "Cold Room Validated").length;
const totalValue = records.reduce((s, rec) => s + rec.valueLakhs, 0);

const kpis = [
  { l: "In Transit", v: transitCount, s: "reefer moving" },
  { l: "Hub/Alert", v: hubCount, s: "excursion risk" },
  { l: "Delivered", v: deliveredCount, s: "validated" },
  { l: "Total Cold Chain Value", v: `\u20b9${(totalValue / 100).toFixed(0)}Cr`, s: "all shipments" },
];

const INSIGHTS = [
  {
    t: "India Cold Chain Pharma: \u20b935,000 Crore Market, 2-8C GDP Compliance, WHO Pre-Qualified",
    c: "India\u2019s pharmaceutical cold chain logistics market is valued at \u20b935,000 crore (USD 4.2 billion) in FY2024-25, growing at 15% CAGR. India is the world\u2019s 3rd largest pharmaceutical producer by volume (USD 50 billion industry) and supplier of 20% of global generic drugs. Cold chain critical products: (1) Vaccines: India produces 60% of global vaccines (Serum Institute: world\u2019s largest vaccine manufacturer, 3+ billion doses/year). Major vaccines: Covishield (AstraZeneca, 1.5B+ doses), Rotavac (rotavirus, 100M doses), oral polio (150M doses), BCG, DPT, measles-rubella. All vaccines require strict 2-8 degrees Celsius storage and transport. (2) Biologics/Biosimilars: India is the world\u2019s biosimils leader (Biocon: world\u2019s largest biosimilar insulin, Adalimumab/Trastuzumab/Insulin glargine). Storage: 2-8 degrees Celsius. India biosimilar market: \u20b912,000 crore, growing 25% CAGR. (3) Insulin: India has 100+ million diabetics. Insulin cold chain: 2-8C unopened, room temperature after first use (28 days). Annual insulin cold chain volume: 200+ million pens/vials. Major: Biocon (Insugen), Dr Reddys (basalog), Novo Nordisk India. (4) Blood and blood products: India collects 15 million units blood/year (require 2-6C), plasma frozen at -20C to -30C. (5) APIs (Active Pharmaceutical Ingredients): some APIs require temperature-controlled transport (15-25C) to prevent degradation. India produces 70% of global generic API volume. Major API hubs: Hyderabad (Dr Reddys, Aurobindo, Mylan), Mumbai (Cipla, Lupin), Ahmedabad (Zydus, Cadila), Vadodara (Alembic). Cold chain infrastructure: (a) 50+ GDP-compliant cold chain companies: Snowman Logistics (8,000+ pallet capacity), Coldstar (5,000+), Gati Cold Chain, TLC Cold Chain, Ripley Cold Chain. (b) 200+ cold storages (multi-commodity, pharma-dedicated), (c) 5,000+ reefer trucks (insulated, mechanical refrigeration), (d) 100,000+ cold boxes/ vaccine carriers (passive cooling, 72-hour validated), and (e) 15+ airport cold rooms (Mumbai, Delhi, Hyderabad, Bengaluru, Chennai). WHO pre-qualification: India has 40+ WHO-prequalified vaccine products (highest for any country), requiring GDP (Good Distribution Practice) compliance per WHO TRS 961 Annex 7. CDSCO (Central Drugs Standard Control Organisation) regulates all pharma cold chain in India under Drugs and Cosmetics Act 1940.",
  },
  {
    t: "Cold Chain Technology: Reefer Trucks, Passive Cold Boxes, Temperature Loggers, GDP Compliance",
    c: "India\u2019s cold chain logistics employs multiple technology layers: (1) Active cold chain (mechanical refrigeration): (a) Reefer trucks: 3,000+ vehicles in India (Mahindra, Tata Motors, Isuzu, BharatBenz). Specifications: C1 (ambient +12C), C2 (frozen -18C), C3 (chilled 0 to +2C), C4 (deep frozen -25C). Typical pharma reefer: 2-8C setpoint, ±1C tolerance, GPS tracker, temperature logger (data logger records every 5 minutes, downloadable PDF report). Fleet: Snowman (500+ reefers), Coldstar (300+), Gati (200+). Cost: \u20b98-15 per km (reefer vs \u20b93-5 for dry truck). (b) Reefer rail containers: Indian Railways operates 200+ reefer container wagons on CONCOR (temperature set: -20 to +25C). Used for bulk API transport: Mumbai to Hyderabad (600 km, 18 hours), Ahmedabad to Delhi (900 km, 24 hours). (c) Air cargo cold rooms: 15+ airports with GDP-certified pharma handling (Mumbai T2 Pharma Zone, Delhi T3 Cold Room, Hyderabad Pharma Hub, Bengaluru Kempegowda). Emirates SkyCargo, Lufthansa Pharma, Air India Cargo operate temperature-controlledULD (Unit Load Devices). Cost: \u20b9120-250/kg (pharma air cargo, 2-8C, vs \u20b950-100/kg dry). (2) Passive cold chain (no mechanical refrigeration): (a) Cold boxes: insulated containers with PCM (Phase Change Material) gel packs or ice packs. Validated for 48-72 hours at 2-8C. Used for last-mile vaccine delivery (PHC to sub-centre). India has 500,000+ vaccine carriers (state government, UNICEF-procured). (b) Vaccine carriers: smaller (1-5 litres), used by ANM (Auxiliary Nurse Midwife) for outreach immunization sessions. PCM packs preconditioned at -20C for 24 hours, then 2-8C for 72 hours. (c) Cool boxes: larger (20-100 litres) for inter-facility transfer. (3) Temperature monitoring and data logging: (a) Electronic data loggers: temp and humidity recorded every 1-5 minutes, battery life 30-90 days. Brands: Onset HOBO, Testo, Elpro. Cost: \u20b92,000-8,000 per logger. (b) IoT real-time monitoring: cellular-connected sensors (SIM-based, upload every 15 minutes to cloud). Platforms: Controlant (used by Biocon), Roambee (Snowman), Tempi (used by Dr Reddys). Alert: SMS/email within 2 minutes of temperature excursion. (c) TMFD (Temperature Monitoring and Feedback Device): mandatory on all pharma cold chain per CDSCO guidelines. (d) UNT (Universal Normalized Time): WHO standard for calculating thermal exposure (time-temperature integration). GDP compliance: (a) WHO TRS 961 Annex 7: global standard for pharma distribution, (b) EU GDP Guidelines 2013/C 343/01: adopted by India for export, (c) Indian GDP Schedule U: CDSCO requirement for all pharma wholesale/distribution, (d) Validation: cold chain equipment must be validated (temperature mapping, door-opening studies, load simulation) annually. India GDP audit findings: common non-compliance includes inadequate temp records, missing calibration certificates, and untrained personnel.",
  },
  {
    t: "Vaccine Cold Chain: EPI, Mission Indradhanush, COVID-19 Lessons, UIP Logistics",
    c: "India\u2019s vaccine cold chain is the world\u2019s largest public health logistics network: (1) UIP (Universal Immunization Programme): India immunizes 27 million infants and 30 million pregnant women annually against 12 diseases (BCG, DPT, OPV, measles, rubella, hepatitis-B, rotavirus, PCV, JE, pentavalent, fIPV, MR). Vaccine volume: 400+ million doses/year (UIP) + 300+ million doses COVID-19. (2) Cold chain network: 4 levels: (a) National Vaccine Store (NVS, Delhi): receives from SII/Bharat Biotech, stores 50+ million doses, 4 large cold rooms (2-8C), deep freezer (-20C). (b) State Vaccine Stores (36): each has 2-5 cold rooms, walk-in cooler. (c) District Vaccine Stores (780+): each has ILR (Ice-Lined Refrigerator, 300 litres) + deep freezer. (d) PHC/Sub-centre level (160,000+): each has ILR (100-300 litres) + vaccine carrier + ice packs. India has 60,000+ ILRs, 40,000+ deep freezers, 500,000+ vaccine carriers, 80,000+ cold boxes. (3) Mission Indradhanush: intensifies immunization in underserved areas (250+ high-focus districts). Special cold chain: mobile vaccine vans with solar-powered ILRs, cold boxes for hard-to-reach areas (Assam, Bihar, MP, UP, Jharkhand). (4) COVID-19 vaccine cold chain (2021-2023): India administered 2.2 billion COVID-19 vaccine doses (Covishield, Covaxin, Corbevax, Sputnik V). COVID cold chain challenges: (a) Massive scale: 1 billion doses in 6 months (Jan-Jun 2022), (b) Temperature: all Indian COVID vaccines at 2-8C (unlike Pfizer/BioNTech -70C), simplifying logistics, (c) Digital: CoWIN platform tracked 1 billion+ vaccinations with Aadhaar-based identification, (d) Rural: last-mile to 600,000+ villages, often without reliable electricity (solar ILRs used), and (e) Monitoring: real-time IoT temperature monitoring on 50% of reefer trucks. (5) Pulse Polio: India\u2019s polio eradication programme used 700+ million OPV doses/year. Cold chain: OPV stable at -20C for 6 months, 2-8C for 6 months. VVM (Vaccine Vial Monitor) heat-sensitive label on each vial (changes color if exposed to excessive heat). India has been polio-free since 2014. (6) MR (Measles-Rubella) campaign: 2017-2020, 324 million children vaccinated, largest single-vaccine campaign globally. Cold chain: pre-positioning of vaccines at district level 2 weeks before campaign, daily re-supply from state stores. Lessons from COVID: (a) India\u2019s cold chain handled 2.2B doses in 18 months \u2014 proof of scale capability, (b) Digital CoWIN + IoT monitoring reduced wastage to 0.5% (vs 5% pre-COVID), (c) Solar ILRs viable for off-grid villages, and (d) Need for -20C capacity for future mRNA vaccine adoption (Pfizer-BioNTech, Moderna). India is building 50 new -20C freezers in preparation for mRNA vaccine rollout (BioNTech partnership with Bharat Biotech).",
  },
  {
    t: "Pharma Export Cold Chain, Blood Bank Network, and India\u2019s Temperature Logistics Growth",
    c: "India\u2019s pharma export cold chain: India exports USD 25+ billion of pharmaceuticals annually (FY25), of which 30-40% requires cold chain logistics: (1) Vaccine exports: \u20b915,000 crore (USD 1.8 billion). Major export routes: (a) UNICEF/PAHO/Gavi: vaccines to 150+ countries (SII exports 1+ billion doses/year to Africa, Southeast Asia, Latin America). Cold chain: SII Pune airport cold room to Mumbai air cargo, then air freight to destination. (b) Bilateral: Covishield to UK, Canada, Brazil, Saudi Arabia, Myanmar. (c) Bharat Biotech: Covaxin, Rotavac, Typbar TCV (typhoid) exports. (2) Biosimilar exports: Biocon (Adalimumab to US/EU/Japan), Dr Reddys (Biosimilar oncology to US), Zydus (Adalimumab to EU). Cold chain: 2-8C air cargo from Hyderabad/Bengaluru to global distribution centres. (3) API exports: India exports USD 8 billion of APIs annually, 10-15% requires temperature-controlled transport. Cold chain containers from Nhava Sheva (JNPT) and Mundra to global ports. India\u2019s blood bank cold chain: (a) 3,000+ licensed blood banks (government: 1,200, private: 1,800), (b) Annual collection: 15 million units, (c) Storage: whole blood at 2-6C (35-day shelf life), platelets at 20-24C with agitation (5-day shelf life), plasma frozen at -20C (12 months), cryoprecipitate at -30C (12 months), (d) Cold chain equipment: blood bank refrigerators (2-6C, alarm, backup generator), plasma freezers (-20C to -40C), platelet incubators (20-24C with agitator), transport boxes (validated 2-8C for 24 hours), and (e) Temperature monitoring: continuous digital monitoring with SMS alert to blood bank medical officer if temperature exceeds range. India\u2019s cold chain growth: (a) Government investment: \u20b95,000 crore under PM Gati Shakti for cold chain infrastructure (multi-commodity, includes pharma), (b) Private investment: Snowman (\u20b9800 crore new cold storages), Coldstar (\u20b9500 crore), BlackBuck Farms (cold chain for pharma + food), (c) Temperature logistics technology: IoT sensors, blockchain traceability (pilot by Biocon), AI for route optimization (Snowman using ORTEC), and (d) Drone delivery: pilot in Telangana and Karnataka for vaccine last-mile delivery (10kg payload, 15 km range, 15 minutes). India\u2019s cold chain challenges: (a) Last-mile connectivity: rural PHCs without all-weather road access, (b) Power reliability: 40% of PHCs experience power cuts (solar ILRs essential), (c) Temperature excursions: 2-5% of cold chain shipments experience some excursion (most within acceptable limits), (d) Fragmented industry: 500+ small operators, consolidation needed, and (e) Regulatory gaps: CDSCO enforcement of GDP Schedule U is uneven across states. India\u2019s cold chain target: \u20b980,000 crore market by 2030 (from \u20b935,000 crore), driven by biosimilar growth, vaccine exports, mRNA vaccine cold chain, and blood bank modernization.",
  },
];

export default function ColdChainPharmaLogisticsView() {
  const [tab, setTab] = useState(0);
  const [activeFilters, setActiveFilters] = useState<Record<string, string[]>>({});
  const [search, setSearch] = useState("");

  const filterGroups = [
    { key: "status", label: "Status", options: SHIPMENT_STATUSES.map(s => ({ value: s, count: records.filter(rec => rec.status === s).length })) },
    { key: "category", label: "Category", options: CATEGORIES.map(c => ({ value: c, count: records.filter(rec => rec.category === c).length })) },
    { key: "zone", label: "Zone", options: ZONES.map(z => ({ value: z, count: records.filter(rec => rec.zone === z).length })) },
    { key: "mode", label: "Mode", options: MODES.map(m => ({ value: m, count: records.filter(rec => rec.mode === m).length })) },
  ];

  const toggleFilter = (k: string, v: string) => setActiveFilters(p => (function(){ const n={...p}; n[k]=(p[k]||[]).filter(x=>x!==v); if(n[k].length===0) delete n[k]; return n })());

  const filtered = records.filter(r => {
    if (search) {
      const q = search.toLowerCase();
      if (!r.id.toLowerCase().includes(q) && !r.batchNo.toLowerCase().includes(q) && !r.facility.toLowerCase().includes(q) && !r.description.toLowerCase().includes(q) && !r.shipper.toLowerCase().includes(q) && !r.consignee.toLowerCase().includes(q)) return false;
    }
    return Object.entries(activeFilters).every(([k, vs]) => vs.includes(r[k as keyof ShipmentRecord] as string));
  });

  return (
    <div className="ccl-root p-6 space-y-6">
      <PageHeader title="Cold Chain Pharma Logistics" description="India pharmaceutical cold chain logistics covering Serum Institute vaccines, Biocon biologics mAb, Dr Reddys insulin, Bharat Biotech Covaxin, 2-8C GDP compliance, WHO pre-qualified, reefer trucks passive cold boxes IoT temperature monitoring, blood bank network and organ transport" />
      <div className="ccl-tabs flex gap-1 border-b border-gray-200">
        {TABS.map((t, i) => (<button key={t} onClick={() => setTab(i)} className={`ccl-tab px-4 py-2 text-sm font-medium rounded-t ${tab === i ? "bg-emerald-700 text-white" : "text-gray-600 hover:bg-emerald-50"}`}>{t}</button>))}
      </div>

      {tab === 0 && (
        <div className="ccl-dash space-y-6">
          <div className="ccl-kpis grid grid-cols-4 gap-4">
            {kpis.map(k => (<div key={k.l} className="ccl-kpi bg-white rounded-lg border p-4"><div className="text-xs text-gray-500 ccl-kpi-label">{k.l}</div><div className="text-2xl font-bold text-emerald-700 ccl-kpi-val">{k.v}</div><div className="text-xs text-gray-400 ccl-kpi-sub">{k.s}</div></div>))}
          </div>
          <div className="grid grid-cols-2 gap-6">
            <div className="ccl-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Monthly Cold Chain Shipments (Batches)</h3><BarChart data={monthlyShipments} height={220}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="m" /><YAxis /><Tooltip /><Legend /><Bar dataKey="vaccine" fill="#065f46" radius={[4,4,0,0]} name="Vaccine" /><Bar dataKey="insulin" fill="#047857" radius={[4,4,0,0]} name="Insulin" /><Bar dataKey="biologic" fill="#059669" radius={[4,4,0,0]} name="Biologic" /><Bar dataKey="plasma" fill="#10b981" radius={[4,4,0,0]} name="Plasma" /></BarChart></div>
            <div className="ccl-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Pharma Category Distribution</h3><PieChart width={400} height={220}><Pie data={categoryDist} dataKey="v" nameKey="n" cx="50%" cy="50%" outerRadius={80} label>{categoryDist.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}</Pie><Tooltip /></PieChart></div>
          </div>
          <div className="grid grid-cols-2 gap-6">
            <div className="ccl-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Temperature Compliance Rate (%) vs 99% Target</h3><LineChart data={complianceRate} height={220}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="m" /><YAxis domain={[94, 100]} /><Tooltip /><Legend /><Line type="monotone" dataKey="actual" stroke="#065f46" strokeWidth={2} name="Actual %" /><Line type="monotone" dataKey="target" stroke="#dc2626" strokeWidth={2} strokeDasharray="5 5" name="Target" /></LineChart></div>
            <div className="ccl-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Facility Performance Score</h3><BarChart data={facilityPerf} height={220}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="n" tick={{ fontSize: 9 }} /><YAxis domain={[88, 100]} /><Tooltip /><Bar dataKey="v" fill="#047857" radius={[4,4,0,0]} name="Score" /></BarChart></div>
          </div>
        </div>
      )}

      {tab === 1 && (
        <div className="ccl-registry space-y-4">
          <ModuleBreadcrumb items={[{ label: "Cold Chain Pharma", href: "#" }, { label: "Shipment Registry", href: "#" }]} />
          <SearchFilterToolbar searchQuery={search} onSearchChange={setSearch} onClearSearch={() => setSearch("")} activeFilters={activeFilters} filterGroups={filterGroups} onToggleFilter={toggleFilter} onClearAllFilters={() => setActiveFilters({})} totalItems={records.length} filteredCount={filtered.length} />
          <div className="ccl-table-wrap overflow-x-auto bg-white rounded-lg border">
            <table className="w-full text-sm"><thead><tr className="border-b bg-gray-50">{"ID,Batch No,Facility,Zone,Category,Description,Weight,Shipper,Consignee,Mode,Origin,Destination,Ship Date,ETA,Transit (d),Value (\u20b9L),Temp Range,Status,Remarks"
                .split(",").map(h => (<th key={h} className="px-3 py-2 text-left text-xs font-medium text-gray-500 whitespace-nowrap">{h}</th>))}</tr></thead>
            <tbody>{filtered.map(r => {
              const rowCls = r.status === "Temperature Excursion Alert" ? "ccl-row-critical bg-red-50" : r.status === "Customs Bio-Security Hold" ? "ccl-row-warning bg-amber-50" : r.status === "Reefer Truck Moving" || r.status === "Cold Chain Hub Transfer" ? "ccl-row-info bg-blue-50" : "";
              return (<tr key={r.id} className={`border-b hover:bg-emerald-50/30 ${rowCls}`}>
                <td className="px-3 py-2 font-mono font-medium">{r.id}</td>
                <td className="px-3 py-2"><span className="ccl-badge inline-block px-2 py-0.5 rounded text-xs bg-emerald-700 text-white font-mono text-[10px]">{r.batchNo}</span></td>
                <td className="px-3 py-2 text-xs max-w-28 truncate">{r.facility}</td>
                <td className="px-3 py-2"><span className="ccl-badge inline-block px-2 py-0.5 rounded text-xs bg-gray-100 text-gray-700">{r.zone}</span></td>
                <td className="px-3 py-2"><span className="ccl-badge inline-block px-2 py-0.5 rounded text-xs bg-gray-100 text-gray-700">{r.category}</span></td>
                <td className="px-3 py-2 text-xs max-w-32 truncate">{r.description}</td>
                <td className="px-3 py-2 text-xs text-right font-semibold">{r.weight >= 1000 ? `${(r.weight/1000).toFixed(0)}T` : `${r.weight}kg`}</td>
                <td className="px-3 py-2 text-xs max-w-24 truncate">{r.shipper}</td>
                <td className="px-3 py-2 text-xs max-w-24 truncate">{r.consignee}</td>
                <td className="px-3 py-2 text-xs">{r.mode}</td>
                <td className="px-3 py-2 text-xs max-w-24 truncate">{r.origin}</td>
                <td className="px-3 py-2 text-xs max-w-24 truncate">{r.destination}</td>
                <td className="px-3 py-2 text-xs">{r.shipDate}</td>
                <td className="px-3 py-2 text-xs">{r.etaDate}</td>
                <td className="px-3 py-2"><span className={`text-xs font-semibold ${r.transitDays >= 3 ? "text-amber-600" : "text-green-600"}`}>{r.transitDays}d</span></td>
                <td className="px-3 py-2 text-xs font-semibold text-emerald-700">{r.valueLakhs >= 100 ? `\u20b9${(r.valueLakhs/100).toFixed(0)}Cr` : `\u20b9${r.valueLakhs}L`}</td>
                <td className="px-3 py-2"><span className={`ccl-badge inline-block px-2 py-0.5 rounded text-xs ${r.tempRange.includes("-20") ? "bg-blue-100 text-blue-700" : r.tempRange.includes("15") ? "bg-amber-100 text-amber-700" : "bg-emerald-100 text-emerald-700"}`}>{r.tempRange}</span></td>
                <td className="px-3 py-2"><span className={`ccl-badge inline-block px-2 py-0.5 rounded text-xs font-semibold ${SC[statusColor[r.status]]}`}>{r.status}</span></td>
                <td className="px-3 py-2 text-xs text-gray-500 max-w-32 truncate">{r.remarks}</td>
              </tr>);
            })}</tbody></table>
          </div>
        </div>
      )}

      {tab === 2 && (
        <div className="ccl-analytics space-y-6">
          <div className="grid grid-cols-2 gap-6">
            <div className="ccl-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Cold Chain Volume by Zone</h3><BarChart data={ZONES.map(z => ({ n: z.split(" ").slice(0, 2).join(" "), v: +ri(15, 45, 28 + Math.random() * 12).toFixed(0) }))} height={240}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="n" tick={{ fontSize: 9 }} /><YAxis /><Tooltip /><Bar dataKey="v" fill="#065f46" radius={[4,4,0,0]} name="Batches" /></BarChart></div>
            <div className="ccl-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Volume by Category Corridor</h3><AreaChart data={Array.from({ length: 12 }, (_, i) => ({ m: MO[i], vaccine: ri(8, 20, 14 + Math.sin(i*0.5)*3), insulin: ri(4, 12, 8 + Math.cos(i*0.6)*2), biologic: ri(3, 10, 6 + Math.sin(i*0.7)*2) }))} height={240}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="m" /><YAxis /><Tooltip /><Legend /><Area type="monotone" dataKey="vaccine" stackId="1" stroke="#065f46" fill="#6ee7b7" name="Vaccine" /><Area type="monotone" dataKey="insulin" stackId="1" stroke="#047857" fill="#34d399" name="Insulin" /><Area type="monotone" dataKey="biologic" stackId="1" stroke="#059669" fill="#10b981" name="Biologic" /></AreaChart></div>
          </div>
          <div className="ccl-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Avg Transit Days by Transport Mode</h3><BarChart data={[{n:"Reefer Truck",v:1.5},{n:"Cold Box",v:0.5},{n:"Air Cargo",v:1},{n:"Reefer Rail",v:2},{n:"Ambulance",v:0.3},{n:"Drone",v:0.1}].map(d => ({...d, v: +ri(d.v*0.7, d.v*1.3, d.v + Math.random()*0.2).toFixed(1)}))} height={240}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="n" tick={{ fontSize: 9 }} /><YAxis /><Tooltip /><Bar dataKey="v" fill="#047857" radius={[4,4,0,0]} name="Days" /></BarChart></div>
        </div>
      )}

      {tab === 3 && (
        <div className="ccl-insights grid grid-cols-2 gap-6">{INSIGHTS.map(ins => (<div key={ins.t} className="ccl-insight bg-white rounded-lg border p-5"><h3 className="text-base font-bold text-emerald-800 mb-2">{ins.t}</h3><p className="text-sm text-gray-600 leading-relaxed">{ins.c}</p></div>))}</div>
      )}
    </div>
  );
}
