"use client";
import { useState } from "react";
import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, Legend } from "recharts";
import { PageHeader } from "@/components/shared/page-header";
import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar";
import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb";

const COLORS = ["#4a1d1d", "#6b2c2c", "#8b3a3a", "#a84444", "#c45252", "#3a1515", "#5c2222", "#d47070"];
const ARSENALS = ["Ordnance Factory Ambarnath Mumbai", "Ordnance Factory Khamaria Jabalpur", "OFB Ishapore Kolkata", "Bharat Dynamics Ltd Hyderabad", "MIDHANI Hyderabad Defence Alloys", "Ordnance Factory Medak Telangana", "OFB Kanpur Ammunition", "BEL Hyderabad Defence Electronics"];
const CATEGORIES = ["Artillery Shell 155mm", "Small Arms Ammunition", "Missile System TBM", "Demolition Explosives", "Armoured Vehicle Spares", "Radar EW Module", "Communication Equipment", "NBC Protective Gear"];
const SHIPMENT_STATUSES = ["Security Cleared", "Military Convoy Moving", "Base Loading Dock", "Quality Inspection DQA", "Armed Escort Transit", "Delivered Ordnance Depot"];
const ZONES = ["Western Command Chandigarh", "Southern Command Pune", "Eastern Command Kolkata", "Northern Command Udhampur", "Central Command Lucknow", "South Western Command Jaipur"];
const MODES = ["Military Truck 10T",("Armed Rail Wagon"), "Air Force C-17 Globemaster", "Navy Landing Craft", "Heavy Trailer Convoy", "Helicopter Sling External"];
const TABS = ["Dashboard", "Shipment Registry", "Defence Analytics", "Insights"];

const SC: Record<string, string> = { green: "bg-green-100 text-green-700", amber: "bg-amber-100 text-amber-700", red: "bg-red-100 text-red-700", blue: "bg-blue-100 text-blue-700", slate: "bg-slate-100 text-slate-600", orange: "bg-orange-100 text-orange-700" };
const statusColor: Record<string, string> = { "Security Cleared": "green", "Military Convoy Moving": "blue", "Base Loading Dock": "amber", "Quality Inspection DQA": "orange", "Armed Escort Transit": "red", "Delivered Ordnance Depot": "green" };

function ri(min: number, max: number, value: number) { return Math.min(max, Math.max(min, value)); }

const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const monthlyShipments = Array.from({ length: 12 }, (_, i) => ({ m: MO[i], artillery: ri(8, 18, 12 + Math.sin(i * 0.5) * 3), smallArms: ri(20, 45, 32 + Math.cos(i * 0.6) * 6), missile: ri(2, 6, 4 + Math.sin(i * 0.7) * 1), vehicle: ri(4, 10, 7 + Math.cos(i * 0.8) * 2) }));
const categoryDist = [{ n: "Small Arms Ammo", v: 30 }, { n: "Artillery 155mm", v: 22 }, { n: "Armoured Spares", v: 18 }, { n: "Missile Systems", v: 10 }, { n: "Radar EW", v: 8 }, { n: "Explosives Demo", v: 6 }, { n: "Comm Equipment", v: 4 }, { n: "NBC Gear", v: 2 }];
const readinessRate = Array.from({ length: 12 }, (_, i) => ({ m: MO[i], actual: +(ri(88, 98, 94 + Math.sin(i * 0.4) * 2.5)).toFixed(1), target: 95.0 }));
const commandPerf = ZONES.map(z => ({ n: z.split(" ").slice(0, 1).join(" "), v: +ri(82, 97, 91 + Math.random() * 4).toFixed(0) }));

interface ShipmentRecord { id: string; consignmentNo: string; arsenal: string; zone: string; category: string; description: string; weight: number; unit: string; origin: string; destination: string; unitCommand: string; mode: string; dispatchDate: string; etaDate: string; transitDays: number; valueCr: number; securityClass: string; status: string; remarks: string; }

const records: ShipmentRecord[] = [
  { id: "DOL-0001", consignmentNo: "CON-MOD/2025/07/ART-0891", arsenal: "Ordnance Factory Ambarnath Mumbai", zone: "Southern Command Pune", category: "Artillery Shell 155mm", description: "Bofors 155mm HE Shell 42-Inch Rake", weight: 8400, unit: "kg", origin: "OF Ambarnath Magazine", destination: "Depot 41 Ferozepur Punjab", unitCommand: "II Corps Ambala", mode: "Armed Rail Wagon", dispatchDate: "2025-07-08", etaDate: "2025-07-11", transitDays: 3, valueCr: 4.2, securityClass: "RESTR", status: "Military Convoy Moving", remarks: "Bofors 155mm HE 42-inch rake Ambarnath to Ferozepur armed rail wagon Western Railway" },
  { id: "DOL-0002", consignmentNo: "CON-MOD/2025/07/SA-1234", arsenal: "OFB Kanpur Ammunition", zone: "Central Command Lucknow", category: "Small Arms Ammunition", description: "5.56mm INSAS Rifle 50,000 Rounds", weight: 1200, unit: "kg", origin: "OFK Kanpur Magazine", destination: "Central Ordnance Depot Agra", unitCommand: "Brahmos Group Lucknow", mode: "Military Truck 10T", dispatchDate: "2025-07-09", etaDate: "2025-07-10", transitDays: 1, valueCr: 0.8, securityClass: "PROT", status: "Security Cleared", remarks: "5.56mm INSAS 50K rounds Kanpur to COD Agra military truck convoy" },
  { id: "DOL-0003", consignmentNo: "CON-MOD/2025/07/MS-0567", arsenal: "Bharat Dynamics Ltd Hyderabad", zone: "Southern Command Pune", category: "Missile System TBM", description: "Agni-V TBM Missile Canister 3-Stage", weight: 50000, unit: "kg", origin: "BDL Production Facility", destination: "Strategic Forces Command Base", unitCommand: "SFC New Delhi", mode: "Air Force C-17 Globemaster", dispatchDate: "2025-07-07", etaDate: "2025-07-07", transitDays: 0, valueCr: 350, securityClass: "TOP SEC", status: "Armed Escort Transit", remarks: "Agni-V TBM canister BDL Hyderabad to SFC base IAF C-17 special flight TOP SECRET" },
  { id: "DOL-0004", consignmentNo: "CON-MOD/2025/07/EX-0890", arsenal: "Ordnance Factory Khamaria Jabalpur", zone: "Central Command Lucknow", category: "Demolition Explosives", description: "TNT RDX 2T Demolition Kit Military Engineer", weight: 2000, unit: "kg", origin: "OFK Explosive Magazine", destination: "Sappers Regiment Jalandhar", unitCommand: "V Corps Jalandhar", mode: "Heavy Trailer Convoy", dispatchDate: "2025-07-10", etaDate: "2025-07-12", transitDays: 2, valueCr: 2.5, securityClass: "RESTR", status: "Military Convoy Moving", remarks: "TNT/RDX 2T demolition kit Jabalpur to Jalandhar Sappers heavy trailer police escort" },
  { id: "DOL-0005", consignmentNo: "CON-MOD/2025/07/AV-1122", arsenal: "Ordnance Factory Medak Telangana", zone: "Southern Command Pune", category: "Armoured Vehicle Spares", description: "Arjun MBT Track Pack 12-Road Wheel", weight: 24000, unit: "kg", origin: "OF Medak Assembly", destination: "73 Armoured Regiment Jaisalmer", unitCommand: "XII Corps Jaisalmer", mode: "Military Truck 10T", dispatchDate: "2025-07-08", etaDate: "2025-07-11", transitDays: 3, valueCr: 8.5, securityClass: "PROT", status: "Base Loading Dock", remarks: "Arjun MBT track pack 12 road wheel assemblies Medak to Jaisalmer desert sector" },
  { id: "DOL-0006", consignmentNo: "CON-MOD/2025/07/RD-0345", arsenal: "BEL Hyderabad Defence Electronics", zone: "Southern Command Pune", category: "Radar EW Module", description: "Rohini 3D CAR Radar Antenna Array", weight: 6500, unit: "kg", origin: "BEL Radar Division", destination: "AIRC Leh Air Force Station", unitCommand: "Northern Command Udhampur", mode: "Air Force C-17 Globemaster", dispatchDate: "2025-07-09", etaDate: "2025-07-09", transitDays: 0, valueCr: 45, securityClass: "RESTRICTED", status: "Delivered Ordnance Depot", remarks: "Rohini 3D CAR radar antenna BEL Hyderabad to Leh IAF C-17 special delivered" },
  { id: "DOL-0007", consignmentNo: "CON-MOD/2025/07/CM-0567", arsenal: "BEL Hyderabad Defence Electronics", zone: "Eastern Command Kolkata", category: "Communication Equipment", description: "Tactical Communication Node V2 5-Node", weight: 3500, unit: "kg", origin: "BEL Comm Systems", destination: "HQ IV Corps Tezpur Assam", unitCommand: "IV Corps Tezpur", mode: "Military Truck 10T", dispatchDate: "2025-07-10", etaDate: "2025-07-14", transitDays: 4, valueCr: 18, securityClass: "PROT", status: "Military Convoy Moving", remarks: "Tactical comm node 5-unit BEL Hyderabad to Tezpur Assam convoy through Siliguri" },
  { id: "DOL-0008", consignmentNo: "CON-MOD/2025/07/NBC-0891", arsenal: "OFB Ishapore Kolkata", zone: "Eastern Command Kolkata", category: "NBC Protective Gear", description: "NBC Suit MK-III 200-Set Battalion Kit", weight: 800, unit: "kg", origin: "OF Ishapore NBC Div", destination: "6 Mountain Division Tawang", unitCommand: "III Corps Tawang", mode: "Air Force C-17 Globemaster", dispatchDate: "2025-07-08", etaDate: "2025-07-09", transitDays: 1, valueCr: 1.2, securityClass: "PROT", status: "Delivered Ordnance Depot", remarks: "NBC MK-III 200-set battalion kit Ishapore to Tawang IAF delivered to forward area" },
  { id: "DOL-0009", consignmentNo: "CON-MOD/2025/07/ART-1234", arsenal: "Ordnance Factory Ambarnath Mumbai", zone: "Northern Command Udhampur", category: "Artillery Shell 155mm", description: "Kalyani M-46 155mm Cargo Shell Rake", weight: 6200, unit: "kg", origin: "OF Ambarnath Shell Factory", destination: "Depot 13 Srinagar Kashmir", unitCommand: "XV Corps Srinagar", mode: "Armed Rail Wagon", dispatchDate: "2025-07-07", etaDate: "2025-07-10", transitDays: 3, valueCr: 3.8, securityClass: "RESTR", status: "Quality Inspection DQA", remarks: "Kalyani M-46 cargo shell rake Ambarnath to Srinagar DQA inspection pending" },
  { id: "DOL-0010", consignmentNo: "CON-MOD/2025/07/MS-0678", arsenal: "Bharat Dynamics Ltd Hyderabad", zone: "South Western Command Jaipur", category: "Missile System TBM", description: "BrahMos Block-III LACM Crate 8-Unit", weight: 16000, unit: "kg", origin: "BDL BrahMos Facility", destination: "Missile Regiment Jaisalmer", unitCommand: "XII Corps Jaisalmer", mode: "Military Truck 10T", dispatchDate: "2025-07-09", etaDate: "2025-07-11", transitDays: 2, valueCr: 210, securityClass: "TOP SEC", status: "Armed Escort Transit", remarks: "BrahMos Block-III 8-unit crate Hyderabad to Jaisalmer armed escort convoy CISF" },
  { id: "DOL-0011", consignmentNo: "CON-MOD/2025/07/AV-0901", arsenal: "MIDHANI Hyderabad Defence Alloys", zone: "Southern Command Pune", category: "Armoured Vehicle Spares", description: "T-90S Bhishma Turret Ring Special Alloy", weight: 8500, unit: "kg", origin: "MIDHANI Alloy Foundry", destination: "AVNL Chennai Assembly", unitCommand: "AVNL Chennai (Production)", mode: "Heavy Trailer Convoy", dispatchDate: "2025-07-10", etaDate: "2025-07-12", transitDays: 2, valueCr: 15, securityClass: "PROT", status: "Base Loading Dock", remarks: "T-90S Bhishma turret ring special alloy MIDHANI to AVNL Chennai heavy trailer" },
  { id: "DOL-0012", consignmentNo: "CON-MOD/2025/07/SA-0234", arsenal: "OFB Kanpur Ammunition", zone: "Western Command Chandigarh", category: "Small Arms Ammunition", description: "7.62mm AK-203 Rifle 100,000 Rounds", weight: 2500, unit: "kg", origin: "OFK Small Calibre", destination: "Gorkha Rifles Depot Pathankot", unitCommand: "IX Corps Pathankot", mode: "Military Truck 10T", dispatchDate: "2025-07-09", etaDate: "2025-07-10", transitDays: 1, valueCr: 1.5, securityClass: "PROT", status: "Security Cleared", remarks: "7.62mm AK-203 100K rounds Kanpur to Pathankot Gorkha Rifles depot" },
  { id: "DOL-0013", consignmentNo: "CON-MOD/2025/07/EX-0456", arsenal: "Ordnance Factory Khamaria Jabalpur", zone: "Northern Command Udhampur", category: "Demolition Explosives", description: "HMX Plastic Explosive 500kg Engineer Kit", weight: 500, unit: "kg", origin: "OFK High Explosive", destination: "Para SF Battalion Agra", unitCommand: "Para SF Agra", mode: "Air Force C-17 Globemaster", dispatchDate: "2025-07-10", etaDate: "2025-07-10", transitDays: 0, valueCr: 1.8, securityClass: "TOP SEC", status: "Delivered Ordnance Depot", remarks: "HMX plastic explosive 500kg Jabalpur to Para SF Agra IAF C-17 delivered" },
  { id: "DOL-0014", consignmentNo: "CON-MOD/2025/07/CM-0789", arsenal: "BEL Hyderabad Defence Electronics", zone: "Western Command Chandigarh", category: "Radar EW Module", description: "Swati Weapon Locating Radar 4-Unit", weight: 12000, unit: "kg", origin: "BEL LRDE Division", destination: "Artillery Division Ambala", unitCommand: "II Corps Ambala", mode: "Heavy Trailer Convoy", dispatchDate: "2025-07-08", etaDate: "2025-07-10", transitDays: 2, valueCr: 85, securityClass: "RESTR", status: "Military Convoy Moving", remarks: "Swati WLR 4-unit BEL LRDE to Ambala Artillery Div heavy trailer convoy" },
];

const transitCount = records.filter(rec => rec.status === "Military Convoy Moving" || rec.status === "Armed Escort Transit").length;
const loadingCount = records.filter(rec => rec.status === "Base Loading Dock" || rec.status === "Quality Inspection DQA").length;
const deliveredCount = records.filter(rec => rec.status === "Delivered Ordnance Depot" || rec.status === "Security Cleared").length;
const totalValue = records.reduce((s, rec) => s + rec.valueCr, 0);

const kpis = [
  { l: "In Transit", v: transitCount, s: "convoy/escort" },
  { l: "Loading/DQA", v: loadingCount, s: "base inspection" },
  { l: "Delivered/Cleared", v: deliveredCount, s: "depot received" },
  { l: "Total Shipment Value", v: `\u20b9${totalValue.toFixed(0)}Cr`, s: "all ordnance" },
];

const INSIGHTS = [
  {
    t: "India Defence Ordnance Logistics: \u20b980,000 Crore OFB-BEL-BDL Ecosystem, 41 Ordnance Factories",
    c: "India\u2019s defence ordnance logistics ecosystem is valued at \u20b980,000 crore (USD 10 billion) annually, managed by the Department of Military Affairs and Ministry of Defence. Key production and logistics nodes: (1) OFB/AVNL (Ambarnath, Khamaria, Ishapore, Kanpur, Medak, Muradnagar, Varangaon, Chandigarh, Dehradun, Tiruchirappalli): 41 ordnance factories (now corporatized into 7 Defence Public Sector Undertakings under AVNL-Advanced Weapons and Equipment India Ltd, MIL-Munitions India Ltd, AIHL-Armoured Vehicles Nigam Ltd, PLM-Paradeep Marine Products, OL-Warships, GI-Gliders, TL-Troop Comforts). Production: 8 billion rounds of small arms ammunition/year, 500,000+ artillery shells/year, 100,000+ grenades/year. (2) BEL (Bharat Electronics Limited, 9 factories): radar (Rohini 3D CAR, Swati WLR, Ashwin AWACS), communication (Tactical Network, Satcom), EW (Samudrika, Sangraha), missile guidance. Revenue: \u20b922,000 crore FY25. (3) BDL (Bharat Dynamics Limited, 5 factories, Hyderabad): Akash SAM, Astra BVR, BrahMos (joint venture Russia), SRBM Pralay, Agni series ICBM. Revenue: \u20b98,500 crore FY25. (4) MIDHANI (Mishra Dhatu Nigam, Hyderabad): special alloys (maraging steel for gun barrels, titanium for missile bodies, tungsten for penetrators). India\u2019s ordnance logistics challenges: (a) Security classification: PROTECTED (restricted), RESTRICTED, CONFIDENTIAL, SECRET, TOP SECRET \u2014 each requiring different escort levels, documentation, and routing. (b) Escorts: CISF/CRPF for RESTRICTED, Army convoy with armed guards for PROTECTED, IAF C-17/C-130J for TOP SECRET. (c) Route planning: avoids civilian population centres, major highways during peak hours, border areas during escalation. (d) Storage: 41 CODs (Central Ordnance Depots), 200+ sub-depots, underground magazines for explosives (temperature 18-25 degrees Celsius, humidity 40-60%). India\u2019s defence import dependency: 60% of ordnance still imported (Russian 155mm shells during Kargil, Israeli Spike ATGM, French Rafale Meteor BVR). Indigenisation target: 65% by 2029 under Defence Procurement Procedure 2020 Category-I (Buy Indian IDDM). India\u2019s defence export: \u20b921,000 crore FY25 (BrahMos to Philippines, Akash to Armenia, Pinaka to Armenia, Dhanush 155mm to Armenia, Kalyani artillery to unspecified buyer).",
  },
  {
    t: "Artillery Ammunition Supply Chain: 155mm Bofors, Kalyani, Pinaka MBRL, Smerch Rocket",
    c: "India\u2019s artillery ammunition logistics: (1) 155mm/39-cal Bofors FH-77B: inducted 1987 (410 guns during Kargil 1999). Ammunition: HE (High Explosive), smoke, illuminating, cargo (cluster sub-munitions). Production: OF Ambarnath (300 shells/day), Kalyani Strategic Systems (new private-sector entrant, 100 shells/day). Annual consumption: 200,000+ rounds (Line of Actual Control plus training). Shell weight: 43 kg each. Rake: 42-inch rake on BOXN wagon (48 shells per rake, 2,064 kg). Logistics rail journey: Ambarnath to Ferozepur (2 days), Ambarnath to Leh (3 days via Pathankot-Manali-Leh highway, military convoy summer only). (2) 155mm/52-cal K9 Vajra: Samsung Techwin (now Hanwha) self-propelled howitzer, 100 ordered, L&T assembly. Ammunition compatible with Bofors. (3) 155mm/52-cal ATAGS (Advanced Towed Artillery Gun System): DRDO-designed, Tata/Kalyani production, 150+ ordered. Longer range (48 km vs 27 km Bofors). Requires new ammunition types. (4) Pinaka MBRL (Multi-Barrel Rocket Launcher): Mark-I (40 km), Mark-II (75 km), Mark-III (120 km, guided). Production: OFB Varangaon (rockets), Tata Aero (launcher). 12-launcher regiment = 288 rockets per volley. Rocket weight: 100-300 kg. Logistics: special climate-controlled storage for solid propellant rockets (15-25 degrees Celsius). Pinaka deployed in Kargil, Pulwama aftermath, and Eastern Ladakh standoff. (5) Smerch BM-30 (Russian): 90 km range, 12-tube launcher. 62,000 units imported from Russia. Ammunition imported (300mm rockets). (6) BrahMos: supersonic cruise missile (290 km range, Mach 2.8). Block-III: steep dive for mountain targets (Eastern Ladakh). Block-IV: land attack with terrain-hugging. Weight: 3,000 kg per missile. Logistics: IAF C-17 Globemaster III (can carry 2 BrahMos crates per sortie), heavy trailer convoy (road), special rail wagon. India\u2019s ammunition stockpile targets: 45-day war reserve (IA/IN/IAF combined), increased from 20-day (Kargil revealed shortfall). Current status: 40+ days for small arms, 30+ days for artillery, 15+ days for precision-guided munitions. Buffer augmentation: OFB annual production + 100% FMS (Foreign Military Sales) from Russia (emergency Kargil shells airlifted from Russia in 72 hours).",
  },
  {
    t: "Defence Security Protocols, Escort Procedures, and Ammunition Transport Regulations",
    c: "India\u2019s defence ordnance transport is governed by: (1) Defence Security Corps (DSC): provides static security at ordnance depots, factories, magazines (40,000+ personnel). (2) Central Industrial Security Force (CISF): escorts RESTRICTED/CONFIDENTIAL loads in transit (150,000+ personnel). (3) CRPF: escorts HIGH RISK loads through Naxal-affected areas (Chhattisgarh, Odisha, Jharkhand). (4) Army convoy: armed escort with officer, JCO, 10-20 OR for PROTECTED loads. (5) IAF special flight: C-17 Globemaster III, C-130J Hercules for TOP SECRET loads (missiles, classified radar). Air Transportable Cargo: C-17 capacity 77 tonnes, C-130J 20 tonnes, An-32 6.7 tonnes. Escort procedures: (a) Route reconnaissance: 24 hours before convoy departure, intelligence unit checks route for Naxal activity, traffic, weather. (b) Convoy composition: 2-3 escort vehicles (Gypsy, Tata Safari armoured), lead vehicle, ordnance truck, tail vehicle. Convoy speed: 40-50 km/h, no night movement for explosives. (c) Communication: convoy leader has SATCOM phone, VHF radio, GPS tracker. (d) Halts: every 2 hours or 100 km at pre-designated military stations (EME workshop, MES battalion). Ammunition storage regulations: (a) Explosive quantity distance (EQD): minimum separation between explosive stacks (varies by type: TNT 15m, RDX 25m, gunpowder 10m). (b) Lightning protection: all magazines have lightning arrestors (ESE system, 60m rolling sphere). (c) Fire fighting: automatic sprinkler, foam, and CO2 systems. Fire water tank: 50,000 litres per magazine. (d) Temperature: 18-25 degrees Celsius for propellants and explosives (air conditioning in high-temperature zones like Jaisalmer). (e) Humidity: 40-60% for metallic ammunition (dehumidifiers required in coastal magazines like Mumbai, Kochi). Transportation documentation: (a) Form A: movement order (signed by Base Commander). (b) Form B: ammunition particulars (type, quantity, lot number, security classification). (c) Form C: escort details (escort unit, personnel strength, weapons). (d) Form D: route plan (waypoints, halts, alternate routes). All forms archived for 10 years. India\u2019s defence logistics digitization: (a) Defence Inventory Management System (DIMS): RFID tracking of all ordnance items above RESTRICTED. (b) Integrated Defence Logistics (IDL): planned single platform for Army/Navy/Air Force logistics (pilot by IAF). (c) GIS-based route planning: MOD using ISRO Bhuvan for convoy route optimization. (d) Blockchain: pilot for ammunition traceability (lot number to end-user).",
  },
  {
    t: "Missile Systems India: BrahMos, Akash, Astra, Pralay, Agni Series and Warhead Logistics",
    c: "India\u2019s missile systems require the highest security classification (TOP SECRET) for logistics: (1) BrahMos (Joint venture: DRDO India + NPO Mashinostroyeniya Russia): Supersonic cruise missile 290 km range, Mach 2.8, 300 kg semi-armor-piercing warhead. Variants: Block-I (ship/land), Block-II (air-launched Su-30MKI), Block-III (steep dive mountain), Block-IV (terrain-hugging land attack with man-in-loop). Weight: 3,000 kg (air), 4,500 kg (land). Production: 200+ missiles/year (BDL Hyderabad, BrahMos Aerospace Thiruvananthapuram). Export: Philippines (shore-based anti-ship, \u20b93,750 crore), Indonesia (under negotiation). Logistics: IAF C-17 (2 missiles/flight, Hyderabad to forward base in 4 hours), heavy trailer (road, 3-5 days with armed CISF escort). Storage: climate-controlled bunker (15-25 degrees Celsius, inert atmosphere). Warhead: semi-armor-piercing high-explosive (HESA), separate from missile body during storage (assembled at launch site). (2) Akash SAM (DRDO/BEL/BDL): medium-range surface-to-air missile, 25 km range, Mach 2.5, 60 kg warhead. India ordered 10 squadrons (2,400 missiles) at \u20b915,000 crore. Production: BEL (radar, control), BDL (missile). Export: Armenia (\u20b96,000 crore, 4 squadrons). Logistics: army convoy with radar launcher in sections (3 vehicles per launcher: radar, command, launcher). (3) Astra BVR (DRDO): beyond-visual-range air-to-air missile, 100+ km range, active radar homing, 15 kg warhead. Integrated on Su-30MKI, Tejas Mk1A, Mirage 2000. Production: BDL Hyderabad (100+/year). Logistics: air transport in sealed containers, handled by IAF munitions specialists. (4) Pralay SRBM (DRDO): quasi-ballistic tactical missile, 150-500 km range, 200-500 kg warhead (conventional), Mach 5+. India\u2019s answer to Iskander (Russia) and ATACMS (US). First regiment ordered (120 missiles). Logistics: TEL (Transporter Erector Launcher) convoy with separate warhead vehicle (warhead mated at firing position). (5) Agni series ICBM: Agni-I (700 km, army), Agni-II (2,000 km, army), Agni-III (3,500 km, army), Agni-IV (4,000 km, SFC), Agni-V (5,000+ km, SFC). Agni-V canisterized: can be launched from road-mobile TEL within 30 minutes. Storage: hardened underground silos (SFC, Secunderabad). Weight: 50,000 kg (Agni-V with canister). Transport: special 12-axle trailer (SFC-managed), no rail or air transport due to size and classification. Warhead: nuclear (yield: 12-250 kT, thermonuclear capability). Fissile material: plutonium (BARC, Mumbai) and enriched uranium (NPC, Hyderabad). Warhead logistics is managed by DRDO and SFC with dedicated nuclear command authority (PM, NSA, three-service chiefs). India\u2019s missile defence: BMD (Ballistic Missile Defence) Phase-I operational (Delhi, Mumbai), PAD/AAD interceptors at 50 km (endo) and 150 km (exo).",
  },
];

export default function DefenceOrdnanceLogisticsView() {
  const [tab, setTab] = useState(0);
  const [activeFilters, setActiveFilters] = useState<Record<string, string[]>>({});
  const [search, setSearch] = useState("");

  const filterGroups = [
    { key: "status", label: "Status", options: SHIPMENT_STATUSES.map(s => ({ value: s, count: records.filter(rec => rec.status === s).length })) },
    { key: "category", label: "Category", options: CATEGORIES.map(c => ({ value: c, count: records.filter(rec => rec.category === c).length })) },
    { key: "zone", label: "Zone", options: ZONES.map(z => ({ value: z, count: records.filter(rec => rec.zone === z).length })) },
    { key: "mode", label: "Mode", options: MODES.map(m => ({ value: m, count: records.filter(rec => rec.mode === m).length })) },
  ];

  const toggleFilter = (k: string, v: string) => setActiveFilters(p => (function(){ const n={...p}; n[k]=(p[k]||[]).filter(x=>x!==v); if(n[k].length===0) delete n[k]; return n })());

  const filtered = records.filter(r => {
    if (search) {
      const q = search.toLowerCase();
      if (!r.id.toLowerCase().includes(q) && !r.consignmentNo.toLowerCase().includes(q) && !r.arsenal.toLowerCase().includes(q) && !r.description.toLowerCase().includes(q) && !r.destination.toLowerCase().includes(q) && !r.unitCommand.toLowerCase().includes(q)) return false;
    }
    return Object.entries(activeFilters).every(([k, vs]) => vs.includes(r[k as keyof ShipmentRecord] as string));
  });

  return (
    <div className="dol-root p-6 space-y-6">
      <PageHeader title="Defence Ordnance Logistics" description="Indian defence ordnance supply chain covering OFB AVNL BEL BDL MIDHANI, artillery 155mm Bofors Kalyani, missile BrahMos Akash Astra Pralay, small arms INSAS AK-203, demolition explosives, armoured T-90 Arjun spares, DQA inspection and armed escort convoy logistics" />
      <div className="dol-tabs flex gap-1 border-b border-gray-200">
        {TABS.map((t, i) => (<button key={t} onClick={() => setTab(i)} className={`dol-tab px-4 py-2 text-sm font-medium rounded-t ${tab === i ? "bg-red-800 text-white" : "text-gray-600 hover:bg-red-50"}`}>{t}</button>))}
      </div>

      {tab === 0 && (
        <div className="dol-dash space-y-6">
          <div className="dol-kpis grid grid-cols-4 gap-4">
            {kpis.map(k => (<div key={k.l} className="dol-kpi bg-white rounded-lg border p-4"><div className="text-xs text-gray-500 dol-kpi-label">{k.l}</div><div className="text-2xl font-bold text-red-800 dol-kpi-val">{k.v}</div><div className="text-xs text-gray-400 dol-kpi-sub">{k.s}</div></div>))}
          </div>
          <div className="grid grid-cols-2 gap-6">
            <div className="dol-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Monthly Ordnance Shipments (Batches)</h3><BarChart data={monthlyShipments} height={220}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="m" /><YAxis /><Tooltip /><Legend /><Bar dataKey="artillery" fill="#4a1d1d" radius={[4,4,0,0]} name="Artillery" /><Bar dataKey="smallArms" fill="#6b2c2c" radius={[4,4,0,0]} name="Small Arms" /><Bar dataKey="missile" fill="#8b3a3a" radius={[4,4,0,0]} name="Missile" /><Bar dataKey="vehicle" fill="#a84444" radius={[4,4,0,0]} name="Vehicle" /></BarChart></div>
            <div className="dol-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Ordnance Category Distribution</h3><PieChart width={400} height={220}><Pie data={categoryDist} dataKey="v" nameKey="n" cx="50%" cy="50%" outerRadius={80} label>{categoryDist.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}</Pie><Tooltip /></PieChart></div>
          </div>
          <div className="grid grid-cols-2 gap-6">
            <div className="dol-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Ordnance Readiness Rate (%) vs 95% Target</h3><LineChart data={readinessRate} height={220}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="m" /><YAxis domain={[85, 100]} /><Tooltip /><Legend /><Line type="monotone" dataKey="actual" stroke="#4a1d1d" strokeWidth={2} name="Actual %" /><Line type="monotone" dataKey="target" stroke="#dc2626" strokeWidth={2} strokeDasharray="5 5" name="Target" /></LineChart></div>
            <div className="dol-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Command Performance Score</h3><BarChart data={commandPerf} height={220}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="n" tick={{ fontSize: 9 }} /><YAxis domain={[80, 100]} /><Tooltip /><Bar dataKey="v" fill="#6b2c2c" radius={[4,4,0,0]} name="Score" /></BarChart></div>
          </div>
        </div>
      )}

      {tab === 1 && (
        <div className="dol-registry space-y-4">
          <ModuleBreadcrumb items={[{ label: "Defence Ordnance", href: "#" }, { label: "Shipment Registry", href: "#" }]} />
          <SearchFilterToolbar searchQuery={search} onSearchChange={setSearch} onClearSearch={() => setSearch("")} activeFilters={activeFilters} filterGroups={filterGroups} onToggleFilter={toggleFilter} onClearAllFilters={() => setActiveFilters({})} totalItems={records.length} filteredCount={filtered.length} />
          <div className="dol-table-wrap overflow-x-auto bg-white rounded-lg border">
            <table className="w-full text-sm"><thead><tr className="border-b bg-gray-50">{"ID,Consignment,Arsenal,Zone,Category,Description,Weight,Origin,Destination,Command,Mode,Dispatch,ETA,Transit (d),Value (\u20b9Cr),Security,Status,Remarks"
                .split(",").map(h => (<th key={h} className="px-3 py-2 text-left text-xs font-medium text-gray-500 whitespace-nowrap">{h}</th>))}</tr></thead>
            <tbody>{filtered.map(r => {
              const rowCls = r.status === "Armed Escort Transit" ? "dol-row-critical bg-red-50" : r.status === "Quality Inspection DQA" || r.status === "Base Loading Dock" ? "dol-row-warning bg-amber-50" : r.status === "Military Convoy Moving" ? "dol-row-info bg-blue-50" : "";
              return (<tr key={r.id} className={`border-b hover:bg-red-50/30 ${rowCls}`}>
                <td className="px-3 py-2 font-mono font-medium">{r.id}</td>
                <td className="px-3 py-2"><span className="dol-badge inline-block px-2 py-0.5 rounded text-xs bg-red-800 text-white font-mono text-[10px]">{r.consignmentNo}</span></td>
                <td className="px-3 py-2 text-xs max-w-28 truncate">{r.arsenal}</td>
                <td className="px-3 py-2"><span className="dol-badge inline-block px-2 py-0.5 rounded text-xs bg-gray-100 text-gray-700">{r.zone}</span></td>
                <td className="px-3 py-2"><span className="dol-badge inline-block px-2 py-0.5 rounded text-xs bg-gray-100 text-gray-700">{r.category}</span></td>
                <td className="px-3 py-2 text-xs max-w-32 truncate">{r.description}</td>
                <td className="px-3 py-2 text-xs text-right font-semibold">{r.weight >= 1000 ? `${(r.weight/1000).toFixed(1)}T` : `${r.weight}kg`}</td>
                <td className="px-3 py-2 text-xs max-w-24 truncate">{r.origin}</td>
                <td className="px-3 py-2 text-xs max-w-24 truncate">{r.destination}</td>
                <td className="px-3 py-2 text-xs">{r.unitCommand}</td>
                <td className="px-3 py-2 text-xs">{r.mode}</td>
                <td className="px-3 py-2 text-xs">{r.dispatchDate}</td>
                <td className="px-3 py-2 text-xs">{r.etaDate}</td>
                <td className="px-3 py-2"><span className={`text-xs font-semibold ${r.transitDays >= 4 ? "text-red-600" : r.transitDays >= 2 ? "text-amber-600" : "text-green-600"}`}>{r.transitDays}d</span></td>
                <td className="px-3 py-2 text-xs font-semibold text-red-800">{r.valueCr >= 100 ? `\u20b9${r.valueCr}Cr` : r.valueCr >= 1 ? `\u20b9${r.valueCr}Cr` : `\u20b9${(r.valueCr*100).toFixed(0)}L`}</td>
                <td className="px-3 py-2 text-center">{r.securityClass === "TOP SEC" ? <span className="dol-badge inline-block px-2 py-0.5 rounded text-xs bg-black text-white font-bold">TOP SEC</span> : r.securityClass === "RESTR" ? <span className="dol-badge inline-block px-2 py-0.5 rounded text-xs bg-orange-500 text-white">RESTR</span> : <span className="text-gray-400">PROT</span>}</td>
                <td className="px-3 py-2"><span className={`dol-badge inline-block px-2 py-0.5 rounded text-xs font-semibold ${SC[statusColor[r.status]]}`}>{r.status}</span></td>
                <td className="px-3 py-2 text-xs text-gray-500 max-w-32 truncate">{r.remarks}</td>
              </tr>);
            })}</tbody></table>
          </div>
        </div>
      )}

      {tab === 2 && (
        <div className="dol-analytics space-y-6">
          <div className="grid grid-cols-2 gap-6">
            <div className="dol-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Ordnance Volume by Command</h3><BarChart data={ZONES.map(z => ({ n: z.split(" ").slice(0, 1).join(" "), v: +ri(12, 35, 22 + Math.random() * 8).toFixed(0) }))} height={240}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="n" tick={{ fontSize: 9 }} /><YAxis /><Tooltip /><Bar dataKey="v" fill="#4a1d1d" radius={[4,4,0,0]} name="Shipments" /></BarChart></div>
            <div className="dol-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Volume by Category Corridor</h3><AreaChart data={Array.from({ length: 12 }, (_, i) => ({ m: MO[i], artillery: ri(4, 10, 7 + Math.sin(i*0.5)*2), smallArms: ri(8, 20, 14 + Math.cos(i*0.6)*3), missile: ri(1, 4, 2.5 + Math.sin(i*0.7)*0.8) }))} height={240}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="m" /><YAxis /><Tooltip /><Legend /><Area type="monotone" dataKey="artillery" stackId="1" stroke="#4a1d1d" fill="#d47070" name="Artillery" /><Area type="monotone" dataKey="smallArms" stackId="1" stroke="#6b2c2c" fill="#a84444" name="Small Arms" /><Area type="monotone" dataKey="missile" stackId="1" stroke="#8b3a3a" fill="#c45252" name="Missile" /></AreaChart></div>
          </div>
          <div className="dol-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Avg Transit Days by Transport Mode</h3><BarChart data={[{n:"Mil Truck 10T",v:2},{n:"Armed Rail",v:3},{n:"C-17 Globemaster",v:0.5},{n:"Navy LCU",v:5},{n:"Heavy Trailer",v:2.5},{n:"Helicopter Sling",v:0.3}].map(d => ({...d, v: +ri(d.v*0.7, d.v*1.3, d.v + Math.random()*0.4).toFixed(1)}))} height={240}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="n" tick={{ fontSize: 9 }} /><YAxis /><Tooltip /><Bar dataKey="v" fill="#6b2c2c" radius={[4,4,0,0]} name="Days" /></BarChart></div>
        </div>
      )}

      {tab === 3 && (
        <div className="dol-insights grid grid-cols-2 gap-6">{INSIGHTS.map(ins => (<div key={ins.t} className="dol-insight bg-white rounded-lg border p-5"><h3 className="text-base font-bold text-red-900 mb-2">{ins.t}</h3><p className="text-sm text-gray-600 leading-relaxed">{ins.c}</p></div>))}</div>
      )}
    </div>
  );
}
