// ============================================================================
// AutoFlow Logistics - Module Views Exports
// ============================================================================

export { WarehousesView } from './warehouses-view'
export { InboundView } from './inbound-view'
export { OutboundView } from './outbound-view'
export { InventoryView } from './inventory-view'
export { InventoryReplenishmentView } from './inventory-replenishment-view'
export { TransportationView } from './transportation-view'
export { RouteOptimizationView } from './route-optimization-view'
export { EquipmentView } from './equipment-view'
export { EmployeesView } from './employees-view'
export { ProductivityView } from './productivity-view'
export { CostAnalyticsView } from './cost-analytics-view'
export { AlertsView } from './alerts-view'
export { ReportsView } from './reports-view'
export { SettingsView } from './settings-view'
export { DockSchedulerView } from './dock-scheduler-view'
export { WarehouseMapView } from './warehouse-map-view'
export { SLACountdownView } from './sla-countdown-view'
export { OperationsOverviewView } from './operations-overview-view'
export { SupplierQualityScorecardView } from './supplier-quality-scorecard-view'
export { ProcurementPurchaseOrdersView } from './procurement-purchase-orders-view'
export { BillOfMaterialsView } from './bill-of-materials-view'
export { QualityInspectionPlanView } from './quality-inspection-plan-view'
export { NonConformanceReportView } from './non-conformance-report-view'
export { WorkOrderManagementView } from './work-order-management-view'
export { ProductionScheduleView } from './production-schedule-view'
export { ProductionCostVarianceView } from './production-cost-variance-view'
export { InventoryValuationView } from './inventory-valuation-view'
export { DemandForecastingView } from './demand-forecasting-view'
export { SupplierCorrectiveActionRequestView } from './supplier-corrective-action-request-view'
export { ContinualImprovementView } from './continual-improvement-view'
export { FixedAssetRegisterView } from './fixed-asset-register-view'
export { SupplierAuditView } from './supplier-audit-view'
export { ESGSustainabilityAuditView } from './esg-sustainability-audit-view'
export { CapacityPlanningView } from './capacity-planning-view'
export { WarehousePerformanceScorecardView } from './warehouse-performance-scorecard-view'
export { ThreeWayMatchDashboardView } from './three-way-match-dashboard-view'
export { VendorContractManagementView } from './vendor-contract-management-view'
export { SafetyIncidentManagementView } from './safety-incident-management-view'
export { FleetMaintenanceManagementView } from './fleet-maintenance-management-view'
export { CargoDamageClaimsView } from './cargo-damage-claims-view'
export { default as CrossDockTransshipmentView } from './cross-dock-transshipment-view'
export { default as ColdChainTemperatureView } from './cold-chain-temperature-view'
export { default as ContainerFreightStationView } from './container-freight-station-view'
export { default as HazmatDangerousGoodsView } from './hazmat-dangerous-goods-view'
export { default as SerialNumberTrackingView } from './serial-number-tracking-view'
export { default as EcommerceFulfillmentView } from './ecommerce-fulfillment-view'
export { default as LaborManagementView } from './labor-management-view'
export { default as PackagingStandardsView } from './packaging-standards-view'
export { default as SlottingOptimizationView } from './slotting-optimization-view'
export { default as WavePlanningView } from './wave-planning-view'
export { default as StockTransferView } from './stock-transfer-view'
export { default as BarcodeLabelView } from './barcode-label-view'
export { default as CycleCountView } from './cycle-count-view'
export { default as ReturnsProcessingView } from './returns-processing-view'
export { default as PutawayManagementView } from './putaway-management-view'
export { default as LoadingDispatchView } from './loading-dispatch-view'
// Bug 33-AUDIT#10 (MEDIUM) cleanup: removed WarehouseDetailModal export.
// The legacy modal was replaced by WarehouseDetailDrawer in R32; this file
// (warehouse-detail-modal.tsx) is now dead code and will be deleted.
export { default as GoodsReceiptView } from './goods-receipt-view'
export { default as TallyIntegrationView } from './tally-integration-view'
export { default as KittingAssemblyView } from './kitting-assembly-view'
export { default as BatchLotView } from './batch-lot-view'
export { default as ConsignmentStockView } from './consignment-stock-view'
export { default as PoolDistributionView } from './pool-distribution-view'
export { default as ThirdPartyLogisticsView } from './third-party-logistics-view'
export { default as DocumentManagementView } from './document-management-view'
export { default as MultiChannelFulfillmentView } from './multi-channel-fulfillment-view'
export { default as QualityControlView } from './quality-control-view'
export { default as VehicleFleetTransportView } from './vehicle-fleet-transport-view'
export { default as CustomerServiceResolutionView } from './customer-service-resolution-view'
export { default as WarehouseAnalyticsBIView } from './warehouse-analytics-bi-view'
export { default as ReturnsRefundAnalyticsView } from './returns-refund-analytics-view'
export { default as PickPackOptimizationView } from './pick-pack-optimization-view'
export { default as FreightShippingRateView } from './freight-shipping-rate-view'
export { default as DockSchedulingYardView } from './dock-scheduling-yard-view'
export { default as DangerousGoodsHazMatView } from './dangerous-goods-hazmat-view'
export { default as CustomsDutyGstView } from './customs-duty-gst-view'
export { default as PalletContainerView } from './pallet-container-view'
export { default as ReturnsQualityInspectionView } from './returns-quality-inspection-view'
export { default as CODPaymentReconciliationView } from './cod-payment-reconciliation-view'
export { default as WarrantyGuaranteeView } from './warranty-guarantee-view'
export { default as InsuranceClaimsView } from './insurance-claims-view'
export { default as LastMileDeliveryView } from './last-mile-delivery-view'
export { default as MultiChannelIntegrationHubView } from './multi-channel-integration-hub-view'
export { default as SupplierPortalView } from './supplier-portal-view'
export { default as HyperlocalDeliveryView } from './hyperlocal-delivery-view'
export { default as CarbonFootprintTrackerView } from './carbon-footprint-tracker-view'
export { default as SmartLockerKioskView } from './smart-locker-kiosk-view'
export { default as WarehouseDigitalTwinView } from './warehouse-digital-twin-view'
export { default as AGVFleetManagementView } from './agv-fleet-management-view'
export { default as ParcelSortingCrossDockView } from './parcel-sorting-crossdock-view'
export { default as WarehouseSafetyComplianceView } from './warehouse-safety-compliance-view'
export { default as GoodsToPersonPickingView } from './goods-to-person-picking-view'
export { default as ValueAddedServicesView } from './value-added-services-view'
export { default as GateSecurityView } from './gate-security-view'
export { default as YardTruckingView } from './yard-trucking-dock-view'
export { default as PackagingDesignStudioView } from './packaging-design-studio-view'
export { default as WarehouseLaborForecastingView } from './warehouse-labor-forecasting-view'
export { default as ReturnsConsolidationHubView } from './returns-consolidation-hub-view'
export { default as ThreePLPerformanceScorecardView } from './3pl-performance-scorecard-view'
export { default as QualityInspectionAutomationView } from './quality-inspection-automation-view'
export { default as SupplierRiskManagementView } from './supplier-risk-management-view'
export { default as PredictiveDemandForecastingView } from './predictive-demand-forecasting-view'
export { default as LogisticsNetworkOptimizationView } from './logistics-network-optimization-view'
export { default as ContractComplianceAutomationView } from './contract-compliance-automation-view'
export { default as LastMileDeliveryAnalyticsView } from './last-mile-delivery-analytics-view'
export { default as ReturnsProcessingEnhancementView } from './returns-processing-enhancement-view'
export { default as ColdChainMonitoringView } from './cold-chain-monitoring-view'

