// ============================================================================
// AutoFlow Logistics - Module Views Exports
// ============================================================================

export { WarehousesView } from './warehouses-view'
export { InboundView } from './inbound-view'
export { OutboundView } from './outbound-view'
export { InventoryView } from './inventory-view'
export { InventoryReplenishmentView } from './inventory-replenishment-view'
export { TransportationView } from './transportation-view'
export { RouteOptimizationView } from './route-optimization-view'
export { EquipmentView } from './equipment-view'
export { EmployeesView } from './employees-view'
export { ProductivityView } from './productivity-view'
export { CostAnalyticsView } from './cost-analytics-view'
export { AlertsView } from './alerts-view'
export { ReportsView } from './reports-view'
export { SettingsView } from './settings-view'
export { DockSchedulerView } from './dock-scheduler-view'
export { WarehouseMapView } from './warehouse-map-view'
export { SLACountdownView } from './sla-countdown-view'
export { OperationsOverviewView } from './operations-overview-view'
export { SupplierQualityScorecardView } from './supplier-quality-scorecard-view'
export { ProcurementPurchaseOrdersView } from './procurement-purchase-orders-view'
export { BillOfMaterialsView } from './bill-of-materials-view'
export { QualityInspectionPlanView } from './quality-inspection-plan-view'
export { NonConformanceReportView } from './non-conformance-report-view'
export { WorkOrderManagementView } from './work-order-management-view'
export { ProductionScheduleView } from './production-schedule-view'
export { ProductionCostVarianceView } from './production-cost-variance-view'
export { InventoryValuationView } from './inventory-valuation-view'
export { DemandForecastingView } from './demand-forecasting-view'
export { SupplierCorrectiveActionRequestView } from './supplier-corrective-action-request-view'
export { ContinualImprovementView } from './continual-improvement-view'
export { FixedAssetRegisterView } from './fixed-asset-register-view'
export { SupplierAuditView } from './supplier-audit-view'
export { ESGSustainabilityAuditView } from './esg-sustainability-audit-view'
export { CapacityPlanningView } from './capacity-planning-view'
export { WarehousePerformanceScorecardView } from './warehouse-performance-scorecard-view'
export { ThreeWayMatchDashboardView } from './three-way-match-dashboard-view'
export { VendorContractManagementView } from './vendor-contract-management-view'
export { SafetyIncidentManagementView } from './safety-incident-management-view'
export { FleetMaintenanceManagementView } from './fleet-maintenance-management-view'
export { CargoDamageClaimsView } from './cargo-damage-claims-view'
export { default as CrossDockTransshipmentView } from './cross-dock-transshipment-view'
export { default as ColdChainTemperatureView } from './cold-chain-temperature-view'
export { default as ContainerFreightStationView } from './container-freight-station-view'
export { default as HazmatDangerousGoodsView } from './hazmat-dangerous-goods-view'
export { default as SerialNumberTrackingView } from './serial-number-tracking-view'
export { default as EcommerceFulfillmentView } from './ecommerce-fulfillment-view'
export { default as LaborManagementView } from './labor-management-view'
export { default as PackagingStandardsView } from './packaging-standards-view'
export { default as SlottingOptimizationView } from './slotting-optimization-view'
export { default as WavePlanningView } from './wave-planning-view'
export { default as StockTransferView } from './stock-transfer-view'
export { default as BarcodeLabelView } from './barcode-label-view'
export { default as CycleCountView } from './cycle-count-view'
export { default as ReturnsProcessingView } from './returns-processing-view'
export { default as PutawayManagementView } from './putaway-management-view'
export { default as LoadingDispatchView } from './loading-dispatch-view'
// Bug 33-AUDIT#10 (MEDIUM) cleanup: removed WarehouseDetailModal export.
// The legacy modal was replaced by WarehouseDetailDrawer in R32; this file
// (warehouse-detail-modal.tsx) is now dead code and will be deleted.
export { default as GoodsReceiptView } from './goods-receipt-view'
export { default as TallyIntegrationView } from './tally-integration-view'
export { default as KittingAssemblyView } from './kitting-assembly-view'
export { default as BatchLotView } from './batch-lot-view'
