"use client";

import React, { useState, useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { PageHeader } from '@/components/shared';
import { Battery } from 'lucide-react';

interface LithiumMetalRecord {
  id: string;
  batchNo: string;
  city: string;
  manufacturer: string;
  metalGrade: string;
  application: string;
  purityPercent: number;
  densityGcm3: number;
  investmentCr: number;
  status: string;
  priority: string;
  origin: string;
  destination: string;
  shipDate: string;
  transitDays: number;
  zone: string;
  remarks: string;
}

const lithiumMetalRecords: LithiumMetalRecord[] = [
  { id: 'LIT-0001', batchNo: 'LIT-B2401', city: 'Bengaluru', manufacturer: 'Tata Advanced Materials', metalGrade: 'Li 99.9% Battery Grade', application: 'EV Battery Cell (Tata Motors)', purityPercent: 99.9, densityGcm3: 0.534, investmentCr: 720, status: 'Delivered', priority: 'Critical', origin: 'Tata Advanced Materials Bengaluru (KA)', destination: 'Tata Motors Pune (MH)', shipDate: '2026-07-15', transitDays: 1, zone: 'South', remarks: 'Li metal anode for Tata Nexon EV solid-state battery pack &#8594; 99.9% Li &#8594; &#8377;720Cr for 0.3 tonnes &#8594; India &#8377;21,600Cr Li metal &#8594; Tata 500K EV &#8594; 0.534 g/cm3 &#8594; 180&#176;C &#8594; 3860 mAh/g &#8594; anode-free' },
  { id: 'LIT-0002', batchNo: 'LIT-B2402', city: 'Hyderabad', manufacturer: 'DRDO DMRL', metalGrade: 'Li 99.99% Aerospace', application: 'Satellite Battery (ISRO)', purityPercent: 99.99, densityGcm3: 0.534, investmentCr: 580, status: 'Delivered', priority: 'Critical', origin: 'DRDO DMRL Hyderabad (TG)', destination: 'ISRO Ahmedabad (GJ)', shipDate: '2026-07-16', transitDays: 2, zone: 'South', remarks: 'Ultra-pure Li for ISRO GSAT satellite Li-ion cell manufacturing &#8594; 99.99% Li &#8594; &#8377;580Cr for 0.1 tonnes &#8594; India &#8377;17,400Cr space Li &#8594; ISRO 18 sats &#8594; 0.534 g/cm3 &#8594; &#8594; NCA cathode &#8594; 150 Wh/kg &#8594; LEO' },
  { id: 'LIT-0003', batchNo: 'LIT-B2403', city: 'Mumbai', manufacturer: 'Reliance New Energy', metalGrade: 'Li 99.95% Cell Grade', application: 'Grid Storage Battery (Adani Green)', purityPercent: 99.95, densityGcm3: 0.534, investmentCr: 650, status: 'Delivered', priority: 'Critical', origin: 'Reliance Jamnagar (GJ)', destination: 'Adani Green Mumbai (MH)', shipDate: '2026-07-17', transitDays: 1, zone: 'West', remarks: 'Li metal foil for Adani Green 5 MWh grid storage solid-state battery &#8594; 99.95% Li &#8594; &#8377;650Cr for 0.5 tonnes &#8594; India &#8377;19,500Cr grid Li &#8594; Adani 10 GWh &#8594; 0.534 g/cm3 &#8594; &#8594; LFP cathode &#8594; 400 Wh/L &#8594; BESS' },
  { id: 'LIT-0004', batchNo: 'LIT-B2404', city: 'Pune', manufacturer: 'Bharat Forge', metalGrade: 'Li-Al 20/80 Alloy', application: 'Defence Pack (BEL)', purityPercent: 80.0, densityGcm3: 1.57, investmentCr: 420, status: 'Delivered', priority: 'High', origin: 'Bharat Forge Pune (MH)', destination: 'BEL Bengaluru (KA)', shipDate: '2026-07-18', transitDays: 1, zone: 'West', remarks: 'Li-Al alloy anode for BEL military manpack solid-state battery &#8594; 20% Li 80% Al &#8594; &#8377;420Cr for 1 tonne &#8594; India &#8377;12,600Cr defence Li &#8594; BEL 50K packs &#8594; 1.57 g/cm3 &#8594; &#8594; 250 Wh/kg &#8594; &#8594; 1000 cycles' },
  { id: 'LIT-0005', batchNo: 'LIT-B2405', city: 'Chennai', manufacturer: 'IGCAR', metalGrade: 'Li 99.999% Nuclear Grade', application: 'Fusion Blanket Breeder (IPPRG)', purityPercent: 99.999, densityGcm3: 0.534, investmentCr: 890, status: 'Delivered', priority: 'Critical', origin: 'IGCAR Kalpakkam (TN)', destination: 'IPPRG Gandhinagar (GJ)', shipDate: '2026-07-19', transitDays: 2, zone: 'South', remarks: 'Ultra-high purity Li for Indian fusion reactor blanket tritium breeding &#8594; 99.999% Li &#8594; &#8377;890Cr for 0.2 tonnes &#8594; India &#8377;26,700Cr fusion Li &#8594; IPPRG DEMO &#8594; 0.534 g/cm3 &#8594; &#8594; Li4SiO4 &#8594; 800&#176;C &#8594; T breeding' },
  { id: 'LIT-0006', batchNo: 'LIT-B2406', city: 'Ahmedabad', manufacturer: 'Gujarat Lithium Tech', metalGrade: 'Li 99.9% Pharma Grade', application: 'Li-CO2 Battery (Lupin)', purityPercent: 99.9, densityGcm3: 0.534, investmentCr: 340, status: 'Delivered', priority: 'High', origin: 'Gujarat Lithium Tech Ahmedabad (GJ)', destination: 'Lupin Pune (MH)', shipDate: '2026-07-20', transitDays: 1, zone: 'West', remarks: 'Li metal for Lupin pharma medical device Li-CO2 battery R&amp;D &#8594; 99.9% Li &#8594; &#8377;340Cr for 0.1 tonnes &#8594; India &#8377;10,200Cr pharma Li &#8594; Lupin 2000 devices &#8594; 0.534 g/cm3 &#8594; &#8594; Li2CO3 &#8594; 280 Wh/kg &#8594; implantable' },
  { id: 'LIT-0007', batchNo: 'LIT-B2407', city: 'Jaipur', manufacturer: 'Rajasthan Lithium Corp', metalGrade: 'Li-Mg 15/85 Alloy', application: 'EV Lightweight Pack (Mahindra)', purityPercent: 85.0, densityGcm3: 1.24, investmentCr: 510, status: 'Delivered', priority: 'High', origin: 'Rajasthan Lithium Corp Jaipur (RJ)', destination: 'Mahindra Chennai (TN)', shipDate: '2026-07-21', transitDays: 2, zone: 'North', remarks: 'Li-Mg alloy foil for Mahindra XUV400 high-energy solid-state battery &#8594; 15% Li 85% Mg &#8594; &#8377;510Cr for 0.8 tonnes &#8594; India &#8377;15,300Cr auto Li &#8594; Mahindra 200K EV &#8594; 1.24 g/cm3 &#8594; &#8594; 350 Wh/kg &#8594; &#8594; dendrite-free' },
  { id: 'LIT-0008', batchNo: 'LIT-B2408', city: 'Bhubaneswar', manufacturer: 'NALCO', metalGrade: 'Li 99.5% Ingot', application: 'Industrial Grease (IOC)', purityPercent: 99.5, densityGcm3: 0.534, investmentCr: 180, status: 'Delivered', priority: 'Medium', origin: 'NALCO Bhubaneswar (OD)', destination: 'IOC Paradip (OD)', shipDate: '2026-07-22', transitDays: 1, zone: 'East', remarks: 'Li metal for IOC lubricating grease lithium stearate production &#8594; 99.5% Li &#8594; &#8377;180Cr for 2 tonnes &#8594; India &#8377;5,400Cr industrial Li &#8594; IOC 35 MT &#8594; 0.534 g/cm3 &#8594; &#8594; LiOH &#8594; 180&#176;C &#8594; NLGI #2' },
  { id: 'LIT-0009', batchNo: 'LIT-B2409', city: 'Coimbatore', manufacturer: 'Tamil Nadu Lithium', metalGrade: 'Li-Si 30/70 Nanowire', application: 'Li-S Battery Pack (Exicom)', purityPercent: 70.0, densityGcm3: 1.15, investmentCr: 580, status: 'Delivered', priority: 'High', origin: 'Tamil Nadu Lithium Coimbatore (TN)', destination: 'Exicom Gurgaon (HR)', shipDate: '2026-07-23', transitDays: 3, zone: 'South', remarks: 'Li-Si nanowire anode for Exicom 2W/3W Li-S electric two-wheeler battery &#8594; 30% Li 70% Si &#8594; &#8377;580Cr for 0.4 tonnes &#8594; India &#8377;17,400Cr mobility Li &#8594; Exicom 500K packs &#8594; 1.15 g/cm3 &#8594; &#8594; 500 Wh/kg &#8594; &#8594; S cathode' },
  { id: 'LIT-0010', batchNo: 'LIT-B2410', city: 'Surat', manufacturer: 'Gujarat Li Products', metalGrade: 'Li 99.9% Ribbon', application: 'Hearing Aid Battery (Wipro)', purityPercent: 99.9, densityGcm3: 0.534, investmentCr: 220, status: 'Delivered', priority: 'Medium', origin: 'Gujarat Li Products Surat (GJ)', destination: 'Wipro Bengaluru (KA)', shipDate: '2026-07-24', transitDays: 2, zone: 'West', remarks: 'Li ribbon for Wipro medical hearing aid Li-ion micro battery &#8594; 99.9% Li &#8594; &#8377;220Cr for 0.05 tonnes &#8594; India &#8377;6,600Cr medical Li &#8594; Wipro 5M devices &#8594; 0.534 g/cm3 &#8594; &#8594; 200 Wh/kg &#8594; &#8594; micro cell' },
  { id: 'LIT-0011', batchNo: 'LIT-B2411', city: 'Guwahati', manufacturer: 'Assam Lithium Metals', metalGrade: 'Li-B 3/97 Master Alloy', application: 'Al-Li Alloy Forging (HAL)', purityPercent: 97.0, densityGcm3: 2.35, investmentCr: 460, status: 'Delivered', priority: 'High', origin: 'Assam Lithium Metals Guwahati (AS)', destination: 'HAL Bengaluru (KA)', shipDate: '2026-07-25', transitDays: 4, zone: 'East', remarks: 'Li-B master alloy for HAL Tejas Mk2 Al-Li 2195 wing forging &#8594; 3% Li 97% B &#8594; &#8377;460Cr for 0.2 tonnes &#8594; India &#8377;13,800Cr aero Li &#8594; HAL 123 Tejas &#8594; 2.35 g/cm3 &#8594; &#8594; Al-Li &#8594; 520&#176;C &#8594; &#8594; 8% wt reduction' },
  { id: 'LIT-0012', batchNo: 'LIT-B2412', city: 'Lucknow', manufacturer: 'UP Lithium Industries', metalGrade: 'Li 99.95% Foil', application: 'Solid-State Cell (Exicom)', purityPercent: 99.95, densityGcm3: 0.534, investmentCr: 680, status: 'Delayed', priority: 'Critical', origin: 'UP Lithium Industries Lucknow (UP)', destination: 'Exicom Pune (MH)', shipDate: '2026-07-01', transitDays: 27, zone: 'North', remarks: 'Li foil for Exicom solid-state sulfide electrolyte EV cell pilot &#8594; 99.95% Li 20um &#8594; &#8377;680Cr for 0.15 tonnes &#8594; monsoon delay &#8594; India &#8377;20,400Cr EV Li &#8594; Exicom 100K cells &#8594; 0.534 g/cm3 &#8594; &#8594; Li6PS5Cl &#8594; 450 Wh/kg &#8594; pilot' },
  { id: 'LIT-0013', batchNo: 'LIT-B2413', city: 'Noida', manufacturer: 'SAIL', metalGrade: 'Li 99.5% Rod', application: 'Li-Air Battery R&amp;D (CSIR-NCL)', purityPercent: 99.5, densityGcm3: 0.534, investmentCr: 390, status: 'Delivered', priority: 'High', origin: 'SAIL Rourkela (OD)', destination: 'CSIR-NCL Pune (MH)', shipDate: '2026-07-26', transitDays: 3, zone: 'East', remarks: 'Li rod for CSIR-NCL Li-air battery prototype cathode development &#8594; 99.5% Li &#8594; &#8377;390Cr for 0.3 tonnes &#8594; India &#8377;11,700Cr R&amp;D Li &#8594; CSIR &#8594; 0.534 g/cm3 &#8594; &#8594; O2 cathode &#8594; 1200 Wh/kg &#8594; &#8594; lab' },
  { id: 'LIT-0014', batchNo: 'LIT-B2414', city: 'Bhopal', manufacturer: 'BHEL', metalGrade: 'Li-Na 30/70 Liquid Alloy', application: 'Grid Battery (NTPC)', purityPercent: 70.0, densityGcm3: 0.88, investmentCr: 540, status: 'Delivered', priority: 'High', origin: 'BHEL Bhopal (MP)', destination: 'NTPC Singrauli (UP)', shipDate: '2026-07-27', transitDays: 1, zone: 'North', remarks: 'Li-Na liquid metal for NTPC 10 MWh liquid metal battery grid storage &#8594; 30% Li 70% Na &#8594; &#8377;540Cr for 5 tonnes &#8594; India &#8377;16,200Cr grid Li &#8594; NTPC 2 GWh &#8594; 0.88 g/cm3 &#8594; &#8594; 250&#176;C &#8594; 20 yr &#8594; &#8594; liquid' }
];

const tabs = ['Dashboard', 'Registry', 'Analytics', 'Insights'] as const;
type Tab = typeof tabs[number];
const priorityColors: Record<string, string> = { Critical: 'bg-red-100 text-red-800', High: 'bg-amber-100 text-amber-800', Medium: 'bg-green-100 text-green-800', Low: 'bg-slate-100 text-slate-600' };
const delayedSet = new Set(lithiumMetalRecords.filter(r => r.status === 'Delayed').map(r => r.id));

export default function LithiumMetalLogisticsView() {
  const [activeTab, setActiveTab] = useState<Tab>('Dashboard');
  const [search, setSearch] = useState('');
  const [filters, setFilters] = useState<Record<string, string[]>>({});
  const toggleFilter = (k: string, v: string) => { setFilters(p => { const s = { ...p }; const a = s[k] || []; const i = a.indexOf(v); if (i > -1) { a.splice(i, 1); if (!a.length) delete s[k]; } else s[k] = [...a, v]; return s; }); };
  const filtered = useMemo(() => {
    let d = lithiumMetalRecords;
    if (search) { const q = search.toLowerCase(); d = d.filter(r => r.id.toLowerCase().includes(q) || r.batchNo.toLowerCase().includes(q) || r.metalGrade.toLowerCase().includes(q) || r.application.toLowerCase().includes(q) || r.city.toLowerCase().includes(q) || r.manufacturer.toLowerCase().includes(q)); }
    Object.entries(filters).forEach(([k, vs]) => { if (vs.length) d = d.filter(r => { const v = String((r as unknown as Record<string, unknown>)[k] ?? ''); return vs.some(x => v.toLowerCase().includes(x.toLowerCase())); }); });
    return d;
  }, [search, filters]);
  const totalCr = filtered.reduce((s: number, r) => s + r.investmentCr, 0);
  const avgPurity = filtered.length ? filtered.reduce((s: number, r) => s + r.purityPercent, 0) / filtered.length : 0;
  const delayedCount = filtered.filter(r => r.status === 'Delayed').length;

  return (
    <div className="space-y-6">
      <PageHeader title="Lithium Metal Logistics" description="Indian lithium metal supply chain tracking for EV batteries, grid storage, aerospace cells, defence packs, fusion blankets and industrial grease sectors" />
      <div className="flex gap-2 border-b">
        {tabs.map(t => (<button key={t} onClick={() => setActiveTab(t)} className={`px-4 py-2 text-sm font-medium ${activeTab === t ? 'border-b-2 border-teal-500 text-teal-700' : 'text-muted-foreground hover:text-foreground'}`}>{t}</button>))}
      </div>
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card><CardContent><div className="text-2xl font-bold text-teal-600">{filtered.length}</div><div className="text-xs text-muted-foreground">Total Shipments</div></CardContent></Card>
        <Card><CardContent><div className="text-2xl font-bold text-teal-600">&#8377;{totalCr.toLocaleString()} Cr</div><div className="text-xs text-muted-foreground">Total Investment</div></CardContent></Card>
        <Card><CardContent><div className="text-2xl font-bold text-teal-600">{avgPurity.toFixed(1)}%</div><div className="text-xs text-muted-foreground">Avg Purity</div></CardContent></Card>
        <Card><CardContent><div className="text-2xl font-bold text-red-500">{delayedCount}</div><div className="text-xs text-muted-foreground">Delayed Shipments</div></CardContent></Card>
      </div>
      {(activeTab === 'Dashboard' || activeTab === 'Registry') && (
        <div className="space-y-4">
          <div className="flex flex-wrap gap-2">
            <input placeholder="Search ID, grade, application, city..." value={search} onChange={e => setSearch(e.target.value)} className="border rounded-md px-3 py-1.5 text-sm flex-1 min-w-48" />
            {['status', 'priority', 'zone'].map(f => { const opts = [...new Set(lithiumMetalRecords.map(r => (r as unknown as Record<string, unknown>)[f] as string))]; return (<div key={f} className="flex flex-wrap gap-1">{opts.map(o => (<Badge key={o} variant={(filters[f] || []).includes(o) ? 'default' : 'outline'} className="cursor-pointer text-xs" onClick={() => toggleFilter(f, o)}>{o}</Badge>))}</div>); })}
          </div>
          <div className="rounded-md border"><div className="max-h-96 overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-background"><tr><th className="p-2 text-left">ID</th><th className="p-2 text-left">Batch</th><th className="p-2 text-left">Grade</th><th className="p-2 text-left">Application</th><th className="p-2 text-right">Purity%</th><th className="p-2 text-right">&#8377;Cr</th><th className="p-2 text-left">Status</th></tr></thead><tbody>{filtered.map(r => (<tr key={r.id} className={`border-t ${delayedSet.has(r.id) ? 'border-l-4 border-l-red-500 bg-red-50/30' : ''}`}><td className="p-2">{r.id}</td><td className="p-2">{r.batchNo}</td><td className="p-2">{r.metalGrade}</td><td className="p-2">{r.application}</td><td className="p-2 text-right">{r.purityPercent}</td><td className="p-2 text-right">{r.investmentCr}</td><td className="p-2"><Badge variant={r.status === 'Delivered' ? 'default' : 'destructive'}>{r.status}</Badge></td></tr>))}</tbody></table></div></div>
        </div>
      )}
      {(activeTab === 'Dashboard' || activeTab === 'Analytics') && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <Card><CardHeader><CardTitle className="text-sm">Investment by Application</CardTitle></CardHeader><CardContent><div className="space-y-2">{(Object.entries(filtered.reduce((m, r) => { m[r.application] = (m[r.application] || 0) + r.investmentCr; return m }, {} as Record<string, number>)) as [string, number][]).sort((a, b) => b[1] - a[1]).slice(0, 7).map(([a, v]) => (<div key={a} className="flex justify-between text-sm"><span>{a}</span><span className="font-medium">&#8377;{v}Cr</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Shipments by Zone</CardTitle></CardHeader><CardContent><div className="space-y-2">{(Object.entries(filtered.reduce((m, r) => { m[r.zone] = (m[r.zone] || 0) + 1; return m }, {} as Record<string, number>)) as [string, number][]).sort((a, b) => b[1] - a[1]).map(([z, c]) => (<div key={z} className="flex justify-between text-sm"><span>{z}</span><span className="font-medium">{c}</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Top Routes by Value</CardTitle></CardHeader><CardContent><div className="space-y-2">{filtered.sort((a, b) => b.investmentCr - a.investmentCr).slice(0, 7).map(r => (<div key={r.id} className="flex justify-between text-sm"><span>{r.origin.split('(')[0]} &#8594; {r.destination.split('(')[0]}</span><span className="font-medium">&#8377;{r.investmentCr}Cr</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">EV and Mobility</CardTitle></CardHeader><CardContent><div className="space-y-2">{filtered.filter(r => r.application.toLowerCase().includes('ev') || r.application.toLowerCase().includes('auto') || r.application.toLowerCase().includes('mahindra') || r.application.toLowerCase().includes('tata') || r.application.toLowerCase().includes('two-wheeler')).sort((a, b) => b.investmentCr - a.investmentCr).map(r => (<div key={r.id} className="flex justify-between text-sm"><span>{r.metalGrade}</span><span className="font-medium">&#8377;{r.investmentCr}Cr</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">By Priority</CardTitle></CardHeader><CardContent><div className="space-y-2">{Object.entries(filtered.reduce((m, r) => { m[r.priority] = (m[r.priority] || 0) + 1; return m }, {} as Record<string, number>)).map(([p, c]) => (<div key={p} className="flex justify-between text-sm"><span className={priorityColors[p] || ''}>{p}</span><span className="font-medium">{c}</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Purity Distribution</CardTitle></CardHeader><CardContent><div className="space-y-2">{[{ l: 'Ultra-Pure (99.99%+)', f: filtered.filter(r => r.purityPercent >= 99.99).length }, { l: 'High (99.9-99.99%)', f: filtered.filter(r => r.purityPercent >= 99.9 && r.purityPercent < 99.99).length }, { l: 'Medium (99.5-99.9%)', f: filtered.filter(r => r.purityPercent >= 99.5 && r.purityPercent < 99.9).length }, { l: 'Alloy (&lt;99.5%)', f: filtered.filter(r => r.purityPercent < 99.5).length }].map(b => (<div key={b.l} className="flex justify-between text-sm"><span>{b.l}</span><span className="font-medium">{b.f}</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Top Manufacturers</CardTitle></CardHeader><CardContent><div className="space-y-2">{(Object.entries(filtered.reduce((m, r) => { m[r.manufacturer] = (m[r.manufacturer] || 0) + r.investmentCr; return m }, {} as Record<string, number>)) as [string, number][]).sort((a, b) => b[1] - a[1]).slice(0, 7).map(([m, v]) => (<div key={m} className="flex justify-between text-sm"><span>{m}</span><span className="font-medium">&#8377;{v}Cr</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Avg Transit Days</CardTitle></CardHeader><CardContent><div className="space-y-2">{filtered.length ? (Object.entries(filtered.reduce((m, r) => { m[r.zone] = (m[r.zone] || [] as number[]).concat(r.transitDays); return m }, {} as Record<string, number[]>)) as [string, number[]][]).map(([z, d]) => (<div key={z} className="flex justify-between text-sm"><span>{z}</span><span className="font-medium">{(d.reduce((s, n) => s + n, 0) / d.length).toFixed(1)}d</span></div>)) : []}</div></CardContent></Card>
        </div>
      )}
      {(activeTab === 'Dashboard' || activeTab === 'Insights') && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Card><CardContent><div className="text-sm font-medium text-teal-600 mb-2">Tata Motors Solid-State Li Metal Anode</div><div className="text-xs text-muted-foreground">Tata Motors developing anode-free solid-state battery with 99.9% Li metal foil replacing graphite anode for Nexon EV Gen2. Li metal achieves 3860 mAh/g vs graphite 372 mAh/g, 10x capacity increase. Tata Advanced Materials supplying Li foil from domestic production targeting 500K packs by 2028.</div></CardContent></Card>
          <Card><CardContent><div className="text-sm font-medium text-teal-600 mb-2">IGCAR Fusion Blanket Li Breeder</div><div className="text-xs text-muted-foreground">IGCAR supplying 99.999% ultra-pure Li for Indian DEMO fusion reactor blanket breeding module. Li-6 captures neutron to produce tritium fuel for sustained D-T fusion reaction. India targeting 2040 DEMO with Li4SiO4 pebble-bed blanket design under &#8377;35,000Cr national fusion programme.</div></CardContent></Card>
          <Card><CardContent><div className="text-sm font-medium text-teal-600 mb-2">Exicom Li-S Two-Wheeler Battery</div><div className="text-xs text-muted-foreground">Exicom launching Li-S battery with 30/70 Li-Si nanowire anode targeting 500 Wh/kg for electric two-wheeler range extension from 100km to 250km. Li-S eliminates cobalt dependency reducing cell cost 40% vs NMC. Tamil Nadu Lithium scaling nanowire production under &#8377;4,500Cr FAME III.</div></CardContent></Card>
          <Card><CardContent><div className="text-sm font-medium text-teal-600 mb-2">NTPC Li-Na Liquid Metal Grid Battery</div><div className="text-xs text-muted-foreground">NTPC deploying 10 MWh Li-Na 30/70 liquid metal battery for 20-year zero-degradation grid storage replacing Li-ion peaker plants. Li-Na operates at 250&#176;C with 85% round-trip efficiency. BHEL manufacturing liquid alloy at scale. India targeting 100 GWh long-duration storage by 2035.</div></CardContent></Card>
        </div>
      )}
    </div>
  );
}
