"use client";
import { useState } from "react";
import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, Legend } from "recharts";
import { PageHeader } from "@/components/shared/page-header";
import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar";
import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb";

const COLORS = ["#581c87", "#6b21a8", "#7e22ce", "#9333ea", "#a855f7", "#c084fc", "#d8b4fe", "#e9d5ff"];
const OPERATORS = ["ISRO Bengaluru", "Antrix Corporation Bengaluru", "NSIL New Delhi", "Dhruva Space Hyderabad", "Skyroot Aerospace Hyderabad", "Agnikul Cosmos Chennai", "Pixxel Bengaluru", "Bellatrix Aerospace Bengaluru"];
const CATEGORIES = ["PSLV-XL 3800kg LEO Polar", "GSLV Mk-II 2500kg GTO", "GSLV Mk-III 4000kg GTO", "SSLV 500kg LEO Micro", "RLV-TD Reusable 150kg Suborbital", "Sounding Rocket RH-560 200kg", "SmallSat PSLV-CA 1100kg LEO", "Human Gaganyaan LVM3 8500kg LEO"];
const SHIPMENT_STATUSES = ["Stage Integration Testing", "Propellant Loading Cryogenic", "Fairing Encapsulation Payload", "Launch Pad Mobile Erection", "Countdown Sequence Active", "Liftoff Orbital Insertion"];
const ZONES = ["Sriharikota SHAR Andhra Pradesh", "Thumba Equatorial Rocket Kerala", "Chandipur DRDO Odisha", "Hassan ISRO Propulsion Complex KA", "Balasore Range Odisha", "Satish Dhawan SC SHAR AP", "Bengaluru ISRO HQ Karnataka", "Ahmedabad SAC Gujarat"];
const MODES = ["Specialized Rail Transport ISRO", "Heavy Trailer Convoy 60T", "Defense Ship Coast Guard", "Cryogenic Tanker Trailer LN2", "Helicopter Airlift Component", "Port Vessel Coastal Barge"];
const TABS = ["Dashboard", "Launch Registry", "Orbital Analytics", "Insights"];

const statusColor: Record<string, string> = { "Stage Integration Testing": "orange", "Propellant Loading Cryogenic": "blue", "Fairing Encapsulation Payload": "blue", "Launch Pad Mobile Erection": "orange", "Countdown Sequence Active": "orange", "Liftoff Orbital Insertion": "green" };

function formatINR(n: number): string {
  if (n >= 10000000) return "\u20b9" + (n / 10000000).toFixed(1) + "Cr";
  if (n >= 100000) return "\u20b9" + (n / 100000).toFixed(1) + "L";
  return "\u20b9" + (n / 1000).toFixed(0) + "K";
}

const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const monthlyLaunches = Array.from({ length: 12 }, (_, i) => ({ m: MO[i], pslv: +(2 + Math.sin(i * 0.5) * 1.2).toFixed(1), gslv: +(0.8 + Math.cos(i * 0.6) * 0.5).toFixed(1), sslv: +(1.5 + Math.sin(i * 0.4) * 0.8).toFixed(1), gslv3: +(0.5 + Math.cos(i * 0.7) * 0.3).toFixed(1) }));
const vehicleDist = [{ n: "PSLV-XL", v: 35 }, { n: "PSLV-CA", v: 15 }, { n: "GSLV Mk-II", v: 18 }, { n: "GSLV Mk-III", v: 12 }, { n: "SSLV", v: 12 }, { n: "RLV-TD", v: 4 }, { n: "Sounding", v: 4 }];
const orbitTrend = Array.from({ length: 12 }, (_, i) => ({ m: MO[i], leo: +(180 + Math.sin(i * 0.3) * 15).toFixed(0), gto: +(35 + Math.cos(i * 0.4) * 8).toFixed(0), polar: +(120 + Math.sin(i * 0.5) * 10).toFixed(0), suborbital: +(12 + Math.cos(i * 0.6) * 3).toFixed(0) }));
const zoneLaunches = [
  { zone: "SHAR", launches: 85 },
  { zone: "Thumba", launches: 45 },
  { zone: "Chandipur", launches: 25 },
  { zone: "Hassan IPRC", launches: 15 },
  { zone: "Balasore", launches: 10 },
  { zone: "Bangalore", launches: 8 }
];

const INSIGHTS = [
  { t: "ISRO\u2019s Launch Vehicle Fleet: PSLV GSLV LVM3 SSLV and Gaganyaan Program", c: "The Indian Space Research Organisation (ISRO) headquartered in Bengaluru operates India\u2019s fleet of 4 operational launch vehicles: Polar Satellite Launch Vehicle (PSLV) with 4 variants (PSLV-CL, PSLV-CA, PSLV-XL, PSLV-DL) achieving 57 successful missions out of 60 attempts (95% reliability), Geosynchronous Satellite Launch Vehicle (GSLV Mk-II) with indigenous cryogenic upper stage CE-7.5 (15 successful of 16 missions), Launch Vehicle Mark-III (LVM3) with CE-20 cryogenic engine capable of placing 4,000kg in GTO, and Small Satellite Launch Vehicle (SSLV) for 500kg LEO at \u20b930 crore per launch. ISRO\u2019s Satish Dhawan Space Centre (SDSC) SHAR at Sriharikota, Andhra Pradesh serves as India\u2019s primary launch site with 2 active launch pads (First Launch Pad operational since 1993, Second Launch Pad since 2005) and a dedicated SSLV launch pad commissioned in 2022. India\u2019s Gaganyaan human spaceflight program using LVM3 with crew escape system, life support module, and orbital module is scheduled for 2026-2027 with an estimated budget of \u20b912,435 crore ($1.5 billion). ISRO has launched 431 foreign satellites from 36 countries earning \u20b95,000 crore in foreign exchange through Antrix Corporation and NewSpace India Limited (NSIL)." },
  { t: "PSLV: The Workhorse of Indian Space Program with 95% Mission Reliability", c: "The Polar Satellite Launch Vehicle (PSLV) designed and developed by Vikram Sarabhai Space Centre (VSSC) Thiruvananthapuram has completed 60 missions since its maiden flight on September 20, 1993, with 57 successful missions including 39 consecutive successes from 2005 to 2024 (world record for a single launch vehicle family). PSLV-XL variant uses 6 extended solid rocket boosters (S200) with 12.8 tonnes of HTPB propellant each, providing total lift-off thrust of 7,970kN for placing 3,800kg in 600km Sun-Synchronous Orbit (SSO) or 1,425kg in GTO. PSLV\u2019s four stages comprise: S139 solid motor (110T HTPB, 4,800kN thrust, 105s burn), Vikas engine liquid stage (40T UDMH+N2O4, 725kN, 158s), S7 solid motor (7.6T HTPB, 240kN, 112s), and PS-4 liquid stage (2.5T MMH+MON-3, 7.3kN, 420s restart-capable). ISRO\u2019s PSLV-C58 mission in January 2025 demonstrated multi-orbit deployment releasing 12 satellites in 3 different orbits (300km, 450km, 550km) using dual PS-4 restart capability. The vehicle is manufactured at ISRO Propulsion Complex (IPRC) Mahendragiri, Tamil Nadu with solid motor casings forged at Bharat Forge Pune and Vikas engines assembled at Godrej Aerospace Mumbai." },
  { t: "GSLV Mk-III/LVM3 and CE-20 Cryogenic Engine: India\u2019s Heavy Lift Capability", c: "The Launch Vehicle Mark-III (LVM3), formerly GSLV Mk-III, is India\u2019s heaviest operational launch vehicle with capability to place 4,000kg in Geosynchronous Transfer Orbit (GTO) or 8,000kg in Low Earth Orbit (LEO), developed at a cost of \u20b92,500 crore. The vehicle features two S200 solid strap-on boosters (207T each, 10,000kN total thrust), L110 liquid core stage (110T UDMH+N2O4, 7,000kN, 200s with 2 Vikas engines), and the indigenously developed C25 cryogenic upper stage (28T LOX+LH2, 186kN, 643s with CE-20 engine). The CE-20 cryogenic engine developed by Liquid Propulsion Systems Centre (LPSC) Valiamala uses a staged combustion cycle with 2.1MN thrust at 205 bar chamber pressure, significantly upgraded from the CE-7.5 engine (93kN) used on GSLV Mk-II. LVM3 has conducted 8 missions including Chandrayaan-3 lunar landing (July 2023, 3,900kg to trans-lunar injection) and the NISAR joint NASA-ISRO Earth observation satellite (March 2025, 2,800kg to 740km SSO). ISRO\u2019s LVM3 Upgrade program (LVM3-U) targets 6,000kg GTO capability with uprated S200 boosters (220T), enhanced L110 core, and CE-20M engine with 25% higher thrust." },
  { t: "India\u2019s Private Space Sector: Skyroot Agnikul Pixxel Bellatrix and IN-SPACe", c: "India\u2019s private space sector has witnessed explosive growth since the creation of Indian National Space Promotion and Authorization Centre (IN-SPACe) in 2020 as the single-window regulatory body for private space companies. Skyroot Aerospace Hyderabad became India\u2019s first private company to launch a rocket with the Vikram-S suborbital vehicle in November 2022, followed by development of the Vikram-1 orbital launch vehicle (480kg SSO, \u20b930 crore per launch) powered by 3D-printed Krypton-1 engine. Agnikul Cosmos Chennai developed the Agnibaan launch vehicle with 3D-printed semi-cryogenic engine Agnilet (single-piece 3D-printed LOX+Kerosene, 3.5kN) and conducted India\u2019s first private launch from SDSC SHAR in May 2024. Pixxel Bengaluru operates India\u2019s first private hyperspectral satellite constellation with 12 satellites deployed in 300-400km SSO for mining, agriculture, and environmental monitoring applications, having launched 3 satellites on ISRO PSLV and SpaceX Falcon-9. Bellatrix Aerospace Bengaluru develops electric propulsion systems (SITAE thruster, 20mN iodine Hall effect) and green monopropellant thrusters for satellite station-keeping and orbit transfer. The Indian space economy valued at \u20b962,500 crore ($7.5 billion) in 2024 is projected to reach \u20b92,60,000 crore ($31 billion) by 2035, driven by private launch services, satellite communications, Earth observation, and space-based services under the Indian Space Policy 2023." }
];

interface SLCRecord { id: string; batchNo: string; operator: string; zone: string; category: string; description: string; payloadKg: number; orbitAltKm: number; vehicleT: number; engineType: string; fuelType: string; origin: string; project: string; state: string; mode: string; prodDate: string; shipDate: string; transitDays: number; contractValue: number; satelliteMake: string; status: string; remarks: string; }

const records: SLCRecord[] = [
  { id: "SLC-0001", batchNo: "ISR/BLR/2025/PSL-0012", operator: "ISRO Bengaluru", zone: "Sriharikota SHAR Andhra Pradesh", category: "PSLV-XL 3800kg LEO Polar", description: "PSLV-C59 XL mission deploying 12 satellites in 550km SSO including Cartosat-4 and 11 commercial nanosatellites from 7 countries", payloadKg: 1750, orbitAltKm: 550, vehicleT: 320, engineType: "S139 + Vikas + PS4", fuelType: "HTPB + UDMH + MMH", origin: "IPRC Mahendragiri TN", project: "PSLV-C59/Cartosat-4 Multi-Sat", state: "Andhra Pradesh", mode: "Specialized Rail Transport ISRO", prodDate: "2025-01-10", shipDate: "2025-03-20", transitDays: 4, contractValue: 350000000, satelliteMake: "ISRO/Antrix Multi-National", status: "Liftoff Orbital Insertion", remarks: "PSLV-C59 ISRO SHAR successful insertion" },
  { id: "SLC-0002", batchNo: "ISR/BLR/2025/GSL-0018", operator: "ISRO Bengaluru", zone: "Sriharikota SHAR Andhra Pradesh", category: "GSLV Mk-III 4000kg GTO", description: "LVM3-F09 mission deploying GSAT-21 communication satellite 4,200kg in 250km x 36,000km GTO with CE-20 cryogenic upper stage", payloadKg: 4200, orbitAltKm: 36000, vehicleT: 640, engineType: "S200 + L110 + CE-20", fuelType: "HTPB + UDMH + LOX/LH2", origin: "LPSC Valiamala KL", project: "LVM3-F09/GSAT-21 GTO", state: "Andhra Pradesh", mode: "Heavy Trailer Convoy 60T", prodDate: "2025-02-15", shipDate: "2025-05-10", transitDays: 5, contractValue: 750000000, satelliteMake: "ISRO/ISAC Bengaluru", status: "Liftoff Orbital Insertion", remarks: "LVM3-F09 ISRO GSAT-21 GTO insertion" },
  { id: "SLC-0003", batchNo: "NSI/NDL/2025/GSL-0025", operator: "NSIL New Delhi", zone: "Sriharikota SHAR Andhra Pradesh", category: "GSLV Mk-II 2500kg GTO", description: "GSLV-F16 mission deploying 36 OneWeb Gen-2 broadband satellites 2,580kg total in 450km LEO under NSIL commercial launch contract", payloadKg: 2580, orbitAltKm: 450, vehicleT: 415, engineType: "S139 + GS1 + CE-7.5", fuelType: "HTPB + UDMH + LOX/LH2", origin: "IPRC Mahendragiri TN", project: "GSLV-F16/OneWeb Gen-2 LEO", state: "Andhra Pradesh", mode: "Specialized Rail Transport ISRO", prodDate: "2025-03-01", shipDate: "2025-06-05", transitDays: 4, contractValue: 520000000, satelliteMake: "OneWeb UK/NSIL Commercial", status: "Liftoff Orbital Insertion", remarks: "GSLV-F16 NSIL OneWeb LEO insertion" },
  { id: "SLC-0004", batchNo: "SKR/HYD/2025/SSL-0032", operator: "Skyroot Aerospace Hyderabad", zone: "Satish Dhawan SC SHAR AP", category: "SSLV 500kg LEO Micro", description: "Skyroot Vikram-1 orbital mission deploying 3 customer nanosatellites 180kg total in 400km SSO with 3D-printed Krypton-1 engine first stage", payloadKg: 180, orbitAltKm: 400, vehicleT: 28, engineType: "Krypton-1 + Krypton-2 + Krypton-3", fuelType: "HTPB + LOX/Kerosene", origin: "Skyroot Hyderabad Plant TS", project: "Vikram-1/Commercial Nano-3", state: "Andhra Pradesh", mode: "Heavy Trailer Convoy 60T", prodDate: "2025-04-10", shipDate: "2025-07-15", transitDays: 2, contractValue: 300000000, satelliteMake: "Skyroot Customer Multi-National", status: "Stage Integration Testing", remarks: "Skyroot Vikram-1 stage integration" },
  { id: "SLC-0005", batchNo: "ANK/CHN/2025/SSL-0041", operator: "Agnikul Cosmos Chennai", zone: "Sriharikota SHAR Andhra Pradesh", category: "SmallSat PSLV-CA 1100kg LEO", description: "Agnikul Agnibaan orbital debut deploying Pixxel-4 hyperspectral satellite 95kg in 350km SSO with 3D-printed Agnilet semi-cryogenic engine", payloadKg: 95, orbitAltKm: 350, vehicleT: 18, engineType: "Agnilet 3D-Print", fuelType: "LOX/Kerosene 3D-Print", origin: "Agnikul IIT Madras Research Park TN", project: "Agnibaan/Pixxel-4 SSO", state: "Andhra Pradesh", mode: "Helicopter Airlift Component", prodDate: "2025-03-20", shipDate: "2025-06-18", transitDays: 1, contractValue: 250000000, satelliteMake: "Pixxel Bengaluru", status: "Fairing Encapsulation Payload", remarks: "Agnibaan Agnikul Pixxel-4 fairing encapsulation" },
  { id: "SLC-0006", batchNo: "ISR/BLR/2025/GAG-0048", operator: "ISRO Bengaluru", zone: "Sriharikota SHAR Andhra Pradesh", category: "Human Gaganyaan LVM3 8500kg LEO", description: "Gaganyaan G1 uncrewed orbital mission with crew module service module and crew escape system 8,500kg to 400km LEO for 3-day demonstration flight", payloadKg: 8500, orbitAltKm: 400, vehicleT: 640, engineType: "S200 + L110 + CE-20", fuelType: "HTPB + UDMH + LOX/LH2", origin: "LPSC/HAS Bengaluru KA", project: "Gaganyaan G1 Uncrewed Orbital", state: "Andhra Pradesh", mode: "Heavy Trailer Convoy 60T", prodDate: "2025-01-25", shipDate: "2025-04-20", transitDays: 3, contractValue: 2800000000, satelliteMake: "ISRO/HAS Bengaluru", status: "Stage Integration Testing", remarks: "Gaganyaan G1 ISRO crew module integration" },
  { id: "SLC-0007", batchNo: "PXX/BLR/2025/PSL-0055", operator: "Pixxel Bengaluru", zone: "Sriharikota SHAR Andhra Pradesh", category: "PSLV-CA 1100kg LEO SmallSat", description: "PSLV-C60 CA mission deploying Pixxel-5 hyperspectral constellation satellite 85kg in 500km SSO with 5m spatial resolution 60 spectral bands", payloadKg: 350, orbitAltKm: 500, vehicleT: 290, engineType: "S139 + Vikas + PS4", fuelType: "HTPB + UDMH + MMH", origin: "IPRC Mahendragiri TN", project: "PSLV-C60/Pixxel-5 SSO", state: "Andhra Pradesh", mode: "Specialized Rail Transport ISRO", prodDate: "2025-02-25", shipDate: "2025-05-15", transitDays: 4, contractValue: 280000000, satelliteMake: "Pixxel/Antrix Ride-Share", status: "Liftoff Orbital Insertion", remarks: "PSLV-C60 Pixxel-5 SSO insertion success" },
  { id: "SLC-0008", batchNo: "ISR/BLR/2025/RLV-0062", operator: "ISRO Bengaluru", zone: "Chandipur DRDO Odisha", category: "RLV-TD Reusable 150kg Suborbital", description: "RLV-TD reusable launch vehicle demonstration REX mission landing on runway after 1km autonomous approach 150kg technology demonstrator winged body", payloadKg: 150, orbitAltKm: 100, vehicleT: 22, engineType: "S9 Solid + HS9 Booster", fuelType: "HTPB Solid", origin: "VSSC Thiruvananthapuram KL", project: "RLV-LEX3/Reusable Landing Demo", state: "Odisha", mode: "Defense Ship Coast Guard", prodDate: "2025-05-01", shipDate: "2025-07-20", transitDays: 3, contractValue: 180000000, satelliteMake: "ISRO/VSSC Tech Demo", status: "Launch Pad Mobile Erection", remarks: "RLV-TD REX3 ISRO Chandipur pad erection" },
  { id: "SLC-0009", batchNo: "BEL/BLR/2025/SND-0075", operator: "Bellatrix Aerospace Bengaluru", zone: "Thumba Equatorial Rocket Kerala", category: "Sounding Rocket RH-560 200kg", description: "RH-560 sounding rocket mission for upper atmosphere research with Bellatrix SITAE electric propulsion payload test at 150km apogee 200kg sounding vehicle", payloadKg: 80, orbitAltKm: 150, vehicleT: 4, engineType: "Solid Sounding Motor", fuelType: "HTPB Solid", origin: "Bellatrix Bengaluru Plant KA", project: "RH-560/Bellatrix EP Test", state: "Kerala", mode: "Helicopter Airlift Component", prodDate: "2025-03-15", shipDate: "2025-06-02", transitDays: 2, contractValue: 45000000, satelliteMake: "Bellatrix EP Experiment", status: "Propellant Loading Cryogenic", remarks: "RH-560 Bellatrix propellant loading" },
  { id: "SLC-0010", batchNo: "ISR/BLR/2025/PSL-0083", operator: "ISRO Bengaluru", zone: "Sriharikota SHAR Andhra Pradesh", category: "PSLV-XL 3800kg LEO Polar", description: "PSLV-C61 XL dedicated commercial mission deploying 24 Planet Labs SuperDove satellites 280kg in 530km SSO multi-orbit deployment", payloadKg: 280, orbitAltKm: 530, vehicleT: 320, engineType: "S139 + Vikas + PS4", fuelType: "HTPB + UDMH + MMH", origin: "IPRC Mahendragiri TN", project: "PSLV-C61/Planet SuperDove-24", state: "Andhra Pradesh", mode: "Port Vessel Coastal Barge", prodDate: "2025-04-15", shipDate: "2025-07-05", transitDays: 2, contractValue: 320000000, satelliteMake: "Planet Labs USA/NSIL", status: "Countdown Sequence Active", remarks: "PSLV-C61 ISRO Planet countdown" },
  { id: "SLC-0011", batchNo: "DHR/HYD/2025/SSL-0091", operator: "Dhruva Space Hyderabad", zone: "Sriharikota SHAR Andhra Pradesh", category: "SSLV 500kg LEO Micro", description: "SSLV-D3 mission deploying Dhruva-2 satellite 120kg in 450km LEO with in-orbit propulsion system demonstration and xenon electric thruster test", payloadKg: 120, orbitAltKm: 450, vehicleT: 34, engineType: "SSLV 3-Stage Solid", fuelType: "HTPB All-Solid", origin: "Dhruva Hyderabad Plant TS", project: "SSLV-D3/Dhruva-2 LEO EP", state: "Andhra Pradesh", mode: "Heavy Trailer Convoy 60T", prodDate: "2025-05-10", shipDate: "2025-08-08", transitDays: 2, contractValue: 300000000, satelliteMake: "Dhruva Space Hyderabad", status: "Stage Integration Testing", remarks: "SSLV-D3 Dhruva stage integration" },
  { id: "SLC-0012", batchNo: "ISR/BLR/2025/GSL-0098", operator: "ISRO Bengaluru", zone: "Hassan ISRO Propulsion Complex KA", category: "GSLV Mk-III 4000kg GTO", description: "LVM3-F10 Chandrayaan-4 sample return mission 6,500kg to trans-lunar trajectory with lander rover ascender and Earth re-entry capsule", payloadKg: 6500, orbitAltKm: 384400, vehicleT: 640, engineType: "S200 + L110 + CE-20", fuelType: "HTPB + UDMH + LOX/LH2", origin: "LPSC Valiamala KL", project: "LVM3-F10/Chandrayaan-4 TLI", state: "Karnataka", mode: "Cryogenic Tanker Trailer LN2", prodDate: "2025-02-10", shipDate: "2025-05-18", transitDays: 3, contractValue: 4500000000, satelliteMake: "ISRO/URSC Bengaluru", status: "Stage Integration Testing", remarks: "LVM3-F10 Chandrayaan-4 integration" },
  { id: "SLC-0013", batchNo: "ANK/CHN/2025/SSL-0105", operator: "Agnikul Cosmos Chennai", zone: "Sriharikota SHAR Andhra Pradesh", category: "SmallSat PSLV-CA 1100kg LEO", description: "PSLV-C62 CA ride-share mission with Agnikul Agnibaan second orbital flight deploying 4 customer satellites 250kg in 380km SSO multi-payload", payloadKg: 250, orbitAltKm: 380, vehicleT: 290, engineType: "S139 + Vikas + PS4", fuelType: "HTPB + UDMH + MMH", origin: "IPRC Mahendragiri TN", project: "PSLV-C62/Agnibaan-2 Multi-Pay", state: "Andhra Pradesh", mode: "Specialized Rail Transport ISRO", prodDate: "2025-06-01", shipDate: "2025-08-15", transitDays: 2, contractValue: 310000000, satelliteMake: "Agnikul Customer Multi", status: "Stage Integration Testing", remarks: "PSLV-C62 Agnikul stage integration" },
  { id: "SLC-0014", batchNo: "ISR/BLR/2025/GAG-0118", operator: "ISRO Bengaluru", zone: "Sriharikota SHAR Andhra Pradesh", category: "Human Gaganyaan LVM3 8500kg LEO", description: "Gaganyaan G2 uncrewed orbital validation mission with 7-day orbital flight life support system verification crew module 8,500kg 400km LEO", payloadKg: 8500, orbitAltKm: 400, vehicleT: 640, engineType: "S200 + L110 + CE-20", fuelType: "HTPB + UDMH + LOX/LH2", origin: "LPSC/HAS Bengaluru KA", project: "Gaganyaan G2 7-Day Validation", state: "Andhra Pradesh", mode: "Heavy Trailer Convoy 60T", prodDate: "2025-01-15", shipDate: "2025-04-10", transitDays: 3, contractValue: 3200000000, satelliteMake: "ISRO/HAS Bengaluru", status: "Stage Integration Testing", remarks: "Gaganyaan G2 ISRO 7-day integration" }
];

export default function SatelliteLaunchComplexLogisticsView() {
  const [tab, setTab] = useState(0);
  const [search, setSearch] = useState("");
  const [activeFilters, setActiveFilters] = useState<Record<string, string[]>>({});

  const totalPayload = records.reduce((s, r) => s + r.payloadKg, 0);
  const totalContract = records.reduce((s, r) => s + r.contractValue, 0);
  const activeLaunches = records.filter(r => r.status !== "Liftoff Orbital Insertion").length;
  const completed = records.filter(r => r.status === "Liftoff Orbital Insertion").length;

  const kpis = [
    { l: "Total Payload (kg)", v: totalPayload.toLocaleString("en-IN"), s: "Across " + records.length + " launch records" },
    { l: "In Preparation", v: activeLaunches, s: "Integration to countdown" },
    { l: "Launched", v: completed, s: "Orbital insertion success" },
    { l: "Total Contract", v: formatINR(totalContract), s: "Aggregate contract value" }
  ];

  const filterGroups = [
    { key: "operator", label: "Operator", options: OPERATORS.map(d => ({ value: d, count: records.filter(r => r.operator === d).length })) },
    { key: "category", label: "Category", options: CATEGORIES.map(c => ({ value: c, count: records.filter(r => r.category === c).length })) },
    { key: "status", label: "Status", options: SHIPMENT_STATUSES.map(s => ({ value: s, count: records.filter(r => r.status === s).length })) },
    { key: "zone", label: "Zone", options: ZONES.map(z => ({ value: z, count: records.filter(r => r.zone === z).length })) },
    { key: "satelliteMake", label: "Satellite", options: ["ISRO/Antrix Multi-National", "ISRO/ISAC Bengaluru", "OneWeb UK/NSIL Commercial", "Skyroot Customer Multi-National", "Pixxel Bengaluru", "Pixxel/Antrix Ride-Share", "ISRO/HAS Bengaluru", "Planet Labs USA/NSIL", "Dhruva Space Hyderabad", "Agnikul Customer Multi"].map(s => ({ value: s, count: records.filter(r => r.satelliteMake === s).length })) }
  ];

  const toggleFilter = (k: string, v: string) => setActiveFilters(p => (function(){ const n={...p}; n[k]=(p[k]||[]).filter(x=>x!==v); if(n[k].length===0) delete n[k]; return n })());

  const filtered = records.filter(r => {
    if (search) {
      const q = search.toLowerCase();
      if (!r.id.toLowerCase().includes(q) && !r.batchNo.toLowerCase().includes(q) && !r.operator.toLowerCase().includes(q) && !r.description.toLowerCase().includes(q) && !r.category.toLowerCase().includes(q) && !r.project.toLowerCase().includes(q) && !r.engineType.toLowerCase().includes(q)) return false;
    }
    return Object.entries(activeFilters).every(([k, vs]) => vs.includes(r[k as keyof SLCRecord] as string));
  });

  const COLS = ["ID", "Batch No", "Operator", "Zone", "Category", "Description", "Payload (kg)", "Alt (km)", "Vehicle (T)", "Engine", "Fuel", "Origin", "Project", "State", "Mode", "Prod Date", "Ship Date", "Transit (d)", "Contract (\u20b9)", "Satellite", "Status", "Remarks"];

  const renderCharts = () => (
    <>
      <div className="grid grid-cols-2 gap-6">
        <div className="slc-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Monthly Launch Cadence by Vehicle</h3><BarChart data={monthlyLaunches} height={220}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="m" /><YAxis /><Tooltip /><Legend /><Bar dataKey="pslv" fill="#581c87" radius={[4,4,0,0]} name="PSLV" /><Bar dataKey="gslv" fill="#6b21a8" radius={[4,4,0,0]} name="GSLV" /><Bar dataKey="sslv" fill="#7e22ce" radius={[4,4,0,0]} name="SSLV" /><Bar dataKey="gslv3" fill="#a855f7" radius={[4,4,0,0]} name="LVM3" /></BarChart></div>
        <div className="slc-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Launch Vehicle Distribution (%)</h3><PieChart width={400} height={220}><Pie data={vehicleDist} dataKey="v" nameKey="n" cx="50%" cy="50%" outerRadius={80} label>{vehicleDist.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}</Pie><Tooltip /></PieChart></div>
      </div>
      <div className="grid grid-cols-2 gap-6">
        <div className="slc-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Orbits by Type (Satellites Deployed)</h3><AreaChart data={orbitTrend} height={220}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="m" /><YAxis /><Tooltip /><Legend /><Area type="monotone" dataKey="leo" fill="#e9d5ff" stroke="#581c87" strokeWidth={1} fillOpacity={0.6} name="LEO" /><Area type="monotone" dataKey="gto" fill="#d8b4fe" stroke="#6b21a8" strokeWidth={1} fillOpacity={0.6} name="GTO" /><Area type="monotone" dataKey="polar" fill="#c084fc" stroke="#7e22ce" strokeWidth={1} fillOpacity={0.6} name="Polar" /><Area type="monotone" dataKey="suborbital" fill="#a855f7" stroke="#9333ea" strokeWidth={1} fillOpacity={0.6} name="Suborbital" /></AreaChart></div>
        <div className="slc-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Launches by Site</h3><BarChart data={zoneLaunches} height={220}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="zone" /><YAxis /><Tooltip /><Legend /><Bar dataKey="launches" fill="#6b21a8" radius={[4,4,0,0]} name="Total Launches" /></BarChart></div>
      </div>
    </>
  );

  return (
    <div className="slc-root p-6 space-y-6">
      <PageHeader title="Satellite Launch Complex Logistics" description="Indian satellite launch complex logistics covering PSLV-XL 3800kg SSO GSLV Mk-II 2500kg GTO GSLV Mk-III LVM3 4000kg GTO SSLV 500kg LEO RLV-TD reusable 150kg suborbital RH-560 sounding rocket 200kg SmallSat PSLV-CA 1100kg Gaganyaan human 8500kg LEO ISRO Antrix NSIL Skyroot Agnikul Pixxel Bellatrix Dhruva Space Sriharikota SHAR Thumba Chandipur Balasore IN-SPACe 57 PSLV missions 22480MW 2032 private space economy" />
      <div className="slc-tabs flex gap-1 border-b border-gray-200">
        {TABS.map((t, i) => (<button key={t} onClick={() => setTab(i)} className={`slc-tab px-4 py-2 text-sm font-medium rounded-t ${tab === i ? "bg-[#581c87] text-white" : "text-gray-600 hover:bg-purple-50"}`}>{t}</button>))}
      </div>
      <ModuleBreadcrumb items={[{ label: "Logistics", href: "#" }, { label: "Satellite Launch" }]} />
      {tab === 0 && (
        <div className="slc-dash space-y-6">
          <div className="grid grid-cols-4 gap-4">
            {kpis.map((k, i) => <div key={i} className="bg-white rounded-lg border p-4"><p className="text-xs text-gray-500">{k.l}</p><p className="text-2xl font-bold text-[#581c87]">{k.v}</p><p className="text-xs text-gray-400">{k.s}</p></div>)}
          </div>
          {renderCharts()}
          <div className="grid grid-cols-2 gap-6">
            {INSIGHTS.map((ins, i) => <div key={i} className="bg-white rounded-lg border p-4"><h4 className="text-sm font-semibold mb-2 text-[#581c87]">{ins.t}</h4><p className="text-xs text-gray-600 leading-relaxed">{ins.c}</p></div>)}
          </div>
        </div>
      )}
      {tab === 1 && (
        <div className="slc-reg space-y-4">
          <SearchFilterToolbar searchQuery={search} onSearchChange={setSearch} onClearSearch={() => setSearch("")} filterGroups={filterGroups} activeFilters={activeFilters} onToggleFilter={toggleFilter} onClearAllFilters={() => setActiveFilters({})} totalItems={records.length} filteredCount={filtered.length} />
          <div className="slc-table-wrap overflow-auto rounded-lg border bg-white"><table className="w-full text-xs"><thead><tr className="bg-gray-50 border-b">{COLS.map((c) => <th key={c} className="px-3 py-2 text-left font-medium text-gray-600 whitespace-nowrap">{c}</th>)}</tr></thead><tbody>{filtered.map((r) => { const sc = statusColor[r.status]; return <tr key={r.id} className={`border-b ${sc === "green" ? "bg-green-50 border-l-4 border-l-green-500" : sc === "orange" ? "bg-orange-50 border-l-4 border-l-orange-400" : sc === "blue" ? "bg-blue-50 border-l-4 border-l-blue-400" : ""}`}><td className="px-3 py-2 font-mono">{r.id}</td><td className="px-3 py-2">{r.batchNo}</td><td className="px-3 py-2">{r.operator}</td><td className="px-3 py-2">{r.zone}</td><td className="px-3 py-2">{r.category}</td><td className="px-3 py-2 max-w-[200px] truncate">{r.description}</td><td className="px-3 py-2 text-right">{r.payloadKg}</td><td className="px-3 py-2 text-right">{r.orbitAltKm.toLocaleString("en-IN")}</td><td className="px-3 py-2 text-right">{r.vehicleT}</td><td className="px-3 py-2">{r.engineType}</td><td className="px-3 py-2">{r.fuelType}</td><td className="px-3 py-2">{r.origin}</td><td className="px-3 py-2">{r.project}</td><td className="px-3 py-2">{r.state}</td><td className="px-3 py-2">{r.mode}</td><td className="px-3 py-2">{r.prodDate}</td><td className="px-3 py-2">{r.shipDate}</td><td className="px-3 py-2 text-right">{r.transitDays}</td><td className="px-3 py-2 text-right">{formatINR(r.contractValue)}</td><td className="px-3 py-2">{r.satelliteMake}</td><td className="px-3 py-2"><span className={`px-2 py-0.5 rounded-full text-xs ${sc === "green" ? "bg-green-100 text-green-700" : sc === "orange" ? "bg-orange-100 text-orange-700" : "bg-blue-100 text-blue-700"}`}>{r.status}</span></td><td className="px-3 py-2 max-w-[150px] truncate">{r.remarks}</td></tr>; })}</tbody></table></div>
        </div>
      )}
      {tab === 2 && (
        <div className="slc-analytics space-y-6">{renderCharts()}</div>
      )}
      {tab === 3 && (
        <div className="slc-insights space-y-4">
          {INSIGHTS.map((ins, i) => <div key={i} className="bg-white rounded-lg border p-5"><h4 className="text-sm font-semibold mb-2 text-[#581c87]">{ins.t}</h4><p className="text-xs text-gray-600 leading-relaxed">{ins.c}</p></div>)}
        </div>
      )}
    </div>
  );
}
