"use client";
import { useState } from "react";
import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, Legend } from "recharts";
import { PageHeader } from "@/components/shared/page-header";
import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar";
import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb";

const COLORS = ["#78350f", "#92400e", "#a16207", "#b45309", "#ca8a04", "#d4a017", "#e0b025", "#eab308"];
const OPERATORS = ["ISRO InSpace Bengaluru", "Dhruva Space Hyderabad", "Bellatrix Aerospace Bengaluru", "Skyroot Aerospace Hyderabad", "SSER Jodhpur", "DRDO Hyderabad", "Agnikul Cosmos Chennai", "Pixxel Bengaluru"];
const CATEGORIES = ["Net Capture 10cm Debris", "Harpoon Capture 1m Debris", "Electrodynamic Tether 5cm", "Laser Ablation 1-10cm", "Robotic Arm LEO Dock", "Drag Sail Deorbit 30cm", "Ion Beam Shepherd 20cm", "Tether Net GTO Removal"];
const SHIPMENT_STATUSES = ["Chaser Satellite Integration", "Capture Mechanism Testing", "Orbit Rendezvous Phase", "Capture Debris Contact", "Deorbit Burn Execution", "Reentry Disposal Complete"];
const ZONES = ["LEO 400-600km LEO Debris", "LEO 600-800km Polar Orbit", "LEO 800-1000km Navigation", "GEO 35,786km Graveyard", "MEO 20,200km GNSS", "SSO 500-600km Sun-Sync", "LEO 300-400km ISS Region", "HEO Molniya 500-40000km"];
const MODES = ["Polar Orbit Launch PSLV", "GTO Launch GSLV Mk-III", "LEO Dedicated SSLV", "Ride-Share PSLV-CA", "International Rideshare Falcon-9", "Sounding Rocket Suborbital"];
const TABS = ["Dashboard", "Mission Registry", "Debris Analytics", "Insights"];

const statusColor: Record<string, string> = { "Chaser Satellite Integration": "blue", "Capture Mechanism Testing": "orange", "Orbit Rendezvous Phase": "orange", "Capture Debris Contact": "orange", "Deorbit Burn Execution": "blue", "Reentry Disposal Complete": "green" };

function formatINR(n: number): string {
  if (n >= 10000000) return "\u20b9" + (n / 10000000).toFixed(1) + "Cr";
  if (n >= 100000) return "\u20b9" + (n / 100000).toFixed(1) + "L";
  return "\u20b9" + (n / 1000).toFixed(0) + "K";
}

const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const monthlyDebris = Array.from({ length: 12 }, (_, i) => ({ m: MO[i], net: +(2 + Math.sin(i * 0.5) * 1).toFixed(0), harpoon: +(1 + Math.cos(i * 0.6) * 0.5).toFixed(0), tether: +(3 + Math.sin(i * 0.4) * 1.2).toFixed(0), laser: +(1 + Math.cos(i * 0.7) * 0.5).toFixed(0) }));
const debrisDist = [{ n: "< 1cm", v: 45 }, { n: "1-10cm", v: 28 }, { n: "10-50cm", v: 12 }, { n: "50cm-1m", v: 8 }, { n: "1-5m", v: 5 }, { n: "> 5m (Rocket Bodies)", v: 2 }];
const trackCount = Array.from({ length: 12 }, (_, i) => ({ m: MO[i], leo: +(28000 + Math.sin(i * 0.3) * 2000).toFixed(0), geo: +(1500 + Math.cos(i * 0.4) * 200).toFixed(0), meo: +(450 + Math.sin(i * 0.5) * 50).toFixed(0) }));
const zoneThreat = [
  { zone: "LEO 400-600", objects: 12500 },
  { zone: "LEO 600-800", objects: 8200 },
  { zone: "LEO 800-1000", objects: 5800 },
  { zone: "GEO 35786", objects: 1500 },
  { zone: "MEO 20200", objects: 450 },
  { zone: "SSO 500-600", objects: 4800 }
];

const INSIGHTS = [
  { t: "India\u2019s Space Debris Mitigation: ISRO InSpace NDMD and DOS Guidelines", c: "India\u2019s space debris mitigation framework is governed by ISRO\u2019s Indian Space Debris Management Directives (NDMD) issued in 2019, aligned with the UN Inter-Agency Space Debris Coordination Committee (IADC) guidelines and the Space Debris Mitigation Standards (ISO 24113:2023). ISRO\u2019s Space Situational Awareness (SSA) tracking network at the Multi-Object Tracking Radar (MOTR) at Sriharikota (Range 1000km, tracking 100+ objects simultaneously) and the NETRA (Network for Space Object Tracking and Analysis) project at Bengaluru monitors 15,000+ tracked objects in LEO, MEO, and GEO. India has contributed 120 spacecraft to Earth orbit with 95 spacecraft still operational and 25 completed missions, of which 8 have been deorbited complying with the 25-year post-mission disposal rule. ISRO\u2019s InSpace (Indian National Space Promotion and Authorization Centre) has allocated \u20b9800 crore for active debris removal (ADR) missions in the 2025-2030 period, targeting removal of 50 large debris objects from LEO including Indian upper stages and defunct satellites. The DRDO Defence Space Agency (DSA) is developing a dedicated debris tracking satellite (DSA-TS1) with optical and radar sensors for real-time conjunction analysis and collision avoidance maneuvers for Indian operational satellites." },
  { t: "Net Capture and Harpoon Technology: Indian ADR Mission Concepts", c: "India\u2019s active debris removal concepts center on two primary capture mechanisms developed by a consortium of ISRO InSpace, Dhruva Space, and Bellatrix Aerospace. The net capture system designed by Dhruva Space Hyderabad uses a lightweight deployable net (5m x 5m, 2.5kg) made of Zylon high-modulus fibers with tungsten weights at corners, launched from a chaser satellite at 20m range closing at 2m/s relative velocity, achieving capture of 10cm-1m debris objects in LEO 400-800km. Post-capture, the chaser performs a deorbit burn using its 400N bipropellant thruster to lower the combined debris-chaser perigee to below 200km for atmospheric reentry within 90 days. The harpoon capture system developed by Bellatrix Aerospace Bengaluru uses a penetrating projectile (2kg, 120m/s muzzle velocity) with barbed tip that embeds into the debris body and attaches via a 50m Kevlar tether to the chaser, suitable for capturing rocket upper stages and large defunct satellites (1-5m) in LEO and GTO. India\u2019s first ADR demonstration mission (ADR-D1) planned for 2027 on PSLV-C65 will target a defunct Indian PSLV fourth stage (PS4) in 400km LEO using a net capture system developed under ISRO\u2019s InSpace ADR technology demonstration program." },
  { t: "Drag Sail and Electrodynamic Tether: Passive Debris Removal for Indian LEO Constellations", c: "Passive debris removal technologies using drag sails and electrodynamic tethers (EDT) are being developed for Indian satellite constellations to ensure 95% compliance with the 25-year post-mission disposal rule. Skyroot Aerospace Hyderabad has developed the SkySail drag sail system (10m x 10m aluminized Kapton membrane, 1.2kg stowed, 300kg/m2 area-to-mass ratio) that deploys autonomously at end-of-mission, increasing atmospheric drag by 100x and reducing deorbit time from 25 years to 2-3 years for 500kg satellites in 600km LEO. Agnikul Cosmos Chennai has designed an EDT system (1km aluminum wire, 2kg, 500V-5A operating at 400km) that generates Lorentz force by interacting with Earth\u2019s magnetic field, actively deorbiting debris from 600-1000km where atmospheric drag is insufficient for passive deorbit. Pixxel Bengaluru is integrating miniature drag sail modules (2m x 2m, 0.3kg) into its hyperspectral constellation satellites for automatic end-of-life deorbit compliance, with each drag sail module costing \u20b915 lakh and adding only 0.5kg to satellite mass. India\u2019s cumulative drag sail deployment target is 200 units across ISRO, Antrix/NSIL commercial, and private satellites by 2030." },
  { t: "Laser Ablation and Ion Beam Shepherd: Ground and Space-Based Debris Remediation", c: "India\u2019s laser-based debris remediation research is led by DRDO\u2019s Laser Science and Technology Centre (LASTEC) Gwalior, developing a ground-based pulsed laser system (Nd:YAG 1064nm, 10kW peak, 10ns pulse, 100Hz repetition) capable of ablating surface material from 1-10cm debris objects in 400-1000km LEO, generating a thrust impulse that modifies debris orbit perigee by 2-5km per pass to accelerate atmospheric reentry. The laser station requires 3m aperture adaptive optics for atmospheric turbulence compensation and can process 100 debris objects per day in clear weather conditions. ISRO\u2019s Space Applications Centre (SAC) Ahmedabad is developing a space-based ion beam shepherd (IBS) concept using a 200mW gridded ion thruster generating a focused xenon ion beam (50mm diameter, 10m range) that imparts thrust to debris without physical contact, enabling non-contact deorbit of 5-50cm debris objects in shared orbital regimes. The IBS chaser satellite (150kg, 500W solar array, 5kg xenon propellant) can deorbit 20 debris objects over its 3-year operational lifetime in 600km LEO. SSER (Space Situational Awareness and Evaluation Radar) Jodhpur is developing a next-generation phased array radar (S-band, 300kW peak, 500km range) for tracking sub-10cm debris objects that are currently invisible to conventional tracking systems, with first light expected in 2027." }
];

interface SDRRecord { id: string; batchNo: string; operator: string; zone: string; category: string; description: string; debrisSizeCm: number; altKm: number; chaserMassKg: number; captureMech: string; propulsionType: string; origin: string; project: string; state: string; mode: string; prodDate: string; shipDate: string; transitDays: number; contractValue: number; targetObj: string; status: string; remarks: string; }

const records: SDRRecord[] = [
  { id: "SDR-0001", batchNo: "INS/BLR/2025/NET-0012", operator: "ISRO InSpace Bengaluru", zone: "LEO 400-600km LEO Debris", category: "Net Capture 10cm Debris", description: "Net capture ADR-D1 mission targeting defunct PSLV PS4 upper stage 10cm debris in 450km LEO using Dhruva Zylon net 5mx5m deorbit burn 200km perigee", debrisSizeCm: 150, altKm: 450, chaserMassKg: 450, captureMech: "Deployable Net 5m", propulsionType: "Bipropellant 400N", origin: "ISRO InSpace Bengaluru KA", project: "ADR-D1/PS4 Deorbit Demo", state: "Karnataka", mode: "Polar Orbit Launch PSLV", prodDate: "2025-01-10", shipDate: "2025-04-18", transitDays: 0, contractValue: 850000000, targetObj: "PSLV-C37 PS4 Stage", status: "Chaser Satellite Integration", remarks: "ADR-D1 ISRO net chaser integration" },
  { id: "SDR-0002", batchNo: "DHR/HYD/2025/HRP-0018", operator: "Dhruva Space Hyderabad", zone: "LEO 600-800km Polar Orbit", category: "Harpoon Capture 1m Debris", description: "Harpoon capture chaser for 1m rocket body debris in 650km polar orbit using Bellatrix penetrating projectile 120m/s Kevlar tether 50m deorbit to 200km", debrisSizeCm: 100, altKm: 650, chaserMassKg: 680, captureMech: "Harpoon Penetrating", propulsionType: "Bipropellant 800N", origin: "Dhruva Hyderabad TS", project: "Dhruva ADR-H1 Polar Debris", state: "Telangana", mode: "GTO Launch GSLV Mk-III", prodDate: "2025-02-15", shipDate: "2025-05-22", transitDays: 0, contractValue: 1200000000, targetObj: "Rohini Sounding Body", status: "Capture Mechanism Testing", remarks: "Harpoon Dhruva capture mech testing" },
  { id: "SDR-0003", batchNo: "BEL/BLR/2025/EDT-0025", operator: "Bellatrix Aerospace Bengaluru", zone: "LEO 300-400km ISS Region", category: "Electrodynamic Tether 5cm", description: "EDT deorbit system for 5cm debris swarm in 350km ISS-adjacent orbit using 1km aluminum wire 500V Lorentz force 600km LEO non-contact deorbit", debrisSizeCm: 5, altKm: 350, chaserMassKg: 150, captureMech: "EDT Wire 1km", propulsionType: "Lorentz EDT", origin: "Bellatrix Bengaluru KA", project: "Bellatrix EDT-1 ISS Region", state: "Karnataka", mode: "Ride-Share PSLV-CA", prodDate: "2025-03-01", shipDate: "2025-06-10", transitDays: 0, contractValue: 320000000, targetObj: "5cm Debris Swarm 350km", status: "Orbit Rendezvous Phase", remarks: "EDT Bellatrix ISS region rendezvous" },
  { id: "SDR-0004", batchNo: "DRD/HYD/2025/LAS-0032", operator: "DRDO Hyderabad", zone: "LEO 800-1000km Navigation", category: "Laser Ablation 1-10cm", description: "Ground-based Nd:YAG pulsed laser 10kW 1064nm LASTEC Gwalior for 1-10cm debris ablation in 800-1000km LEO 3m adaptive optics 100 debris/day capacity", debrisSizeCm: 8, altKm: 900, chaserMassKg: 0, captureMech: "Ground Laser Ablation", propulsionType: "Laser Photon Pressure", origin: "LASTEC Gwalior MP", project: "DRDO LASTEC Laser Ablation LEO", state: "Madhya Pradesh", mode: "Sounding Rocket Suborbital", prodDate: "2025-01-25", shipDate: "2025-04-05", transitDays: 0, contractValue: 1500000000, targetObj: "1-10cm Debris 900km LEO", status: "Capture Mechanism Testing", remarks: "Laser LASTEC ground testing phase" },
  { id: "SDR-0005", batchNo: "SKR/HYD/2025/ARM-0041", operator: "Skyroot Aerospace Hyderabad", zone: "LEO 400-600km LEO Debris", category: "Robotic Arm LEO Dock", description: "Robotic arm chaser satellite with 3-DOF manipulator 2m reach for LEO docking and deorbit of defunct satellite 500kg in 500km with cooperative target grappling", debrisSizeCm: 200, altKm: 500, chaserMassKg: 800, captureMech: "Robotic Arm 3-DOF", propulsionType: "Green Monopropellant 200N", origin: "Skyroot Hyderabad TS", project: "Skyroot ADR-R1 Defunct Sat", state: "Telangana", mode: "LEO Dedicated SSLV", prodDate: "2025-04-10", shipDate: "2025-07-20", transitDays: 0, contractValue: 950000000, targetObj: "Defunct Cartosat-1 500kg", status: "Chaser Satellite Integration", remarks: "Robotic arm Skyroot chaser integration" },
  { id: "SDR-0006", batchNo: "SSR/JDP/2025/TRK-0048", operator: "SSER Jodhpur", zone: "GEO 35,786km Graveyard", category: "Tether Net GTO Removal", description: "SSER phased array radar S-band 300kW 500km range for tracking sub-10cm GEO debris providing conjunction analysis for ISRO INSAT and GSAT operational satellites", debrisSizeCm: 8, altKm: 35786, chaserMassKg: 0, captureMech: "Radar Tracking Only", propulsionType: "Passive Tracking", origin: "SSER Jodhpur RJ", project: "SSER Phased Array Radar GEO", state: "Rajasthan", mode: "Sounding Rocket Suborbital", prodDate: "2025-03-15", shipDate: "2025-06-28", transitDays: 0, contractValue: 680000000, targetObj: "GEO Debris Sub-10cm", status: "Capture Mechanism Testing", remarks: "SSER radar GEO tracking testing" },
  { id: "SDR-0007", batchNo: "ANK/CHN/2025/DRG-0055", operator: "Agnikul Cosmos Chennai", zone: "LEO 600-800km Polar Orbit", category: "Drag Sail Deorbit 30cm", description: "SkySail drag sail 10mx10m aluminized Kapton 1.2kg for 30cm satellite deorbit from 600km LEO reducing 25-year disposal to 3-year 100x drag increase", debrisSizeCm: 30, altKm: 600, chaserMassKg: 2, captureMech: "Drag Sail 10m x 10m", propulsionType: "Passive Atmospheric", origin: "Agnikul Chennai TN", project: "Agnikul SkySail-1 600km", state: "Tamil Nadu", mode: "Ride-Share PSLV-CA", prodDate: "2025-05-01", shipDate: "2025-08-08", transitDays: 0, contractValue: 150000000, targetObj: "Agnikul Demo Sat 30cm", status: "Orbit Rendezvous Phase", remarks: "SkySail Agnikul 600km deployment" },
  { id: "SDR-0008", batchNo: "PXX/BLR/2025/IBS-0062", operator: "Pixxel Bengaluru", zone: "SSO 500-600km Sun-Sync", category: "Ion Beam Shepherd 20cm", description: "Ion beam shepherd chaser with 200mW gridded ion thruster 50mm beam diameter 10m range for non-contact 20cm debris deorbit in SSO 550km 3-year life 20 targets", debrisSizeCm: 20, altKm: 550, chaserMassKg: 150, captureMech: "Ion Beam Non-Contact", propulsionType: "Xenon Ion 200mW", origin: "Pixxel Bengaluru KA", project: "Pixxel IBS-1 SSO Debris", state: "Karnataka", mode: "LEO Dedicated SSLV", prodDate: "2025-02-20", shipDate: "2025-05-18", transitDays: 0, contractValue: 420000000, targetObj: "20cm Debris SSO 550km", status: "Capture Debris Contact", remarks: "IBS Pixxel SSO debris contact" },
  { id: "SDR-0009", batchNo: "INS/BLR/2025/NET-0075", operator: "ISRO InSpace Bengaluru", zone: "LEO 400-600km LEO Debris", category: "Net Capture 10cm Debris", description: "ADR-D2 net capture mission targeting defunct GSAT-1A solar panel fragment in 420km LEO using upgraded net system 8mx8m with active corner thrusters for position control", debrisSizeCm: 80, altKm: 420, chaserMassKg: 500, captureMech: "Active Net 8m", propulsionType: "Bipropellant 400N", origin: "ISRO InSpace Bengaluru KA", project: "ADR-D2/GSAT-1A Fragment", state: "Karnataka", mode: "Polar Orbit Launch PSLV", prodDate: "2025-03-20", shipDate: "2025-06-25", transitDays: 0, contractValue: 920000000, targetObj: "GSAT-1A Solar Panel", status: "Deorbit Burn Execution", remarks: "ADR-D2 ISRO deorbit burn active" },
  { id: "SDR-0010", batchNo: "DHR/HYD/2025/HRP-0083", operator: "Dhruva Space Hyderabad", zone: "LEO 800-1000km Navigation", category: "Harpoon Capture 1m Debris", description: "Harpoon chaser ADR-H2 for defunct navigation satellite casing in 850km LEO using upgraded harpoon with cooperative grappling fixture 200m/s relative approach", debrisSizeCm: 120, altKm: 850, chaserMassKg: 720, captureMech: "Harpoon Grapple Fix", propulsionType: "Bipropellant 800N", origin: "Dhruva Hyderabad TS", project: "Dhruva ADR-H2 Nav Debris", state: "Telangana", mode: "GTO Launch GSLV Mk-III", prodDate: "2025-04-15", shipDate: "2025-07-28", transitDays: 0, contractValue: 1100000000, targetObj: "IRNSS-1A Debris 850km", status: "Chaser Satellite Integration", remarks: "Harpoon Dhruva Nav debris integration" },
  { id: "SDR-0011", batchNo: "DRD/HYD/2025/LAS-0091", operator: "DRDO Hyderabad", zone: "MEO 20,200km GNSS", category: "Laser Ablation 1-10cm", description: "DRDO LASTEC laser station phase-2 upgrade to 20kW 532nm green laser with improved atmospheric compensation for 1-10cm debris in MEO Navstar constellation region", debrisSizeCm: 5, altKm: 20200, chaserMassKg: 0, captureMech: "Ground Laser 20kW", propulsionType: "Laser Ablation v2", origin: "LASTEC Gwalior MP", project: "LASTEC-2 MEO Laser Ablation", state: "Madhya Pradesh", mode: "Sounding Rocket Suborbital", prodDate: "2025-05-10", shipDate: "2025-08-15", transitDays: 0, contractValue: 2200000000, targetObj: "MEO Debris 1-10cm", status: "Capture Mechanism Testing", remarks: "LASTEC-2 MEO laser upgrade testing" },
  { id: "SDR-0012", batchNo: "SKR/HYD/2025/ARM-0098", operator: "Skyroot Aerospace Hyderabad", zone: "LEO 400-600km LEO Debris", category: "Drag Sail Deorbit 30cm", description: "Skyroot SkySail-2 drag sail integration for 30cm microsatellite constellation deorbit compliance 200 units across Indian private satellites 10mx10m 1.2kg module", debrisSizeCm: 30, altKm: 480, chaserMassKg: 2, captureMech: "Drag Sail Modular", propulsionType: "Passive Atmospheric", origin: "Skyroot Hyderabad TS", project: "Skyroot SkySail-2 Batch-50", state: "Telangana", mode: "International Rideshare Falcon-9", prodDate: "2025-06-01", shipDate: "2025-09-10", transitDays: 0, contractValue: 750000000, targetObj: "50 Private Sats 480km", status: "Orbit Rendezvous Phase", remarks: "SkySail-2 Skyroot batch-50 deploy" },
  { id: "SDR-0013", batchNo: "ANK/CHN/2025/DRG-0105", operator: "Agnikul Cosmos Chennai", zone: "SSO 500-600km Sun-Sync", category: "Electrodynamic Tether 5cm", description: "Agnikul EDT-2 advanced electrodynamic tether 2km for 5cm debris swarm removal from 580km SSO generating Lorentz force using 800V power bus 3-year mission", debrisSizeCm: 5, altKm: 580, chaserMassKg: 180, captureMech: "EDT Wire 2km", propulsionType: "Lorentz EDT v2", origin: "Agnikul Chennai TN", project: "Agnikul EDT-2 SSO Swarm", state: "Tamil Nadu", mode: "Ride-Share PSLV-CA", prodDate: "2025-03-25", shipDate: "2025-07-05", transitDays: 0, contractValue: 380000000, targetObj: "5cm Swarm 580km SSO", status: "Reentry Disposal Complete", remarks: "EDT-2 Agnikul SSO reentry complete" },
  { id: "SDR-0014", batchNo: "INS/BLR/2025/NET-0118", operator: "ISRO InSpace Bengaluru", zone: "LEO 400-600km LEO Debris", category: "Net Capture 10cm Debris", description: "ADR-D3 cooperative debris capture with JAXA joint mission targeting Japanese rocket body fragment in 550km LEO using ISRO-JAXA shared net capture system", debrisSizeCm: 200, altKm: 550, chaserMassKg: 550, captureMech: "ISRO-JAXA Net 6m", propulsionType: "Bipropellant 600N", origin: "ISRO InSpace Bengaluru KA", project: "ISRO-JAXA ADR-D3 Joint", state: "Karnataka", mode: "International Rideshare Falcon-9", prodDate: "2025-04-20", shipDate: "2025-08-02", transitDays: 0, contractValue: 1800000000, targetObj: "H-IIA Debris 550km", status: "Chaser Satellite Integration", remarks: "ADR-D3 ISRO-JAXA joint integration" }
];

export default function SpaceDebrisRemovalLogisticsView() {
  const [tab, setTab] = useState(0);
  const [search, setSearch] = useState("");
  const [activeFilters, setActiveFilters] = useState<Record<string, string[]>>({});

  const totalAlt = records.reduce((s, r) => s + r.altKm, 0);
  const totalContract = records.reduce((s, r) => s + r.contractValue, 0);
  const activeMissions = records.filter(r => r.status !== "Reentry Disposal Complete").length;
  const completed = records.filter(r => r.status === "Reentry Disposal Complete").length;

  const kpis = [
    { l: "Total Objects Targeted", v: records.length, s: "14 debris removal records" },
    { l: "Active Missions", v: activeMissions, s: "Integration to deorbit" },
    { l: "Disposal Complete", v: completed, s: "Reentry confirmed" },
    { l: "Total Contract", v: formatINR(totalContract), s: "Aggregate contract value" }
  ];

  const filterGroups = [
    { key: "operator", label: "Operator", options: OPERATORS.map(d => ({ value: d, count: records.filter(r => r.operator === d).length })) },
    { key: "category", label: "Category", options: CATEGORIES.map(c => ({ value: c, count: records.filter(r => r.category === c).length })) },
    { key: "status", label: "Status", options: SHIPMENT_STATUSES.map(s => ({ value: s, count: records.filter(r => r.status === s).length })) },
    { key: "zone", label: "Zone", options: ZONES.map(z => ({ value: z, count: records.filter(r => r.zone === z).length })) },
    { key: "targetObj", label: "Target", options: ["PSLV-C37 PS4 Stage", "Rohini Sounding Body", "5cm Debris Swarm 350km", "1-10cm Debris 900km LEO", "Defunct Cartosat-1 500kg", "GEO Debris Sub-10cm", "Agnikul Demo Sat 30cm", "20cm Debris SSO 550km", "GSAT-1A Solar Panel", "IRNSS-1A Debris 850km", "MEO Debris 1-10cm", "50 Private Sats 480km", "5cm Swarm 580km SSO", "H-IIA Debris 550km"].map(t => ({ value: t, count: records.filter(r => r.targetObj === t).length })) }
  ];

  const toggleFilter = (k: string, v: string) => setActiveFilters(p => (function(){ const n={...p}; n[k]=(p[k]||[]).filter(x=>x!==v); if(n[k].length===0) delete n[k]; return n })());

  const filtered = records.filter(r => {
    if (search) {
      const q = search.toLowerCase();
      if (!r.id.toLowerCase().includes(q) && !r.batchNo.toLowerCase().includes(q) && !r.operator.toLowerCase().includes(q) && !r.description.toLowerCase().includes(q) && !r.category.toLowerCase().includes(q) && !r.project.toLowerCase().includes(q) && !r.captureMech.toLowerCase().includes(q)) return false;
    }
    return Object.entries(activeFilters).every(([k, vs]) => vs.includes(r[k as keyof SDRRecord] as string));
  });

  const COLS = ["ID", "Batch No", "Operator", "Zone", "Category", "Description", "Size (cm)", "Alt (km)", "Chaser (kg)", "Capture", "Propulsion", "Origin", "Project", "State", "Mode", "Prod Date", "Ship Date", "Transit (d)", "Contract (\u20b9)", "Target", "Status", "Remarks"];

  const renderCharts = () => (
    <>
      <div className="grid grid-cols-2 gap-6">
        <div className="sdr-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Monthly Debris Removal by Method</h3><BarChart data={monthlyDebris} height={220}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="m" /><YAxis /><Tooltip /><Legend /><Bar dataKey="net" fill="#78350f" radius={[4,4,0,0]} name="Net" /><Bar dataKey="harpoon" fill="#a16207" radius={[4,4,0,0]} name="Harpoon" /><Bar dataKey="tether" fill="#b45309" radius={[4,4,0,0]} name="Tether" /><Bar dataKey="laser" fill="#ca8a04" radius={[4,4,0,0]} name="Laser" /></BarChart></div>
        <div className="sdr-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Debris Size Distribution (%)</h3><PieChart width={400} height={220}><Pie data={debrisDist} dataKey="v" nameKey="n" cx="50%" cy="50%" outerRadius={80} label>{debrisDist.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}</Pie><Tooltip /></PieChart></div>
      </div>
      <div className="grid grid-cols-2 gap-6">
        <div className="sdr-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Tracked Space Objects by Region</h3><AreaChart data={trackCount} height={220}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="m" /><YAxis /><Tooltip /><Legend /><Area type="monotone" dataKey="leo" fill="#eab308" stroke="#78350f" strokeWidth={1} fillOpacity={0.4} name="LEO" /><Area type="monotone" dataKey="geo" fill="#d4a017" stroke="#a16207" strokeWidth={1} fillOpacity={0.4} name="GEO" /><Area type="monotone" dataKey="meo" fill="#e0b025" stroke="#b45309" strokeWidth={1} fillOpacity={0.4} name="MEO" /></AreaChart></div>
        <div className="sdr-chart bg-white rounded-lg border p-4"><h3 className="text-sm font-semibold mb-3">Debris Objects by Orbital Zone</h3><BarChart data={zoneThreat} height={220}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="zone" /><YAxis /><Tooltip /><Legend /><Bar dataKey="objects" fill="#92400e" radius={[4,4,0,0]} name="Tracked Objects" /></BarChart></div>
      </div>
    </>
  );

  return (
    <div className="sdr-root p-6 space-y-6">
      <PageHeader title="Space Debris Removal Logistics" description="Indian space debris removal logistics covering net capture 10cm harpoon 1m electrodynamic tether 5cm laser ablation 1-10cm robotic arm LEO dock drag sail 30cm deorbit ion beam shepherd 20cm tether net GTO removal ISRO InSpace Dhruva Bellatrix Skyroot DRDO LASTEC SSER Agnikul Pixxel LEO MEO GEO SSO ADR NDMD MOTR NETRA 800 crore 50 debris targets 2025-2030" />
      <div className="sdr-tabs flex gap-1 border-b border-gray-200">
        {TABS.map((t, i) => (<button key={t} onClick={() => setTab(i)} className={`sdr-tab px-4 py-2 text-sm font-medium rounded-t ${tab === i ? "bg-[#78350f] text-white" : "text-gray-600 hover:bg-amber-50"}`}>{t}</button>))}
      </div>
      <ModuleBreadcrumb items={[{ label: "Logistics", href: "#" }, { label: "Space Debris Removal" }]} />
      {tab === 0 && (
        <div className="sdr-dash space-y-6">
          <div className="grid grid-cols-4 gap-4">
            {kpis.map((k, i) => <div key={i} className="bg-white rounded-lg border p-4"><p className="text-xs text-gray-500">{k.l}</p><p className="text-2xl font-bold text-[#78350f]">{k.v}</p><p className="text-xs text-gray-400">{k.s}</p></div>)}
          </div>
          {renderCharts()}
          <div className="grid grid-cols-2 gap-6">
            {INSIGHTS.map((ins, i) => <div key={i} className="bg-white rounded-lg border p-4"><h4 className="text-sm font-semibold mb-2 text-[#78350f]">{ins.t}</h4><p className="text-xs text-gray-600 leading-relaxed">{ins.c}</p></div>)}
          </div>
        </div>
      )}
      {tab === 1 && (
        <div className="sdr-reg space-y-4">
          <SearchFilterToolbar searchQuery={search} onSearchChange={setSearch} onClearSearch={() => setSearch("")} filterGroups={filterGroups} activeFilters={activeFilters} onToggleFilter={toggleFilter} onClearAllFilters={() => setActiveFilters({})} totalItems={records.length} filteredCount={filtered.length} />
          <div className="sdr-table-wrap overflow-auto rounded-lg border bg-white"><table className="w-full text-xs"><thead><tr className="bg-gray-50 border-b">{COLS.map((c) => <th key={c} className="px-3 py-2 text-left font-medium text-gray-600 whitespace-nowrap">{c}</th>)}</tr></thead><tbody>{filtered.map((r) => { const sc = statusColor[r.status]; return <tr key={r.id} className={`border-b ${sc === "green" ? "bg-green-50 border-l-4 border-l-green-500" : sc === "orange" ? "bg-orange-50 border-l-4 border-l-orange-400" : sc === "blue" ? "bg-blue-50 border-l-4 border-l-blue-400" : ""}`}><td className="px-3 py-2 font-mono">{r.id}</td><td className="px-3 py-2">{r.batchNo}</td><td className="px-3 py-2">{r.operator}</td><td className="px-3 py-2">{r.zone}</td><td className="px-3 py-2">{r.category}</td><td className="px-3 py-2 max-w-[200px] truncate">{r.description}</td><td className="px-3 py-2 text-right">{r.debrisSizeCm}</td><td className="px-3 py-2 text-right">{r.altKm.toLocaleString("en-IN")}</td><td className="px-3 py-2 text-right">{r.chaserMassKg}</td><td className="px-3 py-2">{r.captureMech}</td><td className="px-3 py-2">{r.propulsionType}</td><td className="px-3 py-2">{r.origin}</td><td className="px-3 py-2">{r.project}</td><td className="px-3 py-2">{r.state}</td><td className="px-3 py-2">{r.mode}</td><td className="px-3 py-2">{r.prodDate}</td><td className="px-3 py-2">{r.shipDate}</td><td className="px-3 py-2 text-right">{r.transitDays}</td><td className="px-3 py-2 text-right">{formatINR(r.contractValue)}</td><td className="px-3 py-2">{r.targetObj}</td><td className="px-3 py-2"><span className={`px-2 py-0.5 rounded-full text-xs ${sc === "green" ? "bg-green-100 text-green-700" : sc === "orange" ? "bg-orange-100 text-orange-700" : "bg-blue-100 text-blue-700"}`}>{r.status}</span></td><td className="px-3 py-2 max-w-[150px] truncate">{r.remarks}</td></tr>; })}</tbody></table></div>
        </div>
      )}
      {tab === 2 && (
        <div className="sdr-analytics space-y-6">{renderCharts()}</div>
      )}
      {tab === 3 && (
        <div className="sdr-insights space-y-4">
          {INSIGHTS.map((ins, i) => <div key={i} className="bg-white rounded-lg border p-5"><h4 className="text-sm font-semibold mb-2 text-[#78350f]">{ins.t}</h4><p className="text-xs text-gray-600 leading-relaxed">{ins.c}</p></div>)}
        </div>
      )}
    </div>
  );
}
