"use client";

import React, { useState, useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { PageHeader } from '@/components/shared';
import { Flame } from 'lucide-react';

interface VanadiumSheetRecord {
  id: string;
  batchNo: string;
  city: string;
  manufacturer: string;
  sheetGrade: string;
  application: string;
  purityPercent: number;
  thicknessMm: number;
  investmentCr: number;
  status: string;
  priority: string;
  origin: string;
  destination: string;
  shipDate: string;
  transitDays: number;
  zone: string;
  remarks: string;
}

const vanadiumSheetRecords: VanadiumSheetRecord[] = [
  { id: 'VNS-0001', batchNo: 'VNS-B2401', city: 'Mumbai', manufacturer: 'MIDHANI', sheetGrade: 'V-4Cr-4Ti 99.7% Sheet', application: 'Fusion Blanket (IGCAR)', purityPercent: 99.7, thicknessMm: 2.0, investmentCr: 780, status: 'Delivered', priority: 'Critical', origin: 'MIDHANI Hyderabad (TG)', destination: 'IGCAR Kalpakkam (TN)', shipDate: '2026-07-15', transitDays: 1, zone: 'South', remarks: 'V-4Cr-4Ti sheet for IGCAR SST-1 first wall blanket module &#8594; 99.7% V-4Cr-4Ti &#8594; &#8377;780Cr for 1 tonne &#8594; India &#8377;23,400Cr fusion V &#8594; IGCAR SST-1 &#8594; 2.0 mm &#8594; &#8594; SWIP &#8594; &#8594; low activation &#8594; &#8594; blanket' },
  { id: 'VNS-0002', batchNo: 'VNS-B2402', city: 'Hyderabad', manufacturer: 'DRDO DMRL', sheetGrade: 'VMAT 99.5% Aerospace', application: 'Jet Engine Blade (HAL)', purityPercent: 99.5, thicknessMm: 1.5, investmentCr: 690, status: 'Delivered', priority: 'Critical', origin: 'DRDO DMRL Hyderabad (TG)', destination: 'HAL Bengaluru (KA)', shipDate: '2026-07-16', transitDays: 1, zone: 'South', remarks: 'Vanadium alloy sheet for HAL Tejas Mk2 compressor blade afterburner liner &#8594; 99.5% VMAT &#8594; &#8377;690Cr for 0.5 tonnes &#8594; India &#8377;20,700Cr aero V &#8594; HAL 200 blades &#8594; 1.5 mm &#8594; &#8594; hot isostatic &#8594; &#8594; 850&#176;C &#8594; &#8594; aero' },
  { id: 'VNS-0003', batchNo: 'VNS-B2403', city: 'Bengaluru', manufacturer: 'Tata Advanced Materials', sheetGrade: 'V2O5 99.99% Cathode', application: 'VRFB Battery (Reliance)', purityPercent: 99.99, thicknessMm: 0.5, investmentCr: 720, status: 'Delivered', priority: 'High', origin: 'Tata Advanced Materials Bengaluru (KA)', destination: 'Reliance Jamnagar (GJ)', shipDate: '2026-07-17', transitDays: 2, zone: 'South', remarks: 'V2O5 electrolyte sheet for Reliance 200MWh grid-scale VRFB energy storage &#8594; 99.99% V2O5 &#8594; &#8377;720Cr for 3 tonnes &#8594; India &#8377;21,600Cr energy V &#8594; Reliance 5 stations &#8594; 0.5 mm &#8594; &#8594; flow battery &#8594; &#8594; 1.26V cell &#8594; &#8594; VRFB' },
  { id: 'VNS-0004', batchNo: 'VNS-B2404', city: 'Pune', manufacturer: 'Bharat Forge', sheetGrade: 'FeV 80% Master Alloy', application: 'HSLA Rebar (Tata Steel)', purityPercent: 80.0, thicknessMm: 10.0, investmentCr: 380, status: 'Delivered', priority: 'Medium', origin: 'Bharat Forge Pune (MH)', destination: 'Tata Steel Jamshedpur (JH)', shipDate: '2026-07-18', transitDays: 2, zone: 'West', remarks: 'Ferro-vanadium master alloy sheet for Tata Steel TMT rebar micro-alloying &#8594; 80% V &#8594; &#8377;380Cr for 8 tonnes &#8594; India &#8377;11,400Cr steel V &#8594; Tata Steel 5M tonne &#8594; 10 mm &#8594; &#8594; EAF &#8594; &#8594; Fe-500D &#8594; &#8594; rebar' },
  { id: 'VNS-0005', batchNo: 'VNS-B2405', city: 'Chennai', manufacturer: 'IGCAR', sheetGrade: 'V-5Cr-5Ti 99.6% Nuclear', application: 'Fast Breeder Duct (BHAVINI)', purityPercent: 99.6, thicknessMm: 3.0, investmentCr: 850, status: 'Delivered', priority: 'Critical', origin: 'IGCAR Kalpakkam (TN)', destination: 'BHAVINI Kalpakkam (TN)', shipDate: '2026-07-19', transitDays: 0, zone: 'South', remarks: 'V-5Cr-5Ti sheet for PFBR prototype fast breeder fuel sub-assembly duct &#8594; 99.6% V-5Cr-5Ti &#8594; &#8377;850Cr for 0.6 tonnes &#8594; India &#8377;25,500Cr nuclear V &#8594; BHAVINI PFBR &#8594; 3.0 mm &#8594; &#8594; creep &#8594; &#8594; 600&#176;C &#8594; &#8594; duct' },
  { id: 'VNS-0006', batchNo: 'VNS-B2406', city: 'Ahmedabad', manufacturer: 'Gujarat Vanadium Tech', sheetGrade: 'V2O5 99.9% Catalyst', application: 'SO2 Converter (Reliance)', purityPercent: 99.9, thicknessMm: 1.0, investmentCr: 440, status: 'Delivered', priority: 'High', origin: 'Gujarat Vanadium Tech Ahmedabad (GJ)', destination: 'Reliance Vadodara (GJ)', shipDate: '2026-07-20', transitDays: 1, zone: 'West', remarks: 'V2O5 catalyst sheet for Reliance contact process sulphuric acid plant converter &#8594; 99.9% V2O5 &#8594; &#8377;440Cr for 2 tonnes &#8594; India &#8377;13,200Cr chemical V &#8594; Reliance 3 plants &#8594; 1.0 mm &#8594; &#8594; catalytic &#8594; &#8594; 450&#176;C &#8594; &#8594; H2SO4' },
  { id: 'VNS-0007', batchNo: 'VNS-B2407', city: 'Jaipur', manufacturer: 'Rajasthan Vanadium Corp', sheetGrade: 'VN 99.5% Nitride', application: 'Hard Coating (Wipro)', purityPercent: 99.5, thicknessMm: 0.02, investmentCr: 320, status: 'Delivered', priority: 'High', origin: 'Rajasthan Vanadium Corp Jaipur (RJ)', destination: 'Wipro Bengaluru (KA)', shipDate: '2026-07-21', transitDays: 2, zone: 'North', remarks: 'VN sputtering sheet target for Wipro TiAlN-VN nano-composite hard coating &#8594; 99.5% VN &#8594; &#8377;320Cr for 0.1 tonnes &#8594; India &#8377;9,600Cr coating V &#8594; Wipro 20K tools &#8594; 0.02 mm &#8594; &#8594; PVD &#8594; &#8594; 2500 HV &#8594; &#8594; coating' },
  { id: 'VNS-0008', batchNo: 'VNS-B2408', city: 'Bhubaneswar', manufacturer: 'NALCO', sheetGrade: 'V-10Ti-5Cr 99.7% Armour', application: 'APC Vehicle Plate (BEL)', purityPercent: 99.7, thicknessMm: 8.0, investmentCr: 560, status: 'Delivered', priority: 'High', origin: 'NALCO Bhubaneswar (OD)', destination: 'BEL Pune (MH)', shipDate: '2026-07-22', transitDays: 3, zone: 'East', remarks: 'V-10Ti-5Cr armour sheet for BEL Kalyani MPV infantry fighting vehicle spall liner &#8594; 99.7% V-Ti-Cr &#8594; &#8377;560Cr for 2 tonnes &#8594; India &#8377;16,800Cr defence V &#8594; BEL 500 IFV &#8594; 8.0 mm &#8594; &#8594; hot rolled &#8594; &#8594; STANAG &#8594; &#8594; armour' },
  { id: 'VNS-0009', batchNo: 'VNS-B2409', city: 'Coimbatore', manufacturer: 'Tamil Nadu Vanadium Corp', sheetGrade: 'NH4VO3 99.9% Precursor', application: 'Battery Electrolyte (Exicom)', purityPercent: 99.9, thicknessMm: 0.1, investmentCr: 410, status: 'Delivered', priority: 'High', origin: 'Tamil Nadu Vanadium Corp Coimbatore (TN)', destination: 'Exicom Gurgaon (HR)', shipDate: '2026-07-23', transitDays: 2, zone: 'South', remarks: 'NH4VO3 dissolved sheet for Exicom Telecomm 50kWh VRFB electrolyte solution &#8594; 99.9% NH4VO3 &#8594; &#8377;410Cr for 1.5 tonnes &#8594; India &#8377;12,300Cr energy V &#8594; Exicom 200 units &#8594; 0.1 mm &#8594; &#8594; 2M VOSO4 &#8594; &#8594; 25yr cycle &#8594; &#8594; VRFB' },
  { id: 'VNS-0010', batchNo: 'VNS-B2410', city: 'Surat', manufacturer: 'Gujarat V Products', sheetGrade: 'V-15Cr-5Ti 99.6% Hip', application: 'Sodium Fast Reactor (NPCIL)', purityPercent: 99.6, thicknessMm: 4.0, investmentCr: 680, status: 'Delivered', priority: 'Critical', origin: 'Gujarat V Products Surat (GJ)', destination: 'NPCIL Mumbai (MH)', shipDate: '2026-07-24', transitDays: 2, zone: 'West', remarks: 'V-15Cr-5Ti HIP sheet for NPCIL next-gen sodium-cooled fast reactor steam generator &#8594; 99.6% V-Cr-Ti &#8594; &#8377;680Cr for 1.2 tonnes &#8594; India &#8377;20,400Cr nuclear V &#8594; NPCIL 2 reactors &#8594; 4.0 mm &#8594; &#8594; HIP &#8594; &#8594; 550&#176;C &#8594; &#8594; SFR' },
  { id: 'VNS-0011', batchNo: 'VNS-B2411', city: 'Guwahati', manufacturer: 'Assam Vanadium Metals', sheetGrade: 'V2O5 99.95% Aerospace', application: 'SRB Bonding (DRDO)', purityPercent: 99.95, thicknessMm: 0.3, investmentCr: 350, status: 'Delivered', priority: 'High', origin: 'Assam Vanadium Metals Guwahati (AS)', destination: 'DRDO Hyderabad (TG)', shipDate: '2026-07-25', transitDays: 4, zone: 'East', remarks: 'V2O5 ultra-thin sheet for DRDO Agni-V SRB case insulation bonding agent &#8594; 99.95% V2O5 &#8594; &#8377;350Cr for 0.2 tonnes &#8594; India &#8377;10,500Cr defence V &#8594; DRDO 50 SRB &#8594; 0.3 mm &#8594; &#8594; adhesive &#8594; &#8594; EPDM &#8594; &#8594; bonding' },
  { id: 'VNS-0012', batchNo: 'VNS-B2412', city: 'Lucknow', manufacturer: 'UP Vanadium Industries', sheetGrade: 'V-4Cr-4Ti 99.7% Spent', application: 'Tritium Breeder (IGCAR)', purityPercent: 99.7, thicknessMm: 1.5, investmentCr: 620, status: 'Delayed', priority: 'Critical', origin: 'UP Vanadium Industries Lucknow (UP)', destination: 'IGCAR Kalpakkam (TN)', shipDate: '2026-07-01', transitDays: 27, zone: 'North', remarks: 'V-4Cr-4Ti lithium-coated sheet for IGCAR TBM test blanket module tritium breeding &#8594; 99.7% V-Cr-Ti &#8594; &#8377;620Cr for 0.8 tonnes &#8594; monsoon delay &#8594; India &#8377;18,600Cr fusion V &#8594; IGCAR TBM &#8594; 1.5 mm &#8594; &#8594; Li4SiO4 &#8594; &#8594; 500&#176;C &#8594; &#8594; breeder' },
  { id: 'VNS-0013', batchNo: 'VNS-B2413', city: 'Noida', manufacturer: 'SAIL', sheetGrade: 'V-5% Steel Rebar Plate', application: 'Seismic Rebar (L&amp;T)', purityPercent: 5.0, thicknessMm: 12.0, investmentCr: 340, status: 'Delivered', priority: 'Medium', origin: 'SAIL Rourkela (OD)', destination: 'L&amp;T Mumbai (MH)', shipDate: '2026-07-26', transitDays: 2, zone: 'East', remarks: 'V-alloyed steel rebar plate for L&amp;T Himalayan seismic Zone-V bridge construction &#8594; 5% V &#8594; &#8377;340Cr for 10 tonnes &#8594; India &#8377;10,200Cr infra V &#8594; L&amp;T 30 bridges &#8594; 12 mm &#8594; &#8594; QST &#8594; &#8594; Fe-550D &#8594; &#8594; seismic' },
  { id: 'VNS-0014', batchNo: 'VNS-B2414', city: 'Bhopal', manufacturer: 'BHEL', sheetGrade: 'V2O5 99.9% Petrochemical', application: 'Desulphurization (IOC)', purityPercent: 99.9, thicknessMm: 0.5, investmentCr: 290, status: 'Delivered', priority: 'Medium', origin: 'BHEL Bhopal (MP)', destination: 'IOC Paradip (OD)', shipDate: '2026-07-27', transitDays: 2, zone: 'North', remarks: 'V2O5 catalyst sheet for IOC Paradip refinery diesel hydrodesulphurization reactor &#8594; 99.9% V2O5 &#8594; &#8377;290Cr for 1.5 tonnes &#8594; India &#8377;8,700Cr petro V &#8594; IOC 3 units &#8594; 0.5 mm &#8594; &#8594; NiMo &#8594; &#8594; 380&#176;C &#8594; &#8594; HDS' }
];

const tabs = ['Dashboard', 'Registry', 'Analytics', 'Insights'] as const;
type Tab = typeof tabs[number];
const priorityColors: Record<string, string> = { Critical: 'bg-red-100 text-red-800', High: 'bg-amber-100 text-amber-800', Medium: 'bg-green-100 text-green-800', Low: 'bg-slate-100 text-slate-600' };
const delayedSet = new Set(vanadiumSheetRecords.filter(r => r.status === 'Delayed').map(r => r.id));

export default function VanadiumSheetLogisticsView() {
  const [activeTab, setActiveTab] = useState<Tab>('Dashboard');
  const [search, setSearch] = useState('');
  const [filters, setFilters] = useState<Record<string, string[]>>({});
  const toggleFilter = (k: string, v: string) => { setFilters(p => { const s = { ...p }; const a = s[k] || []; const i = a.indexOf(v); if (i > -1) { a.splice(i, 1); if (!a.length) delete s[k]; } else s[k] = [...a, v]; return s; }); };
  const filtered = useMemo(() => {
    let d = vanadiumSheetRecords;
    if (search) { const q = search.toLowerCase(); d = d.filter(r => r.id.toLowerCase().includes(q) || r.batchNo.toLowerCase().includes(q) || r.sheetGrade.toLowerCase().includes(q) || r.application.toLowerCase().includes(q) || r.city.toLowerCase().includes(q) || r.manufacturer.toLowerCase().includes(q)); }
    Object.entries(filters).forEach(([k, vs]) => { if (vs.length) d = d.filter(r => { const v = String((r as unknown as Record<string, unknown>)[k] ?? ''); return vs.some(x => v.toLowerCase().includes(x.toLowerCase())); }); });
    return d;
  }, [search, filters]);
  const totalCr = filtered.reduce((s: number, r) => s + r.investmentCr, 0);
  const avgPurity = filtered.length ? filtered.reduce((s: number, r) => s + r.purityPercent, 0) / filtered.length : 0;
  const delayedCount = filtered.filter(r => r.status === 'Delayed').length;

  return (
    <div className="space-y-6">
      <PageHeader title="Vanadium Sheet Logistics" description="Indian vanadium sheet supply chain tracking for fusion energy, aerospace, VRFB energy storage, nuclear fast reactors, defence armour, and petrochemical catalyst sectors" />
      <div className="flex gap-2 border-b">
        {tabs.map(t => (<button key={t} onClick={() => setActiveTab(t)} className={`px-4 py-2 text-sm font-medium ${activeTab === t ? 'border-b-2 border-orange-500 text-orange-700' : 'text-muted-foreground hover:text-foreground'}`}>{t}</button>))}
      </div>
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card><CardContent><div className="text-2xl font-bold text-orange-600">{filtered.length}</div><div className="text-xs text-muted-foreground">Total Shipments</div></CardContent></Card>
        <Card><CardContent><div className="text-2xl font-bold text-orange-600">&#8377;{totalCr.toLocaleString()} Cr</div><div className="text-xs text-muted-foreground">Total Investment</div></CardContent></Card>
        <Card><CardContent><div className="text-2xl font-bold text-orange-600">{avgPurity.toFixed(2)}%</div><div className="text-xs text-muted-foreground">Avg Purity</div></CardContent></Card>
        <Card><CardContent><div className="text-2xl font-bold text-red-500">{delayedCount}</div><div className="text-xs text-muted-foreground">Delayed Shipments</div></CardContent></Card>
      </div>
      {(activeTab === 'Dashboard' || activeTab === 'Registry') && (
        <div className="space-y-4">
          <div className="flex flex-wrap gap-2">
            <input placeholder="Search ID, grade, application, city..." value={search} onChange={e => setSearch(e.target.value)} className="border rounded-md px-3 py-1.5 text-sm flex-1 min-w-48" />
            {['status', 'priority', 'zone'].map(f => { const opts = [...new Set(vanadiumSheetRecords.map(r => (r as unknown as Record<string, unknown>)[f] as string))]; return (<div key={f} className="flex flex-wrap gap-1">{opts.map(o => (<Badge key={o} variant={(filters[f] || []).includes(o) ? 'default' : 'outline'} className="cursor-pointer text-xs" onClick={() => toggleFilter(f, o)}>{o}</Badge>))}</div>); })}
          </div>
          <div className="rounded-md border"><div className="max-h-96 overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-background"><tr><th className="p-2 text-left">ID</th><th className="p-2 text-left">Batch</th><th className="p-2 text-left">Grade</th><th className="p-2 text-left">Application</th><th className="p-2 text-right">Purity%</th><th className="p-2 text-right">&#8377;Cr</th><th className="p-2 text-left">Status</th></tr></thead><tbody>{filtered.map(r => (<tr key={r.id} className={`border-t ${delayedSet.has(r.id) ? 'border-l-4 border-l-red-500 bg-red-50/30' : ''}`}><td className="p-2">{r.id}</td><td className="p-2">{r.batchNo}</td><td className="p-2">{r.sheetGrade}</td><td className="p-2">{r.application}</td><td className="p-2 text-right">{r.purityPercent}</td><td className="p-2 text-right">{r.investmentCr}</td><td className="p-2"><Badge variant={r.status === 'Delivered' ? 'default' : 'destructive'}>{r.status}</Badge></td></tr>))}</tbody></table></div></div>
        </div>
      )}
      {(activeTab === 'Dashboard' || activeTab === 'Analytics') && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <Card><CardHeader><CardTitle className="text-sm">Investment by Application</CardTitle></CardHeader><CardContent><div className="space-y-2">{(Object.entries(filtered.reduce((m, r) => { m[r.application] = (m[r.application] || 0) + r.investmentCr; return m }, {} as Record<string, number>)) as [string, number][]).sort((a, b) => b[1] - a[1]).slice(0, 7).map(([a, v]) => (<div key={a} className="flex justify-between text-sm"><span>{a}</span><span className="font-medium">&#8377;{v}Cr</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Shipments by Zone</CardTitle></CardHeader><CardContent><div className="space-y-2">{(Object.entries(filtered.reduce((m, r) => { m[r.zone] = (m[r.zone] || 0) + 1; return m }, {} as Record<string, number>)) as [string, number][]).sort((a, b) => b[1] - a[1]).map(([z, c]) => (<div key={z} className="flex justify-between text-sm"><span>{z}</span><span className="font-medium">{c}</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Top Routes by Value</CardTitle></CardHeader><CardContent><div className="space-y-2">{filtered.sort((a, b) => b.investmentCr - a.investmentCr).slice(0, 7).map(r => (<div key={r.id} className="flex justify-between text-sm"><span>{r.origin.split('(')[0]} &#8594; {r.destination.split('(')[0]}</span><span className="font-medium">&#8377;{r.investmentCr}Cr</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Nuclear &amp; Fusion</CardTitle></CardHeader><CardContent><div className="space-y-2">{filtered.filter(r => r.application.toLowerCase().includes('fusion') || r.application.toLowerCase().includes('nuclear') || r.application.toLowerCase().includes('reactor') || r.application.toLowerCase().includes('breeder') || r.application.toLowerCase().includes('npcil') || r.application.toLowerCase().includes('igcar')).sort((a, b) => b.investmentCr - a.investmentCr).map(r => (<div key={r.id} className="flex justify-between text-sm"><span>{r.sheetGrade}</span><span className="font-medium">&#8377;{r.investmentCr}Cr</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">By Priority</CardTitle></CardHeader><CardContent><div className="space-y-2">{Object.entries(filtered.reduce((m, r) => { m[r.priority] = (m[r.priority] || 0) + 1; return m }, {} as Record<string, number>)).map(([p, c]) => (<div key={p} className="flex justify-between text-sm"><span className={priorityColors[p] || ''}>{p}</span><span className="font-medium">{c}</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Sheet Type Distribution</CardTitle></CardHeader><CardContent><div className="space-y-2">{[{ l: 'Pure V Alloy', f: filtered.filter(r => r.sheetGrade.startsWith('V-') && !r.sheetGrade.includes('O5')).length }, { l: 'V2O5 Compound', f: filtered.filter(r => r.sheetGrade.includes('V2O5')).length }, { l: 'Ferro-Vanadium', f: filtered.filter(r => r.sheetGrade.includes('FeV')).length }, { l: 'Other (VN/NH4VO3)', f: filtered.filter(r => r.sheetGrade.includes('VN ') || r.sheetGrade.includes('NH4VO3')).length }].map(b => (<div key={b.l} className="flex justify-between text-sm"><span>{b.l}</span><span className="font-medium">{b.f}</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Top Manufacturers</CardTitle></CardHeader><CardContent><div className="space-y-2">{(Object.entries(filtered.reduce((m, r) => { m[r.manufacturer] = (m[r.manufacturer] || 0) + r.investmentCr; return m }, {} as Record<string, number>)) as [string, number][]).sort((a, b) => b[1] - a[1]).slice(0, 7).map(([m, v]) => (<div key={m} className="flex justify-between text-sm"><span>{m}</span><span className="font-medium">&#8377;{v}Cr</span></div>))}</div></CardContent></Card>
          <Card><CardHeader><CardTitle className="text-sm">Avg Transit Days</CardTitle></CardHeader><CardContent><div className="space-y-2">{filtered.length ? (Object.entries(filtered.reduce((m, r) => { m[r.zone] = (m[r.zone] || [] as number[]).concat(r.transitDays); return m }, {} as Record<string, number[]>)) as [string, number[]][]).map(([z, d]) => (<div key={z} className="flex justify-between text-sm"><span>{z}</span><span className="font-medium">{(d.reduce((s, n) => s + n, 0) / d.length).toFixed(1)}d</span></div>)) : []}</div></CardContent></Card>
        </div>
      )}
      {(activeTab === 'Dashboard' || activeTab === 'Insights') && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Card><CardContent><div className="text-sm font-medium text-orange-600 mb-2">IGCAR V-4Cr-4Ti Fusion Blanket</div><div className="text-xs text-muted-foreground">IGCAR manufacturing V-4Cr-4Ti alloy sheets for SST-1 tokamak first wall and ITER test blanket module. V-4Cr-4Ti offers 100x lower long-lived radioactivity activation vs Inconel after neutron irradiation, enabling hands-on maintenance within 100 years. India fabricating under &#8377;5,200Cr National Fusion Mission with MIDHANI primary supplier.</div></CardContent></Card>
          <Card><CardContent><div className="text-sm font-medium text-orange-600 mb-2">Reliance 200MWh Grid-Scale VRFB</div><div className="text-xs text-muted-foreground">Reliance Green deploying vanadium redox flow batteries using domestically produced V2O5 electrolyte sheets for 200MWh Jamnagar grid-scale storage. VRFB offers 25-year cycle life with zero degradation unlike Li-ion. India targeting 10GWh VRFB by 2030 under &#8377;15,000Cr National Energy Storage Mission with Gujarat Vanadium Tech supplying electrolyte.</div></CardContent></Card>
          <Card><CardContent><div className="text-sm font-medium text-orange-600 mb-2">BHAVINI Fast Breeder Duct Manufacturing</div><div className="text-xs text-muted-foreground">BHAVINI producing V-5Cr-5Ti fuel sub-assembly ducts for Prototype Fast Breeder Reactor operating at 550&#176;C with liquid sodium coolant. Vanadium alloys provide superior swelling resistance vs 316SS at high neutron fluence. India planning 4 additional FBRs by 2035 under &#8377;45,000Cr nuclear expansion programme.</div></CardContent></Card>
          <Card><CardContent><div className="text-sm font-medium text-orange-600 mb-2">DRDO Hypersonic V-10Ti-5Cr Armour</div><div className="text-xs text-muted-foreground">DRDO DMRL developing V-10Ti-5Cr alloy armour plates for next-gen BMP-II+ and Futuristic IFV providing 30% weight reduction over RAFAEL steel armour at equivalent STANAG Level 4 protection. NALCO co-producing sheet via hot-rolling plus annealing under &#8377;2,400Cr DRDO Advanced Armour Materials Mission.</div></CardContent></Card>
        </div>
      )}
    </div>
  );
}
