#!/usr/bin/env python3
"""Generate R270 modules: Returns Quality Lab + Port Operations Hub"""

import os

# ──────────────────────────────────────────────────────────────
# MODULE 1: Returns Quality Lab (rql-*)
# ──────────────────────────────────────────────────────────────
rql = []
rql.append('"use client"')
rql.append('import { useState, useMemo } from "react"')
rql.append('import { AreaChart, Area, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts"')
rql.append('import { BarChart3, TrendingUp, TrendingDown, MapPin, Package, Timer, ArrowUpDown, FlaskConical, AlertTriangle, CheckCircle2, Route, Activity, Thermometer, ShieldCheck, ShieldAlert, Clock, DollarSign, Microscope, TestTubes, RotateCcw, XCircle, ThumbsUp, ThumbsDown } from "lucide-react"')
rql.append('import { PageHeader } from "@/components/shared/page-header"')
rql.append('import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar"')
rql.append('import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb"')
rql.append('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
rql.append('import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"')
rql.append('import { Badge } from "@/components/ui/badge"')
rql.append('')
rql.append('const RETURN_REASONS = ["defective", "wrong_item", "damaged", "quality_fail", "expired", "customer_change", "warranty", "recall"] as const')
rql.append('const INSPECTION_STATUS = ["pending", "in_progress", "passed", "failed", "quarantine", "disposed"] as const')
rql.append('const TEST_TYPES = ["visual", "functional", "dimensional", "electrical", "chemical", "stress_test", "drop_test", "leak_test"] as const')
rql.append('const SEVERITY = ["critical", "major", "minor", "cosmetic"] as const')
rql.append('const WAREHOUSES = ["Mumbai DC-1", "Delhi DC-2", "Bangalore DC-3", "Chennai DC-4", "Hyderabad DC-5", "Pune DC-6"] as const')
rql.append('const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] as const')
rql.append('const TH = { pri: "#ec4899", sec: "#8b5cf6", ter: "#f59e0b", ok: "#059669", warn: "#d97706", err: "#dc2626" }')
rql.append('const PC = ["#ec4899", "#8b5cf6", "#059669", "#f59e0b", "#dc2626", "#14b8a6", "#3b82f6", "#f97316"]')
rql.append('')
rql.append('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297) * 233280; return x - Math.floor(x) }')
rql.append('function ri(min: number, max: number, seed: number): number { return Math.floor(seededRandom(seed) * (max - min + 1)) + min }')
rql.append('function pick<T>(arr: readonly T[], seed: number): T { return arr[Math.floor(seededRandom(seed) * arr.length)] }')
rql.append('')
rql.append('function ReasonBadge({ reason }: { reason: string }) {')
rql.append('  const cols: Record<string, string> = { defective: "bg-red-100 text-red-700 dark:bg-red-900/30", wrong_item: "bg-amber-100 text-amber-700", damaged: "bg-orange-100 text-orange-700 dark:bg-orange-900/30", quality_fail: "rql-quality-fail bg-violet-100 text-violet-700 dark:bg-violet-900/30", expired: "bg-gray-100 text-gray-600", customer_change: "bg-blue-100 text-blue-700", warranty: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30", recall: "rql-recall bg-rose-100 text-rose-700 dark:bg-rose-900/30 shadow-[0_0_6px_rgba(244,63,94,0.3)]" }')
rql.append('  return <span className={"rql-reason-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[reason] || "bg-gray-100 text-gray-700")}>{reason.replace(/_/g, " ")}</span>')
rql.append('}')
rql.append('')
rql.append('function StatusBadge({ status }: { status: string }) {')
rql.append('  const cols: Record<string, string> = { pending: "rql-pending bg-gray-200 text-gray-600 dark:bg-gray-700", in_progress: "rql-in-progress bg-blue-100 text-blue-700 dark:bg-blue-900/30 shadow-[0_0_6px_rgba(59,130,246,0.3)]", passed: "rql-passed bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 shadow-[0_0_6px_rgba(5,150,105,0.3)]", failed: "rql-failed bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_6px_rgba(220,38,38,0.3)]", quarantine: "rql-quarantine bg-amber-100 text-amber-700 dark:bg-amber-900/30 shadow-[0_0_6px_rgba(217,119,6,0.3)]", disposed: "bg-gray-300 text-gray-500" }')
rql.append('  return <span className={"rql-status-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[status] || "")}>{status.replace(/_/g, " ")}</span>')
rql.append('}')
rql.append('')
rql.append('function TestBadge({ type }: { type: string }) {')
rql.append('  return <span className={"rql-test-badge inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-medium bg-purple-100 text-purple-700 dark:bg-purple-900/30"}>{type.replace(/_/g, " ")}</span>')
rql.append('}')
rql.append('')
rql.append('function SeverityBadge({ sev }: { sev: string }) {')
rql.append('  const cols: Record<string, string> = { critical: "rql-critical bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_8px_rgba(220,38,38,0.4)]", major: "bg-orange-100 text-orange-700 dark:bg-orange-900/30", minor: "bg-amber-100 text-amber-700", cosmetic: "bg-gray-100 text-gray-600" }')
rql.append('  return <span className={"rql-severity-badge inline-flex items-center px-1.5 py-0.5 rounded text-[9px] font-bold uppercase " + (cols[sev] || "")}>{sev}</span>')
rql.append('}')
rql.append('')
rql.append('function ScoreBar({ value }: { value: number }) {')
rql.append('  const col = value >= 80 ? TH.ok : value >= 50 ? TH.warn : TH.err')
rql.append('  return <div className="rql-score-bar flex items-center gap-1.5"><div className="w-16 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: value + "%", backgroundColor: col }}/></div><span className="text-[10px] font-bold" style={{ color: col }}>{value}/100</span></div>')
rql.append('}')
rql.append('')
rql.append('function HealthRing({ pct, label, color }: { pct: number; label: string; color: string }) {')
rql.append('  const r = 28, c = 2 * Math.PI * r, off = c - (pct / 100) * c')
rql.append('  return <div className="rql-health-ring flex flex-col items-center"><svg width="68" height="68" viewBox="0 0 68 68"><circle cx="34" cy="34" r={r} fill="none" stroke="#e5e7eb" strokeWidth="6"/><circle cx="34" cy="34" r={r} fill="none" stroke={color} strokeWidth="6" strokeDasharray={c} strokeDashoffset={off} strokeLinecap="round" transform="rotate(-90 34 34)" className="transition-all duration-700"/><text x="34" y="38" textAnchor="middle" className="text-[11px] font-bold" fill={color}>{pct}%</text></svg><span className="text-[9px] text-gray-500 mt-0.5">{label}</span></div>')
rql.append('}')
rql.append('')
rql.append('function KpiTile({ label, value, change, icon: Icon }: { label: string; value: string; change: number; icon: React.ComponentType<{ className?: string }> }) {')
rql.append('  return <div className="rql-kpi-tile bg-white dark:bg-gray-800 rounded-xl p-4 border border-gray-200 dark:border-gray-700 shadow-sm hover:shadow-md transition-shadow"><div className="flex items-center justify-between mb-2"><span className="text-[11px] font-medium text-gray-500">{label}</span><Icon className="w-4 h-4 text-pink-500"/></div><div className="text-xl font-bold text-gray-900 dark:text-gray-100">{value}</div><div className={"flex items-center gap-1 mt-1 text-[10px] font-semibold " + (change >= 0 ? "text-emerald-600" : "text-red-500")}><span>{change >= 0 ? "+" : ""}{change}%</span></div></div>')
rql.append('}')
rql.append('')
rql.append('function ValueTile({ label, value, color }: { label: string; value: string; color: string }) {')
rql.append('  return <div className="rql-value-tile bg-white dark:bg-gray-800 rounded-lg p-3 border border-gray-200 dark:border-gray-700"><div className="text-[10px] text-gray-500 mb-1">{label}</div><div className="text-lg font-bold" style={{ color }}>{value}</div></div>')
rql.append('}')
rql.append('')
rql.append('const returns = Array.from({ length: 55 }, (_, i) => {')
rql.append('  const seed = i * 179 + 53')
rql.append('  const status = pick(INSPECTION_STATUS, seed)')
rql.append('  const reason = pick(RETURN_REASONS, seed + 1)')
rql.append('  return {')
rql.append('    id: "RQL-" + String(i + 9001).padStart(4, "0"), reason, status,')
rql.append('    testType: pick(TEST_TYPES, seed + 2), severity: pick(SEVERITY, seed + 3),')
rql.append('    warehouse: pick(WAREHOUSES, seed + 4), inspector: pick(["Dr. Patel", "Ms. Sharma", "Mr. Kumar", "Dr. Singh", "Ms. Gupta", "Mr. Rao"], seed + 5),')
rql.append('    score: status === "passed" ? ri(80, 100, seed + 6) : status === "failed" ? ri(10, 45, seed + 6) : ri(0, 100, seed + 6),')
rql.append('    tests: ri(1, 8, seed + 7), defects: status === "failed" ? ri(1, 8, seed + 8) : 0,')
rql.append('    turnaround: ri(1, 48, seed + 9), value: ri(500, 50000, seed + 10),')
rql.append('    returnRoute: pick(["refurbish", "resell", "recycle", "dispose", "vendor_return", "warranty_repair"], seed + 11)')
rql.append('  }')
rql.append('})')
rql.append('')
rql.append('const monthlyData = MO.map((m, i) => ({ month: m, returns: ri(120, 300, i * 19 + 1), passRate: ri(65, 95, i * 19 + 2), defects: ri(5, 30, i * 19 + 3), turnaround: ri(4, 24, i * 19 + 4) }))')
rql.append('const reasonDist = RETURN_REASONS.map((r, i) => ({ name: r.replace(/_/g, " "), value: ri(3, 20, i * 47) }))')
rql.append('')
rql.append('export default function ReturnsQualityLabView() {')
rql.append('  const [tab, setTab] = useState("dashboard")')
rql.append('  const [searchQuery, setSearchQuery] = useState("")')
rql.append('  const [activeFilters, setActiveFilters] = useState<Record<string, string[]>>({})')
rql.append('')
rql.append('  const filteredReturns = useMemo(() => {')
rql.append('    return returns.filter(r => {')
rql.append('      if (searchQuery && !r.id.toLowerCase().includes(searchQuery.toLowerCase()) && !r.warehouse.toLowerCase().includes(searchQuery.toLowerCase()) && !r.inspector.toLowerCase().includes(searchQuery.toLowerCase())) return false')
rql.append('      if (activeFilters["reason"] && !activeFilters["reason"].includes(r.reason)) return false')
rql.append('      if (activeFilters["status"] && !activeFilters["status"].includes(r.status)) return false')
rql.append('      if (activeFilters["severity"] && !activeFilters["severity"].includes(r.severity)) return false')
rql.append('      return true')
rql.append('    })')
rql.append('  }, [searchQuery, activeFilters])')
rql.append('')
rql.append('  const filterGroups = [')
rql.append('    { key: "reason", label: "Reason", options: RETURN_REASONS.map(r => ({ value: r, label: r.replace(/_/g, " "), count: 0 })) },')
rql.append('    { key: "status", label: "Status", options: INSPECTION_STATUS.map(s => ({ value: s, label: s.replace(/_/g, " "), count: 0 })) },')
rql.append('    { key: "severity", label: "Severity", options: SEVERITY.map(s => ({ value: s, label: s, count: 0 })) }')
rql.append('  ]')
rql.append('')
rql.append('  const totalReturns = returns.length')
rql.append('  const passRate = Math.round(returns.filter(r => r.status === "passed").length / totalReturns * 100)')
rql.append('  const totalValue = returns.reduce((s, r) => s + r.value, 0)')
rql.append('  const failCount = returns.filter(r => r.status === "failed").length')
rql.append('')
rql.append('  return (')
rql.append('    <div className="space-y-4">')
rql.append('      <PageHeader title="Returns Quality Lab" description="Systematic inspection, testing and disposition of returned merchandise" />')
rql.append('      <Tabs value={tab} onValueChange={setTab}>')
rql.append('        <TabsList className="rql-tabs-list">')
rql.append('          <TabsTrigger value="dashboard">Dashboard</TabsTrigger>')
rql.append('          <TabsTrigger value="inspections">Inspections</TabsTrigger>')
rql.append('          <TabsTrigger value="analytics">Analytics</TabsTrigger>')
rql.append('          <TabsTrigger value="insights">Insights</TabsTrigger>')
rql.append('        </TabsList>')
rql.append('        <TabsContent value="dashboard">')
rql.append('          <div className="grid grid-cols-4 gap-4 mb-4">')
rql.append('            <KpiTile label="Total Inspections" value={String(totalReturns)} change={14} icon={FlaskConical} />')
rql.append('            <KpiTile label="Pass Rate" value={passRate + "%"} change={5} icon={CheckCircle2} />')
rql.append('            <KpiTile label="Total Value" value={"&#8377;" + (totalValue / 100000).toFixed(1) + "L"} change={-8} icon={DollarSign} />')
rql.append('            <KpiTile label="Failed Items" value={String(failCount)} change={-12} icon={XCircle} />')
rql.append('          </div>')
rql.append('          <div className="flex gap-6 mb-4 justify-center flex-wrap">')
rql.append('            <HealthRing pct={passRate} label="Pass Rate" color={TH.ok} />')
rql.append('            <HealthRing pct={88} label="Test Coverage" color={TH.pri} />')
rql.append('            <HealthRing pct={76} label="Turnaround" color={TH.sec} />')
rql.append('            <HealthRing pct={92} label="Accuracy" color={TH.ok} />')
rql.append('            <HealthRing pct={69} label="Recovery" color={TH.ter} />')
rql.append('            <HealthRing pct={85} label="Compliance" color={TH.pri} />')
rql.append('          </div>')
rql.append('          <div className="grid grid-cols-3 gap-4">')
rql.append('            <Card className="rql-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Return Volume</CardTitle></CardHeader><CardContent><LineChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Line type="monotone" dataKey="returns" stroke={TH.pri} strokeWidth={2} /></LineChart></CardContent></Card>')
rql.append('            <Card className="rql-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Defects Found</CardTitle></CardHeader><CardContent><BarChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey="defects" fill={TH.err} radius={[4, 4, 0, 0]} /></BarChart></CardContent></Card>')
rql.append('            <Card className="rql-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Pass Rate Trend</CardTitle></CardHeader><CardContent><AreaChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Area type="monotone" dataKey="passRate" stroke={TH.ok} fill="rgba(5,150,105,0.15)" strokeWidth={2} /></AreaChart></CardContent></Card>')
rql.append('          </div>')
rql.append('        </TabsContent>')
rql.append('        <TabsContent value="inspections">')
rql.append('          <ModuleBreadcrumb items={[{ label: "Quality Lab" }, { label: "All Inspections" }]} />')
rql.append('          <SearchFilterToolbar searchQuery={searchQuery} onSearchChange={setSearchQuery} onClearSearch={() => setSearchQuery("")} activeFilters={activeFilters} filterGroups={filterGroups} onToggleFilter={(k, v) => setActiveFilters(p => { const arr = p[k] || []; return arr.includes(v) ? (function(){ const n = {...p}; n[k] = arr.filter(x => x !== v); if(n[k].length === 0) delete n[k]; return n })() : {...p, [k]: [...arr, v]} })} onClearAllFilters={() => setActiveFilters({})} totalItems={totalReturns} filteredCount={filteredReturns.length} onRefresh={() => {}} placeholder="Search by ID, warehouse, or inspector..." />')
rql.append('          <Card className="rql-table-card"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50"><th className="px-3 py-2 text-left font-semibold">ID</th><th className="px-3 py-2 text-left font-semibold">Reason</th><th className="px-3 py-2 text-left font-semibold">Status</th><th className="px-3 py-2 text-left font-semibold">Test</th><th className="px-3 py-2 text-left font-semibold">Severity</th><th className="px-3 py-2 text-left font-semibold">Warehouse</th><th className="px-3 py-2 text-left font-semibold">Score</th><th className="px-3 py-2 text-left font-semibold">Defects</th><th className="px-3 py-2 text-left font-semibold">Turnaround</th><th className="px-3 py-2 text-left font-semibold">Value</th></tr></thead><tbody>')
rql.append('            {filteredReturns.slice(0, 30).map((r) => (')
rql.append('              <tr key={r.id} className="rql-table-row border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800/30 transition-colors">')
rql.append('                <td className="px-3 py-2 font-mono font-semibold text-pink-600">{r.id}</td>')
rql.append('                <td className="px-3 py-2"><ReasonBadge reason={r.reason} /></td>')
rql.append('                <td className="px-3 py-2"><StatusBadge status={r.status} /></td>')
rql.append('                <td className="px-3 py-2"><TestBadge type={r.testType} /></td>')
rql.append('                <td className="px-3 py-2"><SeverityBadge sev={r.severity} /></td>')
rql.append('                <td className="px-3 py-2 text-gray-600 dark:text-gray-400">{r.warehouse}</td>')
rql.append('                <td className="px-3 py-2"><ScoreBar value={r.score} /></td>')
rql.append('                <td className="px-3 py-2">{r.defects > 0 ? <span className="rql-defect-count inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-bold bg-red-100 text-red-700">{r.defects}</span> : <span className="text-gray-400">0</span>}</td>')
rql.append('                <td className="px-3 py-2 text-gray-600">{r.turnaround}h</td>')
rql.append('                <td className="px-3 py-2 font-semibold">&#8377;{r.value.toLocaleString()}</td>')
rql.append('              </tr>')
rql.append('            ))}')
rql.append('          </tbody></table></div></CardContent></Card>')
rql.append('        </TabsContent>')
rql.append('        <TabsContent value="analytics">')
rql.append('          <ModuleBreadcrumb items={[{ label: "Quality Lab" }, { label: "Analytics" }]} />')
rql.append('          <div className="grid grid-cols-4 gap-4 mb-4">')
rql.append('            <ValueTile label="Refurbished" value={String(returns.filter(r => r.returnRoute === "refurbish").length)} color={TH.pri} />')
rql.append('            <ValueTile label="Recycled" value={String(returns.filter(r => r.returnRoute === "recycle").length)} color={TH.ok} />')
rql.append('            <ValueTile label="Avg Turnaround" value={Math.round(returns.reduce((s, r) => s + r.turnaround, 0) / totalReturns) + "h"} color={TH.sec} />')
rql.append('            <ValueTile label="Quarantined" value={String(returns.filter(r => r.status === "quarantine").length)} color={TH.ter} />')
rql.append('          </div>')
rql.append('          <div className="grid grid-cols-2 gap-4">')
rql.append('            <Card className="rql-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Return Reason Distribution</CardTitle></CardHeader><CardContent><PieChart><Pie data={reasonDist} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({ name, percent }) => name + " " + (percent * 100).toFixed(0) + "%"} labelLine={false}><Cell fill={PC[0]} /><Cell fill={PC[1]} /><Cell fill={PC[2]} /><Cell fill={PC[3]} /><Cell fill={PC[4]} /><Cell fill={PC[5]} /><Cell fill={PC[6]} /><Cell fill={PC[7]} /></Pie><Tooltip /></PieChart></CardContent></Card>')
rql.append('            <Card className="rql-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Avg Turnaround (hours)</CardTitle></CardHeader><CardContent><BarChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey="turnaround" fill={TH.pri} radius={[4, 4, 0, 0]} /></BarChart></CardContent></Card>')
rql.append('          </div>')
rql.append('        </TabsContent>')
rql.append('        <TabsContent value="insights">')
rql.append('          <ModuleBreadcrumb items={[{ label: "Quality Lab" }, { label: "Insights" }]} />')
rql.append('          <div className="grid grid-cols-2 gap-4">')
rql.append('            <Card className="rql-insight-card border-l-4 border-l-pink-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><Microscope className="w-4 h-4 text-pink-600" /><span className="font-semibold text-sm">Defective Rate Spike</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Defective returns from Delhi DC-2 increased 22% in July. Root cause traced to batch ENG-7821 from supplier Apex Electronics. Initiate supplier corrective action request immediately.</p></CardContent></Card>')
rql.append('            <Card className="rql-insight-card border-l-4 border-l-violet-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><TestTubes className="w-4 h-4 text-violet-600" /><span className="font-semibold text-sm">Testing Automation</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Automated functional testing reduced inspection time by 35% for electronics returns. Expand to home appliances category to achieve projected 25% throughput improvement.</p></CardContent></Card>')
rql.append('            <Card className="rql-insight-card border-l-4 border-l-emerald-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><ThumbsUp className="w-4 h-4 text-emerald-600" /><span className="font-semibold text-sm">Refurbishment Success</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Items routed to refurbishment have 87% resale success rate, recovering average 62% of original value. Prioritize cosmetic and minor defect items for refurbishment pipeline.</p></CardContent></Card>')
rql.append('            <Card className="rql-insight-card border-l-4 border-l-amber-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><AlertTriangle className="w-4 h-4 text-amber-600" /><span className="font-semibold text-sm">Recall Alert</span></div><p className="text-xs text-gray-600 dark:text-gray-400">3 items flagged under recall protocol this month. Ensure quarantine hold times are extended from 24h to 72h for all recall-related returns pending manufacturer investigation.</p></CardContent></Card>')
rql.append('          </div>')
rql.append('        </TabsContent>')
rql.append('      </Tabs>')
rql.append('    </div>')
rql.append('  )')
rql.append('}')
rql.append('')

# ──────────────────────────────────────────────────────────────
# MODULE 2: Port Operations Hub (poh-*)
# ──────────────────────────────────────────────────────────────
poh = []
poh.append('"use client"')
poh.append('import { useState, useMemo } from "react"')
poh.append('import { AreaChart, Area, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts"')
poh.append('import { BarChart3, TrendingUp, TrendingDown, MapPin, Package, Timer, ArrowUpDown, Anchor, AlertTriangle, CheckCircle2, Route, Activity, Clock, DollarSign, ShieldCheck, ShieldAlert, Ship, Container, Truck, TrainFront, Waves, ClipboardCheck, Users } from "lucide-react"')
poh.append('import { PageHeader } from "@/components/shared/page-header"')
poh.append('import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar"')
poh.append('import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb"')
poh.append('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
poh.append('import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"')
poh.append('import { Badge } from "@/components/ui/badge"')
poh.append('')
poh.append('const CARGO_TYPES = ["fcl", "lcl", "break_bulk", "roll_on_roll", "project_cargo", "bulk_liquid", "bulk_dry", "reefer"] as const')
poh.append('const VESSEL_STATUS = ["berthed", "arriving", "departed", "at_anchor", "loading", "discharging", "waiting"] as const')
poh.append('const PORTS = ["Nhava Sheva JNPT", "Mundra", "Chennai", "Kandla", "Kolkata Haldia", "Tuticorin V.O.C", "Cochin", "Ennore Kamarajar"] as const')
poh.append('const TERMINALS = ["CT-1", "CT-2", "CT-3", "BOT-1", "BOT-2", "LCT-1", "OCT-1", "OCT-2"] as const')
poh.append('const OPERATIONS = ["import", "export", "transshipment", "coastal"] as const')
poh.append('const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] as const')
poh.append('const TH = { pri: "#0ea5e9", sec: "#f59e0b", ter: "#059669", ok: "#059669", warn: "#d97706", err: "#dc2626" }')
poh.append('const PC = ["#0ea5e9", "#f59e0b", "#059669", "#dc2626", "#8b5cf6", "#ec4899", "#14b8a6", "#f97316"]')
poh.append('')
poh.append('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297) * 233280; return x - Math.floor(x) }')
poh.append('function ri(min: number, max: number, seed: number): number { return Math.floor(seededRandom(seed) * (max - min + 1)) + min }')
poh.append('function pick<T>(arr: readonly T[], seed: number): T { return arr[Math.floor(seededRandom(seed) * arr.length)] }')
poh.append('')
poh.append('function CargoBadge({ type }: { type: string }) {')
poh.append('  const cols: Record<string, string> = { fcl: "bg-sky-100 text-sky-700 dark:bg-sky-900/30", lcl: "bg-blue-100 text-blue-700 dark:bg-blue-900/30", break_bulk: "bg-amber-100 text-amber-700 dark:bg-amber-900/30", roll_on_roll: "bg-violet-100 text-violet-700 dark:bg-violet-900/30", project_cargo: "poh-project bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30", bulk_liquid: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30", bulk_dry: "bg-orange-100 text-orange-700 dark:bg-orange-900/30", reefer: "poh-reefer bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30" }')
poh.append('  return <span className={"poh-cargo-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[type] || "bg-gray-100 text-gray-700")}>{type.replace(/_/g, " ")}</span>')
poh.append('}')
poh.append('')
poh.append('function StatusBadge({ status }: { status: string }) {')
poh.append('  const cols: Record<string, string> = { berthed: "poh-berthed bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 shadow-[0_0_6px_rgba(5,150,105,0.3)]", arriving: "poh-arriving bg-blue-100 text-blue-700 dark:bg-blue-900/30 shadow-[0_0_6px_rgba(59,130,246,0.3)]", departed: "bg-gray-200 text-gray-600 dark:bg-gray-700", at_anchor: "poh-at-anchor bg-amber-100 text-amber-700 dark:bg-amber-900/30", loading: "poh-loading bg-violet-100 text-violet-700 dark:bg-violet-900/30 shadow-[0_0_6px_rgba(139,92,246,0.3)]", discharging: "poh-discharging bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30 shadow-[0_0_6px_rgba(6,182,212,0.3)]", waiting: "poh-waiting bg-orange-100 text-orange-700 dark:bg-orange-900/30" }')
poh.append('  return <span className={"poh-status-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[status] || "")}>{status.replace(/_/g, " ")}</span>')
poh.append('}')
poh.append('')
poh.append('function OperationBadge({ op }: { op: string }) {')
poh.append('  const cols: Record<string, string> = { import: "bg-emerald-100 text-emerald-700", export: "bg-sky-100 text-sky-700", transshipment: "bg-violet-100 text-violet-700", coastal: "bg-amber-100 text-amber-700" }')
poh.append('  return <span className={"poh-op-badge inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-bold " + (cols[op] || "bg-gray-100 text-gray-600")}>{op}</span>')
poh.append('}')
poh.append('')
poh.append('function UtilBar({ value }: { value: number }) {')
poh.append('  const col = value >= 95 ? TH.err : value >= 80 ? TH.warn : TH.ok')
poh.append('  return <div className="poh-util-bar flex items-center gap-1.5"><div className="w-16 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: value + "%", backgroundColor: col }}/></div><span className="text-[10px] font-bold" style={{ color: col }}>{value}%</span></div>')
poh.append('}')
poh.append('')
poh.append('function TonnageBar({ value }: { value: number }) {')
poh.append('  const col = value >= 8000 ? TH.err : value >= 5000 ? TH.warn : TH.ok')
poh.append('  return <div className="poh-tonnage-bar flex items-center gap-1.5"><div className="w-14 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: Math.min(value / 10000 * 100, 100) + "%", backgroundColor: col }}/></div><span className="text-[10px] font-semibold" style={{ color: col }}>{(value / 1000).toFixed(1)}K</span></div>')
poh.append('}')
poh.append('')
poh.append('function HealthRing({ pct, label, color }: { pct: number; label: string; color: string }) {')
poh.append('  const r = 28, c = 2 * Math.PI * r, off = c - (pct / 100) * c')
poh.append('  return <div className="poh-health-ring flex flex-col items-center"><svg width="68" height="68" viewBox="0 0 68 68"><circle cx="34" cy="34" r={r} fill="none" stroke="#e5e7eb" strokeWidth="6"/><circle cx="34" cy="34" r={r} fill="none" stroke={color} strokeWidth="6" strokeDasharray={c} strokeDashoffset={off} strokeLinecap="round" transform="rotate(-90 34 34)" className="transition-all duration-700"/><text x="34" y="38" textAnchor="middle" className="text-[11px] font-bold" fill={color}>{pct}%</text></svg><span className="text-[9px] text-gray-500 mt-0.5">{label}</span></div>')
poh.append('}')
poh.append('')
poh.append('function KpiTile({ label, value, change, icon: Icon }: { label: string; value: string; change: number; icon: React.ComponentType<{ className?: string }> }) {')
poh.append('  return <div className="poh-kpi-tile bg-white dark:bg-gray-800 rounded-xl p-4 border border-gray-200 dark:border-gray-700 shadow-sm hover:shadow-md transition-shadow"><div className="flex items-center justify-between mb-2"><span className="text-[11px] font-medium text-gray-500">{label}</span><Icon className="w-4 h-4 text-sky-500"/></div><div className="text-xl font-bold text-gray-900 dark:text-gray-100">{value}</div><div className={"flex items-center gap-1 mt-1 text-[10px] font-semibold " + (change >= 0 ? "text-emerald-600" : "text-red-500")}><span>{change >= 0 ? "+" : ""}{change}%</span></div></div>')
poh.append('}')
poh.append('')
poh.append('function ValueTile({ label, value, color }: { label: string; value: string; color: string }) {')
poh.append('  return <div className="poh-value-tile bg-white dark:bg-gray-800 rounded-lg p-3 border border-gray-200 dark:border-gray-700"><div className="text-[10px] text-gray-500 mb-1">{label}</div><div className="text-lg font-bold" style={{ color }}>{value}</div></div>')
poh.append('}')
poh.append('')
poh.append('const vessels = Array.from({ length: 60 }, (_, i) => {')
poh.append('  const seed = i * 239 + 71')
poh.append('  return {')
poh.append('    id: "POH-" + String(i + 4001).padStart(4, "0"), vesselName: pick(["MSC Aurora", "CMA Marco Polo", "Maersk Elba", "Evergreen Hero", "Cosco Fortune", "Yang Ming Unity", "Hapag Express", "ONE Harmony", "PIL Venture", "SCI Vigilance"], seed),')
poh.append('    status: pick(VESSEL_STATUS, seed + 1), cargoType: pick(CARGO_TYPES, seed + 2),')
poh.append('    port: pick(PORTS, seed + 3), terminal: pick(TERMINALS, seed + 4), operation: pick(OPERATIONS, seed + 5),')
poh.append('    teu: ri(100, 8000, seed + 6), tonnage: ri(500, 10000, seed + 7),')
poh.append('    berthUtil: ri(40, 100, seed + 8), dwellTime: ri(4, 96, seed + 9),')
poh.append('    containers: ri(10, 500, seed + 10), craneMoves: ri(20, 200, seed + 11),')
poh.append('    eta: MO[ri(0, 11, seed + 12)] + " " + ri(1, 28, seed + 13),')
poh.append('    draft: (ri(80, 160, seed + 14) / 10).toFixed(1)')
poh.append('  }')
poh.append('})')
poh.append('')
poh.append('const monthlyData = MO.map((m, i) => ({ month: m, vessels: ri(80, 200, i * 23 + 1), teu: ri(30000, 80000, i * 23 + 2), berth: ri(70, 95, i * 23 + 3), dwell: ri(12, 36, i * 23 + 4) }))')
poh.append('const cargoDist = CARGO_TYPES.map((c, i) => ({ name: c.replace(/_/g, " "), value: ri(5, 20, i * 53) }))')
poh.append('')
poh.append('export default function PortOperationsHubView() {')
poh.append('  const [tab, setTab] = useState("dashboard")')
poh.append('  const [searchQuery, setSearchQuery] = useState("")')
poh.append('  const [activeFilters, setActiveFilters] = useState<Record<string, string[]>>({})')
poh.append('')
poh.append('  const filteredVessels = useMemo(() => {')
poh.append('    return vessels.filter(v => {')
poh.append('      if (searchQuery && !v.id.toLowerCase().includes(searchQuery.toLowerCase()) && !v.vesselName.toLowerCase().includes(searchQuery.toLowerCase()) && !v.port.toLowerCase().includes(searchQuery.toLowerCase())) return false')
poh.append('      if (activeFilters["cargo"] && !activeFilters["cargo"].includes(v.cargoType)) return false')
poh.append('      if (activeFilters["status"] && !activeFilters["status"].includes(v.status)) return false')
poh.append('      if (activeFilters["operation"] && !activeFilters["operation"].includes(v.operation)) return false')
poh.append('      return true')
poh.append('    })')
poh.append('  }, [searchQuery, activeFilters])')
poh.append('')
poh.append('  const filterGroups = [')
poh.append('    { key: "cargo", label: "Cargo", options: CARGO_TYPES.map(c => ({ value: c, label: c.replace(/_/g, " "), count: 0 })) },')
poh.append('    { key: "status", label: "Status", options: VESSEL_STATUS.map(s => ({ value: s, label: s.replace(/_/g, " "), count: 0 })) },')
poh.append('    { key: "operation", label: "Operation", options: OPERATIONS.map(o => ({ value: o, label: o, count: 0 })) }')
poh.append('  ]')
poh.append('')
poh.append('  const totalVessels = vessels.length')
poh.append('  const avgBerthUtil = Math.round(vessels.reduce((s, v) => s + v.berthUtil, 0) / totalVessels)')
poh.append('  const totalTeu = vessels.reduce((s, v) => s + v.teu, 0)')
poh.append('  const waitingCount = vessels.filter(v => v.status === "waiting" || v.status === "at_anchor").length')
poh.append('')
poh.append('  return (')
poh.append('    <div className="space-y-4">')
poh.append('      <PageHeader title="Port Operations Hub" description="Real-time vessel tracking, berth management and cargo throughput monitoring" />')
poh.append('      <Tabs value={tab} onValueChange={setTab}>')
poh.append('        <TabsList className="poh-tabs-list">')
poh.append('          <TabsTrigger value="dashboard">Dashboard</TabsTrigger>')
poh.append('          <TabsTrigger value="vessels">Vessels</TabsTrigger>')
poh.append('          <TabsTrigger value="cargo">Cargo</TabsTrigger>')
poh.append('          <TabsTrigger value="insights">Insights</TabsTrigger>')
poh.append('        </TabsList>')
poh.append('        <TabsContent value="dashboard">')
poh.append('          <div className="grid grid-cols-4 gap-4 mb-4">')
poh.append('            <KpiTile label="Active Vessels" value={String(totalVessels)} change={7} icon={Anchor} />')
poh.append('            <KpiTile label="Berth Utilisation" value={avgBerthUtil + "%"} change={3} icon={Activity} />')
poh.append('            <KpiTile label="Total TEU" value={(totalTeu / 1000).toFixed(0) + "K"} change={11} icon={Container} />')
poh.append('            <KpiTile label="Waiting/Anchored" value={String(waitingCount)} change={-15} icon={ShieldAlert} />')
poh.append('          </div>')
poh.append('          <div className="flex gap-6 mb-4 justify-center flex-wrap">')
poh.append('            <HealthRing pct={avgBerthUtil} label="Berth Util" color={TH.ok} />')
poh.append('            <HealthRing pct={89} label="Throughput" color={TH.pri} />')
poh.append('            <HealthRing pct={82} label="On-Time" color={TH.sec} />')
poh.append('            <HealthRing pct={94} label="Safety" color={TH.ok} />')
poh.append('            <HealthRing pct={71} label="Automation" color={TH.ter} />')
poh.append('            <HealthRing pct={88} label="Env Score" color={TH.pri} />')
poh.append('          </div>')
poh.append('          <div className="grid grid-cols-3 gap-4">')
poh.append('            <Card className="poh-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Vessel Traffic</CardTitle></CardHeader><CardContent><LineChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Line type="monotone" dataKey="vessels" stroke={TH.pri} strokeWidth={2} /></LineChart></CardContent></Card>')
poh.append('            <Card className="poh-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">TEU Volume</CardTitle></CardHeader><CardContent><BarChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey="teu" fill={TH.sec} radius={[4, 4, 0, 0]} /></BarChart></CardContent></Card>')
poh.append('            <Card className="poh-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Dwell Time Trend</CardTitle></CardHeader><CardContent><AreaChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Area type="monotone" dataKey="dwell" stroke={TH.ter} fill="rgba(5,150,105,0.15)" strokeWidth={2} /></AreaChart></CardContent></Card>')
poh.append('          </div>')
poh.append('        </TabsContent>')
poh.append('        <TabsContent value="vessels">')
poh.append('          <ModuleBreadcrumb items={[{ label: "Port Ops" }, { label: "All Vessels" }]} />')
poh.append('          <SearchFilterToolbar searchQuery={searchQuery} onSearchChange={setSearchQuery} onClearSearch={() => setSearchQuery("")} activeFilters={activeFilters} filterGroups={filterGroups} onToggleFilter={(k, v) => setActiveFilters(p => { const arr = p[k] || []; return arr.includes(v) ? (function(){ const n = {...p}; n[k] = arr.filter(x => x !== v); if(n[k].length === 0) delete n[k]; return n })() : {...p, [k]: [...arr, v]} })} onClearAllFilters={() => setActiveFilters({})} totalItems={totalVessels} filteredCount={filteredVessels.length} onRefresh={() => {}} placeholder="Search by ID, vessel name, or port..." />')
poh.append('          <Card className="poh-table-card"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50"><th className="px-3 py-2 text-left font-semibold">ID</th><th className="px-3 py-2 text-left font-semibold">Vessel</th><th className="px-3 py-2 text-left font-semibold">Status</th><th className="px-3 py-2 text-left font-semibold">Cargo</th><th className="px-3 py-2 text-left font-semibold">Port</th><th className="px-3 py-2 text-left font-semibold">TEU</th><th className="px-3 py-2 text-left font-semibold">Berth Util</th><th className="px-3 py-2 text-left font-semibold">Tonnage</th><th className="px-3 py-2 text-left font-semibold">Dwell</th><th className="px-3 py-2 text-left font-semibold">Op</th></tr></thead><tbody>')
poh.append('            {filteredVessels.slice(0, 30).map((v) => (')
poh.append('              <tr key={v.id} className="poh-table-row border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800/30 transition-colors">')
poh.append('                <td className="px-3 py-2 font-mono font-semibold text-sky-600">{v.id}</td>')
poh.append('                <td className="px-3 py-2 text-gray-700 dark:text-gray-300">{v.vesselName}</td>')
poh.append('                <td className="px-3 py-2"><StatusBadge status={v.status} /></td>')
poh.append('                <td className="px-3 py-2"><CargoBadge type={v.cargoType} /></td>')
poh.append('                <td className="px-3 py-2 text-gray-600 dark:text-gray-400">{v.port}</td>')
poh.append('                <td className="px-3 py-2 font-semibold">{v.teu.toLocaleString()}</td>')
poh.append('                <td className="px-3 py-2"><UtilBar value={v.berthUtil} /></td>')
poh.append('                <td className="px-3 py-2"><TonnageBar value={v.tonnage} /></td>')
poh.append('                <td className="px-3 py-2 text-gray-600">{v.dwellTime}h</td>')
poh.append('                <td className="px-3 py-2"><OperationBadge op={v.operation} /></td>')
poh.append('              </tr>')
poh.append('            ))}')
poh.append('          </tbody></table></div></CardContent></Card>')
poh.append('        </TabsContent>')
poh.append('        <TabsContent value="cargo">')
poh.append('          <ModuleBreadcrumb items={[{ label: "Port Ops" }, { label: "Cargo Analysis" }]} />')
poh.append('          <div className="grid grid-cols-4 gap-4 mb-4">')
poh.append('            <ValueTile label="FCL Containers" value={String(vessels.filter(v => v.cargoType === "fcl").length)} color={TH.pri} />')
poh.append('            <ValueTile label="Reefer Units" value={String(vessels.filter(v => v.cargoType === "reefer").length)} color={TH.ok} />')
poh.append('            <ValueTile label="Avg Dwell Time" value={Math.round(vessels.reduce((s, v) => s + v.dwellTime, 0) / totalVessels) + "h"} color={TH.sec} />')
poh.append('            <ValueTile label="Crane Moves" value={vessels.reduce((s, v) => s + v.craneMoves, 0).toLocaleString()} color={TH.ter} />')
poh.append('          </div>')
poh.append('          <div className="grid grid-cols-2 gap-4">')
poh.append('            <Card className="poh-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Cargo Type Mix</CardTitle></CardHeader><CardContent><PieChart><Pie data={cargoDist} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({ name, percent }) => name + " " + (percent * 100).toFixed(0) + "%"} labelLine={false}><Cell fill={PC[0]} /><Cell fill={PC[1]} /><Cell fill={PC[2]} /><Cell fill={PC[3]} /><Cell fill={PC[4]} /><Cell fill={PC[5]} /><Cell fill={PC[6]} /><Cell fill={PC[7]} /></Pie><Tooltip /></PieChart></CardContent></Card>')
poh.append('            <Card className="poh-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Berth Utilisation Trend</CardTitle></CardHeader><CardContent><BarChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey="berth" fill={TH.pri} radius={[4, 4, 0, 0]} /></BarChart></CardContent></Card>')
poh.append('          </div>')
poh.append('        </TabsContent>')
poh.append('        <TabsContent value="insights">')
poh.append('          <ModuleBreadcrumb items={[{ label: "Port Ops" }, { label: "Insights" }]} />')
poh.append('          <div className="grid grid-cols-2 gap-4">')
poh.append('            <Card className="poh-insight-card border-l-4 border-l-sky-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><Anchor className="w-4 h-4 text-sky-600" /><span className="font-semibold text-sm">Nhava Sheva Congestion</span></div><p className="text-xs text-gray-600 dark:text-gray-400">JNPT CT-1 berth occupancy at 96% causing 8-hour average wait for arriving vessels. Pre-berthing allocation optimization could reduce dwell time by 20% and save 500 crane moves daily.</p></CardContent></Card>')
poh.append('            <Card className="poh-insight-card border-l-4 border-l-amber-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><Waves className="w-4 h-4 text-amber-600" /><span className="font-semibold text-sm">Monsoon Impact</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Mumbai port operations expected 15% slowdown during July-August monsoon. Activate Tuticorin V.O.C as overflow hub for container traffic. Ensure reefer power backup across all terminals.</p></CardContent></Card>')
poh.append('            <Card className="poh-insight-card border-l-4 border-l-emerald-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><CheckCircle2 className="w-4 h-4 text-emerald-600" /><span className="font-semibold text-sm">Vessel Turnaround</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Average vessel turnaround time reduced to 18 hours (down from 26 hours in Q1). Streamlined documentation and dual crane deployment on CT-2 contributed to 30% improvement.</p></CardContent></Card>')
poh.append('            <Card className="poh-insight-card border-l-4 border-l-violet-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><Ship className="w-4 h-4 text-violet-600" /><span className="font-semibold text-sm">Coastal Shipping Growth</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Coastal cargo volume grew 24% YoY driven by RoRo services between Chennai and Kolkata. Consider adding Ennore Kamarajar terminal for dedicated coastal operations to meet projected demand.</p></CardContent></Card>')
poh.append('          </div>')
poh.append('        </TabsContent>')
poh.append('      </Tabs>')
poh.append('    </div>')
poh.append('  )')
poh.append('}')
poh.append('')

base = "/home/z/my-project/src/components/modules"
with open(os.path.join(base, "returns-quality-lab-view.tsx"), "w") as f:
    f.write("\n".join(rql))
with open(os.path.join(base, "port-operations-hub-view.tsx"), "w") as f:
    f.write("\n".join(poh))

print("Generated: returns-quality-lab-view.tsx")
print("Generated: port-operations-hub-view.tsx")
print(f"RQL lines: {len(rql)}")
print(f"POH lines: {len(poh)}")
