#!/usr/bin/env python3
"""Generate R268 modules: Smart Locker Fleet Management + Cold Chain Monitor Pro"""

import os

# ──────────────────────────────────────────────────────────────
# MODULE 1: Smart Locker Fleet Management (slf-*)
# ──────────────────────────────────────────────────────────────
slf = []
slf.append('"use client"')
slf.append('import { useState, useMemo } from "react"')
slf.append('import { AreaChart, Area, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts"')
slf.append('import { BarChart3, TrendingUp, TrendingDown, MapPin, Package, Timer, ArrowUpDown, Lock, Unlock, KeyRound, QrCode, Zap, AlertTriangle, CheckCircle2, Route, Activity, Thermometer, Users, Box, Wifi, Battery, Bell, ShieldCheck, Clock, DollarSign, Smartphone } from "lucide-react"')
slf.append('import { PageHeader } from "@/components/shared/page-header"')
slf.append('import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar"')
slf.append('import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb"')
slf.append('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
slf.append('import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"')
slf.append('import { Badge } from "@/components/ui/badge"')
slf.append('')
slf.append('const LOCKER_TYPES = ["standard", "large", "refrigerated", "climate_controlled", "oversized", "express", "premium"] as const')
slf.append('const LOCKER_STATUS = ["available", "occupied", "maintenance", "out_of_service", "reserved", "collecting"] as const')
slf.append('const LOCKER_SIZES = ["S", "M", "L", "XL", "XXL"] as const')
slf.append('const REGIONS = ["Mumbai Metro", "Delhi NCR", "Bangalore Urban", "Chennai Metro", "Hyderabad City", "Pune Region", "Kolkata Metro", "Ahmedabad Zone"] as const')
slf.append('const CITIES = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Hyderabad", "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Lucknow"] as const')
slf.append('const USAGE_BANDS = ["low", "medium", "high", "critical"] as const')
slf.append('const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] as const')
slf.append('const TH = { pri: "#8b5cf6", sec: "#06b6d4", ter: "#f59e0b", ok: "#059669", warn: "#d97706", err: "#dc2626" }')
slf.append('const PC = ["#8b5cf6", "#06b6d4", "#059669", "#f59e0b", "#dc2626", "#ec4899", "#14b8a6", "#3b82f6"]')
slf.append('')
slf.append('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297) * 233280; return x - Math.floor(x) }')
slf.append('function ri(min: number, max: number, seed: number): number { return Math.floor(seededRandom(seed) * (max - min + 1)) + min }')
slf.append('function pick<T>(arr: readonly T[], seed: number): T { return arr[Math.floor(seededRandom(seed) * arr.length)] }')
slf.append('')
slf.append('function LockerTypeBadge({ type }: { type: string }) {')
slf.append('  const cols: Record<string, string> = { standard: "bg-violet-100 text-violet-700 dark:bg-violet-900/30", large: "bg-blue-100 text-blue-700 dark:bg-blue-900/30", refrigerated: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30", climate_controlled: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30", oversized: "bg-amber-100 text-amber-700 dark:bg-amber-900/30", express: "bg-pink-100 text-pink-700 dark:bg-pink-900/30", premium: "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30" }')
slf.append('  return <span className={"slf-type-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[type] || "bg-gray-100 text-gray-700")}>{type.replace(/_/g, " ")}</span>')
slf.append('}')
slf.append('')
slf.append('function StatusBadge({ status }: { status: string }) {')
slf.append('  const cols: Record<string, string> = { available: "slf-available bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 shadow-[0_0_6px_rgba(5,150,105,0.3)]", occupied: "slf-occupied bg-blue-100 text-blue-700 dark:bg-blue-900/30 shadow-[0_0_6px_rgba(59,130,246,0.3)]", maintenance: "slf-maintenance bg-amber-100 text-amber-700 dark:bg-amber-900/30", out_of_service: "slf-out-of-service bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_6px_rgba(220,38,38,0.3)]", reserved: "bg-violet-100 text-violet-700 dark:bg-violet-900/30", collecting: "slf-collecting bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30 shadow-[0_0_6px_rgba(6,182,212,0.3)]" }')
slf.append('  return <span className={"slf-status-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[status] || "")}>{status.replace(/_/g, " ")}</span>')
slf.append('}')
slf.append('')
slf.append('function SizeBadge({ size }: { size: string }) {')
slf.append('  const cols: Record<string, string> = { S: "bg-gray-100 text-gray-600", M: "bg-blue-100 text-blue-700", L: "bg-violet-100 text-violet-700", XL: "bg-amber-100 text-amber-700", XXL: "bg-red-100 text-red-700" }')
slf.append('  return <span className={"slf-size-badge inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-bold " + (cols[size] || "")}>{size}</span>')
slf.append('}')
slf.append('')
slf.append('function UsageBadge({ band }: { band: string }) {')
slf.append('  const cols: Record<string, string> = { low: "bg-emerald-100 text-emerald-700", medium: "bg-blue-100 text-blue-700", high: "bg-amber-100 text-amber-700", critical: "slf-critical bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_8px_rgba(220,38,38,0.4)]" }')
slf.append('  return <span className={"slf-usage-badge inline-flex items-center px-1.5 py-0.5 rounded text-[9px] font-bold uppercase " + (cols[band] || "")}>{band}</span>')
slf.append('}')
slf.append('')
slf.append('function RegionBadge({ region }: { region: string }) {')
slf.append('  return <span className={"slf-region-badge inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-medium bg-gray-100 text-gray-600 dark:bg-gray-700"}><MapPin className="w-2.5 h-2.5"/>{region}</span>')
slf.append('}')
slf.append('')
slf.append('function UtilBar({ value }: { value: number }) {')
slf.append('  const col = value >= 90 ? TH.err : value >= 70 ? TH.warn : TH.ok')
slf.append('  return <div className="slf-util-bar flex items-center gap-1.5"><div className="w-16 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: value + "%", backgroundColor: col }}/></div><span className="text-[10px] font-bold" style={{ color: col }}>{value}%</span></div>')
slf.append('}')
slf.append('')
slf.append('function RevenueBar({ value }: { value: number }) {')
slf.append('  const col = value >= 5000 ? TH.ok : value >= 2000 ? TH.sec : TH.warn')
slf.append('  return <div className="slf-revenue-bar flex items-center gap-1.5"><div className="w-14 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: Math.min(value / 8000 * 100, 100) + "%", backgroundColor: col }}/></div><span className="text-[10px] font-semibold" style={{ color: col }}>&#8377;{value.toLocaleString()}</span></div>')
slf.append('}')
slf.append('')
slf.append('function HealthRing({ pct, label, color }: { pct: number; label: string; color: string }) {')
slf.append('  const r = 28, c = 2 * Math.PI * r, off = c - (pct / 100) * c')
slf.append('  return <div className="slf-health-ring flex flex-col items-center"><svg width="68" height="68" viewBox="0 0 68 68"><circle cx="34" cy="34" r={r} fill="none" stroke="#e5e7eb" strokeWidth="6"/><circle cx="34" cy="34" r={r} fill="none" stroke={color} strokeWidth="6" strokeDasharray={c} strokeDashoffset={off} strokeLinecap="round" transform="rotate(-90 34 34)" className="transition-all duration-700"/><text x="34" y="38" textAnchor="middle" className="text-[11px] font-bold" fill={color}>{pct}%</text></svg><span className="text-[9px] text-gray-500 mt-0.5">{label}</span></div>')
slf.append('}')
slf.append('')
slf.append('function KpiTile({ label, value, change, icon: Icon }: { label: string; value: string; change: number; icon: React.ComponentType<{ className?: string }> }) {')
slf.append('  return <div className="slf-kpi-tile bg-white dark:bg-gray-800 rounded-xl p-4 border border-gray-200 dark:border-gray-700 shadow-sm hover:shadow-md transition-shadow"><div className="flex items-center justify-between mb-2"><span className="text-[11px] font-medium text-gray-500">{label}</span><Icon className="w-4 h-4 text-violet-500"/></div><div className="text-xl font-bold text-gray-900 dark:text-gray-100">{value}</div><div className={"flex items-center gap-1 mt-1 text-[10px] font-semibold " + (change >= 0 ? "text-emerald-600" : "text-red-500")}><span>{change >= 0 ? "+" : ""}{change}%</span></div></div>')
slf.append('}')
slf.append('')
slf.append('function ValueTile({ label, value, color }: { label: string; value: string; color: string }) {')
slf.append('  return <div className="slf-value-tile bg-white dark:bg-gray-800 rounded-lg p-3 border border-gray-200 dark:border-gray-700"><div className="text-[10px] text-gray-500 mb-1">{label}</div><div className="text-lg font-bold" style={{ color }}>{value}</div></div>')
slf.append('}')
slf.append('')
slf.append('const lockers = Array.from({ length: 60 }, (_, i) => {')
slf.append('  const seed = i * 137 + 42')
slf.append('  const status = pick(LOCKER_STATUS, seed)')
slf.append('  const usage = status === "available" ? 0 : ri(5, 98, seed + 1)')
slf.append('  const band = usage >= 90 ? "critical" : usage >= 70 ? "high" : usage >= 30 ? "medium" : "low"')
slf.append('  return {')
slf.append('    id: "SLF-" + String(i + 1001).padStart(4, "0"), type: pick(LOCKER_TYPES, seed + 2), status, size: pick(LOCKER_SIZES, seed + 3),')
slf.append('    city: pick(CITIES, seed + 4), region: pick(REGIONS, seed + 5), location: pick(["Metro Station", "Mall", "Apartment Lobby", "Office Park", "Airport", "Hospital", "University", "Railway Station"], seed + 6),')
slf.append('    usage, band, revenue: ri(500, 8500, seed + 7), parcels: ri(0, 120, seed + 8), battery: ri(15, 100, seed + 9),')
slf.append('    temp: ri(2, 35, seed + 10), humidity: ri(20, 95, seed + 11), lastService: MO[ri(0, 11, seed + 12)] + " " + ri(1, 28, seed + 13),')
slf.append('    uptime: ri(90, 100, seed + 14), collects: ri(0, 45, seed + 15)')
slf.append('  }')
slf.append('})')
slf.append('')
slf.append('const monthlyData = MO.map((m, i) => ({ month: m, revenue: ri(120, 280, i * 7 + 1), parcels: ri(800, 2200, i * 7 + 2), utilisation: ri(55, 95, i * 7 + 3), active: ri(45, 58, i * 7 + 4) }))')
slf.append('const typeDist = LOCKER_TYPES.map((t, i) => ({ name: t.replace(/_/g, " "), value: ri(8, 18, i * 31) }))')
slf.append('')
slf.append('export default function SmartLockerFleetView() {')
slf.append('  const [tab, setTab] = useState("dashboard")')
slf.append('  const [searchQuery, setSearchQuery] = useState("")')
slf.append('  const [activeFilters, setActiveFilters] = useState<Record<string, string>>({})')
slf.append('')
slf.append('  const filteredLockers = useMemo(() => {')
slf.append('    return lockers.filter(l => {')
slf.append('      if (searchQuery && !l.id.toLowerCase().includes(searchQuery.toLowerCase()) && !l.city.toLowerCase().includes(searchQuery.toLowerCase()) && !l.location.toLowerCase().includes(searchQuery.toLowerCase())) return false')
slf.append('      if (activeFilters["type"] && l.type !== activeFilters["type"]) return false')
slf.append('      if (activeFilters["status"] && l.status !== activeFilters["status"]) return false')
slf.append('      if (activeFilters["region"] && l.region !== activeFilters["region"]) return false')
slf.append('      return true')
slf.append('    })')
slf.append('  }, [searchQuery, activeFilters])')
slf.append('')
slf.append('  const filterGroups = [')
slf.append('    { key: "type", label: "Type", options: LOCKER_TYPES.map(t => ({ value: t, label: t.replace(/_/g, " ") })) },')
slf.append('    { key: "status", label: "Status", options: LOCKER_STATUS.map(s => ({ value: s, label: s.replace(/_/g, " ") })) },')
slf.append('    { key: "region", label: "Region", options: REGIONS.map(r => ({ value: r, label: r })) }')
slf.append('  ]')
slf.append('')
slf.append('  const totalLockers = lockers.length')
slf.append('  const totalRevenue = lockers.reduce((s, l) => s + l.revenue, 0)')
slf.append('  const avgUtil = Math.round(lockers.reduce((s, l) => s + l.usage, 0) / totalLockers)')
slf.append('  const totalParcels = lockers.reduce((s, l) => s + l.parcels, 0)')
slf.append('')
slf.append('  return (')
slf.append('    <div className="space-y-4">')
slf.append('      <PageHeader title="Smart Locker Fleet Management" description="Monitor and manage the smart locker network across India" />')
slf.append('      <Tabs value={tab} onValueChange={setTab}>')
slf.append('        <TabsList className="slf-tabs-list">')
slf.append('          <TabsTrigger value="dashboard">Dashboard</TabsTrigger>')
slf.append('          <TabsTrigger value="lockers">Lockers</TabsTrigger>')
slf.append('          <TabsTrigger value="analytics">Analytics</TabsTrigger>')
slf.append('          <TabsTrigger value="insights">Insights</TabsTrigger>')
slf.append('        </TabsList>')
slf.append('        <TabsContent value="dashboard">')
slf.append('          <div className="grid grid-cols-4 gap-4 mb-4">')
slf.append('            <KpiTile label="Total Lockers" value={String(totalLockers)} change={12} icon={Box} />')
slf.append('            <KpiTile label="Monthly Revenue" value={"&#8377;" + (totalRevenue / 1000).toFixed(1) + "K"} change={8} icon={DollarSign} />')
slf.append('            <KpiTile label="Avg Utilisation" value={avgUtil + "%"} change={5} icon={Activity} />')
slf.append('            <KpiTile label="Total Parcels" value={totalParcels.toLocaleString()} change={15} icon={Package} />')
slf.append('          </div>')
slf.append('          <div className="flex gap-6 mb-4 justify-center flex-wrap">')
slf.append('            <HealthRing pct={94} label="Network Uptime" color={TH.ok} />')
slf.append('            <HealthRing pct={72} label="Utilisation" color={TH.sec} />')
slf.append('            <HealthRing pct={88} label="Availability" color={TH.pri} />')
slf.append('            <HealthRing pct={96} label="Battery Health" color={TH.ok} />')
slf.append('            <HealthRing pct={85} label="Revenue Target" color={TH.sec} />')
slf.append('            <HealthRing pct={91} label="SLA Compliance" color={TH.ok} />')
slf.append('          </div>')
slf.append('          <div className="grid grid-cols-3 gap-4">')
slf.append('            <Card className="slf-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Revenue Trend</CardTitle></CardHeader><CardContent><LineChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Line type="monotone" dataKey="revenue" stroke={TH.pri} strokeWidth={2} /></LineChart></CardContent></Card>')
slf.append('            <Card className="slf-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Parcels Processed</CardTitle></CardHeader><CardContent><BarChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey="parcels" fill={TH.sec} radius={[4, 4, 0, 0]} /></BarChart></CardContent></Card>')
slf.append('            <Card className="slf-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Utilisation Rate</CardTitle></CardHeader><CardContent><AreaChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Area type="monotone" dataKey="utilisation" stroke={TH.ter} fill="rgba(245,158,11,0.15)" strokeWidth={2} /></AreaChart></CardContent></Card>')
slf.append('          </div>')
slf.append('        </TabsContent>')
slf.append('        <TabsContent value="lockers">')
slf.append('          <ModuleBreadcrumb items={[{ label: "Fleet Management" }, { label: "All Lockers" }]} />')
slf.append('          <SearchFilterToolbar searchQuery={searchQuery} onSearchChange={setSearchQuery} onClearSearch={() => setSearchQuery("")} activeFilters={activeFilters} filterGroups={filterGroups} onToggleFilter={(k, v) => setActiveFilters(p => p[k] === v ? (function(){ const n = {...p}; delete n[k]; return n })() : {...p, [k]: v})} onClearAllFilters={() => setActiveFilters({})} totalItems={totalLockers} filteredCount={filteredLockers.length} onRefresh={() => {}} placeholder="Search lockers by ID, city, or location..." />')
slf.append('          <Card className="slf-table-card"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50"><th className="px-3 py-2 text-left font-semibold">ID</th><th className="px-3 py-2 text-left font-semibold">Type</th><th className="px-3 py-2 text-left font-semibold">Status</th><th className="px-3 py-2 text-left font-semibold">Size</th><th className="px-3 py-2 text-left font-semibold">City</th><th className="px-3 py-2 text-left font-semibold">Location</th><th className="px-3 py-2 text-left font-semibold">Usage</th><th className="px-3 py-2 text-left font-semibold">Revenue</th><th className="px-3 py-2 text-left font-semibold">Battery</th><th className="px-3 py-2 text-left font-semibold">Parcels</th></tr></thead><tbody>')
slf.append('            {filteredLockers.slice(0, 30).map((l, i) => (')
slf.append('              <tr key={l.id} className="slf-table-row border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800/30 transition-colors">')
slf.append('                <td className="px-3 py-2 font-mono font-semibold text-violet-600">{l.id}</td>')
slf.append('                <td className="px-3 py-2"><LockerTypeBadge type={l.type} /></td>')
slf.append('                <td className="px-3 py-2"><StatusBadge status={l.status} /></td>')
slf.append('                <td className="px-3 py-2"><SizeBadge size={l.size} /></td>')
slf.append('                <td className="px-3 py-2 text-gray-700 dark:text-gray-300">{l.city}</td>')
slf.append('                <td className="px-3 py-2"><RegionBadge region={l.location} /></td>')
slf.append('                <td className="px-3 py-2"><UtilBar value={l.usage} /></td>')
slf.append('                <td className="px-3 py-2"><RevenueBar value={l.revenue} /></td>')
slf.append('                <td className="px-3 py-2"><div className="flex items-center gap-1"><Battery className="w-3 h-3"/><span className="text-[10px]">{l.battery}%</span></div></td>')
slf.append('                <td className="px-3 py-2 font-semibold">{l.parcels}</td>')
slf.append('              </tr>')
slf.append('            ))}')
slf.append('          </tbody></table></div></CardContent></Card>')
slf.append('        </TabsContent>')
slf.append('        <TabsContent value="analytics">')
slf.append('          <ModuleBreadcrumb items={[{ label: "Fleet Management" }, { label: "Analytics" }]} />')
slf.append('          <div className="grid grid-cols-4 gap-4 mb-4">')
slf.append('            <ValueTile label="Available Lockers" value={String(lockers.filter(l => l.status === "available").length)} color={TH.ok} />')
slf.append('            <ValueTile label="Occupied Lockers" value={String(lockers.filter(l => l.status === "occupied").length)} color={TH.pri} />')
slf.append('            <ValueTile label="Avg Revenue/Locker" value={"&#8377;" + Math.round(totalRevenue / totalLockers).toLocaleString()} color={TH.sec} />')
slf.append('            <ValueTile label="Pending Collections" value={String(lockers.reduce((s, l) => s + l.collects, 0))} color={TH.ter} />')
slf.append('          </div>')
slf.append('          <div className="grid grid-cols-2 gap-4">')
slf.append('            <Card className="slf-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Locker Type Distribution</CardTitle></CardHeader><CardContent><PieChart><Pie data={typeDist} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({ name, percent }) => name + " " + (percent * 100).toFixed(0) + "%"} labelLine={false}><Cell fill={PC[0]} /><Cell fill={PC[1]} /><Cell fill={PC[2]} /><Cell fill={PC[3]} /><Cell fill={PC[4]} /><Cell fill={PC[5]} /><Cell fill={PC[6]} /></Pie><Tooltip /></PieChart></CardContent></Card>')
slf.append('            <Card className="slf-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Monthly Active Lockers</CardTitle></CardHeader><CardContent><BarChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey="active" fill={TH.pri} radius={[4, 4, 0, 0]} /></BarChart></CardContent></Card>')
slf.append('          </div>')
slf.append('        </TabsContent>')
slf.append('        <TabsContent value="insights">')
slf.append('          <ModuleBreadcrumb items={[{ label: "Fleet Management" }, { label: "Insights" }]} />')
slf.append('          <div className="grid grid-cols-2 gap-4">')
slf.append('            <Card className="slf-insight-card border-l-4 border-l-violet-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><TrendingUp className="w-4 h-4 text-violet-600" /><span className="font-semibold text-sm">High Demand Zones</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Mumbai Metro and Delhi NCR show 85%+ utilisation. Consider deploying 15 additional lockers in these regions to reduce waitlist and improve customer satisfaction.</p></CardContent></Card>')
slf.append('            <Card className="slf-insight-card border-l-4 border-l-cyan-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><Zap className="w-4 h-4 text-cyan-600" /><span className="font-semibold text-sm">Battery Alert</span></div><p className="text-xs text-gray-600 dark:text-gray-400">8 lockers have battery below 25%. Schedule proactive maintenance visits to prevent downtime. SLF-1014, SLF-1017, SLF-1023 are top priority.</p></CardContent></Card>')
slf.append('            <Card className="slf-insight-card border-l-4 border-l-emerald-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><CheckCircle2 className="w-4 h-4 text-emerald-600" /><span className="font-semibold text-sm">Revenue Growth</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Monthly revenue increased 12% MoM. Premium and express locker categories are driving growth with 18% higher margins than standard units.</p></CardContent></Card>')
slf.append('            <Card className="slf-insight-card border-l-4 border-l-amber-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><AlertTriangle className="w-4 h-4 text-amber-600" /><span className="font-semibold text-sm">Maintenance Backlog</span></div><p className="text-xs text-gray-600 dark:text-gray-400">4 lockers in out-of-service status for over 72 hours. Escalate to field service team for immediate resolution to maintain SLA targets.</p></CardContent></Card>')
slf.append('          </div>')
slf.append('        </TabsContent>')
slf.append('      </Tabs>')
slf.append('    </div>')
slf.append('  )')
slf.append('}')
slf.append('')

# ──────────────────────────────────────────────────────────────
# MODULE 2: Cold Chain Monitor Pro (ccm-*)
# ──────────────────────────────────────────────────────────────
ccm = []
ccm.append('"use client"')
ccm.append('import { useState, useMemo } from "react"')
ccm.append('import { AreaChart, Area, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts"')
ccm.append('import { BarChart3, TrendingUp, TrendingDown, MapPin, Package, Timer, ArrowUpDown, Thermometer, Snowflake, AlertTriangle, CheckCircle2, Route, Activity, Truck, ShieldCheck, Clock, DollarSign, ThermometerSnowflake, ShieldAlert, CloudRain, Waves, FlaskConical, Fridge, PackageCheck } from "lucide-react"')
ccm.append('import { PageHeader } from "@/components/shared/page-header"')
ccm.append('import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar"')
ccm.append('import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb"')
ccm.append('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
ccm.append('import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"')
ccm.append('import { Badge } from "@/components/ui/badge"')
ccm.append('')
ccm.append('const PRODUCT_TYPES = ["pharmaceutical", "vaccine", "food_dairy", "frozen_meat", "seafood", "fresh_produce", "chemical", "biological"] as const')
ccm.append('const SHIPMENT_STATUS = ["in_transit", "at_hub", "delivered", "alert", "delayed", "quarantine"] as const')
ccm.append('const COLD_TYPES = ["chilled", "frozen", "ambient_controlled", "deep_frozen", "ultra_cold"] as const')
ccm.append('const REGIONS = ["Mumbai Metro", "Delhi NCR", "Bangalore Urban", "Chennai Metro", "Hyderabad City", "Pune Region", "Kolkata Metro", "Ahmedabad Zone"] as const')
ccm.append('const CITIES = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Hyderabad", "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Lucknow"] as const')
ccm.append('const TEMP_BANDS = ["optimal", "warning", "critical", "breach"] as const')
ccm.append('const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] as const')
ccm.append('const TH = { pri: "#06b6d4", sec: "#3b82f6", ter: "#059669", ok: "#059669", warn: "#d97706", err: "#dc2626" }')
ccm.append('const PC = ["#06b6d4", "#3b82f6", "#059669", "#f59e0b", "#dc2626", "#8b5cf6", "#ec4899", "#14b8a6"]')
ccm.append('')
ccm.append('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297) * 233280; return x - Math.floor(x) }')
ccm.append('function ri(min: number, max: number, seed: number): number { return Math.floor(seededRandom(seed) * (max - min + 1)) + min }')
ccm.append('function pick<T>(arr: readonly T[], seed: number): T { return arr[Math.floor(seededRandom(seed) * arr.length)] }')
ccm.append('')
ccm.append('function ProductBadge({ type }: { type: string }) {')
ccm.append('  const cols: Record<string, string> = { pharmaceutical: "bg-blue-100 text-blue-700 dark:bg-blue-900/30", vaccine: "bg-violet-100 text-violet-700 dark:bg-violet-900/30", food_dairy: "bg-amber-100 text-amber-700 dark:bg-amber-900/30", frozen_meat: "bg-red-100 text-red-700 dark:bg-red-900/30", seafood: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30", fresh_produce: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30", chemical: "bg-orange-100 text-orange-700 dark:bg-orange-900/30", biological: "bg-pink-100 text-pink-700 dark:bg-pink-900/30" }')
ccm.append('  return <span className={"ccm-product-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[type] || "bg-gray-100 text-gray-700")}>{type.replace(/_/g, " ")}</span>')
ccm.append('}')
ccm.append('')
ccm.append('function StatusBadge({ status }: { status: string }) {')
ccm.append('  const cols: Record<string, string> = { in_transit: "ccm-in-transit bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30 shadow-[0_0_6px_rgba(6,182,212,0.3)]", at_hub: "ccm-at-hub bg-blue-100 text-blue-700 dark:bg-blue-900/30 shadow-[0_0_6px_rgba(59,130,246,0.3)]", delivered: "ccm-delivered bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 shadow-[0_0_6px_rgba(5,150,105,0.3)]", alert: "ccm-alert bg-amber-100 text-amber-700 dark:bg-amber-900/30 shadow-[0_0_6px_rgba(217,119,6,0.3)]", delayed: "ccm-delayed bg-orange-100 text-orange-700 dark:bg-orange-900/30", quarantine: "ccm-quarantine bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_6px_rgba(220,38,38,0.3)]" }')
ccm.append('  return <span className={"ccm-status-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[status] || "")}>{status.replace(/_/g, " ")}</span>')
ccm.append('}')
ccm.append('')
ccm.append('function ColdBadge({ type }: { type: string }) {')
ccm.append('  const cols: Record<string, string> = { chilled: "bg-blue-100 text-blue-700", frozen: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30", ambient_controlled: "bg-emerald-100 text-emerald-700", deep_frozen: "ccm-deep-frozen bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30", ultra_cold: "ccm-ultra-cold bg-violet-100 text-violet-700 dark:bg-violet-900/30" }')
ccm.append('  return <span className={"ccm-cold-badge inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-bold " + (cols[type] || "")}>{type.replace(/_/g, " ")}</span>')
ccm.append('}')
ccm.append('')
ccm.append('function TempBandBadge({ band }: { band: string }) {')
ccm.append('  const cols: Record<string, string> = { optimal: "bg-emerald-100 text-emerald-700", warning: "bg-amber-100 text-amber-700", critical: "bg-orange-100 text-orange-700 dark:bg-orange-900/30", breach: "ccm-breach bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_8px_rgba(220,38,38,0.4)]" }')
ccm.append('  return <span className={"ccm-temp-band-badge inline-flex items-center px-1.5 py-0.5 rounded text-[9px] font-bold uppercase " + (cols[band] || "")}>{band}</span>')
ccm.append('}')
ccm.append('')
ccm.append('function TempGauge({ current, min, max }: { current: number; min: number; max: number }) {')
ccm.append('  const range = max - min')
ccm.append('  const pct = Math.round(((current - min) / range) * 100)')
ccm.append('  const isOk = current >= min && current <= max')
ccm.append('  const col = isOk ? TH.ok : current < min ? "#3b82f6" : TH.err')
ccm.append('  return <div className="ccm-temp-gauge flex items-center gap-1.5"><Thermometer className="w-3 h-3" style={{ color: col }}/><span className={"text-[10px] font-bold " + (isOk ? "" : "text-red-600")}>{current}&deg;C</span><span className="text-[9px] text-gray-400">({min}&deg;-{max}&deg;C)</span></div>')
ccm.append('}')
ccm.append('')
ccm.append('function HumidityBar({ value }: { value: number }) {')
ccm.append('  const col = value <= 30 ? TH.err : value >= 80 ? TH.warn : TH.ok')
ccm.append('  return <div className="ccm-humidity-bar flex items-center gap-1.5"><div className="w-14 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: value + "%", backgroundColor: col }}/></div><span className="text-[10px] font-semibold" style={{ color: col }}>{value}%</span></div>')
ccm.append('}')
ccm.append('')
ccm.append('function HealthRing({ pct, label, color }: { pct: number; label: string; color: string }) {')
ccm.append('  const r = 28, c = 2 * Math.PI * r, off = c - (pct / 100) * c')
ccm.append('  return <div className="ccm-health-ring flex flex-col items-center"><svg width="68" height="68" viewBox="0 0 68 68"><circle cx="34" cy="34" r={r} fill="none" stroke="#e5e7eb" strokeWidth="6"/><circle cx="34" cy="34" r={r} fill="none" stroke={color} strokeWidth="6" strokeDasharray={c} strokeDashoffset={off} strokeLinecap="round" transform="rotate(-90 34 34)" className="transition-all duration-700"/><text x="34" y="38" textAnchor="middle" className="text-[11px] font-bold" fill={color}>{pct}%</text></svg><span className="text-[9px] text-gray-500 mt-0.5">{label}</span></div>')
ccm.append('}')
ccm.append('')
ccm.append('function KpiTile({ label, value, change, icon: Icon }: { label: string; value: string; change: number; icon: React.ComponentType<{ className?: string }> }) {')
ccm.append('  return <div className="ccm-kpi-tile bg-white dark:bg-gray-800 rounded-xl p-4 border border-gray-200 dark:border-gray-700 shadow-sm hover:shadow-md transition-shadow"><div className="flex items-center justify-between mb-2"><span className="text-[11px] font-medium text-gray-500">{label}</span><Icon className="w-4 h-4 text-cyan-500"/></div><div className="text-xl font-bold text-gray-900 dark:text-gray-100">{value}</div><div className={"flex items-center gap-1 mt-1 text-[10px] font-semibold " + (change >= 0 ? "text-emerald-600" : "text-red-500")}><span>{change >= 0 ? "+" : ""}{change}%</span></div></div>')
ccm.append('}')
ccm.append('')
ccm.append('function ValueTile({ label, value, color }: { label: string; value: string; color: string }) {')
ccm.append('  return <div className="ccm-value-tile bg-white dark:bg-gray-800 rounded-lg p-3 border border-gray-200 dark:border-gray-700"><div className="text-[10px] text-gray-500 mb-1">{label}</div><div className="text-lg font-bold" style={{ color }}>{value}</div></div>')
ccm.append('}')
ccm.append('')
ccm.append('const shipments = Array.from({ length: 55 }, (_, i) => {')
ccm.append('  const seed = i * 193 + 77')
ccm.append('  const product = pick(PRODUCT_TYPES, seed)')
ccm.append('  const coldType = pick(COLD_TYPES, seed + 1)')
ccm.append('  const tempRanges: Record<string, [number, number]> = { chilled: [2, 8], frozen: [-25, -15], ambient_controlled: [15, 25], deep_frozen: [-40, -20], ultra_cold: [-80, -60] }')
ccm.append('  const [tMin, tMax] = tempRanges[coldType]')
ccm.append('  const currentTemp = ri(tMin - 5, tMax + 8, seed + 2)')
ccm.append('  const deviation = currentTemp < tMin ? currentTemp - tMin : currentTemp > tMax ? currentTemp - tMax : 0')
ccm.append('  const band = Math.abs(deviation) === 0 ? "optimal" : Math.abs(deviation) <= 2 ? "warning" : Math.abs(deviation) <= 5 ? "critical" : "breach"')
ccm.append('  const status = band === "breach" ? "alert" : pick(SHIPMENT_STATUS, seed + 3)')
ccm.append('  return {')
ccm.append('    id: "CCM-" + String(i + 5001).padStart(4, "0"), product, status, coldType,')
ccm.append('    city: pick(CITIES, seed + 4), region: pick(REGIONS, seed + 5),')
ccm.append('    currentTemp, minTemp: tMin, maxTemp: tMax, band, deviation,')
ccm.append('    humidity: ri(25, 90, seed + 6), duration: ri(2, 72, seed + 7),')
ccm.append('    value: ri(50000, 500000, seed + 8), weight: ri(10, 5000, seed + 9),')
ccm.append('    sensorCount: ri(1, 6, seed + 10), alerts: band === "breach" ? ri(3, 15, seed + 11) : band === "critical" ? ri(1, 4, seed + 11) : 0')
ccm.append('  }')
ccm.append('})')
ccm.append('')
ccm.append('const monthlyData = MO.map((m, i) => ({ month: m, shipments: ri(180, 350, i * 11 + 1), breaches: ri(0, 8, i * 11 + 2), compliance: ri(92, 99, i * 11 + 3), cost: ri(200, 600, i * 11 + 4) }))')
ccm.append('const productDist = PRODUCT_TYPES.map((t, i) => ({ name: t.replace(/_/g, " "), value: ri(5, 20, i * 37) }))')
ccm.append('')
ccm.append('export default function ColdChainMonitorProView() {')
ccm.append('  const [tab, setTab] = useState("dashboard")')
ccm.append('  const [searchQuery, setSearchQuery] = useState("")')
ccm.append('  const [activeFilters, setActiveFilters] = useState<Record<string, string>>({})')
ccm.append('')
ccm.append('  const filteredShipments = useMemo(() => {')
ccm.append('    return shipments.filter(s => {')
ccm.append('      if (searchQuery && !s.id.toLowerCase().includes(searchQuery.toLowerCase()) && !s.city.toLowerCase().includes(searchQuery.toLowerCase()) && !s.product.toLowerCase().includes(searchQuery.toLowerCase())) return false')
ccm.append('      if (activeFilters["product"] && s.product !== activeFilters["product"]) return false')
ccm.append('      if (activeFilters["status"] && s.status !== activeFilters["status"]) return false')
ccm.append('      if (activeFilters["coldType"] && s.coldType !== activeFilters["coldType"]) return false')
ccm.append('      return true')
ccm.append('    })')
ccm.append('  }, [searchQuery, activeFilters])')
ccm.append('')
ccm.append('  const filterGroups = [')
ccm.append('    { key: "product", label: "Product", options: PRODUCT_TYPES.map(t => ({ value: t, label: t.replace(/_/g, " ") })) },')
ccm.append('    { key: "status", label: "Status", options: SHIPMENT_STATUS.map(s => ({ value: s, label: s.replace(/_/g, " ") })) },')
ccm.append('    { key: "coldType", label: "Cold Type", options: COLD_TYPES.map(c => ({ value: c, label: c.replace(/_/g, " ") })) }')
ccm.append('  ]')
ccm.append('')
ccm.append('  const totalShipments = shipments.length')
ccm.append('  const complianceRate = Math.round(shipments.filter(s => s.band === "optimal").length / totalShipments * 100)')
ccm.append('  const breachCount = shipments.filter(s => s.band === "breach").length')
ccm.append('  const totalValue = shipments.reduce((s, sh) => s + sh.value, 0)')
ccm.append('')
ccm.append('  return (')
ccm.append('    <div className="space-y-4">')
ccm.append('      <PageHeader title="Cold Chain Monitor Pro" description="End-to-end temperature compliance and cold chain visibility" />')
ccm.append('      <Tabs value={tab} onValueChange={setTab}>')
ccm.append('        <TabsList className="ccm-tabs-list">')
ccm.append('          <TabsTrigger value="dashboard">Dashboard</TabsTrigger>')
ccm.append('          <TabsTrigger value="shipments">Shipments</TabsTrigger>')
ccm.append('          <TabsTrigger value="compliance">Compliance</TabsTrigger>')
ccm.append('          <TabsTrigger value="insights">Insights</TabsTrigger>')
ccm.append('        </TabsList>')
ccm.append('        <TabsContent value="dashboard">')
ccm.append('          <div className="grid grid-cols-4 gap-4 mb-4">')
ccm.append('            <KpiTile label="Active Shipments" value={String(totalShipments)} change={6} icon={ThermometerSnowflake} />')
ccm.append('            <KpiTile label="Compliance Rate" value={complianceRate + "%"} change={3} icon={ShieldCheck} />')
ccm.append('            <KpiTile label="Total Value" value={"&#8377;" + (totalValue / 10000000).toFixed(1) + "Cr"} change={-2} icon={DollarSign} />')
ccm.append('            <KpiTile label="Temp Breaches" value={String(breachCount)} change={-15} icon={ShieldAlert} />')
ccm.append('          </div>')
ccm.append('          <div className="flex gap-6 mb-4 justify-center flex-wrap">')
ccm.append('            <HealthRing pct={complianceRate} label="Compliance" color={TH.ok} />')
ccm.append('            <HealthRing pct={96} label="Sensor Uptime" color={TH.pri} />')
ccm.append('            <HealthRing pct={89} label="On-Time Delivery" color={TH.sec} />')
ccm.append('            <HealthRing pct={97} label="Data Integrity" color={TH.ok} />')
ccm.append('            <HealthRing pct={84} label="Cost Efficiency" color={TH.ter} />')
ccm.append('            <HealthRing pct={92} label="Audit Score" color={TH.pri} />')
ccm.append('          </div>')
ccm.append('          <div className="grid grid-cols-3 gap-4">')
ccm.append('            <Card className="ccm-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Shipment Volume</CardTitle></CardHeader><CardContent><LineChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Line type="monotone" dataKey="shipments" stroke={TH.pri} strokeWidth={2} /></LineChart></CardContent></Card>')
ccm.append('            <Card className="ccm-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Temperature Breaches</CardTitle></CardHeader><CardContent><BarChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey="breaches" fill={TH.err} radius={[4, 4, 0, 0]} /></BarChart></CardContent></Card>')
ccm.append('            <Card className="ccm-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Compliance Trend</CardTitle></CardHeader><CardContent><AreaChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Area type="monotone" dataKey="compliance" stroke={TH.ok} fill="rgba(5,150,105,0.15)" strokeWidth={2} /></AreaChart></CardContent></Card>')
ccm.append('          </div>')
ccm.append('        </TabsContent>')
ccm.append('        <TabsContent value="shipments">')
ccm.append('          <ModuleBreadcrumb items={[{ label: "Cold Chain" }, { label: "All Shipments" }]} />')
ccm.append('          <SearchFilterToolbar searchQuery={searchQuery} onSearchChange={setSearchQuery} onClearSearch={() => setSearchQuery("")} activeFilters={activeFilters} filterGroups={filterGroups} onToggleFilter={(k, v) => setActiveFilters(p => p[k] === v ? (function(){ const n = {...p}; delete n[k]; return n })() : {...p, [k]: v})} onClearAllFilters={() => setActiveFilters({})} totalItems={totalShipments} filteredCount={filteredShipments.length} onRefresh={() => {}} placeholder="Search shipments by ID, city, or product..." />')
ccm.append('          <Card className="ccm-table-card"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50"><th className="px-3 py-2 text-left font-semibold">ID</th><th className="px-3 py-2 text-left font-semibold">Product</th><th className="px-3 py-2 text-left font-semibold">Status</th><th className="px-3 py-2 text-left font-semibold">Cold Type</th><th className="px-3 py-2 text-left font-semibold">City</th><th className="px-3 py-2 text-left font-semibold">Temp</th><th className="px-3 py-2 text-left font-semibold">Band</th><th className="px-3 py-2 text-left font-semibold">Humidity</th><th className="px-3 py-2 text-left font-semibold">Duration</th><th className="px-3 py-2 text-left font-semibold">Alerts</th></tr></thead><tbody>')
ccm.append('            {filteredShipments.slice(0, 30).map((s) => (')
ccm.append('              <tr key={s.id} className="ccm-table-row border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800/30 transition-colors">')
ccm.append('                <td className="px-3 py-2 font-mono font-semibold text-cyan-600">{s.id}</td>')
ccm.append('                <td className="px-3 py-2"><ProductBadge product={s.product} /></td>')
ccm.append('                <td className="px-3 py-2"><StatusBadge status={s.status} /></td>')
ccm.append('                <td className="px-3 py-2"><ColdBadge type={s.coldType} /></td>')
ccm.append('                <td className="px-3 py-2 text-gray-700 dark:text-gray-300">{s.city}</td>')
ccm.append('                <td className="px-3 py-2"><TempGauge current={s.currentTemp} min={s.minTemp} max={s.maxTemp} /></td>')
ccm.append('                <td className="px-3 py-2"><TempBandBadge band={s.band} /></td>')
ccm.append('                <td className="px-3 py-2"><HumidityBar value={s.humidity} /></td>')
ccm.append('                <td className="px-3 py-2 text-gray-600">{s.duration}h</td>')
ccm.append('                <td className="px-3 py-2">{s.alerts > 0 ? <span className="ccm-alert-count inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded text-[10px] font-bold bg-red-100 text-red-700"><ShieldAlert className="w-3 h-3"/>{s.alerts}</span> : <span className="text-gray-400">0</span>}</td>')
ccm.append('              </tr>')
ccm.append('            ))}')
ccm.append('          </tbody></table></div></CardContent></Card>')
ccm.append('        </TabsContent>')
ccm.append('        <TabsContent value="compliance">')
ccm.append('          <ModuleBreadcrumb items={[{ label: "Cold Chain" }, { label: "Compliance" }]} />')
ccm.append('          <div className="grid grid-cols-4 gap-4 mb-4">')
ccm.append('            <ValueTile label="Optimal Shipments" value={String(shipments.filter(s => s.band === "optimal").length)} color={TH.ok} />')
ccm.append('            <ValueTile label="Warning Shipments" value={String(shipments.filter(s => s.band === "warning").length)} color={TH.warn} />')
ccm.append('            <ValueTile label="Breach Incidents" value={String(breachCount)} color={TH.err} />')
ccm.append('            <ValueTile label="Avg Duration" value={Math.round(shipments.reduce((s, sh) => s + sh.duration, 0) / totalShipments) + "h"} color={TH.pri} />')
ccm.append('          </div>')
ccm.append('          <div className="grid grid-cols-2 gap-4">')
ccm.append('            <Card className="ccm-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Product Type Distribution</CardTitle></CardHeader><CardContent><PieChart><Pie data={productDist} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({ name, percent }) => name + " " + (percent * 100).toFixed(0) + "%"} labelLine={false}><Cell fill={PC[0]} /><Cell fill={PC[1]} /><Cell fill={PC[2]} /><Cell fill={PC[3]} /><Cell fill={PC[4]} /><Cell fill={PC[5]} /><Cell fill={PC[6]} /><Cell fill={PC[7]} /></Pie><Tooltip /></PieChart></CardContent></Card>')
ccm.append('            <Card className="ccm-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Monthly Cost (Lakh)</CardTitle></CardHeader><CardContent><BarChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey="cost" fill={TH.pri} radius={[4, 4, 0, 0]} /></BarChart></CardContent></Card>')
ccm.append('          </div>')
ccm.append('        </TabsContent>')
ccm.append('        <TabsContent value="insights">')
ccm.append('          <ModuleBreadcrumb items={[{ label: "Cold Chain" }, { label: "Insights" }]} />')
ccm.append('          <div className="grid grid-cols-2 gap-4">')
ccm.append('            <Card className="ccm-insight-card border-l-4 border-l-cyan-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><Thermometer className="w-4 h-4 text-cyan-600" /><span className="font-semibold text-sm">Vaccine Cold Chain Risk</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Ultra-cold vaccine shipments show 4% higher deviation rates during Mumbai-Chennai corridor. Pre-conditioning at origin hub recommended for improved stability.</p></CardContent></Card>')
ccm.append('            <Card className="ccm-insight-card border-l-4 border-l-red-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><AlertTriangle className="w-4 h-4 text-red-600" /><span className="font-semibold text-sm">Breach Hotspots</span></div><p className="text-xs text-gray-600 dark:text-gray-400">3 consecutive breaches detected on Delhi NCR frozen meat route. Root cause: door seal failure on reefer truck RF-204. Immediate inspection required.</p></CardContent></Card>')
ccm.append('            <Card className="ccm-insight-card border-l-4 border-l-emerald-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><CheckCircle2 className="w-4 h-4 text-emerald-600" /><span className="font-semibold text-sm">Sensor Network Growth</span></div><p className="text-xs text-gray-600 dark:text-gray-400">IoT sensor coverage reached 96% of active cold chain routes. Real-time monitoring resolution improved to 30-second intervals across all zones.</p></CardContent></Card>')
ccm.append('            <Card className="ccm-insight-card border-l-4 border-l-blue-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><Snowflake className="w-4 h-4 text-blue-600" /><span className="font-semibold text-sm">Seasonal Demand</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Fresh produce cold chain demand expected to increase 25% in August-September. Pre-position additional reefer capacity at Hyderabad and Chennai hubs.</p></CardContent></Card>')
ccm.append('          </div>')
ccm.append('        </TabsContent>')
ccm.append('      </Tabs>')
ccm.append('    </div>')
ccm.append('  )')
ccm.append('}')
ccm.append('')

# Write both files
base = "/home/z/my-project/src/components/modules"
with open(os.path.join(base, "smart-locker-fleet-view.tsx"), "w") as f:
    f.write("\n".join(slf))
with open(os.path.join(base, "cold-chain-monitor-pro-view.tsx"), "w") as f:
    f.write("\n".join(ccm))

print("Generated: smart-locker-fleet-view.tsx")
print("Generated: cold-chain-monitor-pro-view.tsx")
print(f"SLF lines: {len(slf)}")
print(f"CCM lines: {len(ccm)}")
