#!/usr/bin/env python3
"""Generate R269 modules: Cross-Border Logistics Hub + Warehouse Digital Floor Plan"""

import os

# ──────────────────────────────────────────────────────────────
# MODULE 1: Cross-Border Logistics Hub (cbl-*)
# ──────────────────────────────────────────────────────────────
cbl = []
cbl.append('"use client"')
cbl.append('import { useState, useMemo } from "react"')
cbl.append('import { AreaChart, Area, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts"')
cbl.append('import { BarChart3, TrendingUp, TrendingDown, MapPin, Package, Timer, ArrowUpDown, Globe, Plane, Ship, TrainFront, AlertTriangle, CheckCircle2, Route, Activity, Clock, DollarSign, ShieldCheck, ShieldAlert, FileCheck2, Languages, Fingerprint, Truck } from "lucide-react"')
cbl.append('import { PageHeader } from "@/components/shared/page-header"')
cbl.append('import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar"')
cbl.append('import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb"')
cbl.append('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
cbl.append('import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"')
cbl.append('import { Badge } from "@/components/ui/badge"')
cbl.append('')
cbl.append('const SHIPMENT_TYPES = ["export", "import", "transit", "re_export"] as const')
cbl.append('const CLEARANCE_STATUS = ["pending", "cleared", "held", "rejected", "in_review", "released"] as const')
cbl.append('const MODES = ["air", "sea", "land", "rail", "multimodal"] as const')
cbl.append('const COUNTRIES = ["China", "UAE", "USA", "UK", "Germany", "Singapore", "Japan", "South Korea", "Thailand", "Vietnam"] as const')
cbl.append('const GATEWAYS = ["Nhava Sheva", "JNPT", "Tuticorin", "Chennai Port", "IGI Delhi", "Mumbai Airport", "Bangalore Airport", "Kolkata Port"] as const')
cbl.append('const DOC_STATUS = ["complete", "incomplete", "expired", "pending_submission"] as const')
cbl.append('const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] as const')
cbl.append('const TH = { pri: "#0d9488", sec: "#6366f1", ter: "#ea580c", ok: "#059669", warn: "#d97706", err: "#dc2626" }')
cbl.append('const PC = ["#0d9488", "#6366f1", "#059669", "#ea580c", "#dc2626", "#8b5cf6", "#ec4899", "#14b8a6"]')
cbl.append('')
cbl.append('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297) * 233280; return x - Math.floor(x) }')
cbl.append('function ri(min: number, max: number, seed: number): number { return Math.floor(seededRandom(seed) * (max - min + 1)) + min }')
cbl.append('function pick<T>(arr: readonly T[], seed: number): T { return arr[Math.floor(seededRandom(seed) * arr.length)] }')
cbl.append('')
cbl.append('function ShipmentTypeBadge({ type }: { type: string }) {')
cbl.append('  const cols: Record<string, string> = { export: "bg-teal-100 text-teal-700 dark:bg-teal-900/30", import: "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30", transit: "bg-orange-100 text-orange-700 dark:bg-orange-900/30", re_export: "bg-violet-100 text-violet-700 dark:bg-violet-900/30" }')
cbl.append('  const icons: Record<string, string> = { export: "OUT", import: "IN", transit: "TR", re_export: "RE" }')
cbl.append('  return <span className={"cbl-type-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[type] || "bg-gray-100 text-gray-700")}>{icons[type] || type.replace(/_/g, " ")}</span>')
cbl.append('}')
cbl.append('')
cbl.append('function StatusBadge({ status }: { status: string }) {')
cbl.append('  const cols: Record<string, string> = { pending: "cbl-pending bg-amber-100 text-amber-700 dark:bg-amber-900/30 shadow-[0_0_6px_rgba(217,119,6,0.3)]", cleared: "cbl-cleared bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 shadow-[0_0_6px_rgba(5,150,105,0.3)]", held: "cbl-held bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_6px_rgba(220,38,38,0.3)]", rejected: "cbl-rejected bg-rose-100 text-rose-700 dark:bg-rose-900/30 shadow-[0_0_6px_rgba(244,63,94,0.3)]", in_review: "cbl-in-review bg-blue-100 text-blue-700 dark:bg-blue-900/30", released: "cbl-released bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30 shadow-[0_0_6px_rgba(6,182,212,0.3)]" }')
cbl.append('  return <span className={"cbl-status-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[status] || "")}>{status.replace(/_/g, " ")}</span>')
cbl.append('}')
cbl.append('')
cbl.append('function ModeBadge({ mode }: { mode: string }) {')
cbl.append('  const cols: Record<string, string> = { air: "bg-sky-100 text-sky-700", sea: "bg-blue-100 text-blue-700 dark:bg-blue-900/30", land: "bg-amber-100 text-amber-700", rail: "bg-violet-100 text-violet-700 dark:bg-violet-900/30", multimodal: "bg-teal-100 text-teal-700 dark:bg-teal-900/30" }')
cbl.append('  return <span className={"cbl-mode-badge inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-bold " + (cols[mode] || "bg-gray-100 text-gray-600")}>{mode}</span>')
cbl.append('}')
cbl.append('')
cbl.append('function CountryBadge({ country }: { country: string }) {')
cbl.append('  return <span className={"cbl-country-badge inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-medium bg-gray-100 text-gray-600 dark:bg-gray-700"}><Globe className="w-2.5 h-2.5"/>{country}</span>')
cbl.append('}')
cbl.append('')
cbl.append('function DocBadge({ status }: { status: string }) {')
cbl.append('  const cols: Record<string, string> = { complete: "bg-emerald-100 text-emerald-700", incomplete: "bg-amber-100 text-amber-700", expired: "cbl-expired bg-red-100 text-red-700 dark:bg-red-900/30", pending_submission: "bg-gray-100 text-gray-600" }')
cbl.append('  return <span className={"cbl-doc-badge inline-flex items-center px-1.5 py-0.5 rounded text-[9px] font-bold uppercase " + (cols[status] || "")}>{status.replace(/_/g, " ")}</span>')
cbl.append('}')
cbl.append('')
cbl.append('function DutyBar({ value, max }: { value: number; max: number }) {')
cbl.append('  const pct = Math.round((value / max) * 100); const col = pct >= 80 ? TH.err : pct >= 50 ? TH.warn : TH.ok')
cbl.append('  return <div className="cbl-duty-bar flex items-center gap-1.5"><div className="w-16 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: pct + "%", backgroundColor: col }}/></div><span className="text-[10px] font-semibold" style={{ color: col }}>&#8377;{value.toLocaleString()}</span></div>')
cbl.append('}')
cbl.append('')
cbl.append('function HealthRing({ pct, label, color }: { pct: number; label: string; color: string }) {')
cbl.append('  const r = 28, c = 2 * Math.PI * r, off = c - (pct / 100) * c')
cbl.append('  return <div className="cbl-health-ring flex flex-col items-center"><svg width="68" height="68" viewBox="0 0 68 68"><circle cx="34" cy="34" r={r} fill="none" stroke="#e5e7eb" strokeWidth="6"/><circle cx="34" cy="34" r={r} fill="none" stroke={color} strokeWidth="6" strokeDasharray={c} strokeDashoffset={off} strokeLinecap="round" transform="rotate(-90 34 34)" className="transition-all duration-700"/><text x="34" y="38" textAnchor="middle" className="text-[11px] font-bold" fill={color}>{pct}%</text></svg><span className="text-[9px] text-gray-500 mt-0.5">{label}</span></div>')
cbl.append('}')
cbl.append('')
cbl.append('function KpiTile({ label, value, change, icon: Icon }: { label: string; value: string; change: number; icon: React.ComponentType<{ className?: string }> }) {')
cbl.append('  return <div className="cbl-kpi-tile bg-white dark:bg-gray-800 rounded-xl p-4 border border-gray-200 dark:border-gray-700 shadow-sm hover:shadow-md transition-shadow"><div className="flex items-center justify-between mb-2"><span className="text-[11px] font-medium text-gray-500">{label}</span><Icon className="w-4 h-4 text-teal-500"/></div><div className="text-xl font-bold text-gray-900 dark:text-gray-100">{value}</div><div className={"flex items-center gap-1 mt-1 text-[10px] font-semibold " + (change >= 0 ? "text-emerald-600" : "text-red-500")}><span>{change >= 0 ? "+" : ""}{change}%</span></div></div>')
cbl.append('}')
cbl.append('')
cbl.append('function ValueTile({ label, value, color }: { label: string; value: string; color: string }) {')
cbl.append('  return <div className="cbl-value-tile bg-white dark:bg-gray-800 rounded-lg p-3 border border-gray-200 dark:border-gray-700"><div className="text-[10px] text-gray-500 mb-1">{label}</div><div className="text-lg font-bold" style={{ color }}>{value}</div></div>')
cbl.append('}')
cbl.append('')
cbl.append('const shipments = Array.from({ length: 50 }, (_, i) => {')
cbl.append('  const seed = i * 211 + 93')
cbl.append('  const status = pick(CLEARANCE_STATUS, seed)')
cbl.append('  const docStatus = status === "cleared" || status === "released" ? pick(["complete"], seed + 1) : pick(DOC_STATUS, seed + 1)')
cbl.append('  return {')
cbl.append('    id: "CBL-" + String(i + 7001).padStart(4, "0"), type: pick(SHIPMENT_TYPES, seed + 2), status, mode: pick(MODES, seed + 3),')
cbl.append('    country: pick(COUNTRIES, seed + 4), gateway: pick(GATEWAYS, seed + 5), docStatus,')
cbl.append('    hsCode: "HS" + ri(1000, 9999, seed + 6), weight: ri(50, 25000, seed + 7),')
cbl.append('    duty: ri(5000, 500000, seed + 8), igst: ri(1000, 180000, seed + 9),')
cbl.append('    clearanceTime: ri(1, 72, seed + 10), documents: ri(2, 12, seed + 11),')
cbl.append('    containerNo: "MSCU" + ri(100000, 999999, seed + 12), value: ri(100000, 10000000, seed + 13)')
cbl.append('  }')
cbl.append('})')
cbl.append('')
cbl.append('const monthlyData = MO.map((m, i) => ({ month: m, shipments: ri(150, 400, i * 13 + 1), duty: ri(500, 2000, i * 13 + 2), clearance: ri(85, 98, i * 13 + 3), holds: ri(2, 15, i * 13 + 4) }))')
cbl.append('const modeDist = MODES.map((m, i) => ({ name: m, value: ri(10, 30, i * 41) }))')
cbl.append('')
cbl.append('export default function CrossBorderLogisticsView() {')
cbl.append('  const [tab, setTab] = useState("dashboard")')
cbl.append('  const [searchQuery, setSearchQuery] = useState("")')
cbl.append('  const [activeFilters, setActiveFilters] = useState<Record<string, string[]>>({})')
cbl.append('')
cbl.append('  const filteredShipments = useMemo(() => {')
cbl.append('    return shipments.filter(s => {')
cbl.append('      if (searchQuery && !s.id.toLowerCase().includes(searchQuery.toLowerCase()) && !s.country.toLowerCase().includes(searchQuery.toLowerCase()) && !s.containerNo.toLowerCase().includes(searchQuery.toLowerCase())) return false')
cbl.append('      if (activeFilters["type"] && !activeFilters["type"].includes(s.type)) return false')
cbl.append('      if (activeFilters["status"] && !activeFilters["status"].includes(s.status)) return false')
cbl.append('      if (activeFilters["mode"] && !activeFilters["mode"].includes(s.mode)) return false')
cbl.append('      return true')
cbl.append('    })')
cbl.append('  }, [searchQuery, activeFilters])')
cbl.append('')
cbl.append('  const filterGroups = [')
cbl.append('    { key: "type", label: "Type", options: SHIPMENT_TYPES.map(t => ({ value: t, label: t.replace(/_/g, " "), count: 0 })) },')
cbl.append('    { key: "status", label: "Status", options: CLEARANCE_STATUS.map(s => ({ value: s, label: s.replace(/_/g, " "), count: 0 })) },')
cbl.append('    { key: "mode", label: "Mode", options: MODES.map(m => ({ value: m, label: m, count: 0 })) }')
cbl.append('  ]')
cbl.append('')
cbl.append('  const totalShipments = shipments.length')
cbl.append('  const clearanceRate = Math.round(shipments.filter(s => s.status === "cleared" || s.status === "released").length / totalShipments * 100)')
cbl.append('  const totalDuty = shipments.reduce((s, sh) => s + sh.duty, 0)')
cbl.append('  const heldCount = shipments.filter(s => s.status === "held" || s.status === "rejected").length')
cbl.append('')
cbl.append('  return (')
cbl.append('    <div className="space-y-4">')
cbl.append('      <PageHeader title="Cross-Border Logistics Hub" description="International trade compliance, customs clearance and cross-border shipment tracking" />')
cbl.append('      <Tabs value={tab} onValueChange={setTab}>')
cbl.append('        <TabsList className="cbl-tabs-list">')
cbl.append('          <TabsTrigger value="dashboard">Dashboard</TabsTrigger>')
cbl.append('          <TabsTrigger value="shipments">Shipments</TabsTrigger>')
cbl.append('          <TabsTrigger value="compliance">Compliance</TabsTrigger>')
cbl.append('          <TabsTrigger value="insights">Insights</TabsTrigger>')
cbl.append('        </TabsList>')
cbl.append('        <TabsContent value="dashboard">')
cbl.append('          <div className="grid grid-cols-4 gap-4 mb-4">')
cbl.append('            <KpiTile label="Active Shipments" value={String(totalShipments)} change={10} icon={Globe} />')
cbl.append('            <KpiTile label="Clearance Rate" value={clearanceRate + "%"} change={5} icon={ShieldCheck} />')
cbl.append('            <KpiTile label="Total Duty" value={"&#8377;" + (totalDuty / 10000000).toFixed(2) + "Cr"} change={-3} icon={DollarSign} />')
cbl.append('            <KpiTile label="Held/Rejected" value={String(heldCount)} change={-20} icon={ShieldAlert} />')
cbl.append('          </div>')
cbl.append('          <div className="flex gap-6 mb-4 justify-center flex-wrap">')
cbl.append('            <HealthRing pct={clearanceRate} label="Clearance" color={TH.ok} />')
cbl.append('            <HealthRing pct={92} label="Doc Accuracy" color={TH.pri} />')
cbl.append('            <HealthRing pct={88} label="On-Time" color={TH.sec} />')
cbl.append('            <HealthRing pct={95} label="Compliance" color={TH.ok} />')
cbl.append('            <HealthRing pct={78} label="Auto-Clear" color={TH.ter} />')
cbl.append('            <HealthRing pct={84} label="Digital Filing" color={TH.pri} />')
cbl.append('          </div>')
cbl.append('          <div className="grid grid-cols-3 gap-4">')
cbl.append('            <Card className="cbl-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Shipment Volume</CardTitle></CardHeader><CardContent><LineChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Line type="monotone" dataKey="shipments" stroke={TH.pri} strokeWidth={2} /></LineChart></CardContent></Card>')
cbl.append('            <Card className="cbl-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Customs Holds</CardTitle></CardHeader><CardContent><BarChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey="holds" fill={TH.err} radius={[4, 4, 0, 0]} /></BarChart></CardContent></Card>')
cbl.append('            <Card className="cbl-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Clearance Trend</CardTitle></CardHeader><CardContent><AreaChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Area type="monotone" dataKey="clearance" stroke={TH.ok} fill="rgba(5,150,105,0.15)" strokeWidth={2} /></AreaChart></CardContent></Card>')
cbl.append('          </div>')
cbl.append('        </TabsContent>')
cbl.append('        <TabsContent value="shipments">')
cbl.append('          <ModuleBreadcrumb items={[{ label: "Cross-Border" }, { label: "All Shipments" }]} />')
cbl.append('          <SearchFilterToolbar searchQuery={searchQuery} onSearchChange={setSearchQuery} onClearSearch={() => setSearchQuery("")} activeFilters={activeFilters} filterGroups={filterGroups} onToggleFilter={(k, v) => setActiveFilters(p => { const arr = p[k] || []; return arr.includes(v) ? (function(){ const n = {...p}; n[k] = arr.filter(x => x !== v); if(n[k].length === 0) delete n[k]; return n })() : {...p, [k]: [...arr, v]} })} onClearAllFilters={() => setActiveFilters({})} totalItems={totalShipments} filteredCount={filteredShipments.length} onRefresh={() => {}} placeholder="Search by ID, country, or container..." />')
cbl.append('          <Card className="cbl-table-card"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50"><th className="px-3 py-2 text-left font-semibold">ID</th><th className="px-3 py-2 text-left font-semibold">Type</th><th className="px-3 py-2 text-left font-semibold">Status</th><th className="px-3 py-2 text-left font-semibold">Mode</th><th className="px-3 py-2 text-left font-semibold">Country</th><th className="px-3 py-2 text-left font-semibold">Gateway</th><th className="px-3 py-2 text-left font-semibold">HS Code</th><th className="px-3 py-2 text-left font-semibold">Duty</th><th className="px-3 py-2 text-left font-semibold">Docs</th><th className="px-3 py-2 text-left font-semibold">Clearance</th></tr></thead><tbody>')
cbl.append('            {filteredShipments.slice(0, 30).map((s) => (')
cbl.append('              <tr key={s.id} className="cbl-table-row border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800/30 transition-colors">')
cbl.append('                <td className="px-3 py-2 font-mono font-semibold text-teal-600">{s.id}</td>')
cbl.append('                <td className="px-3 py-2"><ShipmentTypeBadge type={s.type} /></td>')
cbl.append('                <td className="px-3 py-2"><StatusBadge status={s.status} /></td>')
cbl.append('                <td className="px-3 py-2"><ModeBadge mode={s.mode} /></td>')
cbl.append('                <td className="px-3 py-2"><CountryBadge country={s.country} /></td>')
cbl.append('                <td className="px-3 py-2 text-gray-600 dark:text-gray-400">{s.gateway}</td>')
cbl.append('                <td className="px-3 py-2 font-mono text-[10px]">{s.hsCode}</td>')
cbl.append('                <td className="px-3 py-2"><DutyBar value={s.duty} max={500000} /></td>')
cbl.append('                <td className="px-3 py-2"><DocBadge status={s.docStatus} /></td>')
cbl.append('                <td className="px-3 py-2 text-gray-600">{s.clearanceTime}h</td>')
cbl.append('              </tr>')
cbl.append('            ))}')
cbl.append('          </tbody></table></div></CardContent></Card>')
cbl.append('        </TabsContent>')
cbl.append('        <TabsContent value="compliance">')
cbl.append('          <ModuleBreadcrumb items={[{ label: "Cross-Border" }, { label: "Compliance" }]} />')
cbl.append('          <div className="grid grid-cols-4 gap-4 mb-4">')
cbl.append('            <ValueTile label="Exports Cleared" value={String(shipments.filter(s => s.type === "export" && s.status === "cleared").length)} color={TH.ok} />')
cbl.append('            <ValueTile label="Held at Customs" value={String(shipments.filter(s => s.status === "held").length)} color={TH.err} />')
cbl.append('            <ValueTile label="Avg Duty/Ship" value={"&#8377;" + Math.round(totalDuty / totalShipments).toLocaleString()} color={TH.pri} />')
cbl.append('            <ValueTile label="Doc Complete" value={String(shipments.filter(s => s.docStatus === "complete").length)} color={TH.sec} />')
cbl.append('          </div>')
cbl.append('          <div className="grid grid-cols-2 gap-4">')
cbl.append('            <Card className="cbl-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Transport Mode Split</CardTitle></CardHeader><CardContent><PieChart><Pie data={modeDist} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({ name, percent }) => name + " " + (percent * 100).toFixed(0) + "%"} labelLine={false}><Cell fill={PC[0]} /><Cell fill={PC[1]} /><Cell fill={PC[2]} /><Cell fill={PC[3]} /><Cell fill={PC[4]} /></Pie><Tooltip /></PieChart></CardContent></Card>')
cbl.append('            <Card className="cbl-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Monthly Duty (Lakh)</CardTitle></CardHeader><CardContent><BarChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey="duty" fill={TH.pri} radius={[4, 4, 0, 0]} /></BarChart></CardContent></Card>')
cbl.append('          </div>')
cbl.append('        </TabsContent>')
cbl.append('        <TabsContent value="insights">')
cbl.append('          <ModuleBreadcrumb items={[{ label: "Cross-Border" }, { label: "Insights" }]} />')
cbl.append('          <div className="grid grid-cols-2 gap-4">')
cbl.append('            <Card className="cbl-insight-card border-l-4 border-l-teal-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><TrendingUp className="w-4 h-4 text-teal-600" /><span className="font-semibold text-sm">Export Growth China Route</span></div><p className="text-xs text-gray-600 dark:text-gray-400">China-India export corridor grew 18% QoQ. Electronics and pharmaceuticals dominate. Consider pre-clearance agreements with Nhava Sheva customs to reduce dwell time by 30%.</p></CardContent></Card>')
cbl.append('            <Card className="cbl-insight-card border-l-4 border-l-red-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><AlertTriangle className="w-4 h-4 text-red-600" /><span className="font-semibold text-sm">Documentation Delays</span></div><p className="text-xs text-gray-600 dark:text-gray-400">12% of shipments have incomplete documentation at filing. Certificate of Origin and FSSAI licenses are the top missing docs. Automate pre-filing validation to reduce holds.</p></CardContent></Card>')
cbl.append('            <Card className="cbl-insight-card border-l-4 border-l-indigo-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><Ship className="w-4 h-4 text-indigo-600" /><span className="font-semibold text-sm">Sea Freight Optimization</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Sea freight accounts for 45% of volumes but 62% of customs holds. Container scanning backlog at Chennai Port is causing 8-hour delays. Explore direct port clearance for trusted traders.</p></CardContent></Card>')
cbl.append('            <Card className="cbl-insight-card border-l-4 border-l-emerald-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><CheckCircle2 className="w-4 h-4 text-emerald-600" /><span className="font-semibold text-sm">GST Integration Success</span></div><p className="text-xs text-gray-600 dark:text-gray-400">E-Way bill auto-generation achieved 94% success rate for cross-border shipments. Integration with ICEGATE reducing manual data entry by 70% across all gateways.</p></CardContent></Card>')
cbl.append('          </div>')
cbl.append('        </TabsContent>')
cbl.append('      </Tabs>')
cbl.append('    </div>')
cbl.append('  )')
cbl.append('}')
cbl.append('')

# ──────────────────────────────────────────────────────────────
# MODULE 2: Warehouse Digital Floor Plan (wdf-*)
# ──────────────────────────────────────────────────────────────
wdf = []
wdf.append('"use client"')
wdf.append('import { useState, useMemo } from "react"')
wdf.append('import { AreaChart, Area, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts"')
wdf.append('import { BarChart3, TrendingUp, TrendingDown, MapPin, Package, Timer, ArrowUpDown, Grid2x2Plus, AlertTriangle, CheckCircle2, Route, Activity, Thermometer, Users, Box, ScanBarcode, Zap, Lock, Unlock, Eye, Move, RotateCw, Clock, DollarSign } from "lucide-react"')
wdf.append('import { PageHeader } from "@/components/shared/page-header"')
wdf.append('import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar"')
wdf.append('import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb"')
wdf.append('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
wdf.append('import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"')
wdf.append('import { Badge } from "@/components/ui/badge"')
wdf.append('')
wdf.append('const ZONE_TYPES = ["receiving", "bulk_storage", "picking", "packing", "shipping", "quality", "cold_storage", "hazmat", "returns", "staging"] as const')
wdf.append('const ZONE_STATUS = ["active", "under_maintenance", "full", "locked", "reconfiguring", "idle"] as const')
wdf.append('const FLOOR_TYPES = ["ground", "mezzanine", "upper", "basement", "roof"] as const')
wdf.append('const WAREHOUSES = ["Mumbai DC-1", "Delhi DC-2", "Bangalore DC-3", "Chennai DC-4", "Hyderabad DC-5", "Pune DC-6", "Kolkata DC-7", "Ahmedabad DC-8"] as const')
wdf.append('const RACK_TYPES = ["selective", "drive_in", "push_back", "mobile", "high_bay", "carton_flow", "pallet_flow"] as const')
wdf.append('const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] as const')
wdf.append('const TH = { pri: "#2563eb", sec: "#7c3aed", ter: "#059669", ok: "#059669", warn: "#d97706", err: "#dc2626" }')
wdf.append('const PC = ["#2563eb", "#7c3aed", "#059669", "#f59e0b", "#dc2626", "#8b5cf6", "#ec4899", "#14b8a6"]')
wdf.append('')
wdf.append('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297) * 233280; return x - Math.floor(x) }')
wdf.append('function ri(min: number, max: number, seed: number): number { return Math.floor(seededRandom(seed) * (max - min + 1)) + min }')
wdf.append('function pick<T>(arr: readonly T[], seed: number): T { return arr[Math.floor(seededRandom(seed) * arr.length)] }')
wdf.append('')
wdf.append('function ZoneTypeBadge({ type }: { type: string }) {')
wdf.append('  const cols: Record<string, string> = { receiving: "bg-blue-100 text-blue-700 dark:bg-blue-900/30", bulk_storage: "bg-violet-100 text-violet-700 dark:bg-violet-900/30", picking: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30", packing: "bg-amber-100 text-amber-700 dark:bg-amber-900/30", shipping: "bg-sky-100 text-sky-700", quality: "bg-pink-100 text-pink-700", cold_storage: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30", hazmat: "wdf-hazmat bg-red-100 text-red-700 dark:bg-red-900/30", returns: "bg-orange-100 text-orange-700 dark:bg-orange-900/30", staging: "bg-gray-100 text-gray-700" }')
wdf.append('  return <span className={"wdf-type-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[type] || "bg-gray-100 text-gray-700")}>{type.replace(/_/g, " ")}</span>')
wdf.append('}')
wdf.append('')
wdf.append('function StatusBadge({ status }: { status: string }) {')
wdf.append('  const cols: Record<string, string> = { active: "wdf-active bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 shadow-[0_0_6px_rgba(5,150,105,0.3)]", under_maintenance: "wdf-maintenance bg-amber-100 text-amber-700 dark:bg-amber-900/30", full: "wdf-full bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_6px_rgba(220,38,38,0.3)]", locked: "wdf-locked bg-violet-100 text-violet-700 dark:bg-violet-900/30", reconfiguring: "wdf-reconfiguring bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30", idle: "bg-gray-200 text-gray-600 dark:bg-gray-700" }')
wdf.append('  return <span className={"wdf-status-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[status] || "")}>{status.replace(/_/g, " ")}</span>')
wdf.append('}')
wdf.append('')
wdf.append('function FloorBadge({ floor }: { floor: string }) {')
wdf.append('  const cols: Record<string, string> = { ground: "bg-blue-100 text-blue-700", mezzanine: "bg-violet-100 text-violet-700", upper: "bg-indigo-100 text-indigo-700", basement: "bg-gray-100 text-gray-600", roof: "bg-amber-100 text-amber-700" }')
wdf.append('  return <span className={"wdf-floor-badge inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-bold " + (cols[floor] || "")}>{floor}</span>')
wdf.append('}')
wdf.append('')
wdf.append('function RackBadge({ type }: { type: string }) {')
wdf.append('  return <span className={"wdf-rack-badge inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-medium bg-gray-100 text-gray-600 dark:bg-gray-700"}>{type.replace(/_/g, " ")}</span>')
wdf.append('}')
wdf.append('')
wdf.append('function UtilBar({ value }: { value: number }) {')
wdf.append('  const col = value >= 95 ? TH.err : value >= 80 ? TH.warn : TH.ok')
wdf.append('  return <div className="wdf-util-bar flex items-center gap-1.5"><div className="w-16 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: value + "%", backgroundColor: col }}/></div><span className="text-[10px] font-bold" style={{ color: col }}>{value}%</span></div>')
wdf.append('}')
wdf.append('')
wdf.append('function SlotBar({ used, total }: { used: number; total: number }) {')
wdf.append('  const pct = Math.round((used / total) * 100); const col = pct >= 95 ? TH.err : pct >= 80 ? TH.warn : TH.ok')
wdf.append('  return <div className="wdf-slot-bar flex items-center gap-1.5"><div className="w-14 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: pct + "%", backgroundColor: col }}/></div><span className="text-[10px] font-semibold" style={{ color: col }}>{used}/{total}</span></div>')
wdf.append('}')
wdf.append('')
wdf.append('function HealthRing({ pct, label, color }: { pct: number; label: string; color: string }) {')
wdf.append('  const r = 28, c = 2 * Math.PI * r, off = c - (pct / 100) * c')
wdf.append('  return <div className="wdf-health-ring flex flex-col items-center"><svg width="68" height="68" viewBox="0 0 68 68"><circle cx="34" cy="34" r={r} fill="none" stroke="#e5e7eb" strokeWidth="6"/><circle cx="34" cy="34" r={r} fill="none" stroke={color} strokeWidth="6" strokeDasharray={c} strokeDashoffset={off} strokeLinecap="round" transform="rotate(-90 34 34)" className="transition-all duration-700"/><text x="34" y="38" textAnchor="middle" className="text-[11px] font-bold" fill={color}>{pct}%</text></svg><span className="text-[9px] text-gray-500 mt-0.5">{label}</span></div>')
wdf.append('}')
wdf.append('')
wdf.append('function KpiTile({ label, value, change, icon: Icon }: { label: string; value: string; change: number; icon: React.ComponentType<{ className?: string }> }) {')
wdf.append('  return <div className="wdf-kpi-tile bg-white dark:bg-gray-800 rounded-xl p-4 border border-gray-200 dark:border-gray-700 shadow-sm hover:shadow-md transition-shadow"><div className="flex items-center justify-between mb-2"><span className="text-[11px] font-medium text-gray-500">{label}</span><Icon className="w-4 h-4 text-blue-500"/></div><div className="text-xl font-bold text-gray-900 dark:text-gray-100">{value}</div><div className={"flex items-center gap-1 mt-1 text-[10px] font-semibold " + (change >= 0 ? "text-emerald-600" : "text-red-500")}><span>{change >= 0 ? "+" : ""}{change}%</span></div></div>')
wdf.append('}')
wdf.append('')
wdf.append('function ValueTile({ label, value, color }: { label: string; value: string; color: string }) {')
wdf.append('  return <div className="wdf-value-tile bg-white dark:bg-gray-800 rounded-lg p-3 border border-gray-200 dark:border-gray-700"><div className="text-[10px] text-gray-500 mb-1">{label}</div><div className="text-lg font-bold" style={{ color }}>{value}</div></div>')
wdf.append('}')
wdf.append('')
wdf.append('const zones = Array.from({ length: 65 }, (_, i) => {')
wdf.append('  const seed = i * 257 + 61')
wdf.append('  const status = pick(ZONE_STATUS, seed)')
wdf.append('  const totalSlots = ri(50, 500, seed + 1)')
wdf.append('  const usedSlots = status === "full" ? totalSlots : status === "idle" ? ri(0, 10, seed + 2) : ri(10, totalSlots, seed + 2)')
wdf.append('  return {')
wdf.append('    id: "WDF-" + String(i + 3001).padStart(4, "0"), type: pick(ZONE_TYPES, seed + 3), status,')
wdf.append('    floor: pick(FLOOR_TYPES, seed + 4), warehouse: pick(WAREHOUSES, seed + 5),')
wdf.append('    rackType: pick(RACK_TYPES, seed + 6), totalSlots, usedSlots,')
wdf.append('    utilisation: Math.round((usedSlots / totalSlots) * 100),')
wdf.append('    sqft: ri(500, 10000, seed + 7), aisles: ri(2, 12, seed + 8),')
wdf.append('    temp: ri(18, 28, seed + 9), humidity: ri(35, 75, seed + 10),')
wdf.append('    lastAudit: MO[ri(0, 11, seed + 11)] + " " + ri(1, 28, seed + 12),')
wdf.append('    equipment: ri(2, 20, seed + 13)')
wdf.append('  }')
wdf.append('})')
wdf.append('')
wdf.append('const monthlyData = MO.map((m, i) => ({ month: m, throughput: ri(5000, 15000, i * 17 + 1), utilisation: ri(65, 95, i * 17 + 2), reconfig: ri(1, 8, i * 17 + 3), audits: ri(2, 12, i * 17 + 4) }))')
wdf.append('const zoneDist = ZONE_TYPES.map((z, i) => ({ name: z.replace(/_/g, " "), value: ri(5, 15, i * 43) }))')
wdf.append('')
wdf.append('export default function WarehouseDigitalFloorPlanView() {')
wdf.append('  const [tab, setTab] = useState("dashboard")')
wdf.append('  const [searchQuery, setSearchQuery] = useState("")')
wdf.append('  const [activeFilters, setActiveFilters] = useState<Record<string, string[]>>({})')
wdf.append('')
wdf.append('  const filteredZones = useMemo(() => {')
wdf.append('    return zones.filter(z => {')
wdf.append('      if (searchQuery && !z.id.toLowerCase().includes(searchQuery.toLowerCase()) && !z.warehouse.toLowerCase().includes(searchQuery.toLowerCase()) && !z.type.toLowerCase().includes(searchQuery.toLowerCase())) return false')
wdf.append('      if (activeFilters["type"] && !activeFilters["type"].includes(z.type)) return false')
wdf.append('      if (activeFilters["status"] && !activeFilters["status"].includes(z.status)) return false')
wdf.append('      if (activeFilters["floor"] && !activeFilters["floor"].includes(z.floor)) return false')
wdf.append('      return true')
wdf.append('    })')
wdf.append('  }, [searchQuery, activeFilters])')
wdf.append('')
wdf.append('  const filterGroups = [')
wdf.append('    { key: "type", label: "Zone Type", options: ZONE_TYPES.map(t => ({ value: t, label: t.replace(/_/g, " "), count: 0 })) },')
wdf.append('    { key: "status", label: "Status", options: ZONE_STATUS.map(s => ({ value: s, label: s.replace(/_/g, " "), count: 0 })) },')
wdf.append('    { key: "floor", label: "Floor", options: FLOOR_TYPES.map(f => ({ value: f, label: f, count: 0 })) }')
wdf.append('  ]')
wdf.append('')
wdf.append('  const totalZones = zones.length')
wdf.append('  const avgUtil = Math.round(zones.reduce((s, z) => s + z.utilisation, 0) / totalZones)')
wdf.append('  const totalSqft = zones.reduce((s, z) => s + z.sqft, 0)')
wdf.append('  const activeZones = zones.filter(z => z.status === "active").length')
wdf.append('')
wdf.append('  return (')
wdf.append('    <div className="space-y-4">')
wdf.append('      <PageHeader title="Warehouse Digital Floor Plan" description="Visualize and optimize warehouse zone layouts, slot utilization and space planning" />')
wdf.append('      <Tabs value={tab} onValueChange={setTab}>')
wdf.append('        <TabsList className="wdf-tabs-list">')
wdf.append('          <TabsTrigger value="dashboard">Dashboard</TabsTrigger>')
wdf.append('          <TabsTrigger value="zones">Zones</TabsTrigger>')
wdf.append('          <TabsTrigger value="layout">Layout</TabsTrigger>')
wdf.append('          <TabsTrigger value="insights">Insights</TabsTrigger>')
wdf.append('        </TabsList>')
wdf.append('        <TabsContent value="dashboard">')
wdf.append('          <div className="grid grid-cols-4 gap-4 mb-4">')
wdf.append('            <KpiTile label="Total Zones" value={String(totalZones)} change={8} icon={Grid2x2Plus} />')
wdf.append('            <KpiTile label="Avg Utilisation" value={avgUtil + "%"} change={3} icon={Activity} />')
wdf.append('            <KpiTile label="Total Sq Ft" value={(totalSqft / 100000).toFixed(1) + "L"} change={5} icon={Box} />')
wdf.append('            <KpiTile label="Active Zones" value={String(activeZones)} change={-2} icon={Zap} />')
wdf.append('          </div>')
wdf.append('          <div className="flex gap-6 mb-4 justify-center flex-wrap">')
wdf.append('            <HealthRing pct={avgUtil} label="Utilisation" color={TH.ok} />')
wdf.append('            <HealthRing pct={91} label="Space Used" color={TH.pri} />')
wdf.append('            <HealthRing pct={85} label="Pick Accuracy" color={TH.sec} />')
wdf.append('            <HealthRing pct={97} label="Slot Accuracy" color={TH.ok} />')
wdf.append('            <HealthRing pct={78} label="Automation" color={TH.ter} />')
wdf.append('            <HealthRing pct={93} label="Audit Score" color={TH.pri} />')
wdf.append('          </div>')
wdf.append('          <div className="grid grid-cols-3 gap-4">')
wdf.append('            <Card className="wdf-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Throughput</CardTitle></CardHeader><CardContent><LineChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Line type="monotone" dataKey="throughput" stroke={TH.pri} strokeWidth={2} /></LineChart></CardContent></Card>')
wdf.append('            <Card className="wdf-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Reconfigurations</CardTitle></CardHeader><CardContent><BarChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey="reconfig" fill={TH.sec} radius={[4, 4, 0, 0]} /></BarChart></CardContent></Card>')
wdf.append('            <Card className="wdf-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Utilisation Trend</CardTitle></CardHeader><CardContent><AreaChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Area type="monotone" dataKey="utilisation" stroke={TH.ter} fill="rgba(5,150,105,0.15)" strokeWidth={2} /></AreaChart></CardContent></Card>')
wdf.append('          </div>')
wdf.append('        </TabsContent>')
wdf.append('        <TabsContent value="zones">')
wdf.append('          <ModuleBreadcrumb items={[{ label: "Floor Plan" }, { label: "All Zones" }]} />')
wdf.append('          <SearchFilterToolbar searchQuery={searchQuery} onSearchChange={setSearchQuery} onClearSearch={() => setSearchQuery("")} activeFilters={activeFilters} filterGroups={filterGroups} onToggleFilter={(k, v) => setActiveFilters(p => { const arr = p[k] || []; return arr.includes(v) ? (function(){ const n = {...p}; n[k] = arr.filter(x => x !== v); if(n[k].length === 0) delete n[k]; return n })() : {...p, [k]: [...arr, v]} })} onClearAllFilters={() => setActiveFilters({})} totalItems={totalZones} filteredCount={filteredZones.length} onRefresh={() => {}} placeholder="Search zones by ID, warehouse, or type..." />')
wdf.append('          <Card className="wdf-table-card"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50"><th className="px-3 py-2 text-left font-semibold">ID</th><th className="px-3 py-2 text-left font-semibold">Type</th><th className="px-3 py-2 text-left font-semibold">Status</th><th className="px-3 py-2 text-left font-semibold">Floor</th><th className="px-3 py-2 text-left font-semibold">Warehouse</th><th className="px-3 py-2 text-left font-semibold">Rack</th><th className="px-3 py-2 text-left font-semibold">Utilisation</th><th className="px-3 py-2 text-left font-semibold">Slots</th><th className="px-3 py-2 text-left font-semibold">Sq Ft</th><th className="px-3 py-2 text-left font-semibold">Equipment</th></tr></thead><tbody>')
wdf.append('            {filteredZones.slice(0, 30).map((z) => (')
wdf.append('              <tr key={z.id} className="wdf-table-row border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800/30 transition-colors">')
wdf.append('                <td className="px-3 py-2 font-mono font-semibold text-blue-600">{z.id}</td>')
wdf.append('                <td className="px-3 py-2"><ZoneTypeBadge type={z.type} /></td>')
wdf.append('                <td className="px-3 py-2"><StatusBadge status={z.status} /></td>')
wdf.append('                <td className="px-3 py-2"><FloorBadge floor={z.floor} /></td>')
wdf.append('                <td className="px-3 py-2 text-gray-600 dark:text-gray-400">{z.warehouse}</td>')
wdf.append('                <td className="px-3 py-2"><RackBadge type={z.rackType} /></td>')
wdf.append('                <td className="px-3 py-2"><UtilBar value={z.utilisation} /></td>')
wdf.append('                <td className="px-3 py-2"><SlotBar used={z.usedSlots} total={z.totalSlots} /></td>')
wdf.append('                <td className="px-3 py-2 font-semibold">{z.sqft.toLocaleString()}</td>')
wdf.append('                <td className="px-3 py-2 text-gray-600">{z.equipment}</td>')
wdf.append('              </tr>')
wdf.append('            ))}')
wdf.append('          </tbody></table></div></CardContent></Card>')
wdf.append('        </TabsContent>')
wdf.append('        <TabsContent value="layout">')
wdf.append('          <ModuleBreadcrumb items={[{ label: "Floor Plan" }, { label: "Layout Analysis" }]} />')
wdf.append('          <div className="grid grid-cols-4 gap-4 mb-4">')
wdf.append('            <ValueTile label="Ground Floor Zones" value={String(zones.filter(z => z.floor === "ground").length)} color={TH.pri} />')
wdf.append('            <ValueTile label="Mezzanine Zones" value={String(zones.filter(z => z.floor === "mezzanine").length)} color={TH.sec} />')
wdf.append('            <ValueTile label="Total Aisles" value={String(zones.reduce((s, z) => s + z.aisles, 0))} color={TH.ok} />')
wdf.append('            <ValueTile label="Full Zones" value={String(zones.filter(z => z.status === "full").length)} color={TH.err} />')
wdf.append('          </div>')
wdf.append('          <div className="grid grid-cols-2 gap-4">')
wdf.append('            <Card className="wdf-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Zone Type Distribution</CardTitle></CardHeader><CardContent><PieChart><Pie data={zoneDist} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({ name, percent }) => name + " " + (percent * 100).toFixed(0) + "%"} labelLine={false}><Cell fill={PC[0]} /><Cell fill={PC[1]} /><Cell fill={PC[2]} /><Cell fill={PC[3]} /><Cell fill={PC[4]} /><Cell fill={PC[5]} /><Cell fill={PC[6]} /><Cell fill={PC[7]} /><Cell fill={PC[0]} /><Cell fill={PC[1]} /></Pie><Tooltip /></PieChart></CardContent></Card>')
wdf.append('            <Card className="wdf-chart-card"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Monthly Audits</CardTitle></CardHeader><CardContent><BarChart data={monthlyData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey="audits" fill={TH.pri} radius={[4, 4, 0, 0]} /></BarChart></CardContent></Card>')
wdf.append('          </div>')
wdf.append('        </TabsContent>')
wdf.append('        <TabsContent value="insights">')
wdf.append('          <ModuleBreadcrumb items={[{ label: "Floor Plan" }, { label: "Insights" }]} />')
wdf.append('          <div className="grid grid-cols-2 gap-4">')
wdf.append('            <Card className="wdf-insight-card border-l-4 border-l-blue-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><Grid2x2Plus className="w-4 h-4 text-blue-600" /><span className="font-semibold text-sm">Slotting Optimization</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Picking zones at Delhi DC-2 show 30% higher travel distance than optimal. Re-slotting fast-moving SKUs to golden zones can reduce pick time by 22% and improve throughput by 1800 units/day.</p></CardContent></Card>')
wdf.append('            <Card className="wdf-insight-card border-l-4 border-l-violet-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><RotateCw className="w-4 h-4 text-violet-600" /><span className="font-semibold text-sm">Zone Reconfiguration</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Mumbai DC-1 bulk storage is at 98% capacity. Recommend converting staging zone B3 to overflow storage. Estimated 2-day reconfiguration with minimal disruption to operations.</p></CardContent></Card>')
wdf.append('            <Card className="wdf-insight-card border-l-4 border-l-emerald-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><CheckCircle2 className="w-4 h-4 text-emerald-600" /><span className="font-semibold text-sm">Space Utilization</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Bangalore DC-3 achieved 94% space utilization after implementing high-bay racking. This model can be replicated to Chennai DC-4 and Hyderabad DC-5 for projected 15% capacity increase.</p></CardContent></Card>')
wdf.append('            <Card className="wdf-insight-card border-l-4 border-l-amber-500"><CardContent className="p-4"><div className="flex items-center gap-2 mb-2"><AlertTriangle className="w-4 h-4 text-amber-600" /><span className="font-semibold text-sm">Equipment Bottleneck</span></div><p className="text-xs text-gray-600 dark:text-gray-400">Pune DC-6 picking zone has 3 forklifts for 8 aisles causing peak-hour congestion. Deploying 2 additional reach trucks during 10AM-2PM shift can reduce wait time by 40%.</p></CardContent></Card>')
wdf.append('          </div>')
wdf.append('        </TabsContent>')
wdf.append('      </Tabs>')
wdf.append('    </div>')
wdf.append('  )')
wdf.append('}')
wdf.append('')

base = "/home/z/my-project/src/components/modules"
with open(os.path.join(base, "cross-border-logistics-view.tsx"), "w") as f:
    f.write("\n".join(cbl))
with open(os.path.join(base, "warehouse-digital-floor-plan-view.tsx"), "w") as f:
    f.write("\n".join(wdf))

print("Generated: cross-border-logistics-view.tsx")
print("Generated: warehouse-digital-floor-plan-view.tsx")
print(f"CBL lines: {len(cbl)}")
print(f"WDF lines: {len(wdf)}")
