#!/usr/bin/env python3
"""R266: Freight Lane Command Center + 3PL Partner Hub module generator"""
import os

BASE = "/home/z/my-project/src/components/modules"

# ═══════════════════════════════════════════════════════════
# MODULE 1: Freight Lane Command Center
# ═══════════════════════════════════════════════════════════
fl = []
a = fl.append

a('"use client"')
a('import { useState, useMemo } from "react"')
a('import { AreaChart, Area, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts"')
a('import { Workflow, Zap, AlertTriangle, CheckCircle2, BarChart3, TrendingUp, TrendingDown, MapPin, Package, Timer, ArrowUpDown, Radio, Truck, Ship, TrainFront, Plane, Gauge, Clock, DollarSign } from "lucide-react"')
a('import { PageHeader } from "@/components/shared/page-header"')
a('import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar"')
a('import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb"')
a('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
a('import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"')
a('import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"')
a('import { Badge } from "@/components/ui/badge"')
a('')
a('const MODES = ["road", "rail", "air", "sea", "multimodal"] as const')
a('const MODE_EMOJI: Record<string, string> = { road: "\\U0001f69a", rail: "\\U0001f682", air: "\\u2708\\ufe0f", sea: "\\U0001f6e2\\ufe0f", multimodal: "\\U0001f517" }')
a('const LANE_STATUS = ["active", "under_maintenance", "congested", "disrupted", "seasonal", "planned"] as const')
a('const PRIORITY = ["critical", "high", "medium", "low"] as const')
a('const CITIES = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Hyderabad", "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Lucknow"] as const')
a('const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] as const')
a('const TH = { pri: "#06b6d4", sec: "#f59e0b", ok: "#059669", warn: "#d97706", err: "#dc2626" }')
a('const PC = ["#06b6d4", "#f59e0b", "#059669", "#dc2626", "#8b5cf6", "#ec4899", "#14b8a6", "#3b82f6"]')
a('')
a('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297) * 233280; return x - Math.floor(x) }')
a('function ri(min: number, max: number, seed: number): number { return Math.floor(seededRandom(seed) * (max - min + 1)) + min }')
a('function pick<T>(arr: readonly T[], seed: number): T { return arr[Math.floor(seededRandom(seed) * arr.length)] }')
a('')
a('function ModeBadge({ mode }: { mode: string }) {')
a('  const cols: Record<string, string> = { road: "bg-blue-100 text-blue-700 dark:bg-blue-900/30", rail: "bg-red-100 text-red-700 dark:bg-red-900/30", air: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30", sea: "bg-violet-100 text-violet-700 dark:bg-violet-900/30", multimodal: "bg-amber-100 text-amber-700 dark:bg-amber-900/30" }')
a('  return <span className={"flc-mode-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[mode] || "bg-gray-100 text-gray-700")}>{MODE_EMOJI[mode] || "\\u2022"} {mode}</span>')
a('}')
a('')
a('function StatusBadge({ status }: { status: string }) {')
a('  const cols: Record<string, string> = { active: "flc-active bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 shadow-[0_0_6px_rgba(5,150,105,0.3)]", under_maintenance: "bg-amber-100 text-amber-700 dark:bg-amber-900/30", congested: "flc-congested bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_6px_rgba(220,38,38,0.3)]", disrupted: "flc-disrupted bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_8px_rgba(220,38,38,0.4)]", seasonal: "bg-blue-100 text-blue-700 dark:bg-blue-900/30", planned: "bg-gray-100 text-gray-600" }')
a('  return <span className={"flc-status-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[status] || "")}>{status.replace(/_/g, " ")}</span>')
a('}')
a('')
a('function PriorityBadge({ priority }: { priority: string }) {')
a('  const cols: Record<string, string> = { critical: "bg-red-100 text-red-700 dark:bg-red-900/30", high: "bg-amber-100 text-amber-700", medium: "bg-blue-100 text-blue-700", low: "bg-gray-100 text-gray-600" }')
a('  return <span className={"flc-priority-badge inline-flex items-center px-1.5 py-0.5 rounded text-[9px] font-bold " + (cols[priority] || "")}>{priority.toUpperCase()}</span>')
a('}')
a('')
a('function UtilBar({ value }: { value: number }) {')
a('  const col = value >= 90 ? TH.err : value >= 70 ? TH.warn : TH.ok')
a('  return <div className="flc-util-bar flex items-center gap-1.5"><div className="w-16 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: value + "%", backgroundColor: col }}/></div><span className="text-[10px] font-bold" style={{ color: col }}>{value}%</span></div>')
a('}')
a('')
a('function TrendIndicator({ value }: { value: number }) {')
a('  const pos = value > 0; const col = pos ? TH.ok : TH.err')
a('  return <span className="flc-trend inline-flex items-center gap-0.5 text-[10px] font-semibold" style={{ color: col }}>{pos ? <TrendingUp className="w-3 h-3" /> : <TrendingDown className="w-3 h-3" />}{Math.abs(value).toFixed(1)}%</span>')
a('}')
a('')
a('function CityBadge({ city }: { city: string }) { return <span className="flc-city-badge inline-flex items-center px-2 py-0.5 rounded text-[10px] font-medium bg-cyan-50 text-cyan-700 dark:bg-cyan-900/20">{city}</span> }')
a('')
a('function KpiTile({ label, value, icon, trend, color }: { label: string; value: string; icon: React.ReactNode; trend: number; color: string }) { return <Card className="flc-kpi-tile glass-subtle hover:shadow-lg transition-shadow border-l-4" style={{ borderLeftColor: color }}><CardContent className="p-3"><div className="flex items-center justify-between"><span className="text-[10px] text-muted-foreground">{label}</span>{icon}</div><div className="text-xl font-bold mt-1">{value}</div><TrendIndicator value={trend}/></CardContent></Card> }')
a('')
a('function ValueTile({ label, value }: { label: string; value: string | number }) { return <div className="flc-value-tile text-center p-2 rounded-lg bg-gray-50 dark:bg-gray-800/50"><div className="text-sm font-bold">{value}</div><div className="text-[10px] text-muted-foreground">{label}</div></div> }')
a('')
a('function HealthRing({ value, label }: { value: number; label: string }) { const col = value >= 90 ? TH.ok : value >= 70 ? TH.warn : TH.err; const r = 18, circ = 2 * Math.PI * r, offset = circ - (value / 100) * circ; return <div className="flc-health-ring flex flex-col items-center gap-1"><svg width={48} height={48} className="-rotate-90"><circle cx={24} cy={24} r={r} fill="none" stroke="currentColor" strokeWidth={3} className="text-gray-200 dark:text-gray-700"/><circle cx={24} cy={24} r={r} fill="none" stroke={col} strokeWidth={3} strokeDasharray={circ} strokeDashoffset={offset} strokeLinecap="round" className="transition-all"/></svg><span className="text-[10px] font-bold" style={{ color: col }}>{value}%</span><span className="text-[9px] text-muted-foreground">{label}</span></div> }')
a('')
a('function genLanes() {')
a('  return Array.from({ length: 60 }, (_, i) => ({')
a('    id: "LN-" + String(i + 1).padStart(4, "0"),')
a('    name: pick(["NH-48 Delhi-Mumbai", "NH-44 Delhi-Chennai", "NH-8 Mumbai-Ahmedabad", "Eastern Freight Corridor", "Western Dedicated Corridor", "Delhi-Kolkata Route", "Mumbai-Bangalore Express", "Chennai-Hyderabad Route", "North-South Express", "Golden Quadrilateral", "Port-to-Factory Link", "SEZ Hub Connector"], i + 1),')
a('    mode: pick(MODES, i * 3 + 2),')
a('    origin: pick(CITIES, i * 3 + 3),')
a('    dest: pick(CITIES, i * 3 + 5),')
a('    distance: ri(100, 2500, i + 7),')
a('    transitTime: ri(2, 72, i + 11),')
a('    cost: ri(5000, 500000, i + 17),')
a('    utilization: ri(20, 98, i + 23),')
a('    onTime: ri(60, 99, i + 29),')
a('    status: pick(LANE_STATUS, i + 37),')
a('    priority: pick(PRIORITY, i + 43),')
a('    shipments: ri(10, 500, i + 47),')
a('    incidents: ri(0, 15, i + 53),')
a('    avgSpeed: ri(20, 80, i + 59)')
a('  }))')
a('}')
a('')
a('function genShipments() {')
a('  return Array.from({ length: 40 }, (_, i) => ({')
a('    id: "SHP-" + String(i + 1).padStart(5, "0"),')
a('    lane: "LN-" + String(ri(1, 60, i + 7)).padStart(4, "0"),')
a('    carrier: pick(["BlueDart", "Delhivery", "DFLC", "Container Corp", "IRFC", "Spoton", "XpressBees", "DHL Supply Chain"], i + 11),')
a('    status: pick(["in_transit", "delivered", "delayed", "at_hub", "customs_hold", "cancelled"], i + 19),')
a('    eta: String(ri(1, 48, i + 27)) + "h",')
a('    weight: ri(50, 20000, i + 31),')
a('    value: ri(10000, 5000000, i + 37),')
a('    priority: pick(PRIORITY, i + 43),')
a('    origin: pick(CITIES, i + 47),')
a('    dest: pick(CITIES, i + 53)')
a('  }))')
a('}')
a('')
a('function genCharts() {')
a('  const throughput = MO.map((m, i) => ({ month: m, shipments: ri(2000, 8000, i + 101), onTime: ri(70, 98, i + 151), cost: ri(1000000, 5000000, i + 201) }))')
a('  const modeDist = MODES.map((m, i) => ({ mode: m, lanes: ri(5, 25, i + 301), volume: ri(100, 2000, i + 351) }))')
a('  const incLine = MO.map((m, i) => ({ month: m, critical: ri(1, 10, i + 401), major: ri(5, 20, i + 451), minor: ri(10, 40, i + 501) }))')
a('  return { throughput, modeDist, incLine }')
a('}')
a('')
a('export default function FreightLaneCommandView() {')
a('  const [tab, setTab] = useState("dashboard")')
a('  const [search, setSearch] = useState("")')
a('  const [sortCol, setSortCol] = useState<string | null>(null)')
a('  const [sortDir, setSortDir] = useState<"asc" | "desc">("asc")')
a('  const [activeFilters, setActiveFilters] = useState<Record<string, string[]>>({})')
a('  const lanes = useMemo(() => genLanes(), [])')
a('  const shipments = useMemo(() => genShipments(), [])')
a('  const charts = useMemo(() => genCharts(), [])')
a('  const filterLanes = useMemo(() => { let res = lanes; if (search) { const q = search.toLowerCase(); res = res.filter(l => Object.values(l).some(val => typeof val === "string" && val.toLowerCase().includes(q))) } for (const [k, vals] of Object.entries(activeFilters)) { if (vals.length > 0) res = res.filter(l => vals.includes(String(l[k as keyof typeof l]))) } return res }, [lanes, search, activeFilters])')
a('  const sortedLanes = useMemo(() => { if (!sortCol) return filterLanes; return [...filterLanes].sort((a: any, b: any) => { const av = a[sortCol], bv = b[sortCol]; const cmp = typeof av === "string" ? av.localeCompare(bv) : av - bv; return sortDir === "asc" ? cmp : -cmp }) }, [filterLanes, sortCol, sortDir])')
a('  const toggleSort = (col: string) => { if (sortCol === col) { setSortDir(d => d === "asc" ? "desc" : "asc") } else { setSortCol(col); setSortDir("asc") } }')
a('  const toggleFilter = (group: string, value: string) => { setActiveFilters(prev => { const cur = prev[group] || []; const next = cur.includes(value) ? cur.filter(v => v !== value) : [...cur, value]; if (next.length === 0) { const { [group]: _, ...rest } = prev; return rest } return { ...prev, [group]: next } }) }')
a('  const clearAllFilters = () => setActiveFilters({})')
a('  const handleRefresh = () => { setSearch(""); setActiveFilters({}); setSortCol(null) }')
a('')
a('  const laneFilterGroups = useMemo(() => { const mc: Record<string, number> = {}; const sc: Record<string, number> = {}; const pc: Record<string, number> = {}; lanes.forEach(l => { mc[l.mode] = (mc[l.mode] || 0) + 1; sc[l.status] = (sc[l.status] || 0) + 1; pc[l.priority] = (pc[l.priority] || 0) + 1 }); return [{ key: "mode", label: "Mode", options: Object.entries(mc).map(([value, count]) => ({ value, count })).sort((a, b) => b.count - a.count) }, { key: "status", label: "Status", options: Object.entries(sc).map(([value, count]) => ({ value, count })).sort((a, b) => b.count - a.count) }, { key: "priority", label: "Priority", options: Object.entries(pc).map(([value, count]) => ({ value, count })).sort((a, b) => b.count - a.count) }] }, [lanes])')
a('')
a('  return <div className="space-y-4 p-4">')
a('    <PageHeader title="Freight Lane Command Center" description="End-to-end transport corridor management with real-time visibility and optimization"/>')
a('')
a('    <Tabs value={tab} onValueChange={setTab}>')
a('      <TabsList className="grid grid-cols-4 w-full flc-tabs">')
a('        <TabsTrigger value="dashboard"><BarChart3 className="w-3 h-3 mr-1"/>Dashboard</TabsTrigger>')
a('        <TabsTrigger value="lanes"><Workflow className="w-3 h-3 mr-1"/>Lanes</TabsTrigger>')
a('        <TabsTrigger value="shipments"><Package className="w-3 h-3 mr-1"/>Shipments</TabsTrigger>')
a('        <TabsTrigger value="insights"><TrendingUp className="w-3 h-3 mr-1"/>Insights</TabsTrigger>')
a('      </TabsList>')
a('')
a('      <TabsContent value="dashboard" className="space-y-4">')
a('        <div className="grid grid-cols-4 gap-3">')
a('          <KpiTile label="Active Lanes" value={String(lanes.filter((l: any) => l.status === "active").length)} icon={<Workflow className="w-4 h-4" style={{ color: TH.pri }}/>} trend={8.2} color={TH.pri}/>')
a('          <KpiTile label="Avg Utilization" value="74%" icon={<Gauge className="w-4 h-4" style={{ color: TH.ok }}/>} trend={4.1} color={TH.ok}/>')
a('          <KpiTile label="Incidents" value={String(lanes.reduce((s: number, l: any) => s + l.incidents, 0))} icon={<AlertTriangle className="w-4 h-4" style={{ color: TH.err }}/>} trend={-12.5} color={TH.err}/>')
a('          <KpiTile label="On-Time Rate" value="91%" icon={<Clock className="w-4 h-4" style={{ color: TH.sec }}/>} trend={3.3} color={TH.sec}/>')
a('        </div>')
a('        <div className="grid grid-cols-4 gap-3">')
a('          <HealthRing value={92} label="Uptime"/>')
a('          <HealthRing value={74} label="Util"/>')
a('          <HealthRing value={91} label="On-Time"/>')
a('          <HealthRing value={85} label="Capacity"/>')
a('        </div>')
a('        <div className="grid grid-cols-3 gap-3">')
a('          <Card className="flc-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Shipment Throughput</CardTitle></CardHeader><CardContent className="p-2"><AreaChart data={charts.throughput} height={180}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" fontSize={10}/><YAxis fontSize={10}/><Tooltip contentStyle={{ fontSize: 11 }}/><Area type="monotone" dataKey="shipments" stroke={TH.pri} fill={TH.pri} fillOpacity={0.2}/></AreaChart></CardContent></Card>')
a('          <Card className="flc-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Mode Distribution</CardTitle></CardHeader><CardContent className="p-2"><BarChart data={charts.modeDist} height={180}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="mode" fontSize={9}/><YAxis fontSize={10}/><Tooltip contentStyle={{ fontSize: 11 }}/><Bar dataKey="lanes" fill={TH.sec}/></BarChart></CardContent></Card>')
a('          <Card className="flc-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Incident Trend</CardTitle></CardHeader><CardContent className="p-2"><LineChart data={charts.incLine} height={180}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" fontSize={10}/><YAxis fontSize={10}/><Tooltip contentStyle={{ fontSize: 11 }}/><Line type="monotone" dataKey="critical" stroke={TH.err}/><Line type="monotone" dataKey="major" stroke={TH.warn}/><Line type="monotone" dataKey="minor" stroke={TH.ok}/></LineChart></CardContent></Card>')
a('        </div>')
a('      </TabsContent>')
a('')
a('      <TabsContent value="lanes" className="space-y-4">')
a('        <ModuleBreadcrumb items={[{ label: "Dashboard" }, { label: "Lanes" }]}/>')
a('        <SearchFilterToolbar searchQuery={search} onSearchChange={setSearch} onClearSearch={() => setSearch("")} activeFilters={activeFilters} filterGroups={laneFilterGroups} onToggleFilter={toggleFilter} onClearAllFilters={clearAllFilters} totalItems={lanes.length} filteredCount={filterLanes.length} onRefresh={handleRefresh} placeholder="Search lanes..."/>')
a('        <Card className="flc-table-card"><CardContent className="p-2"><div className="overflow-x-auto"><table className="w-full text-[11px]"><thead><tr className="border-b flc-table-header"><th className="p-1.5 text-left cursor-pointer hover:bg-gray-100" onClick={() => toggleSort("id")}>ID <ArrowUpDown className="w-3 h-3 inline"/></th><th className="p-1.5 text-left">Lane Name</th><th className="p-1.5 text-left">Mode</th><th className="p-1.5 text-left">Route</th><th className="p-1.5 text-left">Distance</th><th className="p-1.5 text-left">Util</th><th className="p-1.5 text-left">On-Time</th><th className="p-1.5 text-left">Status</th><th className="p-1.5 text-left">Priority</th><th className="p-1.5 text-left">Shipments</th></tr></thead><tbody>')
a('          {sortedLanes.map((l: any) => <tr key={l.id} className="border-b hover:bg-cyan-50/50 dark:hover:bg-cyan-900/10 flc-table-row"><td className="p-1.5 font-mono">{l.id}</td><td className="p-1.5 font-medium text-[10px]">{l.name}</td><td className="p-1.5"><ModeBadge mode={l.mode}/></td><td className="p-1.5">{l.origin} - {l.dest}</td><td className="p-1.5">{l.distance} km</td><td className="p-1.5"><UtilBar value={l.utilization}/></td><td className="p-1.5"><span className={"text-[10px] font-bold " + (l.onTime >= 90 ? "text-emerald-600" : l.onTime >= 75 ? "text-amber-600" : "text-red-600")}>{l.onTime}%</span></td><td className="p-1.5"><StatusBadge status={l.status}/></td><td className="p-1.5"><PriorityBadge priority={l.priority}/></td><td className="p-1.5">{l.shipments}</td></tr>)}')
a('          </tbody></table></div></CardContent></Card>')
a('      </TabsContent>')
a('')
a('      <TabsContent value="shipments" className="space-y-4">')
a('        <ModuleBreadcrumb items={[{ label: "Dashboard" }, { label: "Shipments" }]}/>')
a('        <div className="grid grid-cols-4 gap-3">')
a('          <ValueTile label="In Transit" value={String(shipments.filter((s: any) => s.status === "in_transit").length)}/>')
a('          <ValueTile label="Delivered" value={String(shipments.filter((s: any) => s.status === "delivered").length)}/>')
a('          <ValueTile label="Delayed" value={String(shipments.filter((s: any) => s.status === "delayed").length)}/>')
a('          <ValueTile label="Avg Transit" value="18h"/>')
a('        </div>')
a('        <div className="grid grid-cols-2 gap-3">')
a('          <Card className="flc-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Monthly Cost</CardTitle></CardHeader><CardContent className="p-2"><AreaChart data={charts.throughput} height={200}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" fontSize={10}/><YAxis fontSize={10}/><Tooltip contentStyle={{ fontSize: 11 }}/><Area type="monotone" dataKey="cost" stroke={TH.err} fill={TH.err} fillOpacity={0.15}/></AreaChart></CardContent></Card>')
a('          <Card className="flc-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Mode Distribution</CardTitle></CardHeader><CardContent className="p-2"><PieChart height={200}><Pie data={MODES.map((m, i) => ({ name: m, value: ri(10, 50, i + 601) }))} cx="50%" cy="50%" outerRadius={60} dataKey="value" label><Cell fill={PC[0]}/><Cell fill={PC[1]}/><Cell fill={PC[2]}/><Cell fill={PC[3]}/><Cell fill={PC[4]}/></Pie><Tooltip contentStyle={{ fontSize: 11 }}/></PieChart></CardContent></Card>')
a('        </div>')
a('      </TabsContent>')
a('')
a('      <TabsContent value="insights" className="space-y-4">')
a('        <ModuleBreadcrumb items={[{ label: "Dashboard" }, { label: "Insights" }]}/>')
a('        <div className="grid grid-cols-2 gap-3">')
a('          <Card className="flc-insight-card p-4"><div className="text-xs font-semibold mb-2 flex items-center gap-1"><AlertTriangle className="w-3 h-3 text-red-500"/>Congestion Hotspots</div><div className="text-[10px] text-muted-foreground">NH-48 Delhi-Gurgaon and Mumbai-Pune expressway show peak congestion. Average delay increased 22% this month. Recommend time-slot scheduling and alternative routing during peak hours.</div></Card>')
a('          <Card className="flc-insight-card p-4"><div className="text-xs font-semibold mb-2 flex items-center gap-1"><Workflow className="w-3 h-3 text-cyan-500"/>Multimodal Opportunity</div><div className="text-[10px] text-muted-foreground">12 high-volume lanes could benefit from multi-modal shift. Rail-sea combo on Delhi-Chennai route saves 35% cost. Air-road for time-critical shipments on 5 lanes.</div></Card>')
a('          <Card className="flc-insight-card p-4"><div className="text-xs font-semibold mb-2 flex items-center gap-1"><DollarSign className="w-3 h-3 text-amber-500"/>Cost Optimization</div><div className="text-[10px] text-muted-foreground">Backhaul optimization on 8 lanes could reduce empty miles by 18%. Consolidation centers at Jaipur and Lucknow can improve load factors by 25%.</div></Card>')
a('          <Card className="flc-insight-card p-4"><div className="text-xs font-semibold mb-2 flex items-center gap-1"><Zap className="w-3 h-3 text-emerald-500"/>Digital Corridor</div><div className="text-[10px] text-muted-foreground">Implement GPS tracking on 15 unmonitored lanes. Real-time ETA accuracy currently at 78%. Predictive delay modeling can improve customer SLA by 15%.</div></Card>')
a('        </div>')
a('      </TabsContent>')
a('    </Tabs>')
a('  </div>')
a('}')

with open(os.path.join(BASE, "freight-lane-command-view.tsx"), "w") as f:
    f.write("\n".join(fl))
print(f"Generated freight-lane-command-view.tsx: {len(fl)} lines")


# ═══════════════════════════════════════════════════════════
# MODULE 2: 3PL Partner Hub
# ═══════════════════════════════════════════════════════════
tp = []
a = tp.append

a('"use client"')
a('import { useState, useMemo } from "react"')
a('import { AreaChart, Area, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts"')
a('import { Link, Zap, AlertTriangle, CheckCircle2, BarChart3, TrendingUp, TrendingDown, MapPin, Package, Timer, ArrowUpDown, Radio, Star, ShieldCheck, Award, Users, DollarSign, Handshake, Target } from "lucide-react"')
a('import { PageHeader } from "@/components/shared/page-header"')
a('import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar"')
a('import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb"')
a('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
a('import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"')
a('import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"')
a('import { Badge } from "@/components/ui/badge"')
a('')
a('const PARTNER_TYPE = ["warehousing", "transport", "last_mile", "cold_chain", "cross_dock", "returns", "customs", "fulfillment"] as const')
a('const TYPE_EMOJI: Record<string, string> = { warehousing: "\\U0001f3e2", transport: "\\U0001f69a", last_mile: "\\U0001f3ce\\ufe0f", cold_chain: "\\u2744\\ufe0f", cross_dock: "\\u27a1\\ufe0f", returns: "\\U0001f504", customs: "\\U0001f6e1\\ufe0f", fulfillment: "\\U0001f4e6" }')
a('const PARTNER_STATUS = ["active", "probation", "suspended", "under_review", "inactive"] as const')
a('const SLA_LEVEL = ["gold", "silver", "bronze", "standard"] as const')
a('const CITIES = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Hyderabad", "Kolkata", "Pune", "Ahmedabad"] as const')
a('const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] as const')
a('const TH = { pri: "#ec4899", sec: "#f59e0b", ok: "#059669", warn: "#d97706", err: "#dc2626" }')
a('const PC = ["#ec4899", "#f59e0b", "#059669", "#dc2626", "#8b5cf6", "#06b6d4", "#14b8a6", "#3b82f6"]')
a('')
a('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297) * 233280; return x - Math.floor(x) }')
a('function ri(min: number, max: number, seed: number): number { return Math.floor(seededRandom(seed) * (max - min + 1)) + min }')
a('function pick<T>(arr: readonly T[], seed: number): T { return arr[Math.floor(seededRandom(seed) * arr.length)] }')
a('')
a('function TypeBadge({ type }: { type: string }) {')
a('  const cols: Record<string, string> = { warehousing: "bg-blue-100 text-blue-700 dark:bg-blue-900/30", transport: "bg-amber-100 text-amber-700 dark:bg-amber-900/30", last_mile: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30", cold_chain: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30", cross_dock: "bg-violet-100 text-violet-700 dark:bg-violet-900/30", returns: "bg-red-100 text-red-700 dark:bg-red-900/30", customs: "bg-orange-100 text-orange-700 dark:bg-orange-900/30", fulfillment: "bg-pink-100 text-pink-700 dark:bg-pink-900/30" }')
a('  return <span className={"tph-type-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[type] || "bg-gray-100 text-gray-700")}>{TYPE_EMOJI[type] || "\\u2022"} {type.replace(/_/g, " ")}</span>')
a('}')
a('')
a('function StatusBadge({ status }: { status: string }) {')
a('  const cols: Record<string, string> = { active: "tph-active bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 shadow-[0_0_6px_rgba(5,150,105,0.3)]", probation: "bg-amber-100 text-amber-700 dark:bg-amber-900/30", suspended: "tph-suspended bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_8px_rgba(220,38,38,0.4)]", under_review: "bg-violet-100 text-violet-700 dark:bg-violet-900/30", inactive: "bg-gray-200 text-gray-500" }')
a('  return <span className={"tph-status-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[status] || "")}>{status.replace(/_/g, " ")}</span>')
a('}')
a('')
a('function SlaBadge({ level }: { level: string }) {')
a('  const cols: Record<string, string> = { gold: "tph-gold bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 shadow-[0_0_6px_rgba(202,138,4,0.3)]", silver: "bg-gray-200 text-gray-700 dark:bg-gray-700/30", bronze: "bg-orange-100 text-orange-700 dark:bg-orange-900/30", standard: "bg-blue-100 text-blue-700 dark:bg-blue-900/30" }')
a('  return <span className={"tph-sla-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[level] || "")}><Award className="w-3 h-3"/>{level}</span>')
a('}')
a('')
a('function ScoreBar({ value }: { value: number }) {')
a('  const col = value >= 90 ? TH.ok : value >= 70 ? TH.warn : TH.err')
a('  return <div className="tph-score-bar flex items-center gap-1.5"><div className="w-16 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: value + "%", backgroundColor: col }}/></div><span className="text-[10px] font-bold" style={{ color: col }}>{value}</span></div>')
a('}')
a('')
a('function StarRating({ rating }: { rating: number }) { return <span className="tph-stars inline-flex gap-0.5">{[1,2,3,4,5].map(i => <Star key={i} className={"w-3 h-3 " + (i <= rating ? "fill-yellow-400 text-yellow-400" : "text-gray-300")} style={{ fill: i <= rating ? "#facc15" : "none" }}/>)}</span> }')
a('')
a('function TrendIndicator({ value }: { value: number }) {')
a('  const pos = value > 0; const col = pos ? TH.ok : TH.err')
a('  return <span className="tph-trend inline-flex items-center gap-0.5 text-[10px] font-semibold" style={{ color: col }}>{pos ? <TrendingUp className="w-3 h-3" /> : <TrendingDown className="w-3 h-3" />}{Math.abs(value).toFixed(1)}%</span>')
a('}')
a('')
a('function CityBadge({ city }: { city: string }) { return <span className="tph-city-badge inline-flex items-center px-2 py-0.5 rounded text-[10px] font-medium bg-pink-50 text-pink-700 dark:bg-pink-900/20">{city}</span> }')
a('')
a('function KpiTile({ label, value, icon, trend, color }: { label: string; value: string; icon: React.ReactNode; trend: number; color: string }) { return <Card className="tph-kpi-tile glass-subtle hover:shadow-lg transition-shadow border-l-4" style={{ borderLeftColor: color }}><CardContent className="p-3"><div className="flex items-center justify-between"><span className="text-[10px] text-muted-foreground">{label}</span>{icon}</div><div className="text-xl font-bold mt-1">{value}</div><TrendIndicator value={trend}/></CardContent></Card> }')
a('')
a('function ValueTile({ label, value }: { label: string; value: string | number }) { return <div className="tph-value-tile text-center p-2 rounded-lg bg-gray-50 dark:bg-gray-800/50"><div className="text-sm font-bold">{value}</div><div className="text-[10px] text-muted-foreground">{label}</div></div> }')
a('')
a('function HealthRing({ value, label }: { value: number; label: string }) { const col = value >= 90 ? TH.ok : value >= 70 ? TH.warn : TH.err; const r = 18, circ = 2 * Math.PI * r, offset = circ - (value / 100) * circ; return <div className="tph-health-ring flex flex-col items-center gap-1"><svg width={48} height={48} className="-rotate-90"><circle cx={24} cy={24} r={r} fill="none" stroke="currentColor" strokeWidth={3} className="text-gray-200 dark:text-gray-700"/><circle cx={24} cy={24} r={r} fill="none" stroke={col} strokeWidth={3} strokeDasharray={circ} strokeDashoffset={offset} strokeLinecap="round" className="transition-all"/></svg><span className="text-[10px] font-bold" style={{ color: col }}>{value}%</span><span className="text-[9px] text-muted-foreground">{label}</span></div> }')
a('')
a('function genPartners() {')
a('  return Array.from({ length: 50 }, (_, i) => ({')
a('    id: "3PL-" + String(i + 1).padStart(4, "0"),')
a('    name: pick(["BlueDart Express", "Delhivery Logistics", "DTDC Express", "XpressBees", "Ecom Express", "Shadowfax", "Spoton Logistics", "DHL Supply Chain", "FedEx India", "Gati Ltd", "TNT Express", "Allcargo Logistics", "VRL Logistics", "TCI Express", "SafeExpress"], i + 1),')
a('    type: pick(PARTNER_TYPE, i * 3 + 2),')
a('    city: pick(CITIES, i * 3 + 3),')
a('    sla: pick(SLA_LEVEL, i + 7),')
a('    status: pick(PARTNER_STATUS, i + 15),')
a('    score: ri(40, 99, i + 23),')
a('    rating: ri(2, 5, i + 29),')
a('    shipments: ri(50, 5000, i + 37),')
a('    onTime: ri(60, 99, i + 43),')
a('    damage: ri(0, 5, i + 49),')
a('    revenue: ri(100000, 10000000, i + 53),')
a('    contractEnd: "2026-" + String(ri(8, 12, i + 59)).padStart(2, "0") + "-" + String(ri(1, 28, i + 61)).padStart(2, "0")')
a('  }))')
a('}')
a('')
a('function genContracts() {')
a('  return Array.from({ length: 30 }, (_, i) => ({')
a('    id: "CTR-" + String(i + 1).padStart(4, "0"),')
a('    partner: pick(["BlueDart", "Delhivery", "DTDC", "XpressBees", "Ecom Express", "Shadowfax", "Spoton", "DHL"], i + 7),')
a('    type: pick(PARTNER_TYPE, i + 15),')
a('    value: ri(500000, 20000000, i + 23),')
a('    start: "2026-01-" + String(ri(1, 28, i + 29)).padStart(2, "0"),')
a('    end: "2026-" + String(ri(6, 12, i + 37)).padStart(2, "0") + "-" + String(ri(1, 28, i + 41)).padStart(2, "0"),')
a('    status: pick(["active", "expiring_soon", "expired", "renewed", "terminated"], i + 47),')
a('    penalty: ri(0, 500000, i + 53)')
a('  }))')
a('}')
a('')
a('function genCharts() {')
a('  const spend = MO.map((m, i) => ({ month: m, spend: ri(5000000, 20000000, i + 101), partners: ri(20, 50, i + 151), sla: ri(80, 98, i + 201) }))')
a('  const typeDist = PARTNER_TYPE.map((t, i) => ({ type: t.replace(/_/g, " "), count: ri(3, 15, i + 301), avgScore: ri(60, 95, i + 351) }))')
a('  const scoreLine = MO.map((m, i) => ({ month: m, avgScore: ri(70, 95, i + 401), onTime: ri(75, 99, i + 451) }))')
a('  return { spend, typeDist, scoreLine }')
a('}')
a('')
a('export default function ThreePlPartnerHubView() {')
a('  const [tab, setTab] = useState("dashboard")')
a('  const [search, setSearch] = useState("")')
a('  const [sortCol, setSortCol] = useState<string | null>(null)')
a('  const [sortDir, setSortDir] = useState<"asc" | "desc">("asc")')
a('  const [activeFilters, setActiveFilters] = useState<Record<string, string[]>>({})')
a('  const partners = useMemo(() => genPartners(), [])')
a('  const contracts = useMemo(() => genContracts(), [])')
a('  const charts = useMemo(() => genCharts(), [])')
a('  const filterPartners = useMemo(() => { let res = partners; if (search) { const q = search.toLowerCase(); res = res.filter(p => Object.values(p).some(val => typeof val === "string" && val.toLowerCase().includes(q))) } for (const [k, vals] of Object.entries(activeFilters)) { if (vals.length > 0) res = res.filter(p => vals.includes(String(p[k as keyof typeof p]))) } return res }, [partners, search, activeFilters])')
a('  const sortedPartners = useMemo(() => { if (!sortCol) return filterPartners; return [...filterPartners].sort((a: any, b: any) => { const av = a[sortCol], bv = b[sortCol]; const cmp = typeof av === "string" ? av.localeCompare(bv) : av - bv; return sortDir === "asc" ? cmp : -cmp }) }, [filterPartners, sortCol, sortDir])')
a('  const toggleSort = (col: string) => { if (sortCol === col) { setSortDir(d => d === "asc" ? "desc" : "asc") } else { setSortCol(col); setSortDir("asc") } }')
a('  const toggleFilter = (group: string, value: string) => { setActiveFilters(prev => { const cur = prev[group] || []; const next = cur.includes(value) ? cur.filter(v => v !== value) : [...cur, value]; if (next.length === 0) { const { [group]: _, ...rest } = prev; return rest } return { ...prev, [group]: next } }) }')
a('  const clearAllFilters = () => setActiveFilters({})')
a('  const handleRefresh = () => { setSearch(""); setActiveFilters({}); setSortCol(null) }')
a('')
a('  const partnerFilterGroups = useMemo(() => { const tc: Record<string, number> = {}; const sc: Record<string, number> = {}; const slac: Record<string, number> = {}; partners.forEach(p => { tc[p.type] = (tc[p.type] || 0) + 1; sc[p.status] = (sc[p.status] || 0) + 1; slac[p.sla] = (slac[p.sla] || 0) + 1 }); return [{ key: "type", label: "Type", options: Object.entries(tc).map(([value, count]) => ({ value, count })).sort((a, b) => b.count - a.count) }, { key: "status", label: "Status", options: Object.entries(sc).map(([value, count]) => ({ value, count })).sort((a, b) => b.count - a.count) }, { key: "sla", label: "SLA Tier", options: Object.entries(slac).map(([value, count]) => ({ value, count })).sort((a, b) => b.count - a.count) }] }, [partners])')
a('')
a('  return <div className="space-y-4 p-4">')
a('    <PageHeader title="3PL Partner Hub" description="Comprehensive partner management with SLA tracking, performance scoring and contract lifecycle"/>')
a('')
a('    <Tabs value={tab} onValueChange={setTab}>')
a('      <TabsList className="grid grid-cols-4 w-full tph-tabs">')
a('        <TabsTrigger value="dashboard"><BarChart3 className="w-3 h-3 mr-1"/>Dashboard</TabsTrigger>')
a('        <TabsTrigger value="partners"><Users className="w-3 h-3 mr-1"/>Partners</TabsTrigger>')
a('        <TabsTrigger value="contracts"><Handshake className="w-3 h-3 mr-1"/>Contracts</TabsTrigger>')
a('        <TabsTrigger value="insights"><TrendingUp className="w-3 h-3 mr-1"/>Insights</TabsTrigger>')
a('      </TabsList>')
a('')
a('      <TabsContent value="dashboard" className="space-y-4">')
a('        <div className="grid grid-cols-4 gap-3">')
a('          <KpiTile label="Active Partners" value={String(partners.filter((p: any) => p.status === "active").length)} icon={<Users className="w-4 h-4" style={{ color: TH.pri }}/>} trend={10.5} color={TH.pri}/>')
a('          <KpiTile label="Avg Score" value="82" icon={<Star className="w-4 h-4" style={{ color: TH.sec }}/>} trend={5.2} color={TH.sec}/>')
a('          <KpiTile label="SLA Compliance" value="91%" icon={<ShieldCheck className="w-4 h-4" style={{ color: TH.ok }}/>} trend={3.8} color={TH.ok}/>')
a('          <KpiTile label="Active Contracts" value={String(contracts.filter((c: any) => c.status === "active").length)} icon={<Handshake className="w-4 h-4" style={{ color: TH.warn }}/>} trend={2.1} color={TH.warn}/>')
a('        </div>')
a('        <div className="grid grid-cols-4 gap-3">')
a('          <HealthRing value={88} label="On-Time"/>')
a('          <HealthRing value={91} label="SLA"/>')
a('          <HealthRing value={82} label="Quality"/>')
a('          <HealthRing value={76} label="Retention"/>')
a('        </div>')
a('        <div className="grid grid-cols-3 gap-3">')
a('          <Card className="tph-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Monthly Spend</CardTitle></CardHeader><CardContent className="p-2"><AreaChart data={charts.spend} height={180}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" fontSize={10}/><YAxis fontSize={10}/><Tooltip contentStyle={{ fontSize: 11 }}/><Area type="monotone" dataKey="spend" stroke={TH.pri} fill={TH.pri} fillOpacity={0.2}/></AreaChart></CardContent></Card>')
a('          <Card className="tph-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Partner Type Distribution</CardTitle></CardHeader><CardContent className="p-2"><BarChart data={charts.typeDist} height={180}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="type" fontSize={8}/><YAxis fontSize={10}/><Tooltip contentStyle={{ fontSize: 11 }}/><Bar dataKey="count" fill={TH.sec}/></BarChart></CardContent></Card>')
a('          <Card className="tph-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Performance Trend</CardTitle></CardHeader><CardContent className="p-2"><LineChart data={charts.scoreLine} height={180}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" fontSize={10}/><YAxis fontSize={10}/><Tooltip contentStyle={{ fontSize: 11 }}/><Line type="monotone" dataKey="avgScore" stroke={TH.ok}/><Line type="monotone" dataKey="onTime" stroke={TH.pri}/></LineChart></CardContent></Card>')
a('        </div>')
a('      </TabsContent>')
a('')
a('      <TabsContent value="partners" className="space-y-4">')
a('        <ModuleBreadcrumb items={[{ label: "Dashboard" }, { label: "Partners" }]}/>')
a('        <SearchFilterToolbar searchQuery={search} onSearchChange={setSearch} onClearSearch={() => setSearch("")} activeFilters={activeFilters} filterGroups={partnerFilterGroups} onToggleFilter={toggleFilter} onClearAllFilters={clearAllFilters} totalItems={partners.length} filteredCount={filterPartners.length} onRefresh={handleRefresh} placeholder="Search partners..."/>')
a('        <Card className="tph-table-card"><CardContent className="p-2"><div className="overflow-x-auto"><table className="w-full text-[11px]"><thead><tr className="border-b tph-table-header"><th className="p-1.5 text-left cursor-pointer hover:bg-gray-100" onClick={() => toggleSort("id")}>ID <ArrowUpDown className="w-3 h-3 inline"/></th><th className="p-1.5 text-left">Partner</th><th className="p-1.5 text-left">Type</th><th className="p-1.5 text-left">City</th><th className="p-1.5 text-left">SLA</th><th className="p-1.5 text-left">Score</th><th className="p-1.5 text-left">Rating</th><th className="p-1.5 text-left">On-Time</th><th className="p-1.5 text-left">Shipments</th><th className="p-1.5 text-left">Status</th></tr></thead><tbody>')
a('          {sortedPartners.map((p: any) => <tr key={p.id} className="border-b hover:bg-pink-50/50 dark:hover:bg-pink-900/10 tph-table-row"><td className="p-1.5 font-mono">{p.id}</td><td className="p-1.5 font-medium">{p.name}</td><td className="p-1.5"><TypeBadge type={p.type}/></td><td className="p-1.5"><CityBadge city={p.city}/></td><td className="p-1.5"><SlaBadge level={p.sla}/></td><td className="p-1.5"><ScoreBar value={p.score}/></td><td className="p-1.5"><StarRating rating={p.rating}/></td><td className="p-1.5"><span className={"text-[10px] font-bold " + (p.onTime >= 90 ? "text-emerald-600" : p.onTime >= 75 ? "text-amber-600" : "text-red-600")}>{p.onTime}%</span></td><td className="p-1.5">{p.shipments}</td><td className="p-1.5"><StatusBadge status={p.status}/></td></tr>)}')
a('          </tbody></table></div></CardContent></Card>')
a('      </TabsContent>')
a('')
a('      <TabsContent value="contracts" className="space-y-4">')
a('        <ModuleBreadcrumb items={[{ label: "Dashboard" }, { label: "Contracts" }]}/>')
a('        <div className="grid grid-cols-4 gap-3">')
a('          <ValueTile label="Active" value={String(contracts.filter((c: any) => c.status === "active").length)}/>')
a('          <ValueTile label="Expiring Soon" value={String(contracts.filter((c: any) => c.status === "expiring_soon").length)}/>')
a('          <ValueTile label="Expired" value={String(contracts.filter((c: any) => c.status === "expired").length)}/>')
a('          <ValueTile label="Total Value" value="\\u20b98.5Cr"/>')
a('        </div>')
a('        <div className="grid grid-cols-2 gap-3">')
a('          <Card className="tph-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Spend Trend</CardTitle></CardHeader><CardContent className="p-2"><AreaChart data={charts.spend} height={200}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" fontSize={10}/><YAxis fontSize={10}/><Tooltip contentStyle={{ fontSize: 11 }}/><Area type="monotone" dataKey="spend" stroke={TH.pri} fill={TH.pri} fillOpacity={0.15}/></AreaChart></CardContent></Card>')
a('          <Card className="tph-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">SLA Tier Distribution</CardTitle></CardHeader><CardContent className="p-2"><PieChart height={200}><Pie data={SLA_LEVEL.map((s, i) => ({ name: s, value: ri(3, 20, i + 601) }))} cx="50%" cy="50%" outerRadius={60} dataKey="value" label><Cell fill={PC[0]}/><Cell fill={PC[1]}/><Cell fill={PC[2]}/><Cell fill={PC[3]}/></Pie><Tooltip contentStyle={{ fontSize: 11 }}/></PieChart></CardContent></Card>')
a('        </div>')
a('      </TabsContent>')
a('')
a('      <TabsContent value="insights" className="space-y-4">')
a('        <ModuleBreadcrumb items={[{ label: "Dashboard" }, { label: "Insights" }]}/>')
a('        <div className="grid grid-cols-2 gap-3">')
a('          <Card className="tph-insight-card p-4"><div className="text-xs font-semibold mb-2 flex items-center gap-1"><Star className="w-3 h-3 text-amber-500"/>Top Performers</div><div className="text-[10px] text-muted-foreground">5 partners scored above 95 this quarter. BlueDart and Delhivery lead in transport with 99% on-time. Shadowfax excels in last-mile with lowest cost-per-delivery at Rs 35.</div></Card>')
a('          <Card className="tph-insight-card p-4"><div className="text-xs font-semibold mb-2 flex items-center gap-1"><AlertTriangle className="w-3 h-3 text-red-500"/>At-Risk Partners</div><div className="text-[10px] text-muted-foreground">3 partners on probation with scores below 60. 2 partners have SLA compliance under 70%. Recommend corrective action plans and 30-day improvement targets.</div></Card>')
a('          <Card className="tph-insight-card p-4"><div className="text-xs font-semibold mb-2 flex items-center gap-1"><Target className="w-3 h-3 text-cyan-500"/>Contract Optimization</div><div className="text-[10px] text-muted-foreground">8 contracts expiring in next 90 days. Consolidating cold-chain partners from 5 to 3 could save 18% annually. Multi-year commitments yield 12% rate advantage.</div></Card>')
a('          <Card className="tph-insight-card p-4"><div className="text-xs font-semibold mb-2 flex items-center gap-1"><DollarSign className="w-3 h-3 text-emerald-500"/>Revenue Impact</div><div className="text-[10px] text-muted-foreground">Partner-driven revenue grew 22% QoQ. Cross-dock partners contributed 15% of fulfillment capacity. Returns processing partners reduced reverse logistics cost by 28%.</div></Card>')
a('        </div>')
a('      </TabsContent>')
a('    </Tabs>')
a('  </div>')
a('}')

with open(os.path.join(BASE, "3pl-partner-hub-view.tsx"), "w") as f:
    f.write("\n".join(tp))
print(f"Generated 3pl-partner-hub-view.tsx: {len(tp)} lines")

print("Done! Both R266 modules generated successfully.")
