#!/usr/bin/env python3
"""R262: Generate Supply Chain Digital Twin + Last Mile Optimization Pro modules.
Both modules integrate SearchFilterToolbar + ModuleBreadcrumb directly.
"""

import os

BASE = "/home/z/my-project/src/components/modules"

# ============================================================
# MODULE A: Supply Chain Digital Twin
# ============================================================
lines_a = []
a = lines_a.append

a('"use client"')
a('import { useState, useMemo } from "react"')
a('import { AreaChart, Area, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts"')
a('import { Network, Layers, Activity, TrendingUp, TrendingDown, BarChart3, Zap, AlertTriangle, CheckCircle2, Clock, Radio, Globe, Box, Truck, MapPin, GitBranch, Cpu, RefreshCw, Eye, ArrowUpDown, Search } from "lucide-react"')
a('import { PageHeader } from "@/components/shared/page-header"')
a('import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar"')
a('import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb"')
a('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
a('import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"')
a('import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"')
a('import { Badge } from "@/components/ui/badge"')
a('')
a('// ── Constants ──')
a('const NODE_TYPES = ["supplier", "factory", "warehouse", "dc", "retail", "customer", "port", "airport"] as const')
a('const NODE_EMOJI: Record<string, string> = { supplier: "\\U0001f4e6", factory: "\\U0001f3ed", warehouse: "\\U0001f4e6", dc: "\\U0001f3e0", retail: "\\U0001f3ea", customer: "\\U0001f464", port: "\\u2693", airport: "\\u2708" }')
a('const LINK_TYPES = ["road", "rail", "sea", "air", "pipeline"] as const')
a('const LINK_EMOJI: Record<string, string> = { road: "\\U0001f697", rail: "\\U0001f684", sea: "\\u26f5", air: "\\u2708", pipeline: "\\U0001f6e0" }')
a('const SIM_STATUS = ["running", "paused", "completed", "failed", "queued"] as const')
a('const CITIES = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Hyderabad", "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Lucknow"] as const')
a('const REGIONS = ["West", "North", "South", "East", "Central"] as const')
a('const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] as const')
a('const TH = { pri: "#06b6d4", sec: "#8b5cf6", ok: "#059669", warn: "#d97706", err: "#dc2626" }')
a('const PC = ["#06b6d4", "#8b5cf6", "#059669", "#d97706", "#dc2626", "#3b82f6", "#ec4899", "#f59e0b"]')
a('')
a('// ── Utilities ──')
a('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297) * 233280; return x - Math.floor(x) }')
a('function ri(min: number, max: number, seed: number): number { return Math.floor(seededRandom(seed) * (max - min + 1)) + min }')
a('function pick<T>(arr: readonly T[], seed: number): T { return arr[Math.floor(seededRandom(seed) * arr.length)] }')
a('')
a('// ── Visual Components ──')
a('function NodeTypeBadge({ type }: { type: string }) {')
a('  const cols: Record<string, string> = { supplier: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30", factory: "bg-violet-100 text-violet-700 dark:bg-violet-900/30", warehouse: "bg-blue-100 text-blue-700 dark:bg-blue-900/30", dc: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30", retail: "bg-amber-100 text-amber-700 dark:bg-amber-900/30", customer: "bg-pink-100 text-pink-700 dark:bg-pink-900/30", port: "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30", airport: "bg-sky-100 text-sky-700 dark:bg-sky-900/30" }')
a('  return <span className={"sdt-node-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[type] || "bg-gray-100 text-gray-700")}>{NODE_EMOJI[type] || "\\u2022"} {type}</span>')
a('}')
a('')
a('function LinkTypeBadge({ type }: { type: string }) {')
a('  return <span className="sdt-link-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold bg-violet-100 text-violet-700 dark:bg-violet-900/30">{LINK_EMOJI[type] || "\\u2022"} {type}</span>')
a('}')
a('')
a('function SimStatusBadge({ status }: { status: string }) {')
a('  const cols: Record<string, string> = { running: "sdt-sim-running bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 shadow-[0_0_6px_rgba(5,150,105,0.3)]", paused: "sdt-sim-paused bg-amber-100 text-amber-700 dark:bg-amber-900/30", completed: "sdt-sim-done bg-blue-100 text-blue-700 dark:bg-blue-900/30", failed: "sdt-sim-failed bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_8px_rgba(220,38,38,0.4)]", queued: "sdt-sim-queued bg-gray-100 text-gray-500 dark:bg-gray-900/30" }')
a('  const icons: Record<string, React.ReactNode> = { running: <Radio className="w-3 h-3" />, paused: <Clock className="w-3 h-3" />, completed: <CheckCircle2 className="w-3 h-3" />, failed: <AlertTriangle className="w-3 h-3" />, queued: <Clock className="w-3 h-3" /> }')
a('  return <span className={"sdt-sim-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[status] || "")}>{icons[status]} {status}</span>')
a('}')
a('')
a('function ThroughputBar({ value, max }: { value: number; max: number }) {')
a('  const pct = Math.round((value / max) * 100)')
a('  const col = pct >= 80 ? TH.ok : pct >= 50 ? TH.pri : TH.err')
a('  return <div className="sdt-throughput-bar flex items-center gap-1.5"><div className="w-16 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: pct + "%", backgroundColor: col }}/></div><span className="text-[10px] font-bold" style={{ color: col }}>{pct}%</span></div>')
a('}')
a('')
a('function UtilGauge({ value }: { value: number }) {')
a('  const col = value >= 85 ? TH.err : value >= 60 ? TH.warn : TH.ok')
a('  return <div className="sdt-util-gauge flex items-center gap-1.5"><div className="w-16 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: value + "%", backgroundColor: col }}/></div><span className="text-[10px] font-bold" style={{ color: col }}>{value}%</span></div>')
a('}')
a('')
a('function TrendIndicator({ value }: { value: number }) {')
a('  const pos = value > 0')
a('  const col = pos ? TH.ok : TH.err')
a('  return <span className="sdt-trend inline-flex items-center gap-0.5 text-[10px] font-semibold" style={{ color: col }}>{pos ? <TrendingUp className="w-3 h-3" /> : <TrendingDown className="w-3 h-3" />}{Math.abs(value).toFixed(1)}%</span>')
a('}')
a('')
a('function CityBadge({ city }: { city: string }) {')
a('  return <span className="sdt-city-badge inline-flex items-center px-2 py-0.5 rounded text-[10px] font-medium bg-cyan-50 text-cyan-700 dark:bg-cyan-900/20">{city}</span>')
a('}')
a('')
a('function KpiTile({ label, value, icon, trend, color }: { label: string; value: string; icon: React.ReactNode; trend: number; color: string }) {')
a('  return <Card className="sdt-kpi-tile glass-subtle hover:shadow-lg transition-shadow border-l-4" style={{ borderLeftColor: color }}><CardContent className="p-3"><div className="flex items-center justify-between"><span className="text-[10px] text-muted-foreground">{label}</span>{icon}</div><div className="text-xl font-bold mt-1">{value}</div><TrendIndicator value={trend}/></CardContent></Card>')
a('}')
a('')
a('function ValueTile({ label, value }: { label: string; value: string | number }) {')
a('  return <div className="sdt-value-tile text-center p-2 rounded-lg bg-gray-50 dark:bg-gray-800/50"><div className="text-sm font-bold">{value}</div><div className="text-[10px] text-muted-foreground">{label}</div></div>')
a('}')
a('')
a('function HealthRing({ value, label }: { value: number; label: string }) {')
a('  const col = value >= 90 ? TH.ok : value >= 70 ? TH.warn : TH.err')
a('  const r = 18, circ = 2 * Math.PI * r, offset = circ - (value / 100) * circ')
a('  return <div className="sdt-health-ring flex flex-col items-center gap-1"><svg width={48} height={48} className="-rotate-90"><circle cx={24} cy={24} r={r} fill="none" stroke="currentColor" strokeWidth={3} className="text-gray-200 dark:text-gray-700"/><circle cx={24} cy={24} r={r} fill="none" stroke={col} strokeWidth={3} strokeDasharray={circ} strokeDashoffset={offset} strokeLinecap="round" className="transition-all"/></svg><span className="text-[10px] font-bold" style={{ color: col }}>{value}%</span><span className="text-[9px] text-muted-foreground">{label}</span></div>')
a('}')
a('')
a('function LatencyBadge({ ms }: { ms: number }) {')
a('  const col = ms <= 100 ? TH.ok : ms <= 300 ? TH.warn : TH.err')
a('  return <span className="sdt-latency-badge inline-flex items-center gap-1 text-[10px] font-bold" style={{ color: col }}><Zap className="w-3 h-3"/>{ms}ms</span>')
a('}')
a('')
a('function RiskBadge({ level }: { level: string }) {')
a('  const cols: Record<string, string> = { low: "sdt-risk-low bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30", medium: "sdt-risk-med bg-amber-100 text-amber-700 dark:bg-amber-900/30", high: "sdt-risk-high bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_6px_rgba(220,38,38,0.3)]", critical: "sdt-risk-crit bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_10px_rgba(220,38,38,0.5)]" }')
a('  return <span className={"sdt-risk-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[level] || "")}>{level}</span>')
a('}')
a('')
a('// ── Data Generators ──')
a('function genNodes() {')
a('  return Array.from({ length: 60 }, (_, i) => {')
a('    const nt = pick(NODE_TYPES, i * 3 + 1)')
a('    return {')
a('      id: "NODE-" + String(i + 1).padStart(4, "0"),')
a('      type: nt,')
a('      name: pick(["Tata Steel Hub", "Reliance DC South", "Flipkart Warehouse BLR", "Amazon FC HYD", "BigBasket DC MUM", "DMart Hub DEL", "Bhilwara Warehouse", "Port Mundra", "IGI Airport Hub", "Rail Terminal NCR", "Pharma cold chain", "Auto parts depot", "FMCG super hub", "Electronics zone", "Textile warehouse", "Food processing unit"], i * 3 + 2),')
a('      city: pick(CITIES, i * 3 + 3),')
a('      region: pick(REGIONS, i * 3 + 4),')
a('      capacity: ri(500, 50000, i + 7),')
a('      utilization: ri(30, 98, i + 13),')
a('      throughput: ri(200, 15000, i + 17),')
a('      health: ri(60, 99, i + 19),')
a('      status: pick(["active", "active", "active", "maintenance", "overflow", "degraded"], i + 23),')
a('      latency: ri(15, 450, i + 29),')
a('      connections: ri(2, 18, i + 31)')
a('    }')
a('  })')
a('}')
a('')
a('function genLinks() {')
a('  return Array.from({ length: 50 }, (_, i) => {')
a('    const lt = pick(LINK_TYPES, i * 3 + 1)')
a('    return {')
a('      id: "LINK-" + String(i + 1).padStart(4, "0"),')
a('      type: lt,')
a('      source: "NODE-" + String(ri(1, 60, i + 7)).padStart(4, "0"),')
a('      dest: "NODE-" + String(ri(1, 60, i + 11)).padStart(4, "0"),')
a('      distance: ri(50, 2500, i + 13),')
a('      cost: ri(500, 50000, i + 17),')
a('      transitTime: ri(2, 120, i + 19),')
a('      utilization: ri(20, 95, i + 23),')
a('      reliability: ri(75, 99, i + 29),')
a('      co2: +(ri(1, 500, i + 31) / 10).toFixed(1),')
a('      status: pick(["active", "active", "active", "delayed", "disrupted", "congested"], i + 37),')
a('      volume: ri(100, 8000, i + 41)')
a('    }')
a('  })')
a('}')
a('')
a('function genSimulations() {')
a('  return Array.from({ length: 20 }, (_, i) => {')
a('    const st = pick(SIM_STATUS, i * 3 + 1)')
a('    return {')
a('      id: "SIM-" + String(i + 1).padStart(4, "0"),')
a('      name: pick(["Festival Rush Surge", "Monsoon Disruption", "Port Strike Impact", "Rail Blockage Test", "Demand Spike 200%", "Supplier Failure Cascade", "Warehouse Fire Drill", "Road Flood Scenario", "Customs Delay Wave", "Fuel Price Hike", "New Market Entry", "DC Closure Model", "Multi-Modal Shift", "Inventory Buffer Test", "Lead Time Analysis", "Cost Optimization Run", "Carbon Reduction Plan", "Capacity Expansion", "Network Redesign", "Peak Season Stress"], i * 3 + 2),')
a('      status: st,')
a('      duration: ri(10, 480, i + 7),')
a('      progress: st === "completed" ? 100 : st === "running" ? ri(10, 95, i + 11) : 0,')
a('      nodes: ri(10, 60, i + 13),')
a('      events: ri(50, 2000, i + 17),')
a('      accuracy: ri(70, 98, i + 19),')
a('      created: "2026-07-" + String(ri(1, 30, i + 23)).padStart(2, "0"),')
a('      riskImpact: pick(["low", "medium", "high", "critical"], i + 29)')
a('    }')
a('  })')
a('}')
a('')
a('function genCharts() {')
a('  const throughput = MO.map((m, i) => ({ month: m, actual: ri(20000, 80000, i + 101), digital: ri(18000, 75000, i + 151), predicted: ri(19000, 82000, i + 201) }))')
a('  const nodeDist = NODE_TYPES.map((n, i) => ({ type: n, count: ri(3, 25, i + 301), avgHealth: ri(60, 98, i + 351) }))')
a('  const linkUtil = LINK_TYPES.map((l, i) => ({ type: l, utilization: ri(30, 95, i + 401), cost: ri(10000, 200000, i + 451), co2: ri(50, 800, i + 501) }))')
a('  const riskTrend = MO.map((m, i) => ({ month: m, disruptions: ri(1, 15, i + 551), resilience: ri(70, 98, i + 601), cost: ri(5000, 50000, i + 651) }))')
a('  return { throughput, nodeDist, linkUtil, riskTrend }')
a('}')
a('')
a('// ── Main Component ──')
a('export default function SupplyChainDigitalTwinView() {')
a('  const [tab, setTab] = useState("dashboard")')
a('  const [search, setSearch] = useState("")')
a('  const [detail, setDetail] = useState<Record<string, unknown> | null>(null)')
a('  const [sortField, setSortField] = useState("id")')
a('  const [sortDir, setSortDir] = useState<"asc" | "desc">("asc")')
a('')
a('  const nodes = useMemo(() => genNodes(), [])')
a('  const links = useMemo(() => genLinks(), [])')
a('  const simulations = useMemo(() => genSimulations(), [])')
a('  const charts = useMemo(() => genCharts(), [])')
a('')
a('  const toggleSort = (f: string) => { if (sortField === f) setSortDir(d => d === "asc" ? "desc" : "asc"); else { setSortField(f); setSortDir("asc") } }')
a('  const sortIcon = (f: string) => sortField === f ? (sortDir === "asc" ? "\\u2191" : "\\u2193") : ""')
a('')
a('  const filterNodes = useMemo(() => {')
a('    if (!search) return nodes')
a('    const lq = search.toLowerCase()')
a('    return nodes.filter(n => Object.values(n).some(v => typeof v === "string" && v.toLowerCase().includes(lq)))')
a('  }, [nodes, search])')
a('  const sortedNodes = useMemo(() => [...filterNodes].sort((a, b) => { const va = a[sortField as keyof typeof a], vb = b[sortField as keyof typeof b]; if (va == null || vb == null) return 0; const cmp = String(va).localeCompare(String(vb), undefined, { numeric: true }); return sortDir === "asc" ? cmp : -cmp }), [filterNodes, sortField, sortDir])')
a('')
a('  const filterLinks = useMemo(() => {')
a('    if (!search) return links')
a('    const lq = search.toLowerCase()')
a('    return links.filter(l => Object.values(l).some(v => typeof v === "string" && v.toLowerCase().includes(lq)))')
a('  }, [links, search])')
a('')
a('  const filterSims = useMemo(() => {')
a('    if (!search) return simulations')
a('    const lq = search.toLowerCase()')
a('    return simulations.filter(s => Object.values(s).some(v => typeof v === "string" && v.toLowerCase().includes(lq)))')
a('  }, [simulations, search])')
a('')
a('  // Computed KPIs')
a('  const avgUtil = Math.round(nodes.reduce((s, n) => s + n.utilization, 0) / nodes.length)')
a('  const totalThroughput = nodes.reduce((s, n) => s + n.throughput, 0)')
a('  const activeSims = simulations.filter(s => s.status === "running").length')
a('  const avgHealth = Math.round(nodes.reduce((s, n) => s + n.health, 0) / nodes.length)')
a('')
a('  const handleRefresh = () => { setSearch(""); setSortField("id"); setSortDir("asc") }')
a('')
a('  // Build filter groups for toolbar')
a('  const nodeFilterGroups = useMemo(() => {')
a('    const typeCounts: Record<string, number> = {}')
a('    const cityCounts: Record<string, number> = {}')
a('    nodes.forEach(n => { typeCounts[n.type] = (typeCounts[n.type] || 0) + 1; cityCounts[n.city] = (cityCounts[n.city] || 0) + 1 })')
a('    return [')
a('      { key: "type", label: "Node Type", options: Object.entries(typeCounts).map(([value, count]) => ({ value, count })).sort((a, b) => b.count - a.count) },')
a('      { key: "city", label: "City", options: Object.entries(cityCounts).map(([value, count]) => ({ value, count })).sort((a, b) => b.count - a.count).slice(0, 10) }')
a('    ]')
a('  }, [nodes])')
a('')
a('  const [activeFilters, setActiveFilters] = useState<Record<string, string[]>>({})')
a('  const toggleFilter = (group: string, value: string) => {')
a('    setActiveFilters(prev => {')
a('      const cur = prev[group] || []')
a('      const next = cur.includes(value) ? cur.filter(v => v !== value) : [...cur, value]')
a('      if (next.length === 0) { const { [group]: _, ...rest } = prev; return rest }')
a('      return { ...prev, [group]: next }')
a('    })')
a('  }')
a('  const clearAllFilters = () => setActiveFilters({})')
a('  const totalActiveFilters = Object.values(activeFilters).reduce((s, v) => s + v.length, 0)')
a('  const filteredCount = filterNodes.length')
a('')
a('  const tab0 = (')
a('    <div className="space-y-4">')
a('      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">')
a('        <KpiTile label="Total Nodes" value={nodes.length.toString()} icon={<Box className="w-4 h-4 text-cyan-500"/>} trend={5.2} color={TH.pri}/>')
a('        <KpiTile label="Total Throughput" value={totalThroughput.toLocaleString()} icon={<Truck className="w-4 h-4 text-violet-500"/>} trend={8.7} color={TH.sec}/>')
a('        <KpiTile label="Avg Utilization" value={avgUtil + "%"} icon={<Activity className="w-4 h-4 text-emerald-500"/>} trend={2.1} color={TH.ok}/>')
a('        <KpiTile label="Active Simulations" value={activeSims.toString()} icon={<Cpu className="w-4 h-4 text-amber-500"/>} trend={-3.4} color={TH.warn}/>')
a('      </div>')
a('      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">')
a('        <HealthRing value={avgHealth} label="Network Health"/>')
a('        <HealthRing value={Math.round(links.reduce((s, l) => s + l.reliability, 0) / links.length)} label="Link Reliability"/>')
a('        <HealthRing value={Math.round(simulations.reduce((s, si) => s + si.accuracy, 0) / simulations.length)} label="Sim Accuracy"/>')
a('        <HealthRing value={95} label="Data Freshness"/>')
a('      </div>')
a('      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">')
a('        <Card className="sdt-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Throughput: Real vs Digital Twin (Monthly)</CardTitle></CardHeader><CardContent><AreaChart data={charts.throughput} height={200}><CartesianGrid strokeDasharray="3 3" opacity={0.3}/><XAxis dataKey="month" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip contentStyle={{ fontSize: 10 }}/><Area type="monotone" dataKey="actual" stroke={TH.pri} fill={TH.pri} fillOpacity={0.2}/><Area type="monotone" dataKey="digital" stroke={TH.sec} fill={TH.sec} fillOpacity={0.15}/><Line type="monotone" dataKey="predicted" stroke={TH.ok} strokeWidth={2} strokeDasharray="5 5" dot={{ r: 3 }}/></AreaChart></CardContent></Card>')
a('        <Card className="sdt-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Node Distribution & Health</CardTitle></CardHeader><CardContent><BarChart data={charts.nodeDist} height={200}><CartesianGrid strokeDasharray="3 3" opacity={0.3}/><XAxis dataKey="type" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip contentStyle={{ fontSize: 10 }}/><Bar dataKey="count" fill={TH.pri} radius={[2, 2, 0, 0]}/><Bar dataKey="avgHealth" fill={TH.ok} radius={[2, 2, 0, 0]}/></BarChart></CardContent></Card>')
a('        <Card className="sdt-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Link Utilization by Type</CardTitle></CardHeader><CardContent><BarChart data={charts.linkUtil} height={200}><CartesianGrid strokeDasharray="3 3" opacity={0.3}/><XAxis dataKey="type" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip contentStyle={{ fontSize: 10 }}/><Bar dataKey="utilization" fill={TH.sec} radius={[2, 2, 0, 0]}/></BarChart></CardContent></Card>')
a('        <Card className="sdt-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Risk & Resilience Trend</CardTitle></CardHeader><CardContent><LineChart data={charts.riskTrend} height={200}><CartesianGrid strokeDasharray="3 3" opacity={0.3}/><XAxis dataKey="month" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip contentStyle={{ fontSize: 10 }}/><Line type="monotone" dataKey="disruptions" stroke={TH.err} strokeWidth={2} dot={{ r: 3 }}/><Line type="monotone" dataKey="resilience" stroke={TH.ok} strokeWidth={2} strokeDasharray="5 5" dot={{ r: 3 }}/></LineChart></CardContent></Card>')
a('      </div>')
a('    </div>')
a('  )')
a('')
a('  const tab1 = (')
a('    <div className="space-y-3">')
a('      <ModuleBreadcrumb items={[{ label: "Analytics" }, { label: "Digital Twin" }, { label: "Network Nodes" }]}/>')
a('      <SearchFilterToolbar searchQuery={search} onSearchChange={setSearch} onClearSearch={() => setSearch("")} activeFilters={activeFilters} filterGroups={nodeFilterGroups} onToggleFilter={toggleFilter} onClearAllFilters={clearAllFilters} totalItems={nodes.length} filteredCount={filteredCount} onRefresh={handleRefresh} placeholder="Search nodes by name, city, type..." />')
a('      <div className="rounded-lg border overflow-auto max-h-[calc(100vh-340px)]">')
a('        <table className="sdt-table w-full text-xs"><thead className="bg-cyan-50 dark:bg-cyan-900/20 sticky top-0"><tr><th className="p-2 text-left cursor-pointer select-none" onClick={() => toggleSort("id")}>ID {sortIcon("id")}</th><th className="p-2 text-left cursor-pointer select-none" onClick={() => toggleSort("name")}>Name {sortIcon("name")}</th><th className="p-2 text-left">Type</th><th className="p-2 text-left">City</th><th className="p-2 text-right">Utilization</th><th className="p-2 text-right">Throughput</th><th className="p-2 text-left">Health</th><th className="p-2 text-left">Status</th><th className="p-2 text-left">Latency</th><th className="p-2 text-right">Connections</th></tr></thead>')
a('        <tbody>{sortedNodes.map(n => <tr key={n.id} className="sdt-table-row border-t hover:bg-cyan-50/50 dark:hover:bg-cyan-900/10 cursor-pointer" onClick={() => setDetail(n as unknown as Record<string, unknown>)}><td className="p-2 font-mono">{n.id}</td><td className="p-2 font-medium">{n.name}</td><td className="p-2"><NodeTypeBadge type={n.type}/></td><td className="p-2"><CityBadge city={n.city}/></td><td className="p-2"><UtilGauge value={n.utilization}/></td><td className="p-2 text-right">{n.throughput.toLocaleString()}</td><td className="p-2"><div className="flex items-center gap-1"><div className="w-8 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full" style={{ width: n.health + "%", backgroundColor: n.health >= 90 ? TH.ok : n.health >= 70 ? TH.warn : TH.err }}/></div><span className="text-[10px]">{n.health}%</span></div></td><td className="p-2"><span className={"sdt-status-badge inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-medium " + (n.status === "active" ? "bg-emerald-100 text-emerald-700" : n.status === "maintenance" ? "bg-amber-100 text-amber-700" : n.status === "overflow" ? "bg-red-100 text-red-700" : "bg-gray-100 text-gray-600")}>{n.status}</span></td><td className="p-2"><LatencyBadge ms={n.latency}/></td><td className="p-2 text-right">{n.connections}</td></tr>)}</tbody></table>')
a('      </div>')
a('      <div className="flex items-center justify-between text-[10px] text-muted-foreground"><span>Showing {sortedNodes.length} of {nodes.length} nodes</span>{totalActiveFilters > 0 && <span>{totalActiveFilters} filters active</span>}</div>')
a('    </div>')
a('  )')
a('')
a('  const tab2 = (')
a('    <div className="space-y-3">')
a('      <ModuleBreadcrumb items={[{ label: "Analytics" }, { label: "Digital Twin" }, { label: "Network Links" }]}/>')
a('      <SearchFilterToolbar searchQuery={search} onSearchChange={setSearch} onClearSearch={() => setSearch("")} activeFilters={activeFilters} filterGroups={[]} onToggleFilter={toggleFilter} onClearAllFilters={clearAllFilters} totalItems={links.length} filteredCount={filterLinks.length} onRefresh={handleRefresh} placeholder="Search links by ID, type, status..." />')
a('      <div className="rounded-lg border overflow-auto max-h-[calc(100vh-340px)]">')
a('        <table className="sdt-table w-full text-xs"><thead className="bg-violet-50 dark:bg-violet-900/20 sticky top-0"><tr><th className="p-2 text-left cursor-pointer select-none" onClick={() => toggleSort("id")}>ID {sortIcon("id")}</th><th className="p-2 text-left">Type</th><th className="p-2 text-left">Source</th><th className="p-2 text-left">Dest</th><th className="p-2 text-right">Distance</th><th className="p-2 text-right">Cost</th><th className="p-2 text-right">Transit</th><th className="p-2 text-left">Utilization</th><th className="p-2 text-left">Reliability</th><th className="p-2 text-left">Status</th></tr></thead>')
a('        <tbody>{filterLinks.map(l => <tr key={l.id} className="sdt-table-row border-t hover:bg-violet-50/50 dark:hover:bg-violet-900/10 cursor-pointer" onClick={() => setDetail(l as unknown as Record<string, unknown>)}><td className="p-2 font-mono">{l.id}</td><td className="p-2"><LinkTypeBadge type={l.type}/></td><td className="p-2 font-mono text-[10px]">{l.source}</td><td className="p-2 font-mono text-[10px]">{l.dest}</td><td className="p-2 text-right">{l.distance} km</td><td className="p-2 text-right font-medium">{"\\u20b9"}{l.cost.toLocaleString()}</td><td className="p-2 text-right">{l.transitTime}h</td><td className="p-2"><ThroughputBar value={l.utilization} max={100}/></td><td className="p-2"><span className="text-[10px] font-bold" style={{ color: l.reliability >= 95 ? TH.ok : l.reliability >= 85 ? TH.warn : TH.err }}>{l.reliability}%</span></td><td className="p-2"><span className={"sdt-link-status inline-flex px-1.5 py-0.5 rounded text-[10px] font-medium " + (l.status === "active" ? "bg-emerald-100 text-emerald-700" : l.status === "delayed" ? "bg-amber-100 text-amber-700" : l.status === "disrupted" ? "bg-red-100 text-red-700 shadow-[0_0_4px_rgba(220,38,38,0.3)]" : "bg-gray-100 text-gray-600")}>{l.status}</span></td></tr>)}</tbody></table>')
a('      </div>')
a('      <div className="text-[10px] text-muted-foreground text-right">{filterLinks.length} links</div>')
a('    </div>')
a('  )')
a('')
a('  const tab3 = (')
a('    <div className="space-y-4">')
a('      <ModuleBreadcrumb items={[{ label: "Analytics" }, { label: "Digital Twin" }, { label: "Simulations" }]}/>')
a('      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">')
a('        {simulations.map(s => (')
a('          <Card key={s.id} className={"sdt-sim-card glass-subtle hover:shadow-lg transition-shadow " + (s.status === "running" ? "border-emerald-300 dark:border-emerald-700" : s.status === "failed" ? "border-red-300 dark:border-red-700" : "")}>')
a('            <CardContent className="p-3 space-y-2">')
a('              <div className="flex items-center justify-between"><span className="font-semibold text-xs">{s.name}</span><SimStatusBadge status={s.status}/></div>')
a('              <div className="grid grid-cols-3 gap-1.5"><ValueTile label="Nodes" value={s.nodes}/><ValueTile label="Events" value={s.events.toLocaleString()}/><ValueTile label="Accuracy" value={s.accuracy + "%"}/></div>')
a('              <div className="flex items-center justify-between text-[10px]"><span className="text-muted-foreground">Duration</span><span>{s.duration} min</span></div>')
a('              {s.status === "running" && <div className="w-full h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full bg-emerald-500 transition-all" style={{ width: s.progress + "%" }}/></div>}')
a('              {s.status === "completed" && <div className="text-[10px] text-emerald-600 font-medium">100% complete</div>}')
a('              <div className="flex items-center justify-between"><RiskBadge level={s.riskImpact}/><span className="text-[10px] text-muted-foreground">{s.created}</span></div>')
a('            </CardContent>')
a('          </Card>')
a('        ))}')
a('      </div>')
a('    </div>')
a('  )')
a('')
a('  const tab4 = (')
a('    <div className="space-y-4">')
a('      <ModuleBreadcrumb items={[{ label: "Analytics" }, { label: "Digital Twin" }, { label: "KPI Dashboard" }]}/>')
a('      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">')
a('        <Card className="sdt-insight-card glass-subtle"><CardContent className="p-3 text-center"><div className="text-2xl font-bold text-cyan-600">{nodes.filter(n => n.utilization >= 80).length}</div><div className="text-[10px] text-muted-foreground mt-1">High Util Nodes</div><div className="mt-2 h-1 rounded-full bg-gray-200"><div className="h-full rounded-full bg-cyan-500" style={{ width: (nodes.filter(n => n.utilization >= 80).length / nodes.length * 100) + "%" }}/></div></CardContent></Card>')
a('        <Card className="sdt-insight-card glass-subtle"><CardContent className="p-3 text-center"><div className="text-2xl font-bold text-violet-600">{links.filter(l => l.status === "disrupted").length}</div><div className="text-[10px] text-muted-foreground mt-1">Disrupted Links</div><div className="mt-2 h-1 rounded-full bg-gray-200"><div className="h-full rounded-full bg-red-500" style={{ width: (links.filter(l => l.status === "disrupted").length / links.length * 100) + "%" }}/></div></CardContent></Card>')
a('        <Card className="sdt-insight-card glass-subtle"><CardContent className="p-3 text-center"><div className="text-2xl font-bold text-emerald-600">{"\\u20b9"}{links.reduce((s, l) => s + l.co2 * 100, 0).toLocaleString(undefined, { maximumFractionDigits: 0 })}</div><div className="text-[10px] text-muted-foreground mt-1">Total CO2 Cost</div></CardContent></Card>')
a('        <Card className="sdt-insight-card glass-subtle"><CardContent className="p-3 text-center"><div className="text-2xl font-bold text-amber-600">{simulations.filter(s => s.riskImpact === "critical").length}</div><div className="text-[10px] text-muted-foreground mt-1">Critical Risk Sims</div></CardContent></Card>')
a('      </div>')
a('      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">')
a('        <Card className="sdt-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Node Type Distribution</CardTitle></CardHeader><CardContent><PieChart width={300} height={200}><Pie data={NODE_TYPES.map((t) => ({ name: t, value: nodes.filter(n => n.type === t).length }))} cx="50%" cy="50%" outerRadius={70} dataKey="value" label={({ name, percent }) => name + " " + (percent * 100).toFixed(0) + "%"} labelLine={false}>{NODE_TYPES.map((_, i) => <Cell key={i} fill={PC[i % PC.length]}/>)}</Pie><Tooltip contentStyle={{ fontSize: 10 }}/></PieChart></CardContent></Card>')
a('        <Card className="sdt-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Link Mode Distribution</CardTitle></CardHeader><CardContent><PieChart width={300} height={200}><Pie data={LINK_TYPES.map((t) => ({ name: t, value: links.filter(l => l.type === t).length }))} cx="50%" cy="50%" outerRadius={70} dataKey="value" label={({ name, percent }) => name + " " + (percent * 100).toFixed(0) + "%"} labelLine={false}>{LINK_TYPES.map((_, i) => <Cell key={i} fill={PC[(i + 3) % PC.length]}/>)}</Pie><Tooltip contentStyle={{ fontSize: 10 }}/></PieChart></CardContent></Card>')
a('      </div>')
a('    </div>')
a('  )')
a('')
a('  const tabs = [')
a('    { key: "dashboard", label: "Dashboard", icon: <Network className="w-3.5 h-3.5" />, content: tab0 },')
a('    { key: "nodes", label: "Network Nodes", icon: <Box className="w-3.5 h-3.5" />, content: tab1 },')
a('    { key: "links", label: "Network Links", icon: <GitBranch className="w-3.5 h-3.5" />, content: tab2 },')
a('    { key: "simulations", label: "Simulations", icon: <Cpu className="w-3.5 h-3.5" />, content: tab3 },')
a('    { key: "insights", label: "Insights", icon: <Eye className="w-3.5 h-3.5" />, content: tab4 }')
a('  ]')
a('')
a('  return (')
a('    <div className="space-y-4 p-4">')
a('      <PageHeader title="Supply Chain Digital Twin" description="Real-time digital replica of your entire supply chain network with simulation, risk analysis, and predictive optimization"/>')
a('      <div className="flex items-center gap-3 flex-wrap">')
a('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-cyan-100 dark:bg-cyan-900/30"><Radio className="w-3 h-3 text-cyan-600"/><span className="text-[10px] font-semibold text-cyan-700 dark:text-cyan-300">{activeSims} Simulations Running</span></div>')
a('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-100 dark:bg-emerald-900/30"><CheckCircle2 className="w-3 h-3 text-emerald-600"/><span className="text-[10px] font-semibold text-emerald-700 dark:text-emerald-300">{avgHealth}% Network Health</span></div>')
a('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-violet-100 dark:bg-violet-900/30"><Layers className="w-3 h-3 text-violet-600"/><span className="text-[10px] font-semibold text-violet-700 dark:text-violet-300">{nodes.length} Nodes | {links.length} Links</span></div>')
a('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-amber-100 dark:bg-amber-900/30"><RefreshCw className="w-3 h-3 text-amber-600"/><span className="text-[10px] font-semibold text-amber-700 dark:text-amber-300">Live Sync</span></div>')
a('      </div>')
a('      <Tabs value={tab} onValueChange={setTab}>')
a('        <TabsList className="bg-gradient-to-r from-cyan-500/10 to-violet-500/10 p-0.5 h-9">')
a('          {tabs.map(t => <TabsTrigger key={t.key} value={t.key} className="text-xs gap-1.5 data-[state=active]:bg-cyan-600 data-[state=active]:text-white">{t.icon}{t.label}</TabsTrigger>)}')
a('        </TabsList>')
a('        {tabs.map(t => tab === t.key && <div key={t.key} className="mt-3">{t.content}</div>)}')
a('      </Tabs>')
a('      <Sheet open={!!detail} onOpenChange={() => setDetail(null)}>')
a('        <SheetContent className="w-[420px] overflow-y-auto">')
a('          <SheetHeader><SheetTitle className="text-sm">Node Detail</SheetTitle></SheetHeader>')
a('          {detail && <div className="mt-4 space-y-3">')
a('            <div className="sdt-detail-header rounded-lg p-4 bg-gradient-to-br from-cyan-500 to-violet-600 text-white"><div className="text-lg font-bold">{String(detail.id)}</div><div className="text-xs opacity-80 mt-1">{String(detail.name || detail.type || "Record")}</div></div>')
a('            {Object.entries(detail).filter(([k]) => k !== "id").map(([k, v]) => <div key={k} className="flex items-center justify-between py-1.5 border-b"><span className="text-[10px] text-muted-foreground capitalize">{k.replace(/_/g, " ")}</span><span className="text-xs font-medium">{typeof v === "number" ? v.toLocaleString() : String(v)}</span></div>)}')
a('          </div>}')
a('        </SheetContent>')
a('      </Sheet>')
a('    </div>')
a('  )')
a('}')

with open(os.path.join(BASE, "supply-chain-digital-twin-view.tsx"), "w") as f:
    f.write("\n".join(lines_a))

print(f"Module A: supply-chain-digital-twin-view.tsx ({len(lines_a)} lines)")

# ============================================================
# MODULE B: Last Mile Optimization Pro
# ============================================================
lines_b = []
b = lines_b.append

b('"use client"')
b('import { useState, useMemo } from "react"')
b('import { AreaChart, Area, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts"')
b('import { MapPin, Truck, Package, Clock, TrendingUp, TrendingDown, BarChart3, Zap, AlertTriangle, CheckCircle2, Navigation, Users, Fuel, Route, Star, Phone, Home, Building2, Bike, ChevronRight, Search, ArrowUpDown } from "lucide-react"')
b('import { PageHeader } from "@/components/shared/page-header"')
b('import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar"')
b('import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb"')
b('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
b('import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"')
b('import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"')
b('import { Badge } from "@/components/ui/badge"')
b('')
b('// ── Constants ──')
b('const VEHICLE_TYPES = ["bike", "van", "truck", "e Rickshaw", "drones"] as const')
b('const VEHICLE_EMOJI: Record<string, string> = { bike: "\\U0001f3cd", van: "\\U0001f697", truck: "\\U0001f69a", "e Rickshaw": "\\u26a1", drones: "\\U0001f681" }')
b('const DELIVERY_STATUS = ["in_transit", "delivered", "failed", "rescheduled", "picked_up", "out_for_delivery"] as const')
b('const CITIES = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Hyderabad", "Kolkata", "Pune", "Ahmedabad"] as const')
b('const ZONES = ["Zone A", "Zone B", "Zone C", "Zone D", "Zone E"] as const')
b('const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] as const')
b('const TH = { pri: "#f59e0b", sec: "#ef4444", ok: "#059669", warn: "#d97706", err: "#dc2626" }')
b('const PC = ["#f59e0b", "#ef4444", "#059669", "#3b82f6", "#8b5cf6", "#06b6d4", "#ec4899", "#14b8a6"]')
b('')
b('// ── Utilities ──')
b('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297) * 233280; return x - Math.floor(x) }')
b('function ri(min: number, max: number, seed: number): number { return Math.floor(seededRandom(seed) * (max - min + 1)) + min }')
b('function pick<T>(arr: readonly T[], seed: number): T { return arr[Math.floor(seededRandom(seed) * arr.length)] }')
b('')
b('// ── Visual Components ──')
b('function VehicleBadge({ type }: { type: string }) {')
b('  const cols: Record<string, string> = { bike: "bg-amber-100 text-amber-700 dark:bg-amber-900/30", van: "bg-blue-100 text-blue-700 dark:bg-blue-900/30", truck: "bg-violet-100 text-violet-700 dark:bg-violet-900/30", "e Rickshaw": "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30", drones: "bg-sky-100 text-sky-700 dark:bg-sky-900/30" }')
b('  return <span className={"lmo-vehicle-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[type] || "bg-gray-100 text-gray-700")}>{VEHICLE_EMOJI[type] || "\\u2022"} {type}</span>')
b('}')
b('')
b('function DeliveryStatusBadge({ status }: { status: string }) {')
b('  const cols: Record<string, string> = { in_transit: "lmo-status-transit bg-blue-100 text-blue-700 dark:bg-blue-900/30", delivered: "lmo-status-delivered bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 shadow-[0_0_6px_rgba(5,150,105,0.3)]", failed: "lmo-status-failed bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_8px_rgba(220,38,38,0.4)]", rescheduled: "lmo-status-resched bg-amber-100 text-amber-700 dark:bg-amber-900/30", picked_up: "lmo-status-picked bg-violet-100 text-violet-700 dark:bg-violet-900/30", out_for_delivery: "lmo-status-ofd bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30" }')
b('  const icons: Record<string, React.ReactNode> = { in_transit: <Truck className="w-3 h-3" />, delivered: <CheckCircle2 className="w-3 h-3" />, failed: <AlertTriangle className="w-3 h-3" />, rescheduled: <Clock className="w-3 h-3" />, picked_up: <Package className="w-3 h-3" />, out_for_delivery: <Navigation className="w-3 h-3" /> }')
b('  return <span className={"lmo-delivery-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[status] || "")}>{icons[status]} {status.replace(/_/g, " ")}</span>')
b('}')
b('')
b('function SLABadge({ value }: { value: number }) {')
b('  const col = value >= 95 ? TH.ok : value >= 85 ? TH.warn : TH.err')
b('  return <span className="lmo-sla-badge inline-flex items-center gap-1 text-[10px] font-bold" style={{ color: col }}>{value}%</span>')
b('}')
b('')
b('function EffBar({ value }: { value: number }) {')
b('  const col = value >= 80 ? TH.ok : value >= 50 ? TH.warn : TH.err')
b('  return <div className="lmo-eff-bar flex items-center gap-1.5"><div className="w-16 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: value + "%", backgroundColor: col }}/></div><span className="text-[10px] font-bold" style={{ color: col }}>{value}%</span></div>')
b('}')
b('')
b('function TrendIndicator({ value }: { value: number }) {')
b('  const pos = value > 0')
b('  const col = pos ? TH.ok : TH.err')
b('  return <span className="lmo-trend inline-flex items-center gap-0.5 text-[10px] font-semibold" style={{ color: col }}>{pos ? <TrendingUp className="w-3 h-3" /> : <TrendingDown className="w-3 h-3" />}{Math.abs(value).toFixed(1)}%</span>')
b('}')
b('')
b('function CityBadge({ city }: { city: string }) {')
b('  return <span className="lmo-city-badge inline-flex items-center px-2 py-0.5 rounded text-[10px] font-medium bg-amber-50 text-amber-700 dark:bg-amber-900/20">{city}</span>')
b('}')
b('')
b('function ZoneBadge({ zone }: { zone: string }) {')
b('  return <span className="lmo-zone-badge inline-flex items-center px-2 py-0.5 rounded text-[10px] font-medium bg-violet-50 text-violet-700 dark:bg-violet-900/20">{zone}</span>')
b('}')
b('')
b('function KpiTile({ label, value, icon, trend, color }: { label: string; value: string; icon: React.ReactNode; trend: number; color: string }) {')
b('  return <Card className="lmo-kpi-tile glass-subtle hover:shadow-lg transition-shadow border-l-4" style={{ borderLeftColor: color }}><CardContent className="p-3"><div className="flex items-center justify-between"><span className="text-[10px] text-muted-foreground">{label}</span>{icon}</div><div className="text-xl font-bold mt-1">{value}</div><TrendIndicator value={trend}/></CardContent></Card>')
b('}')
b('')
b('function ValueTile({ label, value }: { label: string; value: string | number }) {')
b('  return <div className="lmo-value-tile text-center p-2 rounded-lg bg-gray-50 dark:bg-gray-800/50"><div className="text-sm font-bold">{value}</div><div className="text-[10px] text-muted-foreground">{label}</div></div>')
b('}')
b('')
b('function FuelTile({ liters, cost, saved }: { liters: number; cost: number; saved: number }) {')
b('  return <div className="lmo-fuel-tile p-2 rounded-lg border border-amber-200 dark:border-amber-800"><div className="flex items-center gap-1 mb-1"><Fuel className="w-3 h-3 text-amber-500"/><span className="text-[10px] font-medium">Fuel</span></div><div className="text-xs font-bold">{liters}L</div><div className="text-[10px] text-muted-foreground">{"\\u20b9"}{cost}</div>{saved > 0 && <div className="text-[10px] text-emerald-600 font-medium">Saved {"\\u20b9"}{saved}</div>}</div>')
b('}')
b('')
b('function StarRating({ value }: { value: number }) {')
b('  return <div className="lmo-star-rating flex items-center gap-0.5">{Array.from({ length: 5 }, (_, i) => <Star key={i} className={"w-3 h-3 " + (i < value ? "text-amber-400 fill-amber-400" : "text-gray-300")}/>)}</div>')
b('}')
b('')
b('function DeliveryRing({ delivered, total }: { delivered: number; total: number }) {')
b('  const pct = Math.round((delivered / total) * 100)')
b('  const r = 18, circ = 2 * Math.PI * r, offset = circ - (pct / 100) * circ')
b('  const col = pct >= 95 ? TH.ok : pct >= 85 ? TH.warn : TH.err')
b('  return <div className="lmo-delivery-ring flex flex-col items-center gap-1"><svg width={48} height={48} className="-rotate-90"><circle cx={24} cy={24} r={r} fill="none" stroke="currentColor" strokeWidth={3} className="text-gray-200 dark:text-gray-700"/><circle cx={24} cy={24} r={r} fill="none" stroke={col} strokeWidth={3} strokeDasharray={circ} strokeDashoffset={offset} strokeLinecap="round" className="transition-all"/></svg><span className="text-[10px] font-bold" style={{ color: col }}>{pct}%</span><span className="text-[9px] text-muted-foreground">{delivered}/{total}</span></div>')
b('}')
b('')
b('function CostTile({ label, value }: { label: string; value: number }) {')
b('  return <div className="lmo-cost-tile text-center p-2 rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800"><div className="text-xs font-bold text-red-600">{"\\u20b9"}{value.toLocaleString()}</div><div className="text-[10px] text-muted-foreground">{label}</div></div>')
b('}')
b('')
b('// ── Data Generators ──')
b('function genDeliveries() {')
b('  return Array.from({ length: 80 }, (_, i) => {')
b('    const st = pick(DELIVERY_STATUS, i * 3 + 1)')
b('    return {')
b('      id: "ORD-" + String(i + 1).padStart(6, "0"),')
b('      customer: pick(["Rahul Sharma", "Priya Patel", "Amit Kumar", "Sneha Gupta", "Vikram Singh", "Anjali Reddy", "Karan Mehta", "Divya Iyer", "Suresh Nair", "Meera Joshi", "Arjun Das", "Pooja Rao", "Rajesh Pillai", "Neha Bose", "Sunil Kulkarni"], i * 3 + 2),')
b('      city: pick(CITIES, i * 3 + 3),')
b('      zone: pick(ZONES, i * 3 + 4),')
b('      vehicle: pick(VEHICLE_TYPES, i * 3 + 5),')
b('      status: st,')
b('      eta: String(ri(5, 240, i + 7)) + " min",')
b('      distance: +(ri(1, 45, i + 11) / 10).toFixed(1),')
b('      cost: ri(30, 500, i + 13),')
b('      weight: ri(1, 50, i + 17),')
b('      priority: pick(["high", "medium", "low"], i + 19),')
b('      rating: ri(1, 5, i + 23),')
b('      attempts: st === "failed" ? ri(2, 5, i + 29) : 1,')
b('      driver: pick(["Ravi K.", "Suresh M.", "Manoj T.", "Arun D.", "Deepak S.", "Ramesh G.", "Vijay P.", "Ganesh B."], i + 31),')
b('      timestamp: "2026-07-" + String(ri(1, 30, i + 37)).padStart(2, "0") + " " + String(ri(8, 21, i + 41)).padStart(2, "0") + ":" + String(ri(0, 59, i + 43)).padStart(2, "0")')
b('    }')
b('  })')
b('}')
b('')
b('function genFleet() {')
b('  return Array.from({ length: 40 }, (_, i) => {')
b('    return {')
b('      id: "VH-" + String(i + 1).padStart(4, "0"),')
b('      type: pick(VEHICLE_TYPES, i * 3 + 1),')
b('      driver: pick(["Ravi K.", "Suresh M.", "Manoj T.", "Arun D.", "Deepak S.", "Ramesh G.", "Vijay P.", "Ganesh B.", "Kiran J.", "Prasad H."], i * 3 + 2),')
b('      city: pick(CITIES, i * 3 + 3),')
b('      zone: pick(ZONES, i * 3 + 4),')
b('      capacity: ri(10, 500, i + 7),')
b('      load: ri(5, 480, i + 11),')
b('      efficiency: ri(45, 98, i + 13),')
b('      fuelLevel: ri(10, 100, i + 17),')
b('      deliveries: ri(5, 60, i + 19),')
b('      delivered: ri(3, 58, i + 23),')
b('      avgTime: ri(15, 90, i + 29),')
b('      rating: +(ri(30, 50, i + 31) / 10).toFixed(1),')
b('      status: pick(["active", "active", "active", "break", "maintenance", "charging"], i + 37),')
b('      battery: pick(VEHICLE_TYPES, i + 1) === "bike" || pick(VEHICLE_TYPES, i + 1) === "e Rickshaw" ? ri(20, 100, i + 41) : null,')
b('      kmToday: ri(20, 200, i + 43)')
b('    }')
b('  })')
b('}')
b('')
b('function genRoutes() {')
b('  return Array.from({ length: 30 }, (_, i) => {')
b('    return {')
b('      id: "RT-" + String(i + 1).padStart(4, "0"),')
b('      name: pick(["Metro Express", "Suburban Sprint", "Highway Direct", "City Loop", "Rapid Rural", "Downtown Dash", "Airport Shuttle", "Market Run", "Industrial Route", "Coastal Connect", "Hill Station Link", "Campus Circuit", "Hospitality Line", "Mall Express", "Residential Route"], i * 3 + 1),')
b('      city: pick(CITIES, i * 3 + 2),')
b('      stops: ri(5, 25, i + 7),')
b('      distance: ri(10, 120, i + 11),')
b('      time: ri(30, 480, i + 13),')
b('      cost: ri(200, 3000, i + 17),')
b('      efficiency: ri(50, 98, i + 19),')
b('      deliveries: ri(10, 80, i + 23),')
b('      fuelUsed: ri(5, 50, i + 29),')
b('      co2Saved: ri(2, 30, i + 31),')
b('      status: pick(["active", "active", "active", "delayed", "cancelled"], i + 37),')
b('      vehicles: ri(2, 15, i + 41)')
b('    }')
b('  })')
b('}')
b('')
b('function genCharts() {')
b('  const daily = MO.map((m, i) => ({ month: m, deliveries: ri(2000, 12000, i + 101), delivered: ri(1800, 11500, i + 151), failed: ri(20, 500, i + 201), onTime: ri(1500, 11000, i + 251) }))')
b('  const vehicleDist = VEHICLE_TYPES.map((v, i) => ({ type: v, count: ri(5, 20, i + 301), avgEff: ri(60, 95, i + 351) }))')
b('  const zonePerf = ZONES.map((z, i) => ({ zone: z, sla: ri(80, 98, i + 401), cost: ri(100, 500, i + 451), satisfaction: ri(3, 5, i + 501) }))')
b('  const costTrend = MO.map((m, i) => ({ month: m, fuel: ri(50000, 200000, i + 551), labor: ri(80000, 300000, i + 601), penalty: ri(5000, 50000, i + 651) }))')
b('  return { daily, vehicleDist, zonePerf, costTrend }')
b('}')
b('')
b('// ── Main Component ──')
b('export default function LastMileOptimizationProView() {')
b('  const [tab, setTab] = useState("dashboard")')
b('  const [search, setSearch] = useState("")')
b('  const [detail, setDetail] = useState<Record<string, unknown> | null>(null)')
b('  const [sortField, setSortField] = useState("id")')
b('  const [sortDir, setSortDir] = useState<"asc" | "desc">("asc")')
b('')
b('  const deliveries = useMemo(() => genDeliveries(), [])')
b('  const fleet = useMemo(() => genFleet(), [])')
b('  const routes = useMemo(() => genRoutes(), [])')
b('  const charts = useMemo(() => genCharts(), [])')
b('')
b('  const toggleSort = (f: string) => { if (sortField === f) setSortDir(d => d === "asc" ? "desc" : "asc"); else { setSortField(f); setSortDir("asc") } }')
b('  const sortIcon = (f: string) => sortField === f ? (sortDir === "asc" ? "\\u2191" : "\\u2193") : ""')
b('')
b('  const filterDeliveries = useMemo(() => {')
b('    if (!search) return deliveries')
b('    const lq = search.toLowerCase()')
b('    return deliveries.filter(d => Object.values(d).some(v => typeof v === "string" && v.toLowerCase().includes(lq)))')
b('  }, [deliveries, search])')
b('')
b('  const sortedDeliveries = useMemo(() => [...filterDeliveries].sort((a, b) => { const va = a[sortField as keyof typeof a], vb = b[sortField as keyof typeof b]; if (va == null || vb == null) return 0; const cmp = String(va).localeCompare(String(vb), undefined, { numeric: true }); return sortDir === "asc" ? cmp : -cmp }), [filterDeliveries, sortField, sortDir])')
b('')
b('  const filterFleet = useMemo(() => {')
b('    if (!search) return fleet')
b('    const lq = search.toLowerCase()')
b('    return fleet.filter(f => Object.values(f).some(v => typeof v === "string" && v.toLowerCase().includes(lq)))')
b('  }, [fleet, search])')
b('')
b('  // Computed KPIs')
b('  const totalDelivered = deliveries.filter(d => d.status === "delivered").length')
b('  const totalFailed = deliveries.filter(d => d.status === "failed").length')
b('  const inTransit = deliveries.filter(d => d.status === "in_transit" || d.status === "out_for_delivery").length')
b('  const avgRating = +(fleet.reduce((s, f) => s + f.rating, 0) / fleet.length).toFixed(1)')
b('  const slaRate = Math.round((totalDelivered / Math.max(1, totalDelivered + totalFailed)) * 100)')
b('')
b('  const handleRefresh = () => { setSearch(""); setSortField("id"); setSortDir("asc") }')
b('')
b('  const [activeFilters, setActiveFilters] = useState<Record<string, string[]>>({})')
b('  const toggleFilter = (group: string, value: string) => {')
b('    setActiveFilters(prev => {')
b('      const cur = prev[group] || []')
b('      const next = cur.includes(value) ? cur.filter(v => v !== value) : [...cur, value]')
b('      if (next.length === 0) { const { [group]: _, ...rest } = prev; return rest }')
b('      return { ...prev, [group]: next }')
b('    })')
b('  }')
b('  const clearAllFilters = () => setActiveFilters({})')
b('  const totalActiveFilters = Object.values(activeFilters).reduce((s, v) => s + v.length, 0)')
b('')
b('  const deliveryFilterGroups = useMemo(() => {')
b('    const statusCounts: Record<string, number> = {}')
b('    const vehicleCounts: Record<string, number> = {}')
b('    const cityCounts: Record<string, number> = {}')
b('    deliveries.forEach(d => { statusCounts[d.status] = (statusCounts[d.status] || 0) + 1; vehicleCounts[d.vehicle] = (vehicleCounts[d.vehicle] || 0) + 1; cityCounts[d.city] = (cityCounts[d.city] || 0) + 1 })')
b('    return [')
b('      { key: "status", label: "Status", options: Object.entries(statusCounts).map(([value, count]) => ({ value: value.replace(/_/g, " "), count })).sort((a, b) => b.count - a.count) },')
b('      { key: "vehicle", label: "Vehicle", options: Object.entries(vehicleCounts).map(([value, count]) => ({ value, count })).sort((a, b) => b.count - a.count) },')
b('      { key: "city", label: "City", options: Object.entries(cityCounts).map(([value, count]) => ({ value, count })).sort((a, b) => b.count - a.count).slice(0, 8) }')
b('    ]')
b('  }, [deliveries])')
b('')
b('  const tab0 = (')
b('    <div className="space-y-4">')
b('      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">')
b('        <KpiTile label="Total Deliveries" value={deliveries.length.toString()} icon={<Package className="w-4 h-4 text-amber-500"/>} trend={12.5} color={TH.pri}/>')
b('        <KpiTile label="In Transit" value={inTransit.toString()} icon={<Truck className="w-4 h-4 text-blue-500"/>} trend={3.2} color="#3b82f6"/>')
b('        <KpiTile label="SLA Rate" value={slaRate + "%"} icon={<CheckCircle2 className="w-4 h-4 text-emerald-500"/>} trend={1.8} color={TH.ok}/>')
b('        <KpiTile label="Failed" value={totalFailed.toString()} icon={<AlertTriangle className="w-4 h-4 text-red-500"/>} trend={-8.3} color={TH.err}/>')
b('      </div>')
b('      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">')
b('        <DeliveryRing delivered={totalDelivered} total={deliveries.length}/>')
b('        <DeliveryRing delivered={fleet.reduce((s, f) => s + f.delivered, 0)} total={fleet.reduce((s, f) => s + f.deliveries, 0)}/>')
b('        <div className="lmo-fleet-summary text-center p-3"><div className="text-2xl font-bold text-amber-600">{fleet.length}</div><div className="text-[10px] text-muted-foreground">Active Vehicles</div><div className="text-xs text-emerald-600 font-medium mt-1">Rating: {avgRating}/5</div></div>')
b('        <div className="lmo-zone-summary text-center p-3"><div className="text-2xl font-bold text-violet-600">{routes.length}</div><div className="text-[10px] text-muted-foreground">Active Routes</div><div className="text-xs text-cyan-600 font-medium mt-1">{routes.reduce((s, r) => s + r.vehicles, 0)} vehicles assigned</div></div>')
b('      </div>')
b('      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">')
b('        <Card className="lmo-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Daily Delivery Volume</CardTitle></CardHeader><CardContent><AreaChart data={charts.daily} height={200}><CartesianGrid strokeDasharray="3 3" opacity={0.3}/><XAxis dataKey="month" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip contentStyle={{ fontSize: 10 }}/><Area type="monotone" dataKey="deliveries" stroke={TH.pri} fill={TH.pri} fillOpacity={0.2}/><Area type="monotone" dataKey="delivered" stroke={TH.ok} fill={TH.ok} fillOpacity={0.15}/><Line type="monotone" dataKey="failed" stroke={TH.err} strokeWidth={2} dot={{ r: 3 }}/></AreaChart></CardContent></Card>')
b('        <Card className="lmo-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Vehicle Distribution & Efficiency</CardTitle></CardHeader><CardContent><BarChart data={charts.vehicleDist} height={200}><CartesianGrid strokeDasharray="3 3" opacity={0.3}/><XAxis dataKey="type" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip contentStyle={{ fontSize: 10 }}/><Bar dataKey="count" fill={TH.pri} radius={[2, 2, 0, 0]}/><Bar dataKey="avgEff" fill={TH.ok} radius={[2, 2, 0, 0]}/></BarChart></CardContent></Card>')
b('        <Card className="lmo-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Zone Performance</CardTitle></CardHeader><CardContent><BarChart data={charts.zonePerf} height={200}><CartesianGrid strokeDasharray="3 3" opacity={0.3}/><XAxis dataKey="zone" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip contentStyle={{ fontSize: 10 }}/><Bar dataKey="sla" fill={TH.sec} radius={[2, 2, 0, 0]}/><Bar dataKey="satisfaction" fill={TH.ok} radius={[2, 2, 0, 0]}/></BarChart></CardContent></Card>')
b('        <Card className="lmo-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Cost Breakdown Trend</CardTitle></CardHeader><CardContent><LineChart data={charts.costTrend} height={200}><CartesianGrid strokeDasharray="3 3" opacity={0.3}/><XAxis dataKey="month" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip contentStyle={{ fontSize: 10 }}/><Line type="monotone" dataKey="fuel" stroke={TH.pri} strokeWidth={2} dot={{ r: 3 }}/><Line type="monotone" dataKey="labor" stroke={TH.sec} strokeWidth={2} strokeDasharray="5 5" dot={{ r: 3 }}/><Line type="monotone" dataKey="penalty" stroke={TH.err} strokeWidth={2} dot={{ r: 3 }}/></LineChart></CardContent></Card>')
b('      </div>')
b('    </div>')
b('  )')
b('')
b('  const tab1 = (')
b('    <div className="space-y-3">')
b('      <ModuleBreadcrumb items={[{ label: "Logistics" }, { label: "Last Mile" }, { label: "Deliveries" }]}/>')
b('      <SearchFilterToolbar searchQuery={search} onSearchChange={setSearch} onClearSearch={() => setSearch("")} activeFilters={activeFilters} filterGroups={deliveryFilterGroups} onToggleFilter={toggleFilter} onClearAllFilters={clearAllFilters} totalItems={deliveries.length} filteredCount={filterDeliveries.length} onRefresh={handleRefresh} placeholder="Search orders, customers, drivers..." />')
b('      <div className="rounded-lg border overflow-auto max-h-[calc(100vh-340px)]">')
b('        <table className="lmo-table w-full text-xs"><thead className="bg-amber-50 dark:bg-amber-900/20 sticky top-0"><tr><th className="p-2 text-left cursor-pointer select-none" onClick={() => toggleSort("id")}>Order ID {sortIcon("id")}</th><th className="p-2 text-left">Customer</th><th className="p-2 text-left">City</th><th className="p-2 text-left">Vehicle</th><th className="p-2 text-left">Status</th><th className="p-2 text-left">ETA</th><th className="p-2 text-right">Distance</th><th className="p-2 text-right">Cost</th><th className="p-2 text-left">Priority</th><th className="p-2 text-left">Driver</th></tr></thead>')
b('        <tbody>{sortedDeliveries.map(d => <tr key={d.id} className="lmo-table-row border-t hover:bg-amber-50/50 dark:hover:bg-amber-900/10 cursor-pointer" onClick={() => setDetail(d as unknown as Record<string, unknown>)}><td className="p-2 font-mono">{d.id}</td><td className="p-2 font-medium">{d.customer}</td><td className="p-2"><CityBadge city={d.city}/></td><td className="p-2"><VehicleBadge type={d.vehicle}/></td><td className="p-2"><DeliveryStatusBadge status={d.status}/></td><td className="p-2">{d.eta}</td><td className="p-2 text-right">{d.distance} km</td><td className="p-2 text-right">{"\\u20b9"}{d.cost}</td><td className="p-2"><span className={"lmo-priority-badge inline-flex px-1.5 py-0.5 rounded text-[10px] font-medium " + (d.priority === "high" ? "bg-red-100 text-red-700" : d.priority === "medium" ? "bg-amber-100 text-amber-700" : "bg-emerald-100 text-emerald-700")}>{d.priority}</span></td><td className="p-2 text-[10px]">{d.driver}</td></tr>)}</tbody></table>')
b('      </div>')
b('      <div className="flex items-center justify-between text-[10px] text-muted-foreground"><span>Showing {sortedDeliveries.length} of {deliveries.length} deliveries</span>{totalActiveFilters > 0 && <span>{totalActiveFilters} filters active</span>}</div>')
b('    </div>')
b('  )')
b('')
b('  const tab2 = (')
b('    <div className="space-y-4">')
b('      <ModuleBreadcrumb items={[{ label: "Logistics" }, { label: "Last Mile" }, { label: "Fleet" }]}/>')
b('      <SearchFilterToolbar searchQuery={search} onSearchChange={setSearch} onClearSearch={() => setSearch("")} activeFilters={activeFilters} filterGroups={[]} onToggleFilter={toggleFilter} onClearAllFilters={clearAllFilters} totalItems={fleet.length} filteredCount={filterFleet.length} onRefresh={handleRefresh} placeholder="Search vehicles, drivers..." />')
b('      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">')
b('        {filterFleet.map(f => (')
b('          <Card key={f.id} className={"lmo-fleet-card glass-subtle hover:shadow-lg transition-shadow " + (f.status === "active" ? "border-emerald-300 dark:border-emerald-700" : f.status === "maintenance" ? "border-amber-300 dark:border-amber-700" : "")}>')
b('            <CardContent className="p-3 space-y-2">')
b('              <div className="flex items-center justify-between"><span className="font-semibold text-xs">{f.id}</span><VehicleBadge type={f.type}/></div>')
b('              <div className="flex items-center justify-between text-[10px]"><span className="text-muted-foreground">Driver</span><span className="font-medium">{f.driver}</span></div>')
b('              <div className="flex items-center justify-between text-[10px]"><span className="text-muted-foreground">City</span><CityBadge city={f.city}/></div>')
b('              <div className="grid grid-cols-3 gap-1.5"><ValueTile label="Capacity" value={f.capacity}/><ValueTile label="Load" value={f.load}/><EffBar value={Math.round((f.load / f.capacity) * 100)}/></div>')
b('              <div className="flex items-center justify-between text-[10px]"><span className="text-muted-foreground">Efficiency</span><EffBar value={f.efficiency}/></div>')
b('              <div className="flex items-center justify-between text-[10px]"><span className="text-muted-foreground">Fuel</span><div className="flex items-center gap-1"><div className="w-10 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full" style={{ width: f.fuelLevel + "%", backgroundColor: f.fuelLevel <= 20 ? TH.err : f.fuelLevel <= 50 ? TH.warn : TH.ok }}/></div><span className="text-[10px]">{f.fuelLevel}%</span></div></div>')
b('              <div className="flex items-center justify-between text-[10px]"><span className="text-muted-foreground">Deliveries</span><DeliveryRing delivered={f.delivered} total={f.deliveries}/></div>')
b('              <div className="flex items-center justify-between text-[10px]"><span className="text-muted-foreground">Rating</span><StarRating value={Math.round(f.rating)}/></div>')
b('              <div className="flex items-center justify-between"><span className={"lmo-veh-status inline-flex px-1.5 py-0.5 rounded text-[10px] font-medium " + (f.status === "active" ? "bg-emerald-100 text-emerald-700" : f.status === "break" ? "bg-amber-100 text-amber-700" : f.status === "maintenance" ? "bg-red-100 text-red-700" : f.status === "charging" ? "bg-cyan-100 text-cyan-700" : "bg-gray-100 text-gray-600")}>{f.status}</span><span className="text-[10px] text-muted-foreground">{f.kmToday} km today</span></div>')
b('            </CardContent>')
b('          </Card>')
b('        ))}')
b('      </div>')
b('    </div>')
b('  )')
b('')
b('  const tab3 = (')
b('    <div className="space-y-3">')
b('      <ModuleBreadcrumb items={[{ label: "Logistics" }, { label: "Last Mile" }, { label: "Routes" }]}/>')
b('      <SearchFilterToolbar searchQuery={search} onSearchChange={setSearch} onClearSearch={() => setSearch("")} activeFilters={activeFilters} filterGroups={[]} onToggleFilter={toggleFilter} onClearAllFilters={clearAllFilters} totalItems={routes.length} filteredCount={routes.length} onRefresh={handleRefresh} placeholder="Search routes..." />')
b('      <div className="rounded-lg border overflow-auto max-h-[calc(100vh-340px)]">')
b('        <table className="lmo-table w-full text-xs"><thead className="bg-violet-50 dark:bg-violet-900/20 sticky top-0"><tr><th className="p-2 text-left cursor-pointer select-none" onClick={() => toggleSort("id")}>ID {sortIcon("id")}</th><th className="p-2 text-left">Route Name</th><th className="p-2 text-left">City</th><th className="p-2 text-right">Stops</th><th className="p-2 text-right">Distance</th><th className="p-2 text-right">Time</th><th className="p-2 text-left">Efficiency</th><th className="p-2 text-right">Deliveries</th><th className="p-2 text-left">CO2 Saved</th><th className="p-2 text-left">Status</th></tr></thead>')
b('        <tbody>{routes.map(r => <tr key={r.id} className="lmo-table-row border-t hover:bg-violet-50/50 dark:hover:bg-violet-900/10 cursor-pointer" onClick={() => setDetail(r as unknown as Record<string, unknown>)}><td className="p-2 font-mono">{r.id}</td><td className="p-2 font-medium">{r.name}</td><td className="p-2"><CityBadge city={r.city}/></td><td className="p-2 text-right">{r.stops}</td><td className="p-2 text-right">{r.distance} km</td><td className="p-2 text-right">{r.time} min</td><td className="p-2"><EffBar value={r.efficiency}/></td><td className="p-2 text-right">{r.deliveries}</td><td className="p-2"><span className="text-[10px] text-emerald-600 font-medium">{r.co2Saved} kg</span></td><td className="p-2"><span className={"lmo-route-status inline-flex px-1.5 py-0.5 rounded text-[10px] font-medium " + (r.status === "active" ? "bg-emerald-100 text-emerald-700" : r.status === "delayed" ? "bg-amber-100 text-amber-700" : r.status === "cancelled" ? "bg-red-100 text-red-700" : "bg-gray-100 text-gray-600")}>{r.status}</span></td></tr>)}</tbody></table>')
b('      </div>')
b('      <div className="text-[10px] text-muted-foreground text-right">{routes.length} routes</div>')
b('    </div>')
b('  )')
b('')
b('  const tab4 = (')
b('    <div className="space-y-4">')
b('      <ModuleBreadcrumb items={[{ label: "Logistics" }, { label: "Last Mile" }, { label: "Analytics" }]}/>')
b('      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">')
b('        <Card className="lmo-insight-card glass-subtle"><CardContent className="p-3 text-center"><div className="text-2xl font-bold text-amber-600">{"\\u20b9"}{deliveries.reduce((s, d) => s + d.cost, 0).toLocaleString()}</div><div className="text-[10px] text-muted-foreground mt-1">Total Delivery Cost</div></CardContent></Card>')
b('        <Card className="lmo-insight-card glass-subtle"><CardContent className="p-3 text-center"><div className="text-2xl font-bold text-emerald-600">{slaRate}%</div><div className="text-[10px] text-muted-foreground mt-1">SLA Achievement</div><div className="mt-2 h-1 rounded-full bg-gray-200"><div className="h-full rounded-full" style={{ width: slaRate + "%", backgroundColor: slaRate >= 95 ? TH.ok : TH.warn }}/></div></CardContent></Card>')
b('        <Card className="lmo-insight-card glass-subtle"><CardContent className="p-3 text-center"><div className="text-2xl font-bold text-blue-600">{fleet.filter(f => f.status === "active").length}</div><div className="text-[10px] text-muted-foreground mt-1">Vehicles Active Now</div></CardContent></Card>')
b('        <Card className="lmo-insight-card glass-subtle"><CardContent className="p-3 text-center"><div className="text-2xl font-bold text-violet-600">{routes.reduce((s, r) => s + r.co2Saved, 0)} kg</div><div className="text-[10px] text-muted-foreground mt-1">Total CO2 Saved</div></CardContent></Card>')
b('      </div>')
b('      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">')
b('        <Card className="lmo-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Delivery Status Distribution</CardTitle></CardHeader><CardContent><PieChart width={300} height={200}><Pie data={DELIVERY_STATUS.map((s) => ({ name: s.replace(/_/g, " "), value: deliveries.filter(d => d.status === s).length }))} cx="50%" cy="50%" outerRadius={70} dataKey="value" label={({ name, percent }) => name + " " + (percent * 100).toFixed(0) + "%"} labelLine={false}>{DELIVERY_STATUS.map((_, i) => <Cell key={i} fill={PC[i % PC.length]}/>)}</Pie><Tooltip contentStyle={{ fontSize: 10 }}/></PieChart></CardContent></Card>')
b('        <Card className="lmo-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Vehicle Type Distribution</CardTitle></CardHeader><CardContent><PieChart width={300} height={200}><Pie data={VEHICLE_TYPES.map((v) => ({ name: v, value: fleet.filter(f => f.type === v).length }))} cx="50%" cy="50%" outerRadius={70} dataKey="value" label={({ name, percent }) => name + " " + (percent * 100).toFixed(0) + "%"} labelLine={false}>{VEHICLE_TYPES.map((_, i) => <Cell key={i} fill={PC[(i + 2) % PC.length]}/>)}</Pie><Tooltip contentStyle={{ fontSize: 10 }}/></PieChart></CardContent></Card>')
b('      </div>')
b('    </div>')
b('  )')
b('')
b('  const tabs = [')
b('    { key: "dashboard", label: "Dashboard", icon: <BarChart3 className="w-3.5 h-3.5" />, content: tab0 },')
b('    { key: "deliveries", label: "Deliveries", icon: <Package className="w-3.5 h-3.5" />, content: tab1 },')
b('    { key: "fleet", label: "Fleet Manager", icon: <Truck className="w-3.5 h-3.5" />, content: tab2 },')
b('    { key: "routes", label: "Route Planner", icon: <Route className="w-3.5 h-3.5" />, content: tab3 },')
b('    { key: "analytics", label: "Analytics", icon: <TrendingUp className="w-3.5 h-3.5" />, content: tab4 }')
b('  ]')
b('')
b('  return (')
b('    <div className="space-y-4 p-4">')
b('      <PageHeader title="Last Mile Optimization Pro" description="End-to-end last mile delivery optimization with fleet management, route planning, real-time tracking, and SLA monitoring"/>')
b('      <div className="flex items-center gap-3 flex-wrap">')
b('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-amber-100 dark:bg-amber-900/30"><Truck className="w-3 h-3 text-amber-600"/><span className="text-[10px] font-semibold text-amber-700 dark:text-amber-300">{inTransit} In Transit</span></div>')
b('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-100 dark:bg-emerald-900/30"><CheckCircle2 className="w-3 h-3 text-emerald-600"/><span className="text-[10px] font-semibold text-emerald-700 dark:text-emerald-300">{slaRate}% SLA Rate</span></div>')
b('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-violet-100 dark:bg-violet-900/30"><Navigation className="w-3 h-3 text-violet-600"/><span className="text-[10px] font-semibold text-violet-700 dark:text-violet-300">{fleet.length} Vehicles | {routes.length} Routes</span></div>')
b('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-blue-100 dark:bg-blue-900/30"><Star className="w-3 h-3 text-blue-600"/><span className="text-[10px] font-semibold text-blue-700 dark:text-blue-300">{avgRating}/5 Rating</span></div>')
b('      </div>')
b('      <Tabs value={tab} onValueChange={setTab}>')
b('        <TabsList className="bg-gradient-to-r from-amber-500/10 to-red-500/10 p-0.5 h-9">')
b('          {tabs.map(t => <TabsTrigger key={t.key} value={t.key} className="text-xs gap-1.5 data-[state=active]:bg-amber-600 data-[state=active]:text-white">{t.icon}{t.label}</TabsTrigger>)}')
b('        </TabsList>')
b('        {tabs.map(t => tab === t.key && <div key={t.key} className="mt-3">{t.content}</div>)}')
b('      </Tabs>')
b('      <Sheet open={!!detail} onOpenChange={() => setDetail(null)}>')
b('        <SheetContent className="w-[420px] overflow-y-auto">')
b('          <SheetHeader><SheetTitle className="text-sm">Delivery Detail</SheetTitle></SheetHeader>')
b('          {detail && <div className="mt-4 space-y-3">')
b('            <div className="lmo-detail-header rounded-lg p-4 bg-gradient-to-br from-amber-500 to-red-600 text-white"><div className="text-lg font-bold">{String(detail.id)}</div><div className="text-xs opacity-80 mt-1">{String(detail.customer || detail.name || "Record")}</div></div>')
b('            {Object.entries(detail).filter(([k]) => k !== "id").map(([k, v]) => <div key={k} className="flex items-center justify-between py-1.5 border-b"><span className="text-[10px] text-muted-foreground capitalize">{k.replace(/_/g, " ")}</span><span className="text-xs font-medium">{typeof v === "number" ? v.toLocaleString() : String(v)}</span></div>)}')
b('          </div>}')
b('        </SheetContent>')
b('      </Sheet>')
b('    </div>')
b('  )')
b('}')

with open(os.path.join(BASE, "last-mile-optimization-pro-view.tsx"), "w") as f:
    f.write("\n".join(lines_b))

print(f"Module B: last-mile-optimization-pro-view.tsx ({len(lines_b)} lines)")
print("Done generating both R262 modules.")
