#!/usr/bin/env python3
"""R265: Fleet Telematics Pro + Dynamic Pricing Engine module generator"""
import os

BASE = "/home/z/my-project/src/components/modules"

# Helper to write a list of lines to a file
def write_lines(filepath, lines):
    with open(filepath, "w") as f:
        f.write("\n".join(lines))
    print(f"Generated {filepath}: {len(lines)} lines")


# ═══════════════════════════════════════════════════════════
# MODULE 1: Fleet Telematics Pro
# ═══════════════════════════════════════════════════════════
ftp = []
a = ftp.append

a('"use client"')
a('import { useState, useMemo } from "react"')
a('import { AreaChart, Area, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts"')
a('import { Fuel, Thermometer, Zap, AlertTriangle, CheckCircle2, BarChart3, TrendingUp, TrendingDown, Speed, MapPin, Package, Timer, ArrowUpDown, Radio, Battery, Gauge, Wrench, Satellite } from "lucide-react"')
a('import { PageHeader } from "@/components/shared/page-header"')
a('import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar"')
a('import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb"')
a('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
a('import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"')
a('import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"')
a('import { Badge } from "@/components/ui/badge"')
a('')
a('const VEHICLE_TYPES = ["truck", "van", "refrigerated", "tanker", "flatbed", "pickup"] as const')
a('const VEHICLE_EMOJI: Record<string, string> = { truck: "\U0001f69a", van: "\U0001f490", refrigerated: "\u2744\ufe0f", tanker: "\U0001f6e2\ufe0f", flatbed: "\U0001f4e6", pickup: "\U0001f3ce\ufe0f" }')
a('const DRIVER_STATUS = ["on_route", "resting", "loading", "unloading", "available", "offline", "idle"] as const')
a('const ALERT_SEV = ["critical", "warning", "info"] as const')
a('const FUEL_TYPES = ["diesel", "petrol", "cng", "electric", "hybrid"] as const')
a('const CITIES = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Hyderabad", "Kolkata", "Pune", "Ahmedabad"] as const')
a('const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] as const')
a('const TH = { pri: "#3b82f6", sec: "#f59e0b", ok: "#059669", warn: "#d97706", err: "#dc2626" }')
a('const PC = ["#3b82f6", "#f59e0b", "#059669", "#dc2626", "#8b5cf6", "#06b6d4", "#ec4899", "#14b8a6"]')
a('')
a('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297) * 233280; return x - Math.floor(x) }')
a('function ri(min: number, max: number, seed: number): number { return Math.floor(seededRandom(seed) * (max - min + 1)) + min }')
a('function pick<T>(arr: readonly T[], seed: number): T { return arr[Math.floor(seededRandom(seed) * arr.length)] }')
a('')
a('function VehicleTypeBadge({ type }: { type: string }) {')
a('  const cols: Record<string, string> = { truck: "bg-blue-100 text-blue-700 dark:bg-blue-900/30", van: "bg-violet-100 text-violet-700 dark:bg-violet-900/30", refrigerated: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30", tanker: "bg-red-100 text-red-700 dark:bg-red-900/30", flatbed: "bg-amber-100 text-amber-700 dark:bg-amber-900/30", pickup: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30" }')
a('  return <span className={"ftp-vehicle-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[type] || "bg-gray-100 text-gray-700")}>{VEHICLE_EMOJI[type] || "\u2022"} {type}</span>')
a('}')
a('')
a('function FuelTypeBadge({ type }: { type: string }) {')
a('  const cols: Record<string, string> = { diesel: "bg-amber-100 text-amber-700 dark:bg-amber-900/30", petrol: "bg-red-100 text-red-700 dark:bg-red-900/30", cng: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30", electric: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30", hybrid: "bg-violet-100 text-violet-700 dark:bg-violet-900/30" }')
a('  const icons: Record<string, React.ReactNode> = { diesel: <Fuel className="w-3 h-3" />, petrol: <Fuel className="w-3 h-3" />, cng: <Zap className="w-3 h-3" />, electric: <Battery className="w-3 h-3" />, hybrid: <Gauge className="w-3 h-3" /> }')
a('  return <span className={"ftp-fuel-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[type] || "")}>{icons[type]} {type}</span>')
a('}')
a('')
a('function DriverStatusBadge({ status }: { status: string }) {')
a('  const cols: Record<string, string> = { on_route: "ftp-onroute bg-blue-100 text-blue-700 dark:bg-blue-900/30 shadow-[0_0_6px_rgba(59,130,246,0.3)]", resting: "bg-gray-100 text-gray-600", loading: "bg-violet-100 text-violet-700", unloading: "bg-amber-100 text-amber-700", available: "ftp-avail bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 shadow-[0_0_6px_rgba(5,150,105,0.3)]", offline: "bg-red-100 text-red-700", idle: "bg-gray-200 text-gray-500" }')
a('  return <span className={"ftp-status-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[status] || "")}>{status.replace(/_/g, " ")}</span>')
a('}')
a('')
a('function SevBadge({ severity }: { severity: string }) {')
a('  const cols: Record<string, string> = { critical: "ftp-critical bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_8px_rgba(220,38,38,0.4)]", warning: "bg-amber-100 text-amber-700", info: "bg-blue-100 text-blue-700" }')
a('  const icons: Record<string, React.ReactNode> = { critical: <AlertTriangle className="w-3 h-3" />, warning: <AlertTriangle className="w-3 h-3" />, info: <Radio className="w-3 h-3" /> }')
a('  return <span className={"ftp-sev-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[severity] || "")}>{icons[severity]} {severity}</span>')
a('}')
a('')
a('function FuelBar({ value, capacity }: { value: number; capacity: number }) {')
a('  const pct = Math.round((value / capacity) * 100); const col = pct <= 20 ? TH.err : pct <= 40 ? TH.warn : TH.ok')
a('  return <div className="ftp-fuel-bar flex items-center gap-1.5"><div className="w-16 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: pct + "%", backgroundColor: col }}/></div><span className="text-[10px] font-bold" style={{ color: col }}>{pct}%</span></div>')
a('}')
a('')
a('function SpeedGauge({ value, max }: { value: number; max: number }) {')
a('  const pct = Math.round((value / max) * 100); const col = pct >= 90 ? TH.err : pct >= 70 ? TH.warn : TH.ok')
a('  return <div className="ftp-speed-gauge flex items-center gap-1.5"><div className="w-16 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: pct + "%", backgroundColor: col }}/></div><span className="text-[10px] font-bold" style={{ color: col }}>{value}</span></div>')
a('}')
a('')
a('function TempBadge({ temp }: { temp: number }) {')
a('  const col = temp >= 95 ? TH.err : temp >= 80 ? TH.warn : TH.ok')
a('  return <span className="ftp-temp-badge inline-flex items-center gap-0.5 text-[10px] font-bold" style={{ color: col }}><Thermometer className="w-3 h-3"/>{temp}&deg;C</span>')
a('}')
a('')
a('function TrendIndicator({ value }: { value: number }) {')
a('  const pos = value > 0; const col = pos ? TH.ok : TH.err')
a('  return <span className="ftp-trend inline-flex items-center gap-0.5 text-[10px] font-semibold" style={{ color: col }}>{pos ? <TrendingUp className="w-3 h-3" /> : <TrendingDown className="w-3 h-3" />}{Math.abs(value).toFixed(1)}%</span>')
a('}')
a('')
a('function CityBadge({ city }: { city: string }) { return <span className="ftp-city-badge inline-flex items-center px-2 py-0.5 rounded text-[10px] font-medium bg-blue-50 text-blue-700 dark:bg-blue-900/20">{city}</span> }')
a('')
a('function KpiTile({ label, value, icon, trend, color }: { label: string; value: string; icon: React.ReactNode; trend: number; color: string }) { return <Card className="ftp-kpi-tile glass-subtle hover:shadow-lg transition-shadow border-l-4" style={{ borderLeftColor: color }}><CardContent className="p-3"><div className="flex items-center justify-between"><span className="text-[10px] text-muted-foreground">{label}</span>{icon}</div><div className="text-xl font-bold mt-1">{value}</div><TrendIndicator value={trend}/></CardContent></Card> }')
a('')
a('function ValueTile({ label, value }: { label: string; value: string | number }) { return <div className="ftp-value-tile text-center p-2 rounded-lg bg-gray-50 dark:bg-gray-800/50"><div className="text-sm font-bold">{value}</div><div className="text-[10px] text-muted-foreground">{label}</div></div> }')
a('')
a('function HealthRing({ value, label }: { value: number; label: string }) { const col = value >= 90 ? TH.ok : value >= 70 ? TH.warn : TH.err; const r = 18, circ = 2 * Math.PI * r, offset = circ - (value / 100) * circ; return <div className="ftp-health-ring flex flex-col items-center gap-1"><svg width={48} height={48} className="-rotate-90"><circle cx={24} cy={24} r={r} fill="none" stroke="currentColor" strokeWidth={3} className="text-gray-200 dark:text-gray-700"/><circle cx={24} cy={24} r={r} fill="none" stroke={col} strokeWidth={3} strokeDasharray={circ} strokeDashoffset={offset} strokeLinecap="round" className="transition-all"/></svg><span className="text-[10px] font-bold" style={{ color: col }}>{value}%</span><span className="text-[9px] text-muted-foreground">{label}</span></div> }')
a('')
a('function genVehicles() {')
a('  return Array.from({ length: 60 }, (_, i) => ({')
a('    id: "VH-" + String(i + 1).padStart(4, "0"),')
a('    type: pick(VEHICLE_TYPES, i * 3 + 1),')
a('    reg: pick(["MH", "DL", "KA", "TN", "TS", "WB", "GJ", "UP"], i * 3 + 2) + String(ri(1, 99, i * 3 + 3)).padStart(2, "0") + " " + String.fromCharCode(65 + ri(0, 25, i + 4)) + " " + String.fromCharCode(65 + ri(0, 25, i + 5)) + String.fromCharCode(65 + ri(0, 25, i + 6)),')
a('    driver: pick(["Raj Kumar", "Amit Singh", "Priya Patel", "Suresh Yadav", "Deepak Sharma", "Manoj Tiwari", "Kavita Devi", "Ravi Verma"], i + 7),')
a('    fuelType: pick(FUEL_TYPES, i + 15),')
a('    fuel: ri(5, 120, i + 23),')
a('    fuelCap: pick([60, 80, 100, 120, 150], i + 31),')
a('    speed: ri(0, 120, i + 37),')
a('    maxSpeed: pick([80, 100, 120, 140], i + 43),')
a('    engineTemp: ri(70, 110, i + 47),')
a('    tirePressure: ri(28, 42, i + 53),')
a('    odometer: ri(10000, 200000, i + 59),')
a('    city: pick(CITIES, i + 67),')
a('    status: pick(DRIVER_STATUS, i + 75),')
a('    lastPing: String(ri(0, 59, i + 83)) + "m ago",')
a('    battery: ri(60, 100, i + 89),')
a('    acOn: ri(0, 1, i + 91) === 1')
a('  }))')
a('}')
a('')
a('function genAlerts() {')
a('  return Array.from({ length: 30 }, (_, i) => ({')
a('    id: "ALT-" + String(i + 1).padStart(4, "0"),')
a('    vehicle: "VH-" + String(ri(1, 60, i + 7)).padStart(4, "0"),')
a('    severity: pick(ALERT_SEV, i + 13),')
a('    type: pick(["Over Speed", "Low Fuel", "Engine Overheat", "Tire Low", "Geofence Exit", "Harsh Braking", "Idling Too Long", "Battery Drain", "AC Failure", "Fuel Theft Alert"], i + 19),')
a('    message: pick(["Vehicle exceeded speed limit on NH-48", "Fuel level below 15% threshold", "Engine temperature above 105C", "Tire pressure below 30 PSI", "Vehicle exited designated geofence", "Harsh braking detected at junction", "Vehicle idling for over 30 minutes", "Battery voltage dropped below 11V", "AC compressor malfunction detected", "Possible fuel siphoning detected"], i + 29),')
a('    city: pick(CITIES, i + 39),')
a('    timestamp: "2026-07-30 " + String(ri(0, 23, i + 47)).padStart(2, "0") + ":" + String(ri(0, 59, i + 53)).padStart(2, "0"),')
a('    resolved: ri(0, 1, i + 59) === 1')
a('  }))')
a('}')
a('')
a('function genCharts() {')
a('  const fuel = MO.map((m, i) => ({ month: m, consumed: ri(800, 3000, i + 101), cost: ri(50000, 200000, i + 151), efficiency: ri(4, 12, i + 201) }))')
a('  const typeDist = VEHICLE_TYPES.map((t, i) => ({ type: t, count: ri(5, 20, i + 301), avgKm: ri(50, 300, i + 351) }))')
a('  const alertTrend = MO.map((m, i) => ({ month: m, critical: ri(2, 15, i + 401), warning: ri(10, 40, i + 451), info: ri(20, 60, i + 501) }))')
a('  return { fuel, typeDist, alertTrend }')
a('}')
a('')
a('export function FleetTelematicsProView() {')
a('  const [tab, setTab] = useState("dashboard")')
a('  const [sortCol, setSortCol] = useState<string | null>(null)')
a('  const [sortDir, setSortDir] = useState<"asc" | "desc">("asc")')
a('  const { searchQuery, setSearchQuery, onClearSearch, activeFilters, onToggleFilter, onClearAllFilters, filteredData } = useSearchFilter({ initialData: genVehicles() })')
a('  const { searchQuery: aq, setSearchQuery: setAq, onClearSearch: cAq, activeFilters: af, onToggleFilter: tAf, onClearAllFilters: clAf, filteredData: fAlerts } = useSearchFilter({ initialData: genAlerts() })')
a('  const alerts = fAlerts')
a('  const vehicles = filteredData')
a('  const charts = useMemo(() => genCharts(), [])')
a('  const sortedVehicles = useMemo(() => {')
a('    if (!sortCol) return vehicles')
a('    return [...vehicles].sort((a: any, b: any) => { const av = a[sortCol], bv = b[sortCol]; const cmp = typeof av === "string" ? av.localeCompare(bv) : av - bv; return sortDir === "asc" ? cmp : -cmp })')
a('  }, [vehicles, sortCol, sortDir])')
a('  const toggleSort = (col: string) => { if (sortCol === col) { setSortDir(d => d === "asc" ? "desc" : "asc") } else { setSortCol(col); setSortDir("asc") } }')
a('')
a('  const vehicleFilterGroups = [')
a('    { key: "type", label: "Type", options: VEHICLE_TYPES.map(t => ({ value: t, label: t })) },')
a('    { key: "fuelType", label: "Fuel", options: FUEL_TYPES.map(f => ({ value: f, label: f })) },')
a('    { key: "status", label: "Status", options: DRIVER_STATUS.map(s => ({ value: s, label: s.replace(/_/g, " ") })) },')
a('    { key: "city", label: "City", options: CITIES.map(c => ({ value: c, label: c })) }')
a('  ]')
a('')
a('  const alertFilterGroups = [')
a('    { key: "severity", label: "Severity", options: ALERT_SEV.map(s => ({ value: s, label: s })) }')
a('  ]')
a('')
a('  return <div className="space-y-4 p-4">')
a('    <PageHeader title="Fleet Telematics Pro" description="Real-time vehicle tracking, fuel monitoring and driver analytics"/>')
a('')
a('    <Tabs value={tab} onValueChange={setTab}>')
a('      <TabsList className="grid grid-cols-5 w-full ftp-tabs">')
a('        <TabsTrigger value="dashboard"><BarChart3 className="w-3 h-3 mr-1"/>Dashboard</TabsTrigger>')
a('        <TabsTrigger value="vehicles"><Satellite className="w-3 h-3 mr-1"/>Vehicles</TabsTrigger>')
a('        <TabsTrigger value="alerts"><AlertTriangle className="w-3 h-3 mr-1"/>Alerts</TabsTrigger>')
a('        <TabsTrigger value="fuel"><Fuel className="w-3 h-3 mr-1"/>Fuel Analytics</TabsTrigger>')
a('        <TabsTrigger value="insights"><TrendingUp className="w-3 h-3 mr-1"/>Insights</TabsTrigger>')
a('      </TabsList>')
a('')
a('      <TabsContent value="dashboard" className="space-y-4">')
a('        <div className="grid grid-cols-4 gap-3">')
a('          <KpiTile label="Active Vehicles" value={String(vehicles.filter((v: any) => v.status === "on_route").length)} icon={<Satellite className="w-4 h-4" style={{ color: TH.pri }}/>} trend={12.5} color={TH.pri}/>')
a('          <KpiTile label="Avg Fuel Level" value="68%" icon={<Fuel className="w-4 h-4" style={{ color: TH.sec }}/>} trend={-3.2} color={TH.sec}/>')
a('          <KpiTile label="Open Alerts" value={String(alerts.filter((a: any) => !a.resolved).length)} icon={<AlertTriangle className="w-4 h-4" style={{ color: TH.err }}/>} trend={8.1} color={TH.err}/>')
a('          <KpiTile label="Fleet Efficiency" value="87%" icon={<Gauge className="w-4 h-4" style={{ color: TH.ok }}/>} trend={5.4} color={TH.ok}/>')
a('        </div>')
a('        <div className="grid grid-cols-4 gap-3">')
a('          <HealthRing value={92} label="Uptime"/>')
a('          <HealthRing value={78} label="Fuel Opt"/>')
a('          <HealthRing value={95} label="GPS Acc"/>')
a('          <HealthRing value={64} label="Maint"/>')
a('        </div>')
a('        <div className="grid grid-cols-3 gap-3">')
a('          <Card className="ftp-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Monthly Fuel Consumption</CardTitle></CardHeader><CardContent className="p-2"><AreaChart data={charts.fuel} height={180}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" fontSize={10}/><YAxis fontSize={10}/><Tooltip contentStyle={{ fontSize: 11 }}/><Area type="monotone" dataKey="consumed" stroke={TH.pri} fill={TH.pri} fillOpacity={0.2}/></AreaChart></CardContent></Card>')
a('          <Card className="ftp-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Vehicle Type Distribution</CardTitle></CardHeader><CardContent className="p-2"><BarChart data={charts.typeDist} height={180}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="type" fontSize={9}/><YAxis fontSize={10}/><Tooltip contentStyle={{ fontSize: 11 }}/><Bar dataKey="count" fill={TH.sec}/></BarChart></CardContent></Card>')
a('          <Card className="ftp-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Alert Trend</CardTitle></CardHeader><CardContent className="p-2"><LineChart data={charts.alertTrend} height={180}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" fontSize={10}/><YAxis fontSize={10}/><Tooltip contentStyle={{ fontSize: 11 }}/><Line type="monotone" dataKey="critical" stroke={TH.err}/><Line type="monotone" dataKey="warning" stroke={TH.warn}/><Line type="monotone" dataKey="info" stroke={TH.pri}/></LineChart></CardContent></Card>')
a('        </div>')
a('      </TabsContent>')
a('')
a('      <TabsContent value="vehicles" className="space-y-4">')
a('        <ModuleBreadcrumb items={[{ label: "Dashboard" }, { label: "Vehicles" }]}/>')
a('        <SearchFilterToolbar searchQuery={searchQuery} onSearchChange={setSearchQuery} onClearSearch={onClearSearch} activeFilters={activeFilters} filterGroups={vehicleFilterGroups} onToggleFilter={onToggleFilter} onClearAllFilters={onClearAllFilters} totalItems={vehicles.length} filteredCount={vehicles.length} onRefresh={() => {}} placeholder="Search vehicles..."/>')
a('        <Card className="ftp-table-card"><CardContent className="p-2"><div className="overflow-x-auto"><table className="w-full text-[11px]"><thead><tr className="border-b ftp-table-header"><th className="p-1.5 text-left cursor-pointer hover:bg-gray-100" onClick={() => toggleSort("id")}>ID <ArrowUpDown className="w-3 h-3 inline"/></th><th className="p-1.5 text-left">Type</th><th className="p-1.5 text-left">Registration</th><th className="p-1.5 text-left">Driver</th><th className="p-1.5 text-left">Fuel</th><th className="p-1.5 text-left">Speed</th><th className="p-1.5 text-left">Engine</th><th className="p-1.5 text-left">Status</th><th className="p-1.5 text-left">City</th><th className="p-1.5 text-left">Last Ping</th></tr></thead><tbody>')
a('          {sortedVehicles.map((v: any) => <tr key={v.id} className="border-b hover:bg-blue-50/50 dark:hover:bg-blue-900/10 ftp-table-row"><td className="p-1.5 font-mono">{v.id}</td><td className="p-1.5"><VehicleTypeBadge type={v.type}/></td><td className="p-1.5 font-medium">{v.reg}</td><td className="p-1.5">{v.driver}</td><td className="p-1.5"><FuelBar value={v.fuel} capacity={v.fuelCap}/></td><td className="p-1.5"><SpeedGauge value={v.speed} max={v.maxSpeed}/></td><td className="p-1.5"><TempBadge temp={v.engineTemp}/></td><td className="p-1.5"><DriverStatusBadge status={v.status}/></td><td className="p-1.5"><CityBadge city={v.city}/></td><td className="p-1.5 text-muted-foreground">{v.lastPing}</td></tr>)}')
a('          </tbody></table></div></CardContent></Card>')
a('      </TabsContent>')
a('')
a('      <TabsContent value="alerts" className="space-y-4">')
a('        <ModuleBreadcrumb items={[{ label: "Dashboard" }, { label: "Alerts" }]}/>')
a('        <SearchFilterToolbar searchQuery={aq} onSearchChange={setAq} onClearSearch={cAq} activeFilters={af} filterGroups={alertFilterGroups} onToggleFilter={tAf} onClearAllFilters={clAf} totalItems={alerts.length} filteredCount={alerts.length} onRefresh={() => {}} placeholder="Search alerts..."/>')
a('        <div className="grid grid-cols-3 gap-3">')
a('          {alerts.map((a: any) => <Card key={a.id} className={"ftp-alert-card p-3 " + (a.severity === "critical" && !a.resolved ? "ftp-alert-critical" : "")}><div className="flex items-center justify-between mb-2"><SevBadge severity={a.severity}/><span className="text-[9px] text-muted-foreground">{a.timestamp}</span></div><div className="text-[11px] font-semibold mb-1">{a.type}</div><div className="text-[10px] text-muted-foreground mb-2">{a.message}</div><div className="flex items-center justify-between"><span className="text-[10px] font-mono">{a.vehicle}</span><span className="text-[10px]">{a.resolved ? <CheckCircle2 className="w-3 h-3 text-emerald-500 inline"/> : <span className="text-red-500 font-semibold">Open</span>}</span></div></Card>)}')
a('        </div>')
a('      </TabsContent>')
a('')
a('      <TabsContent value="fuel" className="space-y-4">')
a('        <ModuleBreadcrumb items={[{ label: "Dashboard" }, { label: "Fuel Analytics" }]}/>')
a('        <div className="grid grid-cols-4 gap-3">')
a('          <ValueTile label="Diesel Cost (MTD)" value="\u20b91.2L"/>')
a('          <ValueTile label="Total Liters" value="18,450L"/>')
a('          <ValueTile label="Avg KMPL" value="8.2"/>')
a('          <ValueTile label="Fuel Theft Alerts" value="3"/>')
a('        </div>')
a('        <div className="grid grid-cols-2 gap-3">')
a('          <Card className="ftp-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Fuel Cost Trend</CardTitle></CardHeader><CardContent className="p-2"><AreaChart data={charts.fuel} height={200}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" fontSize={10}/><YAxis fontSize={10}/><Tooltip contentStyle={{ fontSize: 11 }}/><Area type="monotone" dataKey="cost" stroke={TH.err} fill={TH.err} fillOpacity={0.15}/></AreaChart></CardContent></Card>')
a('          <Card className="ftp-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Fuel Type Distribution</CardTitle></CardHeader><CardContent className="p-2"><PieChart height={200}><Pie data={FUEL_TYPES.map((f, i) => ({ name: f, value: ri(10, 50, i + 601) }))} cx="50%" cy="50%" outerRadius={60} dataKey="value" label><Cell fill={PC[0]}/><Cell fill={PC[1]}/><Cell fill={PC[2]}/><Cell fill={PC[3]}/><Cell fill={PC[4]}/></Pie><Tooltip contentStyle={{ fontSize: 11 }}/></PieChart></CardContent></Card>')
a('        </div>')
a('      </TabsContent>')
a('')
a('      <TabsContent value="insights" className="space-y-4">')
a('        <ModuleBreadcrumb items={[{ label: "Dashboard" }, { label: "Insights" }]}/>')
a('        <div className="grid grid-cols-2 gap-3">')
a('          <Card className="ftp-insight-card p-4"><div className="text-xs font-semibold mb-2 flex items-center gap-1"><AlertTriangle className="w-3 h-3 text-red-500"/>Over-Speeding Hotspots</div><div className="text-[10px] text-muted-foreground">12 vehicles exceeded 100 km/h in last 24h. NH-48 near Mumbai and Delhi-Gurgaon expressway are the top zones for speed violations.</div></Card>')
a('          <Card className="ftp-insight-card p-4"><div className="text-xs font-semibold mb-2 flex items-center gap-1"><Fuel className="w-3 h-3 text-amber-500"/>Fuel Optimization Opportunity</div><div className="text-[10px] text-muted-foreground">Route optimization could save 15% fuel. 8 vehicles have consistently high idle times. CNG fleet shows 22% lower cost per km than diesel.</div></Card>')
a('          <Card className="ftp-insight-card p-4"><div className="text-xs font-semibold mb-2 flex items-center gap-1"><Thermometer className="w-3 h-3 text-orange-500"/>Preventive Maintenance</div><div className="text-[10px] text-muted-foreground">5 vehicles show engine temp above 95C regularly. Schedule service for VH-0012, VH-0023, VH-0034, VH-0045, VH-0056 to prevent breakdowns.</div></Card>')
a('          <Card className="ftp-insight-card p-4"><div className="text-xs font-semibold mb-2 flex items-center gap-1"><Gauge className="w-3 h-3 text-emerald-500"/>Fleet Performance</div><div className="text-[10px] text-muted-foreground">Electric vehicles have 95% uptime vs 78% for diesel. Refrigerated trucks show 12% higher maintenance cost. Van fleet is most cost-efficient.</div></Card>')
a('        </div>')
a('      </TabsContent>')
a('    </Tabs>')
a('  </div>')
a('}')

write_lines(os.path.join(BASE, "fleet-telematics-pro-view.tsx"), ftp)


# ═══════════════════════════════════════════════════════════
# MODULE 2: Dynamic Pricing Engine
# ═══════════════════════════════════════════════════════════
dpe = []
a = dpe.append

a('"use client"')
a('import { useState, useMemo } from "react"')
a('import { AreaChart, Area, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts"')
a('import { DollarSign, TrendingUp, TrendingDown, Zap, AlertTriangle, CheckCircle2, BarChart3, Calculator, ArrowUpDown, Tag, Target, Package, Truck, Clock, Star, ArrowRightLeft, ShieldCheck, Percent } from "lucide-react"')
a('import { PageHeader } from "@/components/shared/page-header"')
a('import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar"')
a('import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb"')
a('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
a('import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"')
a('import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"')
a('import { Badge } from "@/components/ui/badge"')
a('')
a('const SERVICE_TYPES = ["ftl", "ptl", "express", "air", "surface", "rail", "last_mile", "cold_chain"] as const')
a('const SERVICE_EMOJI: Record<string, string> = { ftl: "\U0001f69a", ptl: "\U0001f4e6", express: "\u26a1", air: "\u2708\ufe0f", surface: "\U0001f6d1", rail: "\U0001f682", last_mile: "\U0001f3ce\ufe0f", cold_chain: "\u2744\ufe0f" }')
a('const PRICING_STATUS = ["active", "draft", "expired", "pending_review", "rejected", "archived"] as const')
a('const COMPETITOR_NAMES = ["BlueDart", "Delhivery", "DTDC", "XpressBees", "Ecom Express", "Shadowfax", "Spoton", "DHL"] as const')
a('const CITIES = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Hyderabad", "Kolkata", "Pune", "Ahmedabad"] as const')
a('const ZONES = ["North", "South", "East", "West", "Central"] as const')
a('const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] as const')
a('const TH = { pri: "#8b5cf6", sec: "#f59e0b", ok: "#059669", warn: "#d97706", err: "#dc2626" }')
a('const PC = ["#8b5cf6", "#f59e0b", "#059669", "#dc2626", "#06b6d4", "#ec4899", "#14b8a6", "#3b82f6"]')
a('')
a('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297) * 233280; return x - Math.floor(x) }')
a('function ri(min: number, max: number, seed: number): number { return Math.floor(seededRandom(seed) * (max - min + 1)) + min }')
a('function pick<T>(arr: readonly T[], seed: number): T { return arr[Math.floor(seededRandom(seed) * arr.length)] }')
a('')
a('function ServiceBadge({ type }: { type: string }) {')
a('  const cols: Record<string, string> = { ftl: "bg-blue-100 text-blue-700 dark:bg-blue-900/30", ptl: "bg-violet-100 text-violet-700 dark:bg-violet-900/30", express: "bg-amber-100 text-amber-700 dark:bg-amber-900/30", air: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30", surface: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30", rail: "bg-red-100 text-red-700 dark:bg-red-900/30", last_mile: "bg-pink-100 text-pink-700 dark:bg-pink-900/30", cold_chain: "bg-sky-100 text-sky-700 dark:bg-sky-900/30" }')
a('  return <span className={"dpe-service-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[type] || "bg-gray-100 text-gray-700")}>{SERVICE_EMOJI[type] || "\u2022"} {type.replace(/_/g, " ")}</span>')
a('}')
a('')
a('function PricingStatusBadge({ status }: { status: string }) {')
a('  const cols: Record<string, string> = { active: "dpe-active bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 shadow-[0_0_6px_rgba(5,150,105,0.3)]", draft: "bg-gray-100 text-gray-600", expired: "bg-red-100 text-red-700", pending_review: "bg-amber-100 text-amber-700", rejected: "bg-red-100 text-red-700", archived: "bg-gray-200 text-gray-500" }')
a('  const icons: Record<string, React.ReactNode> = { active: <CheckCircle2 className="w-3 h-3" />, draft: <Clock className="w-3 h-3" />, expired: <AlertTriangle className="w-3 h-3" />, pending_review: <Star className="w-3 h-3" />, rejected: <ShieldCheck className="w-3 h-3" />, archived: <Package className="w-3 h-3" /> }')
a('  return <span className={"dpe-status-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[status] || "")}>{icons[status]} {status.replace(/_/g, " ")}</span>')
a('}')
a('')
a('function CompetitorBadge({ name }: { name: string }) {')
a('  return <span className="dpe-competitor-badge inline-flex items-center px-2 py-0.5 rounded text-[10px] font-medium bg-violet-50 text-violet-700 dark:bg-violet-900/20">{name}</span>')
a('}')
a('')
a('function MarginBar({ margin }: { margin: number }) {')
a('  const col = margin >= 25 ? TH.ok : margin >= 10 ? TH.warn : TH.err')
a('  return <div className="dpe-margin-bar flex items-center gap-1.5"><div className="w-16 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: Math.min(margin * 2, 100) + "%", backgroundColor: col }}/></div><span className="text-[10px] font-bold" style={{ color: col }}>{margin}%</span></div>')
a('}')
a('')
a('function DemandIndicator({ level }: { level: number }) {')
a('  const col = level >= 80 ? TH.err : level >= 50 ? TH.warn : TH.ok')
a('  const label = level >= 80 ? "High" : level >= 50 ? "Medium" : "Low"')
a('  return <span className="dpe-demand inline-flex items-center gap-0.5 text-[10px] font-bold" style={{ color: col }}>{label} ({level}%)</span>')
a('}')
a('')
a('function TrendIndicator({ value }: { value: number }) {')
a('  const pos = value > 0; const col = pos ? TH.ok : TH.err')
a('  return <span className="dpe-trend inline-flex items-center gap-0.5 text-[10px] font-semibold" style={{ color: col }}>{pos ? <TrendingUp className="w-3 h-3" /> : <TrendingDown className="w-3 h-3" />}{Math.abs(value).toFixed(1)}%</span>')
a('}')
a('')
a('function ZoneBadge({ zone }: { zone: string }) { return <span className="dpe-zone-badge inline-flex items-center px-2 py-0.5 rounded text-[10px] font-medium bg-violet-50 text-violet-700 dark:bg-violet-900/20">{zone}</span> }')
a('')
a('function KpiTile({ label, value, icon, trend, color }: { label: string; value: string; icon: React.ReactNode; trend: number; color: string }) { return <Card className="dpe-kpi-tile glass-subtle hover:shadow-lg transition-shadow border-l-4" style={{ borderLeftColor: color }}><CardContent className="p-3"><div className="flex items-center justify-between"><span className="text-[10px] text-muted-foreground">{label}</span>{icon}</div><div className="text-xl font-bold mt-1">{value}</div><TrendIndicator value={trend}/></CardContent></Card> }')
a('')
a('function ValueTile({ label, value }: { label: string; value: string | number }) { return <div className="dpe-value-tile text-center p-2 rounded-lg bg-gray-50 dark:bg-gray-800/50"><div className="text-sm font-bold">{value}</div><div className="text-[10px] text-muted-foreground">{label}</div></div> }')
a('')
a('function HealthRing({ value, label }: { value: number; label: string }) { const col = value >= 90 ? TH.ok : value >= 70 ? TH.warn : TH.err; const r = 18, circ = 2 * Math.PI * r, offset = circ - (value / 100) * circ; return <div className="dpe-health-ring flex flex-col items-center gap-1"><svg width={48} height={48} className="-rotate-90"><circle cx={24} cy={24} r={r} fill="none" stroke="currentColor" strokeWidth={3} className="text-gray-200 dark:text-gray-700"/><circle cx={24} cy={24} r={r} fill="none" stroke={col} strokeWidth={3} strokeDasharray={circ} strokeDashoffset={offset} strokeLinecap="round" className="transition-all"/></svg><span className="text-[10px] font-bold" style={{ color: col }}>{value}%</span><span className="text-[9px] text-muted-foreground">{label}</span></div> }')
a('')
a('function genPricingRules() {')
a('  return Array.from({ length: 80 }, (_, i) => ({')
a('    id: "PR-" + String(i + 1).padStart(5, "0"),')
a('    service: pick(SERVICE_TYPES, i * 3 + 1),')
a('    origin: pick(CITIES, i * 3 + 2),')
a('    dest: pick(CITIES, i * 3 + 3),')
a('    baseRate: ri(5, 80, i + 7) + (ri(0, 99, i + 11) / 100),')
a('    surgeFactor: ri(80, 200, i + 13) / 100,')
a('    minCharge: ri(200, 5000, i + 17),')
a('    margin: ri(-5, 35, i + 23),')
a('    demand: ri(10, 95, i + 29),')
a('    competitor: pick(COMPETITOR_NAMES, i + 37),')
a('    compRate: ri(5, 80, i + 45) + (ri(0, 99, i + 49) / 100),')
a('    volume: ri(50, 2000, i + 53),')
a('    zone: pick(ZONES, i + 59),')
a('    status: pick(PRICING_STATUS, i + 67),')
a('    effectiveDate: "2026-07-" + String(ri(1, 30, i + 73)).padStart(2, "0")')
a('  }))')
a('}')
a('')
a('function genCompetitorData() {')
a('  return Array.from({ length: 40 }, (_, i) => ({')
a('    id: "CD-" + String(i + 1).padStart(4, "0"),')
a('    competitor: pick(COMPETITOR_NAMES, i + 7),')
a('    service: pick(SERVICE_TYPES, i + 11),')
a('    lane: pick(CITIES, i + 17) + " -> " + pick(CITIES, i + 23),')
a('    theirRate: ri(5, 80, i + 29) + (ri(0, 99, i + 33) / 100),')
a('    ourRate: ri(5, 80, i + 37) + (ri(0, 99, i + 41) / 100),')
a('    diff: ri(-20, 20, i + 47),')
a('    marketShare: ri(5, 45, i + 53),')
a('    volume: ri(100, 5000, i + 59),')
a('    trend: pick(["up", "down", "stable"], i + 67)')
a('  }))')
a('}')
a('')
a('function genCharts() {')
a('  const revenue = MO.map((m, i) => ({ month: m, revenue: ri(500000, 2000000, i + 101), margin: ri(8, 30, i + 151), volume: ri(1000, 8000, i + 201) }))')
a('  const svcDist = SERVICE_TYPES.map((s, i) => ({ service: s.replace(/_/g, " "), rules: ri(5, 20, i + 301), avgMargin: ri(5, 25, i + 351) }))')
a('  const surgeLine = MO.map((m, i) => ({ month: m, surge: ri(80, 200, i + 401) / 100, demand: ri(30, 95, i + 451) }))')
a('  return { revenue, svcDist, surgeLine }')
a('}')
a('')
a('export function DynamicPricingEngineView() {')
a('  const [tab, setTab] = useState("dashboard")')
a('  const [sortCol, setSortCol] = useState<string | null>(null)')
a('  const [sortDir, setSortDir] = useState<"asc" | "desc">("asc")')
a('  const { searchQuery, setSearchQuery, onClearSearch, activeFilters, onToggleFilter, onClearAllFilters, filteredData } = useSearchFilter({ initialData: genPricingRules() })')
a('  const { searchQuery: cq, setSearchQuery: setCq, onClearSearch: cCq, activeFilters: cf, onToggleFilter: tCf, onClearAllFilters: clCf, filteredData: fComp } = useSearchFilter({ initialData: genCompetitorData() })')
a('  const rules = filteredData')
a('  const compData = fComp')
a('  const charts = useMemo(() => genCharts(), [])')
a('  const sortedRules = useMemo(() => {')
a('    if (!sortCol) return rules')
a('    return [...rules].sort((a: any, b: any) => { const av = a[sortCol], bv = b[sortCol]; const cmp = typeof av === "string" ? av.localeCompare(bv) : av - bv; return sortDir === "asc" ? cmp : -cmp })')
a('  }, [rules, sortCol, sortDir])')
a('  const toggleSort = (col: string) => { if (sortCol === col) { setSortDir(d => d === "asc" ? "desc" : "asc") } else { setSortCol(col); setSortDir("asc") } }')
a('')
a('  const ruleFilterGroups = [')
a('    { key: "service", label: "Service", options: SERVICE_TYPES.map(s => ({ value: s, label: s.replace(/_/g, " ") })) },')
a('    { key: "status", label: "Status", options: PRICING_STATUS.map(s => ({ value: s, label: s.replace(/_/g, " ") })) },')
a('    { key: "zone", label: "Zone", options: ZONES.map(z => ({ value: z, label: z })) },')
a('    { key: "origin", label: "Origin", options: CITIES.map(c => ({ value: c, label: c })) }')
a('  ]')
a('')
a('  const compFilterGroups = [')
a('    { key: "competitor", label: "Competitor", options: COMPETITOR_NAMES.map(c => ({ value: c, label: c })) }')
a('  ]')
a('')
a('  return <div className="space-y-4 p-4">')
a('    <PageHeader title="Dynamic Pricing Engine" description="AI-powered pricing optimization, competitor intelligence and margin management"/>')
a('')
a('    <Tabs value={tab} onValueChange={setTab}>')
a('      <TabsList className="grid grid-cols-5 w-full dpe-tabs">')
a('        <TabsTrigger value="dashboard"><BarChart3 className="w-3 h-3 mr-1"/>Dashboard</TabsTrigger>')
a('        <TabsTrigger value="rules"><DollarSign className="w-3 h-3 mr-1"/>Pricing Rules</TabsTrigger>')
a('        <TabsTrigger value="competitors"><Target className="w-3 h-3 mr-1"/>Competitors</TabsTrigger>')
a('        <TabsTrigger value="surge"><Zap className="w-3 h-3 mr-1"/>Surge Analysis</TabsTrigger>')
a('        <TabsTrigger value="insights"><TrendingUp className="w-3 h-3 mr-1"/>Insights</TabsTrigger>')
a('      </TabsList>')
a('')
a('      <TabsContent value="dashboard" className="space-y-4">')
a('        <div className="grid grid-cols-4 gap-3">')
a('          <KpiTile label="Active Rules" value={String(rules.filter((r: any) => r.status === "active").length)} icon={<DollarSign className="w-4 h-4" style={{ color: TH.pri }}/>} trend={15.3} color={TH.pri}/>')
a('          <KpiTile label="Avg Margin" value="18.2%" icon={<Percent className="w-4 h-4" style={{ color: TH.ok }}/>} trend={3.8} color={TH.ok}/>')
a('          <KpiTile label="Surge Events" value="24" icon={<Zap className="w-4 h-4" style={{ color: TH.err }}/>} trend={-5.1} color={TH.err}/>')
a('          <KpiTile label="Competitors" value="8" icon={<Target className="w-4 h-4" style={{ color: TH.sec }}/>} trend={0} color={TH.sec}/>')
a('        </div>')
a('        <div className="grid grid-cols-4 gap-3">')
a('          <HealthRing value={88} label="Accuracy"/>')
a('          <HealthRing value={72} label="Win Rate"/>')
a('          <HealthRing value={95} label="Auto Apply"/>')
a('          <HealthRing value={81} label="ROI"/>')
a('        </div>')
a('        <div className="grid grid-cols-3 gap-3">')
a('          <Card className="dpe-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Revenue & Margin Trend</CardTitle></CardHeader><CardContent className="p-2"><AreaChart data={charts.revenue} height={180}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" fontSize={10}/><YAxis fontSize={10}/><Tooltip contentStyle={{ fontSize: 11 }}/><Area type="monotone" dataKey="revenue" stroke={TH.pri} fill={TH.pri} fillOpacity={0.2}/></AreaChart></CardContent></Card>')
a('          <Card className="dpe-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Service Type Rules</CardTitle></CardHeader><CardContent className="p-2"><BarChart data={charts.svcDist} height={180}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="service" fontSize={8}/><YAxis fontSize={10}/><Tooltip contentStyle={{ fontSize: 11 }}/><Bar dataKey="rules" fill={TH.sec}/></BarChart></CardContent></Card>')
a('          <Card className="dpe-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Surge & Demand</CardTitle></CardHeader><CardContent className="p-2"><LineChart data={charts.surgeLine} height={180}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" fontSize={10}/><YAxis fontSize={10}/><Tooltip contentStyle={{ fontSize: 11 }}/><Line type="monotone" dataKey="surge" stroke={TH.err}/><Line type="monotone" dataKey="demand" stroke={TH.ok}/></LineChart></CardContent></Card>')
a('        </div>')
a('      </TabsContent>')
a('')
a('      <TabsContent value="rules" className="space-y-4">')
a('        <ModuleBreadcrumb items={[{ label: "Dashboard" }, { label: "Pricing Rules" }]}/>')
a('        <SearchFilterToolbar searchQuery={searchQuery} onSearchChange={setSearchQuery} onClearSearch={onClearSearch} activeFilters={activeFilters} filterGroups={ruleFilterGroups} onToggleFilter={onToggleFilter} onClearAllFilters={onClearAllFilters} totalItems={rules.length} filteredCount={rules.length} onRefresh={() => {}} placeholder="Search pricing rules..."/>')
a('        <Card className="dpe-table-card"><CardContent className="p-2"><div className="overflow-x-auto"><table className="w-full text-[11px]"><thead><tr className="border-b dpe-table-header"><th className="p-1.5 text-left cursor-pointer hover:bg-gray-100" onClick={() => toggleSort("id")}>ID <ArrowUpDown className="w-3 h-3 inline"/></th><th className="p-1.5 text-left">Service</th><th className="p-1.5 text-left">Lane</th><th className="p-1.5 text-left">Base Rate</th><th className="p-1.5 text-left">Surge</th><th className="p-1.5 text-left">Margin</th><th className="p-1.5 text-left">Demand</th><th className="p-1.5 text-left">Competitor</th><th className="p-1.5 text-left">Status</th></tr></thead><tbody>')
a('          {sortedRules.map((r: any) => <tr key={r.id} className="border-b hover:bg-violet-50/50 dark:hover:bg-violet-900/10 dpe-table-row"><td className="p-1.5 font-mono">{r.id}</td><td className="p-1.5"><ServiceBadge type={r.service}/></td><td className="p-1.5">{r.origin} - {r.dest}</td><td className="p-1.5 font-semibold">\u20b9{r.baseRate.toFixed(2)}</td><td className="p-1.5 text-amber-600 font-semibold">{r.surgeFactor.toFixed(2)}x</td><td className="p-1.5"><MarginBar margin={r.margin}/></td><td className="p-1.5"><DemandIndicator level={r.demand}/></td><td className="p-1.5"><CompetitorBadge name={r.competitor}/></td><td className="p-1.5"><PricingStatusBadge status={r.status}/></td></tr>)}')
a('          </tbody></table></div></CardContent></Card>')
a('      </TabsContent>')
a('')
a('      <TabsContent value="competitors" className="space-y-4">')
a('        <ModuleBreadcrumb items={[{ label: "Dashboard" }, { label: "Competitors" }]}/>')
a('        <SearchFilterToolbar searchQuery={cq} onSearchChange={setCq} onClearSearch={cCq} activeFilters={cf} filterGroups={compFilterGroups} onToggleFilter={tCf} onClearAllFilters={clCf} totalItems={compData.length} filteredCount={compData.length} onRefresh={() => {}} placeholder="Search competitors..."/>')
a('        <Card className="dpe-table-card"><CardContent className="p-2"><div className="overflow-x-auto"><table className="w-full text-[11px]"><thead><tr className="border-b dpe-table-header"><th className="p-1.5 text-left">ID</th><th className="p-1.5 text-left">Competitor</th><th className="p-1.5 text-left">Service</th><th className="p-1.5 text-left">Lane</th><th className="p-1.5 text-left">Their Rate</th><th className="p-1.5 text-left">Our Rate</th><th className="p-1.5 text-left">Diff</th><th className="p-1.5 text-left">Share</th><th className="p-1.5 text-left">Trend</th></tr></thead><tbody>')
a('          {compData.map((c: any) => <tr key={c.id} className="border-b hover:bg-violet-50/50 dark:hover:bg-violet-900/10 dpe-table-row"><td className="p-1.5 font-mono">{c.id}</td><td className="p-1.5"><CompetitorBadge name={c.competitor}/></td><td className="p-1.5"><ServiceBadge type={c.service}/></td><td className="p-1.5">{c.lane}</td><td className="p-1.5 font-semibold">\u20b9{c.theirRate.toFixed(2)}</td><td className="p-1.5 font-semibold">\u20b9{c.ourRate.toFixed(2)}</td><td className="p-1.5"><span className={"font-bold " + (c.diff > 0 ? "text-emerald-600" : c.diff < 0 ? "text-red-600" : "text-gray-500")}>{c.diff > 0 ? "+" : ""}{c.diff}%</span></td><td className="p-1.5"><div className="dpe-share-bar w-12 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full" style={{ width: c.marketShare + "%", backgroundColor: TH.pri }}/></div><span className="text-[10px] ml-1">{c.marketShare}%</span></td><td className="p-1.5">{c.trend === "up" ? <TrendingUp className="w-3 h-3 text-emerald-500"/> : c.trend === "down" ? <TrendingDown className="w-3 h-3 text-red-500"/> : <ArrowRightLeft className="w-3 h-3 text-gray-400"/>}</td></tr>)}')
a('          </tbody></table></div></CardContent></Card>')
a('      </TabsContent>')
a('')
a('      <TabsContent value="surge" className="space-y-4">')
a('        <ModuleBreadcrumb items={[{ label: "Dashboard" }, { label: "Surge Analysis" }]}/>')
a('        <div className="grid grid-cols-4 gap-3">')
a('          <ValueTile label="Active Surges" value="12"/>')
a('          <ValueTile label="Avg Surge Factor" value="1.45x"/>')
a('          <ValueTile label="Peak Surge Today" value="2.1x"/>')
a('          <ValueTile label="Revenue Impact" value="+\u20b98.5L"/>')
a('        </div>')
a('        <div className="grid grid-cols-2 gap-3">')
a('          <Card className="dpe-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Surge Factor Trend</CardTitle></CardHeader><CardContent className="p-2"><AreaChart data={charts.surgeLine} height={200}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" fontSize={10}/><YAxis fontSize={10}/><Tooltip contentStyle={{ fontSize: 11 }}/><Area type="monotone" dataKey="surge" stroke={TH.err} fill={TH.err} fillOpacity={0.15}/></AreaChart></CardContent></Card>')
a('          <Card className="dpe-chart-card"><CardHeader className="p-2 pb-0"><CardTitle className="text-xs">Service Type Distribution</CardTitle></CardHeader><CardContent className="p-2"><PieChart height={200}><Pie data={SERVICE_TYPES.map((s, i) => ({ name: s.replace(/_/g, " "), value: ri(5, 30, i + 701) }))} cx="50%" cy="50%" outerRadius={60} dataKey="value" label><Cell fill={PC[0]}/><Cell fill={PC[1]}/><Cell fill={PC[2]}/><Cell fill={PC[3]}/><Cell fill={PC[4]}/><Cell fill={PC[5]}/><Cell fill={PC[6]}/><Cell fill={PC[7]}/></Pie><Tooltip contentStyle={{ fontSize: 11 }}/></PieChart></CardContent></Card>')
a('        </div>')
a('      </TabsContent>')
a('')
a('      <TabsContent value="insights" className="space-y-4">')
a('        <ModuleBreadcrumb items={[{ label: "Dashboard" }, { label: "Insights" }]}/>')
a('        <div className="grid grid-cols-2 gap-3">')
a('          <Card className="dpe-insight-card p-4"><div className="text-xs font-semibold mb-2 flex items-center gap-1"><DollarSign className="w-3 h-3 text-violet-500"/>Margin Improvement</div><div className="text-[10px] text-muted-foreground">Express and air services show highest margin potential. Consider dynamic base rate adjustment for Delhi-Bangalore and Mumbai-Chennai corridors where demand exceeds supply by 30%.</div></Card>')
a('          <Card className="dpe-insight-card p-4"><div className="text-xs font-semibold mb-2 flex items-center gap-1"><Target className="w-3 h-3 text-amber-500"/>Competitor Gap Analysis</div><div className="text-[10px] text-muted-foreground">Delhivery undercuts on PTL by 12%. XpressBees has 18% higher express rates creating opportunity. Shadowfax gaining market share in last-mile with 8% lower pricing.</div></Card>')
a('          <Card className="dpe-insight-card p-4"><div className="text-xs font-semibold mb-2 flex items-center gap-1"><Zap className="w-3 h-3 text-red-500"/>Surge Patterns</div><div className="text-[10px] text-muted-foreground">Festival seasons show 2x surge. E-commerce sale events like Big Billion Days and Great Indian Festival trigger 2.5x. Pre-plan capacity allocation and communicate surge pricing 72h ahead.</div></Card>')
a('          <Card className="dpe-insight-card p-4"><div className="text-xs font-semibold mb-2 flex items-center gap-1"><TrendingUp className="w-3 h-3 text-emerald-500"/>Revenue Optimization</div><div className="text-[10px] text-muted-foreground">Implement zone-based pricing for North region where volumes are 25% higher. Cold chain margins can improve 8% with distance-weighted pricing. FTL corridor optimization yields 15% uplift.</div></Card>')
a('        </div>')
a('      </TabsContent>')
a('    </Tabs>')
a('  </div>')
a('}')

write_lines(os.path.join(BASE, "dynamic-pricing-engine-view.tsx"), dpe)
print("Done! Both R265 modules generated successfully.")
