#!/usr/bin/env python3
"""Generate R258 modules: logistics-control-tower and warehouse-smart-picking"""

import os

# ═══════════════════════════════════════════════════════════════════════
# MODULE 1: Logistics Control Tower
# ═══════════════════════════════════════════════════════════════════════
m1 = []
m1.append('"use client"')
m1.append('')
m1.append('import { useState, useMemo } from "react"')
m1.append('import {')
m1.append('  AreaChart, Area, BarChart, Bar, PieChart, Pie, Cell,')
m1.append('  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip,')
m1.append('} from "recharts"')
m1.append('import {')
m1.append('  Search, Eye, ArrowUpDown, TrendingUp, TrendingDown, Clock, IndianRupee, Zap,')
m1.append('  AlertTriangle, Users, BarChart3, MapPin, Package, Box, CheckCircle, XCircle, Activity, Timer, ShieldCheck, Star, Radio, Gauge, ThermometerSun, Plane, TrainFront, Ship, Truck, Globe, Satellite, Radar, Target, Crosshair, Compass, Play, Pause, Square, CircleDot, MonitorSmartphone, ArrowRight, ArrowLeftRight, RefreshCw, Filter, Download, ChevronRight')
m1.append('} from "lucide-react"')
m1.append('import { PageHeader } from "@/components/shared/page-header"')
m1.append('import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"')
m1.append('import { Input } from "@/components/ui/input"')
m1.append('import { Button } from "@/components/ui/button"')
m1.append('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
m1.append('import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"')
m1.append('')
m1.append('const WH_NAMES = ["Mumbai Hub","Delhi NCR","Bangalore South","Chennai Port","Hyderabad East","Kolkata DC","Pune West","Ahmedabad North"] as const')
m1.append('const OPS_TYPES = ["Receiving","Putaway","Picking","Packing","Shipping","Returns","QC Check","Kitting"] as const')
m1.append('const OPS_EMOJI: Record<string,string> = {Receiving:"\U0001f4e5",Putaway:"\U0001f4c2",Picking:"\U0001f4e6",Packing:"\U0001f3f7\ufe0f",Shipping:"\U0001f69b",Returns:"\U0001f504","QC Check":"\u2705",Kitting:"\U0001f527"}')
m1.append('const OPS_STS = ["Running","Paused","Delayed","Completed","Scheduled","Cancelled"] as const')
m1.append('const ALERT_CATS = ["SLA Breach","Capacity Alert","Equipment Failure","Staffing Issue","Safety Incident","Quality Hold","System Error","Weather Disruption"] as const')
m1.append('const ALERT_SEVS = ["P1 Critical","P2 High","P3 Medium","P4 Low"] as const')
m1.append('const TRANS_MODES = ["Road","Rail","Air","Sea","Multimodal"] as const')
m1.append('const TRANS_STS = ["In Transit","At Hub","Delayed","Delivered","Customs Hold","Loading","Unloading"] as const')
m1.append('const CITIES = ["Mumbai","Delhi","Bangalore","Chennai","Hyderabad","Kolkata","Pune","Ahmedabad","Jaipur","Lucknow","Coimbatore","Indore"] as const')
m1.append('const CARRIERS = ["BlueDart","Delhivery","DTDC","Ecom Express","XpressBees","Shadowfax","Rivigo","Spoton"] as const')
m1.append('const SHIP_TYPES = ["FCL","LCL","FTL","LTL","Parcel","Express","Bulk","Cold Chain"] as const')
m1.append('const MO = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"] as const')
m1.append('const TH = {indigo:"#4f46e5",blue:"#3b82f6",emerald:"#059669",amber:"#d97706",rose:"#e11d48",cyan:"#0891b2",violet:"#7c3aed",orange:"#f97316"}')
m1.append('const PC = [TH.indigo,TH.blue,TH.emerald,TH.amber,TH.rose,TH.cyan,TH.violet,TH.orange]')

m1.append('')
m1.append('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297 + 233280) * 10000; return x - Math.floor(x) }')
m1.append('function ri(a: number, b: number, s: number): number { return Math.floor(seededRandom(s) * (b - a + 1)) + a }')
m1.append('function pick<T>(arr: readonly T[], s: number): T { return arr[Math.abs(s) % arr.length] }')
m1.append('function rf(d: number): string { return "\\u20b9" + (d * 1000).toLocaleString("en-IN") }')
m1.append('function filterData<T>(d: T[], q: string): T[] { if (!q) return d; const l = q.toLowerCase(); return d.filter(i => Object.values(i as unknown as Record<string, string | number>).some(v => String(v).toLowerCase().includes(l))) }')
m1.append('function sortedData<T>(d: T[], f: string, dir: "asc" | "desc"): T[] { return [...d].sort((a, b) => { const av = (a as unknown as Record<string, string | number>)[f], bv = (b as unknown as Record<string, string | number>)[f]; if (typeof av === "number" && typeof bv === "number") return dir === "asc" ? av - bv : bv - av; return dir === "asc" ? String(av ?? "").localeCompare(String(bv ?? "")) : String(bv ?? "").localeCompare(String(av ?? "")) }) }')

# --- Visual Components ---
m1.append('')
m1.append('/* 18 Visual Components */')
m1.append('function OpsTypeBadge({ t }: { t: string }) {')
m1.append('  const cl: Record<string,string> = {Receiving:"bg-indigo-100 text-indigo-700",Putaway:"bg-blue-100 text-blue-700",Picking:"bg-emerald-100 text-emerald-700",Packing:"bg-amber-100 text-amber-700",Shipping:"bg-rose-100 text-rose-700",Returns:"bg-cyan-100 text-cyan-700","QC Check":"bg-violet-100 text-violet-700",Kitting:"bg-orange-100 text-orange-700"}')
m1.append('  return <span className={"lct-ot-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium " + (cl[t]||"bg-gray-100")}>{OPS_EMOJI[t]} {t}</span>')
m1.append('}')
m1.append('function OpsStatusBadge({ s }: { s: string }) {')
m1.append('  const cl: Record<string,string> = {Running:"bg-emerald-100 text-emerald-700",Paused:"bg-amber-100 text-amber-700",Delayed:"bg-red-100 text-red-700",Completed:"bg-slate-100 text-slate-600",Scheduled:"bg-blue-100 text-blue-700",Cancelled:"bg-gray-100 text-gray-500"}')
m1.append('  const pulse = s==="Running"||s==="Delayed" ? " animate-pulse" : ""')
m1.append('  return <span className={"lct-os-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cl[s]||"bg-gray-100") + pulse}>\u25cf {s}</span>')
m1.append('}')
m1.append('function AlertCatBadge({ c }: { c: string }) {')
m1.append('  return <span className="lct-ac-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300">\u26a0 {c}</span>')
m1.append('}')
m1.append('function AlertSevBadge({ s }: { s: string }) {')
m1.append('  const cl: Record<string,string> = {"P1 Critical":"bg-red-100 text-red-700 shadow-[0_0_8px_oklch(0.55_0.22_25/0.3)]","P2 High":"bg-orange-100 text-orange-700","P3 Medium":"bg-amber-100 text-amber-700","P4 Low":"bg-blue-100 text-blue-700"}')
m1.append('  const emoji: Record<string,string> = {"P1 Critical":"\U0001f534","P2 High":"\U0001f7e0","P3 Medium":"\U0001f7e1","P4 Low":"\U0001f535"}')
m1.append('  return <span className={"lct-as-badge inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold " + (cl[s]||"bg-gray-100")}>{emoji[s]} {s}</span>')
m1.append('}')
m1.append('function TransModeBadge({ m }: { m: string }) {')
m1.append('  const emoji: Record<string,string> = {Road:"\U0001f69b",Rail:"\U0001f682",Air:"\u2708\ufe0f",Sea:"\U0001f6a2",Multimodal:"\U0001f517"}')
m1.append('  const cl: Record<string,string> = {Road:"bg-amber-100 text-amber-700",Rail:"bg-blue-100 text-blue-700",Air:"bg-violet-100 text-violet-700",Sea:"bg-cyan-100 text-cyan-700",Multimodal:"bg-emerald-100 text-emerald-700"}')
m1.append('  return <span className={"lct-tm-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium " + (cl[m]||"bg-gray-100")}>{emoji[m]} {m}</span>')
m1.append('}')
m1.append('function TransStatusBadge({ s }: { s: string }) {')
m1.append('  const cl: Record<string,string> = {"In Transit":"bg-blue-100 text-blue-700 animate-pulse","At Hub":"bg-indigo-100 text-indigo-700",Delayed:"bg-red-100 text-red-700",Delivered:"bg-emerald-100 text-emerald-700","Customs Hold":"bg-amber-100 text-amber-700",Loading:"bg-cyan-100 text-cyan-700",Unloading:"bg-violet-100 text-violet-700"}')
m1.append('  return <span className={"lct-ts-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cl[s]||"bg-gray-100")}>\u25cf {s}</span>')
m1.append('}')
m1.append('function ShipTypeBadge({ t }: { t: string }) {')
m1.append('  const cl: Record<string,string> = {FCL:"bg-blue-100 text-blue-700",LCL:"bg-indigo-100 text-indigo-700",FTL:"bg-amber-100 text-amber-700",LTL:"bg-orange-100 text-orange-700",Parcel:"bg-emerald-100 text-emerald-700",Express:"bg-rose-100 text-rose-700",Bulk:"bg-slate-100 text-slate-700","Cold Chain":"bg-cyan-100 text-cyan-700"}')
m1.append('  return <span className={"lct-st-badge inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold " + (cl[t]||"bg-gray-100")}>{t}</span>')
m1.append('}')
m1.append('function CarrierBadge({ c }: { c: string }) {')
m1.append('  return <span className="lct-carrier inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold bg-gradient-to-r from-blue-50 to-indigo-50 text-blue-700 dark:from-blue-900/30 dark:to-indigo-900/30 dark:text-blue-300">\U0001f69a {c}</span>')
m1.append('}')
m1.append('function CityBadge({ city }: { city: string }) {')
m1.append('  return <span className="lct-city inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-medium bg-cyan-50 text-cyan-700 dark:bg-cyan-900/30 dark:text-cyan-300">\U0001f4cd {city}</span>')
m1.append('}')
m1.append('function WhBadge({ wh }: { wh: string }) {')
m1.append('  return <span className="lct-wh inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold bg-indigo-50 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-300">\U0001f3ed {wh}</span>')
m1.append('}')
m1.append('function ThroughputBar({ value, max }: { value: number; max: number }) {')
m1.append('  const pct = Math.round((value / max) * 100)')
m1.append('  const c = pct > 80 ? "bg-red-500" : pct > 60 ? "bg-amber-500" : pct > 40 ? "bg-blue-500" : "bg-emerald-500"')
m1.append('  return <div className="lct-thr-bar flex items-center gap-2 w-full"><div className="flex-1 h-2.5 rounded-full bg-gray-200 dark:bg-gray-700"><div className={"h-full rounded-full transition-all " + c} style={{width: pct + "%"}}/></div><span className="text-[10px] font-bold tabular-nums min-w-[40px] text-right">{value}/{max}</span></div>')
m1.append('}')
m1.append('function SlaCountdown({ hours }: { hours: number }) {')
m1.append('  const c = hours > 8 ? "text-emerald-600 dark:text-emerald-400" : hours > 4 ? "text-amber-600 dark:text-amber-400" : hours > 2 ? "text-orange-600 dark:text-orange-400" : "text-red-600 dark:text-red-400"')
m1.append('  return <span className={"lct-sla inline-flex items-center gap-1 text-xs font-bold tabular-nums " + c}><Timer className="h-3 w-3"/>{hours}h left</span>')
m1.append('}')
m1.append('function ValueTile({ value, label, trend }: { value: string; label: string; trend: number }) {')
m1.append('  return <div className="lct-val-tile text-right"><div className="text-sm font-bold tabular-nums">{value}</div><div className="text-[10px] text-muted-foreground">{label}</div>{trend !== 0 && <div className={"text-[10px] font-semibold flex items-center justify-end gap-0.5 " + (trend > 0 ? "text-emerald-600" : "text-red-600")}>{trend > 0 ? <TrendingUp className="h-3 w-3"/> : <TrendingDown className="h-3 w-3"/>}{Math.abs(trend)}%</div>}</div>')
m1.append('}')
m1.append('function HealthRing({ score }: { score: number }) {')
m1.append('  const c = score >= 90 ? "text-emerald-500" : score >= 75 ? "text-blue-500" : score >= 60 ? "text-amber-500" : "text-red-500"')
m1.append('  const label = score >= 90 ? "Excellent" : score >= 75 ? "Good" : score >= 60 ? "Fair" : "Critical"')
m1.append('  return <div className="lct-health flex flex-col items-center"><div className={"text-3xl font-black tabular-nums " + c}>{score}</div><div className={"text-[10px] font-bold " + c}>{label}</div></div>')
m1.append('}')
m1.append('function PriorityDot({ p }: { p: string }) {')
m1.append('  const cl: Record<string,string> = {Urgent:"bg-red-500 shadow-[0_0_6px_rgba(239,68,68,0.5)]",High:"bg-orange-500",Medium:"bg-amber-400",Low:"bg-blue-400"}')
m1.append('  return <div className={"lct-priority w-2.5 h-2.5 rounded-full " + (cl[p]||"bg-gray-400")}/>')
m1.append('}')
m1.append('function StarRating({ value }: { value: number }) {')
m1.append('  return <span className="lct-stars inline-flex gap-0.5">{"\u2605".repeat(value)}{"\u2606".repeat(5 - value)}</span>')
m1.append('}')
m1.append('function CostTile({ value }: { value: number }) {')
m1.append('  return <span className="lct-cost text-sm font-bold tabular-nums text-indigo-600 dark:text-indigo-400">{rf(value)}</span>')
m1.append('}')
m1.append('function ProgressRing({ pct }: { pct: number }) {')
m1.append('  const c = pct >= 90 ? "text-emerald-500" : pct >= 70 ? "text-blue-500" : pct >= 50 ? "text-amber-500" : "text-red-500"')
m1.append('  return <div className="lct-ring flex items-center gap-1.5"><div className={"text-xs font-bold tabular-nums " + c}>{pct}%</div><div className="flex-1 h-1.5 rounded-full bg-gray-200 dark:bg-gray-700"><div className={"h-full rounded-full transition-all " + c.replace("text-","bg-")} style={{width: pct + "%"}}/></div></div>')
m1.append('}')

# --- Data Generation ---
m1.append('')
m1.append('/* Data */')
m1.append('function genOpsData() {')
m1.append('  return Array.from({length: 80}, (_, i) => ({')
m1.append('    id: "OPS-" + String(i+1001).padStart(4,"0"),')
m1.append('    warehouse: pick(WH_NAMES, i+1),')
m1.append('    type: pick(OPS_TYPES, i+2),')
m1.append('    status: pick(OPS_STS, i+3),')
m1.append('    throughput: ri(120, 950, i+4),')
m1.append('    target: ri(800, 1000, i+5),')
m1.append('    accuracy: ri(88, 100, i+6),')
m1.append('    slaHours: ri(1, 24, i+7),')
m1.append('    teamSize: ri(5, 45, i+8),')
m1.append('    shift: pick(["Morning","Afternoon","Night"], i+9),')
m1.append('    health: ri(55, 99, i+10),')
m1.append('    cost: ri(15, 120, i+11),')
m1.append('  }))')
m1.append('}')
m1.append('')
m1.append('function genAlertData() {')
m1.append('  return Array.from({length: 65}, (_, i) => ({')
m1.append('    id: "ALT-" + String(i+2001).padStart(4,"0"),')
m1.append('    category: pick(ALERT_CATS, i+1),')
m1.append('    severity: pick(ALERT_SEVS, i+2),')
m1.append('    warehouse: pick(WH_NAMES, i+3),')
m1.append('    resolved: i % 3 === 0 ? false : i % 3 === 1 ? true : pick([true,false], i+4),')
m1.append('    createdAt: ri(1,48) + "h ago",')
m1.append('    assignee: pick(["Rahul S.","Priya M.","Amit K.","Sneha D.","Vikram P."], i+5),')
m1.append('    impact: pick(["High","Medium","Low"], i+6),')
m1.append('  }))')
m1.append('}')
m1.append('')
m1.append('function genTransitData() {')
m1.append('  return Array.from({length: 70}, (_, i) => ({')
m1.append('    id: "TR-" + String(i+3001).padStart(4,"0"),')
m1.append('    origin: pick(CITIES, i+1),')
m1.append('    destination: pick(CITIES, (i+7) % CITIES.length),')
m1.append('    mode: pick(TRANS_MODES, i+2),')
m1.append('    status: pick(TRANS_STS, i+3),')
m1.append('    carrier: pick(CARRIERS, i+4),')
m1.append('    shipType: pick(SHIP_TYPES, i+5),')
m1.append('    eta: ri(1, 72) + "h",')
m1.append('    weight: ri(50, 5000) + " kg",')
m1.append('    value: ri(5, 500, i+6),')
m1.append('    progress: ri(5, 100, i+7),')
m1.append('    temp: ri(2, 35, i+8) + "\u00b0C",')
m1.append('  }))')
m1.append('}')

# --- Chart Data ---
m1.append('')
m1.append('function genChartData() {')
m1.append('  const monthly = MO.map((m, i) => ({ month: m, inbound: ri(2000,5000,i), outbound: ri(1800,4800,i+12), returns: ri(200,600,i+24), cost: ri(50,150,i+36) }))')
m1.append('  const hubPie = WH_NAMES.map((w, i) => ({ name: w.split(" ")[0], value: ri(500,3000,i) }))')
m1.append('  const modePie = TRANS_MODES.map((m, i) => ({ name: m, value: ri(100,800,i) }))')
m1.append('  const alertBar = ALERT_CATS.map((c, i) => ({ name: c.split(" ")[0], p1: ri(2,15,i), p2: ri(5,25,i+8), p3: ri(10,40,i+16), p4: ri(15,60,i+24) }))')
m1.append('  const carrierBar = CARRIERS.map((c, i) => ({ name: c, onTime: ri(75,98,i), avgCost: ri(20,80,i+8), volume: ri(500,3000,i+16) }))')
m1.append('  const cityLine = CITIES.slice(0,8).map((c, i) => ({ city: c, throughput: ri(2000,8000,i), accuracy: ri(90,99,i+8), cost: ri(30,120,i+16) }))')
m1.append('  return { monthly, hubPie, modePie, alertBar, carrierBar, cityLine }')
m1.append('}')

# --- Main Component ---
m1.append('')
m1.append('export default function LogisticsControlTowerView() {')
m1.append('  const [tab, setTab] = useState("overview")')
m1.append('  const [search, setSearch] = useState("")')
m1.append('  const [sortField, setSortField] = useState("id")')
m1.append('  const [sortDir, setSortDir] = useState<"asc"|"desc">("asc")')
m1.append('  const [detail, setDetail] = useState<Record<string, unknown>|null>(null)')
m1.append('  const [sheetTab, setSheetTab] = useState("ops")')
m1.append('')
m1.append('  const opsData = useMemo(() => genOpsData(), [])')
m1.append('  const alertData = useMemo(() => genAlertData(), [])')
m1.append('  const transitData = useMemo(() => genTransitData(), [])')
m1.append('  const charts = useMemo(() => genChartData(), [])')
m1.append('')
m1.append('  const filteredOps = useMemo(() => sortedData(filterData(opsData, search), sortField, sortDir), [opsData, search, sortField, sortDir])')
m1.append('  const filteredAlerts = useMemo(() => sortedData(filterData(alertData, search), sortField, sortDir), [alertData, search, sortField, sortDir])')
m1.append('  const filteredTransit = useMemo(() => sortedData(filterData(transitData, search), sortField, sortDir), [transitData, search, sortField, sortDir])')
m1.append('')
m1.append('  const toggleSort = (f: string) => { if (sortField === f) setSortDir(d => d === "asc" ? "desc" : "asc"); else { setSortField(f); setSortDir("asc") } }')

# Tab 0: Overview Dashboard
m1.append('')
m1.append('  const tab0 = (')
m1.append('    <div className="space-y-4">')
m1.append('      {/* KPI Row */}')
m1.append('      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">')
m1.append("        {['Total Shipments:12,847','Active Hubs:8/8','Avg Throughput:3,241/hr','On-time Rate:94.2%','Open Alerts:23','Cost Savings:18.5%','Avg Accuracy:97.3%','Network Health:91'].map((item, i) => {")
m1.append('          const [label, val] = item.split(":")')
m1.append('          const icons = [<Package key="p"/>,<Globe key="g"/>,<Activity key="a"/>,<Target key="t"/>,<AlertTriangle key="at"/>,<IndianRupee key="r"/>,<ShieldCheck key="s"/>,<HealthRing key="h" score={91}/>]')
m1.append('          return (')
m1.append('            <Card key={i} className="glass-subtle lct-kpi-card">')
m1.append('              <CardContent className="p-3"><div className="flex items-center gap-2.5">{icons[i]}<div><div className="text-[10px] text-muted-foreground">{label}</div><div className="text-lg font-black tabular-nums">{val}</div></div></div></CardContent>')
m1.append('            </Card>')
m1.append('          )')
m1.append('        })}')
m1.append('      </div>')
m1.append('      {/* Charts Row */}')
m1.append('      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">')
m1.append('        <Card className="glass-subtle lct-chart-card"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Monthly Shipment Volume</CardTitle></CardHeader><CardContent className="p-3"><AreaChart data={charts.monthly}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Area type="monotone" dataKey="inbound" stackId="1" stroke={TH.blue} fill={TH.blue} fillOpacity={0.4}/><Area type="monotone" dataKey="outbound" stackId="1" stroke={TH.emerald} fill={TH.emerald} fillOpacity={0.4}/><Area type="monotone" dataKey="returns" stackId="1" stroke={TH.rose} fill={TH.rose} fillOpacity={0.4}/></AreaChart></CardContent></Card>')
m1.append('        <Card className="glass-subtle lct-chart-card"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Hub Distribution</CardTitle></CardHeader><CardContent className="p-3"><PieChart><Pie data={charts.hubPie} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({name}: {name:string}) => <text x={0} y={0} fill="currentColor" fontSize={10} textAnchor="middle">{name}</text>}>{charts.hubPie.map((_,i) => <Cell key={i} fill={PC[i%PC.length]}/>)}</Pie><Tooltip/></PieChart></CardContent></Card>')
m1.append('        <Card className="glass-subtle lct-chart-card"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Alert Distribution by Severity</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.alertBar}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="p1" fill={TH.rose} stackId="a"/><Bar dataKey="p2" fill={TH.orange} stackId="a"/><Bar dataKey="p3" fill={TH.amber} stackId="a"/><Bar dataKey="p4" fill={TH.blue} stackId="a"/></BarChart></CardContent></Card>')
m1.append('        <Card className="glass-subtle lct-chart-card"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Transport Mode Split</CardTitle></CardHeader><CardContent className="p-3"><PieChart><Pie data={charts.modePie} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({name, percent}: {name:string;percent:number}) => <text x={0} y={0} fill="currentColor" fontSize={10} textAnchor="middle">{name} {(percent*100).toFixed(0)}%</text>}>{charts.modePie.map((_,i) => <Cell key={i} fill={PC[i%PC.length]}/>)}</Pie><Tooltip/></PieChart></CardContent></Card>')
m1.append('      </div>')
m1.append('      {/* Carrier Performance */}')
m1.append('      <Card className="glass-subtle lct-chart-card"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Carrier On-time Performance (%)</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.carrierBar} layout="vertical"><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis type="number" domain={[0,100]} tick={{fontSize:10}}/><YAxis dataKey="name" type="category" width={85} tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="onTime" radius={[0,4,4,0]}>{charts.carrierBar.map((_,i) => <Cell key={i} fill={charts.carrierBar[i].onTime > 95 ? TH.emerald : charts.carrierBar[i].onTime > 90 ? TH.blue : charts.carrierBar[i].onTime > 85 ? TH.amber : TH.rose}/>)}</Bar></BarChart></CardContent></Card>')
m1.append('    </div>')
m1.append('  )')

# Tab 1: Operations Monitor
m1.append('')
m1.append('  const tab1 = (')
m1.append('    <div className="space-y-3">')
m1.append('      <div className="flex items-center gap-2"><div className="relative flex-1"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground"/><Input className="h-8 pl-8 text-xs" placeholder="Search operations..." value={search} onChange={e => setSearch(e.target.value)}/></div><Button variant="outline" size="sm" className="h-8 text-xs"><RefreshCw className="h-3 w-3 mr-1"/>Refresh</Button></div>')
m1.append('      <div className="rounded-lg border overflow-auto max-h-[calc(100vh-280px)]">')
m1.append('        <table className="w-full text-xs"><thead className="bg-indigo-50 dark:bg-indigo-900/20 sticky top-0 z-10"><tr>')
m1.append('          <th className="p-2 text-left font-semibold cursor-pointer select-none" onClick={() => toggleSort("id")}>ID <ArrowUpDown className="inline h-3 w-3 ml-0.5 opacity-50"/></th>')
m1.append('          <th className="p-2 text-left font-semibold">Warehouse</th>')
m1.append('          <th className="p-2 text-left font-semibold">Type</th>')
m1.append('          <th className="p-2 text-left font-semibold">Status</th>')
m1.append('          <th className="p-2 text-left font-semibold">Throughput</th>')
m1.append('          <th className="p-2 text-left font-semibold">Target</th>')
m1.append('          <th className="p-2 text-left font-semibold">Accuracy</th>')
m1.append('          <th className="p-2 text-left font-semibold">SLA</th>')
m1.append('          <th className="p-2 text-left font-semibold">Team</th>')
m1.append('          <th className="p-2 text-left font-semibold">Health</th>')
m1.append('          <th className="p-2 text-left font-semibold">Cost</th>')
m1.append('          <th className="p-2"></th>')
m1.append('        </tr></thead><tbody className="divide-y">')
m1.append('          {filteredOps.map((row, idx) => (')
m1.append('            <tr key={row.id} className="hover:bg-indigo-50/50 dark:hover:bg-indigo-900/10 transition-colors">')
m1.append('              <td className="p-2 font-mono font-medium">{row.id}</td>')
m1.append('              <td className="p-2"><WhBadge wh={row.warehouse}/></td>')
m1.append('              <td className="p-2"><OpsTypeBadge t={row.type}/></td>')
m1.append('              <td className="p-2"><OpsStatusBadge s={row.status}/></td>')
m1.append('              <td className="p-2"><ThroughputBar value={row.throughput} max={row.target}/></td>')
m1.append('              <td className="p-2 numeric-cell tabular-nums">{row.target}</td>')
m1.append('              <td className="p-2 numeric-cell tabular-nums">{row.accuracy}%</td>')
m1.append('              <td className="p-2"><SlaCountdown hours={row.slaHours}/></td>')
m1.append('              <td className="p-2 tabular-nums">{row.teamSize}</td>')
m1.append('              <td className="p-2"><HealthRing score={row.health}/></td>')
m1.append('              <td className="p-2"><CostTile value={row.cost}/></td>')
m1.append('              <td className="p-2"><Button variant="ghost" size="sm" className="h-6 w-6 p-0" onClick={() => setDetail(row)}><Eye className="h-3 w-3"/></Button></td>')
m1.append('            </tr>')
m1.append('          ))}')
m1.append('        </tbody></table>')
m1.append('      </div>')
m1.append('      <div className="text-[10px] text-muted-foreground text-right">{filteredOps.length} operations</div>')
m1.append('    </div>')
m1.append('  )')

# Tab 2: Alert Center
m1.append('')
m1.append('  const tab2 = (')
m1.append('    <div className="space-y-3">')
m1.append('      <div className="flex items-center gap-2"><div className="relative flex-1"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground"/><Input className="h-8 pl-8 text-xs" placeholder="Search alerts..." value={search} onChange={e => setSearch(e.target.value)}/></div><Button variant="outline" size="sm" className="h-8 text-xs"><Filter className="h-3 w-3 mr-1"/>Filter</Button></div>')
m1.append('      <div className="rounded-lg border overflow-auto max-h-[calc(100vh-280px)]">')
m1.append('        <table className="w-full text-xs"><thead className="bg-rose-50 dark:bg-rose-900/20 sticky top-0 z-10"><tr>')
m1.append('          <th className="p-2 text-left font-semibold">ID</th>')
m1.append('          <th className="p-2 text-left font-semibold">Category</th>')
m1.append('          <th className="p-2 text-left font-semibold">Severity</th>')
m1.append('          <th className="p-2 text-left font-semibold">Warehouse</th>')
m1.append('          <th className="p-2 text-left font-semibold">Status</th>')
m1.append('          <th className="p-2 text-left font-semibold">Created</th>')
m1.append('          <th className="p-2 text-left font-semibold">Assignee</th>')
m1.append('          <th className="p-2 text-left font-semibold">Impact</th>')
m1.append('          <th className="p-2"></th>')
m1.append('        </tr></thead><tbody className="divide-y">')
m1.append('          {filteredAlerts.map(row => (')
m1.append('            <tr key={row.id} className={"hover:bg-rose-50/50 dark:hover:bg-rose-900/10 transition-colors " + (!row.resolved && row.severity === "P1 Critical" ? "bg-red-50/60 dark:bg-red-900/10" : "")}>')
m1.append('              <td className="p-2 font-mono font-medium">{row.id}</td>')
m1.append('              <td className="p-2"><AlertCatBadge c={row.category}/></td>')
m1.append('              <td className="p-2"><AlertSevBadge s={row.severity}/></td>')
m1.append('              <td className="p-2"><WhBadge wh={row.warehouse}/></td>')
m1.append('              <td className="p-2"><span className={"lct-resolved inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (row.resolved ? "bg-emerald-100 text-emerald-700" : "bg-red-100 text-red-700 animate-pulse")}>{row.resolved ? "\u2705 Resolved" : "\U0001f534 Open"}</span></td>')
m1.append('              <td className="p-2 tabular-nums">{row.createdAt}</td>')
m1.append('              <td className="p-2 text-muted-foreground">{row.assignee}</td>')
m1.append('              <td className="p-2"><PriorityDot p={row.impact}/></td>')
m1.append('              <td className="p-2"><Button variant="ghost" size="sm" className="h-6 w-6 p-0" onClick={() => setDetail(row)}><Eye className="h-3 w-3"/></Button></td>')
m1.append('            </tr>')
m1.append('          ))}')
m1.append('        </tbody></table>')
m1.append('      </div>')
m1.append('      <div className="text-[10px] text-muted-foreground text-right">{filteredAlerts.length} alerts</div>')
m1.append('    </div>')
m1.append('  )')

# Tab 3: Transit Tracker
m1.append('')
m1.append('  const tab3 = (')
m1.append('    <div className="space-y-3">')
m1.append('      <div className="flex items-center gap-2"><div className="relative flex-1"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground"/><Input className="h-8 pl-8 text-xs" placeholder="Search shipments..." value={search} onChange={e => setSearch(e.target.value)}/></div><Button variant="outline" size="sm" className="h-8 text-xs"><Download className="h-3 w-3 mr-1"/>Export</Button></div>')
m1.append('      <div className="rounded-lg border overflow-auto max-h-[calc(100vh-280px)]">')
m1.append('        <table className="w-full text-xs"><thead className="bg-blue-50 dark:bg-blue-900/20 sticky top-0 z-10"><tr>')
m1.append('          <th className="p-2 text-left font-semibold cursor-pointer select-none" onClick={() => toggleSort("id")}>ID <ArrowUpDown className="inline h-3 w-3 ml-0.5 opacity-50"/></th>')
m1.append('          <th className="p-2 text-left font-semibold">Route</th>')
m1.append('          <th className="p-2 text-left font-semibold">Mode</th>')
m1.append('          <th className="p-2 text-left font-semibold">Type</th>')
m1.append('          <th className="p-2 text-left font-semibold">Carrier</th>')
m1.append('          <th className="p-2 text-left font-semibold">Status</th>')
m1.append('          <th className="p-2 text-left font-semibold">ETA</th>')
m1.append('          <th className="p-2 text-left font-semibold">Progress</th>')
m1.append('          <th className="p-2 text-left font-semibold">Weight</th>')
m1.append('          <th className="p-2 text-left font-semibold">Temp</th>')
m1.append('          <th className="p-2 text-left font-semibold">Value</th>')
m1.append('          <th className="p-2"></th>')
m1.append('        </tr></thead><tbody className="divide-y">')
m1.append('          {filteredTransit.map(row => (')
m1.append('            <tr key={row.id} className="hover:bg-blue-50/50 dark:hover:bg-blue-900/10 transition-colors">')
m1.append('              <td className="p-2 font-mono font-medium">{row.id}</td>')
m1.append('              <td className="p-2"><div className="flex items-center gap-1 text-[10px]"><CityBadge city={row.origin}/><ChevronRight className="h-3 w-3 text-muted-foreground"/><CityBadge city={row.destination}/></div></td>')
m1.append('              <td className="p-2"><TransModeBadge m={row.mode}/></td>')
m1.append('              <td className="p-2"><ShipTypeBadge t={row.shipType}/></td>')
m1.append('              <td className="p-2"><CarrierBadge c={row.carrier}/></td>')
m1.append('              <td className="p-2"><TransStatusBadge s={row.status}/></td>')
m1.append('              <td className="p-2 tabular-nums">{row.eta}</td>')
m1.append('              <td className="p-2"><ProgressRing pct={row.progress}/></td>')
m1.append('              <td className="p-2 tabular-nums">{row.weight}</td>')
m1.append('              <td className="p-2 tabular-nums">{row.temp}</td>')
m1.append('              <td className="p-2"><CostTile value={row.value}/></td>')
m1.append('              <td className="p-2"><Button variant="ghost" size="sm" className="h-6 w-6 p-0" onClick={() => setDetail(row)}><Eye className="h-3 w-3"/></Button></td>')
m1.append('            </tr>')
m1.append('          ))}')
m1.append('        </tbody></table>')
m1.append('      </div>')
m1.append('      <div className="text-[10px] text-muted-foreground text-right">{filteredTransit.length} shipments</div>')
m1.append('    </div>')
m1.append('  )')

# Tab 4: Analytics
m1.append('')
m1.append('  const tab4 = (')
m1.append('    <div className="space-y-3">')
m1.append('      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">')
m1.append('        <Card className="glass-subtle lct-chart-card"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Cost Trend (\\u20b9 K)</CardTitle></CardHeader><CardContent className="p-3"><LineChart data={charts.monthly}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Line type="monotone" dataKey="cost" stroke={TH.indigo} strokeWidth={2} dot={{r:3}}/></LineChart></CardContent></Card>')
m1.append('        <Card className="glass-subtle lct-chart-card"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Hub Throughput Comparison</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.cityLine}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="city" tick={{fontSize:9}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="throughput" fill={TH.indigo} radius={[4,4,0,0]}/></BarChart></CardContent></Card>')
m1.append('        <Card className="glass-subtle lct-chart-card"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Accuracy by Hub (%)</CardTitle></CardHeader><CardContent className="p-3"><LineChart data={charts.cityLine}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="city" tick={{fontSize:9}}/><YAxis domain={[85,100]} tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Line type="monotone" dataKey="accuracy" stroke={TH.emerald} strokeWidth={2} dot={{r:4}}/></LineChart></CardContent></Card>')
m1.append('        <Card className="glass-subtle lct-chart-card"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Cost per Hub (\\u20b9K)</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.cityLine} layout="vertical"><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis type="number" tick={{fontSize:10}}/><YAxis dataKey="city" type="category" width={75} tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="cost" fill={TH.amber} radius={[0,4,4,0]}/></BarChart></CardContent></Card>')
m1.append('      </div>')
m1.append('    </div>')
m1.append('  )')

# Tab 5: Hub Matrix
m1.append('')
m1.append('  const tab5 = (')
m1.append('    <div className="space-y-3">')
m1.append('      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">')
m1.append('        {WH_NAMES.map((wh, i) => {')
m1.append('          const ops = opsData.filter(o => o.warehouse === wh)')
m1.append('          const running = ops.filter(o => o.status === "Running").length')
m1.append('          const delayed = ops.filter(o => o.status === "Delayed").length')
m1.append('          const alerts = alertData.filter(a => a.warehouse === wh)')
m1.append('          const critical = alerts.filter(a => a.severity === "P1 Critical" && !a.resolved).length')
m1.append('          const avgHealth = Math.round(ops.reduce((s,o) => s+o.health, 0) / (ops.length||1))')
m1.append('          const avgThroughput = Math.round(ops.reduce((s,o) => s+o.throughput, 0) / (ops.length||1))')
m1.append('          return (')
m1.append('            <Card key={wh} className="glass-subtle lct-hub-card hover:border-indigo-300 dark:hover:border-indigo-700 transition-all">')
m1.append('              <CardContent className="p-4">')
m1.append('                <div className="flex items-center justify-between mb-3"><WhBadge wh={wh}/><HealthRing score={avgHealth}/></div>')
m1.append('                <div className="grid grid-cols-2 gap-2 text-center">')
m1.append('                  <div className="rounded-lg bg-blue-50 dark:bg-blue-900/20 p-2"><div className="text-lg font-black text-blue-600">{running}</div><div className="text-[9px] text-muted-foreground">Running</div></div>')
m1.append('                  <div className="rounded-lg bg-red-50 dark:bg-red-900/20 p-2"><div className="text-lg font-black text-red-600">{delayed}</div><div className="text-[9px] text-muted-foreground">Delayed</div></div>')
m1.append('                  <div className="rounded-lg bg-amber-50 dark:bg-amber-900/20 p-2"><div className="text-lg font-black text-amber-600">{critical}</div><div className="text-[9px] text-muted-foreground">Critical</div></div>')
m1.append('                  <div className="rounded-lg bg-emerald-50 dark:bg-emerald-900/20 p-2"><div className="text-lg font-black text-emerald-600">{avgThroughput}</div><div className="text-[9px] text-muted-foreground">Avg Thruput</div></div>')
m1.append('                </div>')
m1.append('              </CardContent>')
m1.append('            </Card>')
m1.append('          )')
m1.append('        })}')
m1.append('      </div>')
m1.append('    </div>')
m1.append('  )')

# Main Return
m1.append('')
m1.append('  const tabs = [')
m1.append('    {key:"overview",label:"Overview",icon:<Radar className="h-3.5 w-3.5"/>,content:tab0},')
m1.append('    {key:"operations",label:"Operations",icon:<Gauge className="h-3.5 w-3.5"/>,content:tab1},')
m1.append('    {key:"alerts",label:"Alert Center",icon:<AlertTriangle className="h-3.5 w-3.5"/>,content:tab2},')
m1.append('    {key:"transit",label:"Transit",icon:<Truck className="h-3.5 w-3.5"/>,content:tab3},')
m1.append('    {key:"analytics",label:"Analytics",icon:<BarChart3 className="h-3.5 w-3.5"/>,content:tab4},')
m1.append('    {key:"hubs",label:"Hub Matrix",icon:<Globe className="h-3.5 w-3.5"/>,content:tab5},')
m1.append('  ]')
m1.append('')
m1.append('  return (')
m1.append('    <div className="space-y-4 p-4">')
m1.append('      <PageHeader title="Logistics Control Tower" description="Real-time cross-warehouse operations monitoring, alert management, and transit tracking" icon={<MonitorSmartphone className="h-5 w-5 text-indigo-600"/>}/>')

# Live status indicator
m1.append('      <div className="flex items-center gap-3 flex-wrap">')
m1.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-100 dark:bg-emerald-900/30"><span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"/> <span className="text-[10px] font-semibold text-emerald-700 dark:text-emerald-300">LIVE</span></div>')
m1.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-blue-100 dark:bg-blue-900/30"><span className="text-[10px] font-semibold text-blue-700 dark:text-blue-300">8 Hubs Connected</span></div>')
m1.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-indigo-100 dark:bg-indigo-900/30"><span className="text-[10px] font-semibold text-indigo-700 dark:text-indigo-300">Network Score: 91</span></div>')
m1.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-amber-100 dark:bg-amber-900/30"><span className="text-[10px] font-semibold text-amber-700 dark:text-amber-300">3 Active Incidents</span></div>')
m1.append('      </div>')

m1.append('      <Tabs value={tab} onValueChange={setTab}>')
m1.append('        <TabsList className="bg-gradient-to-r from-indigo-500/10 to-blue-500/10 p-0.5 h-9">')
m1.append('          {tabs.map(t => <TabsTrigger key={t.key} value={t.key} className="text-xs gap-1.5 data-[state=active]:bg-indigo-600 data-[state=active]:text-white">{t.icon}{t.label}</TabsTrigger>)}')
m1.append('        </TabsList>')
m1.append('        {tabs.map(t => tab === t.key && <div key={t.key} className="mt-3">{t.content}</div>)}')
m1.append('      </Tabs>')

# Detail Sheet
m1.append('      <Sheet open={!!detail} onOpenChange={() => setDetail(null)}>')
m1.append('        <SheetContent className="w-[420px] overflow-y-auto">')
m1.append('          <SheetHeader><SheetTitle className="text-sm">Detail View</SheetTitle></SheetHeader>')
m1.append('          {detail && (')
m1.append('            <div className="mt-4 space-y-3">')
m1.append('              <div className="rounded-lg bg-gradient-to-r from-indigo-50 to-blue-50 dark:from-indigo-900/20 dark:to-blue-900/20 p-4"><div className="text-lg font-bold">Record Details</div><div className="text-xs text-muted-foreground mt-1">Full information for selected item</div></div>')
m1.append('              {Object.entries(detail).map(([k, v]) => <div key={k} className="flex items-center justify-between py-1.5 border-b border-border/50"><span className="text-xs font-medium text-muted-foreground">{k}</span><span className="text-xs font-semibold tabular-nums">{String(v)}</span></div>)}')
m1.append('            </div>')
m1.append('          )}')
m1.append('        </SheetContent>')
m1.append('      </Sheet>')
m1.append('    </div>')
m1.append('  )')
m1.append('}')

m1_content = '\n'.join(m1)

# ═══════════════════════════════════════════════════════════════════════
# MODULE 2: Warehouse Smart Picking
# ═══════════════════════════════════════════════════════════════════════
m2 = []
m2.append('"use client"')
m2.append('')
m2.append('import { useState, useMemo } from "react"')
m2.append('import {')
m2.append('  AreaChart, Area, BarChart, Bar, PieChart, Pie, Cell,')
m2.append('  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip,')
m2.append('} from "recharts"')
m2.append('import {')
m2.append('  Search, Eye, ArrowUpDown, TrendingUp, TrendingDown, Clock, IndianRupee, Zap,')
m2.append('  AlertTriangle, Users, BarChart3, MapPin, Package, Box, CheckCircle, XCircle, Activity, Timer, ShieldCheck, Star, Target, Crosshair, Brain, Sparkles, ShoppingCart, Warehouse, ArrowRight, ListOrdered, Waypoints, Route, Footprints, ChevronRight, Pickaxe, HandMetal')
m2.append('} from "lucide-react"')
m2.append('import { PageHeader } from "@/components/shared/page-header"')
m2.append('import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"')
m2.append('import { Input } from "@/components/ui/input"')
m2.append('import { Button } from "@/components/ui/button"')
m2.append('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
m2.append('import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"')
m2.append('')
m2.append('const PICK_METHODS = ["Zone Picking","Batch Picking","Wave Picking","Cluster Picking","Discrete Picking","Goods-to-Person","Voice Picking","Pick-to-Light"] as const')
m2.append('const PICK_EMOJI: Record<string,string> = {["Zone Picking"]:"\U0001f3af",["Batch Picking"]:"\U0001f4e6",["Wave Picking"]:"\U0001f30a",["Cluster Picking"]:"\U0001f465",["Discrete Picking"]:"\U0001f4e5",["Goods-to-Person"]:"\U0001f916",["Voice Picking"]:"\U0001f3a4",["Pick-to-Light"]:"\U0001f4a1"}')
m2.append('const PICK_STS = ["Assigned","In Progress","Completed","Paused","Cancelled","Exception"] as const')
m2.append('const ZONES = ["Zone A - Fast Movers","Zone B - Medium","Zone C - Slow Movers","Zone D - Bulk","Zone E - Hazmat","Zone F - Cold","Zone G - High Value","Zone H - Returns"] as const')
m2.append('const PRIORITIES = ["Urgent","High","Medium","Low","Economy"] as const')
m2.append('const SKU_CATS = ["Electronics","Apparel","FMCG","Pharma","Auto Parts","Home Decor","Sports","Books"] as const')
m2.append('const SLOT_TYPES = ["Pallet Rack","Shelf Bin","Floor Stack","Flow Rack","Carton Flow","Mezzanine","Mobile Rack","ASRS"] as const')
m2.append('const PATH_ALGOS = ["S-Shape","Largest Gap","Midpoint","Composite","Optimal AI","Nearest Neighbor","Zigzag","Return"] as const')
m2.append('const ERR_TYPES = ["Wrong SKU","Wrong Qty","Damaged","Short Ship","Location Error","Label Mismatch","Weight Mismatch","QC Fail"] as const')
m2.append('const MO = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"] as const')
m2.append('const TH = {emerald:"#059669",blue:"#3b82f6",amber:"#d97706",rose:"#e11d48",violet:"#7c3aed",cyan:"#0891b2",indigo:"#4f46e5",orange:"#f97316"}')
m2.append('const PC = [TH.emerald,TH.blue,TH.amber,TH.rose,TH.violet,TH.cyan,TH.indigo,TH.orange]')

m2.append('')
m2.append('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297 + 233280) * 10000; return x - Math.floor(x) }')
m2.append('function ri(a: number, b: number, s: number): number { return Math.floor(seededRandom(s) * (b - a + 1)) + a }')
m2.append('function pick<T>(arr: readonly T[], s: number): T { return arr[Math.abs(s) % arr.length] }')
m2.append('function filterData<T>(d: T[], q: string): T[] { if (!q) return d; const l = q.toLowerCase(); return d.filter(i => Object.values(i as unknown as Record<string, string | number>).some(v => String(v).toLowerCase().includes(l))) }')
m2.append('function sortedData<T>(d: T[], f: string, dir: "asc" | "desc"): T[] { return [...d].sort((a, b) => { const av = (a as unknown as Record<string, string | number>)[f], bv = (b as unknown as Record<string, string | number>)[f]; if (typeof av === "number" && typeof bv === "number") return dir === "asc" ? av - bv : bv - av; return dir === "asc" ? String(av ?? "").localeCompare(String(bv ?? "")) : String(bv ?? "").localeCompare(String(av ?? "")) }) }')

# --- Visual Components ---
m2.append('')
m2.append('/* 18 Visual Components */')
m2.append('function PickMethodBadge({ m }: { m: string }) {')
m2.append('  const cl: Record<string,string> = {["Zone Picking"]:"bg-emerald-100 text-emerald-700",["Batch Picking"]:"bg-blue-100 text-blue-700",["Wave Picking"]:"bg-amber-100 text-amber-700",["Cluster Picking"]:"bg-violet-100 text-violet-700",["Discrete Picking"]:"bg-cyan-100 text-cyan-700",["Goods-to-Person"]:"bg-indigo-100 text-indigo-700",["Voice Picking"]:"bg-rose-100 text-rose-700",["Pick-to-Light"]:"bg-orange-100 text-orange-700"}')
m2.append('  return <span className={"wsp-method inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium " + (cl[m]||"bg-gray-100")}>{PICK_EMOJI[m]} {m}</span>')
m2.append('}')
m2.append('function PickStatusBadge({ s }: { s: string }) {')
m2.append('  const cl: Record<string,string> = {Assigned:"bg-blue-100 text-blue-700","In Progress":"bg-amber-100 text-amber-700 animate-pulse",Completed:"bg-emerald-100 text-emerald-700",Paused:"bg-slate-100 text-slate-600",Cancelled:"bg-gray-100 text-gray-500",Exception:"bg-red-100 text-red-700 shadow-[0_0_8px_oklch(0.55_0.22_25/0.3)]"}')
m2.append('  return <span className={"wsp-status inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cl[s]||"bg-gray-100")}>\u25cf {s}</span>')
m2.append('}')
m2.append('function ZoneBadge({ z }: { z: string }) {')
m2.append('  const code = z.split(" - ")[0]')
m2.append('  const cl: Record<string,string> = {"Zone A":"bg-emerald-50 text-emerald-700","Zone B":"bg-blue-50 text-blue-700","Zone C":"bg-amber-50 text-amber-700","Zone D":"bg-slate-50 text-slate-700","Zone E":"bg-red-50 text-red-700","Zone F":"bg-cyan-50 text-cyan-700","Zone G":"bg-violet-50 text-violet-700","Zone H":"bg-rose-50 text-rose-700"}')
m2.append('  return <span className={"wsp-zone inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold " + (cl[code]||"bg-gray-50") + " dark:bg-opacity-20"}>\U0001f4cd {code}</span>')
m2.append('}')
m2.append('function PriorityBadge({ p }: { p: string }) {')
m2.append('  const cl: Record<string,string> = {Urgent:"bg-red-100 text-red-700 shadow-[0_0_8px_oklch(0.55_0.22_25/0.3)]",High:"bg-orange-100 text-orange-700",Medium:"bg-amber-100 text-amber-700",Low:"bg-blue-100 text-blue-700",Economy:"bg-slate-100 text-slate-600"}')
m2.append('  const emoji: Record<string,string> = {Urgent:"\U0001f534",High:"\U0001f7e0",Medium:"\U0001f7e1",Low:"\U0001f535",Economy:"\u26aa"}')
m2.append('  return <span className={"wsp-priority inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold " + (cl[p]||"bg-gray-100")}>{emoji[p]} {p}</span>')
m2.append('}')
m2.append('function SkuCatBadge({ c }: { c: string }) {')
m2.append('  const cl: Record<string,string> = {Electronics:"bg-indigo-100 text-indigo-700",Apparel:"bg-pink-100 text-pink-700",FMCG:"bg-emerald-100 text-emerald-700",Pharma:"bg-cyan-100 text-cyan-700","Auto Parts":"bg-amber-100 text-amber-700","Home Decor":"bg-violet-100 text-violet-700",Sports:"bg-orange-100 text-orange-700",Books:"bg-rose-100 text-rose-700"}')
m2.append('  return <span className={"wsp-sku inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium " + (cl[c]||"bg-gray-100")}>{c}</span>')
m2.append('}')
m2.append('function SlotTypeBadge({ t }: { t: string }) {')
m2.append('  return <span className="wsp-slot inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-medium bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300">\U0001f4c1 {t}</span>')
m2.append('}')
m2.append('function AlgoBadge({ a }: { a: string }) {')
m2.append('  const ai = a.includes("AI") || a.includes("Optimal")')
m2.append('  return <span className={"wsp-algo inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium " + (ai ? "bg-gradient-to-r from-violet-100 to-indigo-100 text-violet-700 dark:from-violet-900/30 dark:to-indigo-900/30" : "bg-slate-100 text-slate-700")}>{ai ? "\U0001f916" : "\U0001f527"} {a}</span>')
m2.append('}')
m2.append('function ErrTypeBadge({ t }: { t: string }) {')
m2.append('  return <span className="wsp-err inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300">\u274c {t}</span>')
m2.append('}')
m2.append('function PickerBadge({ name, score }: { name: string; score: number }) {')
m2.append('  const c = score >= 95 ? "text-emerald-600" : score >= 85 ? "text-blue-600" : score >= 70 ? "text-amber-600" : "text-red-600"')
m2.append('  return <span className={"wsp-picker inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-[10px] font-semibold " + c}><Footprints className="h-3 w-3"/>{name} <span className="font-black tabular-nums">{score}%</span></span>')
m2.append('}')
m2.append('function AccuracyGauge({ value }: { value: number }) {')
m2.append('  const c = value >= 99 ? "text-emerald-600" : value >= 97 ? "text-blue-600" : value >= 95 ? "text-amber-600" : "text-red-600"')
m2.append('  return <div className="wsp-accuracy flex items-center gap-1"><span className={"text-sm font-black tabular-nums " + c}>{value}%</span><div className="flex-1 h-1.5 rounded-full bg-gray-200 dark:bg-gray-700"><div className={"h-full rounded-full transition-all " + c.replace("text-","bg-")} style={{width: value + "%"}}/></div></div>')
m2.append('}')
m2.append('function SpeedTile({ value, unit }: { value: number; unit: string }) {')
m2.append('  return <div className="wsp-speed text-right"><div className="text-sm font-bold tabular-nums">{value}<span className="text-[10px] text-muted-foreground ml-0.5">{unit}</span></div></div>')
m2.append('}')
m2.append('function PickRateBar({ picks, target }: { picks: number; target: number }) {')
m2.append('  const pct = Math.round((picks / target) * 100)')
m2.append('  const c = pct >= 100 ? "bg-emerald-500" : pct >= 80 ? "bg-blue-500" : pct >= 60 ? "bg-amber-500" : "bg-red-500"')
m2.append('  return <div className="wsp-rate-bar flex items-center gap-2"><div className="flex-1 h-2 rounded-full bg-gray-200 dark:bg-gray-700"><div className={"h-full rounded-full transition-all " + c} style={{width: Math.min(pct,100) + "%"}}/></div><span className="text-[10px] font-bold tabular-nums">{picks}/{target}</span></div>')
m2.append('}')
m2.append('function TravelDistTile({ meters }: { meters: number }) {')
m2.append('  const km = (meters / 1000).toFixed(1)')
m2.append('  return <span className="wsp-travel text-xs font-medium tabular-nums text-violet-600 dark:text-violet-400">{km} km</span>')
m2.append('}')
m2.append('function UPHGauge({ uph }: { uph: number }) {')
m2.append('  const c = uph >= 120 ? "text-emerald-600" : uph >= 100 ? "text-blue-600" : uph >= 80 ? "text-amber-600" : "text-red-600"')
m2.append('  return <div className="wsp-uph flex items-center gap-1"><span className={"text-sm font-black tabular-nums " + c}>{uph}</span><span className="text-[9px] text-muted-foreground">UPH</span></div>')
m2.append('}')
m2.append('function EffortScore({ score }: { score: number }) {')
m2.append('  const c = score >= 90 ? "bg-emerald-100 text-emerald-700" : score >= 70 ? "bg-blue-100 text-blue-700" : score >= 50 ? "bg-amber-100 text-amber-700" : "bg-red-100 text-red-700"')
m2.append('  return <span className={"wsp-effort inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-bold " + c}>{score}/100</span>')
m2.append('}')
m2.append('function StarRating({ value }: { value: number }) {')
m2.append('  return <span className="wsp-stars inline-flex gap-0.5">{"\u2605".repeat(value)}{"\u2606".repeat(5-value)}</span>')
m2.append('}')
m2.append('function ValueTile({ value, label, trend }: { value: string; label: string; trend: number }) {')
m2.append('  return <div className="wsp-val text-right"><div className="text-sm font-bold tabular-nums">{value}</div><div className="text-[10px] text-muted-foreground">{label}</div>{trend !== 0 && <div className={"text-[10px] font-semibold flex items-center justify-end gap-0.5 " + (trend > 0 ? "text-emerald-600" : "text-red-600")}>{trend > 0 ? <TrendingUp className="h-3 w-3"/> : <TrendingDown className="h-3 w-3"/>}{Math.abs(trend)}%</div>}</div>')
m2.append('}')

# --- Data Generation ---
m2.append('')
m2.append('function genPickTasks() {')
m2.append('  return Array.from({length: 80}, (_, i) => ({')
m2.append('    id: "PK-" + String(i+5001).padStart(4,"0"),')
m2.append('    method: pick(PICK_METHODS, i+1),')
m2.append('    status: pick(PICK_STS, i+2),')
m2.append('    zone: pick(ZONES, i+3),')
m2.append('    priority: pick(PRIORITIES, i+4),')
m2.append('    picker: pick(["Arun K.","Bhavna S.","Deepak R.","Esha P.","Farhan M.","Geeta T."], i+5),')
m2.append('    pickerScore: ri(72, 99, i+6),')
m2.append('    sku: "SKU-" + String(ri(1000,9999,i+7)),')
m2.append('    skuCat: pick(SKU_CATS, i+8),')
m2.append('    slot: pick(SLOT_TYPES, i+9),')
m2.append('    location: "LOC-" + String(ri(1,999,i+10)).padStart(4,"0") + "-" + pick(["A","B","C","D"], i+11) + "-" + ri(1,6,i+12),')
m2.append('    qty: ri(1, 50, i+13),')
m2.append('    targetQty: ri(10, 60, i+14),')
m2.append('    picksPerHr: ri(65, 150, i+15),')
m2.append('    accuracy: ri(92, 100, i+16),')
m2.append('    travelDist: ri(200, 3500, i+17),')
m2.append('    effortScore: ri(40, 98, i+18),')
m2.append('    algo: pick(PATH_ALGOS, i+19),')
m2.append('    itemsTotal: ri(5, 120, i+20),')
m2.append('    orderCount: ri(1, 15, i+21),')
m2.append('    startTime: ri(0,23) + ":" + String(ri(0,59,i+22)).padStart(2,"0"),')
m2.append('    duration: ri(3, 90, i+23) + " min",')
m2.append('  }))')
m2.append('}')
m2.append('')
m2.append('function genExceptions() {')
m2.append('  return Array.from({length: 55}, (_, i) => ({')
m2.append('    id: "EX-" + String(i+6001).padStart(4,"0"),')
m2.append('    taskId: "PK-" + String(ri(5001,5080,i+1)).padStart(4,"0"),')
m2.append('    type: pick(ERR_TYPES, i+2),')
m2.append('    severity: pick(["Critical","Major","Minor","Info"], i+3),')
m2.append('    zone: pick(ZONES, i+4),')
m2.append('    picker: pick(["Arun K.","Bhavna S.","Deepak R.","Esha P.","Farhan M.","Geeta T."], i+5),')
m2.append('    resolved: i % 3 !== 0,')
m2.append('    rootCause: pick(["Human Error","System Glitch","Wrong Label","Inventory Mismatch","Damaged Stock","Equipment Failure"], i+6),')
m2.append('    action: pick(["Re-pick","Adjust Qty","Replace Item","Investigate","Log and Skip","Escalate"], i+7),')
m2.append('    costImpact: ri(0, 50, i+8),')
m2.append('  }))')
m2.append('}')
m2.append('')
m2.append('function genPickers() {')
m2.append('  return ["Arun K.","Bhavna S.","Deepak R.","Esha P.","Farhan M.","Geeta T."].map((name, i) => ({')
m2.append('    name,')
m2.append('    uph: ri(80, 145, i+1),')
m2.append('    accuracy: ri(93, 100, i+2),')
m2.append('    totalPicks: ri(2000, 8000, i+3),')
m2.append('    avgDist: ri(800, 2500, i+4),')
m2.append('    shift: pick(["Morning","Afternoon","Night"], i+5),')
m2.append('    zone: pick(ZONES, i+6),')
m2.append('    score: ri(75, 99, i+7),')
m2.append('    rating: ri(3, 5, i+8),')
m2.append('    exceptions: ri(0, 25, i+9),')
m2.append('  }))')
m2.append('}')

# --- Chart Data ---
m2.append('')
m2.append('function genCharts() {')
m2.append('  const hourly = Array.from({length:12}, (_, i) => ({ hour: (8+i) + ":00", picks: ri(200,600,i), accuracy: ri(94,100,i+12), errors: ri(0,15,i+24) }))')
m2.append('  const methodPie = PICK_METHODS.map((m, i) => ({ name: m.split(" ")[0], value: ri(80,400,i) }))')
m2.append('  const zoneBar = ZONES.map((z, i) => ({ name: z.split(" - ")[0], picks: ri(500,3000,i), accuracy: ri(93,100,i+8), time: ri(10,45,i+16) }))')
m2.append('  const monthly = MO.map((m, i) => ({ month: m, picks: ri(15000,45000,i), accuracy: ri(94,99,i+12), uph: ri(90,130,i+24) }))')
m2.append('  const algoBar = PATH_ALGOS.map((a, i) => ({ name: a.split(" ")[0], distance: ri(500,3000,i), time: ri(15,60,i+8), efficiency: ri(60,98,i+16) }))')
m2.append('  return { hourly, methodPie, zoneBar, monthly, algoBar }')
m2.append('}')

# --- Main Component ---
m2.append('')
m2.append('export default function WarehouseSmartPickingView() {')
m2.append('  const [tab, setTab] = useState("dashboard")')
m2.append('  const [search, setSearch] = useState("")')
m2.append('  const [sortField, setSortField] = useState("id")')
m2.append('  const [sortDir, setSortDir] = useState<"asc"|"desc">("asc")')
m2.append('  const [detail, setDetail] = useState<Record<string, unknown>|null>(null)')
m2.append('')
m2.append('  const pickTasks = useMemo(() => genPickTasks(), [])')
m2.append('  const exceptions = useMemo(() => genExceptions(), [])')
m2.append('  const pickers = useMemo(() => genPickers(), [])')
m2.append('  const charts = useMemo(() => genCharts(), [])')
m2.append('')
m2.append('  const filteredTasks = useMemo(() => sortedData(filterData(pickTasks, search), sortField, sortDir), [pickTasks, search, sortField, sortDir])')
m2.append('  const filteredEx = useMemo(() => sortedData(filterData(exceptions, search), sortField, sortDir), [exceptions, search, sortField, sortDir])')
m2.append('')
m2.append('  const toggleSort = (f: string) => { if (sortField === f) setSortDir(d => d === "asc" ? "desc" : "asc"); else { setSortField(f); setSortDir("asc") } }')

# Tab 0: Dashboard
m2.append('')
m2.append('  const tab0 = (')
m2.append('    <div className="space-y-4">')
m2.append('      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">')
m2.append('        {[["Total Picks Today","4,218","12.3%",<Package key="p"/>],["Avg UPH","112","+5.1%",<Zap key="z"/>],["Accuracy Rate","97.8%","+0.3%",<Target key="t"/>],["Active Pickers","6","0",<Users key="u"/>],["Exceptions","8","-15%",<AlertTriangle key="a"/>],["Avg Travel","1.8 km","-8%",<Route key="r"/>],["Path Efficiency","91%","+3%",<Waypoints key="w"/>],["Cost per Pick","\\u20b94.2","-6%",<IndianRupee key="r"/>]].map(([label,val,tr,icon], i) => (')
m2.append('          <Card key={i} className="glass-subtle wsp-kpi"><CardContent className="p-3"><div className="flex items-center gap-2.5">{icon}<div><div className="text-[10px] text-muted-foreground">{String(label)}</div><div className="text-lg font-black tabular-nums">{String(val)}</div><div className={"text-[10px] font-semibold " + (String(tr).startsWith("-")||String(tr).startsWith("0") ? "text-emerald-600" : "text-emerald-600")}>{String(tr)}</div></div></div></CardContent></Card>')
m2.append('        ))}')
m2.append('      </div>')
m2.append('      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">')
m2.append('        <Card className="glass-subtle wsp-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Hourly Pick Volume</CardTitle></CardHeader><CardContent className="p-3"><AreaChart data={charts.hourly}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="hour" tick={{fontSize:9}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Area type="monotone" dataKey="picks" stroke={TH.emerald} fill={TH.emerald} fillOpacity={0.3}/></AreaChart></CardContent></Card>')
m2.append('        <Card className="glass-subtle wsp-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Pick Method Distribution</CardTitle></CardHeader><CardContent className="p-3"><PieChart><Pie data={charts.methodPie} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({name}: {name:string}) => <text x={0} y={0} fill="currentColor" fontSize={9} textAnchor="middle">{name}</text>}>{charts.methodPie.map((_,i) => <Cell key={i} fill={PC[i%PC.length]}/>)}</Pie><Tooltip/></PieChart></CardContent></Card>')
m2.append('        <Card className="glass-subtle wsp-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Zone Performance</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.zoneBar}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="name" tick={{fontSize:9}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="picks" fill={TH.emerald} radius={[4,4,0,0]}/></BarChart></CardContent></Card>')
m2.append('        <Card className="glass-subtle wsp-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Path Algorithm Efficiency (%)</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.algoBar} layout="vertical"><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis type="number" domain={[0,100]} tick={{fontSize:10}}/><YAxis dataKey="name" type="category" width={65} tick={{fontSize:9}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="efficiency" radius={[0,4,4,0]}>{charts.algoBar.map((_,i) => <Cell key={i} fill={charts.algoBar[i].efficiency > 90 ? TH.emerald : charts.algoBar[i].efficiency > 80 ? TH.blue : charts.algoBar[i].efficiency > 70 ? TH.amber : TH.rose}/>)}</Bar></BarChart></CardContent></Card>')
m2.append('      </div>')
m2.append('    </div>')
m2.append('  )')

# Tab 1: Pick Tasks
m2.append('')
m2.append('  const tab1 = (')
m2.append('    <div className="space-y-3">')
m2.append('      <div className="flex items-center gap-2"><div className="relative flex-1"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground"/><Input className="h-8 pl-8 text-xs" placeholder="Search pick tasks..." value={search} onChange={e => setSearch(e.target.value)}/></div></div>')
m2.append('      <div className="rounded-lg border overflow-auto max-h-[calc(100vh-280px)]">')
m2.append('        <table className="w-full text-xs"><thead className="bg-emerald-50 dark:bg-emerald-900/20 sticky top-0 z-10"><tr>')
m2.append('          <th className="p-2 text-left font-semibold cursor-pointer select-none" onClick={() => toggleSort("id")}>ID <ArrowUpDown className="inline h-3 w-3 ml-0.5 opacity-50"/></th>')
m2.append('          <th className="p-2 text-left font-semibold">Method</th>')
m2.append('          <th className="p-2 text-left font-semibold">Status</th>')
m2.append('          <th className="p-2 text-left font-semibold">Zone</th>')
m2.append('          <th className="p-2 text-left font-semibold">Priority</th>')
m2.append('          <th className="p-2 text-left font-semibold">Picker</th>')
m2.append('          <th className="p-2 text-left font-semibold">SKU</th>')
m2.append('          <th className="p-2 text-left font-semibold">Qty</th>')
m2.append('          <th className="p-2 text-left font-semibold">UPH</th>')
m2.append('          <th className="p-2 text-left font-semibold">Accuracy</th>')
m2.append('          <th className="p-2 text-left font-semibold">Travel</th>')
m2.append('          <th className="p-2 text-left font-semibold">Effort</th>')
m2.append('          <th className="p-2 text-left font-semibold">Algo</th>')
m2.append('          <th className="p-2"></th>')
m2.append('        </tr></thead><tbody className="divide-y">')
m2.append('          {filteredTasks.map(row => (')
m2.append('            <tr key={row.id} className="hover:bg-emerald-50/50 dark:hover:bg-emerald-900/10 transition-colors">')
m2.append('              <td className="p-2 font-mono font-medium">{row.id}</td>')
m2.append('              <td className="p-2"><PickMethodBadge m={row.method}/></td>')
m2.append('              <td className="p-2"><PickStatusBadge s={row.status}/></td>')
m2.append('              <td className="p-2"><ZoneBadge z={row.zone}/></td>')
m2.append('              <td className="p-2"><PriorityBadge p={row.priority}/></td>')
m2.append('              <td className="p-2"><PickerBadge name={row.picker} score={row.pickerScore}/></td>')
m2.append('              <td className="p-2"><div><SkuCatBadge c={row.skuCat}/><div className="font-mono text-[9px] text-muted-foreground mt-0.5">{row.sku}</div></div></td>')
m2.append('              <td className="p-2"><PickRateBar picks={row.qty} target={row.targetQty}/></td>')
m2.append('              <td className="p-2"><UPHGauge uph={row.picksPerHr}/></td>')
m2.append('              <td className="p-2"><AccuracyGauge value={row.accuracy}/></td>')
m2.append('              <td className="p-2"><TravelDistTile meters={row.travelDist}/></td>')
m2.append('              <td className="p-2"><EffortScore score={row.effortScore}/></td>')
m2.append('              <td className="p-2"><AlgoBadge a={row.algo}/></td>')
m2.append('              <td className="p-2"><Button variant="ghost" size="sm" className="h-6 w-6 p-0" onClick={() => setDetail(row)}><Eye className="h-3 w-3"/></Button></td>')
m2.append('            </tr>')
m2.append('          ))}')
m2.append('        </tbody></table>')
m2.append('      </div>')
m2.append('      <div className="text-[10px] text-muted-foreground text-right">{filteredTasks.length} tasks</div>')
m2.append('    </div>')
m2.append('  )')

# Tab 2: Picker Leaderboard
m2.append('')
m2.append('  const tab2 = (')
m2.append('    <div className="space-y-3">')
m2.append('      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">')
m2.append('        {pickers.sort((a,b) => b.score - a.score).map((p, i) => (')
m2.append('          <Card key={p.name} className="glass-subtle wsp-picker-card hover:border-emerald-300 dark:hover:border-emerald-700 transition-all">')
m2.append('            <CardContent className="p-4">')
m2.append('              <div className="flex items-center justify-between mb-3">')
m2.append('                <div className="flex items-center gap-2"><div className={"w-8 h-8 rounded-full flex items-center justify-center text-sm font-black text-white " + (i === 0 ? "bg-gradient-to-br from-amber-400 to-amber-600" : i === 1 ? "bg-gradient-to-br from-slate-300 to-slate-500" : i === 2 ? "bg-gradient-to-br from-amber-600 to-amber-800" : "bg-gradient-to-br from-blue-400 to-blue-600")}>#{i+1}</div><div><div className="text-sm font-bold">{p.name}</div><div className="text-[10px] text-muted-foreground">{p.shift} Shift</div></div></div>')
m2.append('                <EffortScore score={p.score}/>')
m2.append('              </div>')
m2.append('              <div className="grid grid-cols-2 gap-2">')
m2.append('                <div className="rounded-lg bg-emerald-50 dark:bg-emerald-900/20 p-2 text-center"><UPHGauge uph={p.uph}/></div>')
m2.append('                <div className="rounded-lg bg-blue-50 dark:bg-blue-900/20 p-2 text-center"><AccuracyGauge value={p.accuracy}/></div>')
m2.append('                <div className="rounded-lg bg-amber-50 dark:bg-amber-900/20 p-2 text-center"><SpeedTile value={p.totalPicks.toLocaleString()} unit="picks"/></div>')
m2.append('                <div className="rounded-lg bg-violet-50 dark:bg-violet-900/20 p-2 text-center"><TravelDistTile meters={p.avgDist}/></div>')
m2.append('              </div>')
m2.append('              <div className="flex items-center justify-between mt-2 pt-2 border-t"><StarRating value={p.rating}/><span className="text-[10px] text-muted-foreground">{p.exceptions} exceptions</span></div>')
m2.append('            </CardContent>')
m2.append('          </Card>')
m2.append('        ))}')
m2.append('      </div>')
m2.append('    </div>')
m2.append('  )')

# Tab 3: Exception Log
m2.append('')
m2.append('  const tab3 = (')
m2.append('    <div className="space-y-3">')
m2.append('      <div className="flex items-center gap-2"><div className="relative flex-1"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground"/><Input className="h-8 pl-8 text-xs" placeholder="Search exceptions..." value={search} onChange={e => setSearch(e.target.value)}/></div></div>')
m2.append('      <div className="rounded-lg border overflow-auto max-h-[calc(100vh-280px)]">')
m2.append('        <table className="w-full text-xs"><thead className="bg-red-50 dark:bg-red-900/20 sticky top-0 z-10"><tr>')
m2.append('          <th className="p-2 text-left font-semibold">ID</th>')
m2.append('          <th className="p-2 text-left font-semibold">Task</th>')
m2.append('          <th className="p-2 text-left font-semibold">Error Type</th>')
m2.append('          <th className="p-2 text-left font-semibold">Severity</th>')
m2.append('          <th className="p-2 text-left font-semibold">Zone</th>')
m2.append('          <th className="p-2 text-left font-semibold">Picker</th>')
m2.append('          <th className="p-2 text-left font-semibold">Status</th>')
m2.append('          <th className="p-2 text-left font-semibold">Root Cause</th>')
m2.append('          <th className="p-2 text-left font-semibold">Action</th>')
m2.append('          <th className="p-2 text-left font-semibold">Cost</th>')
m2.append('        </tr></thead><tbody className="divide-y">')
m2.append('          {filteredEx.map(row => (')
m2.append('            <tr key={row.id} className="hover:bg-red-50/50 dark:hover:bg-red-900/10 transition-colors">')
m2.append('              <td className="p-2 font-mono font-medium">{row.id}</td>')
m2.append('              <td className="p-2 font-mono">{row.taskId}</td>')
m2.append('              <td className="p-2"><ErrTypeBadge t={row.type}/></td>')
m2.append('              <td className="p-2"><PriorityBadge p={row.severity}/></td>')
m2.append('              <td className="p-2"><ZoneBadge z={row.zone}/></td>')
m2.append('              <td className="p-2 text-muted-foreground">{row.picker}</td>')
m2.append('              <td className="p-2"><span className={"inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (row.resolved ? "bg-emerald-100 text-emerald-700" : "bg-red-100 text-red-700 animate-pulse")}>{row.resolved ? "\\u2705 Resolved" : "\\U0001f534 Open"}</span></td>')
m2.append('              <td className="p-2 text-muted-foreground">{row.rootCause}</td>')
m2.append('              <td className="p-2 text-muted-foreground">{row.action}</td>')
m2.append('              <td className="p-2 numeric-cell tabular-nums">\\u20b9{row.costImpact}</td>')
m2.append('            </tr>')
m2.append('          ))}')
m2.append('        </tbody></table>')
m2.append('      </div>')
m2.append('      <div className="text-[10px] text-muted-foreground text-right">{filteredEx.length} exceptions</div>')
m2.append('    </div>')
m2.append('  )')

# Tab 4: Optimization Analytics
m2.append('')
m2.append('  const tab4 = (')
m2.append('    <div className="space-y-3">')
m2.append('      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">')
m2.append('        <Card className="glass-subtle wsp-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Monthly Pick Volume & UPH</CardTitle></CardHeader><CardContent className="p-3"><LineChart data={charts.monthly}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="month" tick={{fontSize:9}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Line type="monotone" dataKey="picks" stroke={TH.emerald} strokeWidth={2} dot={{r:3}}/><Line type="monotone" dataKey="uph" stroke={TH.blue} strokeWidth={2} dot={{r:3}}/></LineChart></CardContent></Card>')
m2.append('        <Card className="glass-subtle wsp-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Hourly Error Rate</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.hourly}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="hour" tick={{fontSize:9}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="errors" fill={TH.rose} radius={[4,4,0,0]}/></BarChart></CardContent></Card>')
m2.append('        <Card className="glass-subtle wsp-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Zone Accuracy Comparison (%)</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.zoneBar}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="name" tick={{fontSize:9}}/><YAxis domain={[90,100]} tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="accuracy" fill={TH.blue} radius={[4,4,0,0]}/></BarChart></CardContent></Card>')
m2.append('        <Card className="glass-subtle wsp-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Monthly Accuracy Trend (%)</CardTitle></CardHeader><CardContent className="p-3"><LineChart data={charts.monthly}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="month" tick={{fontSize:9}}/><YAxis domain={[93,100]} tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Line type="monotone" dataKey="accuracy" stroke={TH.emerald} strokeWidth={2} dot={{r:4}}/></LineChart></CardContent></Card>')
m2.append('      </div>')
m2.append('    </div>')
m2.append('  )')

# Tab 5: Slot Utilization
m2.append('')
m2.append('  const tab5 = (')
m2.append('    <div className="space-y-3">')
m2.append('      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">')
m2.append('        {ZONES.map((z, i) => {')
m2.append('          const zoneTasks = pickTasks.filter(t => t.zone === z)')
m2.append('          const avgUPH = Math.round(zoneTasks.reduce((s,t) => s+t.picksPerHr, 0) / (zoneTasks.length||1))')
m2.append('          const avgAcc = Math.round(zoneTasks.reduce((s,t) => s+t.accuracy, 0) / (zoneTasks.length||1))')
m2.append('          const avgEffort = Math.round(zoneTasks.reduce((s,t) => s+t.effortScore, 0) / (zoneTasks.length||1))')
m2.append('          const exCount = exceptions.filter(e => e.zone === z).length')
m2.append('          return (')
m2.append('            <Card key={z} className="glass-subtle wsp-zone-card hover:border-emerald-300 dark:hover:border-emerald-700 transition-all">')
m2.append('              <CardContent className="p-4">')
m2.append('                <div className="flex items-center justify-between mb-3"><ZoneBadge z={z}/><EffortScore score={avgEffort}/></div>')
m2.append('                <div className="grid grid-cols-2 gap-2 text-center">')
m2.append('                  <div className="rounded-lg bg-emerald-50 dark:bg-emerald-900/20 p-2"><UPHGauge uph={avgUPH}/></div>')
m2.append('                  <div className="rounded-lg bg-blue-50 dark:bg-blue-900/20 p-2"><AccuracyGauge value={avgAcc}/></div>')
m2.append('                  <div className="rounded-lg bg-violet-50 dark:bg-violet-900/20 p-2"><SpeedTile value={zoneTasks.length} unit="tasks"/></div>')
m2.append('                  <div className="rounded-lg bg-red-50 dark:bg-red-900/20 p-2"><div className="text-lg font-black text-red-600">{exCount}</div><div className="text-[9px] text-muted-foreground">Exceptions</div></div>')
m2.append('                </div>')
m2.append('              </CardContent>')
m2.append('            </Card>')
m2.append('          )')
m2.append('        })}')
m2.append('      </div>')
m2.append('    </div>')
m2.append('  )')

# Main Return
m2.append('')
m2.append('  const tabs = [')
m2.append('    {key:"dashboard",label:"Dashboard",icon:<Sparkles className="h-3.5 w-3.5"/>,content:tab0},')
m2.append('    {key:"tasks",label:"Pick Tasks",icon:<ListOrdered className="h-3.5 w-3.5"/>,content:tab1},')
m2.append('    {key:"pickers",label:"Pickers",icon:<Users className="h-3.5 w-3.5"/>,content:tab2},')
m2.append('    {key:"exceptions",label:"Exceptions",icon:<XCircle className="h-3.5 w-3.5"/>,content:tab3},')
m2.append('    {key:"analytics",label:"Analytics",icon:<Brain className="h-3.5 w-3.5"/>,content:tab4},')
m2.append('    {key:"zones",label:"Zones",icon:<Warehouse className="h-3.5 w-3.5"/>,content:tab5},')
m2.append('  ]')
m2.append('')
m2.append('  return (')
m2.append('    <div className="space-y-4 p-4">')
m2.append('      <PageHeader title="Warehouse Smart Picking" description="AI-powered pick optimization with real-time picker tracking, exception management, and path efficiency analytics" icon={<Crosshair className="h-5 w-5 text-emerald-600"/>}/>')
m2.append('      <div className="flex items-center gap-3 flex-wrap">')
m2.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-100 dark:bg-emerald-900/30"><Sparkles className="h-3 w-3 text-emerald-600"/><span className="text-[10px] font-semibold text-emerald-700 dark:text-emerald-300">AI Path Optimizer Active</span></div>')
m2.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-blue-100 dark:bg-blue-900/30"><span className="text-[10px] font-semibold text-blue-700 dark:text-blue-300">6 Pickers Online</span></div>')
m2.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-violet-100 dark:bg-violet-900/30"><span className="text-[10px] font-semibold text-violet-700 dark:text-violet-300">8 Zones Active</span></div>')
m2.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-amber-100 dark:bg-amber-900/30"><span className="text-[10px] font-semibold text-amber-700 dark:text-amber-300">8 Open Exceptions</span></div>')
m2.append('      </div>')
m2.append('      <Tabs value={tab} onValueChange={setTab}>')
m2.append('        <TabsList className="bg-gradient-to-r from-emerald-500/10 to-blue-500/10 p-0.5 h-9">')
m2.append('          {tabs.map(t => <TabsTrigger key={t.key} value={t.key} className="text-xs gap-1.5 data-[state=active]:bg-emerald-600 data-[state=active]:text-white">{t.icon}{t.label}</TabsTrigger>)}')
m2.append('        </TabsList>')
m2.append('        {tabs.map(t => tab === t.key && <div key={t.key} className="mt-3">{t.content}</div>)}')
m2.append('      </Tabs>')
m2.append('      <Sheet open={!!detail} onOpenChange={() => setDetail(null)}>')
m2.append('        <SheetContent className="w-[420px] overflow-y-auto">')
m2.append('          <SheetHeader><SheetTitle className="text-sm">Task Detail</SheetTitle></SheetHeader>')
m2.append('          {detail && (')
m2.append('            <div className="mt-4 space-y-3">')
m2.append('              <div className="rounded-lg bg-gradient-to-r from-emerald-50 to-blue-50 dark:from-emerald-900/20 dark:to-blue-900/20 p-4"><div className="text-lg font-bold">Record Details</div><div className="text-xs text-muted-foreground mt-1">Full information for selected item</div></div>')
m2.append('              {Object.entries(detail).map(([k, v]) => <div key={k} className="flex items-center justify-between py-1.5 border-b border-border/50"><span className="text-xs font-medium text-muted-foreground">{k}</span><span className="text-xs font-semibold tabular-nums">{String(v)}</span></div>)}')
m2.append('            </div>')
m2.append('          )}')
m2.append('        </SheetContent>')
m2.append('      </Sheet>')
m2.append('    </div>')
m2.append('  )')
m2.append('}')

m2_content = '\n'.join(m2)

# Write both files
out_dir = '/home/z/my-project/src/components/modules'

with open(os.path.join(out_dir, 'logistics-control-tower-view.tsx'), 'w') as f:
    f.write(m1_content)

with open(os.path.join(out_dir, 'warehouse-smart-picking-view.tsx'), 'w') as f:
    f.write(m2_content)

print(f"Module 1: logistics-control-tower-view.tsx - {len(m1_content)} chars, {len(m1)} lines")
print(f"Module 2: warehouse-smart-picking-view.tsx - {len(m2_content)} chars, {len(m2)} lines")
print("Both modules generated successfully!")
