#!/usr/bin/env python3
"""Generate R259 modules: supply-chain-resilience + logistics-procurement-command"""

import os

BASE = '/home/z/my-project/src/components/modules'

# ═══════════════════════════════════════════════════════════════════════
# MODULE 1: Supply Chain Resilience Hub
# ═══════════════════════════════════════════════════════════════════════
m1 = []
m1.append('"use client"')
m1.append('')
m1.append('import { useState, useMemo } from "react"')
m1.append('import {')
m1.append('  AreaChart, Area, BarChart, Bar, PieChart, Pie, Cell,')
m1.append('  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip,')
m1.append('} from "recharts"')
m1.append('import {')
m1.append('  Search, Eye, ArrowUpDown, TrendingUp, TrendingDown, Clock, IndianRupee, Zap,')
m1.append('  AlertTriangle, Users, BarChart3, MapPin, Package, Box, CheckCircle, XCircle, Activity, Timer, ShieldCheck, Star, Radio, Gauge, ShieldAlert, HeartPulse, Globe, ArrowRight, ChevronRight, RefreshCw, Download, Filter, TriangleAlert, CircleDot, Waypoints, Route, Warehouse, Truck, Plane, Ship, TrainFront')
m1.append('} from "lucide-react"')
m1.append('import { PageHeader } from "@/components/shared/page-header"')
m1.append('import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"')
m1.append('import { Input } from "@/components/ui/input"')
m1.append('import { Button } from "@/components/ui/button"')
m1.append('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
m1.append('import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"')
m1.append('')
m1.append('const RISK_TYPES = ["Supplier Failure","Transport Disruption","Demand Surge","Regulatory Change","Natural Disaster","Geopolitical Risk","Cyber Threat","Quality Issue","Labor Strike","Port Congestion"] as const')
m1.append('const RISK_EMOJI: Record<string,string> = {["Supplier Failure"]:"\U0001f4e5",["Transport Disruption"]:"\U0001f69b",["Demand Surge"]:"\U0001f4c8",["Regulatory Change"]:"\U0001f4dc",["Natural Disaster"]:"\U0001f30a",["Geopolitical Risk"]:"\U0001f5fa",["Cyber Threat"]:"\U0001f5a5",["Quality Issue"]:"\u274c",["Labor Strike"]:"\u2696\ufe0f",["Port Congestion"]:"\U0001f6a2"}')
m1.append('const RISK_SEVS = ["Critical","High","Medium","Low"] as const')
m1.append('const BCP_STS = ["Active","Draft","Testing","Expired","Under Review"] as const')
m1.append('const ALT_ROUTES = ["Air Freight","Rail Diversion","Alternate Port","Nearshoring","Safety Stock","Dual Sourcing","Buffer Inventory","Express Lane"] as const')
m1.append('const CITIES = ["Mumbai","Delhi","Bangalore","Chennai","Hyderabad","Kolkata","Pune","Ahmedabad","Jaipur","Lucknow","Coimbatore","Indore"] as const')
m1.append('const REGIONS = ["North India","South India","West India","East India","Central India","NE India"] as const')
m1.append('const SUPPLIERS = ["Tata Steel","Reliance Industries","Mahindra Logistics","Blue Star","Godrej Group","L&T","Bajaj Electricals","Hindalco","JSW Steel","Grasim"] as const')
m1.append('const MO = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"] as const')
m1.append('const TH = {red:"#dc2626",orange:"#ea580c",amber:"#d97706",blue:"#3b82f6",emerald:"#059669",violet:"#7c3aed",rose:"#e11d48",cyan:"#0891b2"}')
m1.append('const PC = [TH.red,TH.orange,TH.amber,TH.blue,TH.emerald,TH.violet,TH.rose,TH.cyan]')
m1.append('')
m1.append('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297 + 233280) * 10000; return x - Math.floor(x) }')
m1.append('function ri(a: number, b: number, s: number): number { return Math.floor(seededRandom(s) * (b - a + 1)) + a }')
m1.append('function pick<T>(arr: readonly T[], s: number): T { return arr[Math.abs(s) % arr.length] }')
m1.append('function filterData<T>(d: T[], q: string): T[] { if (!q) return d; const l = q.toLowerCase(); return d.filter(i => Object.values(i as unknown as Record<string, string | number>).some(v => String(v).toLowerCase().includes(l))) }')
m1.append('function sortedData<T>(d: T[], f: string, dir: "asc" | "desc"): T[] { return [...d].sort((a, b) => { const av = (a as unknown as Record<string, string | number>)[f], bv = (b as unknown as Record<string, string | number>)[f]; if (typeof av === "number" && typeof bv === "number") return dir === "asc" ? av - bv : bv - av; return dir === "asc" ? String(av ?? "").localeCompare(String(bv ?? "")) : String(bv ?? "").localeCompare(String(av ?? "")) }) }')

# Visual Components
m1.append('')
m1.append('/* 17 Visual Components */')
m1.append('function RiskTypeBadge({ t }: { t: string }) {')
m1.append('  const cl: Record<string,string> = {["Supplier Failure"]:"bg-red-100 text-red-700",["Transport Disruption"]:"bg-orange-100 text-orange-700",["Demand Surge"]:"bg-blue-100 text-blue-700",["Regulatory Change"]:"bg-amber-100 text-amber-700",["Natural Disaster"]:"bg-violet-100 text-violet-700",["Geopolitical Risk"]:"bg-slate-100 text-slate-700",["Cyber Threat"]:"bg-cyan-100 text-cyan-700",["Quality Issue"]:"bg-rose-100 text-rose-700",["Labor Strike"]:"bg-indigo-100 text-indigo-700",["Port Congestion"]:"bg-emerald-100 text-emerald-700"}')
m1.append('  return <span className={"scr-rt-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium " + (cl[t]||"bg-gray-100")}>{RISK_EMOJI[t]} {t}</span>')
m1.append('}')
m1.append('function RiskSevBadge({ s }: { s: string }) {')
m1.append('  const cl: Record<string,string> = {Critical:"bg-red-100 text-red-700 shadow-[0_0_8px_oklch(0.55_0.22_25/0.3)]",High:"bg-orange-100 text-orange-700",Medium:"bg-amber-100 text-amber-700",Low:"bg-blue-100 text-blue-700"}')
m1.append('  const emoji: Record<string,string> = {Critical:"\U0001f534",High:"\U0001f7e0",Medium:"\U0001f7e1",Low:"\U0001f535"}')
m1.append('  const pulse = s==="Critical" ? " animate-pulse" : ""')
m1.append('  return <span className={"scr-rs-badge inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold " + (cl[s]||"bg-gray-100") + pulse}>{emoji[s]} {s}</span>')
m1.append('}')
m1.append('function BcpStatusBadge({ s }: { s: string }) {')
m1.append('  const cl: Record<string,string> = {Active:"bg-emerald-100 text-emerald-700",Draft:"bg-blue-100 text-blue-700",Testing:"bg-amber-100 text-amber-700",Expired:"bg-gray-100 text-gray-500","Under Review":"bg-violet-100 text-violet-700"}')
m1.append('  return <span className={"scr-bcp-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cl[s]||"bg-gray-100")}>\u25cf {s}</span>')
m1.append('}')
m1.append('function AltRouteBadge({ r }: { r: string }) {')
m1.append('  const cl: Record<string,string> = {["Air Freight"]:"bg-violet-100 text-violet-700",["Rail Diversion"]:"bg-blue-100 text-blue-700",["Alternate Port"]:"bg-cyan-100 text-cyan-700",Nearshoring:"bg-emerald-100 text-emerald-700",["Safety Stock"]:"bg-amber-100 text-amber-700",["Dual Sourcing"]:"bg-indigo-100 text-indigo-700",["Buffer Inventory"]:"bg-rose-100 text-rose-700",["Express Lane"]:"bg-orange-100 text-orange-700"}')
m1.append('  return <span className={"scr-alt-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium " + (cl[r]||"bg-gray-100")}>{r}</span>')
m1.append('}')
m1.append('function CityBadge({ city }: { city: string }) {')
m1.append('  return <span className="scr-city inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-medium bg-cyan-50 text-cyan-700 dark:bg-cyan-900/30 dark:text-cyan-300">\U0001f4cd {city}</span>')
m1.append('}')
m1.append('function RegionBadge({ r }: { r: string }) {')
m1.append('  return <span className="scr-region inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-medium bg-indigo-50 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-300">{r}</span>')
m1.append('}')
m1.append('function SupplierBadge({ s }: { s: string }) {')
m1.append('  return <span className="scr-supp inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold bg-gradient-to-r from-blue-50 to-indigo-50 text-blue-700 dark:from-blue-900/30 dark:to-indigo-900/30 dark:text-blue-300">\U0001f3ed {s}</span>')
m1.append('}')
m1.append('function RiskScoreRing({ score }: { score: number }) {')
m1.append('  const c = score >= 80 ? "text-red-500" : score >= 60 ? "text-orange-500" : score >= 40 ? "text-amber-500" : "text-emerald-500"')
m1.append('  const label = score >= 80 ? "Critical" : score >= 60 ? "High" : score >= 40 ? "Medium" : "Low"')
m1.append('  return <div className="scr-score flex flex-col items-center"><div className={"text-3xl font-black tabular-nums " + c}>{score}</div><div className={"text-[10px] font-bold " + c}>{label}</div></div>')
m1.append('}')
m1.append('function ResilienceGauge({ value }: { value: number }) {')
m1.append('  const c = value >= 85 ? "text-emerald-600" : value >= 70 ? "text-blue-600" : value >= 55 ? "text-amber-600" : "text-red-600"')
m1.append('  return <div className="scr-resilience flex items-center gap-1"><span className={"text-sm font-black tabular-nums " + c}>{value}%</span><div className="flex-1 h-1.5 rounded-full bg-gray-200 dark:bg-gray-700"><div className={"h-full rounded-full transition-all " + c.replace("text-","bg-")} style={{width: value + "%"}}/></div></div>')
m1.append('}')
m1.append('function ImpactBar({ value, max }: { value: number; max: number }) {')
m1.append('  const pct = Math.round((value / max) * 100)')
m1.append('  const c = pct > 80 ? "bg-red-500" : pct > 60 ? "bg-orange-500" : pct > 40 ? "bg-amber-500" : "bg-blue-500"')
m1.append('  return <div className="scr-impact flex items-center gap-2 w-full"><div className="flex-1 h-2.5 rounded-full bg-gray-200 dark:bg-gray-700"><div className={"h-full rounded-full transition-all " + c} style={{width: pct + "%"}}/></div><span className="text-[10px] font-bold tabular-nums min-w-[40px] text-right">{value}</span></div>')
m1.append('}')
m1.append('function MitigationBar({ pct }: { pct: number }) {')
m1.append('  const c = pct >= 90 ? "bg-emerald-500" : pct >= 70 ? "bg-blue-500" : pct >= 50 ? "bg-amber-500" : "bg-red-500"')
m1.append('  return <div className="scr-mit flex items-center gap-1.5"><div className="flex-1 h-2 rounded-full bg-gray-200 dark:bg-gray-700"><div className={"h-full rounded-full transition-all " + c} style={{width: pct + "%"}}/></div><span className="text-[10px] font-bold tabular-nums">{pct}%</span></div>')
m1.append('}')
m1.append('function ValueTile({ value, label, trend }: { value: string; label: string; trend: number }) {')
m1.append('  return <div className="scr-val text-right"><div className="text-sm font-bold tabular-nums">{value}</div><div className="text-[10px] text-muted-foreground">{label}</div>{trend !== 0 && <div className={"text-[10px] font-semibold flex items-center justify-end gap-0.5 " + (trend > 0 ? "text-emerald-600" : "text-red-600")}>{trend > 0 ? <TrendingUp className="h-3 w-3"/> : <TrendingDown className="h-3 w-3"/>}{Math.abs(trend)}%</div>}</div>')
m1.append('}')
m1.append('function SlaCountdown({ days }: { days: number }) {')
m1.append('  const c = days > 30 ? "text-emerald-600 dark:text-emerald-400" : days > 14 ? "text-amber-600 dark:text-amber-400" : days > 7 ? "text-orange-600 dark:text-orange-400" : "text-red-600 dark:text-red-400"')
m1.append('  return <span className={"scr-sla inline-flex items-center gap-1 text-xs font-bold tabular-nums " + c}><Timer className="h-3 w-3"/>{days}d</span>')
m1.append('}')
m1.append('function CostTile({ value }: { value: number }) {')
m1.append('  return <span className="scr-cost text-sm font-bold tabular-nums text-orange-600 dark:text-orange-400">\u20b9{(value * 1000).toLocaleString("en-IN")}</span>')
m1.append('}')
m1.append('function StarRating({ value }: { value: number }) {')
m1.append('  return <span className="scr-stars inline-flex gap-0.5">{"\u2605".repeat(value)}{"\u2606".repeat(5-value)}</span>')
m1.append('}')
m1.append('function PriorityDot({ p }: { p: string }) {')
m1.append('  const cl: Record<string,string> = {Urgent:"bg-red-500 shadow-[0_0_6px_rgba(239,68,68,0.5)]",High:"bg-orange-500",Medium:"bg-amber-400",Low:"bg-blue-400"}')
m1.append('  return <div className={"scr-priority w-2.5 h-2.5 rounded-full " + (cl[p]||"bg-gray-400")}/>')
m1.append('}')

# Data Generation
m1.append('')
m1.append('function genRisks() {')
m1.append('  return Array.from({length: 75}, (_, i) => ({')
m1.append('    id: "RSK-" + String(i+7001).padStart(4,"0"),')
m1.append('    type: pick(RISK_TYPES, i+1),')
m1.append('    severity: pick(RISK_SEVS, i+2),')
m1.append('    riskScore: ri(10, 95, i+3),')
m1.append('    region: pick(REGIONS, i+4),')
m1.append('    city: pick(CITIES, i+5),')
m1.append('    supplier: pick(SUPPLIERS, i+6),')
m1.append('    impact: ri(1, 100, i+7),')
m1.append('    likelihood: ri(5, 95, i+8),')
m1.append('    mitigation: ri(20, 100, i+9),')
m1.append('    residual: ri(5, 60, i+10),')
m1.append('    status: pick(["Active","Mitigated","Monitoring","Escalated","Resolved"], i+11),')
m1.append('    owner: pick(["Rahul S.","Priya M.","Amit K.","Sneha D.","Vikram P.","Geeta T."], i+12),')
m1.append('    costExposure: ri(10, 500, i+13),')
m1.append('    slaDays: ri(3, 90, i+14),')
m1.append('  }))')
m1.append('}')
m1.append('')
m1.append('function genBcp() {')
m1.append('  return Array.from({length: 40}, (_, i) => ({')
m1.append('    id: "BCP-" + String(i+3001).padStart(4,"0"),')
m1.append('    name: pick(["Primary Supplier BCP","Transport Fallback","Warehouse Contingency","IT DR Plan","Financial Continuity","Demand Surge Response","Regulatory Compliance","Quality Escalation"], i+1),')
m1.append('    status: pick(BCP_STS, i+2),')
m1.append('    riskType: pick(RISK_TYPES, i+3),')
m1.append('    altRoute: pick(ALT_ROUTES, i+4),')
m1.append('    region: pick(REGIONS, i+5),')
m1.append('    resilience: ri(50, 98, i+6),')
m1.append('    rto: ri(1, 72, i+7) + "h",')
m1.append('    rpo: ri(0, 24, i+8) + "h",')
m1.append('    lastTest: ri(1, 90, i+9) + "d ago",')
m1.append('    nextTest: ri(1, 180, i+10) + "d",')
m1.append('    effectiveness: ri(60, 99, i+11),')
m1.append('  }))')
m1.append('}')
m1.append('')
m1.append('function genCharts() {')
m1.append('  const monthly = MO.map((m, i) => ({ month: m, riskEvents: ri(5,35,i), mitigated: ri(3,28,i+12), cost: ri(50,300,i+24), resilience: ri(65,98,i+36) }))')
m1.append('  const riskPie = RISK_TYPES.map((t, i) => ({ name: t.split(" ")[0], value: ri(5,40,i) }))')
m1.append('  const sevBar = RISK_SEVS.map((s, i) => ({ name: s, count: ri(10,50,i), mitigated: ri(5,45,i+4) }))')
m1.append('  const regionLine = REGIONS.map((r, i) => ({ region: r.split(" ")[0], score: ri(30,85,i), resilience: ri(55,95,i+6), cost: ri(20,200,i+12) }))')
m1.append('  const altPie = ALT_ROUTES.map((r, i) => ({ name: r.split(" ")[0], value: ri(20,100,i) }))')
m1.append('  return { monthly, riskPie, sevBar, regionLine, altPie }')
m1.append('}')

# Main Component
m1.append('')
m1.append('export default function SupplyChainResilienceHubView() {')
m1.append('  const [tab, setTab] = useState("overview")')
m1.append('  const [search, setSearch] = useState("")')
m1.append('  const [sortField, setSortField] = useState("id")')
m1.append('  const [sortDir, setSortDir] = useState<"asc"|"desc">("asc")')
m1.append('  const [detail, setDetail] = useState<Record<string, unknown>|null>(null)')
m1.append('')
m1.append('  const risks = useMemo(() => genRisks(), [])')
m1.append('  const bcpPlans = useMemo(() => genBcp(), [])')
m1.append('  const charts = useMemo(() => genCharts(), [])')
m1.append('')
m1.append('  const filteredRisks = useMemo(() => sortedData(filterData(risks, search), sortField, sortDir), [risks, search, sortField, sortDir])')
m1.append('  const filteredBcp = useMemo(() => sortedData(filterData(bcpPlans, search), sortField, sortDir), [bcpPlans, search, sortField, sortDir])')
m1.append('')
m1.append('  const toggleSort = (f: string) => { if (sortField === f) setSortDir(d => d === "asc" ? "desc" : "asc"); else { setSortField(f); setSortDir("asc") } }')

# Tab 0: Overview Dashboard
m1.append('')
m1.append('  const tab0 = (')
m1.append('    <div className="space-y-4">')
m1.append('      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">')
m1.append("        {[['Active Risks','23','-8%',<ShieldAlert key='sa'/>],['Avg Risk Score','62','+5%',<Gauge key='g'/>],['Resilience Index','84%','+3%',<ShieldCheck key='sc'/>],['BCP Plans Active','18','+2',<HeartPulse key='hp'/>],['Mitigated This Month','45','+12%',<CheckCircle key='cc'/>],['Cost Exposure','\\u20b92.4M','-15%',<IndianRupee key='r'/>],['Avg RTO','4.2h','-20%',<Timer key='t'/>],['Next BCP Test','12d','--',<Clock key='ck'/>]].map(([label,val,tr,icon], i) => (")
m1.append('          <Card key={i} className="glass-subtle scr-kpi"><CardContent className="p-3"><div className="flex items-center gap-2.5">{icon}<div><div className="text-[10px] text-muted-foreground">{String(label)}</div><div className="text-lg font-black tabular-nums">{String(val)}</div><div className="text-[10px] font-semibold text-emerald-600">{String(tr)}</div></div></div></CardContent></Card>')
m1.append('        ))}')
m1.append('      </div>')
m1.append('      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">')
m1.append('        <Card className="glass-subtle scr-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Monthly Risk Events</CardTitle></CardHeader><CardContent className="p-3"><AreaChart data={charts.monthly}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Area type="monotone" dataKey="riskEvents" stroke={TH.red} fill={TH.red} fillOpacity={0.3}/><Area type="monotone" dataKey="mitigated" stroke={TH.emerald} fill={TH.emerald} fillOpacity={0.3}/></AreaChart></CardContent></Card>')
m1.append('        <Card className="glass-subtle scr-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Risk Category Distribution</CardTitle></CardHeader><CardContent className="p-3"><PieChart><Pie data={charts.riskPie} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({name}: {name:string}) => <text x={0} y={0} fill="currentColor" fontSize={9} textAnchor="middle">{name}</text>}>{charts.riskPie.map((_,i) => <Cell key={i} fill={PC[i%PC.length]}/>)}</Pie><Tooltip/></PieChart></CardContent></Card>')
m1.append('        <Card className="glass-subtle scr-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Risk Severity Breakdown</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.sevBar}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="count" fill={TH.orange} radius={[4,4,0,0]}/><Bar dataKey="mitigated" fill={TH.emerald} radius={[4,4,0,0]}/></BarChart></CardContent></Card>')
m1.append('        <Card className="glass-subtle scr-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Alternate Strategy Mix</CardTitle></CardHeader><CardContent className="p-3"><PieChart><Pie data={charts.altPie} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({name,percent}: {name:string;percent:number}) => <text x={0} y={0} fill="currentColor" fontSize={9} textAnchor="middle">{name} {(percent*100).toFixed(0)}%</text>}>{charts.altPie.map((_,i) => <Cell key={i} fill={PC[i%PC.length]}/>)}</Pie><Tooltip/></PieChart></CardContent></Card>')
m1.append('      </div>')
m1.append('    </div>')
m1.append('  )')

# Tab 1: Risk Register
m1.append('')
m1.append('  const tab1 = (')
m1.append('    <div className="space-y-3">')
m1.append('      <div className="flex items-center gap-2"><div className="relative flex-1"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground"/><Input className="h-8 pl-8 text-xs" placeholder="Search risks..." value={search} onChange={e => setSearch(e.target.value)}/></div><Button variant="outline" size="sm" className="h-8 text-xs"><Filter className="h-3 w-3 mr-1"/>Filter</Button></div>')
m1.append('      <div className="rounded-lg border overflow-auto max-h-[calc(100vh-280px)]">')
m1.append('        <table className="w-full text-xs"><thead className="bg-red-50 dark:bg-red-900/20 sticky top-0 z-10"><tr>')
m1.append('          <th className="p-2 text-left font-semibold cursor-pointer select-none" onClick={() => toggleSort("id")}>ID <ArrowUpDown className="inline h-3 w-3 ml-0.5 opacity-50"/></th>')
m1.append('          <th className="p-2 text-left font-semibold">Type</th>')
m1.append('          <th className="p-2 text-left font-semibold">Severity</th>')
m1.append('          <th className="p-2 text-left font-semibold">Score</th>')
m1.append('          <th className="p-2 text-left font-semibold">Region</th>')
m1.append('          <th className="p-2 text-left font-semibold">Supplier</th>')
m1.append('          <th className="p-2 text-left font-semibold">Impact</th>')
m1.append('          <th className="p-2 text-left font-semibold">Likelihood</th>')
m1.append('          <th className="p-2 text-left font-semibold">Mitigation</th>')
m1.append('          <th className="p-2 text-left font-semibold">Status</th>')
m1.append('          <th className="p-2 text-left font-semibold">SLA</th>')
m1.append('          <th className="p-2 text-left font-semibold">Exposure</th>')
m1.append('          <th className="p-2"></th>')
m1.append('        </tr></thead><tbody className="divide-y">')
m1.append('          {filteredRisks.map(row => (')
m1.append('            <tr key={row.id} className={"hover:bg-red-50/50 dark:hover:bg-red-900/10 transition-colors " + (row.severity === "Critical" && row.status === "Active" ? "bg-red-50/60 dark:bg-red-900/10" : "")}>')
m1.append('              <td className="p-2 font-mono font-medium">{row.id}</td>')
m1.append('              <td className="p-2"><RiskTypeBadge t={row.type}/></td>')
m1.append('              <td className="p-2"><RiskSevBadge s={row.severity}/></td>')
m1.append('              <td className="p-2"><RiskScoreRing score={row.riskScore}/></td>')
m1.append('              <td className="p-2"><RegionBadge r={row.region}/></td>')
m1.append('              <td className="p-2"><SupplierBadge s={row.supplier}/></td>')
m1.append('              <td className="p-2"><ImpactBar value={row.impact} max={100}/></td>')
m1.append('              <td className="p-2 numeric-cell tabular-nums">{row.likelihood}%</td>')
m1.append('              <td className="p-2"><MitigationBar pct={row.mitigation}/></td>')
m1.append('              <td className="p-2"><span className={"inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (row.status==="Active"?"bg-red-100 text-red-700 animate-pulse":row.status==="Resolved"?"bg-emerald-100 text-emerald-700":row.status==="Mitigated"?"bg-blue-100 text-blue-700":"bg-amber-100 text-amber-700")}>\u25cf {row.status}</span></td>')
m1.append('              <td className="p-2"><SlaCountdown days={row.slaDays}/></td>')
m1.append('              <td className="p-2"><CostTile value={row.costExposure}/></td>')
m1.append('              <td className="p-2"><Button variant="ghost" size="sm" className="h-6 w-6 p-0" onClick={() => setDetail(row)}><Eye className="h-3 w-3"/></Button></td>')
m1.append('            </tr>')
m1.append('          ))}')
m1.append('        </tbody></table>')
m1.append('      </div>')
m1.append('      <div className="text-[10px] text-muted-foreground text-right">{filteredRisks.length} risks</div>')
m1.append('    </div>')
m1.append('  )')

# Tab 2: BCP Plans
m1.append('')
m1.append('  const tab2 = (')
m1.append('    <div className="space-y-3">')
m1.append('      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">')
m1.append('        {bcpPlans.map(plan => (')
m1.append('          <Card key={plan.id} className="glass-subtle scr-bcp-card hover:border-orange-300 dark:hover:border-orange-700 transition-all">')
m1.append('            <CardContent className="p-4">')
m1.append('              <div className="flex items-center justify-between mb-2"><span className="font-mono text-[10px] text-muted-foreground">{plan.id}</span><BcpStatusBadge s={plan.status}/></div>')
m1.append('              <div className="text-xs font-bold mb-2">{plan.name}</div>')
m1.append('              <div className="flex items-center gap-2 mb-2"><RiskTypeBadge t={plan.riskType}/><AltRouteBadge r={plan.altRoute}/></div>')
m1.append('              <div className="grid grid-cols-2 gap-1.5 text-center">')
m1.append('                <div className="rounded-lg bg-blue-50 dark:bg-blue-900/20 p-1.5"><div className="text-xs font-black text-blue-600">{plan.rto}</div><div className="text-[9px] text-muted-foreground">RTO</div></div>')
m1.append('                <div className="rounded-lg bg-violet-50 dark:bg-violet-900/20 p-1.5"><div className="text-xs font-black text-violet-600">{plan.rpo}</div><div className="text-[9px] text-muted-foreground">RPO</div></div>')
m1.append('              </div>')
m1.append('              <div className="mt-2"><ResilienceGauge value={plan.resilience}/><div className="flex items-center justify-between mt-1"><span className="text-[10px] text-muted-foreground">Last test: {plan.lastTest}</span><span className="text-[10px] text-muted-foreground">Eff: {plan.effectiveness}%</span></div></div>')
m1.append('            </CardContent>')
m1.append('          </Card>')
m1.append('        ))}')
m1.append('      </div>')
m1.append('    </div>')
m1.append('  )')

# Tab 3: Analytics
m1.append('')
m1.append('  const tab3 = (')
m1.append('    <div className="space-y-3">')
m1.append('      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">')
m1.append('        <Card className="glass-subtle scr-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Monthly Cost Exposure (\\u20b9K)</CardTitle></CardHeader><CardContent className="p-3"><LineChart data={charts.monthly}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Line type="monotone" dataKey="cost" stroke={TH.orange} strokeWidth={2} dot={{r:3}}/></LineChart></CardContent></Card>')
m1.append('        <Card className="glass-subtle scr-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Resilience Trend (%)</CardTitle></CardHeader><CardContent className="p-3"><LineChart data={charts.monthly}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis domain={[60,100]} tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Line type="monotone" dataKey="resilience" stroke={TH.emerald} strokeWidth={2} dot={{r:4}}/></LineChart></CardContent></Card>')
m1.append('        <Card className="glass-subtle scr-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Risk Score by Region</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.regionLine}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="region" tick={{fontSize:9}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="score" fill={TH.red} radius={[4,4,0,0]}/></BarChart></CardContent></Card>')
m1.append('        <Card className="glass-subtle scr-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Resilience by Region (%)</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.regionLine}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="region" tick={{fontSize:9}}/><YAxis domain={[40,100]} tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="resilience" fill={TH.emerald} radius={[4,4,0,0]}/></BarChart></CardContent></Card>')
m1.append('      </div>')
m1.append('    </div>')
m1.append('  )')

# Tab 4: Region Heatmap
m1.append('')
m1.append('  const tab4 = (')
m1.append('    <div className="space-y-3">')
m1.append('      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">')
m1.append('        {REGIONS.map((region, i) => {')
m1.append('          const regionRisks = risks.filter(r => r.region === region)')
m1.append('          const critical = regionRisks.filter(r => r.severity === "Critical").length')
m1.append('          const high = regionRisks.filter(r => r.severity === "High").length')
m1.append('          const mitigated = regionRisks.filter(r => r.status === "Mitigated" || r.status === "Resolved").length')
m1.append('          const avgScore = Math.round(regionRisks.reduce((s,r) => s+r.riskScore, 0) / (regionRisks.length||1))')
m1.append('          const avgResilience = Math.round(regionRisks.reduce((s,r) => s+r.mitigation, 0) / (regionRisks.length||1))')
m1.append('          return (')
m1.append('            <Card key={region} className="glass-subtle scr-region-card hover:border-orange-300 dark:hover:border-orange-700 transition-all">')
m1.append('              <CardContent className="p-4">')
m1.append('                <div className="flex items-center justify-between mb-3"><RegionBadge r={region}/><RiskScoreRing score={avgScore}/></div>')
m1.append('                <div className="grid grid-cols-2 gap-2 text-center">')
m1.append('                  <div className="rounded-lg bg-red-50 dark:bg-red-900/20 p-2"><div className="text-lg font-black text-red-600">{critical}</div><div className="text-[9px] text-muted-foreground">Critical</div></div>')
m1.append('                  <div className="rounded-lg bg-orange-50 dark:bg-orange-900/20 p-2"><div className="text-lg font-black text-orange-600">{high}</div><div className="text-[9px] text-muted-foreground">High</div></div>')
m1.append('                  <div className="rounded-lg bg-emerald-50 dark:bg-emerald-900/20 p-2"><div className="text-lg font-black text-emerald-600">{mitigated}</div><div className="text-[9px] text-muted-foreground">Mitigated</div></div>')
m1.append('                  <div className="rounded-lg bg-blue-50 dark:bg-blue-900/20 p-2"><ResilienceGauge value={avgResilience}/></div>')
m1.append('                </div>')
m1.append('              </CardContent>')
m1.append('            </Card>')
m1.append('          )')
m1.append('        })}')
m1.append('      </div>')
m1.append('    </div>')
m1.append('  )')

# Main Return
m1.append('')
m1.append('  const tabs = [')
m1.append('    {key:"overview",label:"Overview",icon:<ShieldAlert className="h-3.5 w-3.5"/>,content:tab0},')
m1.append('    {key:"risks",label:"Risk Register",icon:<TriangleAlert className="h-3.5 w-3.5"/>,content:tab1},')
m1.append('    {key:"bcp",label:"BCP Plans",icon:<HeartPulse className="h-3.5 w-3.5"/>,content:tab2},')
m1.append('    {key:"analytics",label:"Analytics",icon:<BarChart3 className="h-3.5 w-3.5"/>,content:tab3},')
m1.append('    {key:"regions",label:"Regions",icon:<Globe className="h-3.5 w-3.5"/>,content:tab4},')
m1.append('  ]')
m1.append('')
m1.append('  return (')
m1.append('    <div className="space-y-4 p-4">')
m1.append('      <PageHeader title="Supply Chain Resilience Hub" description="Risk intelligence, business continuity planning, disruption monitoring, and resilience analytics across the supply chain network"/>')
m1.append('      <div className="flex items-center gap-3 flex-wrap">')
m1.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-red-100 dark:bg-red-900/30"><ShieldAlert className="h-3 w-3 text-red-600"/><span className="text-[10px] font-semibold text-red-700 dark:text-red-300">3 Critical Risks</span></div>')
m1.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-100 dark:bg-emerald-900/30"><span className="text-[10px] font-semibold text-emerald-700 dark:text-emerald-300">18 Active BCPs</span></div>')
m1.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-blue-100 dark:bg-blue-900/30"><span className="text-[10px] font-semibold text-blue-700 dark:text-blue-300">Network Resilience: 84%</span></div>')
m1.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-amber-100 dark:bg-amber-900/30"><span className="text-[10px] font-semibold text-amber-700 dark:text-amber-300">Next Audit: 12d</span></div>')
m1.append('      </div>')
m1.append('      <Tabs value={tab} onValueChange={setTab}>')
m1.append('        <TabsList className="bg-gradient-to-r from-red-500/10 to-orange-500/10 p-0.5 h-9">')
m1.append('          {tabs.map(t => <TabsTrigger key={t.key} value={t.key} className="text-xs gap-1.5 data-[state=active]:bg-red-600 data-[state=active]:text-white">{t.icon}{t.label}</TabsTrigger>)}')
m1.append('        </TabsList>')
m1.append('        {tabs.map(t => tab === t.key && <div key={t.key} className="mt-3">{t.content}</div>)}')
m1.append('      </Tabs>')
m1.append('      <Sheet open={!!detail} onOpenChange={() => setDetail(null)}>')
m1.append('        <SheetContent className="w-[420px] overflow-y-auto">')
m1.append('          <SheetHeader><SheetTitle className="text-sm">Risk Detail</SheetTitle></SheetHeader>')
m1.append('          {detail && <div className="mt-4 space-y-3"><div className="rounded-lg bg-gradient-to-r from-red-50 to-orange-50 dark:from-red-900/20 dark:to-orange-900/20 p-4"><div className="text-lg font-bold">Risk Analysis</div><div className="text-xs text-muted-foreground mt-1">Full risk assessment details</div></div>{Object.entries(detail).map(([k, v]) => <div key={k} className="flex items-center justify-between py-1.5 border-b border-border/50"><span className="text-xs font-medium text-muted-foreground">{k}</span><span className="text-xs font-semibold tabular-nums">{String(v)}</span></div>)}</div>}')
m1.append('        </SheetContent>')
m1.append('      </Sheet>')
m1.append('    </div>')
m1.append('  )')
m1.append('}')

m1_content = '\n'.join(m1)

# ═══════════════════════════════════════════════════════════════════════
# MODULE 2: Logistics Procurement Command
# ═══════════════════════════════════════════════════════════════════════
m2 = []
m2.append('"use client"')
m2.append('')
m2.append('import { useState, useMemo } from "react"')
m2.append('import {')
m2.append('  AreaChart, Area, BarChart, Bar, PieChart, Pie, Cell,')
m2.append('  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip,')
m2.append('} from "recharts"')
m2.append('import {')
m2.append('  Search, Eye, ArrowUpDown, TrendingUp, TrendingDown, Clock, IndianRupee, Zap,')
m2.append('  AlertTriangle, Users, BarChart3, MapPin, Package, Box, CheckCircle, XCircle, Activity, Timer, ShieldCheck, Star, Radio, Gauge, Download, Filter, FileText, Handshake, Trophy, Medal, Target, Receipt, ClipboardCheck, ArrowRight, ChevronRight, RefreshCw, Globe, Truck, Calculator, BadgeDollarSign, Scale')
m2.append('} from "lucide-react"')
m2.append('import { PageHeader } from "@/components/shared/page-header"')
m2.append('import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"')
m2.append('import { Input } from "@/components/ui/input"')
m2.append('import { Button } from "@/components/ui/button"')
m2.append('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
m2.append('import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"')
m2.append('')
m2.append('const PROCUREMENT_TYPES = ["Spot Rate","Contract Rate","Bid Award","Rate Card","Spot Quote","Volume Commit","LTL Pool","FCL Contract"] as const')
m2.append('const PROC_EMOJI: Record<string,string> = {["Spot Rate"]:"\U0001f4b0",["Contract Rate"]:"\U0001f4cb",["Bid Award"]:"\U0001f3c6",["Rate Card"]:"\U0001f4b3",["Spot Quote"]:"\U0001f4e2",["Volume Commit"]:"\U0001f4ca",["LTL Pool"]:"\U0001f69a",["FCL Contract"]:"\U0001f6a2"}')
m2.append('const BID_STS = ["Open","Under Review","Awarded","Rejected","Expired","Negotiating"] as const')
m2.append('const LANE_TYPES = ["Domestic","Export","Import","Cross-dock","Last Mile","Long Haul","Regional","Local"] as const')
m2.append('const CARRIERS = ["BlueDart","Delhivery","DTDC","Ecom Express","XpressBees","Shadowfax","Rivigo","Spoton","Gati","VRL","TCI","SafeExpress"] as const')
m2.append('const CITIES = ["Mumbai","Delhi","Bangalore","Chennai","Hyderabad","Kolkata","Pune","Ahmedabad","Jaipur","Lucknow","Coimbatore","Indore"] as const')
m2.append('const EVAL_CRITERIA = ["Price","Transit Time","Service Quality","Capacity","Reliability","Coverage","Technology","Sustainability"] as const')
m2.append('const CONTRACT_STS = ["Active","Expiring Soon","Expired","Under Negotiation","Renewed","Terminated"] as const')
m2.append('const MO = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"] as const')
m2.append('const TH = {blue:"#3b82f6",emerald:"#059669",amber:"#d97706",violet:"#7c3aed",rose:"#e11d48",cyan:"#0891b2",indigo:"#4f46e5",orange:"#f97316"}')
m2.append('const PC = [TH.blue,TH.emerald,TH.amber,TH.violet,TH.rose,TH.cyan,TH.indigo,TH.orange]')
m2.append('')
m2.append('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297 + 233280) * 10000; return x - Math.floor(x) }')
m2.append('function ri(a: number, b: number, s: number): number { return Math.floor(seededRandom(s) * (b - a + 1)) + a }')
m2.append('function pick<T>(arr: readonly T[], s: number): T { return arr[Math.abs(s) % arr.length] }')
m2.append('function rf(d: number): string { return "\\u20b9" + (d * 1000).toLocaleString("en-IN") }')
m2.append('function filterData<T>(d: T[], q: string): T[] { if (!q) return d; const l = q.toLowerCase(); return d.filter(i => Object.values(i as unknown as Record<string, string | number>).some(v => String(v).toLowerCase().includes(l))) }')
m2.append('function sortedData<T>(d: T[], f: string, dir: "asc" | "desc"): T[] { return [...d].sort((a, b) => { const av = (a as unknown as Record<string, string | number>)[f], bv = (b as unknown as Record<string, string | number>)[f]; if (typeof av === "number" && typeof bv === "number") return dir === "asc" ? av - bv : bv - av; return dir === "asc" ? String(av ?? "").localeCompare(String(bv ?? "")) : String(bv ?? "").localeCompare(String(av ?? "")) }) }')

# Visual Components
m2.append('')
m2.append('/* 17 Visual Components */')
m2.append('function ProcTypeBadge({ t }: { t: string }) {')
m2.append('  const cl: Record<string,string> = {["Spot Rate"]:"bg-amber-100 text-amber-700",["Contract Rate"]:"bg-blue-100 text-blue-700",["Bid Award"]:"bg-emerald-100 text-emerald-700",["Rate Card"]:"bg-violet-100 text-violet-700",["Spot Quote"]:"bg-rose-100 text-rose-700",["Volume Commit"]:"bg-cyan-100 text-cyan-700",["LTL Pool"]:"bg-indigo-100 text-indigo-700",["FCL Contract"]:"bg-orange-100 text-orange-700"}')
m2.append('  return <span className={"lpc-type inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium " + (cl[t]||"bg-gray-100")}>{PROC_EMOJI[t]} {t}</span>')
m2.append('}')
m2.append('function BidStatusBadge({ s }: { s: string }) {')
m2.append('  const cl: Record<string,string> = {Open:"bg-emerald-100 text-emerald-700 animate-pulse","Under Review":"bg-amber-100 text-amber-700",Awarded:"bg-blue-100 text-blue-700",Rejected:"bg-red-100 text-red-700",Expired:"bg-gray-100 text-gray-500",Negotiating:"bg-violet-100 text-violet-700"}')
m2.append('  return <span className={"lpc-bid inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cl[s]||"bg-gray-100")}>\u25cf {s}</span>')
m2.append('}')
m2.append('function LaneTypeBadge({ t }: { t: string }) {')
m2.append('  const cl: Record<string,string> = {Domestic:"bg-blue-100 text-blue-700",Export:"bg-violet-100 text-violet-700",Import:"bg-cyan-100 text-cyan-700","Cross-dock":"bg-emerald-100 text-emerald-700","Last Mile":"bg-rose-100 text-rose-700","Long Haul":"bg-amber-100 text-amber-700",Regional:"bg-indigo-100 text-indigo-700",Local:"bg-orange-100 text-orange-700"}')
m2.append('  return <span className={"lpc-lane inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium " + (cl[t]||"bg-gray-100")}>{t}</span>')
m2.append('}')
m2.append('function CarrierBadge({ c }: { c: string }) {')
m2.append('  return <span className="lpc-carrier inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold bg-gradient-to-r from-blue-50 to-indigo-50 text-blue-700 dark:from-blue-900/30 dark:to-indigo-900/30 dark:text-blue-300">\U0001f69a {c}</span>')
m2.append('}')
m2.append('function CityBadge({ city }: { city: string }) {')
m2.append('  return <span className="lpc-city inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-medium bg-cyan-50 text-cyan-700 dark:bg-cyan-900/30 dark:text-cyan-300">\U0001f4cd {city}</span>')
m2.append('}')
m2.append('function EvalBadge({ c }: { c: string }) {')
m2.append('  return <span className="lpc-eval inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300">\u2b50 {c}</span>')
m2.append('}')
m2.append('function ContractStatusBadge({ s }: { s: string }) {')
m2.append('  const cl: Record<string,string> = {Active:"bg-emerald-100 text-emerald-700","Expiring Soon":"bg-amber-100 text-amber-700 animate-pulse",Expired:"bg-gray-100 text-gray-500","Under Negotiation":"bg-violet-100 text-violet-700",Renewed:"bg-blue-100 text-blue-700",Terminated:"bg-red-100 text-red-700"}')
m2.append('  return <span className={"lpc-cs inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cl[s]||"bg-gray-100")}>\u25cf {s}</span>')
m2.append('}')
m2.append('function SavingsBar({ value, benchmark }: { value: number; benchmark: number }) {')
m2.append('  const diff = benchmark - value')
m2.append('  const pct = benchmark > 0 ? Math.round((diff / benchmark) * 100) : 0')
m2.append('  const c = pct >= 15 ? "bg-emerald-500" : pct >= 8 ? "bg-blue-500" : pct >= 0 ? "bg-amber-500" : "bg-red-500"')
m2.append('  return <div className="lpc-savings flex items-center gap-2"><div className="text-xs font-bold tabular-nums">{pct > 0 ? "+" : ""}{pct}%</div><div className="flex-1 h-2 rounded-full bg-gray-200 dark:bg-gray-700"><div className={"h-full rounded-full transition-all " + c} style={{width: Math.min(Math.abs(pct)*3, 100) + "%"}}/></div></div>')
m2.append('}')
m2.append('function ScoreGauge({ value, label }: { value: number; label: string }) {')
m2.append('  const c = value >= 90 ? "text-emerald-600" : value >= 75 ? "text-blue-600" : value >= 60 ? "text-amber-600" : "text-red-600"')
m2.append('  return <div className="lpc-score flex flex-col items-center"><div className={"text-2xl font-black tabular-nums " + c}>{value}</div><div className="text-[10px] text-muted-foreground">{label}</div></div>')
m2.append('}')
m2.append('function RateTile({ base, negotiated }: { base: number; negotiated: number }) {')
m2.append('  const saved = base - negotiated')
m2.append('  return <div className="lpc-rate text-right"><div className="text-sm font-bold tabular-nums text-emerald-600">{rf(negotiated)}</div><div className="text-[10px] text-muted-foreground line-through">{rf(base)}</div>{saved > 0 && <div className="text-[10px] font-semibold text-emerald-600">Save {rf(saved)}</div>}</div>')
m2.append('}')
m2.append('function VolumeBar({ committed, capacity }: { committed: number; capacity: number }) {')
m2.append('  const pct = Math.round((committed / capacity) * 100)')
m2.append('  const c = pct > 90 ? "bg-red-500" : pct > 75 ? "bg-amber-500" : pct > 50 ? "bg-blue-500" : "bg-emerald-500"')
m2.append('  return <div className="lpc-vol flex items-center gap-2"><div className="flex-1 h-2 rounded-full bg-gray-200 dark:bg-gray-700"><div className={"h-full rounded-full transition-all " + c} style={{width: Math.min(pct,100) + "%"}}/></div><span className="text-[10px] font-bold tabular-nums">{pct}%</span></div>')
m2.append('}')
m2.append('function StarRating({ value }: { value: number }) {')
m2.append('  return <span className="lpc-stars inline-flex gap-0.5">{"\u2605".repeat(value)}{"\u2606".repeat(5-value)}</span>')
m2.append('}')
m2.append('function ValueTile({ value, label, trend }: { value: string; label: string; trend: number }) {')
m2.append('  return <div className="lpc-val text-right"><div className="text-sm font-bold tabular-nums">{value}</div><div className="text-[10px] text-muted-foreground">{label}</div>{trend !== 0 && <div className={"text-[10px] font-semibold flex items-center justify-end gap-0.5 " + (trend > 0 ? "text-emerald-600" : "text-red-600")}>{trend > 0 ? <TrendingUp className="h-3 w-3"/> : <TrendingDown className="h-3 w-3"/>}{Math.abs(trend)}%</div>}</div>')
m2.append('}')
m2.append('function ValueTileNoTrend({ value, label }: { value: string; label: string }) {')
m2.append('  return <div className="lpc-val text-right"><div className="text-sm font-bold tabular-nums">{value}</div><div className="text-[10px] text-muted-foreground">{label}</div></div>')
m2.append('}')
m2.append('function PriorityDot({ p }: { p: string }) {')
m2.append('  const cl: Record<string,string> = {Urgent:"bg-red-500 shadow-[0_0_6px_rgba(239,68,68,0.5)]",High:"bg-orange-500",Medium:"bg-amber-400",Low:"bg-blue-400"}')
m2.append('  return <div className={"lpc-priority w-2.5 h-2.5 rounded-full " + (cl[p]||"bg-gray-400")}/>')
m2.append('}')
m2.append('function CostTile({ value }: { value: number }) {')
m2.append('  return <span className="lpc-cost text-sm font-bold tabular-nums text-violet-600 dark:text-violet-400">{rf(value)}</span>')
m2.append('}')
m2.append('function TtlBadge({ days }: { days: number }) {')
m2.append('  const c = days > 90 ? "text-emerald-600" : days > 30 ? "text-amber-600" : "text-red-600"')
m2.append('  return <span className={"lpc-ttl inline-flex items-center gap-1 text-xs font-bold tabular-nums " + c}><Clock className="h-3 w-3"/>{days}d</span>')
m2.append('}')

# Data Generation
m2.append('')
m2.append('function genBids() {')
m2.append('  return Array.from({length: 75}, (_, i) => ({')
m2.append('    id: "BID-" + String(i+8001).padStart(4,"0"),')
m2.append('    type: pick(PROCUREMENT_TYPES, i+1),')
m2.append('    status: pick(BID_STS, i+2),')
m2.append('    laneType: pick(LANE_TYPES, i+3),')
m2.append('    origin: pick(CITIES, i+4),')
m2.append('    destination: pick(CITIES, (i+7) % CITIES.length),')
m2.append('    carrier: pick(CARRIERS, i+5),')
m2.append('    baseRate: ri(5, 50, i+6),')
m2.append('    negotiatedRate: ri(3, 45, i+7),')
m2.append('    volume: ri(100, 5000, i+8),')
m2.append('    committed: ri(50, 4000, i+9),')
m2.append('    evalScore: ri(60, 98, i+10),')
m2.append('    transitDays: ri(1, 15, i+11),')
m2.append('    serviceScore: ri(70, 99, i+12),')
m2.append('    totalValue: ri(50, 800, i+13),')
m2.append('    ttl: ri(5, 180, i+14),')
m2.append('  }))')
m2.append('}')
m2.append('')
m2.append('function genContracts() {')
m2.append('  return Array.from({length: 45}, (_, i) => ({')
m2.append('    id: "CTR-" + String(i+4001).padStart(4,"0"),')
m2.append('    carrier: pick(CARRIERS, i+1),')
m2.append('    status: pick(CONTRACT_STS, i+2),')
m2.append('    laneType: pick(LANE_TYPES, i+3),')
m2.append('    origin: pick(CITIES, i+4),')
m2.append('    destination: pick(CITIES, (i+6) % CITIES.length),')
m2.append('    annualValue: ri(200, 5000, i+5),')
m2.append('    savings: ri(5, 25, i+6),')
m2.append('    startMonth: pick(MO, i+7),')
m2.append('    endMonth: pick(MO, i+8),')
m2.append('    performance: ri(75, 99, i+9),')
m2.append('    penaltyIncidents: ri(0, 12, i+10),')
m2.append('    onTimeRate: ri(85, 99, i+11),')
m2.append('  }))')
m2.append('}')
m2.append('')
m2.append('function genCharts() {')
m2.append('  const monthly = MO.map((m, i) => ({ month: m, spend: ri(2000,8000,i), savings: ri(200,1500,i+12), bids: ri(10,50,i+24), awarded: ri(5,35,i+36) }))')
m2.append('  const typePie = PROCUREMENT_TYPES.map((t, i) => ({ name: t.split(" ")[0], value: ri(20,100,i) }))')
m2.append('  const carrierBar = CARRIERS.slice(0,8).map((c, i) => ({ name: c, volume: ri(500,4000,i), savings: ri(5,20,i+8), onTime: ri(85,99,i+16) }))')
m2.append('  const laneBar = LANE_TYPES.map((l, i) => ({ name: l.split(" ")[0], avgRate: ri(5,40,i), volume: ri(300,3000,i+8) }))')
m2.append('  const evalRadar = EVAL_CRITERIA.map((c, i) => ({ name: c.split(" ")[0], score: ri(60,98,i) }))')
m2.append('  return { monthly, typePie, carrierBar, laneBar, evalRadar }')
m2.append('}')

# Main Component
m2.append('')
m2.append('export default function LogisticsProcurementCommandView() {')
m2.append('  const [tab, setTab] = useState("dashboard")')
m2.append('  const [search, setSearch] = useState("")')
m2.append('  const [sortField, setSortField] = useState("id")')
m2.append('  const [sortDir, setSortDir] = useState<"asc"|"desc">("asc")')
m2.append('  const [detail, setDetail] = useState<Record<string, unknown>|null>(null)')
m2.append('')
m2.append('  const bids = useMemo(() => genBids(), [])')
m2.append('  const contracts = useMemo(() => genContracts(), [])')
m2.append('  const charts = useMemo(() => genCharts(), [])')
m2.append('')
m2.append('  const filteredBids = useMemo(() => sortedData(filterData(bids, search), sortField, sortDir), [bids, search, sortField, sortDir])')
m2.append('  const filteredContracts = useMemo(() => sortedData(filterData(contracts, search), sortField, sortDir), [contracts, search, sortField, sortDir])')
m2.append('')
m2.append('  const toggleSort = (f: string) => { if (sortField === f) setSortDir(d => d === "asc" ? "desc" : "asc"); else { setSortField(f); setSortDir("asc") } }')

# Tab 0: Dashboard
m2.append('')
m2.append('  const tab0 = (')
m2.append('    <div className="space-y-4">')
m2.append('      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">')
m2.append("        {[['Active Bids','34','+8',<FileText key='f'/>],['Total Savings','\\u20b912.5M','+18%',<Trophy key='t'/>],['Avg Savings Rate','14.2%','+2.1%',<Target key='g'/>],['Active Contracts','28','+3',<ClipboardCheck key='c'/>],['Open Bids','12','-2',<Handshake key='h'/>],['Avg Eval Score','86','+4',<Medal key='m'/>],['On-time Rate','94.5%','+1.2%',<Clock key='ck'/>],['Total Procurement','\\u20b984M','+12%',<IndianRupee key='r'/>]].map(([label,val,tr,icon], i) => (")
m2.append('          <Card key={i} className="glass-subtle lpc-kpi"><CardContent className="p-3"><div className="flex items-center gap-2.5">{icon}<div><div className="text-[10px] text-muted-foreground">{String(label)}</div><div className="text-lg font-black tabular-nums">{String(val)}</div><div className="text-[10px] font-semibold text-emerald-600">{String(tr)}</div></div></div></CardContent></Card>')
m2.append('        ))}')
m2.append('      </div>')
m2.append('      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">')
m2.append('        <Card className="glass-subtle lpc-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Monthly Spend vs Savings (\\u20b9L)</CardTitle></CardHeader><CardContent className="p-3"><AreaChart data={charts.monthly}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Area type="monotone" dataKey="spend" stroke={TH.blue} fill={TH.blue} fillOpacity={0.3}/><Area type="monotone" dataKey="savings" stroke={TH.emerald} fill={TH.emerald} fillOpacity={0.3}/></AreaChart></CardContent></Card>')
m2.append('        <Card className="glass-subtle lpc-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Procurement Type Mix</CardTitle></CardHeader><CardContent className="p-3"><PieChart><Pie data={charts.typePie} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({name}: {name:string}) => <text x={0} y={0} fill="currentColor" fontSize={9} textAnchor="middle">{name}</text>}>{charts.typePie.map((_,i) => <Cell key={i} fill={PC[i%PC.length]}/>)}</Pie><Tooltip/></PieChart></CardContent></Card>')
m2.append('        <Card className="glass-subtle lpc-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Carrier Volume & Savings</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.carrierBar}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="name" tick={{fontSize:9}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="volume" fill={TH.blue} radius={[4,4,0,0]}/><Bar dataKey="savings" fill={TH.emerald} radius={[4,4,0,0]}/></BarChart></CardContent></Card>')
m2.append('        <Card className="glass-subtle lpc-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Lane Rate Comparison (\\u20b9K)</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.laneBar}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="name" tick={{fontSize:9}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="avgRate" fill={TH.violet} radius={[4,4,0,0]}/></BarChart></CardContent></Card>')
m2.append('      </div>')
m2.append('    </div>')
m2.append('  )')

# Tab 1: Bid Management
m2.append('')
m2.append('  const tab1 = (')
m2.append('    <div className="space-y-3">')
m2.append('      <div className="flex items-center gap-2"><div className="relative flex-1"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground"/><Input className="h-8 pl-8 text-xs" placeholder="Search bids..." value={search} onChange={e => setSearch(e.target.value)}/></div><Button variant="outline" size="sm" className="h-8 text-xs"><Download className="h-3 w-3 mr-1"/>Export</Button></div>')
m2.append('      <div className="rounded-lg border overflow-auto max-h-[calc(100vh-280px)]">')
m2.append('        <table className="w-full text-xs"><thead className="bg-blue-50 dark:bg-blue-900/20 sticky top-0 z-10"><tr>')
m2.append('          <th className="p-2 text-left font-semibold cursor-pointer select-none" onClick={() => toggleSort("id")}>ID <ArrowUpDown className="inline h-3 w-3 ml-0.5 opacity-50"/></th>')
m2.append('          <th className="p-2 text-left font-semibold">Type</th>')
m2.append('          <th className="p-2 text-left font-semibold">Status</th>')
m2.append('          <th className="p-2 text-left font-semibold">Route</th>')
m2.append('          <th className="p-2 text-left font-semibold">Lane</th>')
m2.append('          <th className="p-2 text-left font-semibold">Carrier</th>')
m2.append('          <th className="p-2 text-left font-semibold">Rate</th>')
m2.append('          <th className="p-2 text-left font-semibold">Savings</th>')
m2.append('          <th className="p-2 text-left font-semibold">Volume</th>')
m2.append('          <th className="p-2 text-left font-semibold">Eval</th>')
m2.append('          <th className="p-2 text-left font-semibold">Service</th>')
m2.append('          <th className="p-2 text-left font-semibold">TTL</th>')
m2.append('          <th className="p-2 text-left font-semibold">Value</th>')
m2.append('          <th className="p-2"></th>')
m2.append('        </tr></thead><tbody className="divide-y">')
m2.append('          {filteredBids.map(row => (')
m2.append('            <tr key={row.id} className="hover:bg-blue-50/50 dark:hover:bg-blue-900/10 transition-colors">')
m2.append('              <td className="p-2 font-mono font-medium">{row.id}</td>')
m2.append('              <td className="p-2"><ProcTypeBadge t={row.type}/></td>')
m2.append('              <td className="p-2"><BidStatusBadge s={row.status}/></td>')
m2.append('              <td className="p-2"><div className="flex items-center gap-1 text-[10px]"><CityBadge city={row.origin}/><ChevronRight className="h-3 w-3 text-muted-foreground"/><CityBadge city={row.destination}/></div></td>')
m2.append('              <td className="p-2"><LaneTypeBadge t={row.laneType}/></td>')
m2.append('              <td className="p-2"><CarrierBadge c={row.carrier}/></td>')
m2.append('              <td className="p-2"><RateTile base={row.baseRate} negotiated={row.negotiatedRate}/></td>')
m2.append('              <td className="p-2"><SavingsBar value={row.negotiatedRate} benchmark={row.baseRate}/></td>')
m2.append('              <td className="p-2"><VolumeBar committed={row.committed} capacity={row.volume}/></td>')
m2.append('              <td className="p-2"><ScoreGauge value={row.evalScore} label="Eval"/></td>')
m2.append('              <td className="p-2 numeric-cell tabular-nums">{row.serviceScore}%</td>')
m2.append('              <td className="p-2"><TtlBadge days={row.ttl}/></td>')
m2.append('              <td className="p-2"><CostTile value={row.totalValue}/></td>')
m2.append('              <td className="p-2"><Button variant="ghost" size="sm" className="h-6 w-6 p-0" onClick={() => setDetail(row)}><Eye className="h-3 w-3"/></Button></td>')
m2.append('            </tr>')
m2.append('          ))}')
m2.append('        </tbody></table>')
m2.append('      </div>')
m2.append('      <div className="text-[10px] text-muted-foreground text-right">{filteredBids.length} bids</div>')
m2.append('    </div>')
m2.append('  )')

# Tab 2: Contracts
m2.append('')
m2.append('  const tab2 = (')
m2.append('    <div className="space-y-3">')
m2.append('      <div className="flex items-center gap-2"><div className="relative flex-1"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground"/><Input className="h-8 pl-8 text-xs" placeholder="Search contracts..." value={search} onChange={e => setSearch(e.target.value)}/></div></div>')
m2.append('      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">')
m2.append('        {filteredContracts.map(c => (')
m2.append('          <Card key={c.id} className="glass-subtle lpc-contract hover:border-blue-300 dark:hover:border-blue-700 transition-all">')
m2.append('            <CardContent className="p-4">')
m2.append('              <div className="flex items-center justify-between mb-2"><span className="font-mono text-[10px] text-muted-foreground">{c.id}</span><ContractStatusBadge s={c.status}/></div>')
m2.append('              <div className="flex items-center gap-2 mb-2"><CarrierBadge c={c.carrier}/><LaneTypeBadge t={c.laneType}/></div>')
m2.append('              <div className="flex items-center gap-1 mb-2 text-[10px]"><CityBadge city={c.origin}/><ChevronRight className="h-3 w-3 text-muted-foreground"/><CityBadge city={c.destination}/></div>')
m2.append('              <div className="grid grid-cols-3 gap-1.5 text-center">')
m2.append('                <div className="rounded-lg bg-blue-50 dark:bg-blue-900/20 p-1.5"><div className="text-xs font-black text-blue-600">{c.onTimeRate}%</div><div className="text-[9px] text-muted-foreground">On-time</div></div>')
m2.append('                <div className="rounded-lg bg-emerald-50 dark:bg-emerald-900/20 p-1.5"><div className="text-xs font-black text-emerald-600">{c.savings}%</div><div className="text-[9px] text-muted-foreground">Savings</div></div>')
m2.append('                <div className="rounded-lg bg-violet-50 dark:bg-violet-900/20 p-1.5"><div className="text-xs font-black text-violet-600">{c.penaltyIncidents}</div><div className="text-[9px] text-muted-foreground">Penalties</div></div>')
m2.append('              </div>')
m2.append('              <div className="flex items-center justify-between mt-2 pt-2 border-t"><StarRating value={Math.round(c.performance / 20)}/><span className="text-[10px] text-muted-foreground">{c.startMonth} - {c.endMonth}</span></div>')
m2.append('            </CardContent>')
m2.append('          </Card>')
m2.append('        ))}')
m2.append('      </div>')
m2.append('    </div>')
m2.append('  )')

# Tab 3: Analytics
m2.append('')
m2.append('  const tab3 = (')
m2.append('    <div className="space-y-3">')
m2.append('      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">')
m2.append('        <Card className="glass-subtle lpc-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Bid Activity (Monthly)</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.monthly}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="month" tick={{fontSize:9}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="bids" fill={TH.blue} radius={[4,4,0,0]}/><Bar dataKey="awarded" fill={TH.emerald} radius={[4,4,0,0]}/></BarChart></CardContent></Card>')
m2.append('        <Card className="glass-subtle lpc-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Carrier On-time Performance (%)</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.carrierBar} layout="vertical"><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis type="number" domain={[80,100]} tick={{fontSize:10}}/><YAxis dataKey="name" type="category" width={70} tick={{fontSize:9}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="onTime" radius={[0,4,4,0]}>{charts.carrierBar.map((_,i) => <Cell key={i} fill={charts.carrierBar[i].onTime > 95 ? TH.emerald : charts.carrierBar[i].onTime > 90 ? TH.blue : TH.amber}/>)}</Bar></BarChart></CardContent></Card>')
m2.append('        <Card className="glass-subtle lpc-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Evaluation Criteria Scores</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.evalRadar}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="name" tick={{fontSize:9}}/><YAxis domain={[0,100]} tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="score" fill={TH.violet} radius={[4,4,0,0]}/></BarChart></CardContent></Card>')
m2.append('        <Card className="glass-subtle lpc-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Lane Volume Distribution</CardTitle></CardHeader><CardContent className="p-3"><PieChart><Pie data={charts.laneBar} cx="50%" cy="50%" outerRadius={80} dataKey="volume" label={({name}: {name:string}) => <text x={0} y={0} fill="currentColor" fontSize={9} textAnchor="middle">{name}</text>}>{charts.laneBar.map((_,i) => <Cell key={i} fill={PC[i%PC.length]}/>)}</Pie><Tooltip/></PieChart></CardContent></Card>')
m2.append('      </div>')
m2.append('    </div>')
m2.append('  )')

# Main Return
m2.append('')
m2.append('  const tabs = [')
m2.append('    {key:"dashboard",label:"Dashboard",icon:<Trophy className="h-3.5 w-3.5"/>,content:tab0},')
m2.append('    {key:"bids",label:"Bid Mgmt",icon:<FileText className="h-3.5 w-3.5"/>,content:tab1},')
m2.append('    {key:"contracts",label:"Contracts",icon:<ClipboardCheck className="h-3.5 w-3.5"/>,content:tab2},')
m2.append('    {key:"analytics",label:"Analytics",icon:<BarChart3 className="h-3.5 w-3.5"/>,content:tab3},')
m2.append('  ]')
m2.append('')
m2.append('  return (')
m2.append('    <div className="space-y-4 p-4">')
m2.append('      <PageHeader title="Logistics Procurement Command" description="Freight procurement intelligence with carrier bidding, rate optimization, contract management, and spend analytics"/>')
m2.append('      <div className="flex items-center gap-3 flex-wrap">')
m2.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-blue-100 dark:bg-blue-900/30"><Handshake className="h-3 w-3 text-blue-600"/><span className="text-[10px] font-semibold text-blue-700 dark:text-blue-300">12 Open Bids</span></div>')
m2.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-100 dark:bg-emerald-900/30"><span className="text-[10px] font-semibold text-emerald-700 dark:text-emerald-300">\\u20b912.5M Saved YTD</span></div>')
m2.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-violet-100 dark:bg-violet-900/30"><span className="text-[10px] font-semibold text-violet-700 dark:text-violet-300">28 Active Contracts</span></div>')
m2.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-amber-100 dark:bg-amber-900/30"><span className="text-[10px] font-semibold text-amber-700 dark:text-amber-300">3 Expiring Soon</span></div>')
m2.append('      </div>')
m2.append('      <Tabs value={tab} onValueChange={setTab}>')
m2.append('        <TabsList className="bg-gradient-to-r from-blue-500/10 to-violet-500/10 p-0.5 h-9">')
m2.append('          {tabs.map(t => <TabsTrigger key={t.key} value={t.key} className="text-xs gap-1.5 data-[state=active]:bg-blue-600 data-[state=active]:text-white">{t.icon}{t.label}</TabsTrigger>)}')
m2.append('        </TabsList>')
m2.append('        {tabs.map(t => tab === t.key && <div key={t.key} className="mt-3">{t.content}</div>)}')
m2.append('      </Tabs>')
m2.append('      <Sheet open={!!detail} onOpenChange={() => setDetail(null)}>')
m2.append('        <SheetContent className="w-[420px] overflow-y-auto">')
m2.append('          <SheetHeader><SheetTitle className="text-sm">Bid Detail</SheetTitle></SheetHeader>')
m2.append('          {detail && <div className="mt-4 space-y-3"><div className="rounded-lg bg-gradient-to-r from-blue-50 to-violet-50 dark:from-blue-900/20 dark:to-violet-900/20 p-4"><div className="text-lg font-bold">Procurement Details</div><div className="text-xs text-muted-foreground mt-1">Full bid and rate analysis</div></div>{Object.entries(detail).map(([k, v]) => <div key={k} className="flex items-center justify-between py-1.5 border-b border-border/50"><span className="text-xs font-medium text-muted-foreground">{k}</span><span className="text-xs font-semibold tabular-nums">{String(v)}</span></div>)}</div>}')
m2.append('        </SheetContent>')
m2.append('      </Sheet>')
m2.append('    </div>')
m2.append('  )')
m2.append('}')

m2_content = '\n'.join(m2)

# Write
with open(os.path.join(BASE, 'supply-chain-resilience-hub-view.tsx'), 'w') as f:
    f.write(m1_content)

with open(os.path.join(BASE, 'logistics-procurement-command-view.tsx'), 'w') as f:
    f.write(m2_content)

print(f"Module 1: supply-chain-resilience-hub-view.tsx - {len(m1_content)} chars, {len(m1)} lines")
print(f"Module 2: logistics-procurement-command-view.tsx - {len(m2_content)} chars, {len(m2)} lines")
print("Done!")
