#!/usr/bin/env python3
"""Generate R418b: Chromium Oxide Logistics View"""
import os

COMPONENT = "ChromiumOxide"
THEME = "chromium-oxide"
PREFIX = "CRO"
ICON = "Palette"
COLOR = "#7c3aed"  # violet-600
INTERFACE = "ChromiumOxideRecord"
VAR = "chromiumOxideRecords"

RECORDS = [
    ("CRO-0001", "CRO-B2401", "Mumbai", "India Chrome", "Cr2O3 Pigment 99%", "Asian Paints Automotive", 99.2, 8.5, 760, "Delivered", "High", "India Chrome Mumbai (MH)", "Asian Paints Mumbai (MH)", "2026-07-15", 1, "West", "Chromium oxide green pigment for Asian Paints automotive OEM polyurethane topcoat &#8594; DPP grade &#8594; &#8377;760Cr for 3,000 tonnes &#8594; India &#8377;4,200Cr pigment &#8594; Asian 50M litres &#8594; 8.5 Mohs &#8594; &#8594; Pigment &#8594; &#8594; 240&#176;C &#8594; &#8594; Coatings"),
    ("CRO-0002", "CRO-B2402", "Bengaluru", "DRDO DMRL", "Cr2O3 Ceramic 99.5%", "ISRO TPS Coating", 99.5, 9.2, 920, "In Transit", "Critical", "DRDO Hyderabad (TG)", "ISRO Thiruvananthapuram (KL)", "2026-07-18", 1, "South", "High-purity chromia ceramic for ISRO reusable launch vehicle thermal protection system plasma spray &#8594; APS grade &#8594; &#8377;920Cr for 600 tonnes &#8594; India &#8377;7,800Cr TPS &#8594; ISRO 6 vehicles &#8594; 9.2 GPa &#8594; &#8594; Ceramic &#8594; &#8594; 1400&#176;C &#8594; &#8594; Space"),
    ("CRO-0003", "CRO-B2403", "Chennai", "Tata Steel Chromite", "Cr2O3 Refractory 98%", "SAIL AOD Vessel", 98.3, 7.8, 680, "Delivered", "High", "Tata Steel Sukinda (OD)", "SAIL Durgapur (WB)", "2026-07-20", 2, "East", "Chromia refractory brick for SAIL Durgapur argon oxygen decarburization vessel lining &#8594; 98% Cr2O3 &#8594; &#8377;680Cr for 2,500 tonnes &#8594; India &#8377;5,400Cr refractory &#8594; SAIL 4 AOD &#8594; 7.8 GPa &#8594; &#8594; Brick &#8594; &#8594; 1700&#176;C &#8594; &#8594; Steel"),
    ("CRO-0004", "CRO-B2404", "Hyderabad", "Bharat Forge Chrome", "Cr2O3 Metallurgical 96%", "Bharat Forge Crankshaft", 96.5, 8.1, 720, "Delivered", "High", "Bharat Forge Pune (MH)", "Bharat Forge Pune (MH)", "2026-07-22", 1, "West", "Chromium oxide for Bharat Forge crankshaft chrome plating and surface hardening &#8594; HVOF grade &#8594; &#8377;720Cr for 2,000 tonnes &#8594; India &#8377;5,800Cr metallurgical &#8594; Bharat 200K shafts &#8594; 8.1 GPa &#8594; &#8594; Plating &#8594; &#8594; 500&#176;C &#8594; &#8594; Auto"),
    ("CRO-0005", "CRO-B2405", "Kolkata", "Shalimar Paints", "Cr2O3 Camo Green 99%", "BEL DRDO Camo Net", 99.1, 7.5, 580, "In Transit", "Medium", "Shalimar Paints Kolkata (WB)", "BEL Bengaluru (KA)", "2026-07-24", 2, "East", "Chromium oxide green pigment for BEL DRDO camouflage netting and vehicle NIR signature paint &#8594; mil spec &#8594; &#8377;580Cr for 1,200 tonnes &#8594; India &#8377;3,200Cr military &#8594; BEL 100K sets &#8594; 7.5 Mohs &#8594; &#8594; NIR &#8594; &#8594; 300&#176;C &#8594; &#8594; Defence"),
    ("CRO-0006", "CRO-B2406", "Ahmedabad", "Gujarat Chrome Chem", "Cr2O3 Tanning 97%", "Tata Leather Tannery", 97.4, 5.5, 440, "Delivered", "Medium", "Gujarat Chrome Chem Ahmedabad (GJ)", "Tata Leather Kolkata (WB)", "2026-07-26", 3, "West", "Basic chromium sulfate tanning agent for Tata Leather automotive upholstery chrome tanning &#8594; BCS grade &#8594; &#8377;440Cr for 4,000 tonnes &#8594; India &#8377;1,800Cr tanning &#8594; Tata 5M hides &#8594; 5.5 Mohs &#8594; &#8594; BCS &#8594; &#8594; 120&#176;C &#8594; &#8594; Leather"),
    ("CRO-0007", "CRO-B2407", "Jaipur", "Rajasthan Chromite", "Cr2O3 Abrasive 96%", "Grindwell Norton Wheel", 96.2, 9.0, 620, "In Transit", "High", "Rajasthan Chromite Udaipur (RJ)", "Grindwell Norton Bengaluru (KA)", "2026-07-28", 2, "West", "Chromium oxide abrasive grain for Grindwell Norton precision grinding wheel vitrified bond &#8594; A46 grade &#8594; &#8377;620Cr for 2,500 tonnes &#8594; India &#8377;4,600Cr abrasive &#8594; Norton 500K wheels &#8594; 9.0 Mohs &#8594; &#8594; Abrasive &#8594; &#8594; 1200&#176;C &#8594; &#8594; Abrasives"),
    ("CRO-0008", "CRO-B2408", "Coimbatore", "TN Chrome Products", "Cr2O3 Glass 99.3%", "Asahi India Container", 99.3, 6.8, 520, "Delivered", "Medium", "TN Chrome Products Chennai (TN)", "Asahi India Mumbai (MH)", "2026-07-30", 1, "South", "Chromium oxide glass colourant for Asahi India green-tinted beverage container glass &#8594; emerald &#8594; &#8377;520Cr for 1,500 tonnes &#8594; India &#8377;2,800Cr glass &#8594; Asahi 800M bottles &#8594; 6.8 Mohs &#8594; &#8594; Glass &#8594; &#8594; 1500&#176;C &#8594; &#8594; Glass"),
    ("CRO-0009", "CRO-B2409", "Guwahati", "Assam Chromite", "Cr2O3 Ore Beneficiation", "NALCO Ferro Chrome", 94.8, 7.2, 380, "Delivered", "Low", "Assam Chromite Dima Hasao (AS)", "NALCO Damanjodi (OD)", "2026-08-01", 5, "East", "Chromite ore concentrate for NALCO ferro chrome smelter charge feed &#8594; 46% Cr2O3 &#8594; &#8377;380Cr for 15,000 tonnes &#8594; India &#8377;1,200Cr ore &#8594; NALCO 3 smelters &#8594; 7.2 Mohs &#8594; &#8594; Ore &#8594; &#8594; 1800&#176;C &#8594; &#8594; Mining"),
    ("CRO-0010", "CRO-B2410", "Lucknow", "UP Chrome Industries", "Cr2O3 Ceramic 99.8%", "CSIR-NAL Coating", 99.8, 9.5, 720, "Delivered", "High", "UP Chrome Kanpur (UP)", "CSIR-NAL Bengaluru (KA)", "2026-08-03", 2, "North", "Ultra-high purity chromia for CSIR-NAL thermal barrier coating APS powder for HAL Tejas engine &#8594; 99.8% &#8594; &#8377;720Cr for 800 tonnes &#8594; India &#8377;6,400Cr TBC &#8594; NAL 200 engines &#8594; 9.5 GPa &#8594; &#8594; TBC &#8594; &#8594; 1200&#176;C &#8594; &#8594; Aero"),
    ("CRO-0011", "CRO-B2411", "Nagpur", "BHEL Chromite Div", "Cr2O3 Welding 97%", "L&amp;T Welding Rod", 97.1, 7.5, 540, "In Transit", "Medium", "BHEL Bhopal (MP)", "L&amp;T Mumbai (MH)", "2026-08-05", 2, "West", "Chromium oxide flux for L&amp;T E308L stainless steel welding rod and flux cored wire coating &#8594; AWS A5.4 &#8594; &#8377;540Cr for 2,000 tonnes &#8594; India &#8377;3,400Cr welding &#8594; L&amp;T 50K tonnes &#8594; 7.5 Mohs &#8594; &#8594; Flux &#8594; &#8594; 600&#176;C &#8594; &#8594; Welding"),
    ("CRO-0012", "CRO-B2412", "Visakhapatnam", "Vizag Chrome Works", "Cr2O3 Naval 99.4%", "GRSE Submarine Hull", 99.4, 8.8, 680, "Delayed", "Critical", "Vizag Chrome Visakha (AP)", "GRSE Kolkata (WB)", "2026-08-07", 2, "East", "Chromia ceramic tile for GRSE Project 75I submarine hull sonar dome acoustic tiling &#8594; 99.4% &#8594; &#8377;680Cr for 600 tonnes &#8597; India &#8377;5,800Cr naval &#8594; GRSE 4 submarines &#8594; 8.8 GPa &#8594; &#8594; Acoustic &#8594; &#8594; 1100&#176;C &#8594; &#8594; Naval"),
    ("CRO-0013", "CRO-B2413", "Bhopal", "IGCAR Nuclear", "Cr2O3 Control Rod 99.9%", "NPCIL PHWR Absorber", 99.9, 9.8, 940, "In Transit", "Critical", "IGCAR Kalpakkam (TN)", "NPCIL Rawatbhata (RJ)", "2026-08-09", 2, "Central", "Ultra-high purity chromia sinter for NPCIL PHWR 700 control rod neutron absorber material &#8594; 99.9% &#8594; &#8377;940Cr for 400 tonnes &#8594; India &#8377;9,400Cr nuclear &#8594; NPCIL 8 reactors &#8594; 9.8 GPa &#8594; &#8594; Absorber &#8594; &#8594; 800&#176;C &#8594; &#8594; Nuclear"),
    ("CRO-0014", "CRO-B2414", "Rourkela", "SAIL Chromite Mine", "Cr2O3 Foundry 95%", "Tata Steel Casting", 95.5, 7.0, 420, "Delivered", "Medium", "SAIL Rourkela (OD)", "Tata Steel Jamshedpur (JH)", "2026-08-11", 1, "East", "Foundry chromite sand facing for Tata Steel heavy steel casting mould and core facing &#8594; AFS 55 &#8594; &#8377;420Cr for 6,000 tonnes &#8594; India &#8377;2,200Cr foundry &#8594; Tata 10 castings &#8594; 7.0 Mohs &#8594; &#8594; Foundry &#8594; &#8594; 1400&#176;C &#8594; &#8594; Steel"),
]

OUTPUT = os.path.join("/home/z/my-project/src/components/modules", f"{THEME}-logistics-view.tsx")

L = []
L.append('"use client";')
L.append("")
L.append("import React, { useState, useMemo } from 'react';")
L.append("import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';")
L.append("import { Badge } from '@/components/ui/badge';")
L.append("import { PageHeader } from '@/components/shared';")
L.append("import { " + ICON + " } from 'lucide-react';")
L.append("")
L.append("interface " + INTERFACE + " {")
L.append("  id: string; batchNo: string; city: string; manufacturer: string; oxideGrade: string;")
L.append("  application: string; purityPercent: number; hardnessGPa: number; investmentCr: number;")
L.append("  status: string; priority: string; origin: string; destination: string;")
L.append("  shipDate: string; transitDays: number; zone: string; remarks: string;")
L.append("}")
L.append("")
L.append("const " + VAR + ": " + INTERFACE + "[] = [")
for i, rec in enumerate(RECORDS):
    rid,batch,city,mfr,grade,app,pur,hard,inv,stat,pri,orig,dest,ship,trans,zone,rem = rec
    L.append("  { id: '" + rid + "', batchNo: '" + batch + "', city: '" + city + "', manufacturer: '" + mfr + "', oxideGrade: '" + grade + "', application: '" + app + "', purityPercent: " + str(pur) + ", hardnessGPa: " + str(hard) + ", investmentCr: " + str(inv) + ", status: '" + stat + "', priority: '" + pri + "', origin: '" + orig + "', destination: '" + dest + "', shipDate: '" + ship + "', transitDays: " + str(trans) + ", zone: '" + zone + "', remarks: '" + rem + "' },")
L.append("];")
L.append("")
L.append("export default function " + COMPONENT + "LogisticsView() {")
L.append("  const [activeTab, setActiveTab] = useState<string>('dashboard');")
L.append("  const [searchTerm, setSearchTerm] = useState<string>('');")
L.append("  const [filterZone, setFilterZone] = useState<string>('all');")
L.append("  const [filterStatus, setFilterStatus] = useState<string>('all');")
L.append("")
L.append("  const tabs = [")
L.append("    { id: 'dashboard', label: 'Dashboard', icon: " + ICON + " },")
L.append("    { id: 'registry', label: 'Registry', icon: " + ICON + " },")
L.append("    { id: 'analytics', label: 'Analytics', icon: " + ICON + " },")
L.append("    { id: 'insights', label: 'Insights', icon: " + ICON + " },")
L.append("  ];")
L.append("")
L.append("  const filteredRecords = useMemo(() => {")
L.append("    return " + VAR + ".filter((r) => {")
L.append("      const matchSearch = searchTerm === '' ||")
L.append("        r.id.toLowerCase().includes(searchTerm.toLowerCase()) ||")
L.append("        r.batchNo.toLowerCase().includes(searchTerm.toLowerCase()) ||")
L.append("        r.city.toLowerCase().includes(searchTerm.toLowerCase()) ||")
L.append("        r.manufacturer.toLowerCase().includes(searchTerm.toLowerCase()) ||")
L.append("        r.oxideGrade.toLowerCase().includes(searchTerm.toLowerCase()) ||")
L.append("        r.application.toLowerCase().includes(searchTerm.toLowerCase());")
L.append("      const matchZone = filterZone === 'all' || r.zone === filterZone;")
L.append("      const matchStatus = filterStatus === 'all' || r.status === filterStatus;")
L.append("      return matchSearch && matchZone && matchStatus;")
L.append("    });")
L.append("  }, [searchTerm, filterZone, filterStatus]);")
L.append("")
L.append("  const zones = useMemo(() => {")
L.append("    const zMap: Record<string, number> = {};")
L.append("    " + VAR + ".forEach((r) => { zMap[r.zone] = (zMap[r.zone] || 0) + 1; });")
L.append("    return Object.entries(zMap).sort((a, b) => b[1] - a[1]);")
L.append("  }, []);")
L.append("")
L.append("  const kpiData = useMemo(() => {")
L.append("    const total = " + VAR + ".reduce((s: number, r) => s + r.investmentCr, 0);")
L.append("    const avgPurity = " + VAR + ".reduce((s: number, r) => s + r.purityPercent, 0) / " + VAR + ".length;")
L.append("    const delayed = " + VAR + ".filter((r) => r.status === 'Delayed').length;")
L.append("    const critical = " + VAR + ".filter((r) => r.priority === 'Critical').length;")
L.append("    return { total, avgPurity: avgPurity.toFixed(2), delayed, critical };")
L.append("  }, []);")
L.append("")
L.append("  const statusColor = (status: string) => {")
L.append("    switch (status) {")
L.append("      case 'Delivered': return 'bg-green-500/20 text-green-700 border-green-500/30';")
L.append("      case 'In Transit': return 'bg-blue-500/20 text-blue-700 border-blue-500/30';")
L.append("      case 'Delayed': return 'bg-red-500/20 text-red-700 border-red-500/30';")
L.append("      case 'Processing': return 'bg-yellow-500/20 text-yellow-700 border-yellow-500/30';")
L.append("      default: return 'bg-gray-500/20 text-gray-700 border-gray-500/30';")
L.append("    }")
L.append("  };")
L.append("")
L.append("  const priorityColor = (priority: string) => {")
L.append("    switch (priority) {")
L.append("      case 'Critical': return 'bg-red-500/20 text-red-700 border-red-500/30';")
L.append("      case 'High': return 'bg-orange-500/20 text-orange-700 border-orange-500/30';")
L.append("      case 'Medium': return 'bg-yellow-500/20 text-yellow-700 border-yellow-500/30';")
L.append("      case 'Low': return 'bg-green-500/20 text-green-700 border-green-500/30';")
L.append("      default: return 'bg-gray-500/20 text-gray-700 border-gray-500/30';")
L.append("    }")
L.append("  };")
L.append("")
L.append("  const themeColor = '" + COLOR + "';")
L.append("  return (")
L.append("    <div className=\"space-y-6 p-6\">")
L.append("      <PageHeader title=\"Chromium Oxide Logistics\" description=\"Indian chromium oxide pigment, refractory, ceramic TPS, abrasive, tanning and nuclear absorber supply chain tracking across 14 grades\" />")
L.append("      <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4\">")
L.append("        <Card className=\"border-l-4 border-l-violet-500\"><CardContent className=\"pt-6\"><div className=\"text-2xl font-bold text-violet-600\">{kpiData.total.toLocaleString()} Cr</div><div className=\"text-xs text-muted-foreground mt-1\">Total Investment</div></CardContent></Card>")
L.append("        <Card className=\"border-l-4 border-l-violet-500\"><CardContent className=\"pt-6\"><div className=\"text-2xl font-bold text-violet-600\">{kpiData.avgPurity}%</div><div className=\"text-xs text-muted-foreground mt-1\">Avg Purity</div></CardContent></Card>")
L.append("        <Card className=\"border-l-4 border-l-violet-500\"><CardContent className=\"pt-6\"><div className=\"text-2xl font-bold text-violet-600\">{kpiData.delayed}</div><div className=\"text-xs text-muted-foreground mt-1\">Delayed Batches</div></CardContent></Card>")
L.append("        <Card className=\"border-l-4 border-l-violet-500\"><CardContent className=\"pt-6\"><div className=\"text-2xl font-bold text-violet-600\">{kpiData.critical}</div><div className=\"text-xs text-muted-foreground mt-1\">Critical Records</div></CardContent></Card>")
L.append("      </div>")
L.append("      <div className=\"flex flex-wrap gap-2 border-b pb-2\">")
L.append("        {tabs.map((tab) => (")
L.append("          <button key={tab.id} onClick={() => setActiveTab(tab.id)} className={`px-4 py-2 rounded-t-md text-sm font-medium transition-colors ${activeTab === tab.id ? 'bg-violet-500 text-white shadow-md' : 'bg-muted text-muted-foreground hover:bg-muted/80'}`}>")
L.append("            {tab.label}")
L.append("          </button>")
L.append("        ))}")
L.append("      </div>")
# Dashboard
L.append("      {activeTab === 'dashboard' && (")
L.append("        <div className=\"grid grid-cols-1 lg:grid-cols-2 gap-4\">")
L.append("          <Card><CardHeader><CardTitle className=\"text-base\">Zone Distribution</CardTitle></CardHeader><CardContent>")
L.append("            <div className=\"space-y-2\">{zones.map(([zone, count]) => { const pct = (count as number / " + VAR + ".length) * 100; return <div key={zone} className=\"flex items-center gap-2\"><span className=\"text-xs w-16 text-muted-foreground\">{zone as string}</span><div className=\"flex-1 h-2 bg-muted rounded-full\"><div className=\"h-2 rounded-full\" style={{ width: `${pct}%`, backgroundColor: themeColor }} /></div><span className=\"text-xs font-medium w-8\">{count as number}</span></div>; })}</div>")
L.append("          </CardContent></Card>")
L.append("          <Card><CardHeader><CardTitle className=\"text-base\">Status Overview</CardTitle></CardHeader><CardContent>")
L.append("            <div className=\"grid grid-cols-2 gap-3\">")
L.append("              {['Delivered', 'In Transit', 'Delayed', 'Processing'].map((s) => { const c = " + VAR + ".filter((r) => r.status === s).length; return <div key={s} className={`text-center p-3 rounded-lg border ${statusColor(s)}`}><div className=\"text-lg font-bold\">{c}</div><div className=\"text-xs\">{s}</div></div>; })}")
L.append("            </div>")
L.append("          </CardContent></Card>")
L.append("          <Card className=\"lg:col-span-2\"><CardHeader><CardTitle className=\"text-base\">Investment by Grade (Top 8)</CardTitle></CardHeader><CardContent>")
L.append("            <div className=\"grid grid-cols-2 md:grid-cols-4 gap-3\">")
L.append("              {" + VAR + ".slice(0, 8).map((r) => <div key={r.id} className=\"text-center p-3 rounded-lg border bg-muted/30\"><div className=\"text-sm font-medium truncate\">{r.oxideGrade}</div><div className=\"text-lg font-bold\" style={{ color: themeColor }}>&#8377;{r.investmentCr}Cr</div><div className=\"text-xs text-muted-foreground\">{r.application}</div></div>)}")
L.append("            </div>")
L.append("          </CardContent></Card>")
L.append("        </div>")
L.append("      )}")
# Registry
L.append("      {activeTab === 'registry' && (")
L.append("        <div className=\"space-y-4\">")
L.append("          <div className=\"flex flex-wrap gap-3\">")
L.append("            <input type=\"text\" placeholder=\"Search ID, batch, city, grade...\" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className=\"px-3 py-2 border rounded-md text-sm flex-1 min-w-[200px]\" />")
L.append("            <select value={filterZone} onChange={(e) => setFilterZone(e.target.value)} className=\"px-3 py-2 border rounded-md text-sm\"><option value=\"all\">All Zones</option>{zones.map(([z]) => <option key={z} value={z}>{z as string}</option>)}</select>")
L.append("            <select value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)} className=\"px-3 py-2 border rounded-md text-sm\"><option value=\"all\">All Status</option>{['Delivered','In Transit','Delayed','Processing'].map((s) => <option key={s} value={s}>{s}</option>)}</select>")
L.append("          </div>")
L.append("          <div className=\"grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3\">")
L.append("            {filteredRecords.map((record) => (")
L.append("              <Card key={record.id} className={record.status === 'Delayed' ? 'border-l-4 border-l-red-500 bg-red-50/30' : ''}>")
L.append("                <CardContent className=\"pt-4 pb-4\">")
L.append("                  <div className=\"flex justify-between items-start mb-2\">")
L.append("                    <div><span className=\"font-semibold text-sm\">{record.id}</span><span className=\"text-xs text-muted-foreground ml-2\">{record.batchNo}</span></div>")
L.append("                    <div className=\"flex gap-1\"><Badge variant=\"outline\" className={statusColor(record.status)}>{record.status}</Badge><Badge variant=\"outline\" className={priorityColor(record.priority)}>{record.priority}</Badge></div>")
L.append("                  </div>")
L.append("                  <div className=\"text-xs space-y-1\">")
L.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">Grade:</span><span className=\"font-medium\">{record.oxideGrade}</span></div>")
L.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">Application:</span><span className=\"font-medium\">{record.application}</span></div>")
L.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">Purity:</span><span className=\"font-medium\">{record.purityPercent}%</span></div>")
L.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">Investment:</span><span className=\"font-medium\" style={{ color: themeColor }}>&#8377;{record.investmentCr}Cr</span></div>")
L.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">City:</span><span className=\"font-medium\">{record.city}</span></div>")
L.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">Route:</span><span className=\"font-medium text-xs\">{record.origin} &#8594; {record.destination}</span></div>")
L.append("                  </div>")
L.append("                </CardContent>")
L.append("              </Card>")
L.append("            ))}")
L.append("          </div>")
L.append("          <div className=\"text-sm text-muted-foreground\">Showing {filteredRecords.length} of {" + VAR + ".length} records</div>")
L.append("        </div>")
L.append("      )}")
# Analytics
L.append("      {activeTab === 'analytics' && (")
L.append("        <div className=\"grid grid-cols-1 lg:grid-cols-2 gap-4\">")
L.append("          <Card><CardHeader><CardTitle className=\"text-base\">Manufacturer Performance</CardTitle></CardHeader><CardContent>")
L.append("            <div className=\"space-y-2\">")
L.append("              {(() => { const mfrMap: Record<string, number> = {}; " + VAR + ".forEach((r) => { mfrMap[r.manufacturer] = (mfrMap[r.manufacturer] || 0) + r.investmentCr; }); return Object.entries(mfrMap).sort((a, b) => b[1] - a[1]).slice(0, 8).map(([mfr, inv]) => { const pct = (inv as number / kpiData.total) * 100; return <div key={mfr} className=\"flex items-center gap-2\"><span className=\"text-xs w-40 truncate\">{mfr as string}</span><div className=\"flex-1 h-2 bg-muted rounded-full\"><div className=\"h-2 rounded-full\" style={{ width: `${pct}%`, backgroundColor: themeColor }} /></div><span className=\"text-xs font-medium\">&#8377;{inv as number}Cr</span></div>; }); })()}")
L.append("            </div>")
L.append("          </CardContent></Card>")
L.append("          <Card><CardHeader><CardTitle className=\"text-base\">Priority Distribution</CardTitle></CardHeader><CardContent>")
L.append("            <div className=\"grid grid-cols-2 gap-3\">")
L.append("              {['Critical', 'High', 'Medium', 'Low'].map((p) => { const c = " + VAR + ".filter((r) => r.priority === p).length; return <div key={p} className={`text-center p-3 rounded-lg border ${priorityColor(p)}`}><div className=\"text-lg font-bold\">{c}</div><div className=\"text-xs\">{p}</div></div>; })}")
L.append("            </div>")
L.append("          </CardContent></Card>")
L.append("          <Card><CardHeader><CardTitle className=\"text-base\">Investment by Zone</CardTitle></CardHeader><CardContent>")
L.append("            <div className=\"space-y-2\">{(() => { const zInv: Record<string, number> = {}; " + VAR + ".forEach((r) => { zInv[r.zone] = (zInv[r.zone] || 0) + r.investmentCr; }); return Object.entries(zInv).sort((a, b) => b[1] - a[1]).map(([zone, inv]) => { const pct = (inv as number / kpiData.total) * 100; return <div key={zone} className=\"flex items-center gap-2\"><span className=\"text-xs w-16\">{zone as string}</span><div className=\"flex-1 h-2 bg-muted rounded-full\"><div className=\"h-2 rounded-full\" style={{ width: `${pct}%`, backgroundColor: themeColor }} /></div><span className=\"text-xs font-medium\">&#8377;{inv as number}Cr</span></div>; }); })()}</div>")
L.append("          </CardContent></Card>")
L.append("          <Card><CardHeader><CardTitle className=\"text-base\">Purity Distribution</CardTitle></CardHeader><CardContent>")
L.append("            <div className=\"space-y-2\">")
L.append("              {(() => { const ranges = { '99.5%+': 0, '99-99.4%': 0, '96-98.9%': 0, '<96%': 0 }; " + VAR + ".forEach((r) => { if (r.purityPercent >= 99.5) ranges['99.5%+']++; else if (r.purityPercent >= 99) ranges['99-99.4%']++; else if (r.purityPercent >= 96) ranges['96-98.9%']++; else ranges['<96%']++; }); return (Object.entries(ranges) as [string, number][]).filter(([, v]) => v > 0).map(([range, count]) => { const pct = (count / " + VAR + ".length) * 100; return <div key={range} className=\"flex items-center gap-2\"><span className=\"text-xs w-24\">{range}</span><div className=\"flex-1 h-2 bg-muted rounded-full\"><div className=\"h-2 rounded-full\" style={{ width: `${pct}%`, backgroundColor: themeColor }} /></div><span className=\"text-xs font-medium\">{count}</span></div>; }); })()}")
L.append("            </div>")
L.append("          </CardContent></Card>")
L.append("        </div>")
L.append("      )}")
# Insights
L.append("      {activeTab === 'insights' && (")
L.append("        <div className=\"grid grid-cols-1 md:grid-cols-2 gap-4\">")
L.append("          <Card><CardHeader><CardTitle className=\"text-base\">Supply Chain Intelligence</CardTitle></CardHeader><CardContent><div className=\"space-y-3 text-sm\">")
L.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-violet-500 bg-violet-50/50\"><div className=\"font-medium\">Nuclear Absorber Demand</div><div className=\"text-xs text-muted-foreground mt-1\">NPCIL PHWR 700 and BARC research reactor programme driving 99.9% chromia absorber &#8594; &#8377;940Cr for 400 tonnes &#8594; critical national security</div></div>")
L.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-violet-500 bg-violet-50/50\"><div className=\"font-medium\">Space TPS Growth</div><div className=\"text-xs text-muted-foreground mt-1\">ISRO RLV and GSLV Mk3 expansion &#8594; chromia ceramic TPS + NAL TBC &#8594; &#8377;1,640Cr combined for aerospace coatings</div></div>")
L.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-violet-500 bg-violet-50/50\"><div className=\"font-medium\">Defence Camouflage</div><div className=\"text-xs text-muted-foreground mt-1\">BEL DRDO NIR camouflage netting and vehicle paint &#8594; chromia green pigment military specification &#8594; &#8377;580Cr for 1,200 tonnes</div></div>")
L.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-violet-500 bg-violet-50/50\"><div className=\"font-medium\">Monsoon Disruption Alert</div><div className=\"text-xs text-muted-foreground mt-1\">CRO-B2412 GRSE submarine sonar dome delayed &#8594; monsoon Visakhapatnam &#8594; Project 75I Kalvari-class delivery risk</div></div>")
L.append("          </div></CardContent></Card>")
L.append("          <Card><CardHeader><CardTitle className=\"text-base\">Investment Landscape</CardTitle></CardHeader><CardContent><div className=\"space-y-3 text-sm\">")
L.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-violet-500 bg-violet-50/50\"><div className=\"font-medium\">Total Portfolio: &#8377;{kpiData.total.toLocaleString()} Cr</div><div className=\"text-xs text-muted-foreground mt-1\">Across 14 chromia grades spanning coatings, refractory, aerospace, defence, abrasive, glass, welding, tanning, naval and nuclear &#8594; avg purity {kpiData.avgPurity}%</div></div>")
L.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-violet-500 bg-violet-50/50\"><div className=\"font-medium\">Critical Priority: 4 Records</div><div className=\"text-xs text-muted-foreground mt-1\">ISRO TPS &#8594; CSIR-NAL TBC &#8594; GRSE submarine &#8594; NPCIL absorber &#8594; strategic programmes</div></div>")
L.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-violet-500 bg-violet-50/50\"><div className=\"font-medium\">Top Applications</div><div className=\"text-xs text-muted-foreground mt-1\">Nuclear absorber &#8594; aerospace TPS/TBC &#8594; automotive coating &#8594; steel refractory &#8594; abrasive grinding &#8594; 5 sectors above &#8377;600Cr</div></div>")
L.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-violet-500 bg-violet-50/50\"><div className=\"font-medium\">Import Dependency</div><div className=\"text-xs text-muted-foreground mt-1\">High-purity 99.5%+ chromia still 40% imported &#8594; Sukinda chromite expansion and UP Chrome capacity ramp critical for Atmanirbhar</div></div>")
L.append("          </div></CardContent></Card>")
L.append("        </div>")
L.append("      )}")
L.append("    </div>")
L.append("  );")
L.append("}")
L.append("")

content = "\n".join(L)

import re
bad = [e for e in re.findall(r'&#(\d+);', content) if int(e) > 9999]
if bad:
    print(f"WARNING: bad entities: {bad}")
else:
    print(f"OK: {len(re.findall(r'&#(\d+);', content))} entities, all clean")

with open(OUTPUT, "w") as f:
    f.write(content)
print(f"Generated {OUTPUT} ({len(L)} lines)")
print(f"Records: {len(RECORDS)}, Total: {sum(r[8] for r in RECORDS)} Cr, Avg purity: {sum(r[6] for r in RECORDS)/len(RECORDS):.2f}%")
