#!/usr/bin/env python3
"""R264: Smart Dock Scheduler + Logistics AI Copilot."""
import os
BASE = "/home/z/my-project/src/components/modules"

# ─── Module A: Smart Dock Scheduler ───
def gen_dock_scheduler():
    L = []
    def a(s): L.append(s)
    a('"use client"')
    a('import { useState, useMemo } from "react"')
    a('import { AreaChart, Area, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts"')
    a('import { Anchor, Clock, Truck, AlertTriangle, CheckCircle2, BarChart3, TrendingUp, TrendingDown, Zap, Eye, Search, Thermometer, Wrench, MapPin, Package, Timer, ArrowUpDown, Radio } from "lucide-react"')
    a('import { PageHeader } from "@/components/shared/page-header"')
    a('import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar"')
    a('import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb"')
    a('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
    a('import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"')
    a('import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"')
    a('import { Badge } from "@/components/ui/badge"')
    a('')
    a('const DOCK_TYPES = ["loading", "unloading", "cross_dock", "cold_storage", "hazardous", "bulk"] as const')
    a('const DOCK_EMOJI: Record<string, string> = { loading: "\\U0001f4e5", unloading: "\\U0001f4e4", cross_dock: "\\u27a1\\ufe0f", cold_storage: "\\u2744\\ufe0f", hazardous: "\\u2622\\ufe0f", bulk: "\\U0001f4e6" }')
    a('const DOCK_STATUS = ["available", "occupied", "maintenance", "reserved", "blocked"] as const')
    a('const APPT_STATUS = ["scheduled", "checked_in", "loading", "unloading", "completed", "cancelled", "delayed"] as const')
    a('const CITIES = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Hyderabad", "Kolkata", "Pune", "Ahmedabad"] as const')
    a('const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] as const')
    a('const TH = { pri: "#3b82f6", sec: "#f59e0b", ok: "#059669", warn: "#d97706", err: "#dc2626" }')
    a('const PC = ["#3b82f6", "#f59e0b", "#059669", "#dc2626", "#8b5cf6", "#06b6d4", "#ec4899", "#14b8a6"]')
    a('')
    a('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297) * 233280; return x - Math.floor(x) }')
    a('function ri(min: number, max: number, seed: number): number { return Math.floor(seededRandom(seed) * (max - min + 1)) + min }')
    a('function pick<T>(arr: readonly T[], seed: number): T { return arr[Math.floor(seededRandom(seed) * arr.length)] }')
    a('')
    a('function DockTypeBadge({ type }: { type: string }) {')
    a('  const cols: Record<string, string> = { loading: "bg-blue-100 text-blue-700 dark:bg-blue-900/30", unloading: "bg-amber-100 text-amber-700 dark:bg-amber-900/30", cross_dock: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30", cold_storage: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30", hazardous: "bg-red-100 text-red-700 dark:bg-red-900/30", bulk: "bg-violet-100 text-violet-700 dark:bg-violet-900/30" }')
    a('  return <span className={"sds-dock-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[type] || "bg-gray-100 text-gray-700")}>{DOCK_EMOJI[type] || "\\u2022"} {type.replace(/_/g, " ")}</span>')
    a('}')
    a('')
    a('function DockStatusBadge({ status }: { status: string }) {')
    a('  const cols: Record<string, string> = { available: "sds-available bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 shadow-[0_0_6px_rgba(5,150,105,0.3)]", occupied: "sds-occupied bg-blue-100 text-blue-700 dark:bg-blue-900/30", maintenance: "sds-maint bg-amber-100 text-amber-700 dark:bg-amber-900/30", reserved: "sds-reserved bg-violet-100 text-violet-700 dark:bg-violet-900/30", blocked: "sds-blocked bg-red-100 text-red-700 dark:bg-red-900/30 shadow-[0_0_8px_rgba(220,38,38,0.4)]" }')
    a('  const icons: Record<string, React.ReactNode> = { available: <CheckCircle2 className="w-3 h-3" />, occupied: <Truck className="w-3 h-3" />, maintenance: <Wrench className="w-3 h-3" />, reserved: <Clock className="w-3 h-3" />, blocked: <AlertTriangle className="w-3 h-3" /> }')
    a('  return <span className={"sds-status-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[status] || "")}>{icons[status]} {status}</span>')
    a('}')
    a('')
    a('function ApptStatusBadge({ status }: { status: string }) {')
    a('  const cols: Record<string, string> = { scheduled: "bg-gray-100 text-gray-600", checked_in: "bg-blue-100 text-blue-700", loading: "bg-violet-100 text-violet-700", unloading: "bg-amber-100 text-amber-700", completed: "bg-emerald-100 text-emerald-700", cancelled: "bg-red-100 text-red-700", delayed: "bg-red-100 text-red-700 shadow-[0_0_6px_rgba(220,38,38,0.3)]" }')
    a('  return <span className={"sds-appt-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[status] || "")}>{status.replace(/_/g, " ")}</span>')
    a('}')
    a('')
    a('function UtilBar({ value }: { value: number }) {')
    a('  const col = value >= 80 ? TH.err : value >= 50 ? TH.warn : TH.ok')
    a('  return <div className="sds-util-bar flex items-center gap-1.5"><div className="w-16 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: value + "%", backgroundColor: col }}/></div><span className="text-[10px] font-bold" style={{ color: col }}>{value}%</span></div>')
    a('}')
    a('')
    a('function TrendIndicator({ value }: { value: number }) {')
    a('  const pos = value > 0; const col = pos ? TH.ok : TH.err')
    a('  return <span className="sds-trend inline-flex items-center gap-0.5 text-[10px] font-semibold" style={{ color: col }}>{pos ? <TrendingUp className="w-3 h-3" /> : <TrendingDown className="w-3 h-3" />}{Math.abs(value).toFixed(1)}%</span>')
    a('}')
    a('')
    a('function CityBadge({ city }: { city: string }) { return <span className="sds-city-badge inline-flex items-center px-2 py-0.5 rounded text-[10px] font-medium bg-blue-50 text-blue-700 dark:bg-blue-900/20">{city}</span> }')
    a('')
    a('function KpiTile({ label, value, icon, trend, color }: { label: string; value: string; icon: React.ReactNode; trend: number; color: string }) { return <Card className="sds-kpi-tile glass-subtle hover:shadow-lg transition-shadow border-l-4" style={{ borderLeftColor: color }}><CardContent className="p-3"><div className="flex items-center justify-between"><span className="text-[10px] text-muted-foreground">{label}</span>{icon}</div><div className="text-xl font-bold mt-1">{value}</div><TrendIndicator value={trend}/></CardContent></Card> }')
    a('')
    a('function ValueTile({ label, value }: { label: string; value: string | number }) { return <div className="sds-value-tile text-center p-2 rounded-lg bg-gray-50 dark:bg-gray-800/50"><div className="text-sm font-bold">{value}</div><div className="text-[10px] text-muted-foreground">{label}</div></div> }')
    a('')
    a('function HealthRing({ value, label }: { value: number; label: string }) { const col = value >= 90 ? TH.ok : value >= 70 ? TH.warn : TH.err; const r = 18, circ = 2 * Math.PI * r, offset = circ - (value / 100) * circ; return <div className="sds-health-ring flex flex-col items-center gap-1"><svg width={48} height={48} className="-rotate-90"><circle cx={24} cy={24} r={r} fill="none" stroke="currentColor" strokeWidth={3} className="text-gray-200 dark:text-gray-700"/><circle cx={24} cy={24} r={r} fill="none" stroke={col} strokeWidth={3} strokeDasharray={circ} strokeDashoffset={offset} strokeLinecap="round" className="transition-all"/></svg><span className="text-[10px] font-bold" style={{ color: col }}>{value}%</span><span className="text-[9px] text-muted-foreground">{label}</span></div> }')
    a('')
    a('function genDocks() {')
    a('  return Array.from({ length: 40 }, (_, i) => ({')
    a('    id: "DK-" + String(i + 1).padStart(3, "0"),')
    a('    type: pick(DOCK_TYPES, i * 3 + 1),')
    a('    name: pick(["Gate Alpha", "Gate Bravo", "Gate Charlie", "Gate Delta", "Bay 1", "Bay 2", "Dock East", "Dock West", "Platform A", "Ramp B"], i * 3 + 2),')
    a('    city: pick(CITIES, i * 3 + 3),')
    a('    status: pick(DOCK_STATUS, i + 5),')
    a('    utilization: ri(10, 95, i + 7),')
    a('    throughput: ri(5, 50, i + 11),')
    a('    avgWait: ri(5, 120, i + 13),')
    a('    capacity: ri(2, 8, i + 17),')
    a('    currentLoad: ri(0, 8, i + 19),')
    a('    temperature: ri(18, 35, i + 23),')
    a('    lastService: "2026-07-" + String(ri(1, 30, i + 29)).padStart(2, "0"),')
    a('    equipment: pick(["Conveyor", "Forklift", "Pallet Jack", "Scanner", "Scale", "Chiller"], i + 31)')
    a('  }))')
    a('}')
    a('')
    a('function genAppointments() {')
    a('  return Array.from({ length: 60 }, (_, i) => ({')
    a('    id: "APT-" + String(i + 1).padStart(5, "0"),')
    a('    dock: "DK-" + String(ri(1, 40, i + 7)).padStart(3, "0"),')
    a('    carrier: pick(["BlueDart", "Delhivery", "DTDC", "XpressBees", "Ecom Express", "Shadowfax", "Spoton", "Amazon Truck"], i + 11),')
    a('    vehicle: pick(["TRK-" + String(ri(100, 999, i + 13)), "VAN-" + String(ri(100, 999, i + 17)), "FLT-" + String(ri(10, 99, i + 19))], i + 23),')
    a('    status: pick(APPT_STATUS, i + 29),')
    a('    scheduledTime: String(ri(6, 22, i + 31)).padStart(2, "0") + ":" + String(ri(0, 59, i + 37)).padStart(2, "0"),')
    a('    actualTime: String(ri(6, 23, i + 41)).padStart(2, "0") + ":" + String(ri(0, 59, i + 43)).padStart(2, "0"),')
    a('    delay: ri(-15, 90, i + 47),')
    a('    pallets: ri(1, 40, i + 51),')
    a('    weight: ri(100, 8000, i + 53),')
    a('    priority: pick(["high", "medium", "low"], i + 57),')
    a('    date: "2026-07-" + String(ri(1, 30, i + 59)).padStart(2, "0")')
    a('  }))')
    a('}')
    a('')
    a('function genCharts() {')
    a('  const hourly = MO.map((m, i) => ({ month: m, scheduled: ri(200, 800, i + 101), completed: ri(150, 750, i + 151), delayed: ri(10, 80, i + 201), cancelled: ri(5, 30, i + 251) }))')
    a('  const typeDist = DOCK_TYPES.map((t, i) => ({ type: t, count: ri(3, 12, i + 301), avgUtil: ri(40, 90, i + 351) }))')
    a('  const waitLine = MO.map((m, i) => ({ month: m, avgWait: ri(15, 90, i + 401), target: 30, peakWait: ri(60, 180, i + 451) }))')
    a('  return { hourly, typeDist, waitLine }')
    a('}')
    a('')
    a('export default function SmartDockSchedulerView() {')
    a('  const [tab, setTab] = useState("dashboard")')
    a('  const [search, setSearch] = useState("")')
    a('  const [detail, setDetail] = useState<Record<string, unknown> | null>(null)')
    a('  const [sortField, setSortField] = useState("id")')
    a('  const [sortDir, setSortDir] = useState<"asc" | "desc">("asc")')
    a('  const [activeFilters, setActiveFilters] = useState<Record<string, string[]>>({})')
    a('  const docks = useMemo(() => genDocks(), [])')
    a('  const appointments = useMemo(() => genAppointments(), [])')
    a('  const charts = useMemo(() => genCharts(), [])')
    a('  const toggleSort = (f: string) => { if (sortField === f) setSortDir(d => d === "asc" ? "desc" : "asc"); else { setSortField(f); setSortDir("asc") } }')
    a('  const sortIcon = (f: string) => sortField === f ? (sortDir === "asc" ? "\\u2191" : "\\u2193") : ""')
    a('  const filterDocks = useMemo(() => { if (!search) return docks; const lq = search.toLowerCase(); return docks.filter(d => Object.values(d).some(v => typeof v === "string" && v.toLowerCase().includes(lq))) }, [docks, search])')
    a('  const sortedDocks = useMemo(() => [...filterDocks].sort((a, b) => { const va = a[sortField as keyof typeof a], vb = b[sortField as keyof typeof b]; if (va == null || vb == null) return 0; return sortDir === "asc" ? String(va).localeCompare(String(vb), undefined, { numeric: true }) : -String(va).localeCompare(String(vb), undefined, { numeric: true }) }), [filterDocks, sortField, sortDir])')
    a('  const filterAppts = useMemo(() => { if (!search) return appointments; const lq = search.toLowerCase(); return appointments.filter(a => Object.values(a).some(v => typeof v === "string" && v.toLowerCase().includes(lq))) }, [appointments, search])')
    a('  const availDocks = docks.filter(d => d.status === "available").length')
    a('  const avgUtil = Math.round(docks.reduce((s, d) => s + d.utilization, 0) / docks.length)')
    a('  const avgWait = Math.round(docks.reduce((s, d) => s + d.avgWait, 0) / docks.length)')
    a('  const completedAppts = appointments.filter(a => a.status === "completed").length')
    a('  const handleRefresh = () => { setSearch(""); setSortField("id"); setSortDir("asc"); setActiveFilters({}) }')
    a('  const toggleFilter = (group: string, value: string) => { setActiveFilters(prev => { const cur = prev[group] || []; const next = cur.includes(value) ? cur.filter(v => v !== value) : [...cur, value]; if (next.length === 0) { const { [group]: _, ...rest } = prev; return rest } return { ...prev, [group]: next } }) }')
    a('  const clearAllFilters = () => setActiveFilters({})')
    a('  const totalActiveFilters = Object.values(activeFilters).reduce((s, v) => s + v.length, 0)')
    a('  const dockFilterGroups = useMemo(() => { const tc: Record<string, number> = {}; const sc: Record<string, number> = {}; docks.forEach(d => { tc[d.type] = (tc[d.type] || 0) + 1; sc[d.status] = (sc[d.status] || 0) + 1 }); return [{ key: "type", label: "Type", options: Object.entries(tc).map(([value, count]) => ({ value, count })).sort((a, b) => b.count - a.count) }, { key: "status", label: "Status", options: Object.entries(sc).map(([value, count]) => ({ value, count })).sort((a, b) => b.count - a.count) }] }, [docks])')
    a('')
    a('  const tab0 = (<div className="space-y-4"><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><KpiTile label="Available Docks" value={String(availDocks)} icon={<Anchor className="w-4 h-4 text-blue-500"/>} trend={5.2} color={TH.pri}/><KpiTile label="Avg Utilization" value={avgUtil + "%"} icon={<Zap className="w-4 h-4 text-amber-500"/>} trend={2.3} color={TH.sec}/><KpiTile label="Avg Wait Time" value={avgWait + " min"} icon={<Clock className="w-4 h-4 text-red-500"/>} trend={-8.1} color={TH.err}/><KpiTile label="Completed" value={String(completedAppts)} icon={<CheckCircle2 className="w-4 h-4 text-emerald-500"/>} trend={11.4} color={TH.ok}/></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><HealthRing value={100 - avgUtil} label="Free Capacity"/><HealthRing value={Math.round(appointments.filter(a => a.status === "completed").length / appointments.length * 100)} label="On-Time"/><HealthRing value={95} label="Equipment"/><HealthRing value={Math.round((1 - docks.filter(d => d.status === "blocked").length / docks.length) * 100)} label="Operational"/></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><Card className="sds-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Appointment Volume</CardTitle></CardHeader><CardContent><AreaChart data={charts.hourly} height={200}><CartesianGrid strokeDasharray="3 3" opacity={0.3}/><XAxis dataKey="month" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip contentStyle={{ fontSize: 10 }}/><Area type="monotone" dataKey="scheduled" stroke={TH.pri} fill={TH.pri} fillOpacity={0.2}/><Area type="monotone" dataKey="completed" stroke={TH.ok} fill={TH.ok} fillOpacity={0.15}/><Line type="monotone" dataKey="delayed" stroke={TH.err} strokeWidth={2} dot={{ r: 3 }}/></AreaChart></CardContent></Card><Card className="sds-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Dock Type & Utilization</CardTitle></CardHeader><CardContent><BarChart data={charts.typeDist} height={200}><CartesianGrid strokeDasharray="3 3" opacity={0.3}/><XAxis dataKey="type" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip contentStyle={{ fontSize: 10 }}/><Bar dataKey="count" fill={TH.pri} radius={[2, 2, 0, 0]}/><Bar dataKey="avgUtil" fill={TH.sec} radius={[2, 2, 0, 0]}/></BarChart></CardContent></Card><Card className="sds-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Wait Time Trend</CardTitle></CardHeader><CardContent><LineChart data={charts.waitLine} height={200}><CartesianGrid strokeDasharray="3 3" opacity={0.3}/><XAxis dataKey="month" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip contentStyle={{ fontSize: 10 }}/><Line type="monotone" dataKey="avgWait" stroke={TH.warn} strokeWidth={2} dot={{ r: 3 }}/><Line type="monotone" dataKey="target" stroke={TH.ok} strokeWidth={2} strokeDasharray="5 5" dot={{ r: 3 }}/><Line type="monotone" dataKey="peakWait" stroke={TH.err} strokeWidth={2} dot={{ r: 3 }}/></LineChart></CardContent></Card><Card className="sds-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Dock Status Distribution</CardTitle></CardHeader><CardContent><PieChart width={300} height={200}><Pie data={DOCK_STATUS.map(s => ({ name: s, value: docks.filter(d => d.status === s).length }))} cx="50%" cy="50%" outerRadius={70} dataKey="value" label={({ name, percent }) => name + " " + (percent * 100).toFixed(0) + "%"} labelLine={false}>{DOCK_STATUS.map((_, i) => <Cell key={i} fill={PC[i % PC.length]}/>)}</Pie><Tooltip contentStyle={{ fontSize: 10 }}/></PieChart></CardContent></Card></div></div>)')
    a('')
    a('  const tab1 = (<div className="space-y-3"><ModuleBreadcrumb items={[{ label: "Warehouse" }, { label: "Dock Scheduling" }, { label: "Docks" }]}/><SearchFilterToolbar searchQuery={search} onSearchChange={setSearch} onClearSearch={() => setSearch("")} activeFilters={activeFilters} filterGroups={dockFilterGroups} onToggleFilter={toggleFilter} onClearAllFilters={clearAllFilters} totalItems={docks.length} filteredCount={sortedDocks.length} onRefresh={handleRefresh} placeholder="Search docks by name, type..." /><div className="rounded-lg border overflow-auto max-h-[calc(100vh-340px)]"><table className="sds-table w-full text-xs"><thead className="bg-blue-50 dark:bg-blue-900/20 sticky top-0"><tr><th className="p-2 text-left cursor-pointer select-none" onClick={() => toggleSort("id")}>ID {sortIcon("id")}</th><th className="p-2 text-left">Name</th><th className="p-2 text-left">Type</th><th className="p-2 text-left">City</th><th className="p-2 text-left">Status</th><th className="p-2 text-left">Utilization</th><th className="p-2 text-right">Throughput</th><th className="p-2 text-right">Wait</th><th className="p-2 text-left">Equipment</th></tr></thead><tbody>{sortedDocks.map(d => <tr key={d.id} className="sds-table-row border-t hover:bg-blue-50/50 dark:hover:bg-blue-900/10 cursor-pointer" onClick={() => setDetail(d as unknown as Record<string, unknown>)}><td className="p-2 font-mono">{d.id}</td><td className="p-2 font-medium">{d.name}</td><td className="p-2"><DockTypeBadge type={d.type}/></td><td className="p-2"><CityBadge city={d.city}/></td><td className="p-2"><DockStatusBadge status={d.status}/></td><td className="p-2"><UtilBar value={d.utilization}/></td><td className="p-2 text-right">{d.throughput}/hr</td><td className="p-2 text-right">{d.avgWait} min</td><td className="p-2 text-[10px]">{d.equipment}</td></tr>)}</tbody></table></div><div className="flex items-center justify-between text-[10px] text-muted-foreground"><span>Showing {sortedDocks.length} of {docks.length} docks</span>{totalActiveFilters > 0 && <span>{totalActiveFilters} filters</span>}</div></div>)')
    a('')
    a('  const tab2 = (<div className="space-y-3"><ModuleBreadcrumb items={[{ label: "Warehouse" }, { label: "Dock Scheduling" }, { label: "Appointments" }]}/><SearchFilterToolbar searchQuery={search} onSearchChange={setSearch} onClearSearch={() => setSearch("")} activeFilters={activeFilters} filterGroups={[]} onToggleFilter={toggleFilter} onClearAllFilters={clearAllFilters} totalItems={appointments.length} filteredCount={filterAppts.length} onRefresh={handleRefresh} placeholder="Search appointments..." /><div className="rounded-lg border overflow-auto max-h-[calc(100vh-340px)]"><table className="sds-table w-full text-xs"><thead className="bg-amber-50 dark:bg-amber-900/20 sticky top-0"><tr><th className="p-2 text-left cursor-pointer select-none" onClick={() => toggleSort("id")}>ID {sortIcon("id")}</th><th className="p-2 text-left">Carrier</th><th className="p-2 text-left">Dock</th><th className="p-2 text-left">Status</th><th className="p-2 text-left">Scheduled</th><th className="p-2 text-left">Actual</th><th className="p-2 text-right">Delay</th><th className="p-2 text-right">Pallets</th><th className="p-2 text-left">Priority</th></tr></thead><tbody>{filterAppts.map(ap => <tr key={ap.id} className="sds-table-row border-t hover:bg-amber-50/50 dark:hover:bg-amber-900/10 cursor-pointer" onClick={() => setDetail(ap as unknown as Record<string, unknown>)}><td className="p-2 font-mono">{ap.id}</td><td className="p-2 font-medium">{ap.carrier}</td><td className="p-2 font-mono text-[10px]">{ap.dock}</td><td className="p-2"><ApptStatusBadge status={ap.status}/></td><td className="p-2 text-[10px]">{ap.scheduledTime}</td><td className="p-2 text-[10px]">{ap.actualTime}</td><td className="p-2 text-right"><span className="text-[10px] font-bold" style={{ color: ap.delay > 15 ? TH.err : ap.delay > 0 ? TH.warn : TH.ok }}>{ap.delay > 0 ? "+" + ap.delay : "0"} min</span></td><td className="p-2 text-right">{ap.pallets}</td><td className="p-2"><span className={"inline-flex px-1.5 py-0.5 rounded text-[10px] font-medium " + (ap.priority === "high" ? "bg-red-100 text-red-700" : ap.priority === "medium" ? "bg-amber-100 text-amber-700" : "bg-emerald-100 text-emerald-700")}>{ap.priority}</span></td></tr>)}</tbody></table></div><div className="text-[10px] text-muted-foreground text-right">{filterAppts.length} appointments</div></div>)')
    a('')
    a('  const tabs = [{ key: "dashboard", label: "Dashboard", icon: <BarChart3 className="w-3.5 h-3.5" />, content: tab0 }, { key: "docks", label: "Docks", icon: <Anchor className="w-3.5 h-3.5" />, content: tab1 }, { key: "appointments", label: "Appointments", icon: <Clock className="w-3.5 h-3.5" />, content: tab2 }]')
    a('')
    a('  return (<div className="space-y-4 p-4"><PageHeader title="Smart Dock Scheduler" description="AI-powered dock scheduling with real-time bay management, appointment optimization, and wait time analytics"/><div className="flex items-center gap-3 flex-wrap"><div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-blue-100 dark:bg-blue-900/30"><Anchor className="w-3 h-3 text-blue-600"/><span className="text-[10px] font-semibold text-blue-700 dark:text-blue-300">{availDocks} Docks Available</span></div><div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-100 dark:bg-emerald-900/30"><CheckCircle2 className="w-3 h-3 text-emerald-600"/><span className="text-[10px] font-semibold text-emerald-700 dark:text-emerald-300">{completedAppts} Completed Today</span></div><div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-amber-100 dark:bg-amber-900/30"><Clock className="w-3 h-3 text-amber-600"/><span className="text-[10px] font-semibold text-amber-700 dark:text-amber-300">{avgWait} min Avg Wait</span></div><div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-violet-100 dark:bg-violet-900/30"><Radio className="w-3 h-3 text-violet-600"/><span className="text-[10px] font-semibold text-violet-700 dark:text-violet-300">{docks.length} Total Docks</span></div></div><Tabs value={tab} onValueChange={setTab}><TabsList className="bg-gradient-to-r from-blue-500/10 to-amber-500/10 p-0.5 h-9">{tabs.map(t => <TabsTrigger key={t.key} value={t.key} className="text-xs gap-1.5 data-[state=active]:bg-blue-600 data-[state=active]:text-white">{t.icon}{t.label}</TabsTrigger>)}</TabsList>{tabs.map(t => tab === t.key && <div key={t.key} className="mt-3">{t.content}</div>)}</Tabs><Sheet open={!!detail} onOpenChange={() => setDetail(null)}><SheetContent className="w-[420px] overflow-y-auto"><SheetHeader><SheetTitle className="text-sm">Detail View</SheetTitle></SheetHeader>{detail && <div className="mt-4 space-y-3"><div className="sds-detail-header rounded-lg p-4 bg-gradient-to-br from-blue-500 to-amber-600 text-white"><div className="text-lg font-bold">{String(detail.id)}</div><div className="text-xs opacity-80 mt-1">{String(detail.name || detail.carrier || "Record")}</div></div>{Object.entries(detail).filter(([k]) => k !== "id").map(([k, v]) => <div key={k} className="flex items-center justify-between py-1.5 border-b"><span className="text-[10px] text-muted-foreground capitalize">{k.replace(/_/g, " ")}</span><span className="text-xs font-medium">{typeof v === "number" ? v.toLocaleString() : String(v)}</span></div>)}</div>}</SheetContent></Sheet></div>)')
    a('}')
    
    with open(os.path.join(BASE, "smart-dock-scheduler-view.tsx"), "w") as f:
        f.write("\n".join(L))
    print(f"Module A: smart-dock-scheduler-view.tsx ({len(L)} lines)")

# ─── Module B: Logistics AI Copilot ───
def gen_ai_copilot():
    L = []
    def a(s): L.append(s)
    a('"use client"')
    a('import { useState, useMemo } from "react"')
    a('import { AreaChart, Area, BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts"')
    a('import { BrainCircuit, Sparkles, MessageSquare, BarChart3, TrendingUp, TrendingDown, Lightbulb, Target, Zap, CheckCircle2, Clock, AlertTriangle, Search, Eye, FileText, ArrowRight, Star, ThumbsUp, ThumbsDown, Bot } from "lucide-react"')
    a('import { PageHeader } from "@/components/shared/page-header"')
    a('import { SearchFilterToolbar } from "@/components/shared/search-filter-toolbar"')
    a('import { ModuleBreadcrumb } from "@/components/shared/module-breadcrumb"')
    a('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
    a('import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"')
    a('import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"')
    a('import { Badge } from "@/components/ui/badge"')
    a('')
    a('const AI_MODULES = ["demand_forecast", "route_optimizer", "inventory_agent", "risk_analyzer", "cost_predictor", "supplier_eval", "shipment_tracker", "warehouse_planner"] as const')
    a('const AI_EMOJI: Record<string, string> = { demand_forecast: "\\U0001f4ca", route_optimizer: "\\U0001f5fa", inventory_agent: "\\U0001f4e6", risk_analyzer: "\\u26a0\\ufe0f", cost_predictor: "\\U0001f4b0", supplier_eval: "\\U0001f91d", shipment_tracker: "\\U0001f4e8", warehouse_planner: "\\U0001f3ed" }')
    a('const SUGGESTION_TYPES = ["cost_saving", "efficiency", "risk_mitigation", "automation", "capacity", "quality", "sustainability", "customer_exp"] as const')
    a('const SUGG_EMOJI: Record<string, string> = { cost_saving: "\\U0001f4b0", efficiency: "\\u26a1", risk_mitigation: "\\U0001f6e1", automation: "\\U0001f916", capacity: "\\U0001f4e6", quality: "\\u2b50", sustainability: "\\U0001f333", customer_exp: "\\u2764\\ufe0f" }')
    a('const INSIGHT_STATUS = ["new", "reviewed", "implemented", "dismissed", "expired"] as const')
    a('const CITIES = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Hyderabad", "Kolkata", "Pune", "Ahmedabad"] as const')
    a('const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] as const')
    a('const TH = { pri: "#8b5cf6", sec: "#f59e0b", ok: "#059669", warn: "#d97706", err: "#dc2626" }')
    a('const PC = ["#8b5cf6", "#f59e0b", "#059669", "#dc2626", "#3b82f6", "#06b6d4", "#ec4899", "#14b8a6"]')
    a('')
    a('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297) * 233280; return x - Math.floor(x) }')
    a('function ri(min: number, max: number, seed: number): number { return Math.floor(seededRandom(seed) * (max - min + 1)) + min }')
    a('function pick<T>(arr: readonly T[], seed: number): T { return arr[Math.floor(seededRandom(seed) * arr.length)] }')
    a('')
    a('function AiModuleBadge({ module }: { module: string }) {')
    a('  const cols: Record<string, string> = { demand_forecast: "bg-violet-100 text-violet-700 dark:bg-violet-900/30", route_optimizer: "bg-blue-100 text-blue-700 dark:bg-blue-900/30", inventory_agent: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30", risk_analyzer: "bg-red-100 text-red-700 dark:bg-red-900/30", cost_predictor: "bg-amber-100 text-amber-700 dark:bg-amber-900/30", supplier_eval: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30", shipment_tracker: "bg-pink-100 text-pink-700 dark:bg-pink-900/30", warehouse_planner: "bg-orange-100 text-orange-700 dark:bg-orange-900/30" }')
    a('  return <span className={"aic-module-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[module] || "bg-gray-100 text-gray-700")}>{AI_EMOJI[module] || "\\u2022"} {module.replace(/_/g, " ")}</span>')
    a('}')
    a('')
    a('function SuggTypeBadge({ type }: { type: string }) { return <span className="aic-sugg-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30">{SUGG_EMOJI[type] || "\\u2022"} {type.replace(/_/g, " ")}</span> }')
    a('')
    a('function InsightStatusBadge({ status }: { status: string }) {')
    a('  const cols: Record<string, string> = { new: "aic-new bg-blue-100 text-blue-700 dark:bg-blue-900/30 shadow-[0_0_6px_rgba(59,130,246,0.3)]", reviewed: "aic-reviewed bg-amber-100 text-amber-700 dark:bg-amber-900/30", implemented: "aic-implemented bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 shadow-[0_0_6px_rgba(5,150,105,0.3)]", dismissed: "aic-dismissed bg-gray-100 text-gray-500 dark:bg-gray-900/30", expired: "aic-expired bg-gray-200 text-gray-400 dark:bg-gray-800" }')
    a('  return <span className={"aic-status-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cols[status] || "")}>{status}</span>')
    a('}')
    a('')
    a('function ConfBar({ value }: { value: number }) { const col = value >= 80 ? TH.ok : value >= 50 ? TH.warn : TH.err; return <div className="aic-conf-bar flex items-center gap-1.5"><div className="w-16 h-2 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden"><div className="h-full rounded-full transition-all" style={{ width: value + "%", backgroundColor: col }}/></div><span className="text-[10px] font-bold" style={{ color: col }}>{value}%</span></div> }')
    a('')
    a('function TrendIndicator({ value }: { value: number }) { const pos = value > 0; const col = pos ? TH.ok : TH.err; return <span className="aic-trend inline-flex items-center gap-0.5 text-[10px] font-semibold" style={{ color: col }}>{pos ? <TrendingUp className="w-3 h-3" /> : <TrendingDown className="w-3 h-3" />}{Math.abs(value).toFixed(1)}%</span> }')
    a('')
    a('function CityBadge({ city }: { city: string }) { return <span className="aic-city-badge inline-flex items-center px-2 py-0.5 rounded text-[10px] font-medium bg-violet-50 text-violet-700 dark:bg-violet-900/20">{city}</span> }')
    a('')
    a('function KpiTile({ label, value, icon, trend, color }: { label: string; value: string; icon: React.ReactNode; trend: number; color: string }) { return <Card className="aic-kpi-tile glass-subtle hover:shadow-lg transition-shadow border-l-4" style={{ borderLeftColor: color }}><CardContent className="p-3"><div className="flex items-center justify-between"><span className="text-[10px] text-muted-foreground">{label}</span>{icon}</div><div className="text-xl font-bold mt-1">{value}</div><TrendIndicator value={trend}/></CardContent></Card> }')
    a('')
    a('function ValueTile({ label, value }: { label: string; value: string | number }) { return <div className="aic-value-tile text-center p-2 rounded-lg bg-gray-50 dark:bg-gray-800/50"><div className="text-sm font-bold">{value}</div><div className="text-[10px] text-muted-foreground">{label}</div></div> }')
    a('')
    a('function HealthRing({ value, label }: { value: number; label: string }) { const col = value >= 90 ? TH.ok : value >= 70 ? TH.warn : TH.err; const r = 18, circ = 2 * Math.PI * r, offset = circ - (value / 100) * circ; return <div className="aic-health-ring flex flex-col items-center gap-1"><svg width={48} height={48} className="-rotate-90"><circle cx={24} cy={24} r={r} fill="none" stroke="currentColor" strokeWidth={3} className="text-gray-200 dark:text-gray-700"/><circle cx={24} cy={24} r={r} fill="none" stroke={col} strokeWidth={3} strokeDasharray={circ} strokeDashoffset={offset} strokeLinecap="round" className="transition-all"/></svg><span className="text-[10px] font-bold" style={{ color: col }}>{value}%</span><span className="text-[9px] text-muted-foreground">{label}</span></div> }')
    a('')
    a('function SavingsTile({ amount, label }: { amount: number; label: string }) { return <div className="aic-savings-tile p-2 rounded-lg border border-emerald-200 dark:border-emerald-800 bg-emerald-50 dark:bg-emerald-900/20"><div className="flex items-center gap-1 mb-1"><Lightbulb className="w-3 h-3 text-emerald-500"/><span className="text-[10px] font-medium">{label}</span></div><div className="text-xs font-bold text-emerald-600">{"\\u20b9"}{amount.toLocaleString()}</div></div> }')
    a('')
    a('function StarRating({ value }: { value: number }) { return <div className="aic-star-rating flex items-center gap-0.5">{Array.from({ length: 5 }, (_, i) => <Star key={i} className={"w-3 h-3 " + (i < value ? "text-amber-400 fill-amber-400" : "text-gray-300")}/>)}</div> }')
    a('')
    a('function genInsights() {')
    a('  return Array.from({ length: 60 }, (_, i) => ({')
    a('    id: "INS-" + String(i + 1).padStart(4, "0"),')
    a('    module: pick(AI_MODULES, i * 3 + 1),')
    a('    type: pick(SUGGESTION_TYPES, i * 3 + 2),')
    a('    city: pick(CITIES, i * 3 + 3),')
    a('    title: pick(["Reduce warehouse overflow by 25%", "Optimize last mile routes", "Switch to rail for Mumbai-Delhi", "Preorder inventory for Diwali", "Renegotiate supplier contract", "Add cold storage capacity", "Implement cross-docking at BLR", "Deploy EV fleet for Zone A", "Automate quality inspection", "Reduce picking errors", "Consolidate small shipments", "Dynamic pricing for excess stock"], i + 5),')
    a('    confidence: ri(55, 98, i + 7),')
    a('    impact: pick(["high", "medium", "low"], i + 11),')
    a('    savings: ri(10000, 500000, i + 13),')
    a('    status: pick(INSIGHT_STATUS, i + 17),')
    a('    aiModel: pick(["GPT-Logistics", "Transformer-T", "XGBoost-v5", "LSTM-v4", "Ensemble-Hybrid", "Prophet-X"], i + 19),')
    a('    processingTime: ri(50, 5000, i + 23),')
    a('    rating: ri(1, 5, i + 29),')
    a('    feedback: pick(["positive", "negative", "neutral"], i + 31),')
    a('    timestamp: "2026-07-" + String(ri(1, 30, i + 37)).padStart(2, "0") + " " + String(ri(0, 23, i + 41)).padStart(2, "0") + ":" + String(ri(0, 59, i + 43)).padStart(2, "0")')
    a('  }))')
    a('}')
    a('')
    a('function genModels() {')
    a('  return Array.from({ length: 12 }, (_, i) => ({')
    a('    id: "AI-" + String(i + 1).padStart(3, "0"),')
    a('    name: pick(["GPT-Logistics", "Transformer-T", "XGBoost-v5", "LSTM-v4", "Ensemble-Hybrid", "Prophet-X", "DeepAR-Net", "NBEATS-V2", "Temporal-Fusion", "CNN-LSTM", "WaveNet-Small", "LightGBM-Fast"], i + 1),')
    a('    category: pick(AI_MODULES, i + 3),')
    a('    accuracy: ri(70, 98, i + 7),')
    a('    latency: ri(20, 500, i + 11),')
    a('    requests: ri(100, 5000, i + 13),')
    a('    savings: ri(5000, 200000, i + 17),')
    a('    lastTrained: "2026-07-" + String(ri(1, 30, i + 19)).padStart(2, "0"),')
    a('    status: pick(["active", "training", "stale", "retired"], i + 23),')
    a('    version: "v" + ri(1, 5, i + 29) + "." + ri(0, 9, i + 31),')
    a('    uptime: ri(95, 100, i + 37)')
    a('  }))')
    a('}')
    a('')
    a('function genCharts() {')
    a('  const daily = MO.map((m, i) => ({ month: m, suggestions: ri(20, 150, i + 101), implemented: ri(10, 100, i + 151), savings: ri(100000, 2000000, i + 201), accuracy: ri(75, 98, i + 251) }))')
    a('  const modDist = AI_MODULES.map((m, i) => ({ module: m.replace(/_/g, " "), count: ri(5, 40, i + 301), savings: ri(50000, 500000, i + 351) }))')
    a('  const typePie = SUGGESTION_TYPES.map((t, i) => ({ type: t.replace(/_/g, " "), value: ri(3, 25, i + 401) }))')
    a('  return { daily, modDist, typePie }')
    a('}')
    a('')
    a('export default function LogisticsAiCopilotView() {')
    a('  const [tab, setTab] = useState("dashboard")')
    a('  const [search, setSearch] = useState("")')
    a('  const [detail, setDetail] = useState<Record<string, unknown> | null>(null)')
    a('  const [sortField, setSortField] = useState("id")')
    a('  const [sortDir, setSortDir] = useState<"asc" | "desc">("asc")')
    a('  const [activeFilters, setActiveFilters] = useState<Record<string, string[]>>({})')
    a('  const insights = useMemo(() => genInsights(), [])')
    a('  const models = useMemo(() => genModels(), [])')
    a('  const charts = useMemo(() => genCharts(), [])')
    a('  const toggleSort = (f: string) => { if (sortField === f) setSortDir(d => d === "asc" ? "desc" : "asc"); else { setSortField(f); setSortDir("asc") } }')
    a('  const sortIcon = (f: string) => sortField === f ? (sortDir === "asc" ? "\\u2191" : "\\u2193") : ""')
    a('  const filterInsights = useMemo(() => { if (!search) return insights; const lq = search.toLowerCase(); return insights.filter(ins => Object.values(ins).some(v => typeof v === "string" && v.toLowerCase().includes(lq))) }, [insights, search])')
    a('  const sortedInsights = useMemo(() => [...filterInsights].sort((a, b) => { const va = a[sortField as keyof typeof a], vb = b[sortField as keyof typeof b]; if (va == null || vb == null) return 0; return sortDir === "asc" ? String(va).localeCompare(String(vb), undefined, { numeric: true }) : -String(va).localeCompare(String(vb), undefined, { numeric: true }) }), [filterInsights, sortField, sortDir])')
    a('  const totalSavings = insights.reduce((s, i) => s + i.savings, 0)')
    a('  const implemented = insights.filter(i => i.status === "implemented").length')
    a('  const avgConf = Math.round(insights.reduce((s, i) => s + i.confidence, 0) / insights.length)')
    a('  const activeModels = models.filter(m => m.status === "active").length')
    a('  const handleRefresh = () => { setSearch(""); setSortField("id"); setSortDir("asc"); setActiveFilters({}) }')
    a('  const toggleFilter = (group: string, value: string) => { setActiveFilters(prev => { const cur = prev[group] || []; const next = cur.includes(value) ? cur.filter(v => v !== value) : [...cur, value]; if (next.length === 0) { const { [group]: _, ...rest } = prev; return rest } return { ...prev, [group]: next } }) }')
    a('  const clearAllFilters = () => setActiveFilters({})')
    a('  const totalActiveFilters = Object.values(activeFilters).reduce((s, v) => s + v.length, 0)')
    a('  const insightFilterGroups = useMemo(() => { const mc: Record<string, number> = {}; const tc: Record<string, number> = {}; const ic: Record<string, number> = {}; insights.forEach(ins => { mc[ins.module] = (mc[ins.module] || 0) + 1; tc[ins.type] = (tc[ins.type] || 0) + 1; ic[ins.impact] = (ic[ins.impact] || 0) + 1 }); return [{ key: "module", label: "AI Module", options: Object.entries(mc).map(([value, count]) => ({ value, count })).sort((a, b) => b.count - a.count) }, { key: "type", label: "Category", options: Object.entries(tc).map(([value, count]) => ({ value, count })).sort((a, b) => b.count - a.count) }, { key: "impact", label: "Impact", options: Object.entries(ic).map(([value, count]) => ({ value, count })).sort((a, b) => b.count - a.count) }] }, [insights])')
    a('')
    a('  const tab0 = (<div className="space-y-4"><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><KpiTile label="Total Savings" value={"\\u20b9" + (totalSavings / 100000).toFixed(1) + "L"} icon={<Lightbulb className="w-4 h-4 text-amber-500"/>} trend={18.5} color={TH.sec}/><KpiTile label="AI Insights" value={String(insights.length)} icon={<Sparkles className="w-4 h-4 text-violet-500"/>} trend={12.3} color={TH.pri}/><KpiTile label="Implemented" value={String(implemented)} icon={<CheckCircle2 className="w-4 h-4 text-emerald-500"/>} trend={8.7} color={TH.ok}/><KpiTile label="Active Models" value={String(activeModels)} icon={<BrainCircuit className="w-4 h-4 text-blue-500"/>} trend={3.1} color="#3b82f6"/></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><HealthRing value={avgConf} label="AI Confidence"/><HealthRing value={Math.round(implemented / insights.length * 100)} label="Adoption"/><HealthRing value={95} label="Model Uptime"/><HealthRing value={88} label="Data Quality"/></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><Card className="aic-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">AI Suggestions & Savings Trend</CardTitle></CardHeader><CardContent><AreaChart data={charts.daily} height={200}><CartesianGrid strokeDasharray="3 3" opacity={0.3}/><XAxis dataKey="month" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip contentStyle={{ fontSize: 10 }}/><Area type="monotone" dataKey="suggestions" stroke={TH.pri} fill={TH.pri} fillOpacity={0.2}/><Area type="monotone" dataKey="implemented" stroke={TH.ok} fill={TH.ok} fillOpacity={0.15}/><Line type="monotone" dataKey="accuracy" stroke={TH.sec} strokeWidth={2} dot={{ r: 3 }}/></AreaChart></CardContent></Card><Card className="aic-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">AI Module Distribution</CardTitle></CardHeader><CardContent><BarChart data={charts.modDist} height={200}><CartesianGrid strokeDasharray="3 3" opacity={0.3}/><XAxis dataKey="module" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip contentStyle={{ fontSize: 10 }}/><Bar dataKey="count" fill={TH.pri} radius={[2, 2, 0, 0]}/><Bar dataKey="savings" fill={TH.sec} radius={[2, 2, 0, 0]}/></BarChart></CardContent></Card><Card className="aic-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Insight Category</CardTitle></CardHeader><CardContent><PieChart width={300} height={200}><Pie data={charts.typePie} cx="50%" cy="50%" outerRadius={70} dataKey="value" label={({ name, percent }) => name + " " + (percent * 100).toFixed(0) + "%"} labelLine={false}>{SUGGESTION_TYPES.map((_, i) => <Cell key={i} fill={PC[i % PC.length]}/>)}</Pie><Tooltip contentStyle={{ fontSize: 10 }}/></PieChart></CardContent></Card><Card className="aic-chart-card glass-subtle"><CardHeader className="pb-1"><CardTitle className="text-xs">Model Performance</CardTitle></CardHeader><CardContent><BarChart data={models.map(m => ({ name: m.name, accuracy: m.accuracy, latency: m.latency }))} height={200}><CartesianGrid strokeDasharray="3 3" opacity={0.3}/><XAxis dataKey="name" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip contentStyle={{ fontSize: 10 }}/><Bar dataKey="accuracy" fill={TH.ok} radius={[2, 2, 0, 0]}/><Bar dataKey="latency" fill={TH.warn} radius={[2, 2, 0, 0]}/></BarChart></CardContent></Card></div></div>)')
    a('')
    a('  const tab1 = (<div className="space-y-3"><ModuleBreadcrumb items={[{ label: "AI" }, { label: "Copilot" }, { label: "Insights" }]}/><SearchFilterToolbar searchQuery={search} onSearchChange={setSearch} onClearSearch={() => setSearch("")} activeFilters={activeFilters} filterGroups={insightFilterGroups} onToggleFilter={toggleFilter} onClearAllFilters={clearAllFilters} totalItems={insights.length} filteredCount={sortedInsights.length} onRefresh={handleRefresh} placeholder="Search insights by title, module, type..." /><div className="rounded-lg border overflow-auto max-h-[calc(100vh-340px)]"><table className="aic-table w-full text-xs"><thead className="bg-violet-50 dark:bg-violet-900/20 sticky top-0"><tr><th className="p-2 text-left cursor-pointer select-none" onClick={() => toggleSort("id")}>ID {sortIcon("id")}</th><th className="p-2 text-left">Title</th><th className="p-2 text-left">Module</th><th className="p-2 text-left">Category</th><th className="p-2 text-left">Impact</th><th className="p-2 text-left">Confidence</th><th className="p-2 text-right">Savings</th><th className="p-2 text-left">Status</th><th className="p-2 text-left">Model</th></tr></thead><tbody>{sortedInsights.map(ins => <tr key={ins.id} className="aic-table-row border-t hover:bg-violet-50/50 dark:hover:bg-violet-900/10 cursor-pointer" onClick={() => setDetail(ins as unknown as Record<string, unknown>)}><td className="p-2 font-mono">{ins.id}</td><td className="p-2 font-medium max-w-[200px] truncate">{ins.title}</td><td className="p-2"><AiModuleBadge module={ins.module}/></td><td className="p-2"><SuggTypeBadge type={ins.type}/></td><td className="p-2"><span className={"inline-flex px-1.5 py-0.5 rounded text-[10px] font-medium " + (ins.impact === "high" ? "bg-red-100 text-red-700" : ins.impact === "medium" ? "bg-amber-100 text-amber-700" : "bg-emerald-100 text-emerald-700")}>{ins.impact}</span></td><td className="p-2"><ConfBar value={ins.confidence}/></td><td className="p-2 text-right font-medium text-emerald-600">{"\\u20b9"}{ins.savings.toLocaleString()}</td><td className="p-2"><InsightStatusBadge status={ins.status}/></td><td className="p-2 text-[10px]">{ins.aiModel}</td></tr>)}</tbody></table></div><div className="flex items-center justify-between text-[10px] text-muted-foreground"><span>Showing {sortedInsights.length} of {insights.length} insights</span>{totalActiveFilters > 0 && <span>{totalActiveFilters} filters</span>}</div></div>)')
    a('')
    a('  const tab2 = (<div className="space-y-4"><ModuleBreadcrumb items={[{ label: "AI" }, { label: "Copilot" }, { label: "Models" }]}/><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">{models.map(m => <Card key={m.id} className={"aic-model-card glass-subtle hover:shadow-lg transition-shadow " + (m.status === "active" ? "border-emerald-300 dark:border-emerald-700" : m.status === "training" ? "border-blue-300 dark:border-blue-700" : m.status === "stale" ? "border-amber-300 dark:border-amber-700" : "")}><CardContent className="p-3 space-y-2"><div className="flex items-center justify-between"><span className="font-semibold text-xs">{m.name}</span><span className={"inline-flex px-1.5 py-0.5 rounded text-[10px] font-medium " + (m.status === "active" ? "bg-emerald-100 text-emerald-700" : m.status === "training" ? "bg-blue-100 text-blue-700 animate-pulse" : m.status === "stale" ? "bg-amber-100 text-amber-700" : "bg-gray-100 text-gray-500")}>{m.status}</span></div><div className="grid grid-cols-2 gap-1.5"><ValueTile label="Accuracy" value={m.accuracy + "%"}/><ValueTile label="Latency" value={m.latency + "ms"}/></div><div className="flex items-center justify-between text-[10px]"><span className="text-muted-foreground">Requests</span><span className="font-medium">{m.requests.toLocaleString()}</span></div><div className="flex items-center justify-between text-[10px]"><span className="text-muted-foreground">Savings</span><span className="font-bold text-emerald-600">{"\\u20b9"}{m.savings.toLocaleString()}</span></div><div className="flex items-center justify-between text-[10px]"><span className="text-muted-foreground">Uptime</span><ConfBar value={m.uptime}/></div><div className="flex items-center justify-between"><AiModuleBadge module={m.category}/><span className="text-[10px] text-muted-foreground">{m.version}</span></div></CardContent></Card>)}</div></div>)')
    a('')
    a('  const tabs = [{ key: "dashboard", label: "Dashboard", icon: <BarChart3 className="w-3.5 h-3.5" />, content: tab0 }, { key: "insights", label: "AI Insights", icon: <Sparkles className="w-3.5 h-3.5" />, content: tab1 }, { key: "models", label: "AI Models", icon: <BrainCircuit className="w-3.5 h-3.5" />, content: tab2 }]')
    a('')
    a('  return (<div className="space-y-4 p-4"><PageHeader title="Logistics AI Copilot" description="AI-powered logistics intelligence platform with predictive insights, cost optimization, risk analysis, and automated decision support"/><div className="flex items-center gap-3 flex-wrap"><div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-violet-100 dark:bg-violet-900/30"><BrainCircuit className="w-3 h-3 text-violet-600"/><span className="text-[10px] font-semibold text-violet-700 dark:text-violet-300">{activeModels} AI Models Active</span></div><div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-100 dark:bg-emerald-900/30"><Lightbulb className="w-3 h-3 text-emerald-600"/><span className="text-[10px] font-semibold text-emerald-700 dark:text-emerald-300">{insights.length} Insights Generated</span></div><div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-amber-100 dark:bg-amber-900/30"><Sparkles className="w-3 h-3 text-amber-600"/><span className="text-[10px] font-semibold text-amber-700 dark:text-amber-300">{avgConf}% Confidence</span></div><div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-blue-100 dark:bg-blue-900/30"><Bot className="w-3 h-3 text-blue-600"/><span className="text-[10px] font-semibold text-blue-700 dark:text-blue-300">{"\\u20b9"}{(totalSavings / 100000).toFixed(1)}L Savings</span></div></div><Tabs value={tab} onValueChange={setTab}><TabsList className="bg-gradient-to-r from-violet-500/10 to-amber-500/10 p-0.5 h-9">{tabs.map(t => <TabsTrigger key={t.key} value={t.key} className="text-xs gap-1.5 data-[state=active]:bg-violet-600 data-[state=active]:text-white">{t.icon}{t.label}</TabsTrigger>)}</TabsList>{tabs.map(t => tab === t.key && <div key={t.key} className="mt-3">{t.content}</div>)}</Tabs><Sheet open={!!detail} onOpenChange={() => setDetail(null)}><SheetContent className="w-[420px] overflow-y-auto"><SheetHeader><SheetTitle className="text-sm">Insight Detail</SheetTitle></SheetHeader>{detail && <div className="mt-4 space-y-3"><div className="aic-detail-header rounded-lg p-4 bg-gradient-to-br from-violet-500 to-amber-600 text-white"><div className="text-lg font-bold">{String(detail.id)}</div><div className="text-xs opacity-80 mt-1">{String(detail.title || "Insight")}</div></div>{Object.entries(detail).filter(([k]) => k !== "id").map(([k, v]) => <div key={k} className="flex items-center justify-between py-1.5 border-b"><span className="text-[10px] text-muted-foreground capitalize">{k.replace(/_/g, " ")}</span><span className="text-xs font-medium">{typeof v === "number" ? v.toLocaleString() : String(v)}</span></div>)}</div>}</SheetContent></Sheet></div>)')
    a('}')
    
    with open(os.path.join(BASE, "logistics-ai-copilot-view.tsx"), "w") as f:
        f.write("\n".join(L))
    print(f"Module B: logistics-ai-copilot-view.tsx ({len(L)} lines)")

gen_dock_scheduler()
gen_ai_copilot()
print("Done generating R264 modules.")
