#!/usr/bin/env python3
"""Generate R260 modules: warehouse-quality-command + wms-configuration-studio"""
import os

BASE = '/home/z/my-project/src/components/modules'

# ═══════════════════════════════════════════════════════════════════════
# MODULE 1: Warehouse Quality Command Center
# ═══════════════════════════════════════════════════════════════════════
m = []
m.append('"use client"')
m.append('')
m.append('import { useState, useMemo } from "react"')
m.append('import {')
m.append('  AreaChart, Area, BarChart, Bar, PieChart, Pie, Cell,')
m.append('  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip,')
m.append('} from "recharts"')
m.append('import {')
m.append('  Search, Eye, ArrowUpDown, TrendingUp, TrendingDown, Clock, IndianRupee, Zap,')
m.append('  AlertTriangle, Users, BarChart3, MapPin, Package, Box, CheckCircle, XCircle, Activity, Timer, ShieldCheck, Star, Radio, Gauge, Microscope, ClipboardList, ShieldAlert, ArrowRight, ChevronRight, RefreshCw, Download, Filter, Target, Award, BadgeCheck')
m.append('} from "lucide-react"')
m.append('import { PageHeader } from "@/components/shared/page-header"')
m.append('import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"')
m.append('import { Input } from "@/components/ui/input"')
m.append('import { Button } from "@/components/ui/button"')
m.append('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
m.append('import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"')
m.append('')
m.append('const INSP_TYPES = ["Incoming","In-process","Final","Line","Source","Audit","Pre-shipment","Random"] as const')
m.append('const INSP_EMOJI: Record<string,string> = {Incoming:"\U0001f4e5","In-process":"\u2699\ufe0f","Final":"\u2705","Line":"\U0001f4cf",Source:"\U0001f3ed",Audit:"\U0001f50d","Pre-shipment":"\U0001f69a",Random:"\U0001f3b2"}')
m.append('const DEFECT_TYPES = ["Dimensional","Surface Finish","Material Defect","Assembly Error","Missing Component","Label Error","Packaging Damage","Weight Mismatch","Color Mismatch","Functional Failure"] as const')
m.append('const DEFECT_SEVS = ["Critical","Major","Minor","Cosmetic"] as const')
m.append('const GRADES = ["A - Excellent","B - Good","C - Acceptable","D - Marginal","E - Reject"] as const')
m.append('const QC_STS = ["Passed","Failed","Conditional","In Progress","Pending Review","Escalated"] as const')
m.append('const CITIES = ["Mumbai","Delhi","Bangalore","Chennai","Hyderabad","Kolkata","Pune","Ahmedabad"] as const')
m.append('const INSPECTORS = ["Dr. Anand K.","Sunita P.","Ravi M.","Meera D.","Arun S.","Prachi T."] as const')
m.append('const PRODUCTS = ["Electronics","FMCG","Auto Parts","Pharma","Apparel","Home Decor"] as const')
m.append('const MO = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"] as const')
m.append('const TH = {emerald:"#059669",blue:"#3b82f6",amber:"#d97706",red:"#dc2626",violet:"#7c3aed",cyan:"#0891b2",rose:"#e11d48",orange:"#ea580c"}')
m.append('const PC = [TH.emerald,TH.blue,TH.amber,TH.red,TH.violet,TH.cyan,TH.rose,TH.orange]')
m.append('')
m.append('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297 + 233280) * 10000; return x - Math.floor(x) }')
m.append('function ri(a: number, b: number, s: number): number { return Math.floor(seededRandom(s) * (b - a + 1)) + a }')
m.append('function pick<T>(arr: readonly T[], s: number): T { return arr[Math.abs(s) % arr.length] }')
m.append('function filterData<T>(d: T[], q: string): T[] { if (!q) return d; const l = q.toLowerCase(); return d.filter(i => Object.values(i as unknown as Record<string, string | number>).some(v => String(v).toLowerCase().includes(l))) }')
m.append('function sortedData<T>(d: T[], f: string, dir: "asc" | "desc"): T[] { return [...d].sort((a, b) => { const av = (a as unknown as Record<string, string | number>)[f], bv = (b as unknown as Record<string, string | number>)[f]; if (typeof av === "number" && typeof bv === "number") return dir === "asc" ? av - bv : bv - av; return dir === "asc" ? String(av ?? "").localeCompare(String(bv ?? "")) : String(bv ?? "").localeCompare(String(av ?? "")) }) }')
m.append('')
m.append('/* 16 Visual Components */')
m.append('function InspTypeBadge({ t }: { t: string }) {')
m.append('  const cl: Record<string,string> = {Incoming:"bg-blue-100 text-blue-700","In-process":"bg-amber-100 text-amber-700",Final:"bg-emerald-100 text-emerald-700",Line:"bg-violet-100 text-violet-700",Source:"bg-cyan-100 text-cyan-700",Audit:"bg-rose-100 text-rose-700","Pre-shipment":"bg-indigo-100 text-indigo-700",Random:"bg-orange-100 text-orange-700"}')
m.append('  return <span className={"wqc-it-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium " + (cl[t]||"bg-gray-100")}>{INSP_EMOJI[t]} {t}</span>')
m.append('}')
m.append('function DefectBadge({ t }: { t: string }) {')
m.append('  return <span className="wqc-def-badge inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300">\u274c {t}</span>')
m.append('}')
m.append('function DefectSevBadge({ s }: { s: string }) {')
m.append('  const cl: Record<string,string> = {Critical:"bg-red-100 text-red-700 shadow-[0_0_8px_oklch(0.55_0.22_25/0.3)]",Major:"bg-orange-100 text-orange-700",Minor:"bg-amber-100 text-amber-700",Cosmetic:"bg-blue-100 text-blue-700"}')
m.append('  const emoji: Record<string,string> = {Critical:"\U0001f534",Major:"\U0001f7e0",Minor:"\U0001f7e1",Cosmetic:"\U0001f535"}')
m.append('  return <span className={"wqc-sev-badge inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold " + (cl[s]||"bg-gray-100")}>{emoji[s]} {s}</span>')
m.append('}')
m.append('function GradeBadge({ g }: { g: string }) {')
m.append('  const grade = g.split(" ")[0]')
m.append('  const cl: Record<string,string> = {A:"bg-emerald-100 text-emerald-700",B:"bg-blue-100 text-blue-700",C:"bg-amber-100 text-amber-700",D:"bg-orange-100 text-orange-700",E:"bg-red-100 text-red-700"}')
m.append('  return <span className={"wqc-grade inline-flex items-center justify-center w-7 h-7 rounded-full text-xs font-black " + (cl[grade]||"bg-gray-100")}>{grade}</span>')
m.append('}')
m.append('function QcStatusBadge({ s }: { s: string }) {')
m.append('  const cl: Record<string,string> = {Passed:"bg-emerald-100 text-emerald-700",Failed:"bg-red-100 text-red-700",Conditional:"bg-amber-100 text-amber-700","In Progress":"bg-blue-100 text-blue-700 animate-pulse","Pending Review":"bg-violet-100 text-violet-700",Escalated:"bg-red-100 text-red-700 shadow-[0_0_8px_oklch(0.55_0.22_25/0.3)] animate-pulse"}')
m.append('  return <span className={"wqc-status inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cl[s]||"bg-gray-100")}>\u25cf {s}</span>')
m.append('}')
m.append('function CityBadge({ city }: { city: string }) { return <span className="wqc-city inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-medium bg-cyan-50 text-cyan-700 dark:bg-cyan-900/30 dark:text-cyan-300">\U0001f4cd {city}</span> }')
m.append('function InspectorBadge({ name, score }: { name: string; score: number }) {')
m.append('  const c = score >= 95 ? "text-emerald-600" : score >= 85 ? "text-blue-600" : "text-amber-600"')
m.append('  return <span className={"wqc-insp inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-[10px] font-semibold " + c}><Microscope className="h-3 w-3"/>{name} <span className="font-black tabular-nums">{score}%</span></span>')
m.append('}')
m.append('function ProductBadge({ p }: { p: string }) { return <span className="wqc-prod inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium bg-violet-50 text-violet-700 dark:bg-violet-900/30 dark:text-violet-300">\U0001f4e6 {p}</span> }')
m.append('function AccuracyGauge({ value }: { value: number }) {')
m.append('  const c = value >= 99 ? "text-emerald-600" : value >= 97 ? "text-blue-600" : value >= 95 ? "text-amber-600" : "text-red-600"')
m.append('  return <div className="wqc-acc flex items-center gap-1"><span className={"text-sm font-black tabular-nums " + c}>{value}%</span><div className="flex-1 h-1.5 rounded-full bg-gray-200 dark:bg-gray-700"><div className={"h-full rounded-full transition-all " + c.replace("text-","bg-")} style={{width:value+"%"}}/></div></div>')
m.append('}')
m.append('function DefectRateBar({ value }: { value: number }) {')
m.append('  const c = value <= 0.5 ? "bg-emerald-500" : value <= 1.5 ? "bg-blue-500" : value <= 3 ? "bg-amber-500" : "bg-red-500"')
m.append('  return <div className="wqc-dr flex items-center gap-2"><div className="flex-1 h-2 rounded-full bg-gray-200 dark:bg-gray-700"><div className={"h-full rounded-full transition-all " + c} style={{width: Math.min(value*10, 100)+"%"}}/></div><span className="text-[10px] font-bold tabular-nums">{value}%</span></div>')
m.append('}')
m.append('function SpcIndicator({ cpk }: { cpk: number }) {')
m.append('  const c = cpk >= 1.67 ? "text-emerald-600" : cpk >= 1.33 ? "text-blue-600" : cpk >= 1 ? "text-amber-600" : "text-red-600"')
m.append('  return <span className={"wqc-spc inline-flex items-center gap-1 text-xs font-bold tabular-nums " + c}>Cpk: {cpk}</span>')
m.append('}')
m.append('function ValueTile({ value, label, trend }: { value: string; label: string; trend: number }) {')
m.append('  return <div className="wqc-val text-right"><div className="text-sm font-bold tabular-nums">{value}</div><div className="text-[10px] text-muted-foreground">{label}</div>{trend !== 0 && <div className={"text-[10px] font-semibold flex items-center justify-end gap-0.5 " + (trend > 0 ? "text-emerald-600" : "text-red-600")}>{trend > 0 ? <TrendingUp className="h-3 w-3"/> : <TrendingDown className="h-3 w-3"/>}{Math.abs(trend)}%</div>}</div>')
m.append('}')
m.append('function StarRating({ value }: { value: number }) { return <span className="wqc-stars inline-flex gap-0.5">{"\u2605".repeat(value)}{"\u2606".repeat(5-value)}</span> }')
m.append('function CostTile({ value }: { value: number }) { return <span className="wqc-cost text-sm font-bold tabular-nums text-red-600 dark:text-red-400">\u20b9{(value * 1000).toLocaleString("en-IN")}</span> }')
m.append('function PassRateRing({ pct }: { pct: number }) {')
m.append('  const c = pct >= 98 ? "text-emerald-500" : pct >= 95 ? "text-blue-500" : pct >= 90 ? "text-amber-500" : "text-red-500"')
m.append('  return <div className="wqc-pass flex flex-col items-center"><div className={"text-2xl font-black tabular-nums " + c}>{pct}%</div><div className="text-[9px] text-muted-foreground">Pass</div></div>')
m.append('}')

# Data
m.append('')
m.append('function genInspections() {')
m.append('  return Array.from({length: 80}, (_, i) => ({')
m.append('    id: "QC-" + String(i+9001).padStart(4,"0"),')
m.append('    type: pick(INSP_TYPES, i+1),')
m.append('    status: pick(QC_STS, i+2),')
m.append('    grade: pick(GRADES, i+3),')
m.append('    city: pick(CITIES, i+4),')
m.append('    inspector: pick(INSPECTORS, i+5),')
m.append('    inspScore: ri(65, 100, i+6),')
m.append('    product: pick(PRODUCTS, i+7),')
m.append('    totalItems: ri(50, 500, i+8),')
m.append('    passed: ri(40, 490, i+9),')
m.append('    failed: ri(0, 30, i+10),')
m.append('    defectRate: ri(0, 8, i+11) / 10,')
m.append('    cpk: (ri(80, 200, i+12) / 100).toFixed(2),')
m.append('    duration: ri(5, 120, i+13) + " min",')
m.append('    costOfQuality: ri(1, 25, i+14),')
m.append('    sampleSize: ri(5, 50, i+15),')
m.append('  }))')
m.append('}')
m.append('')
m.append('function genDefects() {')
m.append('  return Array.from({length: 60}, (_, i) => ({')
m.append('    id: "DEF-" + String(i+10001).padStart(4,"0"),')
m.append('    type: pick(DEFECT_TYPES, i+1),')
m.append('    severity: pick(DEFECT_SEVS, i+2),')
m.append('    city: pick(CITIES, i+3),')
m.append('    product: pick(PRODUCTS, i+4),')
m.append('    inspector: pick(INSPECTORS, i+5),')
m.append('    resolved: i % 3 !== 0,')
m.append('    rootCause: pick(["Process Variation","Material Issue","Operator Error","Machine Calibration","Environmental","Design Flaw"], i+6),')
m.append('    correctiveAction: pick(["Adjust Process","Replace Material","Retrain Operator","Recalibrate","Change Spec","Add Inspection"], i+7),')
m.append('    costImpact: ri(0, 50, i+8),')
m.append('    recurrence: ri(0, 5, i+9),')
m.append('  }))')
m.append('}')
m.append('')
m.append('function genCharts() {')
m.append('  const monthly = MO.map((m, i) => ({ month: m, inspected: ri(500,2000,i), passed: ri(450,1950,i+12), defectRate: ri(0.5,4,i+24)/10, cost: ri(10,80,i+36) }))')
m.append('  const typePie = INSP_TYPES.map((t, i) => ({ name: t.split(" ")[0], value: ri(20,80,i) }))')
m.append('  const defectBar = DEFECT_TYPES.map((d, i) => ({ name: d.split(" ")[0], critical: ri(2,20,i), major: ri(5,30,i+10), minor: ri(10,50,i+20), cosmetic: ri(5,25,i+30) }))')
m.append('  const cityLine = CITIES.map((c, i) => ({ city: c, accuracy: ri(92,100,i), defectRate: ri(0.3,3,i+8)/10 }))')
m.append('  return { monthly, typePie, defectBar, cityLine }')
m.append('}')

# Main
m.append('')
m.append('export default function WarehouseQualityCommandView() {')
m.append('  const [tab, setTab] = useState("overview")')
m.append('  const [search, setSearch] = useState("")')
m.append('  const [sortField, setSortField] = useState("id")')
m.append('  const [sortDir, setSortDir] = useState<"asc"|"desc">("asc")')
m.append('  const [detail, setDetail] = useState<Record<string, unknown>|null>(null)')
m.append('')
m.append('  const inspections = useMemo(() => genInspections(), [])')
m.append('  const defects = useMemo(() => genDefects(), [])')
m.append('  const charts = useMemo(() => genCharts(), [])')
m.append('')
m.append('  const filteredInsp = useMemo(() => sortedData(filterData(inspections, search), sortField, sortDir), [inspections, search, sortField, sortDir])')
m.append('  const filteredDef = useMemo(() => sortedData(filterData(defects, search), sortField, sortDir), [defects, search, sortField, sortDir])')
m.append('')
m.append('  const toggleSort = (f: string) => { if (sortField === f) setSortDir(d => d === "asc" ? "desc" : "asc"); else { setSortField(f); setSortDir("asc") } }')

# Tab 0
m.append('')
m.append('  const tab0 = (')
m.append('    <div className="space-y-4">')
m.append('      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">')
m.append("        {[['Total Inspections','1,247','+15%',<ClipboardList key='cl'/>],['Pass Rate','97.2%','+0.8%',<ShieldCheck key='sc'/>],['Defect Rate','0.8%','-0.3%',<AlertTriangle key='at'/>],['Avg Cpk','1.45','+0.12',<Target key='t'/>],['COQ Savings','\\u20b94.2M','+22%',<IndianRupee key='r'/>],['Open Escalations','3','-2',<ShieldAlert key='sa'/>],['Inspectors','6','0',<Users key='u'/>],['Avg Duration','35 min','-8%',<Timer key='tm'/>]].map(([label,val,tr,icon], i) => (")
m.append('          <Card key={i} className="glass-subtle wqc-kpi"><CardContent className="p-3"><div className="flex items-center gap-2.5">{icon}<div><div className="text-[10px] text-muted-foreground">{String(label)}</div><div className="text-lg font-black tabular-nums">{String(val)}</div><div className="text-[10px] font-semibold text-emerald-600">{String(tr)}</div></div></div></CardContent></Card>')
m.append('        ))}')
m.append('      </div>')
m.append('      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">')
m.append('        <Card className="glass-subtle wqc-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Monthly Inspection Volume</CardTitle></CardHeader><CardContent className="p-3"><AreaChart data={charts.monthly}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Area type="monotone" dataKey="inspected" stroke={TH.blue} fill={TH.blue} fillOpacity={0.3}/><Area type="monotone" dataKey="passed" stroke={TH.emerald} fill={TH.emerald} fillOpacity={0.3}/></AreaChart></CardContent></Card>')
m.append('        <Card className="glass-subtle wqc-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Inspection Type Mix</CardTitle></CardHeader><CardContent className="p-3"><PieChart><Pie data={charts.typePie} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({name}: {name:string}) => <text x={0} y={0} fill="currentColor" fontSize={9} textAnchor="middle">{name}</text>}>{charts.typePie.map((_,i) => <Cell key={i} fill={PC[i%PC.length]}/>)}</Pie><Tooltip/></PieChart></CardContent></Card>')
m.append('        <Card className="glass-subtle wqc-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Defect Severity Distribution</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.defectBar}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="name" tick={{fontSize:9}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="critical" fill={TH.red} stackId="a"/><Bar dataKey="major" fill={TH.orange} stackId="a"/><Bar dataKey="minor" fill={TH.amber} stackId="a"/><Bar dataKey="cosmetic" fill={TH.blue} stackId="a"/></BarChart></CardContent></Card>')
m.append('        <Card className="glass-subtle wqc-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">City Accuracy & Defect Rate</CardTitle></CardHeader><CardContent className="p-3"><LineChart data={charts.cityLine}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="city" tick={{fontSize:9}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Line type="monotone" dataKey="accuracy" stroke={TH.emerald} strokeWidth={2}/><Line type="monotone" dataKey="defectRate" stroke={TH.red} strokeWidth={2}/></LineChart></CardContent></Card>')
m.append('      </div>')
m.append('    </div>')
m.append('  )')

# Tab 1: Inspection Log
m.append('')
m.append('  const tab1 = (')
m.append('    <div className="space-y-3">')
m.append('      <div className="flex items-center gap-2"><div className="relative flex-1"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground"/><Input className="h-8 pl-8 text-xs" placeholder="Search inspections..." value={search} onChange={e => setSearch(e.target.value)}/></div></div>')
m.append('      <div className="rounded-lg border overflow-auto max-h-[calc(100vh-280px)]">')
m.append('        <table className="w-full text-xs"><thead className="bg-emerald-50 dark:bg-emerald-900/20 sticky top-0 z-10"><tr>')
m.append('          <th className="p-2 text-left font-semibold cursor-pointer select-none" onClick={() => toggleSort("id")}>ID <ArrowUpDown className="inline h-3 w-3 ml-0.5 opacity-50"/></th>')
m.append('          <th className="p-2 text-left font-semibold">Type</th>')
m.append('          <th className="p-2 text-left font-semibold">Status</th>')
m.append('          <th className="p-2 text-left font-semibold">Grade</th>')
m.append('          <th className="p-2 text-left font-semibold">City</th>')
m.append('          <th className="p-2 text-left font-semibold">Inspector</th>')
m.append('          <th className="p-2 text-left font-semibold">Product</th>')
m.append('          <th className="p-2 text-left font-semibold">Pass Rate</th>')
m.append('          <th className="p-2 text-left font-semibold">Defect %</th>')
m.append('          <th className="p-2 text-left font-semibold">Cpk</th>')
m.append('          <th className="p-2 text-left font-semibold">COQ</th>')
m.append('          <th className="p-2"></th>')
m.append('        </tr></thead><tbody className="divide-y">')
m.append('          {filteredInsp.map(row => (')
m.append('            <tr key={row.id} className="hover:bg-emerald-50/50 dark:hover:bg-emerald-900/10 transition-colors">')
m.append('              <td className="p-2 font-mono font-medium">{row.id}</td>')
m.append('              <td className="p-2"><InspTypeBadge t={row.type}/></td>')
m.append('              <td className="p-2"><QcStatusBadge s={row.status}/></td>')
m.append('              <td className="p-2"><GradeBadge g={row.grade}/></td>')
m.append('              <td className="p-2"><CityBadge city={row.city}/></td>')
m.append('              <td className="p-2"><InspectorBadge name={row.inspector} score={row.inspScore}/></td>')
m.append('              <td className="p-2"><ProductBadge p={row.product}/></td>')
m.append('              <td className="p-2"><AccuracyGauge value={Math.round((row.passed/Math.max(row.totalItems,1))*100)}/></td>')
m.append('              <td className="p-2"><DefectRateBar value={row.defectRate}/></td>')
m.append('              <td className="p-2"><SpcIndicator cpk={row.cpk}/></td>')
m.append('              <td className="p-2"><CostTile value={row.costOfQuality}/></td>')
m.append('              <td className="p-2"><Button variant="ghost" size="sm" className="h-6 w-6 p-0" onClick={() => setDetail(row)}><Eye className="h-3 w-3"/></Button></td>')
m.append('            </tr>')
m.append('          ))}')
m.append('        </tbody></table>')
m.append('      </div>')
m.append('      <div className="text-[10px] text-muted-foreground text-right">{filteredInsp.length} inspections</div>')
m.append('    </div>')
m.append('  )')

# Tab 2: Defect Tracker
m.append('')
m.append('  const tab2 = (')
m.append('    <div className="space-y-3">')
m.append('      <div className="flex items-center gap-2"><div className="relative flex-1"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground"/><Input className="h-8 pl-8 text-xs" placeholder="Search defects..." value={search} onChange={e => setSearch(e.target.value)}/></div></div>')
m.append('      <div className="rounded-lg border overflow-auto max-h-[calc(100vh-280px)]">')
m.append('        <table className="w-full text-xs"><thead className="bg-red-50 dark:bg-red-900/20 sticky top-0 z-10"><tr>')
m.append('          <th className="p-2 text-left font-semibold">ID</th>')
m.append('          <th className="p-2 text-left font-semibold">Type</th>')
m.append('          <th className="p-2 text-left font-semibold">Severity</th>')
m.append('          <th className="p-2 text-left font-semibold">City</th>')
m.append('          <th className="p-2 text-left font-semibold">Product</th>')
m.append('          <th className="p-2 text-left font-semibold">Status</th>')
m.append('          <th className="p-2 text-left font-semibold">Root Cause</th>')
m.append('          <th className="p-2 text-left font-semibold">Action</th>')
m.append('          <th className="p-2 text-left font-semibold">Recurrence</th>')
m.append('          <th className="p-2 text-left font-semibold">Cost</th>')
m.append('        </tr></thead><tbody className="divide-y">')
m.append('          {filteredDef.map(row => (')
m.append('            <tr key={row.id} className="hover:bg-red-50/50 dark:hover:bg-red-900/10 transition-colors">')
m.append('              <td className="p-2 font-mono font-medium">{row.id}</td>')
m.append('              <td className="p-2"><DefectBadge t={row.type}/></td>')
m.append('              <td className="p-2"><DefectSevBadge s={row.severity}/></td>')
m.append('              <td className="p-2"><CityBadge city={row.city}/></td>')
m.append('              <td className="p-2"><ProductBadge p={row.product}/></td>')
m.append('              <td className="p-2"><span className={"inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (row.resolved ? "bg-emerald-100 text-emerald-700" : "bg-red-100 text-red-700 animate-pulse")}>{row.resolved ? "\\u2705 Resolved" : "\\U0001f534 Open"}</span></td>')
m.append('              <td className="p-2 text-muted-foreground">{row.rootCause}</td>')
m.append('              <td className="p-2 text-muted-foreground">{row.correctiveAction}</td>')
m.append('              <td className="p-2 numeric-cell tabular-nums">{row.recurrence}</td>')
m.append('              <td className="p-2"><CostTile value={row.costImpact}/></td>')
m.append('            </tr>')
m.append('          ))}')
m.append('        </tbody></table>')
m.append('      </div>')
m.append('      <div className="text-[10px] text-muted-foreground text-right">{filteredDef.length} defects</div>')
m.append('    </div>')
m.append('  )')

# Tab 3: Inspector Scorecards
m.append('')
m.append('  const tab3 = (')
m.append('    <div className="space-y-3">')
m.append('      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">')
m.append('        {INSPECTORS.map((name, i) => {')
m.append('          const insp = inspections.filter(x => x.inspector === name)')
m.append('          const avgScore = Math.round(insp.reduce((s,x) => s+x.inspScore, 0) / (insp.length||1))')
m.append('          const totalInsp = insp.length')
m.append('          const passCount = insp.filter(x => x.status==="Passed").length')
m.append('          const avgDefRate = (insp.reduce((s,x) => s+x.defectRate, 0) / (insp.length||1)).toFixed(1)')
m.append('          return (')
m.append('            <Card key={name} className="glass-subtle wqc-inspector-card hover:border-emerald-300 dark:hover:border-emerald-700 transition-all">')
m.append('              <CardContent className="p-4">')
m.append('                <div className="flex items-center justify-between mb-3"><div className="flex items-center gap-2"><Microscope className="h-5 w-5 text-emerald-600"/><div><div className="text-sm font-bold">{name}</div><div className="text-[10px] text-muted-foreground">Inspector</div></div></div><PassRateRing pct={Math.round((passCount/Math.max(totalInsp,1))*100)}/></div>')
m.append('                <div className="grid grid-cols-2 gap-2">')
m.append('                  <div className="rounded-lg bg-emerald-50 dark:bg-emerald-900/20 p-2 text-center"><div className="text-lg font-black text-emerald-600">{avgScore}%</div><div className="text-[9px] text-muted-foreground">Avg Score</div></div>')
m.append('                  <div className="rounded-lg bg-blue-50 dark:bg-blue-900/20 p-2 text-center"><div className="text-lg font-black text-blue-600">{totalInsp}</div><div className="text-[9px] text-muted-foreground">Inspections</div></div>')
m.append('                  <div className="rounded-lg bg-amber-50 dark:bg-amber-900/20 p-2 text-center"><div className="text-lg font-black text-amber-600">{avgDefRate}%</div><div className="text-[9px] text-muted-foreground">Avg Defect</div></div>')
m.append('                  <div className="rounded-lg bg-violet-50 dark:bg-violet-900/20 p-2 text-center"><StarRating value={Math.round(avgScore/20)}/></div>')
m.append('                </div>')
m.append('              </CardContent>')
m.append('            </Card>')
m.append('          )')
m.append('        })}')
m.append('      </div>')
m.append('    </div>')
m.append('  )')

# Return
m.append('')
m.append('  const tabs = [')
m.append('    {key:"overview",label:"Dashboard",icon:<ShieldCheck className="h-3.5 w-3.5"/>,content:tab0},')
m.append('    {key:"inspections",label:"Inspections",icon:<ClipboardList className="h-3.5 w-3.5"/>,content:tab1},')
m.append('    {key:"defects",label:"Defects",icon:<AlertTriangle className="h-3.5 w-3.5"/>,content:tab2},')
m.append('    {key:"inspectors",label:"Inspectors",icon:<Users className="h-3.5 w-3.5"/>,content:tab3},')
m.append('  ]')
m.append('')
m.append('  return (')
m.append('    <div className="space-y-4 p-4">')
m.append('      <PageHeader title="Warehouse Quality Command Center" description="Quality inspection management, defect tracking, SPC monitoring, and inspector performance analytics"/>')
m.append('      <div className="flex items-center gap-3 flex-wrap">')
m.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-100 dark:bg-emerald-900/30"><ShieldCheck className="h-3 w-3 text-emerald-600"/><span className="text-[10px] font-semibold text-emerald-700 dark:text-emerald-300">97.2% Pass Rate</span></div>')
m.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-blue-100 dark:bg-blue-900/30"><span className="text-[10px] font-semibold text-blue-700 dark:text-blue-300">6 Inspectors Active</span></div>')
m.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-amber-100 dark:bg-amber-900/30"><span className="text-[10px] font-semibold text-amber-700 dark:text-amber-300">0.8% Defect Rate</span></div>')
m.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-red-100 dark:bg-red-900/30"><ShieldAlert className="h-3 w-3 text-red-600"/><span className="text-[10px] font-semibold text-red-700 dark:text-red-300">3 Escalations</span></div>')
m.append('      </div>')
m.append('      <Tabs value={tab} onValueChange={setTab}>')
m.append('        <TabsList className="bg-gradient-to-r from-emerald-500/10 to-blue-500/10 p-0.5 h-9">')
m.append('          {tabs.map(t => <TabsTrigger key={t.key} value={t.key} className="text-xs gap-1.5 data-[state=active]:bg-emerald-600 data-[state=active]:text-white">{t.icon}{t.label}</TabsTrigger>)}')
m.append('        </TabsList>')
m.append('        {tabs.map(t => tab === t.key && <div key={t.key} className="mt-3">{t.content}</div>)}')
m.append('      </Tabs>')
m.append('      <Sheet open={!!detail} onOpenChange={() => setDetail(null)}><SheetContent className="w-[420px] overflow-y-auto"><SheetHeader><SheetTitle className="text-sm">Inspection Detail</SheetTitle></SheetHeader>{detail && <div className="mt-4 space-y-3"><div className="rounded-lg bg-gradient-to-r from-emerald-50 to-blue-50 dark:from-emerald-900/20 dark:to-blue-900/20 p-4"><div className="text-lg font-bold">QC Details</div></div>{Object.entries(detail).map(([k,v]) => <div key={k} className="flex items-center justify-between py-1.5 border-b border-border/50"><span className="text-xs font-medium text-muted-foreground">{k}</span><span className="text-xs font-semibold tabular-nums">{String(v)}</span></div>)}</div>}</SheetContent></Sheet>')
m.append('    </div>')
m.append('  )')
m.append('}')

m1 = '\n'.join(m)

# ═══════════════════════════════════════════════════════════════════════
# MODULE 2: WMS Configuration Studio
# ═══════════════════════════════════════════════════════════════════════
m2 = []
m2.append('"use client"')
m2.append('')
m2.append('import { useState, useMemo } from "react"')
m2.append('import {')
m2.append('  AreaChart, Area, BarChart, Bar, PieChart, Pie, Cell,')
m2.append('  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip,')
m2.append('} from "recharts"')
m2.append('import {')
m2.append('  Search, Eye, ArrowUpDown, TrendingUp, TrendingDown, Clock, IndianRupee, Zap,')
m2.append('  AlertTriangle, Users, BarChart3, MapPin, Package, Box, CheckCircle, XCircle, Activity, Timer, ShieldCheck, Star, Radio, Gauge, Warehouse, Layers, ScanLine, Factory, Weight, Ruler, Settings, Grid3x3, Maximize2, Move, ArrowRight, ChevronRight, RefreshCw, Download, Filter, Target, LayoutGrid, PackageSearch, ScanBarcode, ClipboardCheck')
m2.append('} from "lucide-react"')
m2.append('import { PageHeader } from "@/components/shared/page-header"')
m2.append('import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"')
m2.append('import { Input } from "@/components/ui/input"')
m2.append('import { Button } from "@/components/ui/button"')
m2.append('import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"')
m2.append('import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"')
m2.append('')
m2.append('const ZONE_TYPES = ["Picking Zone","Receiving Dock","Shipping Dock","Staging","Cold Storage","Bulk Storage","Returns Area","Value-added Services","Kitting Area","QC Hold"] as const')
m2.append('const ZONE_EMOJI: Record<string,string> = {["Picking Zone"]:"\U0001f4e6",["Receiving Dock"]:"\U0001f4e5",["Shipping Dock"]:"\U0001f69b",Staging:"\U0001f4c4",["Cold Storage"]:"\u2744\ufe0f",["Bulk Storage"]:"\U0001f4e5","Returns Area"]:"\U0001f504",["Value-added Services"]:"\U0001f527",["Kitting Area"]:"\U0001f3af",["QC Hold"]:"\u2705"}')
m2.append('const SLOT_TYPES = ["Pallet Rack","Shelf Bin","Floor Stack","Flow Rack","Carton Flow","Mezzanine","Mobile Rack","Drive-in","Push-back","ASRS"] as const')
m2.append('const EQUIP_TYPES = ["Forklift","Pallet Jack","Conveyor","Reach Truck","Order Picker","Cherry Picker","Scissor Lift","Automated Crane","AGV","Robotic Arm"] as const')
m2.append('const EQUIP_STS = ["Active","Maintenance","Idle","Reserved","Decommissioned"] as const')
m2.append('const CITIES = ["Mumbai","Delhi","Bangalore","Chennai","Hyderabad","Kolkata","Pune","Ahmedabad"] as const')
m2.append('const LAYOUT_STS = ["Active","Draft","Under Review","Deprecated","Migrated"] as const')
m2.append('const MO = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"] as const')
m2.append('const TH = {blue:"#3b82f6",emerald:"#059669",amber:"#d97706",violet:"#7c3aed",rose:"#e11d48",cyan:"#0891b2",indigo:"#4f46e5",orange:"#ea580c"}')
m2.append('const PC = [TH.blue,TH.emerald,TH.amber,TH.violet,TH.rose,TH.cyan,TH.indigo,TH.orange]')
m2.append('')
m2.append('function seededRandom(seed: number): number { const x = Math.sin(seed * 9301 + 49297 + 233280) * 10000; return x - Math.floor(x) }')
m2.append('function ri(a: number, b: number, s: number): number { return Math.floor(seededRandom(s) * (b - a + 1)) + a }')
m2.append('function pick<T>(arr: readonly T[], s: number): T { return arr[Math.abs(s) % arr.length] }')
m2.append('function filterData<T>(d: T[], q: string): T[] { if (!q) return d; const l = q.toLowerCase(); return d.filter(i => Object.values(i as unknown as Record<string, string | number>).some(v => String(v).toLowerCase().includes(l))) }')
m2.append('function sortedData<T>(d: T[], f: string, dir: "asc" | "desc"): T[] { return [...d].sort((a, b) => { const av = (a as unknown as Record<string, string | number>)[f], bv = (b as unknown as Record<string, string | number>)[f]; if (typeof av === "number" && typeof bv === "number") return dir === "asc" ? av - bv : bv - av; return dir === "asc" ? String(av ?? "").localeCompare(String(bv ?? "")) : String(bv ?? "").localeCompare(String(av ?? "")) }) }')
m2.append('')
m2.append('/* 16 Visual Components */')
m2.append('function ZoneBadge({ z }: { z: string }) {')
m2.append('  const cl: Record<string,string> = {["Picking Zone"]:"bg-emerald-100 text-emerald-700",["Receiving Dock"]:"bg-blue-100 text-blue-700",["Shipping Dock"]:"bg-amber-100 text-amber-700",Staging:"bg-violet-100 text-violet-700",["Cold Storage"]:"bg-cyan-100 text-cyan-700",["Bulk Storage"]:"bg-indigo-100 text-indigo-700",["Returns Area"]:"bg-rose-100 text-rose-700",["Value-added Services"]:"bg-orange-100 text-orange-700",["Kitting Area"]:"bg-pink-100 text-pink-700",["QC Hold"]:"bg-red-100 text-red-700"}')
m2.append('  return <span className={"wcs-zone inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium " + (cl[z]||"bg-gray-100")}>{ZONE_EMOJI[z]} {z}</span>')
m2.append('}')
m2.append('function SlotBadge({ t }: { t: string }) { return <span className="wcs-slot inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-medium bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300">\U0001f4c1 {t}</span> }')
m2.append('function EquipBadge({ t }: { t: string }) {')
m2.append('  const cl: Record<string,string> = {Forklift:"bg-amber-100 text-amber-700","Pallet Jack":"bg-blue-100 text-blue-700",Conveyor:"bg-emerald-100 text-emerald-700","Reach Truck":"bg-violet-100 text-violet-700","Order Picker":"bg-cyan-100 text-cyan-700","Cherry Picker":"bg-rose-100 text-rose-700","Scissor Lift":"bg-indigo-100 text-indigo-700","Automated Crane":"bg-orange-100 text-orange-700",AGV:"bg-teal-100 text-teal-700","Robotic Arm":"bg-pink-100 text-pink-700"}')
m2.append('  return <span className={"wcs-eq inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium " + (cl[t]||"bg-gray-100")}>\U0001f527 {t}</span>')
m2.append('}')
m2.append('function EquipStatusBadge({ s }: { s: string }) {')
m2.append('  const cl: Record<string,string> = {Active:"bg-emerald-100 text-emerald-700",Maintenance:"bg-amber-100 text-amber-700 animate-pulse",Idle:"bg-slate-100 text-slate-600",Reserved:"bg-blue-100 text-blue-700",Decommissioned:"bg-gray-100 text-gray-500"}')
m2.append('  return <span className={"wcs-es inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cl[s]||"bg-gray-100")}>\u25cf {s}</span>')
m2.append('}')
m2.append('function LayoutStatusBadge({ s }: { s: string }) {')
m2.append('  const cl: Record<string,string> = {Active:"bg-emerald-100 text-emerald-700",Draft:"bg-blue-100 text-blue-700","Under Review":"bg-amber-100 text-amber-700",Deprecated:"bg-gray-100 text-gray-500",Migrated:"bg-violet-100 text-violet-700"}')
m2.append('  return <span className={"wcs-ls inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold " + (cl[s]||"bg-gray-100")}>\u25cf {s}</span>')
m2.append('}')
m2.append('function CityBadge({ city }: { city: string }) { return <span className="wcs-city inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-medium bg-cyan-50 text-cyan-700 dark:bg-cyan-900/30 dark:text-cyan-300">\U0001f4cd {city}</span> }')
m2.append('function UtilBar({ pct }: { pct: number }) {')
m2.append('  const c = pct > 90 ? "bg-red-500" : pct > 75 ? "bg-amber-500" : pct > 50 ? "bg-blue-500" : "bg-emerald-500"')
m2.append('  return <div className="wcs-util flex items-center gap-2"><div className="flex-1 h-2.5 rounded-full bg-gray-200 dark:bg-gray-700"><div className={"h-full rounded-full transition-all " + c} style={{width: Math.min(pct,100)+"%"}}/></div><span className="text-[10px] font-bold tabular-nums">{pct}%</span></div>')
m2.append('}')
m2.append('function CapacityTile({ used, total, unit }: { used: number; total: number; unit: string }) {')
m2.append('  const pct = Math.round((used / Math.max(total, 1)) * 100)')
m2.append('  const c = pct > 90 ? "text-red-600" : pct > 75 ? "text-amber-600" : pct > 50 ? "text-blue-600" : "text-emerald-600"')
m2.append('  return <div className="wcs-cap flex items-center gap-2"><span className={"text-sm font-bold tabular-nums " + c}>{used}/{total}</span><span className="text-[10px] text-muted-foreground">{unit}</span></div>')
m2.append('}')
m2.append('function ValueTile({ value, label, trend }: { value: string; label: string; trend: number }) {')
m2.append('  return <div className="wcs-val text-right"><div className="text-sm font-bold tabular-nums">{value}</div><div className="text-[10px] text-muted-foreground">{label}</div>{trend !== 0 && <div className={"text-[10px] font-semibold flex items-center justify-end gap-0.5 " + (trend > 0 ? "text-emerald-600" : "text-red-600")}>{trend > 0 ? <TrendingUp className="h-3 w-3"/> : <TrendingDown className="h-3 w-3"/>}{Math.abs(trend)}%</div>}</div>')
m2.append('}')
m2.append('function StarRating({ value }: { value: number }) { return <span className="wcs-stars inline-flex gap-0.5">{"\u2605".repeat(value)}{"\u2606".repeat(5-value)}</span> }')
m2.append('function WeightTile({ value }: { value: number }) { return <span className="wcs-wt text-sm font-bold tabular-nums text-indigo-600 dark:text-indigo-400">{value.toLocaleString()} kg</span> }')
m2.append('function ThroughputTile({ value }: { value: number }) { return <span className="wcs-tp text-sm font-bold tabular-nums text-emerald-600 dark:text-emerald-400">{value.toLocaleString()} ops/hr</span> }')
m2.append('function SlotCountTile({ total, occupied }: { total: number; occupied: number }) {')
m2.append('  const pct = Math.round((occupied / Math.max(total, 1)) * 100)')
m2.append('  return <div className="wcs-slot-count flex items-center gap-2"><span className="text-sm font-bold tabular-nums">{occupied}<span className="text-muted-foreground font-normal">/{total}</span></span><div className="flex-1 h-1.5 rounded-full bg-gray-200 dark:bg-gray-700"><div className={"h-full rounded-full " + (pct > 90 ? "bg-red-500" : pct > 75 ? "bg-amber-500" : "bg-emerald-500")} style={{width: pct+"%"}}/></div></div>')
m2.append('}')
m2.append('function ValueTileNoTrend({ value, label }: { value: string; label: string }) {')
m2.append('  return <div className="wcs-val text-right"><div className="text-sm font-bold tabular-nums">{value}</div><div className="text-[10px] text-muted-foreground">{label}</div></div>')
m2.append('}')

# Data
m2.append('')
m2.append('function genZones() {')
m2.append('  return Array.from({length: 50}, (_, i) => ({')
m2.append('    id: "ZONE-" + String(i+11001).padStart(4,"0"),')
m2.append('    name: pick(ZONE_TYPES, i+1) + " " + String.fromCharCode(65 + (i % 8)),')
m2.append('    type: pick(ZONE_TYPES, i+1),')
m2.append('    city: pick(CITIES, i+2),')
m2.append('    capacity: ri(200, 2000, i+3),')
m2.append('    occupied: ri(50, 1800, i+4),')
m2.append('    totalSlots: ri(20, 200, i+5),')
m2.append('    usedSlots: ri(5, 180, i+6),')
m2.append('    utilization: ri(30, 98, i+7),')
m2.append('    throughput: ri(100, 800, i+8),')
m2.append('    maxWeight: ri(500, 10000, i+9),')
m2.append('    currentWeight: ri(100, 9000, i+10),')
m2.append('    tempZone: pick(["Ambient","Cold","Frozen","Controlled"], i+11),')
m2.append('  }))')
m2.append('}')
m2.append('')
m2.append('function genEquipment() {')
m2.append('  return Array.from({length: 60}, (_, i) => ({')
m2.append('    id: "EQ-" + String(i+12001).padStart(4,"0"),')
m2.append('    type: pick(EQUIP_TYPES, i+1),')
m2.append('    status: pick(EQUIP_STS, i+2),')
m2.append('    city: pick(CITIES, i+3),')
m2.append('    zone: pick(ZONE_TYPES, i+4),')
m2.append('    utilization: ri(10, 95, i+5),')
m2.append('    operatingHours: ri(100, 2000, i+6),')
m2.append('    efficiency: ri(60, 99, i+7),')
m2.append('    maintCost: ri(5, 50, i+8),')
m2.append('    lastService: ri(1, 60, i+9) + "d ago",')
m2.append('    nextService: ri(1, 90, i+10) + "d",')
m2.append('  }))')
m2.append('}')
m2.append('')
m2.append('function genLayouts() {')
m2.append('  return Array.from({length: 30}, (_, i) => ({')
m2.append('    id: "LAY-" + String(i+13001).padStart(4,"0"),')
m2.append('    name: pick(["Layout Alpha","Layout Beta","Layout Gamma","Layout Delta","Layout Epsilon"], i+1) + " v" + ri(1,5,i+2),')
m2.append('    status: pick(LAYOUT_STS, i+3),')
m2.append('    city: pick(CITIES, i+4),')
m2.append('    zones: ri(8, 24, i+5),')
m2.append('    totalArea: ri(5000, 50000, i+6) + " sqft",')
m2.append('    utilization: ri(60, 98, i+7),')
m2.append('    throughput: ri(500, 3000, i+8),')
m2.append('    efficiency: ri(70, 98, i+9),')
m2.append('  }))')
m2.append('}')
m2.append('')
m2.append('function genCharts() {')
m2.append('  const monthly = MO.map((m, i) => ({ month: m, util: ri(60,95,i), throughput: ri(2000,8000,i+12), config: ri(2,15,i+24) }))')
m2.append('  const zonePie = ZONE_TYPES.map((z, i) => ({ name: z.split(" ")[0], value: ri(5,30,i) }))')
m2.append('  const equipBar = EQUIP_TYPES.map((e, i) => ({ name: e.split(" ")[0], active: ri(5,15,i), maintenance: ri(0,3,i+10), util: ri(50,95,i+20) }))')
m2.append('  const slotPie = SLOT_TYPES.map((s, i) => ({ name: s.split(" ")[0], count: ri(50,300,i) }))')
m2.append('  return { monthly, zonePie, equipBar, slotPie }')
m2.append('}')

# Main
m2.append('')
m2.append('export default function WmsConfigurationStudioView() {')
m2.append('  const [tab, setTab] = useState("overview")')
m2.append('  const [search, setSearch] = useState("")')
m2.append('  const [sortField, setSortField] = useState("id")')
m2.append('  const [sortDir, setSortDir] = useState<"asc"|"desc">("asc")')
m2.append('  const [detail, setDetail] = useState<Record<string, unknown>|null>(null)')
m2.append('')
m2.append('  const zones = useMemo(() => genZones(), [])')
m2.append('  const equipment = useMemo(() => genEquipment(), [])')
m2.append('  const layouts = useMemo(() => genLayouts(), [])')
m2.append('  const charts = useMemo(() => genCharts(), [])')
m2.append('')
m2.append('  const filteredZones = useMemo(() => sortedData(filterData(zones, search), sortField, sortDir), [zones, search, sortField, sortDir])')
m2.append('  const filteredEquip = useMemo(() => sortedData(filterData(equipment, search), sortField, sortDir), [equipment, search, sortField, sortDir])')
m2.append('  const filteredLayouts = useMemo(() => sortedData(filterData(layouts, search), sortField, sortDir), [layouts, search, sortField, sortDir])')
m2.append('')
m2.append('  const toggleSort = (f: string) => { if (sortField === f) setSortDir(d => d === "asc" ? "desc" : "asc"); else { setSortField(f); setSortDir("asc") } }')

# Tab 0
m2.append('')
m2.append('  const tab0 = (')
m2.append('    <div className="space-y-4">')
m2.append('      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">')
m2.append("        {[['Total Zones','50','+4',<Layers key='l'/>],['Avg Utilization','78%','+3%',<Gauge key='g'/>],['Equipment Active','48','+2',<Settings key='s'/>],['Total Slots','2,450','+120',<Grid3x3 key='gr'/>],['Layouts Active','18','+1',<LayoutGrid key='lg'/>],['Config Changes','12','+5',<RefreshCw key='r'/>],['Throughput','5,240 ops/hr','+8%',<Activity key='a'/>],['Warehouse Area','2.8L sqft','0',<Maximize2 key='m'/>]].map(([label,val,tr,icon], i) => (")
m2.append('          <Card key={i} className="glass-subtle wcs-kpi"><CardContent className="p-3"><div className="flex items-center gap-2.5">{icon}<div><div className="text-[10px] text-muted-foreground">{String(label)}</div><div className="text-lg font-black tabular-nums">{String(val)}</div><div className="text-[10px] font-semibold text-emerald-600">{String(tr)}</div></div></div></CardContent></Card>')
m2.append('        ))}')
m2.append('      </div>')
m2.append('      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">')
m2.append('        <Card className="glass-subtle wcs-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Monthly Utilization & Throughput</CardTitle></CardHeader><CardContent className="p-3"><LineChart data={charts.monthly}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Line type="monotone" dataKey="util" stroke={TH.blue} strokeWidth={2}/><Line type="monotone" dataKey="throughput" stroke={TH.emerald} strokeWidth={2}/></LineChart></CardContent></Card>')
m2.append('        <Card className="glass-subtle wcs-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Zone Type Distribution</CardTitle></CardHeader><CardContent className="p-3"><PieChart><Pie data={charts.zonePie} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({name}: {name:string}) => <text x={0} y={0} fill="currentColor" fontSize={9} textAnchor="middle">{name}</text>}>{charts.zonePie.map((_,i) => <Cell key={i} fill={PC[i%PC.length]}/>)}</Pie><Tooltip/></PieChart></CardContent></Card>')
m2.append('        <Card className="glass-subtle wcs-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Equipment Status</CardTitle></CardHeader><CardContent className="p-3"><BarChart data={charts.equipBar}><CartesianGrid strokeDasharray="3 3" className="opacity-30"/><XAxis dataKey="name" tick={{fontSize:9}}/><YAxis tick={{fontSize:10}}/><Tooltip wrapperClassName="rounded-lg shadow-lg"/><Bar dataKey="active" fill={TH.emerald} radius={[4,4,0,0]}/><Bar dataKey="maintenance" fill={TH.amber} radius={[4,4,0,0]}/></BarChart></CardContent></Card>')
m2.append('        <Card className="glass-subtle wcs-chart"><CardHeader className="p-3 pb-1"><CardTitle className="text-xs font-semibold">Slot Type Distribution</CardTitle></CardHeader><CardContent className="p-3"><PieChart><Pie data={charts.slotPie} cx="50%" cy="50%" outerRadius={80} dataKey="count" label={({name}: {name:string}) => <text x={0} y={0} fill="currentColor" fontSize={9} textAnchor="middle">{name}</text>}>{charts.slotPie.map((_,i) => <Cell key={i} fill={PC[i%PC.length]}/>)}</Pie><Tooltip/></PieChart></CardContent></Card>')
m2.append('      </div>')
m2.append('    </div>')
m2.append('  )')

# Tab 1: Zone Config
m2.append('')
m2.append('  const tab1 = (')
m2.append('    <div className="space-y-3">')
m2.append('      <div className="flex items-center gap-2"><div className="relative flex-1"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground"/><Input className="h-8 pl-8 text-xs" placeholder="Search zones..." value={search} onChange={e => setSearch(e.target.value)}/></div></div>')
m2.append('      <div className="rounded-lg border overflow-auto max-h-[calc(100vh-280px)]">')
m2.append('        <table className="w-full text-xs"><thead className="bg-blue-50 dark:bg-blue-900/20 sticky top-0 z-10"><tr>')
m2.append('          <th className="p-2 text-left font-semibold cursor-pointer select-none" onClick={() => toggleSort("id")}>ID <ArrowUpDown className="inline h-3 w-3 ml-0.5 opacity-50"/></th>')
m2.append('          <th className="p-2 text-left font-semibold">Type</th>')
m2.append('          <th className="p-2 text-left font-semibold">City</th>')
m2.append('          <th className="p-2 text-left font-semibold">Capacity</th>')
m2.append('          <th className="p-2 text-left font-semibold">Occupied</th>')
m2.append('          <th className="p-2 text-left font-semibold">Utilization</th>')
m2.append('          <th className="p-2 text-left font-semibold">Slots</th>')
m2.append('          <th className="p-2 text-left font-semibold">Throughput</th>')
m2.append('          <th className="p-2 text-left font-semibold">Weight</th>')
m2.append('          <th className="p-2 text-left font-semibold">Temp</th>')
m2.append('          <th className="p-2"></th>')
m2.append('        </tr></thead><tbody className="divide-y">')
m2.append('          {filteredZones.map(row => (')
m2.append('            <tr key={row.id} className="hover:bg-blue-50/50 dark:hover:bg-blue-900/10 transition-colors">')
m2.append('              <td className="p-2 font-mono font-medium">{row.id}</td>')
m2.append('              <td className="p-2"><ZoneBadge z={row.type}/></td>')
m2.append('              <td className="p-2"><CityBadge city={row.city}/></td>')
m2.append('              <td className="p-2"><CapacityTile used={row.occupied} total={row.capacity} unit="loc"/></td>')
m2.append('              <td className="p-2 numeric-cell tabular-nums">{row.occupied.toLocaleString()}</td>')
m2.append('              <td className="p-2"><UtilBar pct={row.utilization}/></td>')
m2.append('              <td className="p-2"><SlotCountTile total={row.totalSlots} occupied={row.usedSlots}/></td>')
m2.append('              <td className="p-2"><ThroughputTile value={row.throughput}/></td>')
m2.append('              <td className="p-2"><WeightTile value={row.currentWeight}/></td>')
m2.append('              <td className="p-2"><span className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-medium bg-slate-100 text-slate-700">{row.tempZone === "Cold" ? "\\u2744\\ufe0f" : row.tempZone === "Frozen" ? "\\U0001f9ca" : "\U0001f321\ufe0f"} {row.tempZone}</span></td>')
m2.append('              <td className="p-2"><Button variant="ghost" size="sm" className="h-6 w-6 p-0" onClick={() => setDetail(row)}><Eye className="h-3 w-3"/></Button></td>')
m2.append('            </tr>')
m2.append('          ))}')
m2.append('        </tbody></table>')
m2.append('      </div>')
m2.append('      <div className="text-[10px] text-muted-foreground text-right">{filteredZones.length} zones</div>')
m2.append('    </div>')
m2.append('  )')

# Tab 2: Equipment
m2.append('')
m2.append('  const tab2 = (')
m2.append('    <div className="space-y-3">')
m2.append('      <div className="flex items-center gap-2"><div className="relative flex-1"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground"/><Input className="h-8 pl-8 text-xs" placeholder="Search equipment..." value={search} onChange={e => setSearch(e.target.value)}/></div></div>')
m2.append('      <div className="rounded-lg border overflow-auto max-h-[calc(100vh-280px)]">')
m2.append('        <table className="w-full text-xs"><thead className="bg-amber-50 dark:bg-amber-900/20 sticky top-0 z-10"><tr>')
m2.append('          <th className="p-2 text-left font-semibold cursor-pointer select-none" onClick={() => toggleSort("id")}>ID <ArrowUpDown className="inline h-3 w-3 ml-0.5 opacity-50"/></th>')
m2.append('          <th className="p-2 text-left font-semibold">Type</th>')
m2.append('          <th className="p-2 text-left font-semibold">Status</th>')
m2.append('          <th className="p-2 text-left font-semibold">City</th>')
m2.append('          <th className="p-2 text-left font-semibold">Zone</th>')
m2.append('          <th className="p-2 text-left font-semibold">Utilization</th>')
m2.append('          <th className="p-2 text-left font-semibold">Operating Hrs</th>')
m2.append('          <th className="p-2 text-left font-semibold">Efficiency</th>')
m2.append('          <th className="p-2 text-left font-semibold">Maint Cost</th>')
m2.append('          <th className="p-2 text-left font-semibold">Service</th>')
m2.append('        </tr></thead><tbody className="divide-y">')
m2.append('          {filteredEquip.map(row => (')
m2.append('            <tr key={row.id} className="hover:bg-amber-50/50 dark:hover:bg-amber-900/10 transition-colors">')
m2.append('              <td className="p-2 font-mono font-medium">{row.id}</td>')
m2.append('              <td className="p-2"><EquipBadge t={row.type}/></td>')
m2.append('              <td className="p-2"><EquipStatusBadge s={row.status}/></td>')
m2.append('              <td className="p-2"><CityBadge city={row.city}/></td>')
m2.append('              <td className="p-2"><ZoneBadge z={row.zone}/></td>')
m2.append('              <td className="p-2"><UtilBar pct={row.utilization}/></td>')
m2.append('              <td className="p-2 numeric-cell tabular-nums">{row.operatingHours.toLocaleString()}</td>')
m2.append('              <td className="p-2 numeric-cell tabular-nums">{row.efficiency}%</td>')
m2.append('              <td className="p-2"><span className="text-sm font-bold tabular-nums text-orange-600">\u20b9{row.maintCost * 1000.toLocaleString("en-IN")}</span></td>')
m2.append('              <td className="p-2 text-muted-foreground">{row.lastService}</td>')
m2.append('            </tr>')
m2.append('          ))}')
m2.append('        </tbody></table>')
m2.append('      </div>')
m2.append('      <div className="text-[10px] text-muted-foreground text-right">{filteredEquip.length} equipment</div>')
m2.append('    </div>')
m2.append('  )')

# Tab 3: Layouts
m2.append('')
m2.append('  const tab3 = (')
m2.append('    <div className="space-y-3">')
m2.append('      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">')
m2.append('        {filteredLayouts.map(l => (')
m2.append('          <Card key={l.id} className="glass-subtle wcs-layout hover:border-blue-300 dark:hover:border-blue-700 transition-all">')
m2.append('            <CardContent className="p-4">')
m2.append('              <div className="flex items-center justify-between mb-2"><span className="font-mono text-[10px] text-muted-foreground">{l.id}</span><LayoutStatusBadge s={l.status}/></div>')
m2.append('              <div className="text-xs font-bold mb-2">{l.name}</div>')
m2.append('              <div className="flex items-center gap-2 mb-2"><CityBadge city={l.city}/><ZoneBadge z={pick(ZONE_TYPES, l.zones)}/></div>')
m2.append('              <div className="grid grid-cols-2 gap-1.5 text-center">')
m2.append('                <div className="rounded-lg bg-blue-50 dark:bg-blue-900/20 p-1.5"><div className="text-xs font-black text-blue-600">{l.zones}</div><div className="text-[9px] text-muted-foreground">Zones</div></div>')
m2.append('                <div className="rounded-lg bg-emerald-50 dark:bg-emerald-900/20 p-1.5"><div className="text-xs font-black text-emerald-600">{l.utilization}%</div><div className="text-[9px] text-muted-foreground">Util</div></div>')
m2.append('                <div className="rounded-lg bg-violet-50 dark:bg-violet-900/20 p-1.5"><div className="text-xs font-black text-violet-600">{l.efficiency}%</div><div className="text-[9px] text-muted-foreground">Efficiency</div></div>')
m2.append('                <div className="rounded-lg bg-amber-50 dark:bg-amber-900/20 p-1.5"><div className="text-xs font-black text-amber-600">{l.throughput}</div><div className="text-[9px] text-muted-foreground">Ops/hr</div></div>')
m2.append('              </div>')
m2.append('              <div className="mt-2 text-[10px] text-muted-foreground">Area: {l.totalArea}</div>')
m2.append('            </CardContent>')
m2.append('          </Card>')
m2.append('        ))}')
m2.append('      </div>')
m2.append('    </div>')
m2.append('  )')

# Return
m2.append('')
m2.append('  const tabs = [')
m2.append('    {key:"overview",label:"Dashboard",icon:<LayoutGrid className="h-3.5 w-3.5"/>,content:tab0},')
m2.append('    {key:"zones",label:"Zones",icon:<Layers className="h-3.5 w-3.5"/>,content:tab1},')
m2.append('    {key:"equipment",label:"Equipment",icon:<Settings className="h-3.5 w-3.5"/>,content:tab2},')
m2.append('    {key:"layouts",label:"Layouts",icon:<Grid3x3 className="h-3.5 w-3.5"/>,content:tab3},')
m2.append('  ]')
m2.append('')
m2.append('  return (')
m2.append('    <div className="space-y-4 p-4">')
m2.append('      <PageHeader title="WMS Configuration Studio" description="Warehouse zone configuration, slot management, equipment tracking, and layout design optimization"/>')
m2.append('      <div className="flex items-center gap-3 flex-wrap">')
m2.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-blue-100 dark:bg-blue-900/30"><Layers className="h-3 w-3 text-blue-600"/><span className="text-[10px] font-semibold text-blue-700 dark:text-blue-300">50 Zones Configured</span></div>')
m2.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-100 dark:bg-emerald-900/30"><span className="text-[10px] font-semibold text-emerald-700 dark:text-emerald-300">48 Equipment Active</span></div>')
m2.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-violet-100 dark:bg-violet-900/30"><span className="text-[10px] font-semibold text-violet-700 dark:text-violet-300">18 Active Layouts</span></div>')
m2.append('        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-amber-100 dark:bg-amber-900/30"><span className="text-[10px] font-semibold text-amber-700 dark:text-amber-300">3 Need Maintenance</span></div>')
m2.append('      </div>')
m2.append('      <Tabs value={tab} onValueChange={setTab}>')
m2.append('        <TabsList className="bg-gradient-to-r from-blue-500/10 to-violet-500/10 p-0.5 h-9">')
m2.append('          {tabs.map(t => <TabsTrigger key={t.key} value={t.key} className="text-xs gap-1.5 data-[state=active]:bg-blue-600 data-[state=active]:text-white">{t.icon}{t.label}</TabsTrigger>)}')
m2.append('        </TabsList>')
m2.append('        {tabs.map(t => tab === t.key && <div key={t.key} className="mt-3">{t.content}</div>)}')
m2.append('      </Tabs>')
m2.append('      <Sheet open={!!detail} onOpenChange={() => setDetail(null)}><SheetContent className="w-[420px] overflow-y-auto"><SheetHeader><SheetTitle className="text-sm">Zone Detail</SheetTitle></SheetHeader>{detail && <div className="mt-4 space-y-3"><div className="rounded-lg bg-gradient-to-r from-blue-50 to-violet-50 dark:from-blue-900/20 dark:to-violet-900/20 p-4"><div className="text-lg font-bold">Zone Configuration</div></div>{Object.entries(detail).map(([k,v]) => <div key={k} className="flex items-center justify-between py-1.5 border-b border-border/50"><span className="text-xs font-medium text-muted-foreground">{k}</span><span className="text-xs font-semibold tabular-nums">{String(v)}</span></div>)}</div>}</SheetContent></Sheet>')
m2.append('    </div>')
m2.append('  )')
m2.append('}')

m2_content = '\n'.join(m2)

# Write
with open(os.path.join(BASE, 'warehouse-quality-command-view.tsx'), 'w') as f:
    f.write(m1)
with open(os.path.join(BASE, 'wms-configuration-studio-view.tsx'), 'w') as f:
    f.write(m2_content)

print(f"M1: warehouse-quality-command-view.tsx - {len(m1)} lines")
print(f"M2: wms-configuration-studio-view.tsx - {len(m2)} lines")
