#!/usr/bin/env python3
"""Generate R417b: Silica Glass Logistics View"""
import os

COMPONENT_NAME = "SilicaGlass"
THEME = "silica-glass"
PREFIX = "SLG"
ICON_IMPORT = "Cog"
ICON_JSX = "Cog"
COLOR_ACCENT = "#0ea5e9"  # sky-500
COLOR_ACCENT_TW = "sky"
INTERFACE_NAME = "SilicaGlassRecord"
VARIABLE_NAME = "silicaGlassRecords"

RECORDS = [
    ("SLG-0001", "SLG-B2401", "Mumbai", "Asahi India Glass", "SG-Optical Clear", "BEL HUD Display", 99.99, 6.5, 760, "Delivered", "Critical", "Asahi India Mumbai (MH)", "BEL Bengaluru (KA)", "2026-07-15", 1, "West", "Ultra-clear optical float glass for BEL head-up display fighter aircraft canopy &#8594; 1.2mm thick SG &#8594; &#8377;760Cr for 4,000 tonnes &#8594; India &#8377;4,200Cr optical &#8594; BEL 300 canopies &#8594; 6.5 GPa &#8594; &#8594; Float &#8594; &#8594; 560&#176;C &#8594; &#8594; Display"),
    ("SLG-0002", "SLG-B2402", "Bengaluru", "Saint-Gobain India", "SG-Low Iron Solar", "Adani Solar Panel", 99.98, 5.8, 820, "In Transit", "Critical", "Saint-Gobain Chennai (TN)", "Adani Mundra (GJ)", "2026-07-18", 3, "South", "Low-iron patterned solar glass for Adani Solar bifacial PERC module cover &#8594; 3.2mm AR coated &#8594; &#8377;820Cr for 8,000 tonnes &#8594; India &#8377;6,800Cr solar &#8594; Adani 5GW &#8594; 5.8 GPa &#8594; &#8594; Tempered &#8594; &#8594; 650&#176;C &#8594; &#8594; Solar"),
    ("SLG-0003", "SLG-B2403", "Chennai", "Tata AutoComp Glass", "SG-Laminated Auto", "Hyundai i25 Body", 99.95, 5.2, 690, "Delivered", "High", "Tata AutoComp Pune (MH)", "Hyundai Chennai (TN)", "2026-07-20", 1, "West", "Laminated safety glass windshield for Hyundai i25 sedan front and rear &#8594; PVB interlayer &#8594; &#8377;690Cr for 6,000 tonnes &#8594; India &#8377;4,800Cr auto &#8594; Hyundai 200K units &#8594; 5.2 GPa &#8594; &#8594; Laminated &#8594; &#8594; 350&#176;C &#8594; &#8594; Auto"),
    ("SLG-0004", "SLG-B2404", "Hyderabad", "Pharmaceutical Glass", "SG-Type I Borosil", "Dr Reddys Vial", 99.97, 7.2, 580, "Delivered", "High", "Pharma Glass Hyderabad (TG)", "Dr Reddys Hyderabad (TG)", "2026-07-22", 1, "South", "Type I borosilicate tubing for Dr Reddys injectable glass vial 2R and 5R &#8594; 5.5mm OD &#8594; &#8377;580Cr for 2,000 tonnes &#8594; India &#8377;3,200Cr pharma &#8594; Dr Reddys 400M vials &#8594; 7.2 GPa &#8594; &#8594; Borosilicate &#8594; &#8594; 560&#176;C &#8594; &#8594; Pharma"),
    ("SLG-0005", "SLG-B2405", "Kolkata", "GRP Industries", "SG-Fiber Optic Preform", "Sterlite Fiber", 99.999, 7.8, 940, "In Transit", "Critical", "OFS Fitel Hyderabad (TG)", "Sterlite Aurangabad (MH)", "2026-07-24", 2, "South", "High-purity SiO2 preform rod for Sterlite optical fiber SMF-28e+ drawing &#8594; 150mm dia &#8594; &#8377;940Cr for 500 tonnes &#8594; India &#8377;12,400Cr fiber &#8594; Sterlite 60M fkm &#8594; 7.8 GPa &#8594; &#8594; MCVD &#8594; &#8594; 2000&#176;C &#8594; &#8594; Telecom"),
    ("SLG-0006", "SLG-B2406", "Ahmedabad", "Gujarat Borosil", "SG-Corning 7740", "ISRO Telescope Mirror", 99.995, 6.8, 720, "Delivered", "High", "Gujarat Borosil Baroda (GJ)", "ISRO Bengaluru (KA)", "2026-07-26", 1, "West", "Low expansion borosilicate glass blank for ISRO Astrosat UV telescope primary mirror substrate &#8594; CTEmatch &#8594; &#8377;720Cr for 800 tonnes &#8594; India &#8377;6,800Cr optic &#8594; ISRO 4 mirrors &#8594; 6.8 GPa &#8594; &#8594; Fused &#8594; &#8594; 1020&#176;C &#8594; &#8594; Space"),
    ("SLG-0007", "SLG-B2407", "Jaipur", "Rajasthan Silica", "SG-Fused Quartz Tube", "Wipro Semi Fab", 99.99, 6.2, 540, "In Transit", "Medium", "Rajasthan Silica Jodhpur (RJ)", "Wipro Bengaluru (KA)", "2026-07-28", 2, "West", "Fused quartz tube for Wipro semiconductor furnace diffusion and LPCVD process &#8594; 200mm ID &#8594; &#8377;540Cr for 1,200 tonnes &#8594; India &#8377;5,400Cr semi &#8594; Wipro 8 fabs &#8594; 6.2 GPa &#8594; &#8594; Fused quartz &#8594; &#8594; 1200&#176;C &#8594; &#8594; Semi"),
    ("SLG-0008", "SLG-B2408", "Coimbatore", "TN Glass Works", "SG-Epoxy FRP", "L&T Wind Turbine", 99.6, 4.8, 480, "Delivered", "Medium", "TN Glass Coimbatore (TN)", "L&T Hazira (GJ)", "2026-07-30", 3, "South", "E-glass fiber fabric roll for L&T wind turbine blade spar cap FRP lamination &#8594; 600gsm UD &#8594; &#8377;480Cr for 6,000 tonnes &#8594; India &#8377;2,800Cr FRP &#8594; L&T 3,000 blades &#8594; 4.8 GPa &#8594; &#8594; E-glass &#8594; &#8594; 650&#176;C &#8594; &#8594; Wind"),
    ("SLG-0009", "SLG-B2409", "Guwahati", "Assam Silica Mine", "SG-High Silica Sand", "Kajaria Floor Tile", 99.5, 3.2, 320, "Delivered", "Low", "Assam Silica Tinsukia (AS)", "Kajaria Morbi (GJ)", "2026-08-01", 5, "East", "High-purity silica sand for Kajaria vitrified floor tile body and glaze formulation &#8594; 99.5% SiO2 &#8594; &#8377;320Cr for 20,000 tonnes &#8594; India &#8377;1,200Cr tile &#8594; Kajaria 50M sqm &#8594; 3.2 Mohs &#8594; &#8594; Silica sand &#8594; &#8594; 1200&#176;C &#8594; &#8594; Ceramic"),
    ("SLG-0010", "SLG-B2410", "Lucknow", "UP Silica Corp", "SG-Chemical Grade", "PI Industries API", 99.8, 4.5, 420, "Delivered", "Medium", "UP Silica Allahabad (UP)", "PI Industries Hyderabad (TG)", "2026-08-03", 2, "North", "Chemical-grade silica gel desiccant for PI Industries agrochemical formulation drying &#8594; 3-5mm beads &#8594; &#8377;420Cr for 5,000 tonnes &#8594; India &#8377;1,600Cr gel &#8594; PI 200K tonnes &#8594; 4.5 Mohs &#8594; &#8594; Silica gel &#8594; &#8594; 280&#176;C &#8594; &#8594; Chemical"),
    ("SLG-0011", "SLG-B2411", "Nagpur", "Borosil Glass Works", "SG-Lab Borosilicate", "CSIR-NPL Metrology", 99.96, 6.1, 520, "In Transit", "Medium", "Borosil Mumbai (MH)", "CSIR-NPL New Delhi (DL)", "2026-08-05", 1, "West", "Laboratory-grade borosilicate beaker and flask for CSIR-NPL national metrology calibration &#8594; 3.3 expansion &#8594; &#8377;520Cr for 1,000 tonnes &#8594; India &#8377;3,400Cr lab &#8594; NPL 500K units &#8594; 6.1 GPa &#8594; &#8594; Lab ware &#8594; &#8594; 560&#176;C &#8594; &#8594; Metrology"),
    ("SLG-0012", "SLG-B2412", "Visakhapatnam", "Vizag Glass Factory", "SG-Marine Porthole", "GRSE Naval Vessel", 99.88, 5.5, 440, "Delayed", "High", "Vizag Glass Visakha (AP)", "GRSE Kolkata (WB)", "2026-08-07", 2, "East", "Toughened marine-grade porthole glass for GRSE ASW corvette wheelhouse window &#8594; 20mm thick &#8594; &#8377;440Cr for 800 tonnes &#858594; India &#8377;3,800Cr marine &#8594; GRSE 12 vessels &#8594; 5.5 GPa &#8594; &#8594; Tempered &#8594; &#8594; 600&#176;C &#8594; &#8594; Naval"),
    ("SLG-0013", "SLG-B2413", "Bhopal", "BHEL Ceramic Div", "SG-SiC Composite", "BHEL Insulator", 99.7, 8.2, 680, "In Transit", "High", "BHEL Bhopal (MP)", "BHEL Bengaluru (KA)", "2026-08-09", 2, "Central", "SiO2-SiC composite insulator housing for BHEL 765kV transmission line post insulator &#8594; 110kN M&amp;E &#8594; &#8377;680Cr for 3,000 tonnes &#8594; India &#8377;5,200Cr T&amp;D &#8594; BHEL 40 lines &#8594; 8.2 GPa &#8594; &#8594; Composite &#8594; &#8594; 1200&#176;C &#8594; &#8594; Power"),
    ("SLG-0014", "SLG-B2414", "Rourkela", "SAIL Refractory Div", "SG-Refractory Silica", "Tata Steel BOF", 99.4, 3.8, 380, "Delivered", "Low", "SAIL Rourkela (OD)", "Tata Steel Jamshedpur (JH)", "2026-08-11", 1, "East", "Refractory silica brick for Tata Steel BOF converter lining and slag splash protection &#8594; 96% SiO2 &#8594; &#8377;380Cr for 8,000 tonnes &#8594; India &#8377;1,400Cr refractory &#8594; Tata 6 converters &#8594; 3.8 Mohs &#8594; &#8594; Silica brick &#8594; &#8594; 1650&#176;C &#8594; &#8594; Steel"),
]

OUTPUT = os.path.join("/home/z/my-project/src/components/modules", f"{THEME}-logistics-view.tsx")

lines = []
lines.append(r'''"use client";''')
lines.append("")
lines.append("import React, { useState, useMemo } from 'react';")
lines.append("import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';")
lines.append("import { Badge } from '@/components/ui/badge';")
lines.append("import { PageHeader } from '@/components/shared';")
lines.append(f"import {{ {ICON_IMPORT} }} from 'lucide-react';")
lines.append("")
lines.append(f"interface {INTERFACE_NAME} {{")
lines.append("  id: string;")
lines.append("  batchNo: string;")
lines.append("  city: string;")
lines.append("  manufacturer: string;")
lines.append("  oxideGrade: string;")
lines.append("  application: string;")
lines.append("  purityPercent: number;")
lines.append("  hardnessGPa: number;")
lines.append("  investmentCr: number;")
lines.append("  status: string;")
lines.append("  priority: string;")
lines.append("  origin: string;")
lines.append("  destination: string;")
lines.append("  shipDate: string;")
lines.append("  transitDays: number;")
lines.append("  zone: string;")
lines.append("  remarks: string;")
lines.append("}")
lines.append("")
lines.append(f"const {VARIABLE_NAME}: {INTERFACE_NAME}[] = [")

for i, rec in enumerate(RECORDS):
    rid, batch, city, mfr, grade, app, pur, hard, inv, stat, pri, orig, dest, ship, trans, zone, rem = rec
    comma = "," if i < len(RECORDS) - 1 else ","
    lines.append(f"  {{ id: '{rid}', batchNo: '{batch}', city: '{city}', manufacturer: '{mfr}', oxideGrade: '{grade}', application: '{app}', purityPercent: {pur}, hardnessGPa: {hard}, investmentCr: {inv}, status: '{stat}', priority: '{pri}', origin: '{orig}', destination: '{dest}', shipDate: '{ship}', transitDays: {trans}, zone: '{zone}', remarks: '{rem}' }}{comma}")

lines.append("];")
lines.append("")
lines.append(f"export default function {COMPONENT_NAME}LogisticsView() {{")
lines.append("  const [activeTab, setActiveTab] = useState<string>('dashboard');")
lines.append("  const [searchTerm, setSearchTerm] = useState<string>('');")
lines.append("  const [filterZone, setFilterZone] = useState<string>('all');")
lines.append("  const [filterStatus, setFilterStatus] = useState<string>('all');")
lines.append("")
lines.append("  const tabs = [")
lines.append("    { id: 'dashboard', label: 'Dashboard', icon: {ICON_JSX} },")
lines.append("    { id: 'registry', label: 'Registry', icon: {ICON_JSX} },")
lines.append("    { id: 'analytics', label: 'Analytics', icon: {ICON_JSX} },")
lines.append("    { id: 'insights', label: 'Insights', icon: {ICON_JSX} },")
lines.append("  ];")
lines.append("")
lines.append(f"  const filteredRecords = useMemo(() => {{")
lines.append(f"    return {VARIABLE_NAME}.filter((r) => {{")
lines.append("      const matchSearch = searchTerm === '' ||")
lines.append("        r.id.toLowerCase().includes(searchTerm.toLowerCase()) ||")
lines.append("        r.batchNo.toLowerCase().includes(searchTerm.toLowerCase()) ||")
lines.append("        r.city.toLowerCase().includes(searchTerm.toLowerCase()) ||")
lines.append("        r.manufacturer.toLowerCase().includes(searchTerm.toLowerCase()) ||")
lines.append("        r.oxideGrade.toLowerCase().includes(searchTerm.toLowerCase()) ||")
lines.append("        r.application.toLowerCase().includes(searchTerm.toLowerCase());")
lines.append("      const matchZone = filterZone === 'all' || r.zone === filterZone;")
lines.append("      const matchStatus = filterStatus === 'all' || r.status === filterStatus;")
lines.append("      return matchSearch && matchZone && matchStatus;")
lines.append("    });")
lines.append("  }, [searchTerm, filterZone, filterStatus]);")
lines.append("")
lines.append("  const zones = useMemo(() => {")
lines.append("    const zMap: Record<string, number> = {};")
lines.append(f"    {VARIABLE_NAME}.forEach((r) => {{ zMap[r.zone] = (zMap[r.zone] || 0) + 1; }});")
lines.append("    return Object.entries(zMap).sort((a, b) => b[1] - a[1]);")
lines.append("  }, []);")
lines.append("")
lines.append("  const kpiData = useMemo(() => {")
lines.append(f"    const total = {VARIABLE_NAME}.reduce((s: number, r) => s + r.investmentCr, 0);")
lines.append(f"    const avgPurity = {VARIABLE_NAME}.reduce((s: number, r) => s + r.purityPercent, 0) / {VARIABLE_NAME}.length;")
lines.append(f"    const delayed = {VARIABLE_NAME}.filter((r) => r.status === 'Delayed').length;")
lines.append(f"    const critical = {VARIABLE_NAME}.filter((r) => r.priority === 'Critical').length;")
lines.append(f"    return {{ total, avgPurity: avgPurity.toFixed(2), delayed, critical }};")
lines.append("  }, []);")
lines.append("")
lines.append("  const statusColor = (status: string) => {")
lines.append("    switch (status) {")
lines.append("      case 'Delivered': return 'bg-green-500/20 text-green-700 border-green-500/30';")
lines.append("      case 'In Transit': return 'bg-blue-500/20 text-blue-700 border-blue-500/30';")
lines.append("      case 'Delayed': return 'bg-red-500/20 text-red-700 border-red-500/30';")
lines.append("      case 'Processing': return 'bg-yellow-500/20 text-yellow-700 border-yellow-500/30';")
lines.append("      default: return 'bg-gray-500/20 text-gray-700 border-gray-500/30';")
lines.append("    }")
lines.append("  };")
lines.append("")
lines.append("  const priorityColor = (priority: string) => {")
lines.append("    switch (priority) {")
lines.append("      case 'Critical': return 'bg-red-500/20 text-red-700 border-red-500/30';")
lines.append("      case 'High': return 'bg-orange-500/20 text-orange-700 border-orange-500/30';")
lines.append("      case 'Medium': return 'bg-yellow-500/20 text-yellow-700 border-yellow-500/30';")
lines.append("      case 'Low': return 'bg-green-500/20 text-green-700 border-green-500/30';")
lines.append("      default: return 'bg-gray-500/20 text-gray-700 border-gray-500/30';")
lines.append("    }")
lines.append("  };")
lines.append("")
lines.append(f"  const themeColor = '{COLOR_ACCENT}';")
lines.append("  return (")
lines.append("    <div className=\"space-y-6 p-6\">")
lines.append("      <PageHeader title=\"Silica Glass Logistics\" description=\"Indian optical, solar, pharma, telecom and automotive silica glass supply chain tracking across 14 grades\" icon={ICON_JSX} />")
lines.append("      <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4\">")
lines.append("        <Card className=\"border-l-4 border-l-sky-500\"><CardContent className=\"pt-6\"><div className=\"text-2xl font-bold text-sky-600\">{kpiData.total.toLocaleString()} Cr</div><div className=\"text-xs text-muted-foreground mt-1\">Total Investment</div></CardContent></Card>")
lines.append("        <Card className=\"border-l-4 border-l-sky-500\"><CardContent className=\"pt-6\"><div className=\"text-2xl font-bold text-sky-600\">{kpiData.avgPurity}%</div><div className=\"text-xs text-muted-foreground mt-1\">Avg Purity</div></CardContent></Card>")
lines.append("        <Card className=\"border-l-4 border-l-sky-500\"><CardContent className=\"pt-6\"><div className=\"text-2xl font-bold text-sky-600\">{kpiData.delayed}</div><div className=\"text-xs text-muted-foreground mt-1\">Delayed Batches</div></CardContent></Card>")
lines.append("        <Card className=\"border-l-4 border-l-sky-500\"><CardContent className=\"pt-6\"><div className=\"text-2xl font-bold text-sky-600\">{kpiData.critical}</div><div className=\"text-xs text-muted-foreground mt-1\">Critical Records</div></CardContent></Card>")
lines.append("      </div>")
lines.append("      <div className=\"flex flex-wrap gap-2 border-b pb-2\">")
lines.append("        {tabs.map((tab) => (")
lines.append("          <button key={tab.id} onClick={() => setActiveTab(tab.id)} className={`px-4 py-2 rounded-t-md text-sm font-medium transition-colors ${activeTab === tab.id ? 'bg-sky-500 text-white shadow-md' : 'bg-muted text-muted-foreground hover:bg-muted/80'}`}>")
lines.append("            {tab.label}")
lines.append("          </button>")
lines.append("        ))}")
lines.append("      </div>")
lines.append("      {activeTab === 'dashboard' && (")
lines.append("        <div className=\"grid grid-cols-1 lg:grid-cols-2 gap-4\">")
lines.append("          <Card><CardHeader><CardTitle className=\"text-base\">Zone Distribution</CardTitle></CardHeader><CardContent>")
lines.append("            <div className=\"space-y-2\">{zones.map(([zone, count]) => { const pct = (count as number / " + VARIABLE_NAME + ".length) * 100; return <div key={zone} className=\"flex items-center gap-2\"><span className=\"text-xs w-16 text-muted-foreground\">{zone as string}</span><div className=\"flex-1 h-2 bg-muted rounded-full\"><div className=\"h-2 rounded-full\" style={{ width: `${pct}%`, backgroundColor: themeColor }} /></div><span className=\"text-xs font-medium w-8\">{count as number}</span></div>; })}</div>")
lines.append("          </CardContent></Card>")
lines.append("          <Card><CardHeader><CardTitle className=\"text-base\">Status Overview</CardTitle></CardHeader><CardContent>")
lines.append("            <div className=\"grid grid-cols-2 gap-3\">")
lines.append("              {['Delivered', 'In Transit', 'Delayed', 'Processing'].map((s) => { const c = " + VARIABLE_NAME + ".filter((r) => r.status === s).length; return <div key={s} className={`text-center p-3 rounded-lg border ${statusColor(s)}`}><div className=\"text-lg font-bold\">{c}</div><div className=\"text-xs\">{s}</div></div>; })}")
lines.append("            </div>")
lines.append("          </CardContent></Card>")
lines.append("          <Card className=\"lg:col-span-2\"><CardHeader><CardTitle className=\"text-base\">Investment by Grade (Top 8)</CardTitle></CardHeader><CardContent>")
lines.append("            <div className=\"grid grid-cols-2 md:grid-cols-4 gap-3\">")
lines.append("              " + VARIABLE_NAME + ".slice(0, 8).map((r) => <div key={r.id} className=\"text-center p-3 rounded-lg border bg-muted/30\"><div className=\"text-sm font-medium truncate\">{r.oxideGrade}</div><div className=\"text-lg font-bold\" style={{ color: themeColor }}>&#8377;{r.investmentCr}Cr</div><div className=\"text-xs text-muted-foreground\">{r.application}</div></div>)")
lines.append("            </div>")
lines.append("          </CardContent></Card>")
lines.append("        </div>")
lines.append("      )}")
lines.append("      {activeTab === 'registry' && (")
lines.append("        <div className=\"space-y-4\">")
lines.append("          <div className=\"flex flex-wrap gap-3\">")
lines.append("            <input type=\"text\" placeholder=\"Search ID, batch, city, grade...\" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className=\"px-3 py-2 border rounded-md text-sm flex-1 min-w-[200px]\" />")
lines.append("            <select value={filterZone} onChange={(e) => setFilterZone(e.target.value)} className=\"px-3 py-2 border rounded-md text-sm\"><option value=\"all\">All Zones</option>{zones.map(([z]) => <option key={z} value={z}>{z as string}</option>)}</select>")
lines.append("            <select value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)} className=\"px-3 py-2 border rounded-md text-sm\"><option value=\"all\">All Status</option>{['Delivered','In Transit','Delayed','Processing'].map((s) => <option key={s} value={s}>{s}</option>)}</select>")
lines.append("          </div>")
lines.append("          <div className=\"grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3\">")
lines.append("            {filteredRecords.map((record) => (")
lines.append("              <Card key={record.id} className={record.status === 'Delayed' ? 'border-l-4 border-l-red-500 bg-red-50/30' : ''}>")
lines.append("                <CardContent className=\"pt-4 pb-4\">")
lines.append("                  <div className=\"flex justify-between items-start mb-2\">")
lines.append("                    <div><span className=\"font-semibold text-sm\">{record.id}</span><span className=\"text-xs text-muted-foreground ml-2\">{record.batchNo}</span></div>")
lines.append("                    <div className=\"flex gap-1\"><Badge variant=\"outline\" className={statusColor(record.status)}>{record.status}</Badge><Badge variant=\"outline\" className={priorityColor(record.priority)}>{record.priority}</Badge></div>")
lines.append("                  </div>")
lines.append("                  <div className=\"text-xs space-y-1\">")
lines.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">Grade:</span><span className=\"font-medium\">{record.oxideGrade}</span></div>")
lines.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">Application:</span><span className=\"font-medium\">{record.application}</span></div>")
lines.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">Purity:</span><span className=\"font-medium\">{record.purityPercent}%</span></div>")
lines.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">Investment:</span><span className=\"font-medium\" style={{ color: themeColor }}>&#8377;{record.investmentCr}Cr</span></div>")
lines.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">City:</span><span className=\"font-medium\">{record.city}</span></div>")
lines.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">Route:</span><span className=\"font-medium text-xs\">{record.origin} &#8594; {record.destination}</span></div>")
lines.append("                  </div>")
lines.append("                </CardContent>")
lines.append("              </Card>")
lines.append("            ))}")
lines.append("          </div>")
lines.append("          <div className=\"text-sm text-muted-foreground\">Showing {filteredRecords.length} of {" + VARIABLE_NAME + ".length} records</div>")
lines.append("        </div>")
lines.append("      )}")
lines.append("      {activeTab === 'analytics' && (")
lines.append("        <div className=\"grid grid-cols-1 lg:grid-cols-2 gap-4\">")
lines.append("          <Card><CardHeader><CardTitle className=\"text-base\">Manufacturer Performance</CardTitle></CardHeader><CardContent>")
lines.append("            <div className=\"space-y-2\">")
lines.append("              {(() => { const mfrMap: Record<string, number> = {}; " + VARIABLE_NAME + ".forEach((r) => { mfrMap[r.manufacturer] = (mfrMap[r.manufacturer] || 0) + r.investmentCr; }); return Object.entries(mfrMap).sort((a, b) => b[1] - a[1]).slice(0, 8).map(([mfr, inv]) => { const pct = (inv as number / kpiData.total) * 100; return <div key={mfr} className=\"flex items-center gap-2\"><span className=\"text-xs w-40 truncate\">{mfr as string}</span><div className=\"flex-1 h-2 bg-muted rounded-full\"><div className=\"h-2 rounded-full\" style={{ width: `${pct}%`, backgroundColor: themeColor }} /></div><span className=\"text-xs font-medium\">&#8377;{inv as number}Cr</span></div>; }); })()}")
lines.append("            </div>")
lines.append("          </CardContent></Card>")
lines.append("          <Card><CardHeader><CardTitle className=\"text-base\">Priority Distribution</CardTitle></CardHeader><CardContent>")
lines.append("            <div className=\"grid grid-cols-2 gap-3\">")
lines.append("              {['Critical', 'High', 'Medium', 'Low'].map((p) => { const c = " + VARIABLE_NAME + ".filter((r) => r.priority === p).length; return <div key={p} className={`text-center p-3 rounded-lg border ${priorityColor(p)}`}><div className=\"text-lg font-bold\">{c}</div><div className=\"text-xs\">{p}</div></div>; })}")
lines.append("            </div>")
lines.append("          </CardContent></Card>")
lines.append("          <Card><CardHeader><CardTitle className=\"text-base\">Investment by Zone</CardTitle></CardHeader><CardContent>")
lines.append("            <div className=\"space-y-2\">{(() => { const zInv: Record<string, number> = {}; " + VARIABLE_NAME + ".forEach((r) => { zInv[r.zone] = (zInv[r.zone] || 0) + r.investmentCr; }); return Object.entries(zInv).sort((a, b) => b[1] - a[1]).map(([zone, inv]) => { const pct = (inv as number / kpiData.total) * 100; return <div key={zone} className=\"flex items-center gap-2\"><span className=\"text-xs w-16\">{zone as string}</span><div className=\"flex-1 h-2 bg-muted rounded-full\"><div className=\"h-2 rounded-full\" style={{ width: `${pct}%`, backgroundColor: themeColor }} /></div><span className=\"text-xs font-medium\">&#8377;{inv as number}Cr</span></div>; }); })()}")
lines.append("          </CardContent></Card>")
lines.append("          <Card><CardHeader><CardTitle className=\"text-base\">Purity Distribution</CardTitle></CardHeader><CardContent>")
lines.append("            <div className=\"space-y-2\">")
lines.append("              {(() => { const ranges = { '99.99%+': 0, '99.95-99.98%': 0, '99.6-99.94%': 0, '&lt;99.6%': 0 }; " + VARIABLE_NAME + ".forEach((r) => { if (r.purityPercent >= 99.99) ranges['99.99%+']++; else if (r.purityPercent >= 99.95) ranges['99.95-99.98%']++; else if (r.purityPercent >= 99.6) ranges['99.6-99.94%']++; else ranges['&lt;99.6%']++; }); return (Object.entries(ranges) as [string, number][]).filter(([, v]) => v > 0).map(([range, count]) => { const pct = (count / " + VARIABLE_NAME + ".length) * 100; return <div key={range} className=\"flex items-center gap-2\"><span className=\"text-xs w-24\">{range}</span><div className=\"flex-1 h-2 bg-muted rounded-full\"><div className=\"h-2 rounded-full\" style={{ width: `${pct}%`, backgroundColor: themeColor }} /></div><span className=\"text-xs font-medium\">{count}</span></div>; }); })()}")
lines.append("            </div>")
lines.append("          </CardContent></Card>")
lines.append("        </div>")
lines.append("      )}")
lines.append("      {activeTab === 'insights' && (")
lines.append("        <div className=\"grid grid-cols-1 md:grid-cols-2 gap-4\">")
lines.append("          <Card><CardHeader><CardTitle className=\"text-base\">Supply Chain Intelligence</CardTitle></CardHeader><CardContent><div className=\"space-y-3 text-sm\">")
lines.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-sky-500 bg-sky-50/50\"><div className=\"font-medium\">Solar Glass Demand Surge</div><div className=\"text-xs text-muted-foreground mt-1\">Adani 5GW and Tata Power solar driving low-iron patterned glass &#8594; Saint-Gobain Chennai ramping &#8594; &#8377;820Cr for 8,000 tonnes</div></div>")
lines.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-sky-500 bg-sky-50/50\"><div className=\"font-medium\">Fiber Optic Preform Expansion</div><div className=\"text-xs text-muted-foreground mt-1\">Sterlite 60M fkm programme requires high-purity SiO2 preform &#8594; &#8377;940Cr for OFS Fitel &#8594; MCVD process at 2000&#176;C</div></div>")
lines.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-sky-500 bg-sky-50/50\"><div className=\"font-medium\">Pharma Vial Bottleneck</div><div className=\"text-xs text-muted-foreground mt-1\">Dr Reddys and Sun Pharma Type I borosilicate vial demand &#8594; Gujarat Borosil and Pharma Glass Hyderabad &#8594; &#8377;1,100Cr combined</div></div>")
lines.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-sky-500 bg-sky-50/50\"><div className=\"font-medium\">Monsoon Disruption Alert</div><div className=\"text-xs text-muted-foreground mt-1\">SLG-B2412 GRSE naval porthole delayed &#8594; monsoon Visakhapatnam port congestion &#8594; ASW corvette delivery risk</div></div>")
lines.append("          </div></CardContent></Card>")
lines.append("          <Card><CardHeader><CardTitle className=\"text-base\">Investment Landscape</CardTitle></CardHeader><CardContent><div className=\"space-y-3 text-sm\">")
lines.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-sky-500 bg-sky-50/50\"><div className=\"font-medium\">Total Portfolio: &#8377;{kpiData.total.toLocaleString()} Cr</div><div className=\"text-xs text-muted-foreground mt-1\">Across 14 silica glass grades spanning optical, solar, pharma, telecom, auto, naval and semiconductor &#8594; avg purity {kpiData.avgPurity}%</div></div>")
lines.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-sky-500 bg-sky-50/50\"><div className=\"font-medium\">Critical Priority: 4 Records</div><div className=\"text-xs text-muted-foreground mt-1\">BEL HUD &#8594; Adani solar &#8594; Sterlite fiber &#8594; all flagged critical &#8594; national infrastructure dependent</div></div>")
lines.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-sky-500 bg-sky-50/50\"><div className=\"font-medium\">Top 3 Manufacturers by Investment</div><div className=\"text-xs text-muted-foreground mt-1\">OFS Fitel &#8594; Saint-Gobain &#8594; Asahi India lead &#8594; Gujarat Borosil emerging for specialty borosilicate</div></div>")
lines.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-sky-500 bg-sky-50/50\"><div className=\"font-medium\">Semiconductor and Space</div><div className=\"text-xs text-muted-foreground mt-1\">Wipro semi and ISRO telescope mirror drive high-purity demand &#8594; &#8377;1,260Cr combined for fused quartz and borosilicate</div></div>")
lines.append("          </div></CardContent></Card>")
lines.append("        </div>")
lines.append("      )}")
lines.append("    </div>")
lines.append("  );")
lines.append("}")
lines.append("")

content = "\n".join(lines)

# Validate no malformed entities
import re
bad = re.findall(r'&#(\d+);', content)
for b in bad:
    if int(b) > 99999:
        print(f"WARNING: potentially malformed entity &#x{b};")
    if int(b) > 9999:
        print(f"INFO: entity &#x{b} -> check validity")

with open(OUTPUT, "w") as f:
    f.write(content)

print(f"Generated {OUTPUT} ({len(lines)} lines)")
print(f"Records: {len(RECORDS)}")
print(f"Total investment: {sum(r[8] for r in RECORDS)} Cr")
print(f"Avg purity: {sum(r[6] for r in RECORDS)/len(RECORDS):.2f}%")
