#!/usr/bin/env python3
"""Generate R418a: Magnesia Dolomite Logistics View — fixed template avoiding R417 bugs"""
import os

COMPONENT = "MagnesiaDolomite"
THEME = "magnesia-dolomite"
PREFIX = "MGO"
ICON = "Thermometer"
COLOR = "#dc2626"  # red-600
INTERFACE = "MagnesiaDolomiteRecord"
VAR = "magnesiaDolomiteRecords"

RECORDS = [
    ("MGO-0001", "MGO-B2401", "Mumbai", "Dalmia Cement", "DB-Caustic 70%", "Tata Steel BOF Lining", 96.5, 3.5, 720, "Delivered", "Critical", "Dalmia Cement Mumbai (MH)", "Tata Steel Jamshedpur (JH)", "2026-07-15", 2, "West", "Caustic magnesia 70% for Tata Steel basic oxygen furnace refractory lining &#8594; 90% CaO &#8594; &#8377;720Cr for 8,000 tonnes &#8594; India &#8377;5,800Cr magnesia &#8594; Tata 5 converters &#8594; 3.5 Mohs &#8594; &#8594; Dead burned &#8594; &#8594; 1800&#176;C &#8594; &#8594; Steel"),
    ("MGO-0002", "MGO-B2402", "Bengaluru", "DRDO DMRL", "DB-Fused Cast 98%", "ISRO SRM Nozzle", 98.5, 8.2, 860, "In Transit", "Critical", "DRDO Hyderabad (TG)", "ISRO Sriharikota (AP)", "2026-07-18", 1, "South", "Fused cast magnesia for ISRO PSLV solid rocket motor convergent-divergent nozzle throat insert &#8594; 98% MgO &#8594; &#8377;860Cr for 1,200 tonnes &#8594; India &#8377;6,200Cr fused &#8594; ISRO 40 motors &#8594; 8.2 GPa &#8594; &#8594; Fused cast &#8594; &#8594; 2800&#176;C &#8594; &#8594; Space"),
    ("MGO-0003", "MGO-B2403", "Chennai", "Ramco Magnesite", "DB-Dead Burned 92%", "SAIL Ladle Lining", 92.8, 5.5, 640, "Delivered", "High", "Ramco Salem (TN)", "SAIL Bhilai (CG)", "2026-07-20", 2, "South", "Dead burned magnesia brick for SAIL Bhilai steel ladle slag line and metal line &#8594; 92% MgO &#8594; &#8377;640Cr for 10,000 tonnes &#8594; India &#8377;4,800Cr brick &#8594; SAIL 8 ladles &#8594; 5.5 GPa &#8594; &#8594; Brick &#8594; &#8594; 1600&#176;C &#8594; &#8594; Steel"),
    ("MGO-0004", "MGO-B2404", "Hyderabad", "Premier Magnesite", "DB-Dolomite 58%", "Jindal Steel Sinter", 58.2, 3.8, 520, "Delivered", "Medium", "Premier Hyderabad (TG)", "Jindal Steel Raigarh (CG)", "2026-07-22", 1, "South", "Dolomite sinter feed for Jindal Steel sinter plant flux in blast furnace ironmaking &#8594; 58% MgCO3 &#8594; &#8377;520Cr for 15,000 tonnes &#8594; India &#8377;1,800Cr dolomite &#8594; Jindal 3 furnaces &#8594; 3.8 Mohs &#8594; &#8594; Sinter &#8594; &#8594; 1300&#176;C &#8594; &#8594; Steel"),
    ("MGO-0005", "MGO-B2405", "Kolkata", "Tata Refractories", "DB-Magnesia Carbon 80%", "JSW Steel RH Degasser", 80.5, 6.8, 780, "In Transit", "High", "Tata Refractories Kolkata (WB)", "JSW Steel Vijaynagar (KA)", "2026-07-24", 2, "East", "Magnesia-carbon brick for JSW Steel Ruhrstahl Heraeus degasser snorkel and vessel &#8594; 80% MgO &#8594; &#8377;780Cr for 4,000 tonnes &#8594; India &#8377;6,400Cr MgC &#8594; JSW 6 degassers &#8594; 6.8 GPa &#8594; &#8594; MgO-C &#8594; &#8594; 1650&#176;C &#8594; &#8594; Steel"),
    ("MGO-0006", "MGO-B2406", "Ahmedabad", "Gujarat Magnesite", "DB-Pharm Grade 99%", "Sun Pharma Antacid", 99.2, 4.2, 480, "Delivered", "Medium", "Gujarat Magnesite Rajkot (GJ)", "Sun Pharma Vadodara (GJ)", "2026-07-26", 1, "West", "Pharmaceutical-grade light magnesia for Sun Pharma antacid tablet and laxative formulation &#8594; USP grade &#8594; &#8377;480Cr for 2,000 tonnes &#8594; India &#8377;3,200Cr pharma &#8594; Sun Pharma 600M tabs &#8594; 4.2 Mohs &#8594; &#8594; Light MgO &#8594; &#8594; 350&#176;C &#8594; &#8594; Pharma"),
    ("MGO-0007", "MGO-B2407", "Jaipur", "Rajasthan Minerals", "DB-EPS Wallboard 85%", "Everest Industries Panel", 85.4, 2.8, 380, "In Transit", "Medium", "Rajasthan Minerals Jodhpur (RJ)", "Everest Industries Kolkata (WB)", "2026-07-28", 3, "West", "Calcined magnesia for Everest Industries EPS wallboard fire retardant additive &#8594; 85% MgO &#8594; &#8377;380Cr for 3,000 tonnes &#8594; India &#8377;1,400Cr wallboard &#8594; Everest 200K panels &#8594; 2.8 Mohs &#8594; &#8594; Calcined &#8594; &#8594; 600&#176;C &#8594; &#8594; Construction"),
    ("MGO-0008", "MGO-B2408", "Coimbatore", "TN Minerals Corp", "DB-Animal Feed 96%", "Venkateshwara Hatchery", 96.1, 3.1, 340, "Delivered", "Low", "TN Minerals Salem (TN)", "Venkateshwara Mumbai (MH)", "2026-07-30", 1, "South", "Feed-grade magnesite for Venkateshwara Hatchery poultry feed magnesium supplement &#8594; 96% MgCO3 &#8594; &#8377;340Cr for 5,000 tonnes &#8594; India &#8377;900Cr feed &#8594; Venky 100K tonnes &#8594; 3.1 Mohs &#8594; &#8594; Feed grade &#8594; &#8594; 400&#176;C &#8594; &#8594; Agriculture"),
    ("MGO-0009", "MGO-B2409", "Guwahati", "Assam Dolomite Mine", "DB-Flux Dolomite 42%", "NMDC Iron Ore Sinter", 42.5, 3.5, 280, "Delivered", "Low", "Assam Dolomite Dima Hasao (AS)", "NMDC Donimalai (KA)", "2026-08-01", 5, "East", "Dolomite flux for NMDC Donimalai iron ore sinter plant basicity adjustment &#8594; 42% MgCO3 &#8594; &#8377;280Cr for 20,000 tonnes &#8594; India &#8377;800Cr flux &#8594; NMDC 4 sinter plants &#8594; 3.5 Mohs &#8594; &#8594; Flux &#8594; &#8594; 1200&#176;C &#8594; &#8594; Mining"),
    ("MGO-0010", "MGO-B2410", "Lucknow", "UP Magnesite Ltd", "DB-Chemical 98%", "PI Industries Fertilizer", 98.3, 4.5, 420, "Delivered", "Medium", "UP Magnesite Lucknow (UP)", "PI Industries Hyderabad (TG)", "2026-08-03", 2, "North", "Chemical-grade magnesia for PI Industries magnesium sulphate fertilizer production &#8594; 98% MgO &#8594; &#8377;420Cr for 3,000 tonnes &#8594; India &#8377;2,400Cr chemical &#8594; PI 50K tonnes &#8594; 4.5 Mohs &#8594; &#8594; MgSO4 &#8594; &#8594; 1100&#176;C &#8594; &#8594; Chemical"),
    ("MGO-0011", "MGO-B2411", "Nagpur", "BHEl Refractory Div", "DB-High Temp 97%", "BHEL Boiler Harp", 97.2, 7.5, 680, "In Transit", "High", "BHEL Bhopal (MP)", "BHEL Hyderabad (TG)", "2026-08-05", 2, "West", "High-temperature magnesia-chrome brick for BHEL 660MW supercritical boiler harp tube seal &#8594; 97% MgO &#8594; &#8377;680Cr for 2,500 tonnes &#8594; India &#8377;4,800Cr boiler &#8594; BHEL 20 boilers &#8594; 7.5 GPa &#8594; &#8594; Mag-Chrome &#8594; &#8594; 1400&#176;C &#8594; &#8594; Power"),
    ("MGO-0012", "MGO-B2412", "Visakhapatnam", "NALCO Refractory", "DB-Naval Insulator 95%", "GRSE Frigate Bulkhead", 95.8, 6.2, 540, "Delayed", "High", "NALCO Vishakapatnam (AP)", "GRSE Kolkata (WB)", "2026-08-07", 2, "East", "Magnesia insulating firebrick for GRSE Nilgiri-class frigate engine room bulkhead thermal shield &#8594; 95% MgO &#8594; &#8377;540Cr for 1,500 tonnes &#8597; India &#8377;3,600Cr naval &#8594; GRSE 7 vessels &#8594; 6.2 GPa &#8594; &#8594; IFB &#8594; &#8594; 1000&#176;C &#8594; &#8594; Naval"),
    ("MGO-0013", "MGO-B2413", "Bhopal", "IGCAR Ceramics", "DB-Nuclear 99.5%", "BHAVINI Breeder Vessel", 99.5, 8.8, 940, "In Transit", "Critical", "IGCAR Kalpakkam (TN)", "BHAVINI Kalpakkam (TN)", "2026-08-09", 1, "Central", "Ultra-high purity magnesia for BHAVINI PFBR primary sodium circuit ceramic insulation &#8594; 99.5% MgO &#8594; &#8377;940Cr for 800 tonnes &#8594; India &#8377;8,200Cr nuclear &#8594; BHAVINI 2 reactors &#8594; 8.8 GPa &#8594; &#8594; Nuclear grade &#8594; &#8594; 1100&#176;C &#8594; &#8594; Nuclear"),
    ("MGO-0014", "MGO-B2414", "Rourkela", "SAIL Refractory", "DB-Ladle Repair 90%", "Tata Steel Tundish", 90.5, 5.8, 480, "Delivered", "Medium", "SAIL Rourkela (OD)", "Tata Steel Kalinganagar (OD)", "2026-08-11", 1, "East", "Magnesia repair mix for Tata Steel Kalinganagar continuous casting tundish working lining &#8594; 90% MgO &#8594; &#8377;480Cr for 4,000 tonnes &#8594; India &#8377;2,800Cr repair &#8594; Tata 6 tundishes &#8594; 5.8 GPa &#8594; &#8594; Repair mix &#8594; &#8594; 1550&#176;C &#8594; &#8594; Steel"),
]

OUTPUT = os.path.join("/home/z/my-project/src/components/modules", f"{THEME}-logistics-view.tsx")

L = []
L.append('"use client";')
L.append("")
L.append("import React, { useState, useMemo } from 'react';")
L.append("import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';")
L.append("import { Badge } from '@/components/ui/badge';")
L.append("import { PageHeader } from '@/components/shared';")
L.append("import { " + ICON + " } from 'lucide-react';")
L.append("")
L.append("interface " + INTERFACE + " {")
L.append("  id: string; batchNo: string; city: string; manufacturer: string; oxideGrade: string;")
L.append("  application: string; purityPercent: number; hardnessGPa: number; investmentCr: number;")
L.append("  status: string; priority: string; origin: string; destination: string;")
L.append("  shipDate: string; transitDays: number; zone: string; remarks: string;")
L.append("}")
L.append("")
L.append("const " + VAR + ": " + INTERFACE + "[] = [")
for i, rec in enumerate(RECORDS):
    rid,batch,city,mfr,grade,app,pur,hard,inv,stat,pri,orig,dest,ship,trans,zone,rem = rec
    L.append("  { id: '" + rid + "', batchNo: '" + batch + "', city: '" + city + "', manufacturer: '" + mfr + "', oxideGrade: '" + grade + "', application: '" + app + "', purityPercent: " + str(pur) + ", hardnessGPa: " + str(hard) + ", investmentCr: " + str(inv) + ", status: '" + stat + "', priority: '" + pri + "', origin: '" + orig + "', destination: '" + dest + "', shipDate: '" + ship + "', transitDays: " + str(trans) + ", zone: '" + zone + "', remarks: '" + rem + "' },")
L.append("];")
L.append("")
L.append("export default function " + COMPONENT + "LogisticsView() {")
L.append("  const [activeTab, setActiveTab] = useState<string>('dashboard');")
L.append("  const [searchTerm, setSearchTerm] = useState<string>('');")
L.append("  const [filterZone, setFilterZone] = useState<string>('all');")
L.append("  const [filterStatus, setFilterStatus] = useState<string>('all');")
L.append("")
L.append("  const tabs = [")
L.append("    { id: 'dashboard', label: 'Dashboard', icon: " + ICON + " },")
L.append("    { id: 'registry', label: 'Registry', icon: " + ICON + " },")
L.append("    { id: 'analytics', label: 'Analytics', icon: " + ICON + " },")
L.append("    { id: 'insights', label: 'Insights', icon: " + ICON + " },")
L.append("  ];")
L.append("")
L.append("  const filteredRecords = useMemo(() => {")
L.append("    return " + VAR + ".filter((r) => {")
L.append("      const matchSearch = searchTerm === '' ||")
L.append("        r.id.toLowerCase().includes(searchTerm.toLowerCase()) ||")
L.append("        r.batchNo.toLowerCase().includes(searchTerm.toLowerCase()) ||")
L.append("        r.city.toLowerCase().includes(searchTerm.toLowerCase()) ||")
L.append("        r.manufacturer.toLowerCase().includes(searchTerm.toLowerCase()) ||")
L.append("        r.oxideGrade.toLowerCase().includes(searchTerm.toLowerCase()) ||")
L.append("        r.application.toLowerCase().includes(searchTerm.toLowerCase());")
L.append("      const matchZone = filterZone === 'all' || r.zone === filterZone;")
L.append("      const matchStatus = filterStatus === 'all' || r.status === filterStatus;")
L.append("      return matchSearch && matchZone && matchStatus;")
L.append("    });")
L.append("  }, [searchTerm, filterZone, filterStatus]);")
L.append("")
L.append("  const zones = useMemo(() => {")
L.append("    const zMap: Record<string, number> = {};")
L.append("    " + VAR + ".forEach((r) => { zMap[r.zone] = (zMap[r.zone] || 0) + 1; });")
L.append("    return Object.entries(zMap).sort((a, b) => b[1] - a[1]);")
L.append("  }, []);")
L.append("")
L.append("  const kpiData = useMemo(() => {")
L.append("    const total = " + VAR + ".reduce((s: number, r) => s + r.investmentCr, 0);")
L.append("    const avgPurity = " + VAR + ".reduce((s: number, r) => s + r.purityPercent, 0) / " + VAR + ".length;")
L.append("    const delayed = " + VAR + ".filter((r) => r.status === 'Delayed').length;")
L.append("    const critical = " + VAR + ".filter((r) => r.priority === 'Critical').length;")
L.append("    return { total, avgPurity: avgPurity.toFixed(2), delayed, critical };")
L.append("  }, []);")
L.append("")
L.append("  const statusColor = (status: string) => {")
L.append("    switch (status) {")
L.append("      case 'Delivered': return 'bg-green-500/20 text-green-700 border-green-500/30';")
L.append("      case 'In Transit': return 'bg-blue-500/20 text-blue-700 border-blue-500/30';")
L.append("      case 'Delayed': return 'bg-red-500/20 text-red-700 border-red-500/30';")
L.append("      case 'Processing': return 'bg-yellow-500/20 text-yellow-700 border-yellow-500/30';")
L.append("      default: return 'bg-gray-500/20 text-gray-700 border-gray-500/30';")
L.append("    }")
L.append("  };")
L.append("")
L.append("  const priorityColor = (priority: string) => {")
L.append("    switch (priority) {")
L.append("      case 'Critical': return 'bg-red-500/20 text-red-700 border-red-500/30';")
L.append("      case 'High': return 'bg-orange-500/20 text-orange-700 border-orange-500/30';")
L.append("      case 'Medium': return 'bg-yellow-500/20 text-yellow-700 border-yellow-500/30';")
L.append("      case 'Low': return 'bg-green-500/20 text-green-700 border-green-500/30';")
L.append("      default: return 'bg-gray-500/20 text-gray-700 border-gray-500/30';")
L.append("    }")
L.append("  };")
L.append("")
L.append("  const themeColor = '" + COLOR + "';")
L.append("  return (")
L.append("    <div className=\"space-y-6 p-6\">")
L.append("      <PageHeader title=\"Magnesia Dolomite Logistics\" description=\"Indian magnesia and dolomite refractory, steel flux, pharmaceutical, nuclear and construction supply chain tracking across 14 grades\" />")
L.append("      <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4\">")
L.append("        <Card className=\"border-l-4 border-l-red-500\"><CardContent className=\"pt-6\"><div className=\"text-2xl font-bold text-red-600\">{kpiData.total.toLocaleString()} Cr</div><div className=\"text-xs text-muted-foreground mt-1\">Total Investment</div></CardContent></Card>")
L.append("        <Card className=\"border-l-4 border-l-red-500\"><CardContent className=\"pt-6\"><div className=\"text-2xl font-bold text-red-600\">{kpiData.avgPurity}%</div><div className=\"text-xs text-muted-foreground mt-1\">Avg Purity</div></CardContent></Card>")
L.append("        <Card className=\"border-l-4 border-l-red-500\"><CardContent className=\"pt-6\"><div className=\"text-2xl font-bold text-red-600\">{kpiData.delayed}</div><div className=\"text-xs text-muted-foreground mt-1\">Delayed Batches</div></CardContent></Card>")
L.append("        <Card className=\"border-l-4 border-l-red-500\"><CardContent className=\"pt-6\"><div className=\"text-2xl font-bold text-red-600\">{kpiData.critical}</div><div className=\"text-xs text-muted-foreground mt-1\">Critical Records</div></CardContent></Card>")
L.append("      </div>")
L.append("      <div className=\"flex flex-wrap gap-2 border-b pb-2\">")
L.append("        {tabs.map((tab) => (")
L.append("          <button key={tab.id} onClick={() => setActiveTab(tab.id)} className={`px-4 py-2 rounded-t-md text-sm font-medium transition-colors ${activeTab === tab.id ? 'bg-red-500 text-white shadow-md' : 'bg-muted text-muted-foreground hover:bg-muted/80'}`}>")
L.append("            {tab.label}")
L.append("          </button>")
L.append("        ))}")
L.append("      </div>")
# Dashboard tab
L.append("      {activeTab === 'dashboard' && (")
L.append("        <div className=\"grid grid-cols-1 lg:grid-cols-2 gap-4\">")
L.append("          <Card><CardHeader><CardTitle className=\"text-base\">Zone Distribution</CardTitle></CardHeader><CardContent>")
L.append("            <div className=\"space-y-2\">{zones.map(([zone, count]) => { const pct = (count as number / " + VAR + ".length) * 100; return <div key={zone} className=\"flex items-center gap-2\"><span className=\"text-xs w-16 text-muted-foreground\">{zone as string}</span><div className=\"flex-1 h-2 bg-muted rounded-full\"><div className=\"h-2 rounded-full\" style={{ width: `${pct}%`, backgroundColor: themeColor }} /></div><span className=\"text-xs font-medium w-8\">{count as number}</span></div>; })}</div>")
L.append("          </CardContent></Card>")
L.append("          <Card><CardHeader><CardTitle className=\"text-base\">Status Overview</CardTitle></CardHeader><CardContent>")
L.append("            <div className=\"grid grid-cols-2 gap-3\">")
L.append("              {['Delivered', 'In Transit', 'Delayed', 'Processing'].map((s) => { const c = " + VAR + ".filter((r) => r.status === s).length; return <div key={s} className={`text-center p-3 rounded-lg border ${statusColor(s)}`}><div className=\"text-lg font-bold\">{c}</div><div className=\"text-xs\">{s}</div></div>; })}")
L.append("            </div>")
L.append("          </CardContent></Card>")
L.append("          <Card className=\"lg:col-span-2\"><CardHeader><CardTitle className=\"text-base\">Investment by Grade (Top 8)</CardTitle></CardHeader><CardContent>")
L.append("            <div className=\"grid grid-cols-2 md:grid-cols-4 gap-3\">")
L.append("              {" + VAR + ".slice(0, 8).map((r) => <div key={r.id} className=\"text-center p-3 rounded-lg border bg-muted/30\"><div className=\"text-sm font-medium truncate\">{r.oxideGrade}</div><div className=\"text-lg font-bold\" style={{ color: themeColor }}>&#8377;{r.investmentCr}Cr</div><div className=\"text-xs text-muted-foreground\">{r.application}</div></div>)}")
L.append("            </div>")
L.append("          </CardContent></Card>")
L.append("        </div>")
L.append("      )}")
# Registry tab
L.append("      {activeTab === 'registry' && (")
L.append("        <div className=\"space-y-4\">")
L.append("          <div className=\"flex flex-wrap gap-3\">")
L.append("            <input type=\"text\" placeholder=\"Search ID, batch, city, grade...\" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className=\"px-3 py-2 border rounded-md text-sm flex-1 min-w-[200px]\" />")
L.append("            <select value={filterZone} onChange={(e) => setFilterZone(e.target.value)} className=\"px-3 py-2 border rounded-md text-sm\"><option value=\"all\">All Zones</option>{zones.map(([z]) => <option key={z} value={z}>{z as string}</option>)}</select>")
L.append("            <select value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)} className=\"px-3 py-2 border rounded-md text-sm\"><option value=\"all\">All Status</option>{['Delivered','In Transit','Delayed','Processing'].map((s) => <option key={s} value={s}>{s}</option>)}</select>")
L.append("          </div>")
L.append("          <div className=\"grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3\">")
L.append("            {filteredRecords.map((record) => (")
L.append("              <Card key={record.id} className={record.status === 'Delayed' ? 'border-l-4 border-l-red-500 bg-red-50/30' : ''}>")
L.append("                <CardContent className=\"pt-4 pb-4\">")
L.append("                  <div className=\"flex justify-between items-start mb-2\">")
L.append("                    <div><span className=\"font-semibold text-sm\">{record.id}</span><span className=\"text-xs text-muted-foreground ml-2\">{record.batchNo}</span></div>")
L.append("                    <div className=\"flex gap-1\"><Badge variant=\"outline\" className={statusColor(record.status)}>{record.status}</Badge><Badge variant=\"outline\" className={priorityColor(record.priority)}>{record.priority}</Badge></div>")
L.append("                  </div>")
L.append("                  <div className=\"text-xs space-y-1\">")
L.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">Grade:</span><span className=\"font-medium\">{record.oxideGrade}</span></div>")
L.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">Application:</span><span className=\"font-medium\">{record.application}</span></div>")
L.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">Purity:</span><span className=\"font-medium\">{record.purityPercent}%</span></div>")
L.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">Investment:</span><span className=\"font-medium\" style={{ color: themeColor }}>&#8377;{record.investmentCr}Cr</span></div>")
L.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">City:</span><span className=\"font-medium\">{record.city}</span></div>")
L.append("                    <div className=\"flex justify-between\"><span className=\"text-muted-foreground\">Route:</span><span className=\"font-medium text-xs\">{record.origin} &#8594; {record.destination}</span></div>")
L.append("                  </div>")
L.append("                </CardContent>")
L.append("              </Card>")
L.append("            ))}")
L.append("          </div>")
L.append("          <div className=\"text-sm text-muted-foreground\">Showing {filteredRecords.length} of {" + VAR + ".length} records</div>")
L.append("        </div>")
L.append("      )}")
# Analytics tab
L.append("      {activeTab === 'analytics' && (")
L.append("        <div className=\"grid grid-cols-1 lg:grid-cols-2 gap-4\">")
L.append("          <Card><CardHeader><CardTitle className=\"text-base\">Manufacturer Performance</CardTitle></CardHeader><CardContent>")
L.append("            <div className=\"space-y-2\">")
L.append("              {(() => { const mfrMap: Record<string, number> = {}; " + VAR + ".forEach((r) => { mfrMap[r.manufacturer] = (mfrMap[r.manufacturer] || 0) + r.investmentCr; }); return Object.entries(mfrMap).sort((a, b) => b[1] - a[1]).slice(0, 8).map(([mfr, inv]) => { const pct = (inv as number / kpiData.total) * 100; return <div key={mfr} className=\"flex items-center gap-2\"><span className=\"text-xs w-40 truncate\">{mfr as string}</span><div className=\"flex-1 h-2 bg-muted rounded-full\"><div className=\"h-2 rounded-full\" style={{ width: `${pct}%`, backgroundColor: themeColor }} /></div><span className=\"text-xs font-medium\">&#8377;{inv as number}Cr</span></div>; }); })()}")
L.append("            </div>")
L.append("          </CardContent></Card>")
L.append("          <Card><CardHeader><CardTitle className=\"text-base\">Priority Distribution</CardTitle></CardHeader><CardContent>")
L.append("            <div className=\"grid grid-cols-2 gap-3\">")
L.append("              {['Critical', 'High', 'Medium', 'Low'].map((p) => { const c = " + VAR + ".filter((r) => r.priority === p).length; return <div key={p} className={`text-center p-3 rounded-lg border ${priorityColor(p)}`}><div className=\"text-lg font-bold\">{c}</div><div className=\"text-xs\">{p}</div></div>; })}")
L.append("            </div>")
L.append("          </CardContent></Card>")
L.append("          <Card><CardHeader><CardTitle className=\"text-base\">Investment by Zone</CardTitle></CardHeader><CardContent>")
L.append("            <div className=\"space-y-2\">{(() => { const zInv: Record<string, number> = {}; " + VAR + ".forEach((r) => { zInv[r.zone] = (zInv[r.zone] || 0) + r.investmentCr; }); return Object.entries(zInv).sort((a, b) => b[1] - a[1]).map(([zone, inv]) => { const pct = (inv as number / kpiData.total) * 100; return <div key={zone} className=\"flex items-center gap-2\"><span className=\"text-xs w-16\">{zone as string}</span><div className=\"flex-1 h-2 bg-muted rounded-full\"><div className=\"h-2 rounded-full\" style={{ width: `${pct}%`, backgroundColor: themeColor }} /></div><span className=\"text-xs font-medium\">&#8377;{inv as number}Cr</span></div>; }); })()}</div>")
L.append("          </CardContent></Card>")
L.append("          <Card><CardHeader><CardTitle className=\"text-base\">Purity Distribution</CardTitle></CardHeader><CardContent>")
L.append("            <div className=\"space-y-2\">")
L.append("              {(() => { const ranges = { '99%+': 0, '95-98.9%': 0, '90-94.9%': 0, '<90%': 0 }; " + VAR + ".forEach((r) => { if (r.purityPercent >= 99) ranges['99%+']++; else if (r.purityPercent >= 95) ranges['95-98.9%']++; else if (r.purityPercent >= 90) ranges['90-94.9%']++; else ranges['<90%']++; }); return (Object.entries(ranges) as [string, number][]).filter(([, v]) => v > 0).map(([range, count]) => { const pct = (count / " + VAR + ".length) * 100; return <div key={range} className=\"flex items-center gap-2\"><span className=\"text-xs w-24\">{range}</span><div className=\"flex-1 h-2 bg-muted rounded-full\"><div className=\"h-2 rounded-full\" style={{ width: `${pct}%`, backgroundColor: themeColor }} /></div><span className=\"text-xs font-medium\">{count}</span></div>; }); })()}")
L.append("            </div>")
L.append("          </CardContent></Card>")
L.append("        </div>")
L.append("      )}")
# Insights tab
L.append("      {activeTab === 'insights' && (")
L.append("        <div className=\"grid grid-cols-1 md:grid-cols-2 gap-4\">")
L.append("          <Card><CardHeader><CardTitle className=\"text-base\">Supply Chain Intelligence</CardTitle></CardHeader><CardContent><div className=\"space-y-3 text-sm\">")
L.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-red-500 bg-red-50/50\"><div className=\"font-medium\">Nuclear Ceramics Demand</div><div className=\"text-xs text-muted-foreground mt-1\">BHAVINI PFBR and IGCAR dual programme driving 99.5%+ nuclear magnesia &#8594; &#8377;940Cr for 800 tonnes &#8594; highest purity segment</div></div>")
L.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-red-500 bg-red-50/50\"><div className=\"font-medium\">Steel Refractory Cycle</div><div className=\"text-xs text-muted-foreground mt-1\">Tata Steel BOF + SAIL ladle + JSW degasser + Tata tundish form &#8594; &#8377;2,620Cr combined &#8594; cyclical lining replacement demand</div></div>")
L.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-red-500 bg-red-50/50\"><div className=\"font-medium\">Space Programme Growth</div><div className=\"text-xs text-muted-foreground mt-1\">ISRO PSLV and GSLV expanded launch cadence driving fused cast magnesia nozzle demand &#8594; &#8377;860Cr for DRDO/ISRO</div></div>")
L.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-red-500 bg-red-50/50\"><div className=\"font-medium\">Monsoon Disruption Alert</div><div className=\"text-xs text-muted-foreground mt-1\">MGO-B2412 GRSE frigate bulkhead delayed &#8594; monsoon Visakhapatnam port congestion &#8594; Nilgiri-class delivery schedule at risk</div></div>")
L.append("          </div></CardContent></Card>")
L.append("          <Card><CardHeader><CardTitle className=\"text-base\">Investment Landscape</CardTitle></CardHeader><CardContent><div className=\"space-y-3 text-sm\">")
L.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-red-500 bg-red-50/50\"><div className=\"font-medium\">Total Portfolio: &#8377;{kpiData.total.toLocaleString()} Cr</div><div className=\"text-xs text-muted-foreground mt-1\">Across 14 magnesia and dolomite grades spanning steel, space, nuclear, pharma, construction and naval &#8594; avg purity {kpiData.avgPurity}%</div></div>")
L.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-red-500 bg-red-50/50\"><div className=\"font-medium\">Critical Priority: 4 Records</div><div className=\"text-xs text-muted-foreground mt-1\">Tata Steel BOF &#8594; ISRO nozzle &#8594; BHEL boiler &#8594; BHAVINI breeder &#8594; national infrastructure dependent</div></div>")
L.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-red-500 bg-red-50/50\"><div className=\"font-medium\">Top Manufacturers</div><div className=\"text-xs text-muted-foreground mt-1\">IGCAR &#8594; DRDO &#8594; BHEL lead R&amp;D demand &#8594; Dalmia &#8594; Ramco &#8594; Tata Refractories drive commercial</div></div>")
L.append("            <div className=\"p-3 rounded-lg border-l-4 border-l-red-500 bg-red-50/50\"><div className=\"font-medium\">Regional Concentration</div><div className=\"text-xs text-muted-foreground mt-1\">South zone dominates with Chennai &#8594; Salem &#8594; Hyderabad &#8594; Kalpakkam supply &#8594; West zone Gujarat emerging</div></div>")
L.append("          </div></CardContent></Card>")
L.append("        </div>")
L.append("      )}")
L.append("    </div>")
L.append("  );")
L.append("}")
L.append("")

content = "\n".join(L)

# Validate entities
import re
bad = [e for e in re.findall(r'&#(\d+);', content) if int(e) > 9999]
if bad:
    print(f"WARNING: bad entities: {bad}")
else:
    print(f"OK: {len(re.findall(r'&#(\d+);', content))} entities, all clean")

with open(OUTPUT, "w") as f:
    f.write(content)
print(f"Generated {OUTPUT} ({len(L)} lines)")
print(f"Records: {len(RECORDS)}, Total: {sum(r[8] for r in RECORDS)} Cr, Avg purity: {sum(r[6] for r in RECORDS)/len(RECORDS):.2f}%")
