#!/usr/bin/env python3
"""Generate R168: Warehouse Safety & Compliance Management module (~1150 lines)"""

LINES = []

def w(line=""):
    LINES.append(line)

w("'use client'")
w()
w("import React, { useState, useEffect, useMemo } from 'react'")
w("import {")
w("  ShieldAlert, ShieldCheck, ShieldX, TriangleAlert, CheckCircle2, XCircle,")
w("  Thermometer, Activity, MapPin, Clock, BarChart3, TrendingUp, TrendingDown,")
w("  Eye, ChevronLeft, ChevronRight, ChevronDown, ChevronUp,")
w("  Wrench, Play, Pause, RefreshCw, Filter,")
w("  Signal, Gauge, Cpu, ArrowUpDown,")
w("  FireExtinguisher, HardHat, Flame, Siren, HeartPulse, Zap,")
w("  Users, FileText, CalendarDays, AlertTriangle, ClipboardCheck, CircleDot, Award, BookOpen")
w("} from 'lucide-react'")
w("import {")
w("  ComposedChart, Bar, Line, Area, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer,")
w("  PieChart, Pie, Cell, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar,")
w("  AreaChart, BarChart")
w("} from 'recharts'")
w()
w("// ============================================================")
w("// TYPES")
w("// ============================================================")
w()
w("interface SafetyIncident {")
w("  id: string; type: string; severity: string;")
w("  warehouse: string; zone: string;")
w("  title: string; description: string;")
w("  reportedBy: string; reportedAt: string;")
w("  status: string; rootCause: string;")
w("  correctiveAction: string;")
w("  injuredCount: number; nearMiss: boolean;")
w("  resolvedAt: string | null;")
w("  complianceRef: string;")
w("  riskScore: number;")
w("}")
w()
w("interface ComplianceAudit {")
w("  id: string; name: string; type: string;")
w("  warehouse: string; auditor: string;")
w("  status: string; score: number;")
w("  totalChecks: number; passedChecks: number;")
w("  failedChecks: number; criticalFinds: number;")
w("  scheduledDate: string; completedDate: string | null;")
w("  nextAudit: string; category: string;")
w("}")
w()
w("interface SafetyEquipment {")
w("  id: string; name: string; type: string;")
w("  warehouse: string; zone: string;")
w("  status: string; lastInspection: string;")
w("  nextInspection: string; expiryDate: string;")
w("  complianceStatus: string;")
w("  condition: number;")
w("}")
w()
w("interface TrainingRecord {")
w("  id: string; course: string; type: string;")
w("  warehouse: string; instructor: string;")
w("  status: string; attendees: number;")
w("  completedAttendees: number; passRate: number;")
w("  scheduledDate: string; duration: number;")
w("  certification: string;")
w("}")
w()
w("interface SafetyInspection {")
w("  id: string; area: string; type: string;")
w("  warehouse: string; inspector: string;")
w("  status: string; score: number;")
w("  totalItems: number; passedItems: number;")
w("  failedItems: number; findings: string;")
w("  completedDate: string;")
w("}")
w()
w("function seededRandom(seed: number): () => number {")
w("  let s = seed % 2147483647")
w("  if (s <= 0) s += 2147483646")
w("  return () => { s = (s * 16807) % 2147483647; return (s - 1) / 2147483646 }")
w("}")
w()
w("function generateData() {")
w("  const rng = seededRandom(168168)")
w("  const r = (min: number, max: number) => Math.floor(rng() * (max - min + 1)) + min")
w("  const rf = (min: number, max: number) => +(rng() * (max - min) + min).toFixed(1)")
w("  const pick = <T,>(arr: T[]): T => arr[Math.floor(rng() * arr.length)]")
w()
w("  const warehouses = ['WH-Mumbai-01','WH-Delhi-02','WH-Bengaluru-03','WH-Chennai-04','WH-Hyderabad-05','WH-Pune-06','WH-Kolkata-07','WH-Jaipur-08']")
w("  const zones = ['Zone-A','Zone-B','Zone-C','Zone-D','Zone-E']")
w("  const incidentTypes = ['Slip/Trip/Fall','Forklift Incident','Fire/Smoke','Chemical Spill','Equipment Malfunction','Electrical Hazard','Fall from Height','Confined Space','Manual Handling','Vehicle Collision']")
w("  const severities = ['critical','major','minor','near-miss']")
w("  const incidentStatuses = ['open','investigating','resolved','closed','escalated']")
w("  const auditTypes = ['Safety Compliance','Fire Safety','Environmental','OSHA','ISO 45001','Internal Audit']")
w("  const auditCategories = ['regulatory','voluntary','internal','customer']")
w("  const equipmentTypes = ['Fire Extinguisher','First Aid Kit','Safety Harness','Hard Hat','Safety Goggles','Emergency Exit Sign','Smoke Detector','Sprinkler System','Spill Kit','AED Defibrillator']")
w("  const courseTypes = ['Fire Safety','Forklift Operation','First Aid','Chemical Handling','Fall Protection','PPE Usage','Emergency Evacuation','Hazard Communication']")
w("  const inspectionTypes = ['Daily Safety Walk','Weekly Inspection','Monthly Audit','Annual Review','Spot Check']")
w("  const auditStatuses = ['scheduled','in_progress','completed','overdue']")
w("  const complianceStatuses = ['compliant','non-compliant','expiring','pending']")
w("  const inspectors = ['Inspector-01','Inspector-02','Inspector-03','Inspector-04']")
w("  const auditors = ['Auditor-Alpha','Auditor-Beta','Auditor-Gamma','Auditor-Delta']")
w("  const instructors = ['Trainer-01','Trainer-02','Trainer-03']")
w("  const regulations = ['OSHA 1910','Factories Act 1948','BIS Standards','ISO 45001:2018','NFPA 101','MSHA Regulations']")
w()
w("  const incidents: SafetyIncident[] = Array.from({ length: 60 }, (_, i) => {")
w("    const st = pick(incidentStatuses)")
w("    const sev = pick(severities)")
w("    return {")
w("      id: `INC-${String(i + 1).padStart(4, '0')}`,")
w("      type: pick(incidentTypes),")
w("      severity: sev,")
w("      warehouse: pick(warehouses),")
w("      zone: pick(zones),")
w("      title: `${pick(incidentTypes)} in ${pick(zones).replace('Zone-','Zone ')}`,")
w("      description: `${pick(incidentTypes)} reported during operations. ${sev === 'near-miss' ? 'No injury — near miss event.' : 'Investigation ' + st + '.'}`,")
w("      reportedBy: `Employee-${String(r(100, 500)).padStart(4,'0')}`,")
w("      reportedAt: `${r(1,90)} days ago`,")
w("      status: st,")
w("      rootCause: st !== 'open' ? pick(['Equipment failure','Human error','Process gap','Environmental','Training deficiency']) : '—',")
w("      correctiveAction: st !== 'open' ? pick(['Replace equipment','Update SOP','Additional training','Install guard','Repair required']) : '—',")
w("      injuredCount: sev === 'near-miss' ? 0 : sev === 'minor' ? r(0, 1) : r(1, 3),")
w("      nearMiss: sev === 'near-miss',")
w("      resolvedAt: st === 'resolved' || st === 'closed' ? `${r(1,30)} days ago` : null,")
w("      complianceRef: pick(regulations),")
w("      riskScore: sev === 'critical' ? r(80, 100) : sev === 'major' ? r(50, 79) : sev === 'minor' ? r(20, 49) : r(5, 19),")
w("    }")
w("  })")
w()
w("  const audits: ComplianceAudit[] = Array.from({ length: 30 }, (_, i) => {")
w("    const st = pick(auditStatuses)")
w("    const total = r(20, 80)")
w("    const passed = st === 'completed' ? r(Math.floor(total * 0.6), total) : st === 'in_progress' ? r(10, total) : r(0, 10)")
w("    return {")
w("      id: `AUD-${String(i + 1).padStart(4, '0')}`,")
w("      name: `${pick(auditTypes)} — ${pick(warehouses).replace('WH-','')}`,")
w("      type: pick(auditTypes),")
w("      warehouse: pick(warehouses),")
w("      auditor: pick(auditors),")
w("      status: st,")
w("      score: st === 'completed' ? r(55, 98) : st === 'in_progress' ? r(30, 80) : 0,")
w("      totalChecks: total,")
w("      passedChecks: passed,")
w("      failedChecks: st === 'completed' ? total - passed : 0,")
w("      criticalFinds: st === 'completed' ? r(0, 5) : 0,")
w("      scheduledDate: `${r(1,60)} days ago`,")
w("      completedDate: st === 'completed' ? `${r(1,30)} days ago` : null,")
w("      nextAudit: `${r(10,180)} days`,")
w("      category: pick(auditCategories),")
w("    }")
w("  })")
w()
w("  const equipment: SafetyEquipment[] = Array.from({ length: 80 }, (_, i) => {")
w("    const cs = pick(complianceStatuses)")
w("    return {")
w("      id: `EQ-${String(i + 1).padStart(4, '0')}`,")
w("      name: `${pick(equipmentTypes)}-${String(i + 1).padStart(3,'0')}`,")
w("      type: pick(equipmentTypes),")
w("      warehouse: pick(warehouses),")
w("      zone: pick(zones),")
w("      status: cs === 'non-compliant' ? 'flagged' : cs === 'expiring' ? 'warning' : 'ok',")
w("      lastInspection: `${r(1,60)} days ago`,")
w("      nextInspection: `${r(1,90)} days`,")
w("      expiryDate: `${r(1,365)} days`,")
w("      complianceStatus: cs,")
w("      condition: rf(40, 100),")
w("    }")
w("  })")
w()
w("  const trainings: TrainingRecord[] = Array.from({ length: 25 }, (_, i) => {")
w("    const st = pick(['completed','in_progress','scheduled','cancelled'])")
w("    const att = r(10, 60)")
w("    return {")
w("      id: `TRN-${String(i + 1).padStart(4, '0')}`,")
w("      course: pick(courseTypes),")
w("      type: pick(['mandatory','refresher','certification','induction']),")
w("      warehouse: pick(warehouses),")
w("      instructor: pick(instructors),")
w("      status: st,")
w("      attendees: att,")
w("      completedAttendees: st === 'completed' ? att : st === 'in_progress' ? r(5, att) : 0,")
w("      passRate: st === 'completed' ? r(70, 100) : 0,")
w("      scheduledDate: `${r(1,30)} days ago`,")
w("      duration: r(30, 480),")
w("      certification: pick(['OSHA 10-Hour','OSHA 30-Hour','First Aid Cert','Forklift License','Fire Warden','Chemical Handler']),")
w("    }")
w("  })")
w()
w("  const inspections: SafetyInspection[] = Array.from({ length: 20 }, (_, i) => {")
w("    const st = pick(['completed','completed','completed','in_progress','scheduled'])")
w("    const total = r(15, 50)")
w("    const passed = st === 'completed' ? r(Math.floor(total * 0.7), total) : r(5, total)")
w("    return {")
w("      id: `INSP-${String(i + 1).padStart(4, '0')}`,")
w("      area: pick(zones),")
w("      type: pick(inspectionTypes),")
w("      warehouse: pick(warehouses),")
w("      inspector: pick(inspectors),")
w("      status: st,")
w("      score: st === 'completed' ? r(60, 100) : 0,")
w("      totalItems: total,")
w("      passedItems: passed,")
w("      failedItems: total - passed,")
w("      findings: pick(['No critical findings','Minor issues found','Guardrail damaged','Lighting insufficient','Spill kit expired','Exit blocked','Signage missing','PPE non-compliance']),")
w("      completedDate: st === 'completed' ? `${r(1,15)} days ago` : '—',")
w("    }")
w("  })")
w()
w("  // KPIs")
w("  const openIncidents = incidents.filter(i => i.status === 'open' || i.status === 'investigating' || i.status === 'escalated').length")
w("  const criticalIncidents = incidents.filter(i => i.severity === 'critical').length")
w("  const avgAuditScore = +(audits.filter(a => a.status === 'completed').reduce((s, a) => s + a.score, 0) / Math.max(audits.filter(a => a.status === 'completed').length, 1)).toFixed(1)")
w("  const nonCompliantEquip = equipment.filter(e => e.complianceStatus === 'non-compliant').length")
w("  const daysWithoutIncident = r(12, 120)")
w("  const trainingCompletion = +((trainings.filter(t => t.status === 'completed').length / trainings.length) * 100).toFixed(1)")
w()
w("  // Monthly incident trend")
w("  const monthlyData = Array.from({ length: 12 }, (_, i) => ({")
w("    month: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i],")
w("    incidents: r(3, 18),")
w("    resolved: r(2, 16),")
w("    nearMisses: r(1, 8),")
w("    trainingHours: r(20, 120),")
w("    auditScore: r(60, 98),")
w("  }))")
w()
w("  // Incident type distribution")
w("  const typeCounts: Record<string, number> = {}")
w("  incidents.forEach(i => { typeCounts[i.type] = (typeCounts[i.type] || 0) + 1 })")
w("  const typePieData = Object.entries(typeCounts).map(([name, value]) => ({ name: name.split('/')[0], value }))")
w()
w("  // Severity distribution")
w("  const severityDist = severities.map(s => ({ severity: s, count: incidents.filter(i => i.severity === s).length }))")
w()
w("  // Warehouse safety radar")
w("  const whSafetyRadar = warehouses.slice(0, 6).map(wh => {")
w("    const whInc = incidents.filter(i => i.warehouse === wh)")
w("    const whAud = audits.filter(a => a.warehouse === wh && a.status === 'completed')")
w("    return {")
w("      warehouse: wh.replace('WH-', '').replace('-0', ' #'),")
w("      safety: Math.max(0, 100 - whInc.filter(i => i.severity === 'critical').length * 15),")
w("      compliance: +((whAud.reduce((s, a) => s + a.score, 0) / Math.max(whAud.length, 1))).toFixed(0),")
w("      training: r(55, 95),")
w("      equipment: r(60, 98),")
w("    }")
w("  })")
w()
w("  // Equipment compliance chart")
w("  const equipCompliance = complianceStatuses.map(cs => ({")
w("    status: cs, count: equipment.filter(e => e.complianceStatus === cs).length })")
w("  })")
w()
w("  return {")
w("    incidents, audits, equipment, trainings, inspections,")
w("    monthlyData, typePieData, severityDist, whSafetyRadar, equipCompliance,")
w("    openIncidents, criticalIncidents, avgAuditScore, nonCompliantEquip, daysWithoutIncident, trainingCompletion,")
w("    severities, incidentStatuses, incidentTypes, auditTypes, auditCategories, auditStatuses,")
w("    complianceStatuses, equipmentTypes, courseTypes, inspectionTypes, warehouses,")
w("}")
w("}")
w()

w("const COLORS = ['#ef4444', '#f97316', '#eab308', '#22c55e', '#06b6d4', '#8b5cf6', '#ec4899', '#14b8a6']")
w("const THEME = { primary: '#ef4444', secondary: '#22c55e', accent: '#f97316', info: '#06b6d4', success: '#22c55e', danger: '#ef4444', warning: '#f97316' }")
w()
w("export default function WarehouseSafetyComplianceView() {")
w("  const data = useMemo(() => generateData(), [])")
w("  const [activeTab, setActiveTab] = useState(0)")
w("  const [selectedIncident, setSelectedIncident] = useState<SafetyIncident | null>(null)")
w("  const [selectedAudit, setSelectedAudit] = useState<ComplianceAudit | null>(null)")
w("  const [selectedEquip, setSelectedEquip] = useState<SafetyEquipment | null>(null)")
w("  const [currentPage, setCurrentPage] = useState(1)")
w("  const [searchQuery, setSearchQuery] = useState('')")
w("  const [statusFilter, setStatusFilter] = useState('all')")
w("  const [severityFilter, setSeverityFilter] = useState('all')")
w("  const [typeFilter, setTypeFilter] = useState('all')")
w("  const [equipFilter, setEquipFilter] = useState('all')")
w("  const [sortField, setSortField] = useState<string>('id')")
w("  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('asc')")
w("  const [eqPage, setEqPage] = useState(1)")
w("  const rowsPerPage = 15")
w()
w("  const [currentTime, setCurrentTime] = useState('')")
w("  useEffect(() => {")
w("    const tick = () => setCurrentTime(new Date().toLocaleTimeString('en-IN', { timeZone: 'Asia/Kolkata', hour12: false }))")
w("    tick()")
w("    const iv = setInterval(tick, 1000)")
w("    return () => clearInterval(iv)")
w("  }, [])")
w()
w("  const filteredIncidents = useMemo(() => {")
w("    let list = data.incidents.filter(i => {")
w("      if (statusFilter !== 'all' && i.status !== statusFilter) return false")
w("      if (severityFilter !== 'all' && i.severity !== severityFilter) return false")
w("      if (searchQuery && !i.id.toLowerCase().includes(searchQuery.toLowerCase()) && !i.title.toLowerCase().includes(searchQuery.toLowerCase()) && !i.warehouse.toLowerCase().includes(searchQuery.toLowerCase())) return false")
w("      return true")
w("    })")
w("    list.sort((a, b) => {")
w("      const aVal = (a as any)[sortField]; const bVal = (b as any)[sortField]")
w("      if (typeof aVal === 'string') return sortDir === 'asc' ? aVal.localeCompare(bVal) : bVal.localeCompare(aVal)")
w("      return sortDir === 'asc' ? (aVal as number) - (bVal as number) : (bVal as number) - (aVal as number)")
w("    })")
w("    return list")
w("  }, [data, statusFilter, severityFilter, searchQuery, sortField, sortDir])")
w()
w("  const filteredEquip = useMemo(() => {")
w("    return data.equipment.filter(e => {")
w("      if (equipFilter !== 'all' && e.complianceStatus !== equipFilter) return false")
w("      if (typeFilter !== 'all' && e.type !== typeFilter) return false")
w("      if (searchQuery && !e.name.toLowerCase().includes(searchQuery.toLowerCase()) && !e.warehouse.toLowerCase().includes(searchQuery.toLowerCase())) return false")
w("      return true")
w("    })")
w("  }, [data, equipFilter, typeFilter, searchQuery])")
w()
w("  const paginated = filteredIncidents.slice((currentPage - 1) * rowsPerPage, currentPage * rowsPerPage)")
w("  const paginatedEq = filteredEquip.slice((eqPage - 1) * rowsPerPage, eqPage * rowsPerPage)")
w("  const totalPages = Math.ceil(filteredIncidents.length / rowsPerPage)")
w("  const totalEqPages = Math.ceil(filteredEquip.length / rowsPerPage)")
w("  const toggleSort = (field: string) => {")
w("    if (sortField === field) setSortDir(d => d === 'asc' ? 'desc' : 'asc')")
w("    else { setSortField(field); setSortDir('asc') }")
w("  }")
w()
w("  const tabs = ['Dashboard', 'Incident Tracker', 'Compliance Audits', 'Safety Equipment', 'Training & Inspections']")
w()
w("  const severityColor = (s: string) => { const map: Record<string, string> = { critical: '#ef4444', major: '#f97316', minor: '#eab308', 'near-miss': '#06b6d4', open: '#ef4444', investigating: '#f97316', resolved: '#22c55e', closed: '#6b7280', escalated: '#dc2626', scheduled: '#06b6d4', in_progress: '#f97316', completed: '#22c55e', overdue: '#ef4444', compliant: '#22c55e', 'non-compliant': '#ef4444', expiring: '#f97316', pending: '#6b7280', mandatory: '#ef4444', refresher: '#f97316', certification: '#8b5cf6', induction: '#06b6d4', regulatory: '#ef4444', voluntary: '#06b6d4', internal: '#8b5cf6', customer: '#f97316' }; return map[s] || '#6b7280' }")
w()
w("  // TAB 0: DASHBOARD")
w("  const renderDashboard = () => (")
w("    <div className='saf-tab-content'>")
w("      <div className='saf-clock-row'><ShieldAlert size={18} style={{ color: THEME.primary }} /><span className='saf-live-dot' /><span className='saf-clock-text'>Live — {currentTime} IST</span></div>")
w("      <div className='saf-kpi-grid'>")
w("        {[{ label: 'Open Incidents', value: data.openIncidents, icon: <TriangleAlert size={20} />, color: '#ef4444' },{ label: 'Critical', value: data.criticalIncidents, icon: <Siren size={20} />, color: '#dc2626' },{ label: 'Days Safe', value: data.daysWithoutIncident, icon: <ShieldCheck size={20} />, color: '#22c55e' },{ label: 'Avg Audit Score', value: `${data.avgAuditScore}%`, icon: <ClipboardCheck size={20} />, color: '#06b6d4' },{ label: 'Non-Compliant Equip', value: data.nonCompliantEquip, icon: <ShieldX size={20} />, color: '#f97316' },{ label: 'Training Rate', value: `${data.trainingCompletion}%`, icon: <Award size={20} />, color: '#8b5cf6' }].map((k, i) => (")
w("          <div key={i} className='saf-kpi-card' style={{ borderTopColor: k.color }}>")
w("            <div className='saf-kpi-icon' style={{ background: `${k.color}15`, color: k.color }}>{k.icon}</div>")
w("            <div className='saf-kpi-body'><span className='saf-kpi-value'>{k.value}</span><span className='saf-kpi-label'>{k.label}</span></div>")
w("          </div>")
w("        ))}")
w("      </div>")
w()
w("      <div className='saf-charts-row'>")
w("        <div className='saf-chart-card saf-chart-wide'>")
w("          <div className='saf-chart-header'><h4 className='saf-chart-title'>Monthly Safety Trend</h4></div>")
w("          <ResponsiveContainer width='100%' height={260}>")
w("            <ComposedChart data={data.monthlyData}>")
w("              <CartesianGrid strokeDasharray='3 3' stroke='#1e293b' />")
w("              <XAxis dataKey='month' stroke='#64748b' tick={{ fontSize: 10 }} />")
w("              <YAxis yAxisId='left' stroke='#64748b' tick={{ fontSize: 10 }} />")
w("              <YAxis yAxisId='right' orientation='right' stroke='#64748b' tick={{ fontSize: 10 }} />")
w("              <Tooltip contentStyle={{ background: '#1e293b', border: '1px solid #334155', borderRadius: 8 }} />")
w("              <Legend wrapperStyle={{ fontSize: 11 }} />")
w("              <Bar yAxisId='left' dataKey='incidents' fill='#ef4444' radius={[4, 4, 0, 0]} name='Incidents' />")
w("              <Bar yAxisId='left' dataKey='resolved' fill='#22c55e' radius={[4, 4, 0, 0]} name='Resolved' />")
w("              <Line yAxisId='right' dataKey='auditScore' stroke='#06b6d4' strokeWidth={2} dot={false} name='Audit Score' />")
w("            </ComposedChart>")
w("          </ResponsiveContainer>")
w("        </div>")
w("        <div className='saf-chart-card'>")
w("          <div className='saf-chart-header'><h4 className='saf-chart-title'>Incident Types</h4></div>")
w("          <ResponsiveContainer width='100%' height={260}>")
w("            <PieChart>")
w("              <Pie data={data.typePieData} cx='50%' cy='50%' outerRadius={80} innerRadius={45} dataKey='value' label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`} labelLine={{ stroke: '#475569' }}>")
w("                {data.typePieData.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}")
w("              </Pie>")
w("              <Tooltip contentStyle={{ background: '#1e293b', border: '1px solid #334155', borderRadius: 8 }} />")
w("            </PieChart>")
w("          </ResponsiveContainer>")
w("        </div>")
w("      </div>")
w()
w("      <div className='saf-charts-row'>")
w("        <div className='saf-chart-card'>")
w("          <div className='saf-chart-header'><h4 className='saf-chart-title'>Warehouse Safety Radar</h4></div>")
w("          <ResponsiveContainer width='100%' height={260}>")
w("            <RadarChart data={data.whSafetyRadar}>")
w("              <PolarGrid stroke='#334155' />")
w("              <PolarAngleAxis dataKey='warehouse' stroke='#94a3b8' tick={{ fontSize: 10 }} />")
w("              <PolarRadiusAxis stroke='#475569' tick={{ fontSize: 9 }} />")
w("              <Radar name='Safety' dataKey='safety' stroke='#ef4444' fill='#ef444430' strokeWidth={2} />")
w("              <Radar name='Compliance' dataKey='compliance' stroke='#22c55e' fill='#22c55e30' strokeWidth={2} />")
w("              <Legend wrapperStyle={{ fontSize: 10 }} />")
w("            </RadarChart>")
w("          </ResponsiveContainer>")
w("        </div>")
w("        <div className='saf-chart-card'>")
w("          <div className='saf-chart-header'><h4 className='saf-chart-title'>Equipment Compliance</h4></div>")
w("          <ResponsiveContainer width='100%' height={260}>")
w("            <BarChart data={data.equipCompliance}>")
w("              <CartesianGrid strokeDasharray='3 3' stroke='#1e293b' />")
w("              <XAxis dataKey='status' stroke='#64748b' tick={{ fontSize: 10 }} />")
w("              <YAxis stroke='#64748b' tick={{ fontSize: 10 }} />")
w("              <Tooltip contentStyle={{ background: '#1e293b', border: '1px solid #334155', borderRadius: 8 }} />")
w("              <Bar dataKey='count' radius={[6, 6, 0, 0]}>")
w("                {data.equipCompliance.map((entry, i) => <Cell key={i} fill={['#22c55e','#ef4444','#f97316','#6b7280'][i]} />)}")
w("              </Bar>")
w("            </BarChart>")
w("          </ResponsiveContainer>")
w("        </div>")
w("      </div>")
w("    </div>")
w("  )")
w()

# TAB 1: INCIDENT TRACKER
w("  const renderIncidents = () => (")
w("    <div className='saf-tab-content'>")
w("      <div className='saf-filter-row'>")
w("        <div className='saf-search-box'><input type='text' placeholder='Search incident ID, title, warehouse...' value={searchQuery} onChange={e => { setSearchQuery(e.target.value); setCurrentPage(1) }} className='saf-search-input' /></div>")
w("        <div className='saf-filter-pills'>")
w("          <button className={`saf-pill ${severityFilter === 'all' ? 'saf-pill-active' : ''}`} onClick={() => setSeverityFilter('all')}>All</button>")
w("          {data.severities.map(s => (<button key={s} className={`saf-pill ${severityFilter === s ? 'saf-pill-active' : ''}`} style={severityFilter === s ? { background: severityColor(s), borderColor: severityColor(s) } : {}} onClick={() => setSeverityFilter(s)}>{s}</button>))}")
w("        </div>")
w("        <div className='saf-filter-pills'>")
w("          <button className={`saf-pill ${statusFilter === 'all' ? 'saf-pill-active' : ''}`} onClick={() => setStatusFilter('all')}>All</button>")
w("          {data.incidentStatuses.map(s => (<button key={s} className={`saf-pill ${statusFilter === s ? 'saf-pill-active' : ''}`} onClick={() => setStatusFilter(s)}>{s}</button>))}")
w("        </div>")
w("      </div>")
w("      <div className='saf-fleet-stats'><span>Total: <b>{filteredIncidents.length}</b></span><span>Open: <b>{filteredIncidents.filter(i => i.status === 'open').length}</b></span><span>Critical: <b>{filteredIncidents.filter(i => i.severity === 'critical').length}</b></span><span>Page {currentPage}/{totalPages}</span></div>")
w("      <div className='saf-table-wrapper'>")
w("        <table className='saf-table'><thead><tr>")
w("          <th onClick={() => toggleSort('id')} className='saf-th-sortable'>ID {sortField === 'id' && (sortDir === 'asc' ? <ChevronUp size={12} /> : <ChevronDown size={12} />)}</th>")
w("          <th>Type</th><th>Severity</th><th>Status</th><th>Warehouse</th><th>Zone</th><th>Risk</th><th>Injuries</th><th>Near Miss</th><th>Reported</th><th>Action</th>")
w("        </tr></thead><tbody>")
w("        {paginated.map(inc => (")
w("          <tr key={inc.id} className='saf-table-row' style={{ borderLeftColor: severityColor(inc.severity) }}>")
w("            <td className='saf-td-id'><ShieldAlert size={14} style={{ color: severityColor(inc.severity), marginRight: 6 }} />{inc.id}</td>")
w("            <td><span className='saf-type-badge'>{inc.type}</span></td>")
w("            <td><span className='saf-status-badge' style={{ background: `${severityColor(inc.severity)}20`, color: severityColor(inc.severity) }}>{inc.severity}</span></td>")
w("            <td><span className='saf-status-badge' style={{ background: `${severityColor(inc.status)}20`, color: severityColor(inc.status) }}>{inc.status}</span></td>")
w("            <td style={{ fontSize: 11 }}>{inc.warehouse.replace('WH-','')}</td>")
w("            <td>{inc.zone}</td>")
w("            <td><div className='saf-bar-cell'><div className='saf-bar-track'><div className='saf-bar-fill' style={{ width: `${inc.riskScore}%`, background: inc.riskScore > 70 ? '#ef4444' : inc.riskScore > 40 ? '#f97316' : '#22c55e' }} /></div><span className='saf-bar-text'>{inc.riskScore}</span></div></td>")
w("            <td style={{ color: inc.injuredCount > 0 ? '#ef4444' : '#22c55e' }}>{inc.injuredCount}</td>")
w("            <td>{inc.nearMiss ? <CheckCircle2 size={14} style={{ color: '#06b6d4' }} /> : '—'}</td>")
w("            <td style={{ fontSize: 11 }}>{inc.reportedAt}</td>")
w("            <td><button className='saf-view-btn' onClick={() => setSelectedIncident(inc)}><Eye size={14} /></button></td>")
w("          </tr>")
w("        ))}")
w("        </tbody></table>")
w("      </div>")
w("      <div className='saf-pagination'>")
w("        <button disabled={currentPage <= 1} onClick={() => setCurrentPage(p => p - 1)} className='saf-page-btn'><ChevronLeft size={16} /></button>")
w("        {Array.from({ length: Math.min(totalPages, 8) }, (_, i) => <button key={i} className={`saf-page-btn ${currentPage === i + 1 ? 'saf-page-active' : ''}`} onClick={() => setCurrentPage(i + 1)}>{i + 1}</button>)}")
w("        <button disabled={currentPage >= totalPages} onClick={() => setCurrentPage(p => p + 1)} className='saf-page-btn'><ChevronRight size={16} /></button>")
w("      </div>")
w("    </div>")
w("  )")
w()

# TAB 2: COMPLIANCE AUDITS
w("  const renderAudits = () => (")
w("    <div className='saf-tab-content'>")
w("      <div className='saf-kpi-grid'>")
w("        <div className='saf-kpi-card' style={{ borderTopColor: '#06b6d4' }}><div className='saf-kpi-icon' style={{ background: '#06b6d415', color: '#06b6d4' }}><ClipboardCheck size={20} /></div><div className='saf-kpi-body'><span className='saf-kpi-value'>{data.audits.length}</span><span className='saf-kpi-label'>Total Audits</span></div></div>")
w("        <div className='saf-kpi-card' style={{ borderTopColor: '#22c55e' }}><div className='saf-kpi-icon' style={{ background: '#22c55e15', color: '#22c55e' }}><CheckCircle2 size={20} /></div><div className='saf-kpi-body'><span className='saf-kpi-value'>{data.audits.filter(a => a.status === 'completed').length}</span><span className='saf-kpi-label'>Completed</span></div></div>")
w("        <div className='saf-kpi-card' style={{ borderTopColor: '#f97316' }}><div className='saf-kpi-icon' style={{ background: '#f9731615', color: '#f97316' }}><AlertTriangle size={20} /></div><div className='saf-kpi-body'><span className='saf-kpi-value'>{data.audits.filter(a => a.status === 'overdue').length}</span><span className='saf-kpi-label'>Overdue</span></div></div>")
w("        <div className='saf-kpi-card' style={{ borderTopColor: '#8b5cf6' }}><div className='saf-kpi-icon' style={{ background: '#8b5cf615', color: '#8b5cf6' }}><BarChart3 size={20} /></div><div className='saf-kpi-body'><span className='saf-kpi-value'>{data.avgAuditScore}%</span><span className='saf-kpi-label'>Avg Score</span></div></div>")
w("      </div>")
w("      <div className='saf-audit-grid'>")
w("        {data.audits.map(aud => {")
w("          const progress = aud.totalChecks > 0 ? (aud.passedChecks / aud.totalChecks) * 100 : 0")
w("          return (")
w("            <div key={aud.id} className='saf-audit-card' style={{ borderTopColor: severityColor(aud.status) }}>")
w("              <div className='saf-audit-header'>")
w("                <span className='saf-audit-id'>{aud.id}</span>")
w("                <span className='saf-audit-status' style={{ background: `${severityColor(aud.status)}20`, color: severityColor(aud.status) }}>{aud.status}</span>")
w("                <span className='saf-audit-cat' style={{ color: severityColor(aud.category) }}>{aud.category}</span>")
w("              </div>")
w("              <div className='saf-audit-name'>{aud.name}</div>")
w("              <div className='saf-audit-score-section'>")
w("                {aud.status === 'completed' && <><div className='saf-audit-score-circle' style={{ borderColor: aud.score > 85 ? '#22c55e' : aud.score > 60 ? '#f97316' : '#ef4444' }}><span className='saf-audit-score-value'>{aud.score}%</span></div></>}")
w("                <div className='saf-audit-progress'>")
w("                  <div className='saf-audit-progress-label'>Checks: {aud.passedChecks}/{aud.totalChecks} passed</div>")
w("                  <div className='saf-progress-track'><div className='saf-progress-fill' style={{ width: `${progress}%`, background: '#22c55e' }} /></div>")
w("                </div>")
w("              </div>")
w("              {aud.criticalFinds > 0 && <div className='saf-audit-finds'><TriangleAlert size={12} style={{ color: '#ef4444' }} /><span>{aud.criticalFinds} critical findings</span></div>}")
w("              <div className='saf-audit-meta'><span>{aud.warehouse.replace('WH-','')}</span><span>{aud.type}</span><span>Next: {aud.nextAudit}</span></div>")
w("              <button className='saf-card-action-btn' onClick={() => setSelectedAudit(aud)}><Eye size={14} /> View Details</button>")
w("            </div>")
w("          )")
w("        })}")
w("      </div>")
w("    </div>")
w("  )")
w()

# TAB 3: SAFETY EQUIPMENT
w("  const renderEquipment = () => (")
w("    <div className='saf-tab-content'>")
w("      <div className='saf-filter-row'>")
w("        <div className='saf-search-box'><input type='text' placeholder='Search equipment, warehouse...' value={searchQuery} onChange={e => { setSearchQuery(e.target.value); setEqPage(1) }} className='saf-search-input' /></div>")
w("        <div className='saf-filter-pills'>")
w("          <button className={`saf-pill ${equipFilter === 'all' ? 'saf-pill-active' : ''}`} onClick={() => setEquipFilter('all')}>All</button>")
w("          {data.complianceStatuses.map(s => (<button key={s} className={`saf-pill ${equipFilter === s ? 'saf-pill-active' : ''}`} style={equipFilter === s ? { background: severityColor(s), borderColor: severityColor(s) } : {}} onClick={() => setEquipFilter(s)}>{s}</button>))}")
w("        </div>")
w("      </div>")
w("      <div className='saf-fleet-stats'><span>Total: <b>{filteredEquip.length}</b></span><span>Non-Compliant: <b>{filteredEquip.filter(e => e.complianceStatus === 'non-compliant').length}</b></span><span>Expiring: <b>{filteredEquip.filter(e => e.complianceStatus === 'expiring').length}</b></span><span>Page {eqPage}/{totalEqPages}</span></div>")
w("      <div className='saf-table-wrapper'>")
w("        <table className='saf-table'><thead><tr><th>Equipment</th><th>Type</th><th>Status</th><th>Condition</th><th>Warehouse</th><th>Zone</th><th>Last Inspection</th><th>Expiry</th><th>Action</th></tr></thead><tbody>")
w("        {paginatedEq.map(eq => (")
w("          <tr key={eq.id} className='saf-table-row' style={{ borderLeftColor: severityColor(eq.complianceStatus) }}>")
w("            <td className='saf-td-id'><FireExtinguisher size={14} style={{ color: severityColor(eq.complianceStatus), marginRight: 6 }} />{eq.id}</td>")
w("            <td><span className='saf-type-badge'>{eq.type}</span></td>")
w("            <td><span className='saf-status-badge' style={{ background: `${severityColor(eq.complianceStatus)}20`, color: severityColor(eq.complianceStatus) }}>{eq.complianceStatus}</span></td>")
w("            <td><div className='saf-bar-cell'><div className='saf-bar-track'><div className='saf-bar-fill' style={{ width: `${eq.condition}%`, background: eq.condition > 70 ? '#22c55e' : eq.condition > 40 ? '#f97316' : '#ef4444' }} /></div><span className='saf-bar-text'>{eq.condition}%</span></div></td>")
w("            <td style={{ fontSize: 11 }}>{eq.warehouse.replace('WH-','')}</td>")
w("            <td>{eq.zone}</td>")
w("            <td style={{ fontSize: 11 }}>{eq.lastInspection}</td>")
w("            <td style={{ fontSize: 11 }}>{eq.expiryDate}</td>")
w("            <td><button className='saf-view-btn' onClick={() => setSelectedEquip(eq)}><Eye size={14} /></button></td>")
w("          </tr>")
w("        ))}")
w("        </tbody></table>")
w("      </div>")
w("      <div className='saf-pagination'>")
w("        <button disabled={eqPage <= 1} onClick={() => setEqPage(p => p - 1)} className='saf-page-btn'><ChevronLeft size={16} /></button>")
w("        {Array.from({ length: Math.min(totalEqPages, 8) }, (_, i) => <button key={i} className={`saf-page-btn ${eqPage === i + 1 ? 'saf-page-active' : ''}`} onClick={() => setEqPage(i + 1)}>{i + 1}</button>)}")
w("        <button disabled={eqPage >= totalEqPages} onClick={() => setEqPage(p => p + 1)} className='saf-page-btn'><ChevronRight size={16} /></button>")
w("      </div>")
w("    </div>")
w("  )")
w()

# TAB 4: TRAINING & INSPECTIONS
w("  const renderTraining = () => (")
w("    <div className='saf-tab-content'>")
w("      <div className='saf-section-header'><Award size={18} style={{ color: '#8b5cf6' }} /><h3 className='saf-section-title'>Safety Training Programs ({data.trainings.length})</h3></div>")
w("      <div className='saf-training-grid'>")
w("        {data.trainings.map(tr => (")
w("          <div key={tr.id} className='saf-training-card' style={{ borderLeftColor: severityColor(tr.type) }}>")
w("            <div className='saf-training-header'>")
w("              <BookOpen size={16} style={{ color: '#8b5cf6' }} />")
w("              <span className='saf-training-name'>{tr.course}</span>")
w("              <span className='saf-training-type' style={{ color: severityColor(tr.type) }}>{tr.type}</span>")
w("            </div>")
w("            <div className='saf-training-meta'>")
w("              <span>{tr.warehouse.replace('WH-','')}</span><span>{tr.instructor}</span><span>{tr.duration} min</span>")
w("              <span className='saf-training-cert'>{tr.certification}</span>")
w("            </div>")
w("            <div className='saf-training-progress'>")
w("              <span>Attendees: {tr.completedAttendees}/{tr.attendees}</span>")
w("              <span>Pass Rate: {tr.passRate > 0 ? `${tr.passRate}%` : '—'}</span>")
w("            </div>")
w("            <span className='saf-training-status' style={{ background: `${severityColor(tr.status)}20`, color: severityColor(tr.status) }}>{tr.status}</span>")
w("          </div>")
w("        ))}")
w("      </div>")
w("      <div className='saf-section-header' style={{ marginTop: 24 }}><ClipboardCheck size={18} style={{ color: '#22c55e' }} /><h3 className='saf-section-title'>Safety Inspections ({data.inspections.length})</h3></div>")
w("      <div className='saf-insp-grid'>")
w("        {data.inspections.map(insp => (")
w("          <div key={insp.id} className='saf-insp-card' style={{ borderLeftColor: severityColor(insp.status) }}>")
w("            <div className='saf-insp-header'>")
w("              <span className='saf-insp-id'>{insp.id}</span>")
w("              <span className='saf-insp-status' style={{ background: `${severityColor(insp.status)}20`, color: severityColor(insp.status) }}>{insp.status}</span>")
w("            </div>")
w("            <div className='saf-insp-name'>{insp.type} — {insp.area}</div>")
w("            <div className='saf-insp-meta'><span>{insp.warehouse.replace('WH-','')}</span><span>{insp.inspector}</span></div>")
w("            {insp.status === 'completed' && <div className='saf-insp-score-row'><span>Score:</span><span className='saf-insp-score' style={{ color: insp.score > 85 ? '#22c55e' : insp.score > 60 ? '#f97316' : '#ef4444' }}>{insp.score}%</span><span>({insp.passedItems}/{insp.totalItems})</span></div>}")
w("            <div className='saf-insp-finding'>{insp.findings}</div>")
w("          </div>")
w("        ))}")
w("      </div>")
w("    </div>")
w("  )")
w()

# DRAWERS
w("  // ---- Incident Drawer ----")
w("  const renderIncidentDrawer = () => {")
w("    if (!selectedIncident) return null")
w("    const i = selectedIncident")
w("    const hBg = i.severity === 'critical' ? 'linear-gradient(135deg, #dc2626, #991b1b)' : i.severity === 'major' ? 'linear-gradient(135deg, #f97316, #c2410c)' : i.severity === 'minor' ? 'linear-gradient(135deg, #eab308, #a16207)' : 'linear-gradient(135deg, #06b6d4, #0e7490)'")
w("    return (<>")
w("      <div className='saf-drawer-overlay' onClick={() => setSelectedIncident(null)} />")
w("      <div className='saf-drawer-panel'>")
w("        <div className='saf-drawer-header' style={{ background: hBg }}>")
w("          <div className='saf-drawer-header-top'>")
w("            <div className='saf-drawer-header-info'><ShieldAlert size={24} className='saf-drawer-header-icon' /><div><div className='saf-drawer-title'>{i.id}</div><div className='saf-drawer-subtitle'>{i.type} · {i.severity}</div></div></div>")
w("            <button className='saf-drawer-close' onClick={() => setSelectedIncident(null)}><XCircle size={20} /></button>")
w("          </div>")
w("          <div className='saf-drawer-badges'><span className='saf-drawer-badge' style={{ background: `${severityColor(i.status)}30`, color: '#fff' }}>{i.status}</span><span className='saf-drawer-badge' style={{ background: '#ffffff20', color: '#fff' }}>{i.nearMiss ? 'NEAR MISS' : `${i.injuredCount} injured`}</span></div>")
w("        </div>")
w("        <div className='saf-drawer-body'>")
w("          <div className='saf-drawer-grid'>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Warehouse</span><span className='saf-drawer-value'>{i.warehouse}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Zone</span><span className='saf-drawer-value'>{i.zone}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Risk Score</span><span className='saf-drawer-value' style={{ color: i.riskScore > 70 ? '#ef4444' : '#22c55e' }}>{i.riskScore}/100</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Compliance Ref</span><span className='saf-drawer-value'>{i.complianceRef}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Reported By</span><span className='saf-drawer-value'>{i.reportedBy}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Reported At</span><span className='saf-drawer-value'>{i.reportedAt}</span></div>")
w("          </div>")
w("          <div className='saf-drawer-section-title'>Description</div>")
w("          <p className='saf-drawer-desc'>{i.description}</p>")
w("          <div className='saf-drawer-section-title'>Investigation</div>")
w("          <div className='saf-drawer-grid'>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Root Cause</span><span className='saf-drawer-value'>{i.rootCause}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Corrective Action</span><span className='saf-drawer-value'>{i.correctiveAction}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Resolved</span><span className='saf-drawer-value'>{i.resolvedAt || '—'}</span></div>")
w("          </div>")
w("          <div className='saf-drawer-actions'><button className='saf-action-btn saf-action-primary'><Play size={14} /> Investigate</button><button className='saf-action-btn saf-action-secondary'><RefreshCw size={14} /> Escalate</button><button className='saf-action-btn saf-action-secondary'><ClipboardCheck size={14} /> Close</button><button className='saf-action-btn saf-action-ghost'><FileText size={14} /> Report</button></div>")
w("        </div>")
w("      </div>")
w("    </>)")
w("  }")
w()

w("  // ---- Audit Drawer ----")
w("  const renderAuditDrawer = () => {")
w("    if (!selectedAudit) return null")
w("    const a = selectedAudit")
w("    return (<>")
w("      <div className='saf-drawer-overlay' onClick={() => setSelectedAudit(null)} />")
w("      <div className='saf-drawer-panel'>")
w("        <div className='saf-drawer-header' style={{ background: 'linear-gradient(135deg, #06b6d4, #0e7490)' }}>")
w("          <div className='saf-drawer-header-top'>")
w("            <div className='saf-drawer-header-info'><ClipboardCheck size={24} className='saf-drawer-header-icon' /><div><div className='saf-drawer-title'>{a.id}</div><div className='saf-drawer-subtitle'>{a.type} · {a.category}</div></div></div>")
w("            <button className='saf-drawer-close' onClick={() => setSelectedAudit(null)}><XCircle size={20} /></button>")
w("          </div>")
w("        </div>")
w("        <div className='saf-drawer-body'>")
w("          <div className='saf-drawer-grid'>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Warehouse</span><span className='saf-drawer-value'>{a.warehouse}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Auditor</span><span className='saf-drawer-value'>{a.auditor}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Status</span><span className='saf-drawer-value' style={{ color: severityColor(a.status) }}>{a.status}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Score</span><span className='saf-drawer-value'>{a.score > 0 ? `${a.score}%` : '—'}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Passed</span><span className='saf-drawer-value'>{a.passedChecks}/{a.totalChecks}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Failed</span><span className='saf-drawer-value' style={{ color: a.failedChecks > 0 ? '#ef4444' : '#22c55e' }}>{a.failedChecks}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Critical Finds</span><span className='saf-drawer-value' style={{ color: a.criticalFinds > 0 ? '#ef4444' : '#22c55e' }}>{a.criticalFinds}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Scheduled</span><span className='saf-drawer-value'>{a.scheduledDate}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Completed</span><span className='saf-drawer-value'>{a.completedDate || '—'}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Next Audit</span><span className='saf-drawer-value'>{a.nextAudit}</span></div>")
w("          </div>")
w("          <div className='saf-drawer-actions'><button className='saf-action-btn saf-action-primary'><Play size={14} /> Start Audit</button><button className='saf-action-btn saf-action-secondary'><FileText size={14} /> Export Report</button></div>")
w("        </div>")
w("      </div>")
w("    </>)")
w("  }")
w()

w("  // ---- Equipment Drawer ----")
w("  const renderEquipDrawer = () => {")
w("    if (!selectedEquip) return null")
w("    const e = selectedEquip")
w("    return (<>")
w("      <div className='saf-drawer-overlay' onClick={() => setSelectedEquip(null)} />")
w("      <div className='saf-drawer-panel'>")
w("        <div className='saf-drawer-header' style={{ background: e.complianceStatus === 'non-compliant' ? 'linear-gradient(135deg, #dc2626, #991b1b)' : e.complianceStatus === 'expiring' ? 'linear-gradient(135deg, #f97316, #c2410c)' : 'linear-gradient(135deg, #22c55e, #15803d)' }}>")
w("          <div className='saf-drawer-header-top'>")
w("            <div className='saf-drawer-header-info'><FireExtinguisher size={24} className='saf-drawer-header-icon' /><div><div className='saf-drawer-title'>{e.id}</div><div className='saf-drawer-subtitle'>{e.name} · {e.type}</div></div></div>")
w("            <button className='saf-drawer-close' onClick={() => setSelectedEquip(null)}><XCircle size={20} /></button>")
w("          </div>")
w("        </div>")
w("        <div className='saf-drawer-body'>")
w("          <div className='saf-drawer-grid'>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Warehouse</span><span className='saf-drawer-value'>{e.warehouse}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Zone</span><span className='saf-drawer-value'>{e.zone}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Compliance</span><span className='saf-drawer-value' style={{ color: severityColor(e.complianceStatus) }}>{e.complianceStatus}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Condition</span><span className='saf-drawer-value'>{e.condition}%</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Last Inspection</span><span className='saf-drawer-value'>{e.lastInspection}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Next Inspection</span><span className='saf-drawer-value'>{e.nextInspection}</span></div>")
w("            <div className='saf-drawer-field'><span className='saf-drawer-label'>Expiry</span><span className='saf-drawer-value'>{e.expiryDate}</span></div>")
w("          </div>")
w("          <div className='saf-drawer-actions'><button className='saf-action-btn saf-action-primary'><Wrench size={14} /> Schedule Inspection</button><button className='saf-action-btn saf-action-secondary'><RefreshCw size={14} /> Replace</button></div>")
w("        </div>")
w("      </div>")
w("    </>)")
w("  }")
w()

# MAIN RENDER
w("  const renderTab = () => { switch (activeTab) { case 0: return renderDashboard(); case 1: return renderIncidents(); case 2: return renderAudits(); case 3: return renderEquipment(); case 4: return renderTraining(); default: return null } }")
w()
w("  return (")
w("    <div className='saf-container'>")
w("      <div className='saf-page-header'>")
w("        <div className='saf-page-title-row'><ShieldAlert size={28} style={{ color: THEME.primary }} /><div><h1 className='saf-page-title'>Warehouse Safety & Compliance</h1><p className='saf-page-subtitle'>Incident Management · Safety Audits · Equipment Compliance · Training Programs</p></div></div>")
w("        <div className='saf-header-stats'><span className='saf-header-stat'><ShieldAlert size={14} />{data.incidents.length} Incidents</span><span className='saf-header-stat'><ClipboardCheck size={14} />{data.audits.length} Audits</span><span className='saf-header-stat'><FireExtinguisher size={14} />{data.equipment.length} Equipment</span><span className='saf-header-stat'><Award size={14} />{data.trainings.length} Training</span></div>")
w("      </div>")
w("      <div className='saf-tabs'>{tabs.map((tab, i) => (<button key={tab} className={`saf-tab ${activeTab === i ? 'saf-tab-active' : ''}`} onClick={() => { setActiveTab(i); setCurrentPage(1); setEqPage(1); setStatusFilter('all'); setSeverityFilter('all'); setTypeFilter('all'); setEquipFilter('all'); setSearchQuery('') }}>{tab}</button>))}</div>")
w("      {renderTab()}")
w("      {renderIncidentDrawer()}{renderAuditDrawer()}{renderEquipDrawer()}")
w("    </div>")
w("  )")
w("}")
w()

outpath = "/home/z/my-project/src/components/modules/warehouse-safety-compliance-view.tsx"
with open(outpath, "w") as f:
    f.write("\n".join(LINES))

print(f"Generated {len(LINES)} lines → {outpath}")
