#!/usr/bin/env python3
"""Generate R171: Gate & Security Management module (gate-security-view.tsx)"""

import random
import time

def seeded_random(seed):
    """Deterministic random for consistent data."""
    r = random.Random(seed)
    def _inner(min_val=0, max_val=1):
        return r.uniform(min_val, max_val)
    return _inner

def generate():
    r = seeded_random(171)
    lines = []
    
    def w(s=""):
        lines.append(s)
    
    # Imports
    w('"use client";')
    w('')
    w('import React, { useState, useMemo, useEffect } from "react";')
    w('import {')
    w('  ComposedChart, Bar, Line, Area, PieChart, Pie, Cell, RadarChart, Radar, PolarGrid, PolarAngleAxis, PolarRadiusAxis,')
    w('  XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer,')
    w('} from "recharts";')
    w('import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";')
    w('import {')
    w('  ScanLine, ShieldCheck, Users, Truck, Camera, Fingerprint, AlertTriangle, Clock, MapPin, Phone, CreditCard,')
    w('  BadgeCheck, ChevronRight, Eye, FileText, XCircle, CheckCircle2, Timer, TrendingUp, Activity, Monitor, Lock, Unlock,')
    w('  Car, Package, UserCheck, ScanFace, ClipboardList, Search, ArrowUpRight, ArrowDownRight,')
    w('} from "lucide-react";')
    w('')
    
    # ===== TYPES =====
    w('// ===== TYPES =====')
    w('interface GateEntry {')
    w('  id: string; type: "inbound" | "outbound"; category: "vehicle" | "visitor" | "employee" | "vendor" | "delivery";')
    w('  entityName: string; entityPhone: string; vehicleNo: string; purpose: string;')
    w('  gateNo: string; checkpoint: string; warehouse: string; city: string; state: string;')
    w('  checkInTime: string; checkOutTime: string; duration: number; status: "checked-in" | "checked-out" | "pending" | "denied" | "blacklisted";')
    w('  securityLevel: "low" | "medium" | "high" | "critical";')
    w('  badgeNo: string; escortRequired: boolean; itemsCarried: number;')
    w('  temperature: number; temperaturePass: boolean;')
    w('  escortName: string; remarks: string;')
    w('}')
    w('')
    w('interface SecurityGuard {')
    w('  id: string; name: string; phone: string; empCode: string;')
    w('  shift: "morning" | "afternoon" | "night"; gateAssigned: string; warehouse: string; city: string;')
    w('  rank: "head-guard" | "senior-guard" | "guard" | "trainee";')
    w('  specialization: string[]; status: "on-duty" | "on-break" | "off-duty" | "training";')
    w('  totalChecks: number; checksToday: number; avgProcessingTime: number;')
    w('  incidentsHandled: number; complianceScore: number;')
    w('  certifications: string[]; age: number; gender: string;')
    w('  lastTraining: string; licenseExpiry: string;')
    w('}')
    w('')
    w('interface CCTVCamera {')
    w('  id: string; name: string; location: string; warehouse: string; city: string;')
    w('  type: "dome" | "bullet" | "ptz" | "thermal"; resolution: string;')
    w('  status: "online" | "offline" | "maintenance" | "recording" | "alert";')
    w('  fov: string; nightVision: boolean; aiEnabled: boolean;')
    w('  storageDays: number; lastMaintenance: string; ipAddress: string;')
    w('  uptime: number; alertsToday: number; recordingHours: number;')
    w('}')
    w('')
    w('interface AccessEvent {')
    w('  id: string; userId: string; userName: string; role: string; department: string;')
    w('  accessPoint: string; warehouse: string; city: string;')
    w('  accessType: "entry" | "exit" | "denied" | "forced" | "tamper";')
    w('  method: "badge" | "biometric" | "rfid" | "mobile" | "pin" | "manual";')
    w('  timestamp: string; zone: string;')
    w('  riskScore: number; biometricMatch: number;')
    w('  deviceStatus: "normal" | "flagged" | "malfunction";')
    w('}')
    w('')
    w('interface SecurityAlert {')
    w('  id: string; type: string; severity: "critical" | "high" | "medium" | "low";')
    w('  source: string; location: string; warehouse: string; city: string;')
    w('  timestamp: string; status: "open" | "investigating" | "resolved" | "escalated" | "false-alarm";')
    w('  description: string;')
    w('  assignedTo: string; responseTime: number; resolvedAt: string;')
    w('  rootCause: string; correctiveAction: string;')
    w('  cameraRef: string; cctvFootage: boolean;')
    w('}')
    w('')
    
    # ===== CONSTANTS =====
    w('// ===== CONSTANTS =====')
    w('const COLORS = { primary: "#0d9488", secondary: "#6366f1", accent: "#f59e0b", danger: "#ef4444", success: "#22c55e", info: "#3b82f6", purple: "#a855f7", pink: "#ec4899" };')
    w('const PIE_COLORS = ["#0d9488", "#6366f1", "#f59e0b", "#ef4444", "#22c55e", "#a855f7", "#3b82f6", "#ec4899", "#14b8a6", "#f97316"];')
    w('')
    w('const warehouses = [')
    w('  { name: "Mumbai Hub", city: "Mumbai", state: "Maharashtra" },')
    w('  { name: "Delhi NCR DC", city: "Delhi NCR", state: "Delhi" },')
    w('  { name: "Bengaluru FC", city: "Bengaluru", state: "Karnataka" },')
    w('  { name: "Hyderabad WH", city: "Hyderabad", state: "Telangana" },')
    w('  { name: "Chennai DC", city: "Chennai", state: "Tamil Nadu" },')
    w('  { name: "Kolkata Hub", city: "Kolkata", state: "West Bengal" },')
    w('  { name: "Pune FC", city: "Pune", state: "Maharashtra" },')
    w('  { name: "Ahmedabad WH", city: "Ahmedabad", state: "Gujarat" },')
    w('];')
    w('')
    
    # Helper: format INR
    w('function formatINR(val: number): string {')
    w('  if (val >= 10000000) return "₹" + (val / 10000000).toFixed(2) + " Cr";')
    w('  if (val >= 100000) return "₹" + (val / 100000).toFixed(2) + " L";')
    w('  return "₹" + val.toLocaleString("en-IN");')
    w('}')
    w('function formatDuration(mins: number): string {')
    w('  if (mins < 60) return `${mins}m`;')
    w('  const h = Math.floor(mins / 60);')
    w('  const m = mins % 60;')
    w('  return m > 0 ? `${h}h ${m}m` : `${h}h`;')
    w('}')
    w('')
    
    # ===== GENERATE DATA =====
    w('// ===== GENERATE DATA =====')
    w('function generateData() {')
    w('  const r = seededRandom(171);')
    w('  const now = new Date();')
    w('')
    w('  // Indian names for security guards')
    w('  const guardFirstNames = ["Rajesh", "Suresh", "Mohan", "Ravi", "Amit", "Vijay", "Sunil", "Deepak", "Sanjay", "Pradeep", "Krishna", "Anil", "Ramesh", "Mahesh", "Ganesh", "Dinesh", "Naresh", "Prakash", "Harish", "Kishore", "Ashok", "Manoj", "Ajay", "Vikram", "Arun", "Subhash", "Dilip", "Nandlal", "Prabhu", "Thakur"];')
    w('  const guardLastNames = ["Yadav", "Singh", "Kumar", "Sharma", "Gupta", "Patel", "Joshi", "Reddy", "Nair", "Pillai", "Verma", "Mishra", "Pandey", "Thakur", "Chauhan", "Rathore", "Maurya", "Kulkarni", "Deshmukh", "Iyer"];')
    w('')
    w('  const visitorFirstNames = ["Arjun", "Priya", "Vikram", "Sneha", "Rahul", "Anita", "Karthik", "Deepa", "Siddharth", "Meera", "Nikhil", "Pooja", "Varun", "Nisha", "Aditya", "Sunita", "Rohan", "Kavita", "Manish", "Swati"];')
    w('  const visitorLastNames = ["Mehta", "Kapoor", "Malhotra", "Bhatia", "Chopra", "Rao", "Iyengar", "Menon", "Banerjee", "Chatterjee", "Desai", "Sheth", "Puri", "Tandon", "Bajaj"];')
    w('')
    w('  const vehicleBrands = ["Tata Ace", "Ashok Leyland Dost", "Mahindra Bolero", "Eicher 1109", "Tata 407", "Ashok Leyland 1616", "BharatBenz 1617", "Tata Signa", "Eicher Pro", "Maruti Eeco", "Toyota Innova", "Mahindra Xylo", "Honda City", "Hyundai Creta", "Tata Nexon"];')
    w('')
    w('  const gateNames = ["Gate A - Main", "Gate B - Loading", "Gate C - Delivery", "Gate D - Emergency", "Gate E - Staff", "Gate F - VIP", "Gate G - Rear", "Gate H - Temp"];')
    w('')
    w('  const checkpoints = ["CP-1 Outer Perimeter", "CP-2 Entry Barrier", "CP-3 X-Ray Scanner", "CP-4 Biometric", "CP-5 Loading Bay", "CP-6 Staff Turnstile", "CP-7 Vehicle Weighbridge", "CP-8 Final Exit"];')
    w('')
    w('  const gatePurposes = ["Delivery", "Pickup", "Client Visit", "Audit", "Maintenance", "Staff Entry", "Vendor Meeting", "Govt Inspection", "IT Service", "Waste Disposal", "Fumigation", "Fire Drill", "Courier", "Cash Transit", "Equipment Demo"];')
    w('')
    w('  const ranks = ["head-guard", "senior-guard", "guard", "trainee"] as const;')
    w('  const shifts = ["morning", "afternoon", "night"] as const;')
    w('  const specializations = ["access-control", "vehicle-inspection", "cctv-monitoring", "fire-safety", "crowd-management", "threat-assessment", "first-aid", "evacuation"];')
    w('  const certifications = ["PSARA Licensed", "Fire Safety Cert", "First Aid Certified", "CCTV Operator", "X-Ray Scanner", "Crowd Control", "Self Defence", "Firearms Trained"];')
    w('')
    w('  const cameraTypes = ["dome", "bullet", "ptz", "thermal"] as const;')
    w('  const resolutions = ["1080p", "2K", "4K", "5MP", "8MP"];')
    w('  const cameraLocations = ["Main Gate Entrance", "Loading Dock Area", "Warehouse Interior A", "Warehouse Interior B", "Packing Zone", "Perimeter Fence N", "Perimeter Fence E", "Perimeter Fence S", "Perimeter Fence W", "Staff Entry", "Admin Block", "Parking Lot", "CCTV Control Room", "High-Value Storage", "Hazmat Zone", "Emergency Exit", "Weighbridge", "Receiving Dock", "Dispatch Bay", "Cafeteria Entrance"];')
    w('')
    w('  const alertTypes = ["Unauthorized Access", "Perimeter Breach", "Tailgating Detected", "Vehicle Overstay", "Unattended Baggage", "Fire Alarm", "CCTV Blind Spot", "Badge Cloning", "Forced Door Open", "Lock Tamper", "Motion After Hours", "Temperature Anomaly", "Chemical Spill", "Crowd Surge", "Power Failure"];')
    w('  const departments = ["Operations", "IT", "Admin", "HR", "Finance", "Logistics", "Warehouse", "Maintenance", "Quality", "Security"];')
    w('  const accessPoints = ["Main Gate Turnstile", "Staff Entry Door", "Warehouse Side Door", "Loading Bay Gate", "Admin Block Door", "Server Room", "Hazmat Zone Door", "High-Value Vault", "Emergency Exit", "Parking Gate"];')
    w('  const accessMethods = ["badge", "biometric", "rfid", "mobile", "pin", "manual"] as const;')
    w('  const zones = ["Zone A - General", "Zone B - Receiving", "Zone C - Storage", "Zone D - Shipping", "Zone E - Admin", "Zone F - Restricted", "Zone G - Hazmat", "Zone H - VIP"];')
    w('')
    w('  // ---- Gate Entries (150) ----')
    w('  const gateEntries: GateEntry[] = [];')
    w('  for (let i = 0; i < 150; i++) {')
    w('    const wh = warehouses[Math.floor(r() * warehouses.length)];')
    w('    const catIdx = Math.floor(r() * 5);')
    w('    const categories = ["vehicle", "visitor", "employee", "vendor", "delivery"] as const;')
    w('    const cat = categories[catIdx];')
    w('    const firstName = cat === "employee" ? guardFirstNames[Math.floor(r() * guardFirstNames.length)] : visitorFirstNames[Math.floor(r() * visitorFirstNames.length)];')
    w('    const lastName = cat === "employee" ? guardLastNames[Math.floor(r() * guardLastNames.length)] : visitorLastNames[Math.floor(r() * visitorLastNames.length)];')
    w('    const checkInH = Math.floor(r() * 14) + 5;')
    w('    const checkInM = Math.floor(r() * 60);')
    w('    const durationMin = Math.floor(r() * 480) + 15;')
    w('    const statusIdx = Math.floor(r() * 5);')
    w('    const statuses = ["checked-in", "checked-out", "pending", "denied", "blacklisted"] as const;')
    w('    const secLevelIdx = Math.floor(r() * 4);')
    w('    const secLevels = ["low", "medium", "high", "critical"] as const;')
    w('    const typeIdx = Math.floor(r() * 2);')
    w('    const types = ["inbound", "outbound"] as const;')
    w('    gateEntries.push({')
    w('      id: `GE-${String(i + 1).padStart(4, "0")}`, type: types[typeIdx], category: cat,')
    w('      entityName: `${firstName} ${lastName}`,')
    w('      entityPhone: `+91 ${9000000000 + Math.floor(r() * 999999999)}`,')
    w('      vehicleNo: cat === "vehicle" || cat === "delivery" || cat === "vendor" ? `${String.fromCharCode(65 + Math.floor(r() * 26))}${String.fromCharCode(65 + Math.floor(r() * 26))}${String.fromCharCode(65 + Math.floor(r() * 26))}-${Math.floor(r() * 100).toString().padStart(2, "0")}-${String.fromCharCode(65 + Math.floor(r() * 26))}${String.fromCharCode(65 + Math.floor(r() * 26))}-${Math.floor(r() * 10000).toString().padStart(4, "0")}` : "N/A",')
    w('      purpose: gatePurposes[Math.floor(r() * gatePurposes.length)],')
    w('      gateNo: gateNames[Math.floor(r() * gateNames.length)],')
    w('      checkpoint: checkpoints[Math.floor(r() * checkpoints.length)],')
    w('      warehouse: wh.name, city: wh.city, state: wh.state,')
    w('      checkInTime: `${String(checkInH).padStart(2, "0")}:${String(checkInM).padStart(2, "0")}`,')
    w('      checkOutTime: statuses[statusIdx] !== "checked-in" ? `${String(Math.min(checkInH + Math.floor(durationMin / 60), 23)).padStart(2, "0")}:${String((checkInM + durationMin) % 60).padStart(2, "0")}` : "--:--",')
    w('      duration: durationMin,')
    w('      status: statuses[statusIdx], securityLevel: secLevels[secLevelIdx],')
    w('      badgeNo: `BG-${String(Math.floor(r() * 9000) + 1000)}`,')
    w('      escortRequired: r() > 0.7,')
    w('      itemsCarried: Math.floor(r() * 8),')
    w('      temperature: Math.round((36 + r() * 3) * 10) / 10, temperaturePass: r() > 0.1,')
    w('      escortName: r() > 0.7 ? `${guardFirstNames[Math.floor(r() * guardFirstNames.length)]} ${guardLastNames[Math.floor(r() * guardLastNames.length)]}` : "N/A",')
    w('      remarks: r() > 0.8 ? ["Normal entry", "VIP visitor", "Govt official", "First visit", "Regular vendor", "Contract renewal", "Fire audit visit", "IT maintenance"][Math.floor(r() * 8)] : "",')
    w('    });')
    w('  }')
    w('')
    
    # Security Guards (40)
    w('  // ---- Security Guards (40) ----')
    w('  const securityGuards: SecurityGuard[] = [];')
    w('  for (let i = 0; i < 40; i++) {')
    w('    const wh = warehouses[Math.floor(r() * warehouses.length)];')
    w('    const fn = guardFirstNames[Math.floor(r() * guardFirstNames.length)];')
    w('    const ln = guardLastNames[Math.floor(r() * guardLastNames.length)];')
    w('    const numSpecs = Math.floor(r() * 3) + 1;')
    w('    const specs: string[] = [];')
    w('    for (let s = 0; s < numSpecs; s++) {')
    w('      const sp = specializations[Math.floor(r() * specializations.length)];')
    w('      if (!specs.includes(sp)) specs.push(sp);')
    w('    }')
    w('    const numCerts = Math.floor(r() * 4) + 1;')
    w('    const certs: string[] = [];')
    w('    for (let c = 0; c < numCerts; c++) {')
    w('      const ct = certifications[Math.floor(r() * certifications.length)];')
    w('      if (!certs.includes(ct)) certs.push(ct);')
    w('    }')
    w('    const statusIdx = Math.floor(r() * 4);')
    w('    const statuses = ["on-duty", "on-break", "off-duty", "training"] as const;')
    w('    securityGuards.push({')
    w('      id: `SG-${String(i + 1).padStart(4, "0")}`, name: `${fn} ${ln}`,')
    w('      phone: `+91 ${9000000000 + Math.floor(r() * 999999999)}`,')
    w('      empCode: `SEC-${String(i + 1).padStart(4, "0")}`,')
    w('      shift: shifts[Math.floor(r() * shifts.length)],')
    w('      gateAssigned: gateNames[Math.floor(r() * gateNames.length)],')
    w('      warehouse: wh.name, city: wh.city,')
    w('      rank: ranks[Math.floor(r() * ranks.length)],')
    w('      specialization: specs, status: statuses[statusIdx],')
    w('      totalChecks: Math.floor(r() * 5000) + 500,')
    w('      checksToday: Math.floor(r() * 80) + 5,')
    w('      avgProcessingTime: Math.round((1 + r() * 5) * 10) / 10,')
    w('      incidentsHandled: Math.floor(r() * 30),')
    w('      complianceScore: Math.round((70 + r() * 30) * 10) / 10,')
    w('      certifications: certs,')
    w('      age: Math.floor(r() * 25) + 22,')
    w('      gender: r() > 0.15 ? "Male" : "Female",')
    w('      lastTraining: `2025-${String(Math.floor(r() * 12) + 1).padStart(2, "0")}-${String(Math.floor(r() * 28) + 1).padStart(2, "0")}`,')
    w('      licenseExpiry: `2026-${String(Math.floor(r() * 12) + 1).padStart(2, "0")}-${String(Math.floor(r() * 28) + 1).padStart(2, "0")}`,')
    w('    });')
    w('  }')
    w('')
    
    # CCTV Cameras (60)
    w('  // ---- CCTV Cameras (60) ----')
    w('  const cctvCameras: CCTVCamera[] = [];')
    w('  for (let i = 0; i < 60; i++) {')
    w('    const wh = warehouses[Math.floor(r() * warehouses.length)];')
    w('    const statusIdx = Math.floor(r() * 5);')
    w('    const statuses = ["online", "offline", "maintenance", "recording", "alert"] as const;')
    w('    cctvCameras.push({')
    w('      id: `CAM-${String(i + 1).padStart(3, "0")}`,')
    w('      name: `${cameraLocations[i % cameraLocations.length]} ${Math.floor(i / cameraLocations.length) + 1 > 1 ? "#" + Math.floor(i / cameraLocations.length + 1) : ""}`,')
    w('      location: cameraLocations[i % cameraLocations.length],')
    w('      warehouse: wh.name, city: wh.city,')
    w('      type: cameraTypes[Math.floor(r() * cameraTypes.length)],')
    w('      resolution: resolutions[Math.floor(r() * resolutions.length)],')
    w('      status: statuses[statusIdx],')
    w('      fov: `${Math.floor(r() * 150) + 30}°`,')
    w('      nightVision: r() > 0.2, aiEnabled: r() > 0.3,')
    w('      storageDays: Math.floor(r() * 60) + 7,')
    w('      lastMaintenance: `2025-${String(Math.floor(r() * 12) + 1).padStart(2, "0")}-${String(Math.floor(r() * 28) + 1).padStart(2, "0")}`,')
    w('      ipAddress: `192.168.${Math.floor(r() * 10) + 1}.${Math.floor(r() * 254) + 1}`,')
    w('      uptime: Math.round((85 + r() * 15) * 10) / 10,')
    w('      alertsToday: Math.floor(r() * 5),')
    w('      recordingHours: Math.round((18 + r() * 6) * 10) / 10,')
    w('    });')
    w('  }')
    w('')
    
    # Access Events (100)
    w('  // ---- Access Events (100) ----')
    w('  const accessEvents: AccessEvent[] = [];')
    w('  for (let i = 0; i < 100; i++) {')
    w('    const wh = warehouses[Math.floor(r() * warehouses.length)];')
    w('    const fn = visitorFirstNames[Math.floor(r() * visitorFirstNames.length)];')
    w('    const ln = visitorLastNames[Math.floor(r() * visitorLastNames.length)];')
    w('    const typeIdx = Math.floor(r() * 5);')
    w('    const types = ["entry", "exit", "denied", "forced", "tamper"] as const;')
    w('    const statusIdx = Math.floor(r() * 3);')
    w('    const deviceStatuses = ["normal", "flagged", "malfunction"] as const;')
    w('    const h = Math.floor(r() * 18) + 5;')
    w('    const m = Math.floor(r() * 60);')
    w('    accessEvents.push({')
    w('      id: `AE-${String(i + 1).padStart(5, "0")}`,')
    w('      userId: `USR-${String(Math.floor(r() * 5000) + 1000)}`,')
    w('      userName: `${fn} ${ln}`,')
    w('      role: departments[Math.floor(r() * departments.length)],')
    w('      department: departments[Math.floor(r() * departments.length)],')
    w('      accessPoint: accessPoints[Math.floor(r() * accessPoints.length)],')
    w('      warehouse: wh.name, city: wh.city,')
    w('      accessType: types[typeIdx],')
    w('      method: accessMethods[Math.floor(r() * accessMethods.length)],')
    w('      timestamp: `2025-07-28 ${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(Math.floor(r() * 60)).padStart(2, "0")}`,')
    w('      zone: zones[Math.floor(r() * zones.length)],')
    w('      riskScore: Math.round(r() * 100),')
    w('      biometricMatch: Math.round((80 + r() * 20) * 10) / 10,')
    w('      deviceStatus: deviceStatuses[statusIdx],')
    w('    });')
    w('  }')
    w('')
    
    # Security Alerts (30)
    w('  // ---- Security Alerts (30) ----')
    w('  const securityAlerts: SecurityAlert[] = [];')
    w('  for (let i = 0; i < 30; i++) {')
    w('    const wh = warehouses[Math.floor(r() * warehouses.length)];')
    w('    const fn = guardFirstNames[Math.floor(r() * guardFirstNames.length)];')
    w('    const ln = guardLastNames[Math.floor(r() * guardLastNames.length)];')
    w('    const statusIdx = Math.floor(r() * 5);')
    w('    const statuses = ["open", "investigating", "resolved", "escalated", "false-alarm"] as const;')
    w('    const sevIdx = Math.floor(r() * 4);')
    w('    const sevs = ["critical", "high", "medium", "low"] as const;')
    w('    const h = Math.floor(r() * 14) + 6;')
    w('    const m = Math.floor(r() * 60);')
    w('    const respTime = Math.round(r() * 30);')
    w('    const causes = ["Unauthorized personnel", "Equipment malfunction", "False positive from AI", "Tailgating by staff", "Expired badge used", "Camera obstruction", "Network timeout", "Power surge", "Human error", "Unknown"];')
    w('    const actions = ["Guard dispatched", "CCTV footage reviewed", "Badge deactivated", "Lock changed", "Perimeter patrol increased", "System reboot", "Staff counselled", "Incident report filed", "Escalated to management", "False alarm logged"];')
    w('    securityAlerts.push({')
    w('      id: `SA-${String(i + 1).padStart(4, "0")}`,')
    w('      type: alertTypes[Math.floor(r() * alertTypes.length)],')
    w('      severity: sevs[sevIdx],')
    w('      source: ["CCTV AI", "Manual Report", "Badge System", "Motion Sensor", "Fire Panel", "Perimeter Alarm"][Math.floor(r() * 6)],')
    w('      location: cameraLocations[Math.floor(r() * cameraLocations.length)],')
    w('      warehouse: wh.name, city: wh.city,')
    w('      timestamp: `2025-07-28 ${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(Math.floor(r() * 60)).padStart(2, "0")}`,')
    w('      status: statuses[statusIdx],')
    w('      description: `${alertTypes[Math.floor(r() * alertTypes.length)]} detected at ${cameraLocations[Math.floor(r() * cameraLocations.length)]} during routine monitoring`,')
    w('      assignedTo: `${fn} ${ln}`,')
    w('      responseTime: respTime,')
    w('      resolvedAt: statuses[statusIdx] === "resolved" || statuses[statusIdx] === "false-alarm" ? `2025-07-28 ${String(h + Math.floor(respTime / 60)).padStart(2, "0")}:${String(m + respTime).padStart(2, "0")}` : "--",')
    w('      rootCause: causes[Math.floor(r() * causes.length)],')
    w('      correctiveAction: actions[Math.floor(r() * actions.length)],')
    w('      cameraRef: `CAM-${String(Math.floor(r() * 60) + 1).padStart(3, "0")}`,')
    w('      cctvFootage: r() > 0.2,')
    w('    });')
    w('  }')
    w('')
    
    # Chart data
    w('  // ---- Chart Data ----')
    w('  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];')
    w('  const monthlyGateData = months.map((m, i) => ({')
    w('    month: m,')
    w('    inbound: Math.floor(800 + r() * 600),')
    w('    outbound: Math.floor(700 + r() * 500),')
    w('    incidents: Math.floor(5 + r() * 20),')
    w('    avgResponseMin: Math.round((3 + r() * 10) * 10) / 10,')
    w('  }));')
    w('')
    w('  const categoryBreakdown = [')
    w('    { category: "Vehicle", value: Math.floor(r() * 300) + 200, color: COLORS.primary },')
    w('    { category: "Visitor", value: Math.floor(r() * 200) + 100, color: COLORS.secondary },')
    w('    { category: "Employee", value: Math.floor(r() * 500) + 300, color: COLORS.accent },')
    w('    { category: "Vendor", value: Math.floor(r() * 150) + 80, color: COLORS.danger },')
    w('    { category: "Delivery", value: Math.floor(r() * 250) + 150, color: COLORS.success },')
    w('  ];')
    w('')
    w('  const warehouseSecurityRadar = [')
    w('    { subject: "Gate Throughput", Mumbai: Math.floor(r() * 30) + 60, Delhi: Math.floor(r() * 30) + 60, Bengaluru: Math.floor(r() * 30) + 60 },')
    w('    { subject: "Response Time", Mumbai: Math.floor(r() * 30) + 60, Delhi: Math.floor(r() * 30) + 60, Bengaluru: Math.floor(r() * 30) + 60 },')
    w('    { subject: "CCTV Coverage", Mumbai: Math.floor(r() * 30) + 60, Delhi: Math.floor(r() * 30) + 60, Bengaluru: Math.floor(r() * 30) + 60 },')
    w('    { subject: "Access Compliance", Mumbai: Math.floor(r() * 30) + 60, Delhi: Math.floor(r() * 30) + 60, Bengaluru: Math.floor(r() * 30) + 60 },')
    w('    { subject: "Incident Resolution", Mumbai: Math.floor(r() * 30) + 60, Delhi: Math.floor(r() * 30) + 60, Bengaluru: Math.floor(r() * 30) + 60 },')
    w('    { subject: "Staff Training", Mumbai: Math.floor(r() * 30) + 60, Delhi: Math.floor(r() * 30) + 60, Bengaluru: Math.floor(r() * 30) + 60 },')
    w('  ];')
    w('')
    w('  const securityLevelDist = [')
    w('    { level: "Low", count: Math.floor(r() * 200) + 300, color: COLORS.success },')
    w('    { level: "Medium", count: Math.floor(r() * 150) + 150, color: COLORS.info },')
    w('    { level: "High", count: Math.floor(r() * 80) + 50, color: COLORS.accent },')
    w('    { level: "Critical", count: Math.floor(r() * 20) + 5, color: COLORS.danger },')
    w('  ];')
    w('')
    w('  const hourlyTrafficData = [];')
    w('  for (let h = 6; h <= 22; h++) {')
    w('    hourlyTrafficData.push({')
    w('      hour: `${h}:00`,')
    w('      inbound: h >= 7 && h <= 10 ? Math.floor(r() * 40) + 20 : Math.floor(r() * 15) + 5,')
    w('      outbound: h >= 16 && h <= 19 ? Math.floor(r() * 40) + 20 : Math.floor(r() * 10) + 3,')
    w('    });')
    w('  }')
    w('')
    w('  const alertTrendData = months.map((m) => ({')
    w('    month: m,')
    w('    critical: Math.floor(r() * 5) + 1,')
    w('    high: Math.floor(r() * 10) + 3,')
    w('    medium: Math.floor(r() * 15) + 5,')
    w('    low: Math.floor(r() * 20) + 10,')
    w('    resolved: Math.floor(r() * 30) + 15,')
    w('  }));')
    w('')
    w('  const accessMethodDist = [')
    w('    { method: "Badge", count: Math.floor(r() * 300) + 200, color: COLORS.primary },')
    w('    { method: "Biometric", count: Math.floor(r() * 200) + 150, color: COLORS.secondary },')
    w('    { method: "RFID", count: Math.floor(r() * 100) + 80, color: COLORS.accent },')
    w('    { method: "Mobile App", count: Math.floor(r() * 150) + 100, color: COLORS.success },')
    w('    { method: "PIN", count: Math.floor(r() * 80) + 30, color: COLORS.info },')
    w('    { method: "Manual", count: Math.floor(r() * 50) + 20, color: COLORS.purple },')
    w('  ];')
    w('')
    w('  return {')
    w('    gateEntries, securityGuards, cctvCameras, accessEvents, securityAlerts,')
    w('    monthlyGateData, categoryBreakdown, warehouseSecurityRadar, securityLevelDist, hourlyTrafficData, alertTrendData, accessMethodDist,')
    w('    months, gatePurposes, gateNames, checkpoints, specializations, certifications,')
    w('  };')
    w('}')
    w('')
    w('const data = generateData();')
    w('')
    
    # ===== COMPONENT =====
    w('export default function GateSecurityView() {')
    w('  const [activeTab, setActiveTab] = useState("dashboard");')
    w('  const [searchTerm, setSearchTerm] = useState("");')
    w('  const [statusFilter, setStatusFilter] = useState("all");')
    w('  const [categoryFilter, setCategoryFilter] = useState("all");')
    w('  const [securityLevelFilter, setSecurityLevelFilter] = useState("all");')
    w('  const [selectedEntry, setSelectedEntry] = useState<GateEntry | null>(null);')
    w('  const [selectedGuard, setSelectedGuard] = useState<SecurityGuard | null>(null);')
    w('  const [selectedCamera, setSelectedCamera] = useState<CCTVCamera | null>(null);')
    w('  const [selectedAlert, setSelectedAlert] = useState<SecurityAlert | null>(null);')
    w('  const [currentPage, setCurrentPage] = useState(1);')
    w('  const [sortField, setSortField] = useState<string>("id");')
    w('  const [sortDir, setSortDir] = useState<"asc" | "desc">("desc");')
    w('  const [alertFilter, setAlertFilter] = useState("all");')
    w('  const [alertSevFilter, setAlertSevFilter] = useState("all");')
    w('  const [cameraStatusFilter, setCameraStatusFilter] = useState("all");')
    w('  const [accessTypeFilter, setAccessTypeFilter] = useState("all");')
    w('  const [now, setNow] = useState(new Date());')
    w('')
    w('  useEffect(() => { const t = setInterval(() => setNow(new Date()), 1000); return () => clearInterval(t); }, []);')
    w('')
    w('  const perPage = 12;')
    w('')
    w('  // ---- Gate Entry Filtering & Sorting ----')
    w('  const filteredEntries = useMemo(() => {')
    w('    let result = data.gateEntries.filter((e) => {')
    w('      const matchSearch = !searchTerm || e.id.toLowerCase().includes(searchTerm.toLowerCase()) || e.entityName.toLowerCase().includes(searchTerm.toLowerCase()) || e.vehicleNo.toLowerCase().includes(searchTerm.toLowerCase()) || e.warehouse.toLowerCase().includes(searchTerm.toLowerCase());')
    w('      const matchStatus = statusFilter === "all" || e.status === statusFilter;')
    w('      const matchCat = categoryFilter === "all" || e.category === categoryFilter;')
    w('      const matchSec = securityLevelFilter === "all" || e.securityLevel === securityLevelFilter;')
    w('      return matchSearch && matchStatus && matchCat && matchSec;')
    w('    });')
    w('    result.sort((a, b) => {')
    w('      let va = a[sortField as keyof GateEntry]; let vb = b[sortField as keyof GateEntry];')
    w('      if (typeof va === "string" && typeof vb === "string") return sortDir === "asc" ? va.localeCompare(vb) : vb.localeCompare(va);')
    w('      if (typeof va === "number" && typeof vb === "number") return sortDir === "asc" ? va - vb : vb - va;')
    w('      return 0;')
    w('    });')
    w('    return result;')
    w('  }, [searchTerm, statusFilter, categoryFilter, securityLevelFilter, sortField, sortDir]);')
    w('')
    w('  const pagedEntries = filteredEntries.slice((currentPage - 1) * perPage, currentPage * perPage);')
    w('')
    w('  // ---- Guard Filtering ----')
    w('  const filteredGuards = useMemo(() => {')
    w('    return data.securityGuards.filter((g) => !searchTerm || g.name.toLowerCase().includes(searchTerm.toLowerCase()) || g.empCode.toLowerCase().includes(searchTerm.toLowerCase()) || g.warehouse.toLowerCase().includes(searchTerm.toLowerCase()));')
    w('  }, [searchTerm]);')
    w('')
    w('  // ---- Camera Filtering ----')
    w('  const filteredCameras = useMemo(() => {')
    w('    return data.cctvCameras.filter((c) => {')
    w('      const matchSearch = !searchTerm || c.id.toLowerCase().includes(searchTerm.toLowerCase()) || c.name.toLowerCase().includes(searchTerm.toLowerCase()) || c.warehouse.toLowerCase().includes(searchTerm.toLowerCase());')
    w('      const matchStatus = cameraStatusFilter === "all" || c.status === cameraStatusFilter;')
    w('      return matchSearch && matchStatus;')
    w('    });')
    w('  }, [searchTerm, cameraStatusFilter]);')
    w('')
    w('  // ---- Access Event Filtering ----')
    w('  const filteredAccess = useMemo(() => {')
    w('    return data.accessEvents.filter((e) => {')
    w('      const matchSearch = !searchTerm || e.id.toLowerCase().includes(searchTerm.toLowerCase()) || e.userName.toLowerCase().includes(searchTerm.toLowerCase()) || e.warehouse.toLowerCase().includes(searchTerm.toLowerCase());')
    w('      const matchType = accessTypeFilter === "all" || e.accessType === accessTypeFilter;')
    w('      return matchSearch && matchType;')
    w('    });')
    w('  }, [searchTerm, accessTypeFilter]);')
    w('')
    w('  // ---- Alert Filtering ----')
    w('  const filteredAlerts = useMemo(() => {')
    w('    return data.securityAlerts.filter((a) => {')
    w('      const matchSearch = !searchTerm || a.id.toLowerCase().includes(searchTerm.toLowerCase()) || a.type.toLowerCase().includes(searchTerm.toLowerCase()) || a.warehouse.toLowerCase().includes(searchTerm.toLowerCase());')
    w('      const matchStatus = alertFilter === "all" || a.status === alertFilter;')
    w('      const matchSev = alertSevFilter === "all" || a.severity === alertSevFilter;')
    w('      return matchSearch && matchStatus && matchSev;')
    w('    });')
    w('  }, [searchTerm, alertFilter, alertSevFilter]);')
    w('')
    w('  // ---- Sort Handler ----')
    w('  const handleSort = (field: string) => { if (sortField === field) setSortDir(sortDir === "asc" ? "desc" : "asc"); else { setSortField(field); setSortDir("desc"); } };')
    w('')
    w('  // ---- KPIs ----')
    w('  const kpis = [')
    w('    { label: "Total Entries Today", value: data.gateEntries.length.toString(), icon: <ScanLine size={18} />, color: COLORS.primary, trend: "+12%", up: true },')
    w('    { label: "Active Security Guards", value: data.securityGuards.filter(g => g.status === "on-duty").length.toString(), icon: <ShieldCheck size={18} />, color: COLORS.secondary, trend: "+3", up: true },')
    w('    { label: "CCTV Cameras Online", value: data.cctvCameras.filter(c => c.status === "online" || c.status === "recording").length.toString(), icon: <Camera size={18} />, color: COLORS.accent, trend: "-2", up: false },')
    w('    { label: "Open Alerts", value: data.securityAlerts.filter(a => a.status === "open" || a.status === "investigating").length.toString(), icon: <AlertTriangle size={18} />, color: COLORS.danger, trend: "+5", up: true },')
    w('    { label: "Denied Entries", value: data.gateEntries.filter(e => e.status === "denied").length.toString(), icon: <XCircle size={18} />, color: COLORS.purple, trend: "-3", up: false },')
    w('    { label: "Avg Response (min)", value: (data.securityAlerts.reduce((s, a) => s + a.responseTime, 0) / data.securityAlerts.length).toFixed(1), icon: <Timer size={18} />, color: COLORS.info, trend: "-0.5m", up: false },')
    w('  ];')
    w('')
    # ---- Helper functions ----
    w('  const statusBadge = (status: string) => {')
    w('    const map: Record<string, string> = {')
    w('      "checked-in": "gse-badge-green", "checked-out": "gse-badge-blue", "pending": "gse-badge-amber", "denied": "gse-badge-red", "blacklisted": "gse-badge-red",')
    w('      "on-duty": "gse-badge-green", "on-break": "gse-badge-amber", "off-duty": "gse-badge-gray", "training": "gse-badge-purple",')
    w('      "online": "gse-badge-green", "offline": "gse-badge-red", "maintenance": "gse-badge-amber", "recording": "gse-badge-blue", "alert": "gse-badge-red",')
    w('      "open": "gse-badge-red", "investigating": "gse-badge-amber", "resolved": "gse-badge-green", "escalated": "gse-badge-red", "false-alarm": "gse-badge-gray",')
    w('      "entry": "gse-badge-green", "exit": "gse-badge-blue", "denied": "gse-badge-red", "forced": "gse-badge-red", "tamper": "gse-badge-amber",')
    w('    };')
    w('    return map[status] || "gse-badge-gray";')
    w('  };')
    w('')
    w('  const secLevelBadge = (level: string) => {')
    w('    const map: Record<string, string> = { low: "gse-badge-green", medium: "gse-badge-blue", high: "gse-badge-amber", critical: "gse-badge-red" };')
    w('    return map[level] || "gse-badge-gray";')
    w('  };')
    w('')
    # ---- Drawer Components ----
    # Entry Drawer
    w('  const renderEntryDrawer = () => {')
    w('    if (!selectedEntry) return null;')
    w('    const e = selectedEntry;')
    w('    return (')
    w('      <>')
    w('        <div className="gse-drawer-overlay" onClick={() => setSelectedEntry(null)} />')
    w('        <div className="gse-drawer-panel">')
    w('          <div className="gse-drawer-header">')
    w('            <div className="gse-drawer-header-left">')
    w('              <ScanLine size={22} />')
    w('              <div>')
    w('                <h3>Gate Entry {e.id}</h3>')
    w('                <span className="gse-drawer-subtitle">{e.warehouse} | {e.gateNo}</span>')
    w('              </div>')
    w('            </div>')
    w('            <button className="gse-drawer-close" onClick={() => setSelectedEntry(null)}><XCircle size={20} /></button>')
    w('          </div>')
    w('          <div className="gse-drawer-body">')
    w('            <div className="gse-drawer-field-grid">')
    w('              {[["Entity", e.entityName], ["Phone", e.entityPhone], ["Category", e.category.charAt(0).toUpperCase() + e.category.slice(1)], ["Vehicle No", e.vehicleNo], ["Purpose", e.purpose], ["Gate", e.gateNo], ["Checkpoint", e.checkpoint], ["City", e.city + ", " + e.state], ["Check In", e.checkInTime], ["Check Out", e.checkOutTime], ["Duration", formatDuration(e.duration)], ["Badge No", e.badgeNo], ["Temperature", e.temperature + "\\u00B0C" + (e.temperaturePass ? " \\u2713" : " \\u2717")], ["Security Level", e.securityLevel.charAt(0).toUpperCase() + e.securityLevel.slice(1)], ["Escort Required", e.escortRequired ? "Yes" : "No"], ["Items Carried", e.itemsCarried.toString()]].map(([label, val]) => (')
    w('                <div className="gse-drawer-field" key={label}><span className="gse-field-label">{label}</span><span className="gse-field-value">{val}</span></div>')
    w('              ))}')
    w('            </div>')
    w('            <div className="gse-drawer-metrics">')
    w('              <div className="gse-metric-card" style={{ borderLeft: `4px solid ${COLORS.primary}` }}><span className="gse-metric-label">Status</span><span className="gse-metric-value"><span className={statusBadge(e.status)}>{e.status.replace("-", " ").toUpperCase()}</span></span></div>')
    w('              <div className="gse-metric-card" style={{ borderLeft: `4px solid ${COLORS.secondary}` }}><span className="gse-metric-label">Type</span><span className="gse-metric-value">{e.type.toUpperCase()}</span></div>')
    w('              <div className="gse-metric-card" style={{ borderLeft: `4px solid ${COLORS.accent}` }}><span className="gse-metric-label">Escort</span><span className="gse-metric-value">{e.escortName}</span></div>')
    w('            </div>')
    w('            {e.remarks && <div className="gse-drawer-notes"><span className="gse-notes-label">Remarks</span><p className="gse-notes-text">{e.remarks}</p></div>}')
    w('            <div className="gse-drawer-actions">')
    w('              <button className="gse-action-btn gse-action-primary"><CheckCircle2 size={16} /> Approve Entry</button>')
    w('              <button className="gse-action-btn gse-action-danger"><XCircle size={16} /> Deny Entry</button>')
    w('              <button className="gse-action-btn gse-action-secondary"><ClipboardList size={16} /> Log Incident</button>')
    w('            </div>')
    w('          </div>')
    w('        </div>')
    w('      </>')
    w('    );')
    w('  };')
    w('')
    
    # Guard Drawer
    w('  const renderGuardDrawer = () => {')
    w('    if (!selectedGuard) return null;')
    w('    const g = selectedGuard;')
    w('    return (')
    w('      <>')
    w('        <div className="gse-drawer-overlay" onClick={() => setSelectedGuard(null)} />')
    w('        <div className="gse-drawer-panel">')
    w('          <div className="gse-drawer-header">')
    w('            <div className="gse-drawer-header-left">')
    w('              <ShieldCheck size={22} />')
    w('              <div>')
    w('                <h3>{g.name}</h3>')
    w('                <span className="gse-drawer-subtitle">{g.empCode} | {g.rank.replace("-", " ").toUpperCase()}</span>')
    w('              </div>')
    w('            </div>')
    w('            <button className="gse-drawer-close" onClick={() => setSelectedGuard(null)}><XCircle size={20} /></button>')
    w('          </div>')
    w('          <div className="gse-drawer-body">')
    w('            <div className="gse-drawer-field-grid">')
    w('              '{[["Phone', g.phone], ["Shift", g.shift.toUpperCase()], ["Gate Assigned", g.gateAssigned], ["Warehouse", g.warehouse], ["City", g.city], ["Age", g.age.toString()], ["Gender", g.gender], ["Last Training", g.lastTraining], ["License Expiry", g.licenseExpiry], ["Rank", g.rank.replace("-", " ").toUpperCase()]].map(([label, val]) => (')
    w('                <div className="gse-drawer-field" key={label}><span className="gse-field-label">{label}</span><span className="gse-field-value">{val}</span></div>')
    w('              ))}')
    w('            </div>')
    w('            <div className="gse-drawer-metrics">')
    w('              <div className="gse-metric-card" style={{ borderLeft: `4px solid ${COLORS.primary}` }}><span className="gse-metric-label">Checks Today</span><span className="gse-metric-value">{g.checksToday}</span></div>')
    w('              <div className="gse-metric-card" style={{ borderLeft: `4px solid ${COLORS.secondary}` }}><span className="gse-metric-label">Compliance Score</span><span className="gse-metric-value">{g.complianceScore}%</span></div>')
    w('              <div className="gse-metric-card" style={{ borderLeft: `4px solid ${COLORS.accent}` }}><span className="gse-metric-label">Incidents Handled</span><span className="gse-metric-value">{g.incidentsHandled}</span></div>')
    w('            </div>')
    w('            <div className="gse-drawer-tags">')
    w('              <span className="gse-tag-label">Specializations</span>')
    w('              <div className="gse-tag-container">{g.specialization.map((s) => <span className="gse-tag" key={s}>{s.replace(/-/g, " ")}</span>)}</div>')
    w('            </div>')
    w('            <div className="gse-drawer-tags">')
    w('              <span className="gse-tag-label">Certifications</span>')
    w('              <div className="gse-tag-container">{g.certifications.map((c) => <span className="gse-tag gse-tag-cert" key={c}>{c}</span>)}</div>')
    w('            </div>')
    w('            <div className="gse-drawer-actions">')
    w('              <button className="gse-action-btn gse-action-primary"><UserCheck size={16} /> Assign Shift</button>')
    w('              <button className="gse-action-btn gse-action-secondary"><ClipboardList size={16} });"> Schedule Training</button>')
    w('            </div>')
    w('          </div>')
    w('        </div>')
    w('      </>')
    w('    );')
    w('  };')
    w('')
    
    # Camera Drawer
    w('  const renderCameraDrawer = () => {')
    w('    if (!selectedCamera) return null;')
    w('    const c = selectedCamera;')
    w('    return (')
    w('      <>')
    w('        <div className="gse-drawer-overlay" onClick={() => setSelectedCamera(null)} />')
    w('        <div className="gse-drawer-panel">')
    w('          <div className="gse-drawer-header">')
    w('            <div className="gse-drawer-header-left">')
    w('              <Camera size={22} />')
    w('              <div>')
    w('                <h3>{c.name}</h3>')
    w('                <span className="gse-drawer-subtitle">{c.id} | {c.warehouse}</span>')
    w('              </div>')
    w('            </div>')
    w('            <button className="gse-drawer-close" onClick={() => setSelectedCamera(null)}><XCircle size={20} /></button>')
    w('          </div>')
    w('          <div className="gse-drawer-body">')
    w('            <div className="gse-drawer-field-grid">')
    w('              '{[["Location', c.location], ["Type", c.type.toUpperCase()], ["Resolution", c.resolution], ["FOV", c.fov], ["City", c.city], ["IP Address", c.ipAddress], ["Last Maintenance", c.lastMaintenance], ["Storage Days", c.storageDays + " days"], ["Recording Hours", c.recordingHours + "h/day"], ["Alerts Today", c.alertsToday.toString()]].map(([label, val]) => (')
    w('                <div className="gse-drawer-field" key={label}><span className="gse-field-label">{label}</span><span className="gse-field-value">{val}</span></div>')
    w('              ))}')
    w('            </div>')
    w('            <div className="gse-drawer-metrics">')
    w('              <div className="gse-metric-card" style={{ borderLeft: `4px solid ${COLORS.primary}` }}><span className="gse-metric-label">Uptime</span><span className="gse-metric-value">{c.uptime}%</span></div>')
    w('              <div className="gse-metric-card" style={{ borderLeft: `4px solid ${COLORS.success}` }}><span className="gse-metric-label">Night Vision</span><span className="gse-metric-value">{c.nightVision ? "Enabled" : "Disabled"}</span></div>')
    w('              <div className="gse-metric-card" style={{ borderLeft: `4px solid ${COLORS.secondary}` }}><span className="gse-metric-label">AI Enabled</span><span className="gse-metric-value">{c.aiEnabled ? "Enabled" : "Disabled"}</span></div>')
    w('            </div>')
    w('            <div className="gse-drawer-actions">')
    w('              <button className="gse-action-btn gse-action-primary"><Eye size={16} /> View Live Feed</button>')
    w('              <button className="gse-action-btn gse-action-secondary"><FileText size={16} });"> Download Footage</button>')
    w('              <button className="gse-action-btn gse-action-danger"><AlertTriangle size={16} /> Report Issue</button>')
    w('            </div>')
    w('          </div>')
    w('        </div>')
    w('      </>')
    w('    );')
    w('  };')
    w('')
    
    # Alert Drawer
    w('  const renderAlertDrawer = () => {')
    w('    if (!selectedAlert) return null;')
    w('    const a = selectedAlert;')
    w('    return (')
    w('      <>')
    w('        <div className="gse-drawer-overlay" onClick={() => setSelectedAlert(null)} />')
    w('        <div className="gse-drawer-panel">')
    w('          <div className="gse-drawer-header">')
    w('            <div className="gse-drawer-header-left">')
    w('              <AlertTriangle size={22} />')
    w('              <div>')
    w('                <h3>Alert {a.id}</h3>')
    w('                <span className="gse-drawer-subtitle">{a.type} | {a.severity.toUpperCase()}</span>')
    w('              </div>')
    w('            </div>')
    w('            <button className="gse-drawer-close" onClick={() => setSelectedAlert(null)}><XCircle size={20} /></button>')
    w('          </div>')
    w('          <div className="gse-drawer-body">')
    w('            <div className="gse-drawer-field-grid">')
    w('              '{[["Source', a.source], ["Location", a.location], ["Warehouse", a.warehouse], ["City", a.city], ["Timestamp", a.timestamp], ["Assigned To", a.assignedTo], ["Response Time", a.responseTime + " min"], ["Camera Ref", a.cameraRef], ["CCTV Footage", a.cctvFootage ? "Available" : "Not Available"], ["Resolved At", a.resolvedAt], ["Status", a.status.replace("-", " ").toUpperCase()]].map(([label, val]) => (')
    w('                <div className="gse-drawer-field" key={label}><span className="gse-field-label">{label}</span><span className="gse-field-value">{val}</span></div>')
    w('              ))}')
    w('            </div>')
    w('            <div className="gse-drawer-metrics">')
    w('              <div className="gse-metric-card" style={{ borderLeft: `4px solid ${COLORS.danger}` }}><span className="gse-metric-label">Severity</span><span className="gse-metric-value"><span className={statusBadge(a.severity === "critical" ? "denied" : a.severity === "high" ? "pending" : a.severity === "medium" ? "checked-in" : "checked-out")}>{a.severity.toUpperCase()}</span></span></div>')
    w('              <div className="gse-metric-card" style={{ borderLeft: `4px solid ${COLORS.accent}` }}><span className="gse-metric-label">Risk Level</span><span className="gse-metric-value">{a.severity === "critical" ? "EXTREME" : a.severity === "high" ? "HIGH" : a.severity === "medium" ? "MODERATE" : "LOW"}</span></div>')
    w('              <div className="gse-metric-card" style={{ borderLeft: `4px solid ${COLORS.info}` }}><span className="gse-metric-label">Response</span><span className="gse-metric-value">{a.responseTime} min</span></div>')
    w('            </div>')
    w('            <div className="gse-drawer-notes"><span className="gse-notes-label">Description</span><p className="gse-notes-text">{a.description}</p></div>')
    w('            <div className="gse-drawer-notes"><span className="gse-notes-label">Root Cause</span><p className="gse-notes-text">{a.rootCause}</p></div>')
    w('            <div className="gse-drawer-notes"><span className="gse-notes-label">Corrective Action</span><p className="gse-notes-text">{a.correctiveAction}</p></div>')
    w('            <div className="gse-drawer-actions">')
    w('              <button className="gse-action-btn gse-action-primary"><CheckCircle2 size={16} /> Resolve Alert</button>')
    w('              <button className="gse-action-btn gse-action-danger"><ArrowUpRight size={16} /> Escalate</button>')
    w('              <button className="gse-action-btn gse-action-secondary"><FileText size={16} });"> Generate Report</button>')
    w('            </div>')
    w('          </div>')
    w('        </div>')
    w('      </>')
    w('    );')
    w('  };')
    w('')
    
    # ===== TAB 0: DASHBOARD =====
    w('  // ===== TAB 0: DASHBOARD =====')
    w('  const renderDashboard = () => (')
    w('    <div className="gse-tab-content">')
    w('      <div className="gse-live-clock">')
    w('        <Clock size={16} />')
    w('        <span>{now.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: true })}</span>')
    w('        <span className="gse-clock-date">{now.toLocaleDateString("en-IN", { weekday: "short", day: "numeric", month: "short", year: "numeric" })}</span>')
    w('      </div>')
    w('      <div className="gse-kpi-grid">{kpis.map((k) => (')
    w('        <div className="gse-kpi-card" key={k.label}>')
    w('          <div className="gse-kpi-icon" style={{ backgroundColor: k.color + "18" }}><span style={{ color: k.color }}>{k.icon}</span></div>')
    w('          <div className="gse-kpi-info"><span className="gse-kpi-value">{k.value}</span><span className="gse-kpi-label">{k.label}</span></div>')
    w('          <span className={`gse-kpi-trend ${k.up ? "gse-trend-up" : "gse-trend-down"}`}>{k.up ? <ArrowUpRight size={14} /> : <ArrowDownRight size={14} />}{k.trend}</span>')
    w('        </div>')
    w('      ))}</div>')
    w('      <div className="gse-charts-grid">')
    w('        <div className="gse-chart-card gse-chart-lg">')
    w('          <h4 className="gse-chart-title">Monthly Gate Traffic & Incidents</h4>')
    w('          <ResponsiveContainer width="100%" height={280}>')
    w('            <ComposedChart data={data.monthlyGateData}>')
    w('              <CartesianGrid strokeDasharray="3 3" stroke="#334155" />')
    w('              <XAxis dataKey="month" tick={{ fill: "#94a3b8", fontSize: 12 }} />')
    w('              <YAxis tick={{ fill: "#94a3b8", fontSize: 12 }} />')
    w('              <Tooltip contentStyle={{ backgroundColor: "#1e293b", border: "1px solid #334155", borderRadius: 8 }} />')
    w('              <Legend />')
    w('              <Bar dataKey="inbound" name="Inbound" fill={COLORS.primary} radius={[4,4,0,0]} />')
    w('              <Bar dataKey="outbound" name="Outbound" fill={COLORS.secondary} radius={[4,4,0,0]} />')
    w('              <Bar dataKey="incidents" name="Incidents" fill={COLORS.danger} radius={[4,4,0,0]} />')
    w('              <Line type="monotone" dataKey="avgResponseMin" name="Avg Response (min)" stroke={COLORS.accent} strokeWidth={2} />')
    w('            </ComposedChart>')
    w('          </ResponsiveContainer>')
    w('        </div>')
    w('        <div className="gse-chart-card">')
    w('          <h4 className="gse-chart-title">Entry Category Distribution</h4>')
    w('          <ResponsiveContainer width="100%" height={260}>')
    w('            <PieChart><Pie data={data.categoryBreakdown} cx="50%" cy="50%" outerRadius={80} dataKey="value" nameKey="category" label={({ category, percent }) => `${category} ${(percent * 100).toFixed(0)}%`}><Cell fill={COLORS.primary} /><Cell fill={COLORS.secondary} /><Cell fill={COLORS.accent} /><Cell fill={COLORS.danger} /><Cell fill={COLORS.success} /></Pie><Tooltip contentStyle={{ backgroundColor: "#1e293b", border: "1px solid #334155", borderRadius: 8 }} /></PieChart>')
    w('          </ResponsiveContainer>')
    w('        </div>')
    w('        <div className="gse-chart-card">')
    w('          <h4 className="gse-chart-title">Warehouse Security Radar</h4>')
    w('          <ResponsiveContainer width="100%" height={260}>')
    w('            <RadarChart data={data.warehouseSecurityRadar}>')
    w('              <PolarGrid stroke="#334155" />')
    w('              <PolarAngleAxis dataKey="subject" tick={{ fill: "#94a3b8", fontSize: 10 }} />')
    w('              <PolarRadiusAxis angle={30} domain={[0, 100]} tick={{ fill: "#94a3b8", fontSize: 10 }} />')
    w('              <Radar name="Mumbai" dataKey="Mumbai" stroke={COLORS.primary} fill={COLORS.primary} fillOpacity={0.15} />')
    w('              <Radar name="Delhi NCR" dataKey="Delhi" stroke={COLORS.secondary} fill={COLORS.secondary} fillOpacity={0.15} />')
    w('              <Radar name="Bengaluru" dataKey="Bengaluru" stroke={COLORS.accent} fill={COLORS.accent} fillOpacity={0.15} />')
    w('              <Legend />')
    w('              <Tooltip contentStyle={{ backgroundColor: "#1e293b", border: "1px solid #334155", borderRadius: 8 }} />')
    w('            </RadarChart>')
    w('          </ResponsiveContainer>')
    w('        </div>')
    w('        <div className="gse-chart-card">')
    w('          <h4 className="gse-chart-title">Security Level Distribution</h4>')
    w('          <ResponsiveContainer width="100%" height={260}>')
    w('            <BarChart data={data.securityLevelDist}><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis dataKey="level" tick={{ fill: "#94a3b8", fontSize: 12 }} /><YAxis tick={{ fill: "#94a3b8", fontSize: 12 }} /><Tooltip contentStyle={{ backgroundColor: "#1e293b", border: "1px solid #334155", borderRadius: 8 }} /><Bar dataKey="count" name="Entries" radius={[4,4,0,0]}>{data.securityLevelDist.map((d, i) => <Cell key={i} fill={d.color} />)}</Bar></BarChart>')
    w('          </ResponsiveContainer>')
    w('        </div>')
    w('        <div className="gse-chart-card">')
    w('          <h4 className="gse-chart-title">Hourly Traffic Flow</h4>')
    w('          <ResponsiveContainer width="100%" height={260}>')
    w('            <AreaChart data={data.hourlyTrafficData}><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis dataKey="hour" tick={{ fill: "#94a3b8", fontSize: 11 }} /><YAxis tick={{ fill: "#94a3b8", fontSize: 12 }} /><Tooltip contentStyle={{ backgroundColor: "#1e293b", border: "1px solid #334155", borderRadius: 8 }} /><Legend /><Area type="monotone" dataKey="inbound" name="Inbound" stroke={COLORS.primary} fill={COLORS.primary} fillOpacity={0.2} /><Area type="monotone" dataKey="outbound" name="Outbound" stroke={COLORS.secondary} fill={COLORS.secondary} fillOpacity={0.2} /></AreaChart>')
    w('          </ResponsiveContainer>')
    w('        </div>')
    w('      </div>')
    w('    </div>')
    w('  );')
    w('')
    
    # ===== TAB 1: GATE ENTRIES =====
    w('  // ===== TAB 1: GATE ENTRIES =====')
    w('  const renderGateEntries = () => (')
    w('    <div className="gse-tab-content">')
    w('      <div className="gse-section-header">')
    w('        <h3 className="gse-section-title">Gate Entry Log</h3>')
    w('        <div className="gse-filters">')
    w('          <div className="gse-search-box"><Search size={16} /><input type="text" placeholder="Search by ID, name, vehicle, warehouse..." value={searchTerm} onChange={(e) => { setSearchTerm(e.target.value); setCurrentPage(1); }} /></div>')
    w('          <select className="gse-filter-select" value={statusFilter} onChange={(e) => { setStatusFilter(e.target.value); setCurrentPage(1); }}><option value="all">All Status</option><option value="checked-in">Checked In</option><option value="checked-out">Checked Out</option><option value="pending">Pending</option><option value="denied">Denied</option><option value="blacklisted">Blacklisted</option></select>')
    w('          <select className="gse-filter-select" value={categoryFilter} onChange={(e) => { setCategoryFilter(e.target.value); setCurrentPage(1); }}><option value="all">All Categories</option><option value="vehicle">Vehicle</option><option value="visitor">Visitor</option><option value="employee">Employee</option><option value="vendor">Vendor</option><option value="delivery">Delivery</option></select>')
    w('          <select className="gse-filter-select" value={securityLevelFilter} onChange={(e) => { setSecurityLevelFilter(e.target.value); setCurrentPage(1); }}><option value="all">All Security Levels</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select>')
    w('        </div>')
    w('      </div>')
    w('      <div className="gse-table-wrapper">')
    w('        <table className="gse-table">')
    w('          <thead><tr>')
    w('            {["ID", "Type", "Category", "Entity", "Vehicle No", "Purpose", "Gate", "Warehouse", "Security", "Check In", "Status"].map((h) => (')
    w('              <th key={h} className="gse-sortable-th" onClick={() => handleSort(h === "ID" ? "id" : h === "Type" ? "type" : h === "Category" ? "category" : h === "Entity" ? "entityName" : h === "Vehicle No" ? "vehicleNo" : h === "Purpose" ? "purpose" : h === "Gate" ? "gateNo" : h === "Warehouse" ? "warehouse" : h === "Security" ? "securityLevel" : h === "Check In" ? "checkInTime" : "status")}>{h}{sortField === (h === "ID" ? "id" : h === "Entity" ? "entityName" : h.toLowerCase().replace(" ", "")) && <span className="gse-sort-icon">{sortDir === "asc" ? "▲" : "▼"}</span>}</th>')
    w('            ))}')
    w('          </tr></thead>')
    w('          <tbody>')
    w('            {pagedEntries.map((e) => (')
    w('              <tr key={e.id} className="gse-table-row" onClick={() => setSelectedEntry(e)}>')
    w('                <td className="gse-mono">{e.id}</td>')
    w('                <td><span className={`gse-type-badge ${e.type === "inbound" ? "gse-type-in" : "gse-type-out"}`}>{e.type === "inbound" ? "▼ IN" : "▲ OUT"}</span></td>')
    w('                <td>{e.category.charAt(0).toUpperCase() + e.category.slice(1)}</td>')
    w('                <td className="gse-bold">{e.entityName}</td>')
    w('                <td className="gse-mono">{e.vehicleNo}</td>')
    w('                <td>{e.purpose}</td>')
    w('                <td>{e.gateNo}</td>')
    w('                <td>{e.city}</td>')
    w('                <td><span className={secLevelBadge(e.securityLevel)}>{e.securityLevel.toUpperCase()}</span></td>')
    w('                <td className="gse-mono">{e.checkInTime}</td>')
    w('                <td><span className={statusBadge(e.status)}>{e.status.replace("-", " ")}</span></td>')
    w('              </tr>')
    w('            ))}')
    w('          </tbody>')
    w('        </table>')
    w('      </div>')
    w('      <div className="gse-pagination">')
    w('        <span className="gse-page-info">Showing {(currentPage - 1) * perPage + 1}-{Math.min(currentPage * perPage, filteredEntries.length)} of {filteredEntries.length}</span>')
    w('        <div className="gse-page-buttons">')
    w('          <button className="gse-page-btn" disabled={currentPage === 1} onClick={() => setCurrentPage(1)}>First</button>')
    w('          <button className="gse-page-btn" disabled={currentPage === 1} onClick={() => setCurrentPage(currentPage - 1)}>Prev</button>')
    w('          <button className="gse-page-btn gse-page-active">{currentPage}</button>')
    w('          <button className="gse-page-btn" disabled={currentPage >= Math.ceil(filteredEntries.length / perPage)} onClick={() => setCurrentPage(currentPage + 1)}>Next</button>')
    w('          <button className="gse-page-btn" disabled={currentPage >= Math.ceil(filteredEntries.length / perPage)} onClick={() => setCurrentPage(Math.ceil(filteredEntries.length / perPage))}>Last</button>')
    w('        </div>')
    w('      </div>')
    w('    </div>')
    w('  );')
    w('')
    
    # ===== TAB 2: SECURITY PERSONNEL =====
    w('  // ===== TAB 2: SECURITY PERSONNEL =====')
    w('  const renderSecurityPersonnel = () => {')
    w('    const onDutyCount = data.securityGuards.filter(g => g.status === "on-duty").length;')
    w('    const onBreakCount = data.securityGuards.filter(g => g.status === "on-break").length;')
    w('    const avgCompliance = (data.securityGuards.reduce((s, g) => s + g.complianceScore, 0) / data.securityGuards.length).toFixed(1);')
    w('    return (')
    w('      <div className="gse-tab-content">')
    w('        <div className="gse-section-header">')
    w('          <h3 className="gse-section-title">Security Personnel</h3>')
    w('          <div className="gse-filters">')
    w('            <div className="gse-search-box"><Search size={16} /><input type="text" placeholder="Search by name, code, warehouse..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} /></div>')
    w('          </div>')
    w('        </div>')
    w('        <div className="gse-guard-stats">')
    w('          <div className="gse-guard-stat-card"><span className="gse-guard-stat-value">{data.securityGuards.length}</span><span className="gse-guard-stat-label">Total Guards</span></div>')
    w('          <div className="gse-guard-stat-card"><span className="gse-guard-stat-value" style={{ color: COLORS.success }}>{onDutyCount}</span><span className="gse-guard-stat-label">On Duty</span></div>')
    w('          <div className="gse-guard-stat-card"><span className="gse-guard-stat-value" style={{ color: COLORS.accent }}>{onBreakCount}</span><span className="gse-guard-stat-label">On Break</span></div>')
    w('          <div className="gse-guard-stat-card"><span className="gse-guard-stat-value">{avgCompliance}%</span><span className="gse-guard-stat-label">Avg Compliance</span></div>')
    w('        </div>')
    w('        <div className="gse-card-grid">')
    w('          {filteredGuards.map((g) => (')
    w('            <div className="gse-guard-card" key={g.id} onClick={() => setSelectedGuard(g)}>')
    w('              <div className="gse-guard-card-header">')
    w('                <div className="gse-guard-avatar">{g.name.split(" ").map(n => n[0]).join("").slice(0, 2)}</div>')
    w('                <div className="gse-guard-card-info">')
    w('                  <span className="gse-guard-name">{g.name}</span>')
    w('                  <span className="gse-guard-code">{g.empCode} | {g.rank.replace("-", " ")}</span>')
    w('                </div>')
    w('                <span className={`gse-guard-status-dot ${g.status === "on-duty" ? "gse-dot-green" : g.status === "on-break" ? "gse-dot-amber" : "gse-dot-gray"}`} title={g.status} />')
    w('              </div>')
    w('              <div className="gse-guard-card-details">')
    w('                <div className="gse-guard-detail-row"><MapPin size={14} /><span>{g.warehouse} | {g.gateAssigned}</span></div>')
    w('                <div className="gse-guard-detail-row"><Clock size={14} /><span>{g.shift.toUpperCase()} Shift</span></div>')
    w('              </div>')
    w('              <div className="gse-guard-card-bars">')
    w('                <div className="gse-bar-row"><span>Compliance</span><div className="gse-bar-bg"><div className="gse-bar-fill" style={{ width: `${g.complianceScore}%`, backgroundColor: g.complianceScore >= 85 ? COLORS.success : g.complianceScore >= 70 ? COLORS.accent : COLORS.danger }} /></div><span>{g.complianceScore}%</span></div>')
    w('                <div className="gse-bar-row"><span>Checks Today</span><div className="gse-bar-bg"><div className="gse-bar-fill" style={{ width: `${Math.min(g.checksToday, 80) / 80 * 100}%`, backgroundColor: COLORS.secondary }} /></div><span>{g.checksToday}</span></div>')
    w('              </div>')
    w('              <div className="gse-guard-card-tags">{g.specialization.slice(0, 2).map((s) => <span className="gse-mini-tag" key={s}>{s.replace(/-/g, " ")}</span>)}</div>')
    w('            </div>')
    w('          ))}')
    w('        </div>')
    w('      </div>')
    w('    );')
    w('  };')
    w('')
    
    # ===== TAB 3: CCTV SURVEILLANCE =====
    w('  // ===== TAB 3: CCTV SURVEILLANCE =====')
    w('  const renderCCTV = () => {')
    w('    const onlineCount = data.cctvCameras.filter(c => c.status === "online" || c.status === "recording").length;')
    w('    const offlineCount = data.cctvCameras.filter(c => c.status === "offline").length;')
    w('    const aiCount = data.cctvCameras.filter(c => c.aiEnabled).length;')
    w('    return (')
    w('      <div className="gse-tab-content">')
    w('        <div className="gse-section-header">')
    w('          <h3 className="gse-section-title">CCTV Surveillance</h3>')
    w('          <div className="gse-filters">')
    w('            <div className="gse-search-box"><Search size={16} /><input type="text" placeholder="Search by camera ID, name, warehouse..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} /></div>')
    w('            <select className="gse-filter-select" value={cameraStatusFilter} onChange={(e) => setCameraStatusFilter(e.target.value)}><option value="all">All Status</option><option value="online">Online</option><option value="recording">Recording</option><option value="offline">Offline</option><option value="maintenance">Maintenance</option><option value="alert">Alert</option></select>')
    w('          </div>')
    w('        </div>')
    w('        <div className="gse-cctv-stats">')
    w('          <div className="gse-cctv-stat-card"><Monitor size={22} style={{ color: COLORS.primary }} /><div><span className="gse-cctv-stat-value">{data.cctvCameras.length}</span><span className="gse-cctv-stat-label">Total Cameras</span></div></div>')
    w('          <div className="gse-cctv-stat-card"><Eye size={22} style={{ color: COLORS.success }} /><div><span className="gse-cctv-stat-value">{onlineCount}</span><span className="gse-cctv-stat-label">Online/Recording</span></div></div>')
    w('          <div className="gse-cctv-stat-card"><XCircle size={22} style={{ color: COLORS.danger }} /><div><span className="gse-cctv-stat-value">{offlineCount}</span><span className="gse-cctv-stat-label">Offline</span></div></div>')
    w('          <div className="gse-cctv-stat-card"><Fingerprint size={22} style={{ color: COLORS.secondary }} /><div><span className="gse-cctv-stat-value">{aiCount}</span><span className="gse-cctv-stat-label">AI-Enabled</span></div></div>')
    w('        </div>')
    w('        <div className="gse-card-grid">')
    w('          {filteredCameras.map((c) => (')
    w('            <div className="gse-camera-card" key={c.id} onClick={() => setSelectedCamera(c)}>')
    w('              <div className="gse-camera-card-header">')
    w('                <div className="gse-camera-icon-wrapper">')
    w('                  <Camera size={20} />')
    w('                </div>')
    w('                <div className="gse-camera-card-info">')
    w('                  <span className="gse-camera-name">{c.id} - {c.name}</span>')
    w('                  <span className="gse-camera-location">{c.warehouse} | {c.location}</span>')
    w('                </div>')
    w('                <span className={statusBadge(c.status)}>{c.status.toUpperCase()}</span>')
    w('              </div>')
    w('              <div className="gse-camera-card-details">')
    w('                <div className="gse-camera-detail-item"><span>Type</span><span className="gse-camera-badge">{c.type.toUpperCase()}</span></div>')
    w('                <div className="gse-camera-detail-item"><span>Resolution</span><span>{c.resolution}</span></div>')
    w('                <div className="gse-camera-detail-item"><span>FOV</span><span>{c.fov}</span></div>')
    w('                <div className="gse-camera-detail-item"><span>Storage</span><span>{c.storageDays} days</span></div>')
    w('              </div>')
    w('              <div className="gse-camera-card-bars">')
    w('                <div className="gse-bar-row"><span>Uptime</span><div className="gse-bar-bg"><div className="gse-bar-fill" style={{ width: `${c.uptime}%`, backgroundColor: c.uptime >= 95 ? COLORS.success : c.uptime >= 90 ? COLORS.accent : COLORS.danger }} /></div><span>{c.uptime}%</span></div>')
    w('              </div>')
    w('              <div className="gse-camera-card-features">')
    w('                {c.nightVision && <span className="gse-camera-feature"><Eye size={14} /> Night Vision</span>}')
    w('                {c.aiEnabled && <span className="gse-camera-feature gse-ai-badge"><Fingerprint size={14} /> AI Enabled</span>}')
    w('              </div>')
    w('              <div className="gse-camera-card-footer">')
    w('                <span className="gse-mono">IP: {c.ipAddress}</span>')
    w('                <span className="gse-mono">Recording: {c.recordingHours}h/day</span>')
    w('              </div>')
    w('            </div>')
    w('          ))}')
    w('        </div>')
    w('      </div>')
    w('    );')
    w('  };')
    w('')
    
    # ===== TAB 4: ACCESS CONTROL =====
    w('  // ===== TAB 4: ACCESS CONTROL =====')
    w('  const renderAccessControl = () => (')
    w('    <div className="gse-tab-content">')
    w('      <div className="gse-section-header">')
    w('        <h3 className="gse-section-title">Access Control Log</h3>')
    w('        <div className="gse-filters">')
    w('          <div className="gse-search-box"><Search size={16} /><input type="text" placeholder="Search by ID, user, warehouse..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} /></div>')
    w('          <select className="gse-filter-select" value={accessTypeFilter} onChange={(e) => setAccessTypeFilter(e.target.value)}><option value="all">All Types</option><option value="entry">Entry</option><option value="exit">Exit</option><option value="denied">Denied</option><option value="forced">Forced</option><option value="tamper">Tamper</option></select>')
    w('        </div>')
    w('      </div>')
    w('      <div className="gse-charts-grid" style={{ marginBottom: "1.5rem" }}>')
    w('        <div className="gse-chart-card">')
    w('          <h4 className="gse-chart-title">Alert Trend by Severity</h4>')
    w('          <ResponsiveContainer width="100%" height={260}>')
    w('            <BarChart data={data.alertTrendData}>')
    w('              <CartesianGrid strokeDasharray="3 3" stroke="#334155" />')
    w('              <XAxis dataKey="month" tick={{ fill: "#94a3b8", fontSize: 12 }} />')
    w('              <YAxis tick={{ fill: "#94a3b8", fontSize: 12 }} />')
    w('              <Tooltip contentStyle={{ backgroundColor: "#1e293b", border: "1px solid #334155", borderRadius: 8 }} />')
    w('              <Legend />')
    w('              <Bar dataKey="critical" name="Critical" stackId="a" fill={COLORS.danger} />')
    w('              <Bar dataKey="high" name="High" stackId="a" fill={COLORS.accent} />')
    w('              <Bar dataKey="medium" name="Medium" stackId="a" fill={COLORS.info} />')
    w('              <Bar dataKey="low" name="Low" stackId="a" fill={COLORS.success} />')
    w('              <Line type="monotone" dataKey="resolved" name="Resolved" stroke={COLORS.primary} strokeWidth={2} />')
    w('            </BarChart>')
    w('          </ResponsiveContainer>')
    w('        </div>')
    w('        <div className="gse-chart-card">')
    w('          <h4 className="gse-chart-title">Access Method Distribution</h4>')
    w('          <ResponsiveContainer width="100%" height={260}>')
    w('            <PieChart><Pie data={data.accessMethodDist} cx="50%" cy="50%" outerRadius={80} dataKey="count" nameKey="method" label={({ method, percent }) => `${method} ${(percent * 100).toFixed(0)}%`}>{data.accessMethodDist.map((d, i) => <Cell key={i} fill={d.color} />)}</Pie><Tooltip contentStyle={{ backgroundColor: "#1e293b", border: "1px solid #334155", borderRadius: 8 }} /></PieChart>')
    w('          </ResponsiveContainer>')
    w('        </div>')
    w('      </div>')
    w('      <div className="gse-table-wrapper">')
    w('        <table className="gse-table">')
    w('          <thead><tr>')
    w('            {["ID", "Timestamp", "User", "Role", "Access Point", "Zone", "Method", "Type", "Biometric %", "Risk"].map((h) => (')
    w('              <th key={h}>{h}</th>')
    w('            ))}')
    w('          </tr></thead>')
    w('          <tbody>')
    w('            {filteredAccess.slice(0, 50).map((e) => (')
    w('              <tr key={e.id} className="gse-table-row">')
    w('                <td className="gse-mono">{e.id}</td>')
    w('                <td className="gse-mono">{e.timestamp}</td>')
    w('                <td className="gse-bold">{e.userName}</td>')
    w('                <td>{e.department}</td>')
    w('                <td>{e.accessPoint}</td>')
    w('                <td>{e.zone}</td>')
    w('                <td><span className="gse-method-badge">{e.method.toUpperCase()}</span></td>')
    w('                <td><span className={statusBadge(e.accessType)}>{e.accessType.toUpperCase()}</span></td>')
    w('                <td><div className="gse-bar-bg gse-bar-sm"><div className="gse-bar-fill" style={{ width: `${e.biometricMatch}%`, backgroundColor: e.biometricMatch >= 95 ? COLORS.success : e.biometricMatch >= 85 ? COLORS.accent : COLORS.danger }} /><span className="gse-bar-value">{e.biometricMatch}%</span></div></td>')
    w('                <td><span className={`gse-risk-badge ${e.riskScore >= 80 ? "gse-risk-high" : e.riskScore >= 50 ? "gse-risk-medium" : "gse-risk-low"}`}>{e.riskScore}</span></td>')
    w('              </tr>')
    w('            ))}')
    w('          </tbody>')
    w('        </table>')
    w('      </div>')
    w('    </div>')
    w('  );')
    w('')
    
    # ===== TAB 5: ALERTS & INCIDENTS =====
    w('  // ===== TAB 5: ALERTS & INCIDENTS =====')
    w('  const renderAlerts = () => (')
    w('    <div className="gse-tab-content">')
    w('      <div className="gse-section-header">')
    w('        <h3 className="gse-section-title">Security Alerts & Incidents</h3>')
    w('        <div className="gse-filters">')
    w('          <div className="gse-search-box"><Search size={16} /><input type="text" placeholder="Search by ID, type, warehouse..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} /></div>')
    w('          <select className="gse-filter-select" value={alertFilter} onChange={(e) => setAlertFilter(e.target.value)}><option value="all">All Status</option><option value="open">Open</option><option value="investigating">Investigating</option><option value="resolved">Resolved</option><option value="escalated">Escalated</option><option value="false-alarm">False Alarm</option></select>')
    w('          <select className="gse-filter-select" value={alertSevFilter} onChange={(e) => setAlertSevFilter(e.target.value)}><option value="all">All Severity</option><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select>')
    w('        </div>')
    w('      </div>')
    w('      <div className="gse-card-grid">')
    w('        {filteredAlerts.map((a) => (')
    w('          <div className="gse-alert-card" key={a.id} onClick={() => setSelectedAlert(a)}>')
    w('            <div className="gse-alert-card-header">')
    w('              <div className="gse-alert-icon-wrapper" style={{ backgroundColor: a.severity === "critical" ? COLORS.danger + "22" : a.severity === "high" ? COLORS.accent + "22" : COLORS.info + "22" }}>')
    w('                <AlertTriangle size={20} style={{ color: a.severity === "critical" ? COLORS.danger : a.severity === "high" ? COLORS.accent : COLORS.info }} />')
    w('              </div>')
    w('              <div className="gse-alert-card-info">')
    w('                <span className="gse-alert-title">{a.id} - {a.type}</span>')
    w('                <span className="gse-alert-location">{a.warehouse} | {a.location}</span>')
    w('              </div>')
    w('              <span className={`gse-sev-badge gse-sev-${a.severity}`}>{a.severity.toUpperCase()}</span>')
    w('            </div>')
    w('            <div className="gse-alert-card-body">')
    w('              <p className="gse-alert-desc">{a.description.slice(0, 100)}{a.description.length > 100 ? "..." : ""}</p>')
    w('              <div className="gse-alert-meta">')
    w('                <span><Clock size={14} /> {a.timestamp}</span>')
    w('                <span><Fingerprint size={14} /> {a.source}</span>')
    w('                <span><Timer size={14} /> {a.responseTime}min response</span>')
    w('              </div>')
    w('            </div>')
    w('            <div className="gse-alert-card-footer">')
    w('              <span className={statusBadge(a.status)}>{a.status.replace("-", " ")}</span>')
    w('              <span>Assigned: {a.assignedTo}</span>')
    w('              <span className={a.cctvFootage ? "gse-cctv-badge" : ""}>{a.cctvFootage ? <Camera size={14} /> + " CCTV Available" : ""}</span>')
    w('            </div>')
    w('          </div>')
    w('        ))}')
    w('      </div>')
    w('    </div>')
    w('  );')
    w('')
    
    # ===== MAIN RENDER =====
    w('  return (')
    w('    <div className="gse-container">')
    w('      <Tabs value={activeTab} onValueChange={setActiveTab}>')
    w('        <TabsList className="gse-tabs-list">')
    w('          <TabsTrigger value="dashboard" className="gse-tab-trigger"><Activity size={16} /> Dashboard</TabsTrigger>')
    w('          <TabsTrigger value="entries" className="gse-tab-trigger"><ScanLine size={16} /> Gate Entries</TabsTrigger>')
    w('          <TabsTrigger value="personnel" className="gse-tab-trigger"><ShieldCheck size={16} /> Personnel</TabsTrigger>')
    w('          <TabsTrigger value="cctv" className="gse-tab-trigger"><Camera size={16} /> CCTV</TabsTrigger>')
    w('          <TabsTrigger value="access" className="gse-tab-trigger"><Fingerprint size={16} /> Access Control</TabsTrigger>')
    w('          <TabsTrigger value="alerts" className="gse-tab-trigger"><AlertTriangle size={16} /> Alerts</TabsTrigger>')
    w('        </TabsList>')
    w('        <TabsContent value="dashboard">{renderDashboard()}</TabsContent>')
    w('        <TabsContent value="entries">{renderGateEntries()}</TabsContent>')
    w('        <TabsContent value="personnel">{renderSecurityPersonnel()}</TabsContent>')
    w('        <TabsContent value="cctv">{renderCCTV()}</TabsContent>')
    w('        <TabsContent value="access">{renderAccessControl()}</TabsContent>')
    w('        <TabsContent value="alerts">{renderAlerts()}</TabsContent>')
    w('      </Tabs>')
    w('      {renderEntryDrawer()}')
    w('      {renderGuardDrawer()}')
    w('      {renderCameraDrawer()}')
    w('      {renderAlertDrawer()}')
    w('    </div>')
    w('  );')
    w('}')
    
    return '\n'.join(lines)

# Generate and write
content = generate()
with open('/home/z/my-project/src/components/modules/gate-security-view.tsx', 'w') as f:
    f.write(content)

print(f"Generated gate-security-view.tsx: {len(content)} chars, {len(content.splitlines())} lines")
