#!/usr/bin/env python3
"""Generate R167: Parcel Sorting & Cross-Dock Automation module (~1350 lines)"""

LINES = []

def w(line=""):
    LINES.append(line)

# ============================================================
# HEADER & TYPES
# ============================================================
w("'use client'")
w()
w("import React, { useState, useEffect, useMemo } from 'react'")
w("import {")
w("  GitFork, Zap, Package, AlertTriangle, CheckCircle2, XCircle,")
w("  Thermometer, Activity, MapPin, Clock, BarChart3, TrendingUp, TrendingDown,")
w("  Eye, ChevronLeft, ChevronRight, ChevronDown, ChevronUp,")
w("  Wrench, Play, Pause, RefreshCw, Filter,")
w("  Signal, Gauge, Cpu, ArrowUpDown,")
w("  Box, Warehouse, Truck, Timer, ScanBarcode,")
w("  ArrowRightLeft, Split, Merge, Network, Shuffle, Route, Inbox, Outbox")
w("} from 'lucide-react'")
w("import {")
w("  ComposedChart, Bar, Line, Area, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer,")
w("  PieChart, Pie, Cell, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar,")
w("  AreaChart, BarChart")
w("} from 'recharts'")
w()
w("// ============================================================")
w("// TYPES")
w("// ============================================================")
w()
w("interface SortingLane {")
w("  id: string; name: string; type: string;")
w("  hub: string; zone: string;")
w("  status: string; currentParcel: string;")
w("  speed: number; parcelsPerHour: number;")
w("  totalParcels: number; errorRate: number;")
w("  uptime: number; sensorStatus: string;")
w("  conveyorLength: number; sortOrder: number;")
w("  assignedRoute: string;")
w("  todayVolume: number; capacity: number;")
w("}")
w()
w("interface Parcel {")
w("  id: string; awb: string; barcode: string;")
w("  weight: number; dimensions: string;")
w("  sender: string; senderCity: string;")
w("  receiver: string; receiverCity: string;")
w("  courier: string; priority: string;")
w("  status: string; sortLane: string;")
w("  hub: string; dock: string;")
w("  scanned: boolean; fragile: boolean;")
w("  value: number; serviceType: string;")
w("  created: string; sorted: string; dispatched: string | null;")
w("  timeInHub: number;")
w("}")
w()
w("interface CrossDockBatch {")
w("  id: string; inboundTruck: string;")
w("  outboundTruck: string; hub: string;")
w("  totalParcels: number; sortedParcels: number;")
w("  status: string; priority: string;")
w("  startTime: string; endTime: string | null;")
w("  dockIn: string; dockOut: string;")
w("  targetSLA: number; elapsed: number;")
w("  efficiency: number;")
w("}")
w()
w("interface SortAlert {")
w("  id: string; laneId: string; laneName: string;")
w("  type: string; severity: string; message: string;")
w("  timestamp: string; acknowledged: boolean;")
w("  metric: string; value: number; threshold: number;")
w("}")
w()
w("interface Dock {")
w("  id: string; name: string; hub: string;")
w("  type: string; status: string;")
w("  currentTruck: string; parcelsLoaded: number;")
w("  maxCapacity: number; utilization: number;")
w("  avgProcessingTime: number;")
w("}")
w()
w("interface SortingRoute {")
w("  id: string; name: string; destination: string;")
w("  status: string; parcelsInQueue: number;")
w("  nextTruck: string; departure: string;")
w("  priority: string;")
w("}")
w()

# ============================================================
# SEEDED RANDOM & DATA GENERATION
# ============================================================
w("function seededRandom(seed: number): () => number {")
w("  let s = seed % 2147483647")
w("  if (s <= 0) s += 2147483646")
w("  return () => { s = (s * 16807) % 2147483647; return (s - 1) / 2147483646 }")
w("}")
w()
w("function generateData() {")
w("  const rng = seededRandom(167167)")
w("  const r = (min: number, max: number) => Math.floor(rng() * (max - min + 1)) + min")
w("  const rf = (min: number, max: number) => +(rng() * (max - min) + min).toFixed(1)")
w("  const pick = <T,>(arr: T[]): T => arr[Math.floor(rng() * arr.length)]")
w()
w("  const hubs = ['HUB-Mumbai-01','HUB-Delhi-02','HUB-Bengaluru-03','HUB-Chennai-04','HUB-Hyderabad-05','HUB-Pune-06','HUB-Kolkata-07','HUB-Jaipur-08']")
w("  const zones = ['Zone-A','Zone-B','Zone-C','Zone-D']")
w("  const cities = ['Mumbai','Delhi','Bengaluru','Chennai','Hyderabad','Pune','Kolkata','Jaipur','Lucknow','Ahmedabad','Indore','Bhopal','Patna','Chandigarh','Coimbatore','Kochi']")
w("  const laneTypes = ['Linear Sorter','Tilt Tray','Cross Belt','Bombay Sorter','Shoe Sorter','Pusher Sorter']")
w("  const statuses = ['active','idle','maintenance','error','changeover']")
w("  const parcelStatuses = ['received','scanning','sorting','sorted','staged','dispatched','exception']")
w("  const priorities = ['express','priority','standard','economy']")
w("  const serviceTypes = ['Same Day','Next Day','Express','Standard','COD','Surface','Air']")
w("  const couriers = ['Delhivery','DTDC','BlueDart','XpressBees','Ecom Express','Shadowfax','Spoton','Amazon Transport']")
w("  const alertTypes = ['Jam Detected','Sensor Fault','Conveyor Overload','Barcode Mismatch','Weight Limit','Speed Drift','Temperature High','Sort Error Burst','Missed Scan','Lane Blockage']")
w("  const severities = ['critical','warning','info']")
w("  const dockTypes = ['inbound','outbound','cross-dock']")
w("  const batchStatuses = ['in_progress','completed','pending','failed']")
w("  const dockNames = ['Dk-A1','Dk-A2','Dk-A3','Dk-B1','Dk-B2','Dk-B3','Dk-C1','Dk-C2','Dk-C3','Dk-D1','Dk-D2']")
w("  const routes = ['North Express','South Corridor','West Link','East Route','Central Hub','Metro Express','Highway Direct','Last Mile Link']")
w()
w("  // Generate 30 sorting lanes")
w("  const lanes: SortingLane[] = Array.from({ length: 30 }, (_, i) => {")
w("    const st = pick(statuses)")
w("    return {")
w("      id: `LN-${String(i + 1).padStart(3, '0')}`,")
w("      name: `Lane ${String.fromCharCode(65 + (i % 6))}${String(Math.floor(i / 6) + 1)}`,")
w("      type: pick(laneTypes),")
w("      hub: pick(hubs),")
w("      zone: pick(zones),")
w("      status: st,")
w("      currentParcel: st === 'active' ? `PCL-${String(r(1000, 9999))}` : '—',")
w("      speed: st === 'active' ? rf(1.5, 4.0) : 0,")
w("      parcelsPerHour: st === 'active' ? r(200, 800) : r(0, 50),")
w("      totalParcels: r(5000, 45000),")
w("      errorRate: rf(0.1, 3.5),")
w("      uptime: rf(85, 99.9),")
w("      sensorStatus: st === 'error' && rng() > 0.5 ? 'fault' : 'ok',")
w("      conveyorLength: rf(8, 30),")
w("      sortOrder: i + 1,")
w("      assignedRoute: pick(routes),")
w("      todayVolume: r(500, 5000),")
w("      capacity: r(3000, 8000),")
w("    }")
w("  })")
w()
w("  // Generate 500 parcels")
w("  const parcels: Parcel[] = Array.from({ length: 500 }, (_, i) => {")
w("    const st = pick(parcelStatuses)")
w("    const hub = pick(hubs)")
w("    return {")
w("      id: `PCL-${String(i + 1000).padStart(5, '0')}`,")
w("      awb: `${String(r(100000000, 999999999))}`,")
w("      barcode: `490${String(r(10000000, 99999999))}`,")
w("      weight: rf(0.1, 30),")
w("      dimensions: `${r(5,60)}x${r(5,40)}x${r(2,30)}`,")
w("      sender: `Customer-${r(100,999)}`[0],")
w("      senderCity: pick(cities),")
w("      receiver: `Customer-${r(100,999)}`,")
w("      receiverCity: pick(cities),")
w("      courier: pick(couriers),")
w("      priority: pick(priorities),")
w("      status: st,")
w("      sortLane: pick(lanes.slice(0, 12)).name,")
w("      hub,")
w("      dock: pick(dockNames),")
w("      scanned: st !== 'received' && st !== 'exception',")
w("      fragile: rng() > 0.85,")
w("      value: r(100, 50000),")
w("      serviceType: pick(serviceTypes),")
w("      created: `${r(1,48)}h ago`,")
w("      sorted: st !== 'received' && st !== 'scanning' ? `${r(1,24)}h ago` : '—',")
w("      dispatched: st === 'dispatched' ? `${r(0,8)}h ago` : null,")
w("      timeInHub: rf(5, 180),")
w("    }")
w("  })")
w()
w("  // Generate 40 cross-dock batches")
w("  const batches: CrossDockBatch[] = Array.from({ length: 40 }, (_, i) => {")
w("    const st = pick(batchStatuses)")
w("    const tp = r(20, 120)")
w("    const sorted = st === 'completed' ? tp : st === 'in_progress' ? r(5, tp) : 0")
w("    return {")
w("      id: `XDB-${String(i + 1).padStart(4, '0')}`,")
w("      inboundTruck: `TRK-${String(r(100, 999)).padStart(3, '0')}-IN`,")
w("      outboundTruck: `TRK-${String(r(100, 999)).padStart(3, '0')}-OUT`,")
w("      hub: pick(hubs),")
w("      totalParcels: tp,")
w("      sortedParcels: sorted,")
w("      status: st,")
w("      priority: pick(['critical','high','normal','low']),")
w("      startTime: `${r(1,12)}h ago`,")
w("      endTime: st === 'completed' || st === 'failed' ? `${r(0,5)}h ago` : null,")
w("      dockIn: pick(dockNames.slice(0, 5)),")
w("      dockOut: pick(dockNames.slice(5)),")
w("      targetSLA: rf(30, 120),")
w("      elapsed: st === 'in_progress' ? rf(10, 90) : st === 'completed' ? rf(20, 100) : 0,")
w("      efficiency: st === 'completed' ? rf(70, 99) : st === 'in_progress' ? rf(40, 80) : 0,")
w("    }")
w("  })")
w()
w("  // Generate 15 alerts")
w("  const alerts: SortAlert[] = Array.from({ length: 15 }, (_, i) => {")
w("    const lane = pick(lanes)")
w("    const sev = pick(severities)")
w("    return {")
w("      id: `SA-${String(i + 1).padStart(4, '0')}`,")
w("      laneId: lane.id,")
w("      laneName: lane.name,")
w("      type: pick(alertTypes),")
w("      severity: sev,")
w("      message: `${pick(alertTypes)} on ${lane.name} at ${lane.hub.replace('HUB-', '')}`,")
w("      timestamp: `${r(1,48)}h ago`,")
w("      acknowledged: rng() > 0.6,")
w("      metric: pick(['Speed','Error Rate','Temperature','Throughput','Sensor']),")
w("      value: rf(10, 95),")
w("      threshold: rf(60, 90),")
w("    }")
w("  })")
w()
w("  // Generate 20 docks")
w("  const docks: Dock[] = Array.from({ length: 20 }, (_, i) => {")
w("    const dt = i < 7 ? 'inbound' : i < 14 ? 'outbound' : 'cross-dock'")
w("    const loaded = r(20, 300)")
w("    const mx = r(200, 500)")
w("    return {")
w("      id: `DK-${String(i + 1).padStart(3, '0')}`,")
w("      name: dockNames[i] || `Dk-E${i - 10}`,")
w("      hub: pick(hubs),")
w("      type: dt,")
w("      status: pick(['active','active','active','idle','maintenance']),")
w("      currentTruck: `TRK-${String(r(100, 999)).padStart(3, '0')}`,")
w("      parcelsLoaded: loaded,")
w("      maxCapacity: mx,")
w("      utilization: +((loaded / mx) * 100).toFixed(1),")
w("      avgProcessingTime: rf(2, 15),")
w("    }")
w("  })")
w()
w("  // Generate 12 sorting routes")
w("  const sortingRoutes: SortingRoute[] = routes.slice(0, 12).map((name, i) => ({")
w("    id: `RT-${String(i + 1).padStart(2, '0')}`,")
w("    name,")
w("    destination: pick(cities),")
w("    status: pick(['active','active','active','congested','paused']),")
w("    parcelsInQueue: r(10, 200),")
w("    nextTruck: `TRK-${String(r(100, 999)).padStart(3, '0')}`[0],")
w("    departure: `${r(15, 240)} min`,")
w("    priority: pick(['high','normal','normal','low']),")
w("  }))")
w()
w("  // KPIs")
w("  const activeLanes = lanes.filter(l => l.status === 'active').length")
w("  const totalParcelsToday = parcels.length")
w("  const sortedToday = parcels.filter(p => p.status === 'sorted' || p.status === 'staged' || p.status === 'dispatched').length")
w("  const avgSortSpeed = +(lanes.filter(l => l.status === 'active').reduce((s, l) => s + l.parcelsPerHour, 0) / Math.max(activeLanes, 1)).toFixed(0)")
w("  const exceptionCount = parcels.filter(p => p.status === 'exception').length")
w("  const crossDockEfficiency = +(batches.filter(b => b.status === 'completed').reduce((s, b) => s + b.efficiency, 0) / Math.max(batches.filter(b => b.status === 'completed').length, 1)).toFixed(1)")
w()
w("  // Hourly data (24h)")
w("  const hourlyData = Array.from({ length: 24 }, (_, i) => ({")
w("    hour: `${String(i).padStart(2, '0')}:00`,")
w("    inbound: r(50, 300),")
w("    sorted: r(40, 280),")
w("    dispatched: r(30, 250),")
w("    exceptions: r(2, 20),")
w("    throughput: r(150, 800),")
w("  }))")
w()
w("  // Lane type distribution")
w("  const typeCounts: Record<string, number> = {}")
w("  lanes.forEach(l => { typeCounts[l.type] = (typeCounts[l.type] || 0) + 1 })")
w("  const typePieData = Object.entries(typeCounts).map(([name, value]) => ({ name, value }))")
w()
w("  // Status distribution")
w("  const statusDist = statuses.map(s => ({ status: s, count: lanes.filter(l => l.status === s).length }))")
w()
w("  // Hub performance radar")
w("  const hubRadar = hubs.slice(0, 6).map(h => {")
w("    const hLanes = lanes.filter(l => l.hub === h)")
w("    const hParcels = parcels.filter(p => p.hub === h)")
w("    return {")
w("      hub: h.replace('HUB-', '').replace('-0', ' #'),")
w("      throughput: +((hParcels.length / Math.max(hLanes.length, 1))).toFixed(0),")
w("      efficiency: +((hLanes.reduce((s, l) => s + l.uptime, 0) / Math.max(hLanes.length, 1))).toFixed(0),")
w("      lanes: hLanes.filter(l => l.status === 'active').length,")
w("      speed: +((hLanes.filter(l => l.status === 'active').reduce((s, l) => s + l.speed, 0) / Math.max(hLanes.filter(l => l.status === 'active').length, 1))).toFixed(1),")
w("    }")
w("  })")
w()
w("  // Courier volume breakdown")
w("  const courierVolume: Record<string, number> = {}")
w("  parcels.forEach(p => { courierVolume[p.courier] = (courierVolume[p.courier] || 0) + 1 })")
w("  const courierChartData = Object.entries(courierVolume).map(([name, count]) => ({ name, count })).sort((a, b) => b.count - a.count)")
w()
w("  return {")
w("    lanes, parcels, batches, alerts, docks, sortingRoutes,")
w("    hourlyData, typePieData, statusDist, hubRadar, courierChartData,")
w("    activeLanes, totalParcelsToday, sortedToday, avgSortSpeed, exceptionCount, crossDockEfficiency,")
w("    statuses, priorities, parcelStatuses, serviceTypes, couriers, hubs,")
w("    dockTypes: dockTypes, dockNames,")
w("  }")
w("}")
w()

# ============================================================
# COMPONENT
# ============================================================
w()
w("const COLORS = ['#ec4899', '#06b6d4', '#8b5cf6', '#22c55e', '#f97316', '#ef4444']")
w("const THEME = { primary: '#ec4899', secondary: '#06b6d4', accent: '#8b5cf6', success: '#22c55e', danger: '#ef4444', warning: '#f97316' }")
w()
w("function formatINR(num: number): string {")
w("  if (num >= 10000000) return `₹${(num / 10000000).toFixed(2)} Cr`")
w("  if (num >= 100000) return `₹${(num / 100000).toFixed(2)} L`")
w("  return `₹${num.toLocaleString('en-IN')}`")
w("}")
w()
w("export default function ParcelSortingCrossDockView() {")
w("  const data = useMemo(() => generateData(), [])")
w("  const [activeTab, setActiveTab] = useState(0)")
w("  const [selectedLane, setSelectedLane] = useState<SortingLane | null>(null)")
w("  const [selectedParcel, setSelectedParcel] = useState<Parcel | null>(null)")
w("  const [selectedBatch, setSelectedBatch] = useState<CrossDockBatch | null>(null)")
w("  const [currentPage, setCurrentPage] = useState(1)")
w("  const [searchQuery, setSearchQuery] = useState('')")
w("  const [statusFilter, setStatusFilter] = useState('all')")
w("  const [typeFilter, setTypeFilter] = useState('all')")
w("  const [priorityFilter, setPriorityFilter] = useState('all')")
w("  const [courierFilter, setCourierFilter] = useState('all')")
w("  const [sortField, setSortField] = useState<string>('id')")
w("  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('asc')")
w("  const [parcelPage, setParcelPage] = useState(1)")
w("  const rowsPerPage = 15")
w()
w("  const [currentTime, setCurrentTime] = useState('')")
w("  useEffect(() => {")
w("    const tick = () => setCurrentTime(new Date().toLocaleTimeString('en-IN', { timeZone: 'Asia/Kolkata', hour12: false }))")
w("    tick()")
w("    const iv = setInterval(tick, 1000)")
w("    return () => clearInterval(iv)")
w("  }, [])")
w()
w("  // Filtered lanes")
w("  const filteredLanes = useMemo(() => {")
w("    let list = data.lanes.filter(l => {")
w("      if (statusFilter !== 'all' && l.status !== statusFilter) return false")
w("      if (typeFilter !== 'all' && l.type !== typeFilter) return false")
w("      if (searchQuery && !l.id.toLowerCase().includes(searchQuery.toLowerCase()) && !l.name.toLowerCase().includes(searchQuery.toLowerCase()) && !l.hub.toLowerCase().includes(searchQuery.toLowerCase())) return false")
w("      return true")
w("    })")
w("    list.sort((a, b) => {")
w("      const aVal = (a as any)[sortField]; const bVal = (b as any)[sortField]")
w("      if (typeof aVal === 'string') return sortDir === 'asc' ? aVal.localeCompare(bVal) : bVal.localeCompare(aVal)")
w("      return sortDir === 'asc' ? (aVal as number) - (bVal as number) : (bVal as number) - (aVal as number)")
w("    })")
w("    return list")
w("  }, [data, statusFilter, typeFilter, searchQuery, sortField, sortDir])")
w()
w("  // Filtered parcels")
w("  const filteredParcels = useMemo(() => {")
w("    return data.parcels.filter(p => {")
w("      if (priorityFilter !== 'all' && p.priority !== priorityFilter) return false")
w("      if (courierFilter !== 'all' && p.courier !== courierFilter) return false")
w("      if (statusFilter !== 'all' && p.status !== statusFilter) return false")
w("      if (searchQuery && !p.id.includes(searchQuery) && !p.awb.includes(searchQuery) && !p.courier.toLowerCase().includes(searchQuery.toLowerCase())) return false")
w("      return true")
w("    })")
w("  }, [data, priorityFilter, courierFilter, statusFilter, searchQuery])")
w()
w("  const paginatedLanes = filteredLanes.slice((currentPage - 1) * rowsPerPage, currentPage * rowsPerPage)")
w("  const paginatedParcels = filteredParcels.slice((parcelPage - 1) * rowsPerPage, parcelPage * rowsPerPage)")
w("  const totalPages = Math.ceil(filteredLanes.length / rowsPerPage)")
w("  const totalParcelPages = Math.ceil(filteredParcels.length / rowsPerPage)")
w()
w("  const toggleSort = (field: string) => {")
w("    if (sortField === field) setSortDir(d => d === 'asc' ? 'desc' : 'asc')")
w("    else { setSortField(field); setSortDir('asc') }")
w("  }")
w()
w("  const tabs = ['Dashboard', 'Sorting Lanes', 'Parcel Tracker', 'Cross-Dock Ops', 'Routes & Alerts']")
w()
w("  const statusColor = (s: string) => {")
w("    const map: Record<string, string> = { active: '#22c55e', idle: '#6b7280', maintenance: '#f59e0b', error: '#ef4444', changeover: '#8b5cf6', received: '#06b6d4', scanning: '#f97316', sorting: '#8b5cf6', sorted: '#22c55e', staged: '#06b6d4', dispatched: '#10b981', exception: '#ef4444', in_progress: '#f97316', completed: '#22c55e', pending: '#6b7280', failed: '#ef4444', congested: '#f97316', paused: '#6b7280', express: '#ef4444', priority: '#f97316', standard: '#06b6d4', economy: '#6b7280', critical: '#ef4444', high: '#f97316', normal: '#06b6d4', low: '#6b7280', online: '#22c55e' }")
w("    return map[s] || '#6b7280'")
w("  }")
w()
w("  const priorityBadge = (p: string) => {")
w("    const c: Record<string, string> = { express: '#ef4444', priority: '#f97316', standard: '#06b6d4', economy: '#6b7280' }")
w("    return c[p] || '#6b7280'")
w("  }")
w()

# ============================================================
# TAB 0: DASHBOARD
# ============================================================
w("  const renderDashboard = () => (")
w("    <div className='psd-tab-content'>")
w("      <div className='psd-clock-row'>")
w("        <GitFork size={18} style={{ color: THEME.primary }} />")
w("        <span className='psd-live-dot' />")
w("        <span className='psd-clock-text'>Live — {currentTime} IST</span>")
w("      </div>")
w()
w("      {/* KPIs */}")
w("      <div className='psd-kpi-grid'>")
w("        <div className='psd-kpi-card' style={{ borderTopColor: '#22c55e' }}>")
w("          <div className='psd-kpi-icon' style={{ background: '#22c55e15', color: '#22c55e' }}><GitFork size={20} /></div>")
w("          <div className='psd-kpi-body'>")
w("            <span className='psd-kpi-value'>{data.activeLanes}</span>")
w("            <span className='psd-kpi-label'>Active Lanes</span>")
w("          </div>")
w("        </div>")
w("        <div className='psd-kpi-card' style={{ borderTopColor: THEME.primary }}>")
w("          <div className='psd-kpi-icon' style={{ background: '#ec489915', color: THEME.primary }}><Package size={20} /></div>")
w("          <div className='psd-kpi-body'>")
w("            <span className='psd-kpi-value'>{data.totalParcelsToday}</span>")
w("            <span className='psd-kpi-label'>Total Parcels</span>")
w("          </div>")
w("        </div>")
w("        <div className='psd-kpi-card' style={{ borderTopColor: THEME.secondary }}>")
w("          <div className='psd-kpi-icon' style={{ background: '#06b6d415', color: THEME.secondary }}><Shuffle size={20} /></div>")
w("          <div className='psd-kpi-body'>")
w("            <span className='psd-kpi-value'>{data.sortedToday}</span>")
w("            <span className='psd-kpi-label'>Sorted Today</span>")
w("          </div>")
w("        </div>")
w("        <div className='psd-kpi-card' style={{ borderTopColor: THEME.accent }}>")
w("          <div className='psd-kpi-icon' style={{ background: '#8b5cf615', color: THEME.accent }}><Gauge size={20} /></div>")
w("          <div className='psd-kpi-body'>")
w("            <span className='psd-kpi-value'>{data.avgSortSpeed}/hr</span>")
w("            <span className='psd-kpi-label'>Avg Sort Speed</span>")
w("          </div>")
w("        </div>")
w("        <div className='psd-kpi-card' style={{ borderTopColor: THEME.warning }}>")
w("          <div className='psd-kpi-icon' style={{ background: '#f9731615', color: THEME.warning }}><ArrowRightLeft size={20} /></div>")
w("          <div className='psd-kpi-body'>")
w("            <span className='psd-kpi-value'>{data.crossDockEfficiency}%</span>")
w("            <span className='psd-kpi-label'>Cross-Dock Eff</span>")
w("          </div>")
w("        </div>")
w("        <div className='psd-kpi-card' style={{ borderTopColor: THEME.danger }}>")
w("          <div className='psd-kpi-icon' style={{ background: '#ef444415', color: THEME.danger }}><AlertTriangle size={20} /></div>")
w("          <div className='psd-kpi-body'>")
w("            <span className='psd-kpi-value'>{data.exceptionCount}</span>")
w("            <span className='psd-kpi-label'>Exceptions</span>")
w("          </div>")
w("        </div>")
w("      </div>")
w()
w("      {/* Charts row 1 */}")
w("      <div className='psd-charts-row'>")
w("        <div className='psd-chart-card psd-chart-wide'>")
w("          <div className='psd-chart-header'><h4 className='psd-chart-title'>24h Parcel Flow (Inbound / Sorted / Dispatched)</h4></div>")
w("          <ResponsiveContainer width='100%' height={260}>")
w("            <ComposedChart data={data.hourlyData}>")
w("              <CartesianGrid strokeDasharray='3 3' stroke='#1e293b' />")
w("              <XAxis dataKey='hour' stroke='#64748b' tick={{ fontSize: 10 }} interval={2} />")
w("              <YAxis stroke='#64748b' tick={{ fontSize: 10 }} />")
w("              <Tooltip contentStyle={{ background: '#1e293b', border: '1px solid #334155', borderRadius: 8 }} />")
w("              <Legend wrapperStyle={{ fontSize: 11 }} />")
w("              <Bar dataKey='inbound' fill='#06b6d4' radius={[4, 4, 0, 0]} name='Inbound' />")
w("              <Bar dataKey='sorted' fill='#8b5cf6' radius={[4, 4, 0, 0]} name='Sorted' />")
w("              <Bar dataKey='dispatched' fill='#22c55e' radius={[4, 4, 0, 0]} name='Dispatched' />")
w("              <Line dataKey='exceptions' stroke='#ef4444' strokeWidth={2} dot={false} name='Exceptions' />")
w("            </ComposedChart>")
w("          </ResponsiveContainer>")
w("        </div>")
w("        <div className='psd-chart-card'>")
w("          <div className='psd-chart-header'><h4 className='psd-chart-title'>Lane Type Distribution</h4></div>")
w("          <ResponsiveContainer width='100%' height={260}>")
w("            <PieChart>")
w("              <Pie data={data.typePieData} cx='50%' cy='50%' outerRadius={80} innerRadius={45} dataKey='value' label={({ name, percent }) => `${name.split(' ')[0]} ${(percent * 100).toFixed(0)}%`} labelLine={{ stroke: '#475569' }}>")
w("                {data.typePieData.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}")
w("              </Pie>")
w("              <Tooltip contentStyle={{ background: '#1e293b', border: '1px solid #334155', borderRadius: 8 }} />")
w("            </PieChart>")
w("          </ResponsiveContainer>")
w("        </div>")
w("      </div>")
w()
w("      {/* Charts row 2 */}")
w("      <div className='psd-charts-row'>")
w("        <div className='psd-chart-card'>")
w("          <div className='psd-chart-header'><h4 className='psd-chart-title'>Hub Performance Radar</h4></div>")
w("          <ResponsiveContainer width='100%' height={260}>")
w("            <RadarChart data={data.hubRadar}>")
w("              <PolarGrid stroke='#334155' />")
w("              <PolarAngleAxis dataKey='hub' stroke='#94a3b8' tick={{ fontSize: 10 }} />")
w("              <PolarRadiusAxis stroke='#475569' tick={{ fontSize: 9 }} />")
w("              <Radar name='Throughput' dataKey='throughput' stroke='#ec4899' fill='#ec489930' strokeWidth={2} />")
w("              <Radar name='Efficiency' dataKey='efficiency' stroke='#06b6d4' fill='#06b6d430' strokeWidth={2} />")
w("              <Legend wrapperStyle={{ fontSize: 10 }} />")
w("            </RadarChart>")
w("          </ResponsiveContainer>")
w("        </div>")
w("        <div className='psd-chart-card'>")
w("          <div className='psd-chart-header'><h4 className='psd-chart-title'>Courier Volume</h4></div>")
w("          <ResponsiveContainer width='100%' height={260}>")
w("            <BarChart data={data.courierChartData}>")
w("              <CartesianGrid strokeDasharray='3 3' stroke='#1e293b' />")
w("              <XAxis dataKey='name' stroke='#64748b' tick={{ fontSize: 9 }} angle={-25} textAnchor='end' height={55} />")
w("              <YAxis stroke='#64748b' tick={{ fontSize: 10 }} />")
w("              <Tooltip contentStyle={{ background: '#1e293b', border: '1px solid #334155', borderRadius: 8 }} />")
w("              <Bar dataKey='count' radius={[6, 6, 0, 0]}>")
w("                {data.courierChartData.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}")
w("              </Bar>")
w("            </BarChart>")
w("          </ResponsiveContainer>")
w("        </div>")
w("      </div>")
w()
w("      {/* Dock status grid */}")
w("      <div className='psd-chart-card psd-chart-full'>")
w("        <div className='psd-chart-header'><h4 className='psd-chart-title'>Dock Status Overview ({data.docks.length} Docks)</h4></div>")
w("        <div className='psd-dock-visual-grid'>")
w("          {data.docks.map(dk => {")
w("            const utilColor = dk.utilization > 85 ? '#ef4444' : dk.utilization > 60 ? '#f59e0b' : '#22c55e'")
w("            return (")
w("              <div key={dk.id} className='psd-dock-cell' style={{ borderLeftColor: dk.type === 'inbound' ? '#06b6d4' : dk.type === 'outbound' ? '#22c55e' : '#8b5cf6' }}>")
w("                <div className='psd-dock-name'>{dk.name}</div>")
w("                <div className='psd-dock-type-badge' style={{ background: `${dk.type === 'inbound' ? '#06b6d4' : dk.type === 'outbound' ? '#22c55e' : '#8b5cf6'}20`, color: dk.type === 'inbound' ? '#06b6d4' : dk.type === 'outbound' ? '#22c55e' : '#8b5cf6' }}>{dk.type}</div>")
w("                <div className='psd-dock-util-bar-track'><div className='psd-dock-util-bar-fill' style={{ width: `${dk.utilization}%`, background: utilColor }} /></div>")
w("                <span className='psd-dock-util-text'>{dk.utilization}% ({dk.parcelsLoaded}/{dk.maxCapacity})</span>")
w("              </div>")
w("            )")
w("          })}")
w("        </div>")
w("      </div>")
w("    </div>")
w("  )")
w()

# ============================================================
# TAB 1: SORTING LANES
# ============================================================
w("  const renderLanes = () => (")
w("    <div className='psd-tab-content'>")
w("      <div className='psd-filter-row'>")
w("        <div className='psd-search-box'>")
w("          <input type='text' placeholder='Search lane ID, name, hub...' value={searchQuery} onChange={e => { setSearchQuery(e.target.value); setCurrentPage(1) }} className='psd-search-input' />")
w("        </div>")
w("        <div className='psd-filter-pills'>")
w("          <button className={`psd-pill ${statusFilter === 'all' ? 'psd-pill-active' : ''}`} onClick={() => setStatusFilter('all')}>All</button>")
w("          {data.statuses.map(s => (")
w("            <button key={s} className={`psd-pill ${statusFilter === s ? 'psd-pill-active' : ''}`} style={statusFilter === s ? { background: statusColor(s), borderColor: statusColor(s) } : {}} onClick={() => setStatusFilter(s)}>{s}</button>")
w("          ))}")
w("        </div>")
w("      </div>")
w()
w("      <div className='psd-fleet-stats'>")
w("        <span>Total: <b>{filteredLanes.length}</b></span>")
w("        <span>Active: <b>{filteredLanes.filter(l => l.status === 'active').length}</b></span>")
w("        <span>Page {currentPage}/{totalPages}</span>")
w("      </div>")
w()
w("      <div className='psd-table-wrapper'>")
w("        <table className='psd-table'>")
w("          <thead>")
w("            <tr>")
w("              <th onClick={() => toggleSort('id')} className='psd-th-sortable'>Lane {sortField === 'id' && (sortDir === 'asc' ? <ChevronUp size={12} /> : <ChevronDown size={12} />)}</th>")
w("              <th>Type</th>")
w("              <th>Status</th>")
w("              <th onClick={() => toggleSort('speed')} className='psd-th-sortable'>Speed {sortField === 'speed' && (sortDir === 'asc' ? <ChevronUp size={12} /> : <ChevronDown size={12} />)}</th>")
w("              <th onClick={() => toggleSort('parcelsPerHour')} className='psd-th-sortable'>Parcels/hr {sortField === 'parcelsPerHour' && (sortDir === 'asc' ? <ChevronUp size={12} /> : <ChevronDown size={12} />)}</th>")
w("              <th>Volume/Capacity</th>")
w("              <th>Error Rate</th>")
w("              <th>Uptime</th>")
w("              <th>Route</th>")
w("              <th>Hub</th>")
w("              <th>Action</th>")
w("            </tr>")
w("          </thead>")
w("          <tbody>")
w("            {paginatedLanes.map(lane => (")
w("              <tr key={lane.id} className='psd-table-row' style={{ borderLeftColor: statusColor(lane.status) }}>")
w("                <td className='psd-td-id'><GitFork size={14} style={{ color: THEME.primary, marginRight: 6 }} />{lane.id}</td>")
w("                <td><span className='psd-type-badge'>{lane.type}</span></td>")
w("                <td><span className='psd-status-badge' style={{ background: `${statusColor(lane.status)}20`, color: statusColor(lane.status) }}>{lane.status}</span></td>")
w("                <td>{lane.speed > 0 ? `${lane.speed} m/s` : '—'}</td>")
w("                <td style={{ fontWeight: 600 }}>{lane.parcelsPerHour}</td>")
w("                <td>")
w("                  <div className='psd-bar-cell'>")
w("                    <div className='psd-bar-track'><div className='psd-bar-fill' style={{ width: `${(lane.todayVolume / lane.capacity) * 100}%`, background: (lane.todayVolume / lane.capacity) > 0.85 ? '#ef4444' : '#ec4899' }} /></div>")
w("                    <span className='psd-bar-text'>{lane.todayVolume}/{lane.capacity}</span>")
w("                  </div>")
w("                </td>")
w("                <td style={{ color: lane.errorRate > 2 ? '#ef4444' : '#22c55e' }}>{lane.errorRate}%</td>")
w("                <td style={{ color: lane.uptime > 95 ? '#22c55e' : lane.uptime > 85 ? '#f59e0b' : '#ef4444' }}>{lane.uptime}%</td>")
w("                <td style={{ fontSize: 11 }}>{lane.assignedRoute}</td>")
w("                <td style={{ fontSize: 11 }}>{lane.hub.replace('HUB-', '')}</td>")
w("                <td><button className='psd-view-btn' onClick={() => setSelectedLane(lane)}><Eye size={14} /></button></td>")
w("              </tr>")
w("            ))}")
w("          </tbody>")
w("        </table>")
w("      </div>")
w("      <div className='psd-pagination'>")
w("        <button disabled={currentPage <= 1} onClick={() => setCurrentPage(p => p - 1)} className='psd-page-btn'><ChevronLeft size={16} /></button>")
w("        {Array.from({ length: Math.min(totalPages, 8) }, (_, i) => <button key={i} className={`psd-page-btn ${currentPage === i + 1 ? 'psd-page-active' : ''}`} onClick={() => setCurrentPage(i + 1)}>{i + 1}</button>)}")
w("        <button disabled={currentPage >= totalPages} onClick={() => setCurrentPage(p => p + 1)} className='psd-page-btn'><ChevronRight size={16} /></button>")
w("      </div>")
w("    </div>")
w("  )")
w()

# ============================================================
# TAB 2: PARCEL TRACKER
# ============================================================
w("  const renderParcels = () => (")
w("    <div className='psd-tab-content'>")
w("      <div className='psd-filter-row'>")
w("        <div className='psd-search-box'>")
w("          <input type='text' placeholder='Search parcel ID, AWB, courier...' value={searchQuery} onChange={e => { setSearchQuery(e.target.value); setParcelPage(1) }} className='psd-search-input' />")
w("        </div>")
w("        <div className='psd-filter-pills'>")
w("          <button className={`psd-pill ${priorityFilter === 'all' ? 'psd-pill-active' : ''}`} onClick={() => setPriorityFilter('all')}>All</button>")
w("          {data.priorities.map(p => (")
w("            <button key={p} className={`psd-pill ${priorityFilter === p ? 'psd-pill-active' : ''}`} style={priorityFilter === p ? { background: priorityBadge(p), borderColor: priorityBadge(p) } : {}} onClick={() => setPriorityFilter(p)}>{p}</button>")
w("          ))}")
w("        </div>")
w("        <div className='psd-filter-pills'>")
w("          <button className={`psd-pill ${courierFilter === 'all' ? 'psd-pill-active' : ''}`} onClick={() => setCourierFilter('all')}>All Couriers</button>")
w("          {data.couriers.slice(0, 5).map(c => (")
w("            <button key={c} className={`psd-pill ${courierFilter === c ? 'psd-pill-active' : ''}`} onClick={() => setCourierFilter(c)}>{c}</button>")
w("          ))}")
w("        </div>")
w("      </div>")
w()
w("      <div className='psd-fleet-stats'>")
w("        <span>Total: <b>{filteredParcels.length}</b></span>")
w("        <span>Sorted: <b>{filteredParcels.filter(p => p.status === 'sorted').length}</b></span>")
w("        <span>Dispatched: <b>{filteredParcels.filter(p => p.status === 'dispatched').length}</b></span>")
w("        <span>Exceptions: <b>{filteredParcels.filter(p => p.status === 'exception').length}</b></span>")
w("      </div>")
w()
w("      <div className='psd-table-wrapper'>")
w("        <table className='psd-table'>")
w("          <thead>")
w("            <tr>")
w("              <th>Parcel ID</th>")
w("              <th>AWB</th>")
w("              <th>Priority</th>")
w("              <th>Status</th>")
w("              <th>Courier</th>")
w("              <th>Service</th>")
w("              <th>Weight</th>")
w("              <th>Route</th>")
w("              <th>Lane</th>")
w("              <th>Value</th>")
w("              <th>Time in Hub</th>")
w("              <th>Action</th>")
w("            </tr>")
w("          </thead>")
w("          <tbody>")
w("            {paginatedParcels.map(p => (")
w("              <tr key={p.id} className='psd-table-row' style={{ borderLeftColor: statusColor(p.status) }}>")
w("                <td className='psd-td-id'>{p.id}</td>")
w("                <td style={{ fontSize: 11, fontFamily: 'monospace' }}>{p.awb}</td>")
w("                <td><span className='psd-status-badge' style={{ background: `${priorityBadge(p.priority)}20`, color: priorityBadge(p.priority) }}>{p.priority}</span></td>")
w("                <td><span className='psd-status-badge' style={{ background: `${statusColor(p.status)}20`, color: statusColor(p.status) }}>{p.status}</span></td>")
w("                <td style={{ fontSize: 11 }}>{p.courier}</td>")
w("                <td><span className='psd-type-badge'>{p.serviceType}</span></td>")
w("                <td>{p.weight} kg</td>")
w("                <td style={{ fontSize: 11 }}>{p.senderCity} → {p.receiverCity}</td>")
w("                <td style={{ fontSize: 11 }}>{p.sortLane}</td>")
w("                <td style={{ fontSize: 11 }}>{formatINR(p.value)}</td>")
w("                <td style={{ fontSize: 11 }}>{p.timeInHub} min</td>")
w("                <td><button className='psd-view-btn' onClick={() => setSelectedParcel(p)}><Eye size={14} /></button></td>")
w("              </tr>")
w("            ))}")
w("          </tbody>")
w("        </table>")
w("      </div>")
w("      <div className='psd-pagination'>")
w("        <button disabled={parcelPage <= 1} onClick={() => setParcelPage(p => p - 1)} className='psd-page-btn'><ChevronLeft size={16} /></button>")
w("        {Array.from({ length: Math.min(totalParcelPages, 8) }, (_, i) => <button key={i} className={`psd-page-btn ${parcelPage === i + 1 ? 'psd-page-active' : ''}`} onClick={() => setParcelPage(i + 1)}>{i + 1}</button>)}")
w("        <button disabled={parcelPage >= totalParcelPages} onClick={() => setParcelPage(p => p + 1)} className='psd-page-btn'><ChevronRight size={16} /></button>")
w("      </div>")
w("    </div>")
w("  )")
w()

# ============================================================
# TAB 3: CROSS-DOCK OPS
# ============================================================
w("  const renderCrossDock = () => (")
w("    <div className='psd-tab-content'>")
w("      <div className='psd-kpi-grid'>")
w("        <div className='psd-kpi-card' style={{ borderTopColor: '#f97316' }}>")
w("          <div className='psd-kpi-icon' style={{ background: '#f9731615', color: '#f97316' }}><ArrowRightLeft size={20} /></div>")
w("          <div className='psd-kpi-body'>")
w("            <span className='psd-kpi-value'>{data.batches.length}</span>")
w("            <span className='psd-kpi-label'>Total Batches</span>")
w("          </div>")
w("        </div>")
w("        <div className='psd-kpi-card' style={{ borderTopColor: '#06b6d4' }}>")
w("          <div className='psd-kpi-icon' style={{ background: '#06b6d415', color: '#06b6d4' }}><Play size={20} /></div>")
w("          <div className='psd-kpi-body'>")
w("            <span className='psd-kpi-value'>{data.batches.filter(b => b.status === 'in_progress').length}</span>")
w("            <span className='psd-kpi-label'>In Progress</span>")
w("          </div>")
w("        </div>")
w("        <div className='psd-kpi-card' style={{ borderTopColor: '#22c55e' }}>")
w("          <div className='psd-kpi-icon' style={{ background: '#22c55e15', color: '#22c55e' }}><CheckCircle2 size={20} /></div>")
w("          <div className='psd-kpi-body'>")
w("            <span className='psd-kpi-value'>{data.batches.filter(b => b.status === 'completed').length}</span>")
w("            <span className='psd-kpi-label'>Completed</span>")
w("          </div>")
w("        </div>")
w("        <div className='psd-kpi-card' style={{ borderTopColor: '#ef4444' }}>")
w("          <div className='psd-kpi-icon' style={{ background: '#ef444415', color: '#ef4444' }}><XCircle size={20} /></div>")
w("          <div className='psd-kpi-body'>")
w("            <span className='psd-kpi-value'>{data.batches.filter(b => b.status === 'failed').length}</span>")
w("            <span className='psd-kpi-label'>Failed</span>")
w("          </div>")
w("        </div>")
w("      </div>")
w()
w("      <div className='psd-xd-grid'>")
w("        {data.batches.map(batch => {")
w("          const progress = batch.totalParcels > 0 ? (batch.sortedParcels / batch.totalParcels) * 100 : 0")
w("          const slaProgress = batch.targetSLA > 0 ? (batch.elapsed / batch.targetSLA) * 100 : 0")
w("          return (")
w("            <div key={batch.id} className='psd-xd-card' style={{ borderColor: statusColor(batch.status) }}>")
w("              <div className='psd-xd-header'>")
w("                <span className='psd-xd-id'>{batch.id}</span>")
w("                <span className='psd-xd-status' style={{ background: `${statusColor(batch.status)}20`, color: statusColor(batch.status) }}>{batch.status}</span>")
w("                <span className='psd-xd-priority' style={{ color: priorityBadge(batch.priority) }}>{batch.priority}</span>")
w("              </div>")
w("              <div className='psd-xd-route'>")
w("                <Inbox size={12} style={{ color: '#06b6d4' }} /><span>{batch.inboundTruck}</span>")
w("                <ArrowRightLeft size={12} style={{ color: THEME.primary, margin: '0 4px' }} />")
w("                <Outbox size={12} style={{ color: '#22c55e' }} /><span>{batch.outboundTruck}</span>")
w("              </div>")
w("              <div className='psd-xd-docks'>{batch.dockIn} → {batch.dockOut}</div>")
w("              <div className='psd-xd-progress-section'>")
w("                <div className='psd-xd-progress-label'>Sort Progress</div>")
w("                <div className='psd-xd-progress-track'><div className='psd-xd-progress-fill' style={{ width: `${progress}%`, background: '#ec4899' }} /></div>")
w("                <span className='psd-xd-progress-text'>{batch.sortedParcels}/{batch.totalParcels} ({Math.round(progress)}%)</span>")
w("              </div>")
w("              <div className='psd-xd-progress-section'>")
w("                <div className='psd-xd-progress-label'>SLA ({batch.targetSLA} min)</div>")
w("                <div className='psd-xd-progress-track'><div className='psd-xd-progress-fill' style={{ width: `${Math.min(slaProgress, 100)}%`, background: slaProgress > 80 ? '#ef4444' : '#06b6d4' }} /></div>")
w("                <span className='psd-xd-progress-text'>{batch.elapsed}/{batch.targetSLA} min</span>")
w("              </div>")
w("              <div className='psd-xd-footer'>")
w("                <span>{batch.hub.replace('HUB-', '')}</span>")
w("                {batch.efficiency > 0 && <span>Eff: {batch.efficiency}%</span>}")
w("              </div>")
w("              <button className='psd-card-action-btn' onClick={() => setSelectedBatch(batch)}><Eye size={14} /> View Details</button>")
w("            </div>")
w("          )")
w("        })}")
w("      </div>")
w("    </div>")
w("  )")
w()

# ============================================================
# TAB 4: ROUTES & ALERTS
# ============================================================
w("  const renderRoutesAlerts = () => (")
w("    <div className='psd-tab-content'>")
w("      <div className='psd-section-header'>")
w("        <Route size={18} style={{ color: THEME.primary }} />")
w("        <h3 className='psd-section-title'>Sorting Routes ({data.sortingRoutes.length})</h3>")
w("      </div>")
w("      <div className='psd-route-grid'>")
w("        {data.sortingRoutes.map(rt => (")
w("          <div key={rt.id} className='psd-route-card' style={{ borderLeftColor: statusColor(rt.status) }}>")
w("            <div className='psd-route-name'>{rt.name}</div>")
w("            <div className='psd-route-meta'>")
w("              <span className='psd-route-status' style={{ background: `${statusColor(rt.status)}20`, color: statusColor(rt.status) }}>{rt.status}</span>")
w("              <span className='psd-route-detail'>→ {rt.destination}</span>")
w("              <span className='psd-route-detail'>{rt.parcelsInQueue} parcels</span>")
w("              <span className='psd-route-detail'>Departs: {rt.departure}</span>")
w("            </div>")
w("          </div>")
w("        ))}")
w("      </div>")
w()
w("      <div className='psd-section-header' style={{ marginTop: 24 }}>")
w("        <AlertTriangle size={18} style={{ color: THEME.danger }} />")
w("        <h3 className='psd-section-title'>Sorting Alerts & Diagnostics</h3>")
w("      </div>")
w("      <div className='psd-kpi-grid'>")
w("        <div className='psd-kpi-card' style={{ borderTopColor: '#ef4444' }}>")
w("          <div className='psd-kpi-icon' style={{ background: '#ef444415', color: '#ef4444' }}><XCircle size={20} /></div>")
w("          <div className='psd-kpi-body'>")
w("            <span className='psd-kpi-value'>{data.alerts.filter(a => a.severity === 'critical' && !a.acknowledged).length}</span>")
w("            <span className='psd-kpi-label'>Critical Unack</span>")
w("          </div>")
w("        </div>")
w("        <div className='psd-kpi-card' style={{ borderTopColor: '#f59e0b' }}>")
w("          <div className='psd-kpi-icon' style={{ background: '#f59e0b15', color: '#f59e0b' }}><AlertTriangle size={20} /></div>")
w("          <div className='psd-kpi-body'>")
w("            <span className='psd-kpi-value'>{data.alerts.filter(a => a.severity === 'warning').length}</span>")
w("            <span className='psd-kpi-label'>Warnings</span>")
w("          </div>")
w("        </div>")
w("        <div className='psd-kpi-card' style={{ borderTopColor: '#22c55e' }}>")
w("          <div className='psd-kpi-icon' style={{ background: '#22c55e15', color: '#22c55e' }}><CheckCircle2 size={20} /></div>")
w("          <div className='psd-kpi-body'>")
w("            <span className='psd-kpi-value'>{data.alerts.filter(a => a.acknowledged).length}/{data.alerts.length}</span>")
w("            <span className='psd-kpi-label'>Acknowledged</span>")
w("          </div>")
w("        </div>")
w("      </div>")
w("      <div className='psd-alert-list'>")
w("        {data.alerts.map(alert => {")
w("          const sevColor = alert.severity === 'critical' ? '#ef4444' : alert.severity === 'warning' ? '#f59e0b' : '#06b6d4'")
w("          return (")
w("            <div key={alert.id} className='psd-alert-row' style={{ borderLeftColor: sevColor }}>")
w("              <div className='psd-alert-icon' style={{ background: `${sevColor}20`, color: sevColor }}>")
w("                {alert.severity === 'critical' ? <XCircle size={16} /> : alert.severity === 'warning' ? <AlertTriangle size={16} /> : <CheckCircle2 size={16} />}")
w("              </div>")
w("              <div className='psd-alert-body'>")
w("                <div className='psd-alert-title'>{alert.type} — {alert.laneName}</div>")
w("                <div className='psd-alert-msg'>{alert.message}</div>")
w("                <div className='psd-alert-meta'>")
w("                  <span>{alert.timestamp}</span>")
w("                  <span>{alert.metric}: {alert.value} / {alert.threshold}</span>")
w("                  <span className={`psd-alert-ack ${alert.acknowledged ? 'psd-ack-yes' : 'psd-ack-no'}`}>{alert.acknowledged ? 'ACK' : 'PENDING'}</span>")
w("                </div>")
w("              </div>")
w("            </div>")
w("          )")
w("        })}")
w("      </div>")
w("    </div>")
w("  )")
w()

# ============================================================
# DRAWERS
# ============================================================
w("  // ---- Lane Detail Drawer ----")
w("  const renderLaneDrawer = () => {")
w("    if (!selectedLane) return null")
w("    const l = selectedLane")
w("    const hBg = l.status === 'error' ? 'linear-gradient(135deg, #dc2626, #991b1b)' : l.status === 'active' ? 'linear-gradient(135deg, #ec4899, #be185d)' : l.status === 'maintenance' ? 'linear-gradient(135deg, #f59e0b, #b45309)' : 'linear-gradient(135deg, #6366f1, #4338ca)'")
w("    return (")
w("      <>")
w("      <div className='psd-drawer-overlay' onClick={() => setSelectedLane(null)} />")
w("      <div className='psd-drawer-panel'>")
w("        <div className='psd-drawer-header' style={{ background: hBg }}>")
w("          <div className='psd-drawer-header-top'>")
w("            <div className='psd-drawer-header-info'>")
w("              <GitFork size={24} className='psd-drawer-header-icon' />")
w("              <div>")
w("                <div className='psd-drawer-title'>{l.id}</div>")
w("                <div className='psd-drawer-subtitle'>{l.name} · {l.type}</div>")
w("              </div>")
w("            </div>")
w("            <button className='psd-drawer-close' onClick={() => setSelectedLane(null)}><XCircle size={20} /></button>")
w("          </div>")
w("          <div className='psd-drawer-badges'>")
w("            <span className='psd-drawer-badge' style={{ background: `${statusColor(l.status)}30`, color: '#fff' }}>{l.status}</span>")
w("            <span className='psd-drawer-badge' style={{ background: '#ffffff20', color: '#fff' }}>{l.assignedRoute}</span>")
w("          </div>")
w("        </div>")
w("        <div className='psd-drawer-body'>")
w("          <div className='psd-drawer-grid'>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Hub</span><span className='psd-drawer-value'>{l.hub}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Zone</span><span className='psd-drawer-value'>{l.zone}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Current Parcel</span><span className='psd-drawer-value'>{l.currentParcel}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Conveyor Length</span><span className='psd-drawer-value'>{l.conveyorLength} m</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Sensor Status</span><span className='psd-drawer-value' style={{ color: l.sensorStatus === 'ok' ? '#22c55e' : '#ef4444' }}>{l.sensorStatus.toUpperCase()}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Sort Order</span><span className='psd-drawer-value'>#{l.sortOrder}</span></div>")
w("          </div>")
w("          <div className='psd-drawer-card-row'>")
w("            <div className='psd-drawer-metric-card'>")
w("              <Gauge size={16} style={{ color: THEME.primary }} />")
w("              <span className='psd-drawer-metric-label'>Speed</span>")
w("              <span className='psd-drawer-metric-value'>{l.speed} m/s</span>")
w("              <div className='psd-drawer-metric-bar'><div style={{ width: `${(l.speed / 4) * 100}%`, background: '#ec4899' }} /></div>")
w("            </div>")
w("            <div className='psd-drawer-metric-card'>")
w("              <Activity size={16} style={{ color: '#22c55e' }} />")
w("              <span className='psd-drawer-metric-label'>Throughput</span>")
w("              <span className='psd-drawer-metric-value'>{l.parcelsPerHour}/hr</span>")
w("              <div className='psd-drawer-metric-bar'><div style={{ width: `${(l.parcelsPerHour / 800) * 100}%`, background: '#22c55e' }} /></div>")
w("            </div>")
w("            <div className='psd-drawer-metric-card'>")
w("              <Timer size={16} style={{ color: '#06b6d4' }} />")
w("              <span className='psd-drawer-metric-label'>Uptime</span>")
w("              <span className='psd-drawer-metric-value'>{l.uptime}%</span>")
w("              <div className='psd-drawer-metric-bar'><div style={{ width: `${l.uptime}%`, background: l.uptime > 95 ? '#22c55e' : '#f59e0b' }} /></div>")
w("            </div>")
w("          </div>")
w("          <div className='psd-drawer-section-title'>Performance</div>")
w("          <div className='psd-drawer-grid'>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Total Parcels</span><span className='psd-drawer-value'>{l.totalParcels.toLocaleString()}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Today Volume</span><span className='psd-drawer-value'>{l.todayVolume.toLocaleString()}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Capacity</span><span className='psd-drawer-value'>{l.capacity.toLocaleString()}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Error Rate</span><span className='psd-drawer-value' style={{ color: l.errorRate > 2 ? '#ef4444' : '#22c55e' }}>{l.errorRate}%</span></div>")
w("          </div>")
w("          <div className='psd-drawer-actions'>")
w("            <button className='psd-action-btn psd-action-primary'><Play size={14} /> Start Lane</button>")
w("            <button className='psd-action-btn psd-action-secondary'><Pause size={14} /> Pause</button>")
w("            <button className='psd-action-btn psd-action-secondary'><Wrench size={14} /> Maintenance</button>")
w("            <button className='psd-action-btn psd-action-ghost'><RefreshCw size={14} /> Calibrate</button>")
w("          </div>")
w("        </div>")
w("      </div>")
w("      </>")
w("    )")
w("  }")
w()

w("  // ---- Parcel Detail Drawer ----")
w("  const renderParcelDrawer = () => {")
w("    if (!selectedParcel) return null")
w("    const p = selectedParcel")
w("    const hBg = p.status === 'dispatched' ? 'linear-gradient(135deg, #22c55e, #15803d)' : p.status === 'exception' ? 'linear-gradient(135deg, #ef4444, #991b1b)' : p.status === 'sorting' ? 'linear-gradient(135deg, #ec4899, #be185d)' : 'linear-gradient(135deg, #6366f1, #4338ca)'")
w("    return (")
w("      <>")
w("      <div className='psd-drawer-overlay' onClick={() => setSelectedParcel(null)} />")
w("      <div className='psd-drawer-panel'>")
w("        <div className='psd-drawer-header' style={{ background: hBg }}>")
w("          <div className='psd-drawer-header-top'>")
w("            <div className='psd-drawer-header-info'>")
w("              <Package size={24} className='psd-drawer-header-icon' />")
w("              <div>")
w("                <div className='psd-drawer-title'>{p.id}</div>")
w("                <div className='psd-drawer-subtitle'>AWB: {p.awb}</div>")
w("              </div>")
w("            </div>")
w("            <button className='psd-drawer-close' onClick={() => setSelectedParcel(null)}><XCircle size={20} /></button>")
w("          </div>")
w("          <div className='psd-drawer-badges'>")
w("            <span className='psd-drawer-badge' style={{ background: `${statusColor(p.status)}30`, color: '#fff' }}>{p.status}</span>")
w("            <span className='psd-drawer-badge' style={{ background: `${priorityBadge(p.priority)}40`, color: '#fff' }}>{p.priority}</span>")
w("            {p.fragile && <span className='psd-drawer-badge' style={{ background: '#ffffff30', color: '#fff' }}>FRAGILE</span>}")
w("          </div>")
w("        </div>")
w("        <div className='psd-drawer-body'>")
w("          <div className='psd-drawer-grid'>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Courier</span><span className='psd-drawer-value'>{p.courier}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Service</span><span className='psd-drawer-value'>{p.serviceType}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Hub</span><span className='psd-drawer-value'>{p.hub}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Dock</span><span className='psd-drawer-value'>{p.dock}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Sort Lane</span><span className='psd-drawer-value'>{p.sortLane}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Scanned</span><span className='psd-drawer-value' style={{ color: p.scanned ? '#22c55e' : '#ef4444' }}>{p.scanned ? 'YES' : 'NO'}</span></div>")
w("          </div>")
w("          <div className='psd-drawer-section-title'>Dimensions & Weight</div>")
w("          <div className='psd-drawer-grid'>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Weight</span><span className='psd-drawer-value'>{p.weight} kg</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Dimensions</span><span className='psd-drawer-value'>{p.dimensions} cm</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Declared Value</span><span className='psd-drawer-value'>{formatINR(p.value)}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Barcode</span><span className='psd-drawer-value' style={{ fontFamily: 'monospace', fontSize: 11 }}>{p.barcode}</span></div>")
w("          </div>")
w("          <div className='psd-drawer-section-title'>Route</div>")
w("          <div className='psd-drawer-grid'>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>From</span><span className='psd-drawer-value'>{p.senderCity}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>To</span><span className='psd-drawer-value'>{p.receiverCity}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Created</span><span className='psd-drawer-value'>{p.created}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Sorted</span><span className='psd-drawer-value'>{p.sorted}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Dispatched</span><span className='psd-drawer-value'>{p.dispatched || '—'}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Time in Hub</span><span className='psd-drawer-value'>{p.timeInHub} min</span></div>")
w("          </div>")
w("          <div className='psd-drawer-actions'>")
w("            <button className='psd-action-btn psd-action-primary'><ScanBarcode size={14} /> Rescan</button>")
w("            <button className='psd-action-btn psd-action-secondary'><Shuffle size={14} /> Re-sort</button>")
w("            <button className='psd-action-btn psd-action-ghost'><Eye size={14} /> Track</button>")
w("          </div>")
w("        </div>")
w("      </div>")
w("      </>")
w("    )")
w("  }")
w()

w("  // ---- Batch Detail Drawer ----")
w("  const renderBatchDrawer = () => {")
w("    if (!selectedBatch) return null")
w("    const b = selectedBatch")
w("    return (")
w("      <>")
w("      <div className='psd-drawer-overlay' onClick={() => setSelectedBatch(null)} />")
w("      <div className='psd-drawer-panel'>")
w("        <div className='psd-drawer-header' style={{ background: 'linear-gradient(135deg, #f97316, #c2410c)' }}>")
w("          <div className='psd-drawer-header-top'>")
w("            <div className='psd-drawer-header-info'>")
w("              <ArrowRightLeft size={24} className='psd-drawer-header-icon' />")
w("              <div>")
w("                <div className='psd-drawer-title'>{b.id}</div>")
w("                <div className='psd-drawer-subtitle'>{b.status} · Priority: {b.priority}</div>")
w("              </div>")
w("            </div>")
w("            <button className='psd-drawer-close' onClick={() => setSelectedBatch(null)}><XCircle size={20} /></button>")
w("          </div>")
w("        </div>")
w("        <div className='psd-drawer-body'>")
w("          <div className='psd-drawer-grid'>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Hub</span><span className='psd-drawer-value'>{b.hub}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Status</span><span className='psd-drawer-value' style={{ color: statusColor(b.status) }}>{b.status}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Inbound Truck</span><span className='psd-drawer-value'>{b.inboundTruck}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Outbound Truck</span><span className='psd-drawer-value'>{b.outboundTruck}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Dock In</span><span className='psd-drawer-value'>{b.dockIn}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Dock Out</span><span className='psd-drawer-value'>{b.dockOut}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Total Parcels</span><span className='psd-drawer-value'>{b.totalParcels}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Sorted</span><span className='psd-drawer-value'>{b.sortedParcels}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Target SLA</span><span className='psd-drawer-value'>{b.targetSLA} min</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Elapsed</span><span className='psd-drawer-value'>{b.elapsed} min</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Efficiency</span><span className='psd-drawer-value'>{b.efficiency > 0 ? `${b.efficiency}%` : '—'}</span></div>")
w("            <div className='psd-drawer-field'><span className='psd-drawer-label'>Started</span><span className='psd-drawer-value'>{b.startTime}</span></div>")
w("          </div>")
w("          <div className='psd-drawer-actions'>")
w("            <button className='psd-action-btn psd-action-primary'><Play size={14} /> Resume</button>")
w("            <button className='psd-action-btn psd-action-secondary'><RefreshCw size={14} /> Reassign</button>")
w("            <button className='psd-action-btn psd-action-ghost'><Eye size={14} /> Monitor</button>")
w("          </div>")
w("        </div>")
w("      </div>")
w("      </>")
w("    )")
w("  }")
w()

# ============================================================
# MAIN RENDER
# ============================================================
w("  const renderTab = () => {")
w("    switch (activeTab) {")
w("      case 0: return renderDashboard()")
w("      case 1: return renderLanes()")
w("      case 2: return renderParcels()")
w("      case 3: return renderCrossDock()")
w("      case 4: return renderRoutesAlerts()")
w("      default: return null")
w("    }")
w("  }")
w()
w("  return (")
w("    <div className='psd-container'>")
w("      <div className='psd-page-header'>")
w("        <div className='psd-page-title-row'>")
w("          <GitFork size={28} style={{ color: THEME.primary }} />")
w("          <div>")
w("            <h1 className='psd-page-title'>Parcel Sorting & Cross-Dock</h1>")
w("            <p className='psd-page-subtitle'>Automated Parcel Sorting, Cross-Dock Transfer & Route Optimization</p>")
w("          </div>")
w("        </div>")
w("        <div className='psd-header-stats'>")
w("          <span className='psd-header-stat'><GitFork size={14} />{data.lanes.length} Lanes</span>")
w("          <span className='psd-header-stat'><Package size={14} />{data.parcels.length} Parcels</span>")
w("          <span className='psd-header-stat'><ArrowRightLeft size={14} />{data.batches.length} Batches</span>")
w("          <span className='psd-header-stat'><AlertTriangle size={14} />{data.alerts.length} Alerts</span>")
w("        </div>")
w("      </div>")
w()
w("      <div className='psd-tabs'>")
w("        {tabs.map((tab, i) => (")
w("          <button key={tab} className={`psd-tab ${activeTab === i ? 'psd-tab-active' : ''}`} onClick={() => { setActiveTab(i); setCurrentPage(1); setParcelPage(1); setStatusFilter('all'); setTypeFilter('all'); setPriorityFilter('all'); setCourierFilter('all'); setSearchQuery('') }}>")
w("            {tab}")
w("          </button>")
w("        ))}")
w("      </div>")
w()
w("      {renderTab()}")
w("      {renderLaneDrawer()}")
w("      {renderParcelDrawer()}")
w("      {renderBatchDrawer()}")
w("    </div>")
w("  )")
w("}")
w()

# Write
outpath = "/home/z/my-project/src/components/modules/parcel-sorting-crossdock-view.tsx"
with open(outpath, "w") as f:
    f.write("\n".join(LINES))

print(f"Generated {len(LINES)} lines → {outpath}")
