#!/usr/bin/env python3
"""Generate R166: AGV Fleet Management module (~1400 lines)"""

LINES = []

def w(line=""):
    LINES.append(line)

# ============================================================
# HEADER & TYPES
# ============================================================
w("'use client'")
w()
w("import React, { useState, useEffect, useMemo } from 'react'")
w("import {")
w("  Bot, Zap, Battery, AlertTriangle, CheckCircle2, XCircle,")
w("  Thermometer, Activity, MapPin, Clock, BarChart3, PieChart as PieChartIcon,")
w("  Eye, ChevronLeft, ChevronRight, ChevronDown, ChevronUp,")
w("  Wrench, Play, Pause, Square, RefreshCw, Filter,")
w("  Signal, Gauge, Cpu, MapPinned, ArrowUpDown, TrendingUp,")
w("  Package, Box, Warehouse, CircleDot, Circle, TriangleAlert")
w("} from 'lucide-react'")
w("import {")
w("  ComposedChart, Bar, Line, Area, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer,")
w("  PieChart, Pie, Cell, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar,")
w("  AreaChart")
w("} from 'recharts'")
w()
w("// ============================================================")
w("// TYPES")
w("// ============================================================")
w()
w("interface AGVVehicle {")
w("  id: string; name: string; model: string; type: string;")
w("  warehouse: string; zone: string;")
w("  status: string; batteryLevel: number;")
w("  currentTask: string; speed: number;")
w("  loadWeight: number; maxLoad: number;")
w("  totalDistance: number; totalTasks: number;")
w("  uptimeHours: number; lastMaintenance: string;")
w("  nextMaintenance: string;")
w("  firmware: string; cpuUsage: number; memoryUsage: number;")
w("  motorTemp: number; lidarStatus: string;")
w("  aisle: string; targetLocation: string;")
w("  errorCount24h: number; efficiency: number;")
w("  assignedTo: string;")
w("}")
w()
w("interface AGVTask {")
w("  id: string; agvId: string; agvName: string;")
w("  type: string; priority: string; status: string;")
w("  pickupLocation: string; dropoffLocation: string;")
w("  aisle: string; weight: number;")
w("  created: string; started: string; completed: string | null;")
w("  distance: number; estimatedTime: number; actualTime: number | null;")
w("  assignedBy: string;")
w("}")
w()
w("interface ChargingStation {")
w("  id: string; name: string; warehouse: string;")
w("  zone: string; status: string;")
w("  totalSlots: number; occupiedSlots: number;")
w("  powerOutput: number; avgChargeTime: number;")
w("  totalCharges: number; efficiency: number;")
w("  lastMaintenance: string;")
w("}")
w()
w("interface AGVAlert {")
w("  id: string; agvId: string; agvName: string;")
w("  type: string; severity: string; message: string;")
w("  timestamp: string; acknowledged: boolean;")
w("  value: number; threshold: number;")
w("}")
w()
w("interface ZoneMapCell {")
w("  aisle: string; zone: string;")
w("  agvCount: number; taskDensity: number;")
w("  congestion: string;")
w("}")
w()
w("interface PathRoute {")
w("  id: string; name: string; status: string;")
w("  length: number; avgTime: number; trafficLevel: string;")
w("  agvCount: number; incidents24h: number;")
w("}")
w()

# ============================================================
# SEEDED RANDOM & DATA GENERATION
# ============================================================
w("function seededRandom(seed: number): () => number {")
w("  let s = seed % 2147483647")
w("  if (s <= 0) s += 2147483646")
w("  return () => { s = (s * 16807) % 2147483647; return (s - 1) / 2147483646 }")
w("}")
w()
w("function generateData() {")
w("  const rng = seededRandom(166166)")
w("  const r = (min: number, max: number) => Math.floor(rng() * (max - min + 1)) + min")
w("  const rf = (min: number, max: number) => +(rng() * (max - min) + min).toFixed(1)")
w("  const pick = <T,>(arr: T[]): T => arr[Math.floor(rng() * arr.length)]")
w()
w("  const warehouses = ['WH-Mumbai-01','WH-Delhi-02','WH-Bengaluru-03','WH-Chennai-04','WH-Hyderabad-05','WH-Pune-06','WH-Kolkata-07','WH-Jaipur-08']")
w("  const zones = ['Zone-A','Zone-B','Zone-C','Zone-D','Zone-E','Zone-F']")
w("  const agvModels = ['AMR-ProX-500','AMR-FleetM-300','AGV-PalletL-800','AMR-PickP-200','AGV-HeavyH-1200','AMR-SortS-400']")
w("  const agvTypes = ['Pallet Mover','Pick & Place','Sorter','Heavy Lift','Hybrid','Forklift AGV']")
w("  const statuses = ['active','idle','charging','maintenance','error','offline']")
w("  const taskTypes = ['Pallet Transport','Order Picking','Replenishment','Returns Processing','Cross-Dock Transfer','Inventory Count']")
w("  const priorities = ['critical','high','normal','low']")
w("  const taskStatuses = ['in_progress','completed','pending','cancelled','failed']")
w("  const alertTypes = ['Low Battery','Obstacle Detected','Motor Overheating','Lidar Fault','Path Blocked','Communication Lost','Load Unbalanced','Charging Fault','Firmware Error','Collision Avoidance']")
w("  const severities = ['critical','warning','info']")
w("  const firmwareVersions = ['v3.2.1','v3.1.4','v3.3.0','v2.9.8','v3.2.0']")
w("  const aisles = ['A1','A2','A3','A4','B1','B2','B3','B4','C1','C2','C3','C4','D1','D2','D3','D4']")
w("  const locations = ['St-01','St-02','St-03','St-04','St-05','St-06','St-07','St-08','St-09','St-10','St-11','St-12','St-13','St-14','St-15','St-16','Dk-01','Dk-02','Dk-03','Dk-04']")
w()
w("  // Generate 50 AGVs")
w("  const agvs: AGVVehicle[] = Array.from({ length: 50 }, (_, i) => {")
w("    const st = pick(statuses)")
w("    const wt = rf(300, 1200)")
w("    const battery = st === 'charging' ? rf(15, 95) : st === 'error' ? rf(5, 40) : rf(35, 100)")
w("    return {")
w("      id: `AGV-${String(i + 1).padStart(3, '0')}`,")
w("      name: `${pick(agvModels)}-${String(i + 1).padStart(3, '0')}`.substring(0, 22),")
w("      model: pick(agvModels),")
w("      type: pick(agvTypes),")
w("      warehouse: pick(warehouses),")
w("      zone: pick(zones),")
w("      status: st,")
w("      batteryLevel: battery,")
w("      currentTask: st === 'active' ? pick(taskTypes) : st === 'error' ? 'Fault Recovery' : '—',")
w("      speed: st === 'active' ? rf(0.5, 2.5) : 0,")
w("      loadWeight: st === 'active' ? rf(50, wt * 0.9) : rf(0, 30),")
w("      maxLoad: wt,")
w("      totalDistance: rf(120, 8500),")
w("      totalTasks: r(80, 3200),")
w("      uptimeHours: rf(200, 4800),")
w("      lastMaintenance: `${r(1,28)} days ago`,")
w("      nextMaintenance: `${r(1,30)} days`,")
w("      firmware: pick(firmwareVersions),")
w("      cpuUsage: st === 'active' ? rf(40, 85) : st === 'idle' ? rf(5, 20) : rf(10, 30),")
w("      memoryUsage: st === 'active' ? rf(45, 78) : rf(20, 45),")
w("      motorTemp: st === 'active' ? rf(38, 72) : rf(28, 42),")
w("      lidarStatus: st === 'error' && rng() > 0.5 ? 'fault' : 'ok',")
w("      aisle: st === 'active' ? pick(aisles) : '—',")
w("      targetLocation: st === 'active' ? pick(locations) : '—',")
w("      errorCount24h: st === 'error' ? r(1, 8) : r(0, 2),")
w("      efficiency: st === 'active' ? rf(65, 98) : st === 'idle' ? 0 : rf(50, 85),")
w("      assignedTo: st === 'active' ? `Operator-${r(1, 12).toString().padStart(2, '0')}` : '—',")
w("    }")
w("  })")
w()
w("  // Generate 300 tasks")
w("  const tasks: AGVTask[] = Array.from({ length: 300 }, (_, i) => {")
w("    const st = pick(taskStatuses)")
w("    const agv = pick(agvs)")
w("    const dist = rf(20, 350)")
w("    const et = rf(3, 25)")
w("    return {")
w("      id: `TSK-${String(i + 1).padStart(4, '0')}`,")
w("      agvId: agv.id,")
w("      agvName: agv.name.substring(0, 18),")
w("      type: pick(taskTypes),")
w("      priority: pick(priorities),")
w("      status: st,")
w("      pickupLocation: pick(locations),")
w("      dropoffLocation: pick(locations),")
w("      aisle: pick(aisles),")
w("      weight: rf(20, 800),")
w("      created: `${r(1,30)}h ago`,")
w("      started: st !== 'pending' ? `${r(1,20)}h ago` : '—',")
w("      completed: st === 'completed' || st === 'failed' ? `${r(0,10)}h ago` : null,")
w("      distance: dist,")
w("      estimatedTime: et,")
w("      actualTime: st === 'completed' ? rf(et * 0.7, et * 1.4) : null,")
w("      assignedBy: `Scheduler-${r(1, 4)}`,")
w("    }")
w("  })")
w()
w("  // Generate 20 charging stations")
w("  const stations: ChargingStation[] = Array.from({ length: 20 }, (_, i) => {")
w("    const occ = r(0, 4)")
w("    return {")
w("      id: `CHG-${String(i + 1).padStart(3, '0')}`,")
w("      name: `Charger-${pick(['Alpha','Beta','Gamma','Delta','Sigma','Omega'])}-${String(i + 1).padStart(2, '0')}`,")
w("      warehouse: pick(warehouses),")
w("      zone: pick(zones),")
w("      status: pick(['online','online','online','maintenance']),")
w("      totalSlots: r(4, 8),")
w("      occupiedSlots: occ,")
w("      powerOutput: r(50, 150),")
w("      avgChargeTime: rf(45, 120),")
w("      totalCharges: r(200, 5000),")
w("      efficiency: rf(82, 99),")
w("      lastMaintenance: `${r(1,60)} days ago`,")
w("    }")
w("  })")
w()
w("  // Generate 15 alerts")
w("  const alerts: AGVAlert[] = Array.from({ length: 15 }, (_, i) => {")
w("    const agv = pick(agvs)")
w("    const sev = pick(severities)")
w("    return {")
w("      id: `ALT-${String(i + 1).padStart(4, '0')}`,")
w("      agvId: agv.id,")
w("      agvName: agv.name.substring(0, 18),")
w("      type: pick(alertTypes),")
w("      severity: sev,")
w("      message: `${pick(alertTypes)} on ${agv.id} ${sev === 'critical' ? 'requires immediate attention' : sev === 'warning' ? 'needs monitoring' : 'logged for review'}`,")
w("      timestamp: `${r(1,48)}h ago`,")
w("      acknowledged: rng() > 0.6,")
w("      value: rf(0, 100),")
w("      threshold: rf(60, 95),")
w("    }")
w("  })")
w()
w("  // Generate zone map (16 cells)")
w("  const zoneMap: ZoneMapCell[] = aisles.slice(0, 16).map((aisle, i) => ({")
w("    aisle,")
w("    zone: pick(zones),")
w("    agvCount: r(0, 5),")
w("    taskDensity: r(1, 10),")
w("    congestion: pick(['low','medium','high']),")
w("  }))")
w()
w("  // Generate 12 path routes")
w("  const paths: PathRoute[] = Array.from({ length: 12 }, (_, i) => ({")
w("    id: `PATH-${String(i + 1).padStart(2, '0')}`,")
w("    name: `${pick(['Main Corridor','Cross Aisle','Dock Route','Staging Path','Receiving Lane','Shipping Lane','Pick Zone Loop','Buffer Transfer','High-Speed Bypass','Return Loop','Emergency Escape','Service Tunnel'])} ${String(i+1).padStart(2,'0')}`,")
w("    status: pick(['active','active','active','blocked','restricted']),")
w("    length: rf(30, 250),")
w("    avgTime: rf(2, 15),")
w("    trafficLevel: pick(['low','medium','high']),")
w("    agvCount: r(0, 6),")
w("    incidents24h: r(0, 3),")
w("  }))")
w()
w("  // KPI data")
w("  const activeAGVs = agvs.filter(a => a.status === 'active').length")
w("  const avgBattery = +(agvs.reduce((s, a) => s + a.batteryLevel, 0) / agvs.length).toFixed(1)")
w("  const avgEfficiency = +(agvs.filter(a => a.status === 'active').reduce((s, a) => s + a.efficiency, 0) / Math.max(activeAGVs, 1)).toFixed(1)")
w("  const completedTasks24h = tasks.filter(t => t.status === 'completed').length")
w("  const totalDistanceToday = +agvs.reduce((s, a) => s + a.totalDistance, 0).toFixed(1)")
w("  const errorAGVs = agvs.filter(a => a.status === 'error').length")
w()
w("  // Hourly throughput data (24h)")
w("  const hourlyData = Array.from({ length: 24 }, (_, i) => ({")
w("    hour: `${String(i).padStart(2, '0')}:00`,")
w("    tasksCompleted: r(8, 35),")
w("    tasksAssigned: r(5, 30),")
w("    avgSpeed: rf(0.8, 2.2),")
w("    energyUsage: r(40, 180),")
w("  }))")
w()
w("  // Type distribution")
w("  const typeCounts: Record<string, number> = {}")
w("  agvs.forEach(a => { typeCounts[a.type] = (typeCounts[a.type] || 0) + 1 })")
w("  const typePieData = Object.entries(typeCounts).map(([name, value]) => ({ name, value }))")
w()
w("  // Battery distribution")
w("  const batteryDist = [")
w("    { range: 'Critical (0-15%)', count: agvs.filter(a => a.batteryLevel <= 15).length, color: '#ef4444' },")
w("    { range: 'Low (16-30%)', count: agvs.filter(a => a.batteryLevel > 15 && a.batteryLevel <= 30).length, color: '#f97316' },")
w("    { range: 'Medium (31-60%)', count: agvs.filter(a => a.batteryLevel > 30 && a.batteryLevel <= 60).length, color: '#f59e0b' },")
w("    { range: 'Good (61-85%)', count: agvs.filter(a => a.batteryLevel > 60 && a.batteryLevel <= 85).length, color: '#22c55e' },")
w("    { range: 'Full (86-100%)', count: agvs.filter(a => a.batteryLevel > 85).length, color: '#06b6d4' },")
w("  ]")
w()
w("  // Warehouse radar")
w("  const warehouseRadar = warehouses.slice(0, 6).map(wh => {")
w("    const whAGVs = agvs.filter(a => a.warehouse === wh)")
w("    return {")
w("      warehouse: wh.replace('WH-', '').replace('-0', ' #'),")
w("      utilization: +((whAGVs.filter(a => a.status === 'active').length / Math.max(whAGVs.length, 1)) * 100).toFixed(0),")
w("      efficiency: +((whAGVs.reduce((s, a) => s + a.efficiency, 0) / Math.max(whAGVs.length, 1))).toFixed(0),")
w("      battery: +((whAGVs.reduce((s, a) => s + a.batteryLevel, 0) / Math.max(whAGVs.length, 1))).toFixed(0),")
w("      throughput: r(40, 95),")
w("    }")
w("  })")
w()
w("  return {")
w("    agvs, tasks, stations, alerts, zoneMap, paths,")
w("    hourlyData, typePieData, batteryDist, warehouseRadar,")
w("    activeAGVs, avgBattery, avgEfficiency, completedTasks24h, totalDistanceToday, errorAGVs,")
w("    // return enums used in JSX")
w("    statuses, agvTypes, taskTypes, priorities, taskStatuses, severities,")
w("    warehouses, zones, aisles,")
w("  }")
w("}")
w()

# ============================================================
# COMPONENT
# ============================================================
w()
w("const COLORS = ['#f97316', '#06b6d4', '#8b5cf6', '#22c55e', '#ef4444', '#f59e0b']")
w("const THEME = { primary: '#f97316', secondary: '#06b6d4', accent: '#8b5cf6', success: '#22c55e', danger: '#ef4444', warning: '#f59e0b' }")
w()
w("function formatINR(num: number): string {")
w("  if (num >= 10000000) return `₹${(num / 10000000).toFixed(2)} Cr`")
w("  if (num >= 100000) return `₹${(num / 100000).toFixed(2)} L`")
w("  return `₹${num.toLocaleString('en-IN')}`")
w("}")
w()
w("export default function AGVFleetManagementView() {")
w("  const data = useMemo(() => generateData(), [])")
w("  const [activeTab, setActiveTab] = useState(0)")
w("  const [selectedAGV, setSelectedAGV] = useState<AGVVehicle | null>(null)")
w("  const [selectedTask, setSelectedTask] = useState<AGVTask | null>(null)")
w("  const [selectedStation, setSelectedStation] = useState<ChargingStation | null>(null)")
w("  const [currentPage, setCurrentPage] = useState(1)")
w("  const [searchQuery, setSearchQuery] = useState('')")
w("  const [statusFilter, setStatusFilter] = useState('all')")
w("  const [typeFilter, setTypeFilter] = useState('all')")
w("  const [priorityFilter, setPriorityFilter] = useState('all')")
w("  const [sortField, setSortField] = useState<string>('id')")
w("  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('asc')")
w("  const [taskPage, setTaskPage] = useState(1)")
w("  const rowsPerPage = 15")
w()
w("  // Live clock")
w("  const [currentTime, setCurrentTime] = useState('')")
w("  useEffect(() => {")
w("    const tick = () => setCurrentTime(new Date().toLocaleTimeString('en-IN', { timeZone: 'Asia/Kolkata', hour12: false }))")
w("    tick()")
w("    const iv = setInterval(tick, 1000)")
w("    return () => clearInterval(iv)")
w("  }, [])")
w()
w("  // Filtered/sorted fleets")
w("  const filteredAGVs = useMemo(() => {")
w("    let list = data.agvs.filter(a => {")
w("      if (statusFilter !== 'all' && a.status !== statusFilter) return false")
w("      if (typeFilter !== 'all' && a.type !== typeFilter) return false")
w("      if (searchQuery && !a.id.toLowerCase().includes(searchQuery.toLowerCase()) && !a.name.toLowerCase().includes(searchQuery.toLowerCase()) && !a.warehouse.toLowerCase().includes(searchQuery.toLowerCase())) return false")
w("      return true")
w("    })")
w("    list.sort((a, b) => {")
w("      const aVal = (a as any)[sortField]")
w("      const bVal = (b as any)[sortField]")
w("      if (typeof aVal === 'string') return sortDir === 'asc' ? aVal.localeCompare(bVal) : bVal.localeCompare(aVal)")
w("      return sortDir === 'asc' ? (aVal as number) - (bVal as number) : (bVal as number) - (aVal as number)")
w("    })")
w("    return list")
w("  }, [data, statusFilter, typeFilter, searchQuery, sortField, sortDir])")
w()
w("  const filteredTasks = useMemo(() => {")
w("    return data.tasks.filter(t => {")
w("      if (priorityFilter !== 'all' && t.priority !== priorityFilter) return false")
w("      if (statusFilter !== 'all' && t.status !== statusFilter) return false")
w("      if (searchQuery && !t.id.toLowerCase().includes(searchQuery.toLowerCase()) && !t.agvName.toLowerCase().includes(searchQuery.toLowerCase()) && !t.type.toLowerCase().includes(searchQuery.toLowerCase())) return false")
w("      return true")
w("    })")
w("  }, [data, priorityFilter, statusFilter, searchQuery])")
w()
w("  const paginatedAGVs = filteredAGVs.slice((currentPage - 1) * rowsPerPage, currentPage * rowsPerPage)")
w("  const paginatedTasks = filteredTasks.slice((taskPage - 1) * rowsPerPage, taskPage * rowsPerPage)")
w("  const totalPages = Math.ceil(filteredAGVs.length / rowsPerPage)")
w("  const totalTaskPages = Math.ceil(filteredTasks.length / rowsPerPage)")
w()
w("  const toggleSort = (field: string) => {")
w("    if (sortField === field) setSortDir(d => d === 'asc' ? 'desc' : 'asc')")
w("    else { setSortField(field); setSortDir('asc') }")
w("  }")
w()
w("  const tabs = ['Dashboard', 'Fleet Overview', 'Task Queue', 'Charging Network', 'Path Planning & Alerts']")
w()
w("  const statusColor = (s: string) => {")
w("    const map: Record<string, string> = { active: '#22c55e', idle: '#6b7280', charging: '#06b6d4', maintenance: '#f59e0b', error: '#ef4444', offline: '#374151' }")
w("    return map[s] || '#6b7280'")
w("  }")
w()
w("  const batteryColor = (lv: number) => lv > 60 ? '#22c55e' : lv > 30 ? '#f59e0b' : '#ef4444'")
w()
w("  const priorityBadge = (p: string) => {")
w("    const c: Record<string, string> = { critical: '#ef4444', high: '#f97316', normal: '#06b6d4', low: '#6b7280' }")
w("    return c[p] || '#6b7280'")
w("  }")
w()
w("  // =====================================================")
w("  // TAB 0: DASHBOARD")
w("  // =====================================================")
w("  const renderDashboard = () => (")
w("    <div className='agv-tab-content'>")
w("      <div className='agv-clock-row'>")
w("        <Bot size={18} style={{ color: THEME.primary }} />")
w("        <span className='agv-live-dot' />")
w("        <span className='agv-clock-text'>Live — {currentTime} IST</span>")
w("      </div>")
w()
w("      {/* KPIs */}")
w("      <div className='agv-kpi-grid'>")
w("        {['active','charging','error'].map(st => {")
w("          const count = data.agvs.filter(a => a.status === st).length")
w("          return (")
w("            <div key={st} className='agv-kpi-card' style={{ borderTopColor: statusColor(st) }}>")
w("              <div className='agv-kpi-icon' style={{ background: `${statusColor(st)}15`, color: statusColor(st) }}>")
w("                {st === 'active' ? <Zap size={20} /> : st === 'charging' ? <Battery size={20} /> : <AlertTriangle size={20} />}")
w("              </div>")
w("              <div className='agv-kpi-body'>")
w("                <span className='agv-kpi-value'>{count}</span>")
w("                <span className='agv-kpi-label'>{st === 'active' ? 'Active AGVs' : st === 'charging' ? 'Charging' : 'Errors'}</span>")
w("              </div>")
w("            </div>")
w("          )")
w("        })}")
w("        <div className='agv-kpi-card' style={{ borderTopColor: THEME.secondary }}>")
w("          <div className='agv-kpi-icon' style={{ background: '#06b6d415', color: THEME.secondary }}><Activity size={20} /></div>")
w("          <div className='agv-kpi-body'>")
w("            <span className='agv-kpi-value'>{data.avgEfficiency}%</span>")
w("            <span className='agv-kpi-label'>Avg Efficiency</span>")
w("          </div>")
w("        </div>")
w("        <div className='agv-kpi-card' style={{ borderTopColor: THEME.accent }}>")
w("          <div className='agv-kpi-icon' style={{ background: '#8b5cf615', color: THEME.accent }}><BarChart3 size={20} /></div>")
w("          <div className='agv-kpi-body'>")
w("            <span className='agv-kpi-value'>{data.completedTasks24h}</span>")
w("            <span className='agv-kpi-label'>Tasks Completed</span>")
w("          </div>")
w("        </div>")
w("        <div className='agv-kpi-card' style={{ borderTopColor: THEME.warning }}>")
w("          <div className='agv-kpi-icon' style={{ background: '#f59e0b15', color: THEME.warning }}><Gauge size={20} /></div>")
w("          <div className='agv-kpi-body'>")
w("            <span className='agv-kpi-value'>{data.totalDistanceToday.toLocaleString()}</span>")
w("            <span className='agv-kpi-label'>Total Distance (m)</span>")
w("          </div>")
w("        </div>")
w("      </div>")
w()
w("      {/* Charts row 1 */}")
w("      <div className='agv-charts-row'>")
w("        <div className='agv-chart-card agv-chart-wide'>")
w("          <div className='agv-chart-header'><h4 className='agv-chart-title'>24h Throughput & Energy</h4></div>")
w("          <ResponsiveContainer width='100%' height={260}>")
w("            <ComposedChart data={data.hourlyData}>")
w("              <CartesianGrid strokeDasharray='3 3' stroke='#1e293b' />")
w("              <XAxis dataKey='hour' stroke='#64748b' tick={{ fontSize: 10 }} interval={2} />")
w("              <YAxis yAxisId='left' stroke='#64748b' tick={{ fontSize: 10 }} />")
w("              <YAxis yAxisId='right' orientation='right' stroke='#64748b' tick={{ fontSize: 10 }} />")
w("              <Tooltip contentStyle={{ background: '#1e293b', border: '1px solid #334155', borderRadius: 8 }} />")
w("              <Legend wrapperStyle={{ fontSize: 11 }} />")
w("              <Bar yAxisId='left' dataKey='tasksCompleted' fill='#22c55e' radius={[4, 4, 0, 0]} name='Completed' />")
w("              <Bar yAxisId='left' dataKey='tasksAssigned' fill='#06b6d4' radius={[4, 4, 0, 0]} name='Assigned' />")
w("              <Line yAxisId='right' dataKey='energyUsage' stroke='#f97316' strokeWidth={2} dot={false} name='Energy (kWh)' />")
w("            </ComposedChart>")
w("          </ResponsiveContainer>")
w("        </div>")
w("        <div className='agv-chart-card'>")
w("          <div className='agv-chart-header'><h4 className='agv-chart-title'>AGV Type Distribution</h4></div>")
w("          <ResponsiveContainer width='100%' height={260}>")
w("            <PieChart>")
w("              <Pie data={data.typePieData} cx='50%' cy='50%' outerRadius={80} innerRadius={45} dataKey='value' label={({ name, percent }) => `${name.split(' ')[0]} ${(percent * 100).toFixed(0)}%`} labelLine={{ stroke: '#475569' }}>")
w("                {data.typePieData.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}")
w("              </Pie>")
w("              <Tooltip contentStyle={{ background: '#1e293b', border: '1px solid #334155', borderRadius: 8 }} />")
w("            </PieChart>")
w("          </ResponsiveContainer>")
w("        </div>")
w("      </div>")
w()
w("      {/* Charts row 2 */}")
w("      <div className='agv-charts-row'>")
w("        <div className='agv-chart-card'>")
w("          <div className='agv-chart-header'><h4 className='agv-chart-title'>Warehouse Performance Radar</h4></div>")
w("          <ResponsiveContainer width='100%' height={260}>")
w("            <RadarChart data={data.warehouseRadar}>")
w("              <PolarGrid stroke='#334155' />")
w("              <PolarAngleAxis dataKey='warehouse' stroke='#94a3b8' tick={{ fontSize: 10 }} />")
w("              <PolarRadiusAxis stroke='#475569' tick={{ fontSize: 9 }} />")
w("              <Radar name='Utilization' dataKey='utilization' stroke='#f97316' fill='#f9731630' strokeWidth={2} />")
w("              <Radar name='Efficiency' dataKey='efficiency' stroke='#06b6d4' fill='#06b6d430' strokeWidth={2} />")
w("              <Radar name='Battery' dataKey='battery' stroke='#22c55e' fill='#22c55e30' strokeWidth={2} />")
w("              <Legend wrapperStyle={{ fontSize: 10 }} />")
w("            </RadarChart>")
w("          </ResponsiveContainer>")
w("        </div>")
w("        <div className='agv-chart-card'>")
w("          <div className='agv-chart-header'><h4 className='agv-chart-title'>Battery Distribution</h4></div>")
w("          <ResponsiveContainer width='100%' height={260}>")
w("            <BarChart data={data.batteryDist}>")
w("              <CartesianGrid strokeDasharray='3 3' stroke='#1e293b' />")
w("              <XAxis dataKey='range' stroke='#64748b' tick={{ fontSize: 8 }} angle={-25} textAnchor='end' height={60} />")
w("              <YAxis stroke='#64748b' tick={{ fontSize: 10 }} />")
w("              <Tooltip contentStyle={{ background: '#1e293b', border: '1px solid #334155', borderRadius: 8 }} />")
w("              <Bar dataKey='count' radius={[6, 6, 0, 0]}>")
w("                {data.batteryDist.map((entry, i) => <Cell key={i} fill={entry.color} />)}")
w("              </Bar>")
w("            </BarChart>")
w("          </ResponsiveContainer>")
w("        </div>")
w("      </div>")
w()
w("      {/* Zone heat map */}")
w("      <div className='agv-chart-card agv-chart-full'>")
w("        <div className='agv-chart-header'><h4 className='agv-chart-title'>Zone Traffic Heat Map</h4></div>")
w("        <div className='agv-heatmap-grid'>")
w("          {data.zoneMap.map((cell) => {")
w("            const bg = cell.congestion === 'high' ? '#ef4444' : cell.congestion === 'medium' ? '#f59e0b' : '#22c55e'")
w("            const opacity = 0.2 + (cell.agvCount / 5) * 0.8")
w("            return (")
w("              <div key={cell.aisle} className='agv-heatmap-cell' style={{ background: `${bg}${Math.round(opacity * 255).toString(16).padStart(2, '0')}`, borderColor: bg }}>")
w("                <span className='agv-heatmap-aisle'>{cell.aisle}</span>")
w("                <span className='agv-heatmap-zone'>{cell.zone}</span>")
w("                <span className='agv-heatmap-count'>{cell.agvCount} AGV{cell.agvCount !== 1 ? 's' : ''}</span>")
w("                <span className='agv-heatmap-density' style={{ color: bg }}>{cell.congestion}</span>")
w("              </div>")
w("            )")
w("          })}")
w("        </div>")
w("      </div>")
w("    </div>")
w("  )")
w()

# ============================================================
# TAB 1: FLEET OVERVIEW
# ============================================================
w("  // =====================================================")
w("  // TAB 1: FLEET OVERVIEW")
w("  // =====================================================")
w("  const renderFleet = () => (")
w("    <div className='agv-tab-content'>")
w("      {/* Filter row */}")
w("      <div className='agv-filter-row'>")
w("        <div className='agv-search-box'>")
w("          <input type='text' placeholder='Search AGV ID, name, warehouse...' value={searchQuery} onChange={e => { setSearchQuery(e.target.value); setCurrentPage(1) }} className='agv-search-input' />")
w("        </div>")
w("        <div className='agv-filter-pills'>")
w("          <button className={`agv-pill ${statusFilter === 'all' ? 'agv-pill-active' : ''}`} onClick={() => setStatusFilter('all')}>All</button>")
w("          {data.statuses.map(s => (")
w("            <button key={s} className={`agv-pill ${statusFilter === s ? 'agv-pill-active' : ''}`} style={statusFilter === s ? { background: statusColor(s), borderColor: statusColor(s) } : {}} onClick={() => setStatusFilter(s)}>{s}</button>")
w("          ))}")
w("        </div>")
w("        <div className='agv-filter-pills'>")
w("          <button className={`agv-pill ${typeFilter === 'all' ? 'agv-pill-active' : ''}`} onClick={() => setTypeFilter('all')}>All Types</button>")
w("          {data.agvTypes.map(t => (")
w("            <button key={t} className={`agv-pill ${typeFilter === t ? 'agv-pill-active' : ''}`} onClick={() => setTypeFilter(t)}>{t}</button>")
w("          ))}")
w("        </div>")
w("      </div>")
w()
w("      <div className='agv-fleet-stats'>")
w("        <span>Total: <b>{filteredAGVs.length}</b></span>")
w("        <span>Page {currentPage}/{totalPages}</span>")
w("      </div>")
w()
w("      {/* Table */}")
w("      <div className='agv-table-wrapper'>")
w("        <table className='agv-table'>")
w("          <thead>")
w("            <tr>")
w("              <th onClick={() => toggleSort('id')} className='agv-th-sortable'>AGV ID {sortField === 'id' && (sortDir === 'asc' ? <ChevronUp size={12} /> : <ChevronDown size={12} />)}</th>")
w("              <th>Model</th>")
w("              <th>Type</th>")
w("              <th>Status</th>")
w("              <th onClick={() => toggleSort('batteryLevel')} className='agv-th-sortable'>Battery {sortField === 'batteryLevel' && (sortDir === 'asc' ? <ChevronUp size={12} /> : <ChevronDown size={12} />)}</th>")
w("              <th>Current Task</th>")
w("              <th onClick={() => toggleSort('speed')} className='agv-th-sortable'>Speed {sortField === 'speed' && (sortDir === 'asc' ? <ChevronUp size={12} /> : <ChevronDown size={12} />)}</th>")
w("              <th>Load</th>")
w("              <th>Efficiency</th>")
w("              <th>Warehouse</th>")
w("              <th>Aisle</th>")
w("              <th>Action</th>")
w("            </tr>")
w("          </thead>")
w("          <tbody>")
w("            {paginatedAGVs.map(agv => (")
w("              <tr key={agv.id} className='agv-table-row' style={{ borderLeftColor: statusColor(agv.status) }}>")
w("                <td className='agv-td-id'><Bot size={14} style={{ color: statusColor(agv.status), marginRight: 6 }} />{agv.id}</td>")
w("                <td className='agv-td-model'>{agv.model}</td>")
w("                <td><span className='agv-type-badge'>{agv.type}</span></td>")
w("                <td><span className='agv-status-badge' style={{ background: `${statusColor(agv.status)}20`, color: statusColor(agv.status) }}>{agv.status}</span></td>")
w("                <td>")
w("                  <div className='agv-battery-cell'>")
w("                    <div className='agv-battery-bar-track'><div className='agv-battery-bar-fill' style={{ width: `${agv.batteryLevel}%`, background: batteryColor(agv.batteryLevel) }} /></div>")
w("                    <span className='agv-battery-text' style={{ color: batteryColor(agv.batteryLevel) }}>{agv.batteryLevel}%</span>")
w("                  </div>")
w("                </td>")
w("                <td className='agv-td-task'>{agv.currentTask}</td>")
w("                <td>{agv.speed > 0 ? `${agv.speed} m/s` : '—'}</td>")
w("                <td>{agv.loadWeight > 0 ? `${Math.round(agv.loadWeight)} kg` : '—'}</td>")
w("                <td>")
w("                  <div className='agv-eff-cell'>")
w("                    <div className='agv-eff-bar-track'><div className='agv-eff-bar-fill' style={{ width: `${agv.efficiency}%`, background: agv.efficiency > 80 ? '#22c55e' : agv.efficiency > 50 ? '#f59e0b' : '#ef4444' }} /></div>")
w("                    <span style={{ fontSize: 11 }}>{agv.efficiency}%</span>")
w("                  </div>")
w("                </td>")
w("                <td style={{ fontSize: 11 }}>{agv.warehouse.replace('WH-', '')}</td>")
w("                <td>{agv.aisle}</td>")
w("                <td><button className='agv-view-btn' onClick={() => setSelectedAGV(agv)}><Eye size={14} /></button></td>")
w("              </tr>")
w("            ))}")
w("          </tbody>")
w("        </table>")
w("      </div>")
w()
w("      {/* Pagination */}")
w("      <div className='agv-pagination'>")
w("        <button disabled={currentPage <= 1} onClick={() => setCurrentPage(p => p - 1)} className='agv-page-btn'><ChevronLeft size={16} /></button>")
w("        {Array.from({ length: Math.min(totalPages, 8) }, (_, i) => {")
w("          const p = i + 1")
w("          return <button key={p} className={`agv-page-btn ${currentPage === p ? 'agv-page-active' : ''}`} onClick={() => setCurrentPage(p)}>{p}</button>")
w("        })}")
w("        <button disabled={currentPage >= totalPages} onClick={() => setCurrentPage(p => p + 1)} className='agv-page-btn'><ChevronRight size={16} /></button>")
w("      </div>")
w("    </div>")
w("  )")
w()

# ============================================================
# TAB 2: TASK QUEUE
# ============================================================
w("  // =====================================================")
w("  // TAB 2: TASK QUEUE")
w("  // =====================================================")
w("  const renderTasks = () => (")
w("    <div className='agv-tab-content'>")
w("      <div className='agv-filter-row'>")
w("        <div className='agv-search-box'>")
w("          <input type='text' placeholder='Search task ID, AGV name, type...' value={searchQuery} onChange={e => { setSearchQuery(e.target.value); setTaskPage(1) }} className='agv-search-input' />")
w("        </div>")
w("        <div className='agv-filter-pills'>")
w("          <button className={`agv-pill ${priorityFilter === 'all' ? 'agv-pill-active' : ''}`} onClick={() => setPriorityFilter('all')}>All</button>")
w("          {data.priorities.map(p => (")
w("            <button key={p} className={`agv-pill ${priorityFilter === p ? 'agv-pill-active' : ''}`} style={priorityFilter === p ? { background: priorityBadge(p), borderColor: priorityBadge(p) } : {}} onClick={() => setPriorityFilter(p)}>{p}</button>")
w("          ))}")
w("        </div>")
w("        <div className='agv-filter-pills'>")
w("          <button className={`agv-pill ${statusFilter === 'all' ? 'agv-pill-active' : ''}`} onClick={() => setStatusFilter('all')}>All Status</button>")
w("          {data.taskStatuses.map(s => (")
w("            <button key={s} className={`agv-pill ${statusFilter === s ? 'agv-pill-active' : ''}`} onClick={() => setStatusFilter(s)}>{s}</button>")
w("          ))}")
w("        </div>")
w("      </div>")
w()
w("      <div className='agv-fleet-stats'>")
w("        <span>Total Tasks: <b>{filteredTasks.length}</b></span>")
w("        <span>In Progress: <b>{filteredTasks.filter(t => t.status === 'in_progress').length}</b></span>")
w("        <span>Completed: <b>{filteredTasks.filter(t => t.status === 'completed').length}</b></span>")
w("        <span>Failed: <b>{filteredTasks.filter(t => t.status === 'failed').length}</b></span>")
w("      </div>")
w()
w("      <div className='agv-table-wrapper'>")
w("        <table className='agv-table'>")
w("          <thead>")
w("            <tr>")
w("              <th>Task ID</th>")
w("              <th>AGV</th>")
w("              <th>Type</th>")
w("              <th>Priority</th>")
w("              <th>Status</th>")
w("              <th>Pickup</th>")
w("              <th>Dropoff</th>")
w("              <th>Weight</th>")
w("              <th>Distance</th>")
w("              <th>Est / Actual</th>")
w("              <th>Created</th>")
w("              <th>Action</th>")
w("            </tr>")
w("          </thead>")
w("          <tbody>")
w("            {paginatedTasks.map(task => (")
w("              <tr key={task.id} className='agv-table-row' style={{ borderLeftColor: task.status === 'in_progress' ? '#f97316' : task.status === 'completed' ? '#22c55e' : task.status === 'failed' ? '#ef4444' : '#6b7280' }}>")
w("                <td className='agv-td-id'>{task.id}</td>")
w("                <td style={{ fontSize: 11 }}>{task.agvName}</td>")
w("                <td><span className='agv-type-badge'>{task.type}</span></td>")
w("                <td><span className='agv-status-badge' style={{ background: `${priorityBadge(task.priority)}20`, color: priorityBadge(task.priority) }}>{task.priority}</span></td>")
w("                <td><span className='agv-status-badge' style={{ background: `${statusColor(task.status)}20`, color: statusColor(task.status) }}>{task.status}</span></td>")
w("                <td style={{ fontSize: 11 }}>{task.pickupLocation}</td>")
w("                <td style={{ fontSize: 11 }}>{task.dropoffLocation}</td>")
w("                <td>{Math.round(task.weight)} kg</td>")
w("                <td>{task.distance} m</td>")
w("                <td style={{ fontSize: 11 }}>")
w("                  {task.estimatedTime} min")
w("                  {task.actualTime && <span style={{ color: task.actualTime > task.estimatedTime ? '#ef4444' : '#22c55e' }}> / {task.actualTime} min</span>}")
w("                </td>")
w("                <td style={{ fontSize: 11 }}>{task.created}</td>")
w("                <td><button className='agv-view-btn' onClick={() => setSelectedTask(task)}><Eye size={14} /></button></td>")
w("              </tr>")
w("            ))}")
w("          </tbody>")
w("        </table>")
w("      </div>")
w()
w("      <div className='agv-pagination'>")
w("        <button disabled={taskPage <= 1} onClick={() => setTaskPage(p => p - 1)} className='agv-page-btn'><ChevronLeft size={16} /></button>")
w("        {Array.from({ length: Math.min(totalTaskPages, 8) }, (_, i) => {")
w("          const p = i + 1")
w("          return <button key={p} className={`agv-page-btn ${taskPage === p ? 'agv-page-active' : ''}`} onClick={() => setTaskPage(p)}>{p}</button>")
w("        })}")
w("        <button disabled={taskPage >= totalTaskPages} onClick={() => setTaskPage(p => p + 1)} className='agv-page-btn'><ChevronRight size={16} /></button>")
w("      </div>")
w("    </div>")
w("  )")
w()

# ============================================================
# TAB 3: CHARGING NETWORK
# ============================================================
w("  // =====================================================")
w("  // TAB 3: CHARGING NETWORK")
w("  // =====================================================")
w("  const renderCharging = () => (")
w("    <div className='agv-tab-content'>")
w("      <div className='agv-kpi-grid'>")
w("        <div className='agv-kpi-card' style={{ borderTopColor: '#06b6d4' }}>")
w("          <div className='agv-kpi-icon' style={{ background: '#06b6d415', color: '#06b6d4' }}><Zap size={20} /></div>")
w("          <div className='agv-kpi-body'>")
w("            <span className='agv-kpi-value'>{data.stations.length}</span>")
w("            <span className='agv-kpi-label'>Total Stations</span>")
w("          </div>")
w("        </div>")
w("        <div className='agv-kpi-card' style={{ borderTopColor: '#22c55e' }}>")
w("          <div className='agv-kpi-icon' style={{ background: '#22c55e15', color: '#22c55e' }}><CheckCircle2 size={20} /></div>")
w("          <div className='agv-kpi-body'>")
w("            <span className='agv-kpi-value'>{data.stations.filter(s => s.status === 'online').length}</span>")
w("            <span className='agv-kpi-label'>Online</span>")
w("          </div>")
w("        </div>")
w("        <div className='agv-kpi-card' style={{ borderTopColor: '#f59e0b' }}>")
w("          <div className='agv-kpi-icon' style={{ background: '#f59e0b15', color: '#f59e0b' }}><Battery size={20} /></div>")
w("          <div className='agv-kpi-body'>")
w("            <span className='agv-kpi-value'>{data.stations.reduce((s, st) => s + st.occupiedSlots, 0)}</span>")
w("            <span className='agv-kpi-label'>AGVs Charging</span>")
w("          </div>")
w("        </div>")
w("        <div className='agv-kpi-card' style={{ borderTopColor: '#8b5cf6' }}>")
w("          <div className='agv-kpi-icon' style={{ background: '#8b5cf615', color: '#8b5cf6' }}><Activity size={20} /></div>")
w("          <div className='agv-kpi-body'>")
w("            <span className='agv-kpi-value'>{(data.stations.reduce((s, st) => s + st.efficiency, 0) / data.stations.length).toFixed(1)}%</span>")
w("            <span className='agv-kpi-label'>Avg Efficiency</span>")
w("          </div>")
w("        </div>")
w("      </div>")
w()
w("      {/* Station cards grid */}")
w("      <div className='agv-charging-grid'>")
w("        {data.stations.map(st => {")
w("          const usage = (st.occupiedSlots / st.totalSlots) * 100")
w("          return (")
w("            <div key={st.id} className='agv-station-card' style={{ borderColor: st.status === 'online' ? '#22c55e' : '#f59e0b' }}>")
w("              <div className='agv-station-header'>")
w("                <div className='agv-station-name-row'>")
w("                  <Zap size={16} style={{ color: '#06b6d4' }} />")
w("                  <span className='agv-station-name'>{st.name}</span>")
w("                  <span className='agv-station-status-dot' style={{ background: st.status === 'online' ? '#22c55e' : '#f59e0b' }} />")
w("                </div>")
w("                <span className='agv-station-warehouse'>{st.warehouse.replace('WH-', '')} · {st.zone}</span>")
w("              </div>")
w("              <div className='agv-station-slots'>")
w("                <div className='agv-slot-bar-track'>")
w("                  {Array.from({ length: st.totalSlots }, (_, i) => (")
w("                    <div key={i} className='agv-slot-indicator' style={{ background: i < st.occupiedSlots ? '#06b6d4' : '#1e293b' }} />")
w("                  ))}")
w("                </div>")
w("                <span className='agv-slot-label'>{st.occupiedSlots} / {st.totalSlots} slots</span>")
w("              </div>")
w("              <div className='agv-station-stats'>")
w("                <div className='agv-station-stat'>")
w("                  <Cpu size={14} style={{ color: '#64748b' }} />")
w("                  <span>{st.powerOutput} kW</span>")
w("                </div>")
w("                <div className='agv-station-stat'>")
w("                  <Clock size={14} style={{ color: '#64748b' }} />")
w("                  <span>{st.avgChargeTime} min avg</span>")
w("                </div>")
w("                <div className='agv-station-stat'>")
w("                  <Activity size={14} style={{ color: '#64748b' }} />")
w("                  <span>{st.totalCharges} charges</span>")
w("                </div>")
w("              </div>")
w("              <button className='agv-card-action-btn' onClick={() => setSelectedStation(st)}><Eye size={14} /> View Details</button>")
w("            </div>")
w("          )")
w("        })}")
w("      </div>")
w("    </div>")
w("  )")
w()

# ============================================================
# TAB 4: PATH PLANNING & ALERTS
# ============================================================
w("  // =====================================================")
w("  // TAB 4: PATH PLANNING & ALERTS")
w("  // =====================================================")
w("  const renderPathsAlerts = () => (")
w("    <div className='agv-tab-content'>")
w("      {/* Path routes */}")
w("      <div className='agv-section-header'>")
w("        <MapPinned size={18} style={{ color: THEME.primary }} />")
w("        <h3 className='agv-section-title'>Path Routes ({data.paths.length})</h3>")
w("      </div>")
w("      <div className='agv-path-grid'>")
w("        {data.paths.map(p => {")
w("          const bg = p.status === 'active' ? '#22c55e' : p.status === 'blocked' ? '#ef4444' : '#f59e0b'")
w("          return (")
w("            <div key={p.id} className='agv-path-card' style={{ borderLeftColor: bg }}>")
w("              <div className='agv-path-name'>{p.name}</div>")
w("              <div className='agv-path-meta'>")
w("                <span className='agv-path-status' style={{ background: `${bg}20`, color: bg }}>{p.status}</span>")
w("                <span className='agv-path-detail'>{p.length}m · {p.avgTime} min</span>")
w("                <span className='agv-path-detail'>{p.agvCount} AGVs</span>")
w("                <span className='agv-path-detail' style={{ color: p.trafficLevel === 'high' ? '#ef4444' : p.trafficLevel === 'medium' ? '#f59e0b' : '#22c55e' }}>{p.trafficLevel} traffic</span>")
w("              </div>")
w("              {p.incidents24h > 0 && <div className='agv-path-incidents'><TriangleAlert size={12} style={{ color: '#ef4444' }} /><span>{p.incidents24h} incidents</span></div>}")
w("            </div>")
w("          )")
w("        })}")
w("      </div>")
w()
w("      {/* Alert summary cards */}")
w("      <div className='agv-section-header' style={{ marginTop: 24 }}>")
w("        <AlertTriangle size={18} style={{ color: THEME.danger }} />")
w("        <h3 className='agv-section-title'>Alerts & Diagnostics</h3>")
w("      </div>")
w("      <div className='agv-kpi-grid'>")
w("        <div className='agv-kpi-card' style={{ borderTopColor: '#ef4444' }}>")
w("          <div className='agv-kpi-icon' style={{ background: '#ef444415', color: '#ef4444' }}><XCircle size={20} /></div>")
w("          <div className='agv-kpi-body'>")
w("            <span className='agv-kpi-value'>{data.alerts.filter(a => a.severity === 'critical' && !a.acknowledged).length}</span>")
w("            <span className='agv-kpi-label'>Critical Unack</span>")
w("          </div>")
w("        </div>")
w("        <div className='agv-kpi-card' style={{ borderTopColor: '#f59e0b' }}>")
w("          <div className='agv-kpi-icon' style={{ background: '#f59e0b15', color: '#f59e0b' }}><AlertTriangle size={20} /></div>")
w("          <div className='agv-kpi-body'>")
w("            <span className='agv-kpi-value'>{data.alerts.filter(a => a.severity === 'warning').length}</span>")
w("            <span className='agv-kpi-label'>Warnings</span>")
w("          </div>")
w("        </div>")
w("        <div className='agv-kpi-card' style={{ borderTopColor: '#22c55e' }}>")
w("          <div className='agv-kpi-icon' style={{ background: '#22c55e15', color: '#22c55e' }}><CheckCircle2 size={20} /></div>")
w("          <div className='agv-kpi-body'>")
w("            <span className='agv-kpi-value'>{data.alerts.filter(a => a.acknowledged).length}/{data.alerts.length}</span>")
w("            <span className='agv-kpi-label'>Acknowledged</span>")
w("          </div>")
w("        </div>")
w("      </div>")
w()
w("      {/* Alert list */}")
w("      <div className='agv-alert-list'>")
w("        {data.alerts.map(alert => {")
w("          const sevColor = alert.severity === 'critical' ? '#ef4444' : alert.severity === 'warning' ? '#f59e0b' : '#06b6d4'")
w("          return (")
w("            <div key={alert.id} className='agv-alert-row' style={{ borderLeftColor: sevColor }}>")
w("              <div className='agv-alert-icon' style={{ background: `${sevColor}20`, color: sevColor }}>")
w("                {alert.severity === 'critical' ? <XCircle size={16} /> : alert.severity === 'warning' ? <AlertTriangle size={16} /> : <CheckCircle2 size={16} />}")
w("              </div>")
w("              <div className='agv-alert-body'>")
w("                <div className='agv-alert-title'>{alert.type} — {alert.agvName}</div>")
w("                <div className='agv-alert-msg'>{alert.message}</div>")
w("                <div className='agv-alert-meta'>")
w("                  <span>{alert.timestamp}</span>")
w("                  <span className='agv-alert-value'>Value: {alert.value} / Threshold: {alert.threshold}</span>")
w("                  <span className={`agv-alert-ack ${alert.acknowledged ? 'agv-ack-yes' : 'agv-ack-no'}`}>{alert.acknowledged ? 'ACK' : 'PENDING'}</span>")
w("                </div>")
w("              </div>")
w("            </div>")
w("          )")
w("        })}")
w("      </div>")
w("    </div>")
w("  )")
w()

# ============================================================
# DRAWERS
# ============================================================
w("  // =====================================================")
w("  // AGV DETAIL DRAWER")
w("  // =====================================================")
w("  const renderAGDDrawer = () => {")
w("    if (!selectedAGV) return null")
w("    const a = selectedAGV")
w("    const headerBg = a.status === 'error' ? 'linear-gradient(135deg, #dc2626, #991b1b)' : a.status === 'active' ? 'linear-gradient(135deg, #f97316, #c2410c)' : a.status === 'charging' ? 'linear-gradient(135deg, #06b6d4, #0e7490)' : 'linear-gradient(135deg, #6366f1, #4338ca)'")
w("    return (")
w("      <div className='agv-drawer-overlay' onClick={() => setSelectedAGV(null)} />")
w("      <div className='agv-drawer-panel'>")
w("        <div className='agv-drawer-header' style={{ background: headerBg }}>")
w("          <div className='agv-drawer-header-top'>")
w("            <div className='agv-drawer-header-info'>")
w("              <Bot size={24} className='agv-drawer-header-icon' />")
w("              <div>")
w("                <div className='agv-drawer-title'>{a.id}</div>")
w("                <div className='agv-drawer-subtitle'>{a.name} · {a.model}</div>")
w("              </div>")
w("            </div>")
w("            <button className='agv-drawer-close' onClick={() => setSelectedAGV(null)}><XCircle size={20} /></button>")
w("          </div>")
w("          <div className='agv-drawer-badges'>")
w("            <span className='agv-drawer-badge' style={{ background: `${statusColor(a.status)}30`, color: '#fff' }}>{a.status}</span>")
w("            <span className='agv-drawer-badge' style={{ background: '#ffffff20', color: '#fff' }}>{a.type}</span>")
w("          </div>")
w("        </div>")
w()
w("        <div className='agv-drawer-body'>")
w("          {/* Info grid */}")
w("          <div className='agv-drawer-grid'>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Warehouse</span><span className='agv-drawer-value'>{a.warehouse}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Zone</span><span className='agv-drawer-value'>{a.zone}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Current Aisle</span><span className='agv-drawer-value'>{a.aisle}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Target Location</span><span className='agv-drawer-value'>{a.targetLocation}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Current Task</span><span className='agv-drawer-value'>{a.currentTask}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Assigned To</span><span className='agv-drawer-value'>{a.assignedTo}</span></div>")
w("          </div>")
w()
w("          {/* Battery & Speed cards */}")
w("          <div className='agv-drawer-card-row'>")
w("            <div className='agv-drawer-metric-card'>")
w("              <Battery size={16} style={{ color: batteryColor(a.batteryLevel) }} />")
w("              <span className='agv-drawer-metric-label'>Battery</span>")
w("              <span className='agv-drawer-metric-value' style={{ color: batteryColor(a.batteryLevel) }}>{a.batteryLevel}%</span>")
w("              <div className='agv-drawer-metric-bar'><div style={{ width: `${a.batteryLevel}%`, background: batteryColor(a.batteryLevel) }} /></div>")
w("            </div>")
w("            <div className='agv-drawer-metric-card'>")
w("              <Gauge size={16} style={{ color: THEME.primary }} />")
w("              <span className='agv-drawer-metric-label'>Speed</span>")
w("              <span className='agv-drawer-metric-value'>{a.speed} m/s</span>")
w("              <div className='agv-drawer-metric-bar'><div style={{ width: `${(a.speed / 2.5) * 100}%`, background: '#f97316' }} /></div>")
w("            </div>")
w("            <div className='agv-drawer-metric-card'>")
w("              <Activity size={16} style={{ color: '#22c55e' }} />")
w("              <span className='agv-drawer-metric-label'>Efficiency</span>")
w("              <span className='agv-drawer-metric-value'>{a.efficiency}%</span>")
w("              <div className='agv-drawer-metric-bar'><div style={{ width: `${a.efficiency}%`, background: '#22c55e' }} /></div>")
w("            </div>")
w("          </div>")
w()
w("          {/* Performance stats */}")
w("          <div className='agv-drawer-section-title'>Performance</div>")
w("          <div className='agv-drawer-grid'>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Total Distance</span><span className='agv-drawer-value'>{a.totalDistance.toLocaleString()} m</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Total Tasks</span><span className='agv-drawer-value'>{a.totalTasks.toLocaleString()}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Uptime</span><span className='agv-drawer-value'>{a.uptimeHours}h</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Load / Max</span><span className='agv-drawer-value'>{Math.round(a.loadWeight)} / {a.maxLoad} kg</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Errors (24h)</span><span className='agv-drawer-value'>{a.errorCount24h}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Firmware</span><span className='agv-drawer-value'>{a.firmware}</span></div>")
w("          </div>")
w()
w("          {/* Hardware diagnostics */}")
w("          <div className='agv-drawer-section-title'>Hardware Diagnostics</div>")
w("          <div className='agv-drawer-grid'>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>CPU Usage</span><span className='agv-drawer-value'>{a.cpuUsage}%</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Memory</span><span className='agv-drawer-value'>{a.memoryUsage}%</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Motor Temp</span><span className='agv-drawer-value' style={{ color: a.motorTemp > 65 ? '#ef4444' : '#22c55e' }}>{a.motorTemp}°C</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Lidar</span><span className='agv-drawer-value' style={{ color: a.lidarStatus === 'ok' ? '#22c55e' : '#ef4444' }}>{a.lidarStatus.toUpperCase()}</span></div>")
w("          </div>")
w()
w("          {/* Maintenance */}")
w("          <div className='agv-drawer-section-title'>Maintenance</div>")
w("          <div className='agv-drawer-grid'>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Last Maintenance</span><span className='agv-drawer-value'>{a.lastMaintenance}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Next Maintenance</span><span className='agv-drawer-value'>{a.nextMaintenance}</span></div>")
w("          </div>")
w()
w("          {/* Actions */}")
w("          <div className='agv-drawer-actions'>")
w("            <button className='agv-action-btn agv-action-primary'><Play size={14} /> Start Task</button>")
w("            <button className='agv-action-btn agv-action-secondary'><Pause size={14} /> Pause</button>")
w("            <button className='agv-action-btn agv-action-secondary'><Wrench size={14} /> Maintenance</button>")
w("            <button className='agv-action-btn agv-action-ghost'><RefreshCw size={14} /> Reboot</button>")
w("          </div>")
w("        </div>")
w("      </div>")
w("    )")
w("  }")
w()

w("  // =====================================================")
w("  // TASK DETAIL DRAWER")
w("  // =====================================================")
w("  const renderTaskDrawer = () => {")
w("    if (!selectedTask) return null")
w("    const t = selectedTask")
w("    const headerBg = t.status === 'completed' ? 'linear-gradient(135deg, #22c55e, #15803d)' : t.status === 'failed' ? 'linear-gradient(135deg, #ef4444, #991b1b)' : t.status === 'in_progress' ? 'linear-gradient(135deg, #f97316, #c2410c)' : 'linear-gradient(135deg, #6366f1, #4338ca)'")
w("    return (")
w("      <div className='agv-drawer-overlay' onClick={() => setSelectedTask(null)} />")
w("      <div className='agv-drawer-panel'>")
w("        <div className='agv-drawer-header' style={{ background: headerBg }}>")
w("          <div className='agv-drawer-header-top'>")
w("            <div className='agv-drawer-header-info'>")
w("              <Package size={24} className='agv-drawer-header-icon' />")
w("              <div>")
w("                <div className='agv-drawer-title'>{t.id}</div>")
w("                <div className='agv-drawer-subtitle'>{t.type} · Priority: {t.priority}</div>")
w("              </div>")
w("            </div>")
w("            <button className='agv-drawer-close' onClick={() => setSelectedTask(null)}><XCircle size={20} /></button>")
w("          </div>")
w("          <div className='agv-drawer-badges'>")
w("            <span className='agv-drawer-badge' style={{ background: `${statusColor(t.status)}30`, color: '#fff' }}>{t.status}</span>")
w("            <span className='agv-drawer-badge' style={{ background: '#ffffff20', color: '#fff' }}>{t.agvName}</span>")
w("          </div>")
w("        </div>")
w("        <div className='agv-drawer-body'>")
w("          <div className='agv-drawer-grid'>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>AGV</span><span className='agv-drawer-value'>{t.agvId}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Aisle</span><span className='agv-drawer-value'>{t.aisle}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Pickup Location</span><span className='agv-drawer-value'>{t.pickupLocation}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Dropoff Location</span><span className='agv-drawer-value'>{t.dropoffLocation}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Weight</span><span className='agv-drawer-value'>{Math.round(t.weight)} kg</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Distance</span><span className='agv-drawer-value'>{t.distance} m</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Est. Time</span><span className='agv-drawer-value'>{t.estimatedTime} min</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Actual Time</span><span className='agv-drawer-value'>{t.actualTime ? `${t.actualTime} min` : '—'}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Assigned By</span><span className='agv-drawer-value'>{t.assignedBy}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Created</span><span className='agv-drawer-value'>{t.created}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Started</span><span className='agv-drawer-value'>{t.started}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Completed</span><span className='agv-drawer-value'>{t.completed || '—'}</span></div>")
w("          </div>")
w("          <div className='agv-drawer-actions'>")
w("            <button className='agv-action-btn agv-action-primary'><Play size={14} /> Resume</button>")
w("            <button className='agv-action-btn agv-action-secondary'><RefreshCw size={14} /> Reassign</button>")
w("            <button className='agv-action-btn agv-action-secondary'><Square size={14} /> Cancel</button>")
w("            <button className='agv-action-btn agv-action-ghost'><Eye size={14} /> Track</button>")
w("          </div>")
w("        </div>")
w("      </div>")
w("    )")
w("  }")
w()

w("  // =====================================================")
w("  // CHARGING STATION DETAIL DRAWER")
w("  // =====================================================")
w("  const renderStationDrawer = () => {")
w("    if (!selectedStation) return null")
w("    const st = selectedStation")
w("    return (")
w("      <div className='agv-drawer-overlay' onClick={() => setSelectedStation(null)} />")
w("      <div className='agv-drawer-panel'>")
w("        <div className='agv-drawer-header' style={{ background: 'linear-gradient(135deg, #06b6d4, #0e7490)' }}>")
w("          <div className='agv-drawer-header-top'>")
w("            <div className='agv-drawer-header-info'>")
w("              <Zap size={24} className='agv-drawer-header-icon' />")
w("              <div>")
w("                <div className='agv-drawer-title'>{st.name}</div>")
w("                <div className='agv-drawer-subtitle'>{st.id} · {st.status}</div>")
w("              </div>")
w("            </div>")
w("            <button className='agv-drawer-close' onClick={() => setSelectedStation(null)}><XCircle size={20} /></button>")
w("          </div>")
w("        </div>")
w("        <div className='agv-drawer-body'>")
w("          <div className='agv-drawer-grid'>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Warehouse</span><span className='agv-drawer-value'>{st.warehouse}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Zone</span><span className='agv-drawer-value'>{st.zone}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Status</span><span className='agv-drawer-value' style={{ color: st.status === 'online' ? '#22c55e' : '#f59e0b' }}>{st.status}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Power Output</span><span className='agv-drawer-value'>{st.powerOutput} kW</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Avg Charge Time</span><span className='agv-drawer-value'>{st.avgChargeTime} min</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Total Charges</span><span className='agv-drawer-value'>{st.totalCharges.toLocaleString()}</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Efficiency</span><span className='agv-drawer-value'>{st.efficiency}%</span></div>")
w("            <div className='agv-drawer-field'><span className='agv-drawer-label'>Last Maintenance</span><span className='agv-drawer-value'>{st.lastMaintenance}</span></div>")
w("          </div>")
w("          <div className='agv-drawer-section-title'>Slots ({st.occupiedSlots}/{st.totalSlots})</div>")
w("          <div className='agv-slot-bar-track agv-slot-bar-track-lg'>")
w("            {Array.from({ length: st.totalSlots }, (_, i) => (")
w("              <div key={i} className='agv-slot-indicator agv-slot-indicator-lg' style={{ background: i < st.occupiedSlots ? '#06b6d4' : '#1e293b' }} />")
w("            ))}")
w("          </div>")
w("          <div className='agv-drawer-actions'>")
w("            <button className='agv-action-btn agv-action-primary'><Play size={14} /> Start Session</button>")
w("            <button className='agv-action-btn agv-action-secondary'><Wrench size={14} /> Maintenance</button>")
w("            <button className='agv-action-btn agv-action-ghost'><RefreshCw size={14} /> Diagnostics</button>")
w("          </div>")
w("        </div>")
w("      </div>")
w("    )")
w("  }")
w()

# ============================================================
# MAIN RENDER
# ============================================================
w()
w("  const renderTab = () => {")
w("    switch (activeTab) {")
w("      case 0: return renderDashboard()")
w("      case 1: return renderFleet()")
w("      case 2: return renderTasks()")
w("      case 3: return renderCharging()")
w("      case 4: return renderPathsAlerts()")
w("      default: return null")
w("    }")
w("  }")
w()
w("  return (")
w("    <div className='agv-container'>")
w("      <div className='agv-page-header'>")
w("        <div className='agv-page-title-row'>")
w("          <Bot size={28} style={{ color: THEME.primary }} />")
w("          <div>")
w("            <h1 className='agv-page-title'>AGV Fleet Management</h1>")
w("            <p className='agv-page-subtitle'>Automated Guided Vehicle Fleet Operations · Real-time Monitoring & Control</p>")
w("          </div>")
w("        </div>")
w("        <div className='agv-header-stats'>")
w("          <span className='agv-header-stat'><Bot size={14} />{data.agvs.length} Vehicles</span>")
w("          <span className='agv-header-stat'><Package size={14} />{data.tasks.length} Tasks</span>")
w("          <span className='agv-header-stat'><Zap size={14} />{data.stations.length} Stations</span>")
w("          <span className='agv-header-stat'><AlertTriangle size={14} />{data.alerts.length} Alerts</span>")
w("        </div>")
w("      </div>")
w()
w("      <div className='agv-tabs'>")
w("        {tabs.map((tab, i) => (")
w("          <button key={tab} className={`agv-tab ${activeTab === i ? 'agv-tab-active' : ''}`} onClick={() => { setActiveTab(i); setCurrentPage(1); setTaskPage(1); setStatusFilter('all'); setTypeFilter('all'); setPriorityFilter('all'); setSearchQuery('') }}>")
w("            {tab}")
w("          </button>")
w("        ))}")
w("      </div>")
w()
w("      {renderTab()}")
w()
w("      {renderAGDDrawer()}")
w("      {renderTaskDrawer()}")
w("      {renderStationDrawer()}")
w("    </div>")
w("  )")
w("}")
w()

# ============================================================
# WRITE FILE
# ============================================================
outpath = "/home/z/my-project/src/components/modules/agv-fleet-management-view.tsx"
with open(outpath, "w") as f:
    f.write("\n".join(LINES))

print(f"Generated {len(LINES)} lines → {outpath}")
